### ISSUE TITLE
0.4.24 Setup.

### ISSUE THREAD

**Issue by costa2** [lumapu/ahoy#100]
Im Setup der Weboberfläche kann ich das Intervall nicht mehr ändern, es bleibt nach Änderung bei 30s.
Ist das so gewollt?

**Comment by thinklerde** [comment]
Als schnelle hilfe: 
ändere in der config.h den Wert 
<code>#define MIN_SEND_INTERVAL       30 </code>

auf:
<code>#define MIN_SEND_INTERVAL       5</code>

**Comment by stefan123t** [comment]
@thinklerde ja ich habe die [Default Minimum Werte](https://github.com/grindylow/ahoy/pull/98/commits/d4ba302307b2b6995c2df0a83e4d02ff45bbd08d) mal etwas höher angesetzt um Probleme vor allem bei neuen Nutzern auszuschließen. Wer seinen Inverter häufiger abfragen will/muss, kann das ja wie Du beschrieben hast in der config.h jederzeit anpassen.

**Comment by mslookup** [comment]
Hallo @stefan123t,
ich frage meine Wechselrichter auch in einem 5-Sek.-Turnus ab und habe mich das selbe wie @thinklerde nach dem Update gefragt. Das mit der Config Option ist schnell erledigt und hat bei mir funktioniert - danke für den Hinweis!

Meiner Meinung nach können wir das MIN_SEND_INTERVAL default-mäßig ruhig auf 10 setzen. Bei der Anzahl von 3 Wechselrichtern in der default-Einstellung sollte das der ESP8266 doch verkraften können? Versteh mich nicht falsch, aber ich glaub neue Nutzer (worunter ich mich auch zähle) stolpern eher drüber, dass Sie diese Einstellung nicht kleiner als 30 setzen können.

EDIT: Vielleicht wäre auch möglich, das SEND_INTERVAL default auf 30 zu stellen, das MIN_SEND_INTERVAL aber auf z.B. 5 zu setzen. Dann haben alle neuen Nutzer erstmal 30, man kann aber das Sendeinterval manuell im Webinterface runtersetzen, ohne neu-kompilieren und flashen und so.

**Comment by stefan123t** [comment]
@mslookup ja prinzipiell gebe ich Dir recht, wenn man nur 3 WR hat, dann kann man das `MIN_SEND_INTERVAL` auch auf 6-12 Sekunden runtersetzen. Im Hoymiles Code werden teilweise zwei Sekunden als max. Wartezeit auf die Antwortpakete definiert.

Es gab bis jetzt noch keinen `SERIAL/MQTT/SEND_INTERVAL` default Wert. Habe das mal so eingebaut ... also die MIN Werte in die `defines.h` verschoben und in der `config.h` die Default Werte vorgegeben. Ich habe mal auf 15 Sekunden `MIN_SEND_INTERVAL` gestellt. Das sind dann `4x60*24=5760` mögliche Werte/Abfragen am Tag, da ist der Wechselrichter besser überwacht als so mancher Server. Bei 5 Sekunden Intervall wären das sogar `17280` Abfragen pro Wechselrichter!

**Comment by stefan123t** [comment]
@costa2 können wir das Issue schließen ?
