### ISSUE TITLE
Yieldday reset auf 0 trotzt fehlendem Haken bei Stop Polling

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#1002]
Hallo zusammen,
ist gestern durch Zufall aufgefallen.
Eine Gewitterfront hat den Himmel so verdunkelt, dass der Yieldday sich resetet hat,obwohl der Haken nicht gesetzt ist. Version 05.92
Nach dem Gewitter produzierte die Anlage wieder, aber halt mit genullten Zähler. Stromausfall hatte ich nicht.

**Comment by knickohr** [comment]
Siehe Issue #848
