### ISSUE TITLE
[Question] nRF modul nicht erkannt 

### ISSUE THREAD

**Issue by nwrozyna** [lumapu/ahoy#1006]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [X] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

nothing changed since installation (only WIFI settings)
![MicrosoftTeams-image (21)](https://github.com/lumapu/ahoy/assets/43931767/cdadfc5d-f347-456c-a03c-ccf317fe503a)
![MicrosoftTeams-image (22)](https://github.com/lumapu/ahoy/assets/43931767/7140776c-406d-48bd-8f42-a9355911075e)
![MicrosoftTeams-image (23)](https://github.com/lumapu/ahoy/assets/43931767/552326c8-253a-4365-97b7-953abe47cfef)
![MicrosoftTeams-image (24)](https://github.com/lumapu/ahoy/assets/43931767/37c14d95-63c6-4300-80f0-b64cf8d75ee2)

### Error description

It sais **your NRF24 module can't be reached, check the wiring and pinout** but I don't know why

**Comment by Ollipop030** [comment]
Schwarz weiß und gelb am ESP sehen irgenwie falsch aus. Kuck mal hier:
https://ahoydtu.de/img/fritzing/AhoyWemos_Steckplatine.jpg

Bist um einen Pin verrutscht.

**Comment by Ollipop030** [comment]
Und dein NRF ist genau verkehrt herum verkabelt. In der Skizze ist Platine von oben abgebildet, deine Header am NRF sind aber auf der Rückseite.

**Comment by nwrozyna** [comment]
Danke!! Leider immer noch nicht so richtig erfolgreich :( 

![MicrosoftTeams-image (27)](https://github.com/lumapu/ahoy/assets/43931767/d3148838-903d-4aef-9b62-dcdd29d7914f)
![MicrosoftTeams-image (26)](https://github.com/lumapu/ahoy/assets/43931767/f75c89a7-eb8f-4b45-b24c-89fab7eabaf9)
![MicrosoftTeams-image (25)](https://github.com/lumapu/ahoy/assets/43931767/84696459-2429-4593-920a-8a236888dccd)

**Comment by rmayergfx** [comment]
Bitte in Zukunft einen passenden Titel wählen. BUG kann alles sein.
Hat das Setup denn überhaupt schon einmal funktioniert?
Bitte mal Screenshots vom Setup Settings>Systemconfig und System einstellen.

Weitere Infos zur Verkabelung und Hilfestellung gibt es hier: https://github.com/lumapu/ahoy/issues/36

**Comment by nwrozyna** [comment]
Sorry, hatte das Titelfeld nicht als editierbar wahrgenommen. Bin noch neu.

Das Setup hat nicht funktioniert und das gleiche Problem tritt auch bei einem zweiten Bausatz (gleiche Module, gleich verkabelt) auf.

Hier einmal die Screenshots

![image](https://github.com/lumapu/ahoy/assets/43931767/da502f85-a8cc-4ae6-afdc-2a5090b7ada5)
![image](https://github.com/lumapu/ahoy/assets/43931767/0b7d5791-9658-42a7-828f-579dcf7efc42)

**Comment by rmayergfx** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/105392164/9394dd85-1d14-447d-a212-fec0eca5301c)
Passt nicht zu dem was der Entwickler gepostet hat. Strom abziehen und neu verkabeln, dann Settings anpassen!
Modul ist diese hier? https://www.makershop.de/plattformen/d1-mini/wemos-d1-mini/

Alternativ diese Konfig probieren:
![grafik](https://github.com/lumapu/ahoy/assets/105392164/62f971cf-2a07-42fc-97af-628985d97df0)


!!! WICHTIG !!!
Vor jeglicher Änderung der Hardware das Modul immer stromlos machen und kurz warten!
Nach Änderung nicht vergessen das Pinout anzupassen.

**Comment by kiu77** [comment]
Außerdem: Wenn das Modul einmal verpolt wurde (+3V3 und GND vertauscht, kann es defekt sein.
Man sollte die Verkabelung mehrfach prüfen, bevor man die DTU einsteckt - vor allem, wenn man noch nie etwas mit Elektronik vorher gemacht hat.
Man kann ja dazu sagen, dass es sich kein Bug ist, weil es bei sehr vielen Anderen läuft, sondern dass ein Verdrahtungsproblem vorliegen muss.

**Comment by lumapu** [comment]
gibt es einen aktuellen Stand?

**Comment by nwrozyna** [comment]
Hab es noch mehrfach versucht - auch mit leicht adaptierten Steckverbindungen. Ich fürchte, dass ich die Boards ggf. kaputt gemacht habe. 
Hab mir auf jeden Fall einen DTU bei eBay bestellt und ein anderer Bastler freut sich. 

Danke euch für eure Unterstützung.
