### ISSUE TITLE
Your NRF24 module can't be reached, check the wiring, pinout and enable.But NRF24 is disabled

### ISSUE THREAD

**Issue by Sascha27** [lumapu/ahoy#1007]
My Error is :
Your NRF24 module can't be reached, check the wiring, pinout and enable.

But NRF24 is disabled and CMT2300A is Enabled and Working
What´s wrong

Installed V 0.7.6

**Comment by lumapu** [comment]
that you use a developer version where this was not fixed for now. Thank you for the hint.

**Comment by Sascha27** [comment]
Is it not fixed since 0.7.3 ?
I thought it was fixed since 0.7.3

⁣BlueMail for Android herunterladen ​

**Comment by dtuuser** [comment]
Bei mir sind es zwei fehlende Bauteile. Bevor ich da  Lötzinbrücken reingebraten habe, war das Modul nicht erreichbar. Dann ist mir beim Vergleichen aufgefallen, dass die beiden SMD Bauteile fehlen.
Weiß jemand, was da fehlt? 
Mit Brücken ist es erreichbar,  aber empfängt keine Daten.

![20230707_211005](https://github.com/lumapu/ahoy/assets/121714422/704d092d-6899-4c24-8f49-a37651e55165)
