### ISSUE TITLE
Development changelog in firmware

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#1017]
Development firmware links on the device homepage
![grafik](https://github.com/lumapu/ahoy/assets/105392164/ac202b2a-2826-4ee5-81eb-9de0e91227ff)
to 
https://github.com/lumapu/ahoy/blob/main/src/CHANGES.md
but should be
https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md

**Comment by rmayergfx** [comment]
@lumapu 
can you change this for development firmware?

**Comment by lumapu** [comment]
can think about it, hopefully I don't forget it while publishing a new release which then points to development 😄 - there must be some automatism

**Comment by lumapu** [comment]
just now I saw that the development Changelog has a link a few lines below 😀

**Comment by lumapu** [comment]
I don't see that this will implemented in near future - will close.
