### ISSUE TITLE
Keine Verbindung zu Wechselrichter ohne Internet

### ISSUE THREAD

**Issue by querys1** [lumapu/ahoy#1019]
## Hardware
  * [ X] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [X ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [X ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.5.66
Github Hash: _______

### Build & Flash Method:
* [ X] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hallo zusammen,
bei mir war jetzt mal wieder einige Tage kein Internet, da die DSL Leitung durch einen Bagger vom Glasfaserausbau abgerissen wurde.
Hierbei fiel mir mal wieder auf, dass sich die Ahoy DTU nicht mit den Wechselrichtern verbinden kann, auch mit der Verbindung zum MQTT gibt es Probleme. Wenn man 1x am Tag eine Internetverbindung hatte, dann läuft das ganze bis zum Abend durch.
Hat jemand eine Idee woran das liegt? Die Wechselrichter produzieren jedenfalls normal weiter.

**Comment by knickohr** [comment]
![IMG_0979](https://github.com/lumapu/ahoy/assets/63048210/54001fc5-60c0-4876-8f11-a6cb035c3435)

**Comment by querys1** [comment]
Danke dir, der Time Sync war durchaus vorhanden, den kann ich ja vom Handy aufspielen. Aber ich probier die Version mal aus, sobald sie verfügbar ist.

**Comment by knickohr** [comment]
Sie ist verfügbar !

https://github.com/lumapu/ahoy/suites/14089703442/artifacts/787901415

**Comment by querys1** [comment]
Danke direkt ausprobiert, das mit der dev-Version kannte ich nicht. Läuft so unkompliziert wie vorher. 
Mal sehen wann das nächste mal die Internetverbindung gekappt wird. Zwei Straßen weiter haben die 4x die Leitung getrennt.

**Comment by rmayergfx** [comment]
Kleiner TIP zu NTP:
![grafik](https://github.com/lumapu/ahoy/assets/105392164/8e910a11-b318-4483-9a55-9043d9b35345)
Hier habe ich den DE Pool eingetragen. Wenn man allerdings öfters ein Problem mit dem Internet hat, so stellt man hier bei NTP die IP z.B. des Routers ein, der sollte immer online sein und liefert die Zeit auch wenn kein Internet vorhanden ist. Es geht natürlich auch jedes andere System das NTP im Hausnetz zur Verfügung stellen kann, z.B. NAS etc, sofern die Dienste aktiv sind und das Gerät immer online ist.

@lumapu 
Kannst du bitte noch ein Feld bei NTP einfügen, um den Zeitsync zu definieren, d.h. wie oft er gemacht wird?

**Comment by querys1** [comment]
Sehr guter Tipp! Danke! Auf die Idee bin ich noch nicht gekommen.
