### ISSUE TITLE
0.7.10 DTU sendet nur noch FWVersion des ersten Invertes, aber sonst keine Werte

### ISSUE THREAD

**Issue by MiniOh** [lumapu/ahoy#1022]
## Hardware
  * [ ] ESP8266
  * [X] ESP32
  * [ ] Raspberry Pi

Hallo, 

in der 0.7.10 ist es bei mir so, dass mehere tausend Hardware Werte pro Minute (FWVersion, FWBuildYear....) des ersten Inverters per MQTT gesendet werden, sonst aber werden keine Werte mehr versendet.

Ist das bereits bekannt?

**Comment by edw00d4711** [comment]
ESP32
Kann ich bestätigen. Bin zurück auf 0.7.5. Daten kommen wieder.

**Comment by KoLSMS** [comment]
Kann ich auch bestätigen...

Gruß ...

**Comment by lumapu** [comment]
ja ist bekannt und wird in den nächsten Minuten behoben 😀

**Comment by lumapu** [comment]
fixed in `0.7.11`
