### ISSUE TITLE
Update von 5.66 auf höher geht nicht

### ISSUE THREAD

**Issue by kuttek** [lumapu/ahoy#1024]
## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Moin,

wie schon in der Überschrift steht geht ein Update auf 0.6.0 oder 0.6.9 leider nicht update wird angestoßen mit 
Passenden zip läuft durch und nach Neustart ist immer noch die 0.5.66 drauf, es kommt keine Fehlermeldung oder was
anderes die Übersicht geht einfach nach ca. 30 sec  in nicht erreichbar beim neuen einloggen dann alles wieder wie davor
keine Änderung auf 0.6.0 oder 0.6.9.

**Comment by Ollipop030** [comment]
Moin,

hast du die *.zip auch vorher entpackt?

**Comment by kuttek** [comment]
Klar doch ist zwar Warm hier aber sooo Warm ist es doch nicht ...hehe
Habe jetzt mal die Prometheus genommen und parallel dazu im Browser noch ein Paar Einstellungen zugelassen und Schwups ging es kann jetzt nicht sagen welches der beiden Sachen gewirkt hat.
Die Prometheus kann auch genutzt werden wenn man das nicht nutzt? 

Ok Nachtrag habe eben mal versucht die "nicht" Prometheus 0.6.9 zu updaten ging nicht also lags wohl an der Version (oder downgrade geht nicht) was ich so aber nicht verstehe warum sollte die Normal Version nicht laufen.

**Comment by knickohr** [comment]
Wer solche Versionssprünge macht sollte komplett neu flashen und vorher erasen.

**Comment by rmayergfx** [comment]
@knickohr 
Stimme ich soweit zu, aber man sollte vorher auf jeden Fall ein Backup seiner Settings machen. Sinnvollerweise auch noch ein paar Screenshots von den eigenen Einstellungen. Dann einfach über Homepage mit dem Webinstaller https://ahoydtu.de/web_install/ die aktuelle Stable einspielen.

**Comment by knickohr** [comment]
Das Backup wird Dir unter Umständen auch nix helfen. Auch da wurde einiges geändert.

**Comment by rmayergfx** [comment]
Die wichtigsten Eckdaten kann man  aus dem ahoy_setup.json mit jedem Texteditor auslesen, egal ob sich die Version geändert hat oder nichts.  Besser als kein Backup und man muss sich alles erst wieder zusammensuchen. Ich lege mir für jede Version ein Backup mit Datum und Versionsnummer ab, sicher ist sicher.

@lumapu 
Könntest du bitte beim Export der Settings per default Datum_Uhrzeit und Versionsnummer mit einpflegen?
z.B.
2023.07.13_20-24-12_v0.7.11_ahoy_setup.json
