### ISSUE TITLE
MQTT HomeAssistant Autodiscover nicht durchgängig / Erweiterung um Info zu Hersteller, Modell möglich?

### ISSUE THREAD

**Issue by fila612** [lumapu/ahoy#104]
Hallo,

Ich habe voller Freude die Änderung in #85 gesehen und konnte es schon nutzen.
Leider gibt es derzeit damit mehrer "Problemchen", aber erstmal als Frage formuliert, da ich nicht ausschließen kann, dass der Fehler evtl. vorm Rechne sitzt.

1) ich habe mehrere MQTT Geräte, auch von Topic HomeAssisten (Autodiscover). Der Anteile Ahoy ist aber nicht mehr in der Ordnerstruktur von HA zu finden, sondern außerhalb und ohne Ordnername:
![Bildschirmfoto 2022-07-14 um 09 45 03](https://user-images.githubusercontent.com/29542374/178929569-fde719d9-1ff4-409a-97e5-f4403ab05894.png)
=> Zu Beginn erschien der HM-700 auch im Bereich "homeassistant".

2) Die Werte in HA sind sporadisch als nicht verfügbar dargestellt, auch kann ich die Abfragezeiten im SetupTeil der Ahoy GUI nicht mehr ändern (Aktuell bei 4.25 ist dies fest auf 75s eingestellt). 

3) Nice to Have:
Könnte man die MQTT Daten um die Werte Hersteller und Modell (idealeweise aus den Feldern im Setup) ergänzen. Aktuell steht da bei mir im HA jeweils "unknown".

Falls ich etwas vergessen haben sollte oder noch logs, etc. gebraucht werden hänge ich diese gern an.

Besten Dank schon mal vorab

Und: Tolle Arbeit an alle Beteiligten :) DANKE

**Comment by fila612** [comment]
Ich habe nun den WemosD1 als auch den MQTT-Broker einmal rebootet.
Jetzt bekomme ich die Infos doppelt, ich habe jedoch KEIN Topic in dem Setup eingetragen:
![Bildschirmfoto 2022-07-14 um 10 05 35](https://user-images.githubusercontent.com/29542374/178933534-92dc5a5b-415b-4af6-a188-2a90300e8d33.png)

Ist das so gewollt bzw. richtig oder mach ich hier etwas falsch?
Ich vermute, dass der untere Teil (ohne Hauptordner) derjenige ist, welche ohne HA Autodiscover published wird.
Der Anteil im Ordner "homeassistant" ist derjenige, welcher ab #85 möglich ist.
Sollte man hier nicht eine entweder oder Funktion in der GUI hinterlegen?
Interessant sind auch die unterschiedlichen Quantitäten an Meldungen. (siehe die Werte in Klammern).

**Comment by fila612** [comment]
Nach über 2h werden wieder keine "HA-Relevanten" MQTT Werte übertragen. auch im HA werden die Entitäten dann als nicht verfügbar angezeigt, hier mal am Beispiel der AC-Leistung:
![Bildschirmfoto 2022-07-14 um 14 22 24](https://user-images.githubusercontent.com/29542374/178981242-511bdcb9-5e57-4547-8320-f40c280495e3.png)
.
Die Lücke basierte auf dem ursprünglich beschriebenen Verhalten, der gerade Strich rechts ist der Wegfall nach 2h von eben.

**Comment by stefan123t** [comment]
@KG3RK3N Kai hatte das Feature implementiert. Vielleicht kann er etwas zu Deinem Problem beitragen, bzw. Tipps für das weitere Debugging geben ?

**Comment by fila612** [comment]
Das wäre super.

was mir ergänzend noch aufgefallen ist:
Die Messages für den HO-Autodiscover werden aus meiner Sicht nur einmal an den MQTT-Server geschickt (kann man durch Reboot triggern).
Ich habe neben der AHOY auch noch Zigbee2Mqtt am laufen, welchen ebenfalls eine HA-Integration besitzt.

Wenn ich nun mit einem MQTT-Tool auf den Broker schaue, sehe ich den Zigbee2Mqtt Anteil für HA sofort, aber den AHOY-Anteil für HA nur dann, wenn ich (während das Tool mit dem Broker verbunden ist) Den Wemos neustarte.
Irgendwie muss es da unterschiede geben. -ich bin aber technisch leider nicht begabt um da selbst zu korrigieren.

**Comment by KG3RK3N** [comment]
@fila612 

1. Das macht für mich so keinen Sinn, der "Ordner" (HM-700) könnte nur dann im homeassistant Ordner sein wenn auch der MQTT Topic entsprechend gesetzt wurde.
2. Mir ist auch schon aufgefallen, das es in der neusten Version nicht mehr möglich ist das Interval anzupassen übers Setup. Ich habe es so implementiert, das die Werte nach MQTT-Interval + 5s ablaufen. Dort habe ich allerdings auch schon festgestellt, das es sehr knapp bemessen ist. Hier würde ich das auf MQTT-Interval * 2 umstellen, das sollte deutlich unproblematischer sein.
3. Jap, werde ich die Tage mal ergänzen.



> Ich habe nun den WemosD1 als auch den MQTT-Broker einmal rebootet. Jetzt bekomme ich die Infos doppelt, ich habe jedoch KEIN Topic in dem Setup eingetragen: ![Bildschirmfoto 2022-07-14 um 10 05 35](https://user-images.githubusercontent.com/29542374/178933534-92dc5a5b-415b-4af6-a188-2a90300e8d33.png)
> 
> Ist das so gewollt bzw. richtig oder mach ich hier etwas falsch? Ich vermute, dass der untere Teil (ohne Hauptordner) derjenige ist, welche ohne HA Autodiscover published wird. Der Anteil im Ordner "homeassistant" ist derjenige, welcher ab #85 möglich ist. Sollte man hier nicht eine entweder oder Funktion in der GUI hinterlegen? Interessant sind auch die unterschiedlichen Quantitäten an Meldungen. (siehe die Werte in Klammern).

Richtig, der Teil ohne Ordner ist der Teil ohne das auto discovery, das habe ich bewusst so erhalten damit bestehende Konfiguration weiterhin funktionieren. Das die Messages ohne Hauptordner kommen liegt daran, weil keine Abfrage implementiert ist ob dieser Wert gesetzt ist. Sollte man durchaus abfangen.

Auf dem folgenden Bild siehst du eine Discovery Config Message die im home assistant Ordner abgelegt wird. Diese werden nur einmalig verschickt damit der Broker nicht unnötiger weise zugespamt wird und es auch den ESP etwas entlastet. Zusätzlich dazu kann man sehen, das der state auf den anderen Ordner verweist, wo dann der tatsächliche Wert ist wodurch das erneute Senden der Config entfällt und die tatsächlichen Werte nicht mehrfach herausgegeben werden. Home Assistant greift dadurch dann ebenfalls auf die bereits vorhandene MQTT Implementierung zu.
![image](https://user-images.githubusercontent.com/16717995/179402377-d06cd58c-86ab-4e0c-9521-6f03022422fc.png)



> Nach über 2h werden wieder keine "HA-Relevanten" MQTT Werte übertragen. auch im HA werden die Entitäten dann als nicht verfügbar angezeigt, hier mal am Beispiel der AC-Leistung: ![Bildschirmfoto 2022-07-14 um 14 22 24](https://user-images.githubusercontent.com/29542374/178981242-511bdcb9-5e57-4547-8320-f40c280495e3.png) . Die Lücke basierte auf dem ursprünglich beschriebenen Verhalten, der gerade Strich rechts ist der Wegfall nach 2h von eben.

Da diese Werte wie vorher beschrieben nicht über die Discovery Config übertragen werden, würde ich es jetzt erstmal noch nicht auf die Auto Discovery funktion schieben. Vlt. könntest du ja mal schauen, wann die letzte Message von den tatsächlichen Werten übertragen wurde. War der Broker vlt. kurzzeitig nicht erreichbar? Mehrere Benutzer haben hier #106 bereits Probleme bestätigt.

Leider habe ich meinen ESP noch nicht im Dauereinsatz, ordentliches Netzteil kommt aber Anfang der Woche hoffentlich und dann sehen wir mal welche Krankheiten der kleine noch hat 😄

**Comment by stefan123t** [comment]
@KG3RK3N Hallo Kai,
> Mir ist auch schon aufgefallen, das es in der neusten Version nicht mehr möglich ist das Interval anzupassen übers Setup. Ich habe es so implementiert, das die Werte nach Interval + 5s ablaufen. Dort habe ich allerdings auch schon festgestellt, das es sehr knapp bemessen ist. Hier würde ich das auf Interval * 2 umstellen, das sollte deutlich unproblematischer sein.

Das Abfrage Interval habe ich (mit PR #102 bzw. in #100 und #88) mit 30 Sekunden so angepaßt, damit es nicht zu niedrig angesetzt wird (>15 s) und evtl. mehrere WR parallel antworten, was dann den ESP8266 beim Zusammensetzen der Antwort (Payload) durcheinander bringen würde. 
In der Hoymiles DTU-PRO ist das Intervall für die Leistungsbegrenzung übrigens auch auf 15 Sekunden vorbelegt. 
Es sollte sich aber nach wie vor anpassen lassen über das Setup ? 

Oder ist das, was Du meinst das MQTT Intervall, das i.d.R. an das aktuelle Intervall der WR gekoppelt ist / sein sollte (mehr Datenpunkte zu senden als vom WR empfangen wurden macht ja auch keinen Sinn), daher hat das Lukas dementsprechend ebenfalls gekoppelt ?

**Comment by KG3RK3N** [comment]
@stefan123t Ich müsste es nochmal prüfen, hab's nicht mehr exakt in Erinnerung wie es war. Ich denke Mal der Fehler war vor dem Bildschirm und ich hab einfach einen zu kleinen Wert versucht weshalb es nicht geklappt hat. 😄 

Ne, macht schon Sinn das es gekoppelt ist.

PS: hab's oben nochmal editiert, für das Expire für Home Assistant wird das MQTT-Interval berücksichtigt.

**Comment by fila612** [comment]
Hallo @KG3RK3N,

Danke für deine ausführlichen Antworten.
Ich habe nun selbst in den letzten Tagen etwas weiter beobachten und getestet.

1. den Hersteller & Modell habe ich in der app.cpp (in 4.25 ab Zeile 900) im Bereich "deviceDoc" ergänzt:
` deviceDoc["mf"] = "Hoymiles";
   deviceDoc["mdl"] = iv->name;'
   
2. Was mir aufgefallen ist: Wenn ich den HA Neustarten muss, z.B. wenn ich an der HA-configurations.yaml schraube, findet der HA leider den WR nicht mehr, da das Autodiscover nicht mehr via MQTT gesendet wird. Ich musste immer den Wemos Neustarten, damit er die Daten wieder hat. Parallel habe ich auch Zigbee2Mqtt, da sind die HA-Autodiscover immer da (prüfe das mit einem MQTT-Explorer Tool).

3. bzgl. der Intervalle: Ich glaub ich verstehe die einzelnen Punkte im Setup bzw. auch im Code noch nicht ganz:
a) im Setupbereich MQTT gibt es die letzte Zeile "Interval [s] (read-only)", welche derzeit den default-Wert 75 hat. ich vermute (Tuch Beaobachtungen), dass dies der Zyklus ist, indem MQTT Daten published werden.

b) in der "config.h" gibt es "#define MQTT_INTERVAL" => aktuell von mir auf 10 gestellt
c) in der "defines.h" gibt es "#define MIN_MQTT_INTERVAL"=> aktuell von mir auf 10 gestellt

=> nun habe ich in dem Feld aus a) einen Wert von 20....hm


Wie gesagt, ich bin fürs coden nicht die Idealbesetzung (eher T&E), schaue aktuell mehr aus testen und beobachten.
Ich denke, dass in diesem Issue der Punkt 2 aus diesem Kommentar aus meiner Sicht am ehesten geprüft werden sollte. Kann man je selbst einfach bei sich testen (der Wemos sollte aber eine Zeit lang schon laufen).

Ich danke euch schon mal. :)

**Comment by fila612** [comment]
> Da diese Werte wie vorher beschrieben nicht über die Discovery Config übertragen werden, würde ich es jetzt erstmal noch nicht auf die Auto Discovery funktion schieben. Vlt. könntest du ja mal schauen, wann die letzte Message von den tatsächlichen Werten übertragen wurde. War der Broker vlt. kurzzeitig nicht erreichbar? Mehrere Benutzer haben hier #106 bereits Probleme bestätigt.
> 
Kann ich eigentlich ausschließen, da anderen Werte (Zigbee2Mwtt) durchgehend übertragen wurden. Daher würde ich für mein Issue den Broker nicht als Ursache sehen. Ich konnte es ja lösen, in dem ich den Wemos neustartete. Dann waren die Autodiscover-Einträger wieder da und die Daten in HA auch.

**Comment by KG3RK3N** [comment]
> 1. den Hersteller & Modell habe ich in der app.cpp (in 4.25 ab Zeile 900) im Bereich "deviceDoc" ergänzt:
>    ` deviceDoc["mf"] = "Hoymiles";
>    deviceDoc["mdl"] = iv->name;'

Sieht schon mal grundsätzlich gut aus, allerdings denke ich das iv->name hier nicht angebracht ist da es ja der selbst gewählte Name ist und nicht das tatsächliche Model. Bedeutet, wenn ich da "Inverter 1" eintrage würde das auch im Model stehen. Da wir bereits das Model erkennen können anhand der S/N würde ich das eher darüber machen. Zusätzlich was auch wichtig ist das die größe von doc und der maximalen MQTT Message Length angepasst wird, da es sonst dazu kommen kann das ArduinoJson Werte nicht mehr mit rein nimmt und dadurch welche fehlen. Aktuell liegt er bei 384. ArduinoJson hat auch einen Online Kalkulator wo du einfach mal eine Message angeben kannst, um den idealen Wert + etwas spielraum zu ermitteln.


> 2\. Was mir aufgefallen ist: Wenn ich den HA Neustarten muss, z.B. wenn ich an der HA-configurations.yaml schraube, findet der HA leider den WR nicht mehr, da das Autodiscover nicht mehr via MQTT gesendet wird. Ich musste immer den Wemos Neustarten, damit er die Daten wieder hat. Parallel habe ich auch Zigbee2Mqtt, da sind die HA-Autodiscover immer da (prüfe das mit einem MQTT-Explorer Tool).

Guter Punkt den ich so nicht getestet habe, werde ich mal ausprobieren wie es sich verhält. Allerdings müsstest du mal schauen ob im MQTT die Werte (nicht Discovery Config) überhaupt nach einem Neustart gesendet werden, den das sind eigentlich die Werte worauf HA nun schaut. Werden diese nicht mehr verschickt, wird in HA der Wert als unbekannt bzw. nicht verfügbar gekennzeichnet. Bei mir ist es scheinbar so, das Ahoy grundsätzlich Probleme hat mit dem reconnect. Wo wir dann wieder bei #106 landen würden. Genaure Analyse erfolgt aber noch meiner seits was da los ist. 

Nachtrag: 


> Kann ich eigentlich ausschließen, da anderen Werte (Zigbee2Mwtt) durchgehend übertragen wurden. Daher würde ich für mein Issue den Broker nicht als Ursache sehen. Ich konnte es ja lösen, in dem ich den Wemos neustartete. Dann waren die Autodiscover-Einträger wieder da und die Daten in HA auch.

Das meine ich so nicht, der Broker selbst wird nicht das Problem sein. Aber wenn er bspw. kurzzeitig nicht erreichbar ist wegen nem Neustart oder bspw. ein Backup und deshalb die Verbindung abreist, muss ahoy sich ja reconnecten. Allerdings scheinen wir genau da ein Problem zu haben.

**Comment by KG3RK3N** [comment]
Um es vlt. ein wenig besser auf den Punkt zu bringen, ich versuche gerade heraus zu finden ob es tatsächlich das Auto Discovery ist, weil es nur einmalig versendet wird oder ob es an den tatsächlichen Werten liegt welche vlt. nicht mehr verschickt werden weil der reconnect nicht funktioniert.

**Comment by fila612** [comment]
Verstehe, ich teste das jetzt nochmal genau, aber meine bisherigen Beobachtungen deuten auf den Autodiscover hin, weil:
a) die "normalen" Werten kommen durch AHOY weiter an
b) der Autodiscover ist nicht mehr vorhanden, weil die Message zu alt und "retained" ist (ich sehe sie auch nicht mehr im MQTT-Tool)

Wenn ich nun den HA Neustarte kann er die "normalen" Werte nicht mehr zuordnen bzw. zeigt an, dass das Gerät nicht verfügbar ist.
Die Verbindung von AHOY zu MQTT bleibt ja bei einen Restart von HA unberührt, daher sehe ich aktuell noch keinen Zusammenhang zu #106.

**Comment by KG3RK3N** [comment]
Gut, dann müssen wir es abändern das bei jedem connect/reconnect die Config erneut gesendet wird.

**Comment by KG3RK3N** [comment]
Was du mal machen kannst, nur um das zu bestätigen und zum Testen einfach mal die Bedingung abändern und das `&& mMqttConfigSendState[id] != true` entfernen https://github.com/grindylow/ahoy/blob/6dba1d757707426e1c8ff0c4d9d2ce5d22d6f26a/tools/esp8266/app.cpp#L899 

Das würde dazu führen, das er bei jedem MQTT Interval die Config erneut sendet. Würde ich allerdings nur so zum Testen mal machen, final sollte es beim connect/reconnect ausgeführt werden damit wir die config nicht in jedem Interval verschicken.

**Comment by wenzlaff** [comment]
Für diese Art von Nachrichten (Auto discovery) sollte das sogenannte "retain flag" gesetzt werden, das sorgt dafür dass die letzte jeweils die letzte Message in dem Topic im Mqtt Broker verbleibt. 
Mehr Infos z.B. hier: https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/

**Comment by KG3RK3N** [comment]
@wenzlaff Ah, danke für den Hinweis. Wird ausprobiert 👍

**Comment by fila612** [comment]
> Für diese Art von Nachrichten (Auto discovery) sollte das sogenannte "retain flag" gesetzt werden, das sorgt dafür dass die letzte jeweils die letzte Message in dem Topic im Mqtt Broker verbleibt.
> Mehr Infos z.B. hier: https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/

ich glaube das ist die Lösung :)
Falls ich es schaffe und es nicht zu komplex ist, könnte ich mal einen Versuch wagen und testen. Falls jemand da schneller ist und mir einen Code-Schnipsel hier geben kann, kann ich den auch übernehmen.

**Comment by KG3RK3N** [comment]
@fila612 Schau mal hier https://pubsubclient.knolleary.net/api#publish
Ist der 3. Parameter, muss dann in der mqtt.h als möglicher Parameter ergänzt werden damit man das beim senden dann übergeben kann.

**Comment by KG3RK3N** [comment]
Mal fix aus dem Ärmel: 
mqtt.h
```
        void sendMsg(const char *topic, const char *msg) {
            //DPRINTLN(DBG_VERBOSE, F("mqtt.h:sendMsg"));
            char top[64];
            snprintf(top, 64, "%s/%s", mTopic, topic);
            sendMsg2(top, msg, false);
        }

        void sendMsg2(const char *topic, const char *msg, boolean retained) {
            if(mAddressSet) {
                if(!mClient->connected())
                    reconnect();
                if(mClient->connected())
                    mClient->publish(topic, msg, retained);
            }
        }
```

Und hier dann einfach `true` ergänzen
https://github.com/grindylow/ahoy/blob/6dba1d757707426e1c8ff0c4d9d2ce5d22d6f26a/tools/esp8266/app.cpp#L933

**Comment by fila612** [comment]
habs grad mal eingefügt, kompiliert und geflashed. laut dem MQTT-Tool sind das noch keine "retained" Nachrichten.
Zum Vergleich eine Nachricht von Zigbee2Mqtt:
![Bildschirmfoto 2022-07-18 um 09 32 05](https://user-images.githubusercontent.com/29542374/179463687-e085584b-ab09-4e0f-823e-49e16aef06a7.png)

und dann die aktuelle von AHOY:
![Bildschirmfoto 2022-07-18 um 09 32 29](https://user-images.githubusercontent.com/29542374/179463741-59737ee8-06d6-491a-a98d-f7274c1ec2e0.png)

Bei letzteren fehlt das gelbe Retained Schild.


ich beobachte aber mal, evtl. bleiben die Nachrichten ja dennoch drin.

**Comment by fila612** [comment]
Kommando zurück, scheint zu klappen (gerade nochmal neu verbunden):
![Bildschirmfoto 2022-07-18 um 09 36 17](https://user-images.githubusercontent.com/29542374/179464279-8be62bb6-b62f-4837-a3e3-157e2deac9bd.png)

Neustart das HA ist nun ohne Probleme - Daten sind sofort verfügbar :)
Super - vielen Dank
Könnte man ja mal als PR einkippen, oder?

**Comment by KG3RK3N** [comment]
> Kommando zurück, scheint zu klappen (gerade nochmal neu verbunden): ![Bildschirmfoto 2022-07-18 um 09 36 17](https://user-images.githubusercontent.com/29542374/179464279-8be62bb6-b62f-4837-a3e3-157e2deac9bd.png)
> 
> Neustart das HA ist nun ohne Probleme - Daten sind sofort verfügbar :) Super - vielen Dank Könnte man ja mal als PR einkippen, oder?

Klar, rein damit 👍

**Comment by fila612** [comment]
> 2. Mir ist auch schon aufgefallen, das es in der neusten Version nicht mehr möglich ist das Interval anzupassen übers Setup. Ich habe es so implementiert, das die Werte nach MQTT-Interval + 5s ablaufen. Dort habe ich allerdings auch schon festgestellt, das es sehr knapp bemessen ist. Hier würde ich das auf MQTT-Interval * 2 umstellen, das sollte deutlich unproblematischer sein.

=> evtl. als Hinweis: im Rahmen meiner Analyse & Tests habe ich folgenden Zeile auskommentiert:
https://github.com/grindylow/ahoy/blob/6dba1d757707426e1c8ff0c4d9d2ce5d22d6f26a/tools/esp8266/app.cpp#L924

ist aber nicht Bestandteil des PR, aber die Frage wäre, ob man das überhaupt noch braucht.

**Comment by KG3RK3N** [comment]
> > 2. Mir ist auch schon aufgefallen, das es in der neusten Version nicht mehr möglich ist das Interval anzupassen übers Setup. Ich habe es so implementiert, das die Werte nach MQTT-Interval + 5s ablaufen. Dort habe ich allerdings auch schon festgestellt, das es sehr knapp bemessen ist. Hier würde ich das auf MQTT-Interval * 2 umstellen, das sollte deutlich unproblematischer sein.
> 
> => evtl. als Hinweis: im Rahmen meiner Analyse & Tests habe ich folgenden Zeile auskommentiert:
> 
> https://github.com/grindylow/ahoy/blob/6dba1d757707426e1c8ff0c4d9d2ce5d22d6f26a/tools/esp8266/app.cpp#L924
> 
> ist aber nicht Bestandteil des PR, aber die Frage wäre, ob man das überhaupt noch braucht.

Das ist dafür da, damit der jeweilige Sensor in HA auch irgendwann als nicht verfügbar markiert wird falls  z.B. die Verbindung abreißt. Ansonsten würde es Statistiken verfälschen, da HA denkt der Wert ist immer noch der von der letzten Message, obwohl das vlt. auch schon Stunden her sein kann und zeigt es nicht mehr als "nicht verfügbar" an.
https://www.home-assistant.io/integrations/sensor.mqtt/#expire_after

Von daher würde ich das mit drin lassen, allerdings ggf. `mMqttInterval * 2` anstatt nur 5s drauf zu rechnen da das doch recht schnell dazu führen kann das es sehr oft zum "nicht verfügbar" kommt falls der ESP mal etwas verzögert.

**Comment by fila612** [comment]
ich mach hier mal zu und schiebe die Themen um Hersteller und MF mal in einen separaten Issue.
das Intervall bzgl. exp_aft, wo @KG3RK3N noch Änderungen machen wollte pack ich da auch mit rein.
