### ISSUE TITLE
build 0.7.13 - Export Settings falsches Datum

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#1040]
Funktioniert leider nicht so wie gewünscht:
![grafik](https://github.com/lumapu/ahoy/assets/105392164/54eed96f-d847-4062-b54f-a9bbc0db505d)

Kurz nach einem Reboot erscheint das:
na_v0.7.13_ahoy_setup.json
Erst wenn ich manuell auf NTP Server  SYNC NTP gehe
![grafik](https://github.com/lumapu/ahoy/assets/105392164/3d3ad888-416c-4e9d-95b8-8b3899eae145)
Wird das Datum und die Uhrzeit mit abgespeichert, leider total verkehrt:

![grafik](https://github.com/lumapu/ahoy/assets/105392164/7544c897-33f7-4c4c-a6b9-9997c3e7ccc0)

Und das obwohl im Interface Datum und Uhrzeit richtig sind:
![grafik](https://github.com/lumapu/ahoy/assets/105392164/0628783b-823b-4422-8b33-5edb62086e5c)

@lumapu 
Was mir hier noch auffällt, ich bekomme bei SYNC NTP nur command executed, kein wirkliches Feedback ob es auch funktioniert hat, das kenne ich anders von anderen Systemen, da kommt dann auch ein Feedback mit Sync OK in grün, oder Sync failed in rot. Wäre praktisch hier gleich ein Feeback zu bekommen.
Man sollte vielleicht im Bereich NTP Server die Uhrzeit und Datum mit einblenden, um zu sehen ob es funktioniert.

**Comment by lumapu** [comment]
klar, guter Hinweis. Bei meinen Tests hat's funktioniert, ich teste nochmal.

**Comment by Ollipop030** [comment]
Guten Morgen,

gerade die 0.7.15 installiert. Beim Export wird leider immer noch nicht die Uhrzeit mit übernommen (na_v0.7.15_ahoy_setup.json). Zeit ist über NTP synchronisiert und läuft auch richtig.

Nachtrag: Grad gesehen, die Zeit läuft NICHT synchron (hatte das Browserfenster nicht aktualisiert). Ahoy läuft hier 2 Stunden in der Vergangenheit, über NTP mit der fritzbox und 0.debian.pool.ntp.org getestet, und über Sync from Browser.
Die Zeit wird wohl jetzt die UTC sein, dann müssen aber Zeitzonen und Sommer/Winterzeit berücksichtigt werden.

**Comment by KoLSMS** [comment]
> Guten Morgen,
> 
> gerade die 0.7.15 installiert. Beim Export wird leider immer noch nicht die Uhrzeit mit übernommen (na_v0.7.15_ahoy_setup.json). Zeit ist über NTP synchronisiert und läuft auch richtig.
> 
> Nachtrag: Grad gesehen, die Zeit läuft NICHT synchron (hatte das Browserfenster nicht aktualisiert). Ahoy läuft hier 2 Stunden in der Vergangenheit, über NTP mit der fritzbox und 0.debian.pool.ntp.org getestet, und über Sync from Browser. Die Zeit wird wohl jetzt die UTC sein, dann müssen aber Zeitzonen und Sommer/Winterzeit berücksichtigt werden.

Tatsächlich läuft auch meine ahoy seit 0.7.15 zwei Stunden in der Vergangenheit 😕

Gruß...

**Comment by lumapu** [comment]
fix kommt heute noch 😉

**Comment by rmayergfx** [comment]
Mit Version 0.7.16 habe ich aktuell keine Probleme mehr mit dem Export, Datum und Uhrzeit passt nun bei mir.
@lumapu 
Dankeschön.
Kommt bei SYNC FTP noch ein Update des Status in einer späteren Release? Hier wäre es sinnvoll auch das aktuelle Datum/Uhrzeit einzublenden.
