### ISSUE TITLE
Update from 0.7.15 to 0.7.17 or .18 fails

### ISSUE THREAD

**Issue by edw00d4711** [lumapu/ahoy#1044]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.15

### Github Hash

984e344

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Tried to update to latest version from .15

### Error description

Update from .15 to .18 stops with browser error ERR_CONNECTION_ABORTED
Update from .15 to .17 fails with the msg "update failed".

**Comment by lumapu** [comment]
I think that is an individual issue, maybe we collect a few day other repsonses. I think a fresh install of version 0.7.15 can help to solve the issue.
My systems are going from version to version - an the difference between 0.7.11 to 0.719 are marginal and does not touch any update related stuff. Maybe you can check your free heap in /system in the WebUI for its value.

**Comment by edw00d4711** [comment]
Here is a screenshot of the system. Free Heap ok?

![image](https://github.com/lumapu/ahoy/assets/5689688/f98f5e9d-b8a6-400d-826d-b5c8b456a7b1)

Will try a fresh install.

**Comment by edw00d4711** [comment]
Just tried flashing 0.7.19. Went fine! No clue why. Installed over my old .15 without fresh install.
![image](https://github.com/lumapu/ahoy/assets/5689688/d0493712-2b57-44d8-b1b6-7da27e7c39ce)

Thanks for your support and development!

**Comment by rmayergfx** [comment]
If you get in trouble with updates be sure to reboot the device before update. Don´t forget to export your settings prior to the update!
