### ISSUE TITLE
[Bug] ESP32 / W5500 - LAN: statische IP-Adresse wird nicht übernommen

### ISSUE THREAD

**Issue by Gerd-Watzmann** [lumapu/ahoy#1049]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.15

### Github Hash

_______

### Build & Flash Method

ESP Tools (flash)

### Setup

- ESP32  30 pins + W5500 ETH
- firmware: 230527_ahoy_eth_esp32_0.6.15.bin
- ETH-Modifikation aus https://github.com/lumapu/ahoy/issues/886#

### Error description

Obwohl ich im Web-Interface immer eine statische IP-Adresse vergebe (mit DNS, submask und gateway) zieht sich der ESP32 beim Booten immer eine Adresse vom DHCP-Server für das ETH-Interface. 

WLAN ist aus (dies ist korrekt, denn ich möchte ja explizit ausschließlich ETH / LAN verwenden).

Das ist jetzt zwar kein Beinbruch, denn ich kann ihm ja routerseitig eine feste IP4-Adresse zuweisen. Aber offenbar wird die IP-Konfiguration von der Weboberfläche nicht für LAN übernommen (im Gegensatz zu meiner im operativen Betrieb befindlichen ahoyDTU mit Firmware 0.6.9 - dort wird die statische IP-Adresse problemlos für das WLAN übernommen).

**Comment by lumapu** [comment]
binary, welches in #886 veröffentlich wurde, sollte diesen Issue beheben. Der Branch `eth` ist auch aktuell.
