### ISSUE TITLE
Feature Request :  Signslstärke good/bad von NRF ausgeben

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1050]
Offensichtlich existiert in der RF24.h Library ein Funktionsaufruf mit der man die Empfangssignalstärke prüfen kann. Sie gibt ein gut/schlecht zurück wenn die Signalsärke >64dBm bzw. <64dBm ist.

bool goodSignal = radio.testRPD();
if(radio.available()){
Serial.println(goodSignal ? "Strong signal > 64dBm : "Weak signal < 64dBm");
radio.read(0,0);

Offenbar schon in OpenDTU integriert, wäre es schön wenn man das auch für Ahoy machen könnte. Bitte auch mit MQTT ausgeben 😉

HoymilesRadio_NRF.cpp Zeile 58
(Nur die Werte -80 bzw. -30 sind wohl falsch)

**Comment by DanielR92** [comment]
Hallo zusammen,

das wollt ich schon immer drinnen haben. 
Ich schau mir das mal an, da meine Testumgebung aktuell etwas "umständlich" wurde.

Meld mich sobald ich was neues habe.

**Comment by DanielR92** [comment]
Hallo Knickohr,
ich habe das ganze mal eingebaut. 
Das muss jemand noch gegen prüfen... ich hab generell immer eine schlechte Verbindung bei mir.

**Comment by knickohr** [comment]
Von meinen 13 WRs wird wohl einer good ausgeben 😉

**Comment by knickohr** [comment]
Siehe hierzu auch Issue #1129

**Comment by knickohr** [comment]
Das neue Feature funktioniert !  😎 Es gibt auch ein „Strong Signal“. Also bitte noch für jeden Inverter einzeln aufdröseln und noch das - dazu machen.

![IMG_1133](https://github.com/lumapu/ahoy/assets/63048210/eef078d1-0033-46dd-b583-cb5c0cd5e777)

**Comment by knickohr** [comment]
Die Funktion hat leider wenig Nährwert da die meiste Zeit ein <-64dBm kommt, egal wie nah man am WR dran ist. Schade, wäre eine einfache Möglichkeit gewesen eine wenigsten primitive Empfangsqualität darzustellen.

Vielleicht sollten wir doch auf die heuristische Funktion von „Oberfritze“ setzen ?

Ich laß hier aber mal trotzdem auf, so als Reminder 😉

**Comment by DanielR92** [comment]
Hmm, das muss man nochmals anschauen. Danke für die Info schonmal @knickohr

**Comment by knickohr** [comment]
@DanielR92 

Schau Dir den PR #1080 mal an. Da wird auch eine Heuristik generiert welche die Qualität der empfangenen Daten nachbildet. Ist zwar alles noch in der Testphase, wird aber meiner Meinung nicht mehr lange dauern dann fließt das in die nächsten Ahoy-Versionen ein.

Sieht dann so aus :  Quality:  0 -1 -2 4 2, Cnt 3, Fail 0

Was die Werte genau bedeutet muß Dir @oberfritze erklären. Ich weiß nur, je höher der Wert, umso besser. Außerdem müßte man die 5 Werte zu einem zusammen fassen.

**Comment by knickohr** [comment]
Könnte es sein das da noch ein Bug drin war ?  Mit der DEV 58 habe ich jetzt mehrere Inverter die auch ein good bringen 😎

**Comment by lumapu** [comment]
nein, seit dem changelog mache ich nichts mehr geheim, alles transparent 😊

**Comment by knickohr** [comment]
Spannend ! 🤔

**Comment by knickohr** [comment]
Bei der 59 ist es auch OK. Da hin und wieder das auch wechselt, gehe ich davon aus das es korrekt funktioniert. Auch wenn es nicht den erhofften Effekt gebracht hat und nur bei sehr guten und kurzen Empfangsbedingungen funktioniert.

**Comment by knickohr** [comment]
Nachtrag :  ich glaube herausgefunden zu haben warum es bei einigen NRF geht und bei anderen wiederum nicht :

- Fast alle Billig NRF sind China Clone und da funktioniert es nich
- Auch das EByte Modul macht es nicht. Edit :  Es wurde bestätigt das es beim EByte auch funktioniert.
- Einzig das Fusion liefert bei mir diese Werte

Ich mache deshalb hier zu. Es scheint ein reines Chipproblem zu sein, und funktioniert nur mit echten NRF-Chips.

**Comment by DanielR92** [comment]
Danke für die Infos, das sollte man aber im README doch festhalten?

**Comment by knickohr** [comment]
Ja, EByte müßte nochmal verifiziert werden. Bin mir aber ziemlich sicher das da auch nichts kam.

Nachtrag :  Beim EByte funktioniert es auch.
