### ISSUE TITLE
MQTT Home Assistant, keine Anzeige des 2. WR

### ISSUE THREAD

**Issue by schlagucke** [lumapu/ahoy#1051]
## Hardware
  * [ X] ESP8266
  * [ ] ESP32
  * [X ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [X] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.6.9
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hallo,

MQTT funktioniert und die Daten werden auch in Home Assistant angezeigt.

Nur werden die Daten vom ersten Wechselrichter in HA angezeigt und die Daten des zweiten Wechselrichter nicht.

Könnte mir einer eventuell weiterhelfen. 

Habe schon alles zurück gesetzt. Aktualisiert etc. 

Es werden weiterhin nur die Daten vom ersten Wechselrichter und die gesamten Totalwerte übertragen. 

Vielen Dank. 

Gruß

**Comment by knickohr** [comment]
Da ich bereits 13 Inverter an der DTU habe und die DTU alle Werte an den Broker liefert, würde ich das Problem eher bei HA suchen.

**Comment by schlagucke** [comment]
Alles klar. Das schaue ich da noch einmal. 

Ist der Fehler schon einmal ein wenig eingegrenzt.

**Comment by knickohr** [comment]
Hast Du automatisch die Entitäten oder wie sich das nennt angelegt, oder manuell ?

**Comment by schlagucke** [comment]
Die Entitäten haben sich automatisch angelegt.

Sobald ich MQTT in HA aktiviert und alles soweit eingerichtet hatte.



knickohr ***@***.***> schrieb am So. 30. Juli 2023 um 09:35:

**Comment by knickohr** [comment]
Dann mach’s manuell 😉

**Comment by lumapu** [comment]
das wurde meines Wissens erst in der development Version behoben, bitte diese testen, und Feedback geben.

https://nightly.link/lumapu/ahoy/workflows/compile_development/development03/ahoydtu_dev.zip

**Comment by schlagucke** [comment]
Super, vielen Dank für die Info.
