### ISSUE TITLE
Langsame WebGUI und MQTT-Verbindungsabbrüche

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1057]
Sind zwar jetzt zweierlei unterschiedliche Probleme, aber ich denke sie hängen direkt oder indirekt miteinander zusammen.

Zuerst mal, dieser Issue wird nur User tangieren die viele Wechselrichter an der DTU haben. Denn mir ist aufgefallen das diese Probleme mir steigender Anzahl der WRs immer schlimmer werden. Das würde auch meiner Meinung nach erklären warum viele 8266-User bereits ab 2 WRs Probleme mit der WebGUI bekommen.

Ich selbst nutze einen ESP32 (kein S3 momentan, damit gibt es ein anderes Problem mit dem ePaper Display ab der Version 0.7.x) und jetzt schon 13 HM-300 WRs. Das Problem mit dem WebGUI trat erstmals ab der 0.7.17 auf, Seiten werden teilweise überhaupt nicht mehr dargestellt, bzw. es kommen völlig unsinnige Ausgaben. Vor allem die Live-Seite ist mittlerweile für mich unbrauchbar geworden 😲

![IMG_1043](https://github.com/lumapu/ahoy/assets/63048210/cbe8dfa6-8898-412e-963a-afd636665a7e)

Es werden mehrere Total-Boxen angezeigt, hatte schon 7 Stück 😱 und was noch viel schlimmer ist, in keiner Box waren die Werte korrekt !

Andere Seiten sind sehr langsam, so dauert es manchmal 10s und länger bis sie aufgebaut werden. Die „Schwuppdizität“ ist unter aller Sau 😪

Seit der Version 0.7.21 kommt ein weiteres Problem hinzu. Es gibt, nachdem die Inverter alle offline sind, fast im Minutentakt Verbindungsabbrüche vom MQTT.

![IMG_1044](https://github.com/lumapu/ahoy/assets/63048210/a98d92fc-2788-4b5c-931a-81d934f2e6a3)

Hier kann man es sehr schön erkennen, das Problem ist nur Nachts vorhanden 🤔

![IMG_1045](https://github.com/lumapu/ahoy/assets/63048210/77f0e12f-2b44-4b11-bf7c-8341b5234e0c)

Ob es jetzt ausschließlich an der großen Zahl der WRs liegt, wage ich zu bezweifeln. Da würde das Problem eher unter Tags auftreten. Viel eher denke ich das hier die LWT-Message zuschlägt, weil der Keep-Alive-Timeout kommt. Denn wenige Sekunden später ist MQTT wieder connected.

Was ich bereits getestet habe :
- Factory Reset und komplette Neueinrichtung
- Komplett frisch geflashter ESP mit vorherigem Erase
- Die Verbindung zum Broker steht stabil, sonst würde mir die Raspi-Konsole auch wegfliegen

Ich werde heute Abend mal versuchen das MQTT-Intervall zu verkürzen. Vielleicht wird es damit besser. Momentan nutze ich die Einstellung 0, also nur wenn sich Werte ändern wird gesendet.

**Comment by Dirk-Ahoy** [comment]
Hab das Problem auch schon bei einem WR  -   (8266 Board) - hab gestern mal die aktuelle Dev geflasht und dann dauernd Abbrüche über den ganzen Tag gehabt und reboots. Webinterface hängt öfters und dann rebootet die Kiste.   Im Moment bin ich wieder auf 0.7.11 zuück da ich nicht weis ab wann das Problem gekommen ist - dazwischen hatte ich keine Versionen getestet.

**Comment by knickohr** [comment]
Das ist frustrierend 😫 Es ist Nacht und die MQTT-Abbrüche fangen wieder an. Eben sind mir beim Setzten des Intervalls sogar die kompletten Invertereinstellungrn flöten gegangen 😡 Das Ahoy-Spielen ist somit für heute Abend beendet ☹️

Und ja, er macht diese Abbrüche auch wenn keine Inverter angelegt sind. Deshalb gehe ich davon aus das es nicht an der Anzahl der Inverter liegt, sondern da was anderes faul ist.

**Comment by knickohr** [comment]
Irgendwelche seltsamen Dinge passieren hier !  Ahoy spukt 😱

Aber mal der Reihe nach. Nachdem ich gestern Abend durch rumspielen an den Settings meine Invertereinstellungen verloren habe, machte ich einen neuen Import der Settings. Somit waren ja erst mal alle gespeicherten Werte von den Invertern nach dem Reboot weg. Egal, aber was auffällt, das es nachts wieder fast im Minutentakt diese MQTT-Abbrüche gab. Heute Morgen habe ich es dann testweise mit einem festen MQTT-Intervall von 35s laufen lassen. Leider gibt es damit dann auch unter Tags diese Abbrüche, wenn auch wesentlich weniger. Aber was positiv auffällt, heute Abend kamen keine Abbrüche im Minutentakt, also schon mal prima 👍

Vor einer halben Stunde habe ich dann das Fusion-Board mit dem S3 raus gekramt und aktiviert.

Hossa die Waldfee ! 😲 Die Swuppdizität der WebGUI ist 1a, besser kann’s gar nicht sein. Und auch die minütlichen MQTT-Abbrüche sind weg. Jetzt erklär mir das mal einer !

![IMG_1049](https://github.com/lumapu/ahoy/assets/63048210/ad12116a-d468-46dc-b469-752097b07d4b)

Ich werde das Morgen mal „unterLast“ beobachten. Mir deicht langsam der Verdacht, das der native ESP32 mit 13 Invertern auch am Ende ist ! 😢

Leider funktioniert das ePaper mit dem Fusion und Ahoy nicht mehr, da muß seit der ersten Version 0.7.x was an den Pins seitens Ahoy gedreht worden sein. Genauer gesagt, es funktioniert schon noch, aber der NRF wird dann nicht mehr erkannt. Also entweder NRF oder ePaper 🤪 Ich vermute mal wegen der neu hinzugekommenen CMT-Softwareimplementation 😞

**Comment by knickohr** [comment]
Bilder sagen mehr als 1000 Worte :

![IMG_1050](https://github.com/lumapu/ahoy/assets/63048210/a161476d-9d15-4fe4-932d-b652827ad223)

Seit gestern Abend gab es nur mehr 2 MQTT-Abbrüche und die Schuppdizität ist perfekt, auch bei der Live-Seite. Und vor allem, die Werte stimmen jetzt wieder 😎

Einen Test muß ich nachher noch machen um das auszuschließen. Ich hoffe nicht, das es das ist, denn das wäre dann ein kompletter Rückschritt seit der Version 0.7.x 🫣

Nachtrag :  Was auch auffällt, die Werte der einzelnen Inverter kommen jetzt auch wieder in ganzen Blöcken und nicht auf 2 oder 3 aufgesplittert und vor allem sehr schnell. Vorher war es mehr ein Tröpfeln.

**Comment by knickohr** [comment]
Sooo, wir sind einen weiteren Schritt weiter, aber leider kurz vor dem Abgrund ☹️

Mein erster Test hat sich glücklicherweise nicht bewahrheitet. Es ist nicht das ePaper 😎das den MQTT und die Schwuppdizität blockiert.

Und jetzt leider die schlechte Nachricht 😫 Es ist das MQTT selbst. Denn deaktiviere ich es, dann klappt es auch wieder mit der Schwuppdizität 😲

Ein weiterer Test zurück auf die Version 0.7.11 und es funktioniert noch alles 😱

Nun stehe ich da :
- entweder verwende ich den nativen ESP32 ohne MQTT aber mit funktionierendem ePaper
- oder ich nehme den ESP32-S3 (Fusion-Board), dann klappt es mit MQTT aber nicht mit dem ePaper
-  oder ich gehe zurück auf die 0.7.11. da funktionieren ePaper und MQTT am ESP32 noch

Alles Sch…!

**Comment by knickohr** [comment]
Faszinierend was so ein neuer Prozessor bewirkt 😲

![IMG_1053](https://github.com/lumapu/ahoy/assets/63048210/06631d08-82e7-43cb-a138-1d9bb5ef3c31)

Die 3 Abbrüche kommen von manuellen Reboots, ich habe gestern Abend noch etwas gespielt.

Nun stellt sich für mich die Frage ob wir hier in ein Ressourcenproblem rein gelaufen sind, oder ob einfach nur unglücklich programmiert wurde ? 🤔

**Comment by lumapu** [comment]
aktuell ist ein workaround für MqTT aktiv, das kann sich bei der hohen Anzahl an Wechselrichtern natürlich bemerkbar machen.
Das heißt für mich, ich muss den workaround rückgängig machen und es direkt in der MqTT Lib beheben.
Hintergrund: die MqTT Lib reserviert aktuell für jedes Paket neuen Speicher und gibt den zyklisch beim tatsächlichen senden wieder frei. Wenn man bedenkt, dass wir sehr viele Pakete auf einmal schicken ist das eine beträchtliche Menge an Speicher. In erster Linie ist das vor allem für den ESP8266 schädlich, da hierdurch sein heap komplett zerstört (durchlöchert) wird.
Als workaround habe ich eine Methode eingebaut, die jedes Paket einzeln sendet und somit den heap nicht belastet - genau dies ist bei 13 WR nicht unerheblich und wohl auch die falsche Lösung.
Ich habe verschiedene Ideen und hoffe, dass wir dieses Problem damit aus der Welt schaffen können.

Was die Abbrüche nachts angeht, kann ich noch nicht nachvollziehen

**Comment by MartinBachmannHD** [comment]
Nachdem es auf dem ESP8266 (ein alter, gebrauchter und ein komplett neuer) bei mir mit MQTT (aber nur ein HM-600 angeschlossen) nicht so richtig flüssig im UI war habe ich einen neuen ESP32 probiert - immer noch das selbe Verhalten, unresponsive... 
Mein Verdacht ging noch in eine weitere Richtung die das MQTT-Heap Thema evtl noch verstärken könnte - es kommt immer zu TCP-Verbindungs-Abbrüchen (Energiesparen FritzBox oder ESP? Schlechte Verbindung? Wacklige Verdrahtung? ...). Evtl vertärkt das das MQTT-Heap Thema, da dann die Messsages noch gespeichert werden bis sie gesendet werden -> mehrfache Belastung?

**Comment by knickohr** [comment]
OK, der S3 hat einen etwas größeren Heap, aber wirklich mehr Ressourcen hat er nicht. Was aber beim S3 neu ist, neben mehr GPIO, Flash, USB und Bluetooth, er hat 2 Coprozessoren implementiert bekommen die Rechenaufgaben (vor allem Multiplikation und Division) übernehmen, das könnte schon erklären warum es mit dem S3 wesentlich besser klappt. Wäre da nicht das ePaper-Problem 😪

Nein, es werden keine Messages gespeichert Ahoy arbeitet mit QoS=0, also Fire and Forget. Es wird raus geballert, egal ob was hört oder nicht. Und es wird auch kein zweites Mal gesendet oder geprüft ob der Broker es angenommen hat.

**Comment by lumapu** [comment]
was QoS angeht hast du recht, allerdings sammelt die MqTT-Library intern noch die Daten, bevor sie dran kommt die angefallenen Daten rauszuschicken.

**Comment by lumapu** [comment]
@knickohr, wie steht eigentlich dein Intervall? Wenn du auf der Live-Seite ganz nach unten scrollst solltest du es auch sehen können. 
*Every X seconds the values are updated*

Evtl. ist das bei der extrem kurz, damit du in angemessener Zeit alle Inverter abgefragt bekommst - ich baue hier mal ein Minimum von 5s ein. (Nur für die Website, nicht als Abfrageintervall)

**Comment by knickohr** [comment]
Es steht auf 5s, weniger ging schon damals nicht. Dann kam er mit den Retries und den Abfragen nicht mehr hinterher und hat sich vergewohlwurstelt 😉

**Comment by knickohr** [comment]
Yeahhh !  Die 23 fluppt wieder 😎😘

MQTT werde ich mal über den Tag beobachten, vor allem Nachts 😅

Ich werde jetzt aber trotzdem eine zweite DTU aufstellen da ich Empfangsprobleme mit meinen weiter entfernten WRs habe (Gartenhaus). Bin mal gespannt, wie das dann zusammen werkelt 🫣

**Comment by knickohr** [comment]
Sieht gut aus, keine Verbindungsabbrüche mehr, auch wenn die DTU offline ist. Wenn’s bis Morgen Abend so bleibt, kann man hier zu machen 👍

„Dual Core“ funktioniert auch, jetzt klappt’s mit den weiter entfernten WRs gut. War einfacher als gedacht, das in Node-Red zu implementieren 😎

<img width="1024" alt="image" src="https://github.com/lumapu/ahoy/assets/63048210/e4269129-1564-4a1a-9a6b-bff60aee5b2d">
