### ISSUE TITLE
Ahoy mit Accesspoint verbinden?

### ISSUE THREAD

**Issue by DennisXK** [lumapu/ahoy#1059]
## Hardware
  * [x] ESP8266 mit antenne

### nRF24L01+ Module
* [x] nRF24L01+ 

### Antenna:
* [x] circuit board

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2)

### Version / Git SHA: 
Version: 0.5.66
Github Hash: f8fe044

### Build & Flash Method:
* [x] ESP Tools

Hi, ich habe immer wieder Verbindungsprobleme zu meinem wlan. Ich habe auch einen D Lan Accesspoint, doch leider verbindet sich ahoy immer mit der Fritzbox die ein schwächeres Wlan als der AC Point hat.

Ist es möglich, dass ahoy sich auf den Accesspoint verbindet?

**Comment by MetaChuh** [comment]
@DennisXK 
falls der d-lan und die fritzbox die gleichen ssid namen haben, kann man leider nicht spezifisch auswählen, womit man sich verbindet.

hast du schon versucht, dem d-lan eine andere ssid zu vergeben, zb. fritzbox: MeinWLAN und d-lan: MeinWLAN_EXT oder MeinWLAN_D ?
weil dann könntest du spezifisch den access point/router auswählen.

greetings,
metachuh

**Comment by jimknopf63** [comment]
Man kann auch in den WLAN Einstellungen mit der Sendeleistung herumspielen und es so einstellen das die DTU die Fritzbox nicht mehr sieht und nur noch den AP

**Comment by lumapu** [comment]
in Ahoy ist es schon seit langem implementiert, kannst du per USB mal mitloggen was während dem Bootvorgang passiert? Es wird die BSSID mit der besten Sendeleistung ausgewählt. Das hatte seinerzeit @beegee3 implementiert.

**Comment by beegee3** [comment]
@DennisXK du bist noch auf Version 0.5.66. Bitte auf main 0.6.9 (oder dev. 0.7.22) aktualisieren!
