### ISSUE TITLE
MQTT Verbindung wird nach Neustart des Brokers nicht mehr hergestellt

### ISSUE THREAD

**Issue by JauntyJosef** [lumapu/ahoy#106]
Ich habe die Version 0.4.25 installiert. Da bei mir ein Server, auf dem der MQTT Broker läuft, jede Nacht für Backups kurz runterfährt und wieder neu startet, bemerkte ich, dass die Daten danach nicht mehr per MQTT ausgeliefert werden. Bei der Weboberfläche steht: "MQTT: not connected". Nach einem reboot von Ahoy funktioniert es wieder.

**Comment by timtimsson** [comment]
… kann ich bestätigen.

**Comment by der2of6** [comment]
kann den Effekt ebenfalls bestätigen

**Comment by thinklerde** [comment]
Auch wenn  die Internetverbindung weg war und neu aufbaut (Fritzbox) verbindet sich der MQTT ebenfalls nicht neu.

**Comment by timtimsson** [comment]
> … kann ich bestätigen.

ein **lwt** wäre auch nicht schlecht, falls die Verbdg verloren geht
mClient->publish(topic, msg, retained);

**Comment by stefan123t** [comment]
@timtimsson was meinst Du mit lwt ?

**Comment by fila612** [comment]
ich denke, das hier das "Last Will and Testament" Feature von MQTT gemeint ist.
Von dem was ich gelesen habe, könnte das auch die Lösung für das Problem hier zu sein.
Code-technisch bin ich eine Niete :( kann hier nicht viel beisteuern.
in der API des PubSubClient gibt es die Will-Parameter bei Connect: https://pubsubclient.knolleary.net/api#connect

Allgemeine Infos zu LWT sind hier nochmal gut dargestellt: https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

**Comment by timtimsson** [comment]
… ja genau das meine ich. Mit lwt kannst du schauen, ob z.B. öfters die Verbindung verloren wurde oder aktiv überwachen, ob der „ESP“ noch online ist…
Lwt wird ganz oft genutzt, Projekte wie tasmota oder easyEsP.
https://nodemcu.readthedocs.io/en/dev/modules/mqtt
https://www.letscontrolit.com/forum/viewtopic.php?t=1164

**Comment by HorstG-57** [comment]
...Auch wenn ich hier neu bin , möchte ich mal einenen Vorschlag zum MQTT bringen.

a: 
das Lwt setzt einen Topic in dem Moment, wo der MQTT Server erkennt, das ein Publisher ( hier der Ahoy ) 
unerwartet die Verbindung zum MQTT-Server verlorren hat. 
Dieses Topic verfällt nicht, so das ein neuer Subscriber der dieses Topic abfragt den letzten Inhalt erhält.
Wenn man jetzt einen Topic "status" erstellt dieses nicht verfallen läst, und vom LWT dieses auf den Wert "unbekannt" setzen läst und vom Ahoy beim Anmelden am MQTT Server dieses Topic auf "Online" bzw. beim Abmelden auf "Offline" setzen läst, 
dann können die Subscriber sauber erkennen ob der Ahoy noch lebt.

b:
Ich habe ( wie einige andere ) auch das Problem, 
das im Fall, das der MQTT-Server zwischendurch nicht erreichbar war, 
der Ahoy sich auf "MQTT disconnected" setzt und sich dann nicht wieder verbindet. 
Der Ahoy müste eigentlich vorm senden der MQTT Pakete prüfen, ob er noch verbunden ist. 
Sollte das nicht der Fall sein, muss er sich neu mit dem MQTT-Server verbinden.

c: ( SendeInterval der MQTT Meldungen )

Wieso läst man den Ahoy nicht einfach immer mit einen Zeitversatz von einigen Sekunden ( z.B. 2 ), 
nachdem er die Daten vom Wandler erhalten hat, 
die MQTT Daten für dieses Wandler an den MQTT-Server aussenden, 
z.B. durch ein   "mMqttTicker = mMqttInterval -2" an Ende der Datenaufbereitung der Wandler Rohdaten ?
Werden keine Daten empfangen, sendet der Ahoy in seim normalem MQTT Intervall, 
kommen Daten an werden die sofort zum MQTT übertragen.

d:
Die Übertragung der "DiscoveryConfigDaten" vom Ahoy sollte in Setup abschalbar sein. 
Die sind doch nur von Intresse, wenn man die "homeassistant" Software einsetzt, oder ?

**Comment by KG3RK3N** [comment]
@HorstG-57 

> b:
> Ich habe ( wie einige andere ) auch das Problem,
> das im Fall, das der MQTT-Server zwischendurch nicht erreichbar war,
> der Ahoy sich auf "MQTT disconnected" setzt und sich dann nicht wieder verbindet.
> Der Ahoy müste eigentlich vorm senden der MQTT Pakete prüfen, ob er noch verbunden ist.
> Sollte das nicht der Fall sein, muss er sich neu mit dem MQTT-Server verbinden.

Genau das tut er eigentlich schon wie man hier sehen kann und dennoch scheint es nicht richtig zu klappen:
https://github.com/grindylow/ahoy/blob/ed4a99bf7feb9801af7cd02273a1da1a27fff732/tools/esp8266/mqtt.h#L47-L50

> d:
> Die Übertragung der "DiscoveryConfigDaten" vom Ahoy sollte in Setup abschalbar sein.
> Die sind doch nur von Intresse, wenn man die "homeassistant" Software einsetzt, oder ?

Absolut richtig und bin ich bei dir, das könnte man ruhig im Setup ergänzen.

**Comment by HorstG-57** [comment]
Ich habe mal ein wenig mit Debugausgabe dem reconnect() nachgeforscht.
Für mich sieht das so aus, das der reconnect()  auch Richtig aufgerufen wird, 
aber in der PubSubClient::connenct nicht richtig ausgeführt wird. 
Auch ein zusätzlich eingebautes PubSubClient::disconnect bringt keine Besserrung.

**Comment by HorstG-57** [comment]
Habe noch ein wenig weiter versucht dem Problem sein Geheinis zu entlocken, 
das Problem scheint aber tiefer in den Netzwerk Proceduren vom TCP-Stack zu liegen.

Die Reconnect Procedure in der mqtt.h wird sauber aufgerufen, nur 
bekomme der TCP_Client der unter der MQTT Verbindung liegt, die 
Verbindung nicht wieder aufgebaut ( Soweit konnte ich das bis jetzt 
nochvollziehen ).
Nach einer Verbindungsunterbrechung bringt
der MQTT Client sauber den Status -3 ( LOSS CONNECTION ) und
der TCP-Client bringt den Status 0.
Danach bekommt der TCP Client bzw. der MQTT Client die Verbindung nicht 
wieder aufgebaut. Ich habe es hier schon mit einem Disconnect probiert ( 
nachdem festgestellt wurde das die MQTT Verbindung abgebrochen ist ) 
bzw. mit einer Verzögerung vom bis zu 60 Sekunden bevor ein neuer 
connect Versuch unternommen wird. Auch ein "flush" und ein "stop" der 
TCP Verbindung haben keine Verbesserung der Situation gebracht.

**Comment by stefan123t** [comment]
@HorstG-57 versuch doch mal die ESP_DEBUG_* Flags zu setzen um WiFi+SSL+TCP zu debuggen:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html

ESP_DEBUG_CORE
ESP_DEBUG_WIFI
ESP_DEBUG_MDNS
ESP_DEBUG_...

https://github.com/esp8266/Arduino/blob/04c2322721f6865efe0c518be57e795e8643c183/tools/boards.txt.py#L1308-L1309

**Comment by stefan123t** [comment]
Ich fand den folgenden Beitrag und den Hinweis auf die [PlatformIO Espressif 8266 Dokumentation](https://docs.platformio.org/en/latest/platforms/espressif8266.html#serial-debug) hierzu ganz hilfreich 

**Debugging WiFiClient with an ESP8266 on PlatformIO**
https://community.platformio.org/t/debugging-wificlient-with-an-esp8266-on-platformio/9891/2

und habe meinen Debug Level in der platformio.ini unter meiner Zielplattform gesetzt:
```
[env:nodemcu_v2]
build_flags = -DDEBUG_ESP_CORE -DDEBUG_ESP_WIFI -DDEBUG_ESP_HTTP_CLIENT -DDEBUG_ESP_HTTP_SERVER -DDEBUG_ESP_OOM -DDEBUG_ESP_PORT=Serial
```
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/platformio.ini#L4-L31

Ich habe zusätzlich noch folgende monitor_filters aktiviert damit schreibt er es auch noch auf Platte weg:
```
monitor_filters = 
    ;default   ; Remove typical terminal control codes from input
    time      ; Add timestamp with milliseconds for each new line
    log2file  ; Log data to a file “platformio-device-monitor-*.log” located in the current working directory
```

**Comment by HorstG-57** [comment]
Mit einem Restart kann man's auch machen, es geht aber schöner.

Mit dem DEBUG war dann schnell gefunden ( Danke für den Hinweis ). 
Der MQTT-Client verliert seine MQTT Server Adresse und kann sich somit natürlich nicht wieder verbinden.

Ich habe hier jetzt einige Ergänzungen in die Sourcen der version 0.4.25 eingebaut mit denen zwei Probleme behoben werden und eine Anpassung die man über das Setup schaltbar machen sollte.

1.  Problembehebung   :   MQTT reconnect ohne Restart 
2.  Problembehebung   :  Anmeldung am MQTT Server mit dem DeviceName so wie er in Setuo eingetragen ist
3.  nice to have             :  MQTT aktualiesierung sofort nach dem die Daten vom WR eingelesen und aufbereitet wurden

Ausserdem habe ich beim reconnect eine Wartezeit von 5 Sekunden eingebaut 
um zu verhindern das der Reconnect auch sofort wieder fehlschlägt. 

Ich muss hier noch wieder etwas bei Debug aufräumen ( sind noch zuviel auskommentierte Debugzeilen drin ) 

Frage : wie bekommen wir die Änderungen in Git Repo rein ? ich werden da ja wohl nicht schreiben dürfen.

**Comment by fila612** [comment]
mach doch nen eigenen fork und einen PR mit deinen Änderungen, so wäre es doch am saubersten

**Comment by HorstG-57** [comment]
Habe einen Fork erstellt ( horstg-57/ahoy ) , die Sourcen überarbeitet und das ganze hochgeladen, 
eine PULL Request habe ich aufgemacht.

( hat leider etwas gedauert, musste mich erst mal mit Guthub und Git  auseinandersetzen ).

**Comment by stefan123t** [comment]
@HorstG-57 so wie @fila612 vorschlägt mache ich das auch. Fork erstellen und einen API Key registrieren. Dann einen git push auf die eigene Repo URL (`git push https://github.com/HorstG-57/ahoy/`) und dann einen PR in Deiner github Oberfläche erstellen.

**Comment by HorstG-57** [comment]
ich habe eine Stelle eingebaut 
( app.cpp; sofortigen versenden der Daten per MQTT nachdem die Datem vom WR aufbereitet wurden) 
für die noch jemand einen Schalter im Setup einbauen müsste , so das man das je nach eigenen Wünschen aktivieren und deaktiviern kann.

Es währe ausserdem schön, wenn der jenige dann auch gleich ein Feld mit aufnehmen würde, 
wo man die Adresse des NTP-Servers eintragen kann.
 
Die Daten sollten natürlich auch im EPROM gespeichert werden.

**Comment by stefan123t** [comment]
@baloo hat das Problem gerade mit mir gemeinsam untersucht.
Die Strings die in Zeile 92 und 94 an den PubSubClient übergeben werden sind nur temporär auf dem Speicher.
https://github.com/grindylow/ahoy/blob/c35c86210f8507be7352ead73c02e5855f3f9d63/tools/esp8266/mqtt.h#L88-L96 

Der PubSubClient merkt sich aber eine Referenz const char* domain; darauf.
Wenn er dann das nächste Mal was senden soll und will, dann ist an der Stelle im Speicher kein Domain Name / IP mehr.
Man sollte also den mBroker fest initialisieren:
```c
            memset(mBroker,  0, MQTT_ADDR_LEN);

            snprintf(mBroker, MQTT_ADDR_LEN, "%s", broker);
            
        char *getBroker(void) {
            //DPRINTLN(DBG_DEBUG, F("mqtt.h:getBroker"));
            return mBroker;
        }

        char mBroker[MQTT_ADDR_LEN];
```

**Comment by stefan123t** [comment]
Das hast Du m.E. in Deinem Commit auch gemacht. Ich hatte bei mir die mqttAddr verwendet, eventuell klappt das nicht.

**Comment by HorstG-57** [comment]
Das Problem ist nur, das die Refernz bei einem "LOS_Connect" leider auch kaputt geht 
und somit die Broker-Adresse neu gesetzt werden muss.
Darum merke ich mir in meiner Änderung die Broker-Adresse und setze beim reconnect die Server-Adresse neu 
( siehe mqtt.h zeile 141 und 142 ).

**Comment by stefan123t** [comment]
@HorstG-57 habe den mClient->setServer Aufruf in PR #121 auch noch übernommen.
