### ISSUE TITLE
Add support for SML-reader

### ISSUE THREAD

**Issue by technics42** [lumapu/ahoy#1065]
It would be very nice, if you could directly connect some optical device (photo-transistor/-diode/...) and support SML in order to get values from energy meter.
(e.g. https://github.com/mruettgers/SMLReader)

And by doing so, calculate saved costs/power consumption and display it in web-browser.

**Comment by rmayergfx** [comment]
Sorry, this is not the goal of the project. we need a stable solution to get data from (multiple) inverters. Additional hardware and SML will increase the code and also you need hardware with enough performance to support this.

**Comment by kiu77** [comment]
@rmayergfx 
good point.

**Comment by MetaChuh** [comment]
@technics42 

you should gets a shelly 3em tripple phase smart meter, or similar.
https://www.shelly.com/de-at/products/product-overview/shelly-3em-1

you will need this to have exact measurements of all your consumption and overproduction each second.
the optical sensor would stop at 0, without any possibility to see overproduction, and has a very high latency, so you would be almost as blind as if you just look at your meter display when you are at home.

many of us use those 3em's and some of us code for them, in combination with hm inverters, victron chargers, ahoy dtu and open dtu.

greetings,
metachuh

**Comment by Ollipop030** [comment]
> the optical sensor would stop at 0, without any possibility to see overproduction, and has a very high latency

Thats not correct. My Tasmota SML shows a negative value when overproducing, the latency is only a few seconds. I have a second (non-Tasmota) SML, that reads the exact values for each phase when cosuming (1.7.0. - 1.7.3.) and overproducing (2.7.0. - 2.7.3.). But that depends on the powermeter itself. But most powermeters should deliver 1.7.0. and 2.7.0.

But yes, it should not be the job of ahoy to collect any other data as from the inverters.

**Comment by MetaChuh** [comment]
@Ollipop030 
danke für das update und sorry, dachte das gilt für alle smart meter, nicht nur die zähler hier bei uns in wien.
hier ist halt alles slower, außer das stromrechnung abbuchen vom konto 😂
hast du dich auch schon mit dem 3em oder ähnlichem im sicherungskasten rumgespielt ?

**Comment by nexulm** [comment]
I'm using a Tasmota (Connected to HomeAssistant via MQTT and configured Grafana graphs) based SM reader for my EZB as well. Doesn't make sense to me to integrate it into the Ahoy code as well.
BTW: My Ahoy HW is located in the garden and my EZB SM reader 25m away. :-)
![image](https://github.com/lumapu/ahoy/assets/5346351/d905ca13-5f2f-4ba7-b89e-31c3fcd8f162)
![image](https://github.com/lumapu/ahoy/assets/5346351/9113e2e2-89f2-427d-a921-1f0ceae1631b)

**Comment by Ollipop030** [comment]
> hast du dich auch schon mit dem 3em oder ähnlichem im sicherungskasten rumgespielt ?

Nein, bisher nicht. Ich habe ein paar 1-Phasige Shellys, aber da noch nie wirklich auf die Zeit geachtet, wann welche Daten kommen. Zumindest was die Cloud angeht werden aber demnächst wohl alle Geräte minütlich ihre Werte übertragen:

https://stadt-bremerhaven.de/shelly-mit-abo-smart-control-premium-vorgestellt/

**Comment by MetaChuh** [comment]
> Nein, bisher nicht. Ich habe ein paar 1-Phasige Shellys, aber da noch nie wirklich auf die Zeit geachtet, wann welche Daten kommen. Zumindest was die Cloud angeht werden aber demnächst wohl alle Geräte minütlich ihre Werte übertragen:

danke für die info.

cloud verwende ich derzeit nicht, nur die apis der gen1 und gen2 geräte.

falls du code sniplets (bash, php, etc.) für gen1 oder gen2 geräte brauchst, sag bescheid.
gen2 mit rpc api hat gravierende änderungen, hab‘ aber schon fast alles durchprobiert (ist noch nicht alles in der gen2 shelly api dokumentiert)

greetings,
metachuh
