### ISSUE TITLE
Feature Request -  WebGUI Symbole andere Farbe

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1070]
Kann man das orange Häkchen in einer anderen Farbe machen ?  Meinetwegen gelb ?

Beim schnellen drüber schauen geht es mit den anderen orangen Symbolen leicht unter 😉

![IMG_1054](https://github.com/lumapu/ahoy/assets/63048210/f64ae429-a585-4713-a764-c2aa60282ab7)

**Comment by lumapu** [comment]
die Inverter mit dem Status `is available but no data was received until now` bekommen jetzt den grünen Haken, den zuvor dir produzierenden Inverter bekommen haben (in grün).
Letztere bekommen jetzt ein gefüllten Haken auch in grün. 

![grafik](https://github.com/lumapu/ahoy/assets/22733082/493e91b4-5d51-49eb-9f7b-3ab33a06134f)

**Comment by knickohr** [comment]
Ich hab gesagt nicht dringend 😂 Aber gut, wenn’s denn sofort sein muß.

(Das schreibe ich jetzt immer „nicht dringend“, dann isses Morgen gemacht 😇🫣)
