### ISSUE TITLE
[Bug] 0.7.24 - 0.7.25 - Last success Topic wird pro Sekunde gefeuert

### ISSUE THREAD

**Issue by Huschtegutsel** [lumapu/ahoy#1073]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.25

### Github Hash

-

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Standard

### Error description

MQTT Publish steht auf default 0 (publish bei Änderung)

Last success Topic wird pro Sekunde gefeuert... geprüft am Broker/Visu und verbundenem MQTT-Explorer....
MQTT-Client-ID eingetragen, meldet sich damit aber nicht an

![last_success](https://github.com/lumapu/ahoy/assets/71608569/4705a371-e9eb-4fec-964b-3acf475970da)

**Comment by knickohr** [comment]
Ja, da war wohl einer schneller 😉

Aber das wird nicht im Sekundentakt rausgekotzt, sondern bei mehreren Invertern gefühlt im Millisekundentakt 😱

Macht mir den Broker dicht, die Emofangs-LED geht gar nicht mehr aus 😵

Und die Schwuppdizität im WebGUI läßt, vermutlich deswegen, auch wieder zu wünschen übrig 😢

Ganz schnell fixen (nein, ich schreibe besser, hat keine Eile 😂), sonst ist es mit der neuen Release nicht weit her !

![IMG_1058](https://github.com/lumapu/ahoy/assets/63048210/a1808aa2-bc09-4dff-9b55-1cbb351b976c)

**Comment by lumapu** [comment]
😅

**Comment by lumapu** [comment]
das erklärt natürlich auch warum sich mein ESP32 sich so träge anfühlt 😀 Fix ist schon in Arbeit

**Comment by lumapu** [comment]
Build ist in Arbeit - in 10-15min könnt ihr die `0.7.26` installieren. Entschuldigung für diesen blöden Fehler und vielen Dank für das schnelle reporten!

**Comment by keinprofi** [comment]
0.7.26: Fehler ist bei mir noch da:
![img_549](https://github.com/lumapu/ahoy/assets/131543857/3f7f555d-3ecd-4eb3-8d42-ca046662826a)

sieht dann immer wieder so aus:
![img_546](https://github.com/lumapu/ahoy/assets/131543857/869c3813-8ecb-4197-b2e1-f94be13f8daf)

**Comment by lumapu** [comment]
ist dein Wechselrichter mit dem Netz verbunden? Sieht für mich so aus, als würde da die Verbindung fehlen

**Comment by keinprofi** [comment]
Ja, nach Downgrade auf 0.6.9 läuft es wieder einwandfrei (bis auf "total").

0.6.9: 
Die Gesamtleistung pro WR ist korrekt, aber die "Gesamtleistung Panels" nicht. Die steht still
![img_550](https://github.com/lumapu/ahoy/assets/131543857/e786dd53-06ac-4b76-96dc-602367a20984)

edit:
Hier kannst Du sehen wann die 0.6.9. und wann die 0.7.26 aktiv war. Wo der erzeugte Strom angerzeigt wird ist es die 0.7.26, sonst die 0.6.9.
Da der live Verbrauch gegen 0 ist siehst Du auch, dass die WR laufen:
![img_551](https://github.com/lumapu/ahoy/assets/131543857/8fd54bf1-af8e-40b8-98c4-6d74dbf23376)

**Comment by knickohr** [comment]
Was zeigt das braune/orange Feld in der WebGUI ?  Oder haste nur einen Inverter dran ?

**Comment by knickohr** [comment]
> das erklärt natürlich auch warum sich mein ESP32 sich so träge anfühlt 😀 Fix ist schon in Arbeit

Ja, die Schwuppdizität ist ein sehr gutes Indiz für Programmierfehler 😂

**Comment by keinprofi** [comment]
@knickohr 
passt:
![img_552](https://github.com/lumapu/ahoy/assets/131543857/f4366352-4671-4dd9-acd7-27b38cd3702d)

0.6.9:
![img_553](https://github.com/lumapu/ahoy/assets/131543857/aa3df16e-cd8f-4d66-b13f-6a0d5a464603)

Aber viel interessanter ist doch die Frage, warum immer wieder die Verbindung mit der 0.7.26 abbricht...

**Comment by knickohr** [comment]
![Uploading IMG_1060.jpeg…]()

**Comment by lumapu** [comment]
> Ja, die Schwuppdizität ist ein sehr gutes Indiz für Programmierfehler 😂

ich finde das Wort "Schuppdizität" so gut, es passt einfach genau zum Gefühl

**Comment by knickohr** [comment]
https://www.it.niedersachsen.de/startseite/it_news/aktuelles/schwuppdizitat-180256.html#:~:text=Der%20Begriff%20stammt%20urspr%C3%BCnglich%20aus,Computers%20beziehungsweise%20eines%20elektronischen%20Ger%C3%A4tes.

Ach übrigens, bei den Releases fehlt wieder mal der S3-Ordner 😉

**Comment by lumapu** [comment]
komisch, habe das S3 schon ewig nicht mehr getestet - da muss ich die Tage mal die Staubschicht runterkratzen 😉

**Comment by knickohr** [comment]
Mit der 26 ist das ursprüngliche Problem bei mir jetzt weg 👍

**Comment by keinprofi** [comment]
Habs nochmal getestet mit der 0.7.26:
![img_556](https://github.com/lumapu/ahoy/assets/131543857/ab8affb3-e2ce-4304-bc36-b8bfc5fcc746)
![img_559](https://github.com/lumapu/ahoy/assets/131543857/7755cdec-8cd0-43e5-967d-e252c404c011)
![img_561](https://github.com/lumapu/ahoy/assets/131543857/c12e6c00-ea1d-401e-9429-e4251debb314)

Verbindung ist immer wieder weg.
Nach Update keine Einstellungen geändert. Nach Downgrade ebensowenig und funktioniert (außer eben die Daten von "total")

**Comment by Willy541** [comment]
Leider auch mit Version 0.7.26 noch das gleiche Problem, wieder downgrade auf 0.6.29.

**Comment by knickohr** [comment]
Jetzt mal langsam. Der Issue beschreibt jetzt doch schon mindestens 3 Probleme !

@Willy541  :  Um was geht es ?  Gibt’s dazu einen eigenen Issue ?

@keinprofi  :  Wir machen in #1072 weiter

Ansonsten ist das Problem mit den „Last Success“ in der 26 gefixt, zu das Ding wenn @Huschtegutsel damit einverstanden ist.

**Comment by Willy541** [comment]
Nach dem Update auf 0.7.25 und 0.7.26  konnte der Inverter  "Inverter #0: HoyMiles (v0) is not yet available" keine Verbindung aufbauen!
System Information
mac
7C:87:CE:2C:F3:90
sdk
v4.4.4
cpu_freq
240
heap_free
169524
sketch_used
1152
wifi_rssi
-35
ts_uptime
62
version
0.7.26
esp_type
ESP32
heap_total
292224
chip_revision
3
chip_model
ESP32-D0WDQ5
chip_cores
2
Radio
nrf24l01
is not connected
TX count
0
RX success
0
RX fail
0
RX no answer
0
RX fragments
0
TX retransmits
0

**Comment by knickohr** [comment]
Also auch ein Problem für #1072 😉

Nein, doch nicht, dein NRF ist überhaupt nicht mehr verbunden !  Also noch einmal ein ganz anderes Problem.

Les‘ mal im #1072 weiter, vielleicht der Beitrag von DejanBukovec.

**Comment by Willy541** [comment]
Nach downgrade auf 0.6.29:

System Information
mac
7C:87:CE:2C:F3:90
sdk
v4.4.4
cpu_freq
240
heap_free
189348
sketch_used
1101
wifi_rssi
-35
ts_uptime
27
esp_type
ESP32
heap_total
308424
chip_revision
3
chip_model
ESP32-D0WDQ5
chip_cores
2
Radio
nrf24l01+
is connected
Datarate
250 kbps
Power Level
HIGH
TX count
1
RX success
1
RX fail
0
RX no answer
0
RX fragments
1
TX retransmits
0

**Comment by knickohr** [comment]
Überprüft bei der 0.7.x ?

![IMG_1063](https://github.com/lumapu/ahoy/assets/63048210/1453c11c-fcb7-4296-8385-c80b186403b2)

**Comment by Willy541** [comment]
@knickohr 

Beim Punkt "Radio (NRF24L01+)" gibt es kein Feld für einen Haken!

**Comment by knickohr** [comment]
Bei den neuen Versionen schon 😉

**Comment by Willy541** [comment]
OK ich teste!

**Comment by Willy541** [comment]
Abgeschossen, nicht mehr erreichbar!

**Comment by lumapu** [comment]
@Willy541 was heißt das jetzt?

**Comment by knickohr** [comment]
Er hat sich irgendwo verklickert, das Ding bootet nicht mehr 😵

**Comment by MiniOh** [comment]
Mit einem festen MQTT Intervall hat man das "Problem" nicht, richtig?

**Comment by knickohr** [comment]
Wenn das so ist, dann würde ich sogar behaupten das hier tatsächlich ein Kommunikationsproblem mit dem einen oder anderen Inverter vorliegt. Das kann ich bestätigen bei meinen 13 Invertern.  Nicht jeder antwortet immer, es kommt schon mal vor das sich der eine oder andere verschluckt. Denn mit der Einstellung 0 im MQTT-Intervall werden nur Messages gesendet wenn auch was von den WRs empfangen wurde.

Bei gesetztem Intervall (>0] werden halt einfach alte gespeicherte Daten nochmal rausgeballert.

**Comment by Willy541** [comment]
Ich konnte den AhoyDtu nicht mehr erreichen. Nicht mehr per WLAN oder mit der Notfall IP. Im Terminal stand, das ein File corrupt ist . Ich mußte flashen und habe jetzt erstmal 0.6.9 wieder drauf. Ich warte ..... (hatte natürlich kein Backup und mußte alles neu eintragen). War mir mal wieder eine Lehre!

**Comment by knickohr** [comment]
Kommt das Last Success nicht noch ein bißchen zu oft ? 😲

Das kommt ja alle Intervallwerte über alle Inverter.

Nachtrag :  Kann es sein das seit diesem Fix wieder alte Werte (vom Vortag) beim Starten der Inverter nochmal ausgegeben werden ?

**Comment by knickohr** [comment]
Ja, es werden Werte aus der Vergangenheit gesendet 😱

Fixed with Node-Red 😅

![IMG_1080](https://github.com/lumapu/ahoy/assets/63048210/332d0d62-cb73-4475-8721-d65ab2eca0bd)
