### ISSUE TITLE
[Bug] nach Speicher löschen und Neuem Einrichten der DTU funktioniert das ePaper nicht mehr

### ISSUE THREAD

**Issue by Loetnase** [lumapu/ahoy#1075]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus, square dot

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.25 und 0.7.26

### Github Hash

 cbdb150 :: 0.7.26

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Display Config Neueinrichtung nach Speicher Löschen 

### Error description

nach Speicher löschen und Neuem Einrichten der DTU funktioniert das ePaper nicht mehr.
Es fehlt in der Display Config die letzte Zeile  BUSY für den Eintrag GPIO12.
Beim Export der Settings steht im JSON file auch "busy":255, drin. 
Beim Eintragen von 12 und Importieren der JSON Datei funktioniert das ePaper wieder. 
Ist es auch möglich diese 6 Zeilen mit dem Standart vorzubelegen?

Iststand 0.7.25 und 0.7.26
![grafik](https://github.com/lumapu/ahoy/assets/120967249/262d1abe-c586-466a-8b25-648d707caddc)

alter Sollstand
![grafik](https://github.com/lumapu/ahoy/assets/120967249/d4e51d8a-8b73-4666-ad6d-f29161de5b21)

**Comment by knickohr** [comment]
Korrekt, der Versionssprung war zu groß 🫣

Da hat sich einiges an den Einstellungen geändert und es gab Glaubensgemeinschaft auch mal eine inkonsistente JSON. Aber Du hast das Problem ja gefixt 👍

{"type":10,"pwrSafe":true,"pxShift":false,"rotation":2,"contrast":100,"data":13,"clock":14,"cs":15,"reset":26,"busy":12,"dc":27}},"inst":

**Comment by lumapu** [comment]
das wäre doch @knickohr sofort aufgefallen, wenn das epaper nicht mehr geht.
Leider ist mein epaper wohl defekt, ich kann kein Display Update mehr erzwingen - auch nicht mit den simpelsten Beispielen.

**Comment by Loetnase** [comment]
Ich denke das passiert auch nur bei einem neuen ESP32 mit leeren Speicher oder beim kompletten Speicher löschen, ansonsten bleibt ja der Setup im Speicher erhalten. Siehst du und @knickohr im Display Config die 6. Zeile BUSY in der der GPIO 12 einzutragen ist? Die fehlt bei mir. Ich habe dann die JSON Datei exportiert, dort stand bei BUSY 255 drin, die habe ich auf 12 geändert und wieder importiert und ab da hat mein ePaper funktioniert. Vielleicht ist dein ePaper gar nicht kaputt sondern der GPIO 12 wird nicht mehr beschrieben

**Comment by knickohr** [comment]
> das wäre doch @knickohr sofort aufgefallen, wenn das epaper nicht mehr geht.
> Leider ist mein epaper wohl defekt, ich kann kein Display Update mehr erzwingen - auch nicht mit den simpelsten Beispielen.

Nee, isses leider nicht. Nachdem die Config bei mir ja schon korrekt drin ist, hat er ja die passenden Werte. Die JSON ist auch korrekt und wird auch korrekt gesichert. Vermutlich ist nach einem Erase aber das nicht so.

Und ja, es fehlt seit der 25 die 6. Auswahl für den Busy im WebGUI 🤔

**Comment by edw00d4711** [comment]
Fehlt bei mir auch.
![Screenshot 2023-08-07 183918](https://github.com/lumapu/ahoy/assets/5689688/f1daebdb-7872-47e1-a000-75ae581679b2)

**Comment by knickohr** [comment]
Die Auswahl ist wieder da. Ich bin aber direkt zur 28 👍

Warum ich aber hier schreibe :  Die Schwuppdizität ist wieder schlechter 😱 Nicht so schlecht wie zuvor, aber die Live-Seite kann schon mal 10s auf sich warten lassen 🤔

Nachtrag :
Nein, es ist diesmal nicht das MQTT 😅

**Comment by Loetnase** [comment]
> Leider ist mein epaper wohl defekt, ich kann kein Display Update mehr erzwingen - auch nicht mit den simpelsten Beispielen.

@lumapu funktioniert dein ePaper jetzt auch wieder? 
War das der Grund, oder doch kaputt 😅

**Comment by Loetnase** [comment]
> Ist es auch möglich diese 6 Zeilen mit dem Standart vorzubelegen?
@lumapu 
Ist es möglich auch die Standartbelegung vom Pinout ePaper vorzubelegen
![grafik](https://github.com/lumapu/ahoy/assets/120967249/376087a2-06c7-47f4-8e8c-e08f94826ac2)

**Comment by lumapu** [comment]
@Loetnase mein epaper geht weiterhin nicht mehr, keine Ahnung was los ist, habe nichts gefunden wie man prüfen kann wo der Fehler liegt. Am gleichen ESP und Kabel geht ein 4.3" epaper problemlos. (natürlich jeweils angepasste Firmware)

Wann soll der Default geladen werden? sobald man epaper auswählt? oder einen extra Button

**Comment by knickohr** [comment]
Sosooo, das 4,3“ 😅

Magst nicht als Auswahl mit einbauen ? 😇

Ja, die Vorbelegungen bitte bei der Selektion gleich machen. So isses am komfortabelsten.

**Comment by Loetnase** [comment]
Ja da muss ich Knickohr zustimmen. 
Mit Auswahl des ePaper sollte die Vorbelegung der 6 GPIOs stattfinden. 
Dann kann alles manuell verändert werden.
Erst mit Abwahl und erneuter Auswahl des ePaper wird wieder neu vorbelegt. 
Danke 😊😁

**Comment by lumapu** [comment]
vorbelegung baue ich ein.

Das 4.3" wird nicht (von mir) kommen, es war kein Ahoy beim Test beteiligt 😊

Das 1.54" Display hatte ich jetzt sehr lange mit dem Ahoy Logo am Schreibtisch liegen - jetzt mag es leider nichts mehr anderes anzeigen 😢

**Comment by knickohr** [comment]
Das glaube ich so noch nicht. Mein zweites lag bis vor einigen Tagen auch mit dem Ahoy-Logo nur so rum. Es ließ sich problemlos wieder aktivieren. Allerdings war es komplett als DTU aufgebaut.

Und wenn : Ahoy forever ! 😇

**Comment by Loetnase** [comment]
Danke für alles 👍
Ich schließe hiermit das Issue
