### ISSUE TITLE
[Bug] Regression: Boxes for panels not blue anymore

### ISSUE THREAD

**Issue by LeSpocky** [lumapu/ahoy#1091]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.31

### Github Hash

4831945

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

two inverters:

1. HM-400 with one 400 Wp panel
2. HM-600 with two 240 Wp panels

### Error description

Web interface shows boxes for the panels in green now.  Those were blue before.  Looks like a regression after trying to implement #1084 maybe?  See attached screenshot.

![Screenshot_20230814_080538](https://github.com/lumapu/ahoy/assets/661636/e8c1e6fb-80a6-4f8c-a080-19f29d6eccdc)

**Comment by lumapu** [comment]
correct, I will fix this. Copy-Paste issue 😇

**Comment by knickohr** [comment]
Ich möchte bitte in pink 😂

Kann man eigentlich den letzten Alarm auch wieder in das WebGUI einbauen ?
Meinetwegen in den dunkelgrauen Kasten unten wo auch der last success steht ?

**Comment by lumapu** [comment]
ja, dafür muss es aber erst mal funktionieren 🤣
Will das auch haben - Stück für Stück wirds besser.

**Comment by stefan123t** [comment]
Für die AlarmEvents hat Oberfritze im Discord seine Hilfe angeboten @lumapu schau mal wie Du ihm da ggf. Beim PR helfen kannst wenn er so weit ist.

**Comment by LeSpocky** [comment]
Mit v0.7.32 bzw. commit 8544e86 sieht es wieder korrekt aus.  Danke für den schnellen Fix.

**Comment by cibis8** [comment]
bei mir sehen die Farben etwas grau aus :( war ab 7.30 der Fall und hat sich seither nichts verändert...
![Farbe AhoyDTU](https://github.com/lumapu/ahoy/assets/55880017/0898822a-8f1d-4e45-b137-6cbf9cadae5c)

**Comment by lumapu** [comment]
ja das ist auch richtig so. Das graue soll darstellen, dass der Inverter gerade nicht verfügbar ist und von Ahoy als Offline erkannt wird. Quasi ein Status-Check auf den ersten Blick 😀
