### ISSUE TITLE
Enabling MQTT breaks the web interface

### ISSUE THREAD

**Issue by Str8t** [lumapu/ahoy#1092]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.26

### Github Hash

cbdb150

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

- Hoymiles HM600
- Powerlevel set to MIN

### Error description

For a few weeks the device was working fine with software 0.6.9. Then I enabled MQTT with setting a server address. Afterwards I couldn´t really connect to it anymore. There were a lot of timeouts and mostly only the main page available. The website seemed to be loading out of the browsers cache.

Somehow I was lucky and able to update to version 0.7.26 via the web interface. But the issue was not resolved with that version it was even worse.
I can connect to the main page where it says "MQTT is not connected" and the inverter not available. The uptime and the current time are still shown and correct. Opening the settings just shows empty fields, the live view only zero values. But it often also timeouts.
Most of the ping packages are lost. The ones not lost often have a ping of around 2000ms.

I was able to connect to the AP during the startup. I disabled MQTT with removing the IP address. Since then it was working fine without any issue. The inverter was connected and I could see all the values as expected.
After a day, I enabled MQTT again to check if this reproduces the issue. And it does - it is not working anymore.

Just as some other information:
I tested it with different kind of power supplies and different locations, with the same behaviour.
Another ahoyDTU of mine, based on an ESP32 is working since a few months without any problems.

**Comment by knickohr** [comment]
Please update to the last development version 0.7.32.

There are performance issues in some older versions.

**Comment by Str8t** [comment]
Thank you, now it is working fine!
I checked the changelogs beforehand, but did not think any of the changes could fix that.
