### ISSUE TITLE
Inverter alarm [Bug]

### ISSUE THREAD

**Issue by ghost** [lumapu/ahoy#1096]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

7.33

### Github Hash

?

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Hi, happy so far with 7.33
I have tested, alarms inverter, by switching off mains.
some notifictions apear twice
see picture
![alarm](https://github.com/lumapu/ahoy/assets/119303596/0dcea686-835e-4a80-877f-bed049f08508)

**Comment by ghost** [comment]
Or am I misunderstanding, which is also possible

kind regard Herman

**Comment by lumapu** [comment]
I think they should only appear once. For now the alarms are read completely everytime a new alarm is triggered.
I'm in development of this feature so I think it lasts few Dev versions before I'm done with that 😎

Please keep reporting of your findings.
