### ISSUE TITLE
[Bug] Regression: Reboot at midnight not working anymore

### ISSUE THREAD

**Issue by LeSpocky** [lumapu/ahoy#1097]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.33

### Github Hash

9b250c5

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

System config "Reboot Ahoy at midnight" is set according to webpage.

### Error description

1. Installed releases in this order:
    1. v0.5.66
    2. v0.6.0
    3. v0.6.9
    4. v0.7.26
    5. v0.7.31
    6. v0.7.32
    7. v0.7.33
2. Feature worked with v0.7.26
3. Does not work anymore with v0.7.33, device does **not** reboot at midnight

In json settings export the field "rstMidNight" is always false, no matter how the checkbox in the webpage is set.

![Screenshot_20230816-054702_Firefox](https://github.com/lumapu/ahoy/assets/661636/8e4ef351-9eda-4a50-acdf-d10f087a4ae4)
![Screenshot_20230816-054758_Firefox](https://github.com/lumapu/ahoy/assets/661636/1c432873-a8ab-48cc-a30b-44cb0ab9b344)

**Comment by knickohr** [comment]
Try exporting the settings, edit manually, and import again. Maybe a workaround, but not a fix yet 😉

**Comment by LeSpocky** [comment]
> In json settings export the field "rstMidNight" is always false, no matter how the checkbox in the webpage is set.

That's a different field, I suppose belonging to "Reset values and YieldDay at midnight".  

The json member which is actually changed is "wifi.reb".  According to source it is related to `mCfg.sys.schedReboot`.  That setting seems to be set, json export differs in that field, and that field only.  I did not realize that before the first coffee.  ☕

**Comment by LeSpocky** [comment]
If I am not mistaken, the code necessary for the scheduled reboot was added with commit d7eb4a0b982f ("added option to reboot ahoy every 24 hours") but removed with merge commit e4e7e64861a7 ("Merge branch 'development03' into eth") again.  Maybe by accident?

**Comment by lumapu** [comment]
oh thanks for the insight, I will check that. That makes it easy to fix 👍
