### ISSUE TITLE
[Bug] Alarm times one hour off

### ISSUE THREAD

**Issue by LeSpocky** [lumapu/ahoy#1099]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.34

### Github Hash

ac53925

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Two inverters, both start to slightly different times depending on sunlight conditions.  Time set through NTP.  Longitude/latitude set to Magdeburg/Germany.

### Error description

Alarm overlay entries show the wrong time.  Attached are three screenshots which show it.  I had a look at the webpage closely today between 6:00 and 7:00 local time, which is CEST currently.  The inverter 0 started today at around 6:15 local time, the inverter 1 around 6:37 local time.  The webpage however shows the related alarm events an hour later.  Maybe there's something wrong in UTC to localtime conversion?

![Screenshot_20230817_074711](https://github.com/lumapu/ahoy/assets/661636/56335a4d-e838-41ee-b009-a9ac36b4a7e0)
![Screenshot_20230817_074726](https://github.com/lumapu/ahoy/assets/661636/e1b662f8-df24-4827-abf7-3fc1e88130d4)
![Screenshot_20230817_074739](https://github.com/lumapu/ahoy/assets/661636/fe4d2556-d1fd-47c8-adb3-498a0a0c8d8d)

**Comment by knickohr** [comment]
Die Frage ist, wann und wo wird der Zeitstempel gesetzt ?

Kommt der Stempel aus dem Inverter, dann ist es wohl eine Stunde zu spät. Kommt er aus der DTU (nach einem Reboot), dann ist es eine Stunde zu früh ! 🤔

So zumindest bei mir. Ich denke aber die Zeit gibt der Inverter vor und es wird nur einfach umgerechnet. In diesem Fall gibt also der Inverter schon die korrekte Lokalzeit aus, man dürfte daran nichts mehr ändern. Im Changelog sehe ich aber das an der Zeitberechnung was geändert wurde.

**Comment by LeSpocky** [comment]
Note: the difference between UTC and CEST is +2 hours.  It is _not_ CET with +1 hour here, we currently have DST until end of October.

btw: I was wondering how the DTU determines the localtime anyway?  From the longitude/latitude?  As far as I can see there's no timezone setting on the AhoyDTU webpage, right?  Or does the browser do the correction based on browser settings?

**Comment by lumapu** [comment]
yes the correction is done by the browser. There is no timezone setting until now.

The inverter transmits a timestamp starting at 0 but I don't know which timezone is the base. You can simply check `[IP]/api/inverter/alarm/0`. For me it shows `14545`. If you now paste this time to https://www.unixtimestamp.com/ then you will see that it will be `GMT | Thu Jan 01 1970 04:02:25 GMT+0000`. For me adding 2 hours looks correct. (the inverter only receives UTC time)

Edit 1:
I've checked my DB for the entries of Power-AC. The timestamp gives me nearly the same time as the `inverter start` alarm:
`GMT | Thu Aug 17 2023 04:12:41 GMT+0000`

Edit 2:
The temperature has a better correlation:
`GMT | Wed Aug 16 2023 04:04:13 GMT+0000`

**Comment by knickohr** [comment]
Aus der heutigen Release 0.7.36 :

![IMG_1091](https://github.com/lumapu/ahoy/assets/63048210/70fbb15a-6788-4502-b044-41faade109ba)

![IMG_1092](https://github.com/lumapu/ahoy/assets/63048210/93cc6704-a9ae-4b27-ae0a-9eb0a3573165)

![IMG_1093](https://github.com/lumapu/ahoy/assets/63048210/738e7d57-8fde-45b8-9c8f-8ddfc1a4b164)

Das letzte Foto zeigt den Status der einzelnen Inverter. Da sieht man sehr schön, das irgendetwas noch nicht stimmt. Um 7:31 wahren sie alle schon wach und haben fleißig produziert. 6:31 stimmt wohl 😉

Der Timestamp 16284 ist wohl auch korrekt, wenn man daraus die Stunden und Minuten errechnet :  4:31 und halt eben unsere +2 Stunden dazu.

Wie kommt die GUI auf 7:31 ? 😲

**Comment by lumapu** [comment]
hmmm, mal schauen wie das sein kann 😇

**Comment by lumapu** [comment]
Problem gefunden 😀
Der Inveter liefert seinen Timestamp ja für den 01.01.1970. Wenn man für dieses Datum das Zeitzonenoffset berechnet, verwendet man automatisch Winterzeit, also +1 Stunde. Da wir aber aktuell Sommerzeit haben sollten es +2 Stunden sein. Leider wurden bisher beide Zeiten addiert sodass wir +3 Stunden hatten.
Wird gefixt in der nächsten dev `0.7.37`

**Comment by knickohr** [comment]
Ahhh, ich hätte daran denken können !

Ein gleiches Problem hatte ich in Node-Red mit der Uptime der DTU 😅

Hab’s nie hin bekommen. Hier hilft nur, manuell berechnen und sich nicht auf irgendwelche Funktionen verlassen 😱

**Comment by knickohr** [comment]
Purrrfekt ! 👍 

Jetzt müssen wir nur noch die unbekannten Alarmcodes sammeln und heraus finden was sie bedeuten. Hatte eben einen 46 bei einem Inverter 🤔

**Comment by lumapu** [comment]
das gibt's bei OpenDTU schon eine Diskussion dazu:

https://github.com/tbnobody/OpenDTU/discussions/590

**Comment by knickohr** [comment]
Ja, die kenne ich schon 👍

Wie kommen die doppelten Einträge zustande ?

![IMG_1094](https://github.com/lumapu/ahoy/assets/63048210/3206c505-c8b8-4396-8bc8-30a9f3db0303)

**Comment by LeSpocky** [comment]
Mit 4d19e2d sehen die Zeiten heute früh erstmal korrekt aus.  Für beide "Inverter start" Ereignisse wird jetzt eine plausible Zeit angezeigt.
