### ISSUE TITLE
add handling for Responses with Frame ID 0x00

### ISSUE THREAD

**Issue by stefan123t** [lumapu/ahoy#110]
According to [OpenDTU #29 connection problems](https://github.com/tbnobody/OpenDTU/issues/29) the inverter sometimes answers with a Frame ID being zero instead of e.g. 84 being the last frame. This may cause problems in the payload decoder and may cause wrong MQTT messages.

> Thomas formatted the output a little bit:
> ```
>     1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
> RX 95 81 10  2 41 81 10  2 41  1  0  1  1 45  0 52  0 4F  1  B  1  0  0  0 26 D5 34 
> RX 95 81 10  2 41 81 10  2 41  2  0  0 3B 8F  4 EE  5  7  1 46  0 53  0 50  1  D 83 
> RX 95 81 10  2 41 81 10  2 41  3  1  6  0  0 14 B4  0  0 42 78  4 F6  5  E  9 3A C1 
> RX 95 81 10  2 41 81 10  2 41< 0>D9  0 2A  3 D1  1 4C  0  C  B 98 66 
> ```
> The first line shows the index of the bytes.
> Byte 1 - 4: DTU Serial
> Byte 5 - 9: Inverter Serial
> Byte 10: Fragment Number

This seems to be a glitch in the Hoymiles Inverter Firmware (here 1141) which can occur every now and then (e.g. once per day ?).

Please see https://github.com/tbnobody/OpenDTU/commit/c6499e09bd18672e5283106feb72cd899e6ad3c4 for a plausible fix in OpenDTU.

Can this even prevent MQTT/WiFi stack from reconnecting ?

I have seen my ESP8266 stuck in an endless resend loop always claiming he does not get the expected packets. And WiFi connection and MQTT were not responding any more.

similar to 
```
23:16:34.019 -> Requesting Inverter SN 114112345678
23:16:34.019 -> Transmit 27 | 15 12 34 56 78 78 56 34 12 80 0B 00 62 99 37 A4 00 00 00 05 00 00 00 00 F1 BC 85 
23:16:37.040 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:37.040 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:34.019 -> Requesting Inverter SN 114112345678
23:16:34.019 -> Transmit 27 | 15 12 34 56 78 78 56 34 12 80 0B 00 62 99 37 A4 00 00 00 05 00 00 00 00 F1 BC 85 
23:16:37.040 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:37.040 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
23:16:38.566 -> Error while retrieving data: last frame missing: Request Retransmit
23:16:38.566 -> Transmit 11 | 15 12 34 56 78 78 56 34 12 83 AD 
```

But there is also discussion in the same OpenDTU issue # 29 that WiFi Status Events may be returned with different event / state numbers.

**Comment by KG3RK3N** [comment]
Seems that we read the fragment number here:
https://github.com/grindylow/ahoy/blob/ed4a99bf7feb9801af7cd02273a1da1a27fff732/tools/esp8266/app.cpp#L233-L245

I think it would have to look like this to catch it:
```c++
uint8_t *pid = &p->packet[9];
if (*pid == 0x00) {
    DPRINT(DBG_DEBUG, "fragment number zero received and ignored");
} else {
    if((*pid & 0x7F) < 5) {
        memcpy(mPayload[iv->id].data[(*pid & 0x7F) - 1], &p->packet[10], len-11);
        mPayload[iv->id].len[(*pid & 0x7F) - 1] = len-11;
    }

    if((*pid & 0x80) == 0x80) {
        if((*pid & 0x7f) > mPayload[iv->id].maxPackId) {
            mPayload[iv->id].maxPackId = (*pid & 0x7f);
            if(*pid > 0x81)
                mLastPacketId = *pid;
        }
    }
}
```

On my setup I have the issue that the mqtt reconnect very often doesn't work, but I can open the web page from ahoy for the restart. I don't know if this changes can fix that, but I will try that and give feedback after a few days of testing.

**Comment by KG3RK3N** [comment]
Seems that the changes makes no difference on my setup. Reconnection issue still exists.

**Comment by stefan123t** [comment]
@KG3RK3N your change should be alright, would you commit it ? Thanks!
But the FrameID being 0x00 is a very rare symptom, probably it has nothing to do with the reconnect issues.

**Comment by stefan123t** [comment]
Thanks for your commit, I may close the issue for now. Please create a PR.
