### ISSUE TITLE
[Bug] Luminance of SSD1306 cannot be changed

### ISSUE THREAD

**Issue by technics42** [lumapu/ahoy#1106]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+

### Antenna

circuit board

### Power Stabilization

none

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.26

### Github Hash

cbdb150

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Nothing special

### Error description

Changing luminance of display in settings actually does not change luminance/contrast of display.
Regardless of value, the brightness of display is always the same.

**Comment by knickohr** [comment]
Is it really a SSD1306 Controller on the display, or you using a display with another Controller, maybe the 2.42“ OLED with SSD1309 Controller ?

**Comment by technics42** [comment]
Yes, it's really a SSD1306 with 0.96"

**Comment by DanielR92** [comment]
I have a SSD1306 too. But the Luminance makes here no effect... I can reproduce it. 
I use the branch in dev03.

**Comment by kiu77** [comment]
Had this even with an 1,3" display and SH1106. Thought this parameter just nor works. But will double check that now since I know that others have a similar problem.

**Comment by lumapu** [comment]
please test with latest dev version `0.7.46` available in ~20min ([https://fw.ahoydtu.de](https://fw.ahoydtu.de))

**Comment by technics42** [comment]
Thank you, I just tested it.
Luminance can now be changed, but has limited effect - there isn't much change between highest an lowest setting.
To get a wider range, one would need to also make precharge and vcom-deselect values to be changeable - see: https://github.com/olikraus/u8g2/issues/98

**Comment by lumapu** [comment]
@technics42 I think that will be a new feature-request, maybe you create another issue and we collect the interest before implementation.

**Comment by technics42** [comment]
Ok, let's do it this way.
