### ISSUE TITLE
[Bug] Hardware Information missing

### ISSUE THREAD

**Issue by Mogdar-M** [lumapu/ahoy#1114]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.40

### Github Hash

fd2fd20

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT active, no display

### Error description

![Screenshot 2023-08-22 164924](https://github.com/lumapu/ahoy/assets/129499239/041bee26-004c-429e-a828-43d956b23dba)
![Screenshot 2023-08-22 170334](https://github.com/lumapu/ahoy/assets/129499239/5222fe23-12e3-43f0-9824-a68b7b1b482d)

Hardware Code is available via MQTT but not shown in Ahoy

**Comment by knickohr** [comment]
Nicht ungeduldig werden, es kann ein paar Minuten dauern bis die Info vom WR ankommt.

**Comment by Mogdar-M** [comment]
hat 30 Minuten gedauert, jetzt sind Daten da, topic closed
