### ISSUE TITLE
[Bug] Max. values are not correct

### ISSUE THREAD

**Issue by technics42** [lumapu/ahoy#1120]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.36

### Github Hash

ba218ed

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Just using webinterface

### Error description

Max. values (DC/AC) are not properly stored until end of day.
E.g. while one gets >400W at noon, at the evening there is only 40W displayed as max. value.
(max. values differ each day, but surely are no real max. values)

**Comment by knickohr** [comment]
Kann ich nicht nachvollziehen, meine 13 Inverter machen das sauber jeden Tag. War vielleicht der Inverter unter Tags mal weg ?  Gewitter, dunkel ?

**Comment by Solarteur** [comment]
Ich auch nicht. Zwar nur zwei Inverter, aber auch bei diesen werden die Max-Werte der Vergangenheit auch nach dem Neustart am Morgen angezeigt.

**Comment by MetaChuh** [comment]
@knickohr 

> … meine 13 Inverter …

wow, 13 !!! 😳💪
ich hab‘ „nur“ 4 und werd’ schon gefragt ob ich wahnsinnig, süchtig, oder beides bin 😂

@technics42 

max values:

i also can confirm that they are working fine.
the only way this might happen is as mentioned, if the dc voltage drops below 16v , which causes the inverter to shut down, and if it boots again on the same day, it will start from zero.
parallel to this, if the dtu reboots and one or more of the inverters are already offline, the dtu will only see the remaining inverters max values and it does not store the values previous to the reboot for esp flash lifetime reasons.

**Comment by knickohr** [comment]
@MetaChuh 
Bei mir macht das Kleinvieh den Mist. Sind alles nur HM-300 überall auf dem Grundstück verteilt 😲

**Comment by technics42** [comment]
Inverter was not shut down in between.
What could cause the DTU to reboot?
I did not do it manually and did not enable automatic reboot at midnight.
But according to "uptime" it was rebooted somewhere after sunset, so I assume it was also rebooted before.

Just now I recognized there was a reboot about 10 minutes ago. (according to uptime)
What is causing such a reboot?

**Comment by Solarteur** [comment]
> What could cause the DTU to reboot? 

This can have many causes, e.g. an unstable power supply

**Comment by technics42** [comment]
Power supply is fine - could easily deliver more than 10W.
Is there any software issue/setting that could cause a reboot? Multiple or too frequent connects to webserver/REST or inverter polling?
I am polling inverter data every 10 seconds and I am also getting data by REST-api every 10 seconds.
Nrf power level is set to min.

**Comment by Solarteur** [comment]
> Power supply is fine - could easily deliver more than 10W. 

OK. What about the cable? How is the cable connected to the DTU?

How are ESP8266 and nRF24 module wired - plugged in or soldered?

My ahoyDTU (based on ESP32 module) works for weeks without a reboot.

**Comment by technics42** [comment]
Wires are soldered.
Power is provided by USB-cable.
Just right now, when trying to connect to webinterface it was not reachable by some seconds, then uptime was resetted, but I did not see a reboot on the OLED.
Is it possible that only webserver is restarted and also max. values are reset?

**Comment by MetaChuh** [comment]
@technics42 
if the power supply is ok, and 2x 100µF capacitors are present for each 5v and 3.3v, and the esp is not faulty:

it‘s usually that the old debug entpoints /api/record/live are repeatedly used, instead of /api/inverter/id/x, which cause memory problems, due to trying to deliver all data at once.

all /api/record endpoints have been deprecated with 0.7.36 and maybe removed (at least 0.7.40 does not have them any more)

**Comment by technics42** [comment]
I am using api/inverter/id/x and don't think it's a hardware issue.
I was using 0.7.26 before and did not see any reboots (maybe there were some, but I didn't realize it). But now with 0.7.36 I realize them, because of max. values beeing resetted.

**Comment by lumapu** [comment]
how many inverters do you have. For me it sounds that the ESP goes out of heap. Can you try to increase your intervals and check if it's more stable

**Comment by technics42** [comment]
I only use it for one inverter.
Out of heap due to intervals?
Sounds strange to me, but I can try.
Which interval you suspect to cause more heap?
The polling interval to inverter or the interval for getting values by REST-api?

Could you imagine a "reboot" without getting an "ahoy-start-screen" at the OLED?

**Comment by lumapu** [comment]
the default is 30s. Maybe it helps to have two different intervals, eg. 11s and 10s

**Comment by technics42** [comment]
So I am trying to use a different interval for polling the inverter.
(Actually also if both intervalls are the same, they are never started synchroniously.)

**Comment by MetaChuh** [comment]
@technics42 

if you write your control software yourself, you could save the last good yield_day as an offset.

i've implemented this, to be able to change dtu and inverter settings, update, or reboot dtus at any time, without influencing or resetting the daily data within the control.
it also works on unintended reboots and if the inverters go offline twice, due to returning sun, as mentioned above.

here is a little extracted php code sniplet of this control part (could be easily ported to python):

```php

<?php

$inverter_key=0;
$ts_difference=$ts_now-$ts_last_success;	// age of data in seconds

// increment yield_day_max if value is larger and not older than 100s
if ($yield_day > $inverter_array[$inverter_key]["yield_day_max"] and $ts_difference < 100)
{
	$inverter_array[$inverter_key]["yield_day_max"]=$yield_day;
}
			
// save the last known yield_day as offset, after inverter or dtu reboot, after data age verification and if p_ac has new values
if ($yield_day < @$inverter_array[$inverter_key]["yield_day_max"] and $ts_difference < 100 and $p_ac > 0)
{
	$yield_day_offset[$inverter_key]=$inverter_array[$inverter_key]["yield_day_max"];
	$yield_day=$inverter_array[$inverter_key]["yield_day_max"];
}


$yield_day=$inverter_array[$inverter_key]["yield_day"] + $yield_day_offset[$inverter_key];

?>
```

note:

if your control program does not run as a tsr background task (in a loop), you'll need to save the offset and previous max values to file, to re-read them at the next (cron) iteration of your script.

greetings,
metachuh

**Comment by technics42** [comment]
@MetaChuh 
Thanks for your comment/hint 
Actually I am polling from another ESP8266, which is monitoring power meter of the house itself.
I am storing the values on this ESP once a day on its integrated flash (SPIFFS) and can get the values (csv) by downloading them.
(Yes, I could also use an SD-card for that, but I prefer using integrated flash for such little data)

**Comment by MetaChuh** [comment]
very fascinating, intriguing and outside the box thinking, using 2 esps 👍

btw:
i’ve just encountered a possible issue with calculating ts_difference from ts_now and ts_last_success from the dtu, as both will be 0 after reboot, until the time has been synced.
i’ll change that to local time comparison, or overengineer it by additionally comparing ts_now with the local time of the server.

**Comment by technics42** [comment]
After changing inverter polling from 10 to 20 seconds, I did not get a reboot for approx. 40 hours.

**Comment by MetaChuh** [comment]
@technics42 
please dig into this further, as i use 5-10 seconds api query intervals 24/7 on an esp8266 with hardly any dtu reboots in a week.

albeit i only query inverter/id/[0-3]
inverter/list, live etc. are only read once a day, at 00:00h or if the latest ts_uptime value is lower than the previous ts_uptime value (dtu reboot).

do you have a second esp and nrf module you can test on ?

also i don't remember wether you have an 100µF capacitor close to the nrf module for 3.3v.
alternative would be an external 3.3v power supply for the nrf module, to make sure it does not drop the voltage of the esp regulator.

**Comment by technics42** [comment]
@MetaChuh What is your inverter-polling interval?
I changed this from 10 to 20 seconds, but kept REST-api polling at 10 seconds.

As stated above, I don't use an extra capacitor.
This doesn't make any sense to me, as the current drawn by the NRF is very low, especially when set to min-power-level.
I also can't remember any reboots, when using highest power-level, but was using 30s inverter-polling, with prior ahoy version and no REST-api polling.

@lumapu Should one close this issue as it is related to rebooting? Or should one rename this issue?

**Comment by MetaChuh** [comment]
@technics42 
my dtu settings: inverter interval is 10s on dtu 1 and 5s on dtu 2, both with max 5 retries per payload.

capacitor: just give it a try, there could be a reason why it is recommended.

**Comment by technics42** [comment]
@MetaChuh What is your power-level setting for NRF?

**Comment by MetaChuh** [comment]
@technics42 low on the productive dtu running 0.6.9, high on the dev dtu running 0.7.41

**Comment by lumapu** [comment]
can't even follow any more. As I read it from your comments the issue seems solved for me
Solution: increase the poll-intervall which uses the REST API at least to 10s

**Comment by technics42** [comment]
Poll intervall for REST-api never was below 10 seconds! When using 10 seconds I had problems. When using 20 seconds it's ok.
So I close this issue.

**Comment by technics42** [comment]
@MetaChuh I tried with adding a capacitor (100uF) directly to NRF - like I expected, this did not change behaviour.
When setting inverter polling to 10 seconds, DTU will be rebooted frequently. When setting back to 20 seconds it runs stable.
Maybe another difference to your setup is: I am using an OLED - I don't know if you are also using any kind of display.

**Comment by MetaChuh** [comment]
@technics42 
thank you for testing with a capacitor and detailed search for causes.

yes, i also have an oled display on all dtus (sh1106 1.3“ from az-delivery)

i also have one green low current led with a 150Ω resistor connected between 3.3v and rx, and a red lc led with a 150Ω resistor connected between 3.3v and tx.

additionally i have a 100µf capacitor between 5v and gnd, but this is definitively overkill, as my raspberry power supply is more than stable enough.

**Comment by MetaChuh** [comment]
@technics42 
one additional thing that just came to my mind revising different schematics:

i‘ve connected the oled display to 5v instead of 3.3v, as it was within the display’s specifications, to avoid an additional load on the 3.3v regulator of the esp8266.

i hope you can find and eliminate the culprit.
