### ISSUE TITLE
Verbesserungsvorschlag: wäre es möglich bei  "Max power" die Uhrzeit mit anzuzeigen?

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1123]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Gubi2023** [comment]
Verbesserungsvorschlag: wäre es möglich bei "Max power" die Uhrzeit mit anzuzeigen?

**Comment by DanielR92** [comment]
An sich wäre das möglich. Jedoch aktuell noch nicht ganz dringlich hier. :)
Oder wie sehen das die anderen?

**Comment by MetaChuh** [comment]
@DanielR92

nichts ist wirklich dringlich und alles ist wirklich cool 😉

ideen sind immer gut.
viele haben max power mit timestamp sowieso in ihrer steuerung, jedoch wenn es schon standalone diesen wert ab jetzt gibt, ist die idee nicht dringlich, aber ergänzend.

reines brainstorming

**Comment by Gubi2023** [comment]
danke, passt.
