### ISSUE TITLE
[Bug] last_success kommt mir zu oft 😅

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1124]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.41 und davor

### Github Hash

1234567890

### Build & Flash Method

ESP Tools (flash)

### Setup

Multiple Inverters, ePaper, MQTT

### Error description

Das last_success kommt mir ein bißchen zu oft. Bei jedem Inverterticket werden nicht nur die für diesen Inverter spezifischen Werte und sein eigenes last_success ausgegeben, sondern auch die last_success der anderen an der DTU angeschlossenen (obwohl sich deren Werte noch nicht geändert haben).

![IMG_1127](https://github.com/lumapu/ahoy/assets/63048210/7e461a44-5e79-4608-97fa-3a9503bdc73c)

**Comment by knickohr** [comment]
Nein @lumapu , noch nicht fixed 😲

**Comment by lumapu** [comment]
und warum?

**Comment by knickohr** [comment]
Hier mal die „Tickets“ von 2 unterschiedlichen Invertern. Warum kommen beim Inverter 1 auch die last_success von 2 bis 6, bzw. beim Inverter 2, die von 1 und 3 bis 6 ?

![IMG_1135](https://github.com/lumapu/ahoy/assets/63048210/bd3e66a7-8e7a-4c6d-9c4b-fc51af29b24e)

Wie man sieht ändern sich auch nur die Werte von dem betroffenen Inverter, die anderen nicht.

**Comment by knickohr** [comment]
Sie dürfen das „fixed dev“ dran kleben, ich mache zu 😅

![IMG_1136](https://github.com/lumapu/ahoy/assets/63048210/9446c865-1e2a-4e6f-b11f-f313fda83777)

**Comment by knickohr** [comment]
Sorry, tut mit leid 🫣 Aber mit der DEV 56 ist dieser Bug wieder da 😢

Korrektur :  Die DEV 55 macht das auch schon. Weiter bin ich jetzt nicht mehr runter. 

Upps, da scheint noch mehr nicht zu stimmen. Es werden Informationen über die einzelnen Inverter nicht immer ausgegeben 😵

![IMG_1230](https://github.com/lumapu/ahoy/assets/63048210/af46e007-27e0-4f89-9411-cad7bfd4572f)

Bei der DEV 51 kommen die Infos noch richtig. Auch wenn hin und wieder mal ein last_success zu viel drin ist.

Ich sehe gerade im Changelog es gab mit der 52 ein MQTT-Update. Liegt vermutlich daran 🤔

**Comment by knickohr** [comment]
Leider mit der neuen DEV 57 immer noch nicht ganz sauber. Die Alarms sind zwar jetzt weg, nur noch die nötigen, aber das last_success dominiert immer noch heftig.

![IMG_1233](https://github.com/lumapu/ahoy/assets/63048210/9ad702a4-0486-4353-a8b1-d3e3b132d5bb)

Mir kommt es vor, als wenn etwas nicht stimmt mit einem Inverter (keine Antwort, Fehler in der Übertragung, Retransmit, …), dann ballert er immer einen kompletten Satz last_success für alle Inverter raus.

Nachtrag :
Ich habe mir mal das Startverhalten der 51 (die Version die es anscheinend korrekt ausgibt) angeschaut und mußte mit Erschrecken feststellen das sie es auch macht, solange noch nicht alle Inverter einen last_success abgeliefert haben. Hat sich aber jeder Inverter mal korrekt gemeldet, läuft es vorschriftsmäßig. Damit könnte ich sogar leben, ich muß jetzt nur mal schauen was passiert wenn ein Inverter aussteigt. Ob dann das last_success wieder von allen Invertern rausgeballert wird ? 🤔

**Comment by knickohr** [comment]
DEV 58 zeig ähnliches Startverhalten wie die 51. Bis sich alle Inverter ordentlich gemeldet haben ist es durchsetzt mit unendlich vielen last_success. Danach läuft es recht gut, nur wenn ein Inverter sich nicht meldet donnert er für alle Inverter das last_success raus. Da ist noch Optimierungsbedarf 😁

**Comment by knickohr** [comment]
@lumapu 

Workaround von @rejoe2 um zumindest die last_success mit Wert 0 zu unterbinden, die ja eh keine wirklichen Information bereitstellen :

Das mit der "0" bekomme ich in den Griff, allerdings über einen workaround. Für eine wirkliche Lösung müßte imo die publish-Funktion prüfen, zu welchem Inverter der tx-Command eigentlich gehört, und nicht einfach davon ausgehen, dass es für alle dasselbe ist....
Zeile 106 in pubMqttIvData.h
```
  if(mIv->getLastTs(rec) != mIvLastPublish[mIv->id] && mIv->getLastTs(rec) != 0) { 
```

**Comment by knickohr** [comment]
Noch nicht ganz glücklich damit, aber schon wesentlich besser. Mich stört halt immer noch das wenn ein Inverter mal nicht erreichbar ist, immer die llast_success von allen Inverttern raus geballert werden, anstatt nur das vom betroffenen.

**Comment by rejoe2** [comment]
> Noch nicht ganz glücklich damit, aber schon wesentlich besser. Mich stört halt immer noch das wenn ein Inverter mal nicht erreichbar ist, immer die llast_success von allen Inverttern raus geballert werden, anstatt nur das vom betroffenen.

Sagte ja im vorhinein, dass das nur ein workaround ist und man das (auch) imo grundlegender fixen müßte, indem man das letzte Sende-Kommando inverterspezifisch prüft. Leider fehlen mir dazu die Kenntnisse (oder ich müßte mich zu tief eindenken?)...

**Comment by knickohr** [comment]
Ja, man sollte es nur nich in Vergessenheit geraten lassen 🫣

**Comment by knickohr** [comment]
Ja, seit der neuen 0.8.4 ist es besser, muß mir das aber nochmal in Ruhe zu Gemüte führen wenn die 0.8.x stabil bei mir läuft.
