### ISSUE TITLE
Auslesen von <Topic>

### ISSUE THREAD

**Issue by okapi21** [lumapu/ahoy#1128]
Hallo in die Runde,
nachdem ich meine AhouDTU erfolgreich in Betrieb genommen habe, wollte ich meine Daten auf einen mqtt-Server senden.
(mqtt.eclipseprojects.io) Es werden bei <TOPIC>/<INVERTER_NAME_FROM_SETUP>/ch0/#
 **nur angezeigt**-
U_AC / I_AC / P_AC/ Q_AC / F_AC/ PF_AC / Temp / YieldDay / YieldTotal / P_DC/ ALARM_MES_ID / MaxPower

Es werden **nicht angezeigt**-
EVT/ Efficiency / FWVersion/ FWBuildYear/ FWBuildMonthDay / HWPartId / PowerLimit / LastAlarmCode 

wo könnte die Ursache dafür sein ?

**Comment by knickohr** [comment]
Efficiency sollte kommen wen der Inverter arbeitet. Alle anderen Werte kommen nur einmal wenn der Inverter startet, bzw. sich an den Werten was ändert.
