### ISSUE TITLE
[Bug] Versionen ≥ 0.7.36: Fehler in Default-Belegung nrf24

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#1132]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.36+

### Github Hash

ba218ed

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Default

### Error description

Überprüft mit Versionen 0.7.36 / .44 / .45

1. Flash man einen nagelneuen ESP32 mit den obigen Versionen,
ist nach dem Booten auf seiner Webseite 192.168.4.1 zu lesen,
dass die Settings "invalid" wären, auch wenn man den Flash
vor dem Flashen "erasen" lässt.
Eigentlich sollten dann doch passable Default-Werte sein, oder?

2. Setzt man dann die Settings mit "Erase Settings" auf Default-Werte,
dann ist die Belegung des nrF24-Funkmoduls abweichend von der bisherigen
Belegung, was bei mir dauerte, bis es dämmerte.
Bislang war nrf24-CE auf GPIO04 und neu ist der Pin auf GPIO17.
Ist diese Änderung wirklich beabsichtigt?

3. Etwas eher Kosmetisches, aber dennoch unlogisches:
Bei einem frisch geflashten, neuen ESP32 wird nach Eingabe der Daten für einen Inverter
auf der Übersichtsseite angezeigt, dass der Inverter zwar vorhanden sei, aber keine Daten
empfangen würden (bei mir noch wegen der geänderten Belegung des CE-Pins wie zuvor) mit
grünem Häkchen davor. Klickt man dann auf "Sync from Browser", dann findet die DTU den
Inverter nicht und man wird überraschend darüber informiert, dass er "not yet" available wäre. Letztere Meldung wäre ja logisch, wenn der nrf24 wegen falscher Verbindung nicht angesprochen werden kann. Aber die erste Meldung ist nicht adäquat, denn ohne nrf24 kann die DTU ja garnicht wissen, ob der Inverter verfügbar ist.

![Bildschirmfoto 2023-08-30 um 14 33 44](https://github.com/lumapu/ahoy/assets/43971413/f493f294-32cf-4814-94e7-11dce1c0ffdb)

![Bildschirmfoto 2023-08-30 um 13 24 45](https://github.com/lumapu/ahoy/assets/43971413/32b9d4f6-7f29-4e21-987d-811f5878359e)

**Comment by lumapu** [comment]
Komisch, dass die Meldung falsch ist, da aber eine Version vom Inverter bekannt ist, muss eine Verbindung bestanden haben.
Den Default-Pin prüfe ich, danke für den Hinweis.

**Comment by kiu77** [comment]
Ich werde die Version 0.7.46 aufspielen und berichten.

Der Punkt 3. ist aber wirklich merkwürdig:
Bei falsch gesetztem Default-Pin für das nrf24-Modul wird trotzdem nach dem Booten diese Meldung ausgegeben, dass der eingetragene Inverter available sei - obwohl die DTU mangels Kommunikation mit dem Inverter das ja garnicht feststellen kann. Kommen müsste da eigentlich, dass der Inverter not available sei.

**Comment by tobi119** [comment]
Ich bin auch über den GPIO17 gestolpert, wobei man ja immer diskutieren kann, ob ein Default passend ist.
Warum bei mir die Suche etwas gedauert hat: unter System wird dann angezeigt "nrf24l01+ is connected".
Warum das angezeigt wird: ? Es macht einen aber glaubend, dass die Konfiguration passend ist und das Suchen beginnt wo anders.

**Comment by kiu77** [comment]
Die Default-Einstellungen der Pinbelegung sind ab 0.7.47 richtig.
Noch ein kosmetischer Fehler:
Flasht man einen ESP32 neu (mit Erase, dann kommt immer noch die falsche Meldung, dass der Inverter available wäre (but no data...) - was ganz sicher nicht sein kann, da noch kein Inverter angelegt ist in den Settings. 
Ich hab das sogar mal ausprobiert an einem nackten ESP32-BoB, also ohne ein nrf24, und da kommt diese Meldung auch. Sie ist falsch. Siehe Screenshot.
![Bildschirmfoto 2023-09-10 um 13 42 24](https://github.com/lumapu/ahoy/assets/43971413/1b20df1b-e05b-4ebe-932a-fb734242483f)

Zweiter kosmetischer Fehler:
Beim Update der Firmware OTA wählt man die Datei aus und klickt dann auf Update. Das klappt auch. Aber das Textfeld für den Dateinamen ist zu kurz. So kann man z.B. nicht sehen, welche Version die ausgewählte Firmware hat. Also bitte das Feld etwas länger machen, denn Platz ist ja da.
![Bildschirmfoto 2023-09-10 um 19 25 39](https://github.com/lumapu/ahoy/assets/43971413/802e14ea-f171-41f7-8d2b-c47a15b6e292)

Ansonsten finde ich die Firmware nach wie vor toll!

**Comment by lumapu** [comment]
das erste kommt aus dem Cache, kann nicht behoben werden. Dafür muss der Cache geleert werden oder man läd die Seite ohne Cache (`STRG` + `F5`)

das längere Updatefeld ist in der neuen Version `0.7.50` integriert
