### ISSUE TITLE
Inverter Connection bricht immer wieder ab und verbindet sich danach nicht mehr

### ISSUE THREAD

**Issue by theunknownstarman** [lumapu/ahoy#1138]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

board

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

Unabhängig 7.35 od. 7.45

### Github Hash

201098a

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MqTT zu HA
Alle Werte auf Standardinstallation
ESP32 WROOM

### Debug Serial Log output

```shell
09:27:24 I: (#0) prepareDevInformCmd 0x0b
09:27:24 I: TX 27 CH75 | 15 84 99 80 68 89 97 42 64 80 0b 00 64 f4 35 5c 00 00 00 00 00 00 00 00 5a 7f 8f 
09:27:24 I: (#0) nothing received
09:27:54 I: (#0) enqueCommand: 0x01
09:27:54 I: (#0) enqueCommand: 0x0b
09:27:54 I: (#0) prepareDevInformCmd 0x01
09:27:54 I: TX 27 CH3 | 15 84 99 80 68 89 97 42 64 80 01 00 64 f4 35 7a 00 00 00 00 00 00 00 00 31 c7 70 
09:27:54 I: (#0) nothing received
09:28:24 I: (#0) prepareDevInformCmd 0x0b
09:28:24 I: TX 27 CH23 | 15 84 99 80 68 89 97 42 64 80 0b 00 64 f4 35 98 00 00 00 00 00 00 00 00 9f 1d ec 
09:28:24 I: (#0) nothing received
09:28:54 I: (#0) enqueCommand: 0x01
09:28:54 I: (#0) enqueCommand: 0x0b
09:28:54 I: (#0) prepareDevInformCmd 0x01
09:28:54 I: TX 27 CH40 | 15 84 99 80 68 89 97 42 64 80 01 00 64 f4 35 b6 00 00 00 00 00 00 00 00 34 c2 bc 
09:28:54 I: (#0) nothing received
09:29:24 I: (#0) prepareDevInformCmd 0x0b
09:29:24 I: TX 27 CH61 | 15 84 99 80 68 89 97 42 64 80 0b 00 64 f4 35 d4 00 00 00 00 00 00 00 00 5c 79 07 
09:29:24 I: (#0) nothing received
```

### Error description

Ich habe zwei Inverter an der DTU konfiguriert.

Egal ob ich nur einen od. beide einrichte hält im Schnitt die Verbindung maximal einen Tag, manchmal nur ein paar Minuten. Am nächsten Morgen funktioniert die Verbindung noch für max. eine Stunde.  Danach bricht die Verbindung zu beiden Invertern ab und verbindet sich nicht wieder.

Nach mehrmaligem Reboot (mehr als 10 mal etwa) und dann schrittweiser Einrichtung der Konfigurationen
- zuerst nur einen Inverter
- dann zweiten
- dann MqTT
klappt manchmal Verbindung und ist auch stabil bis zum nächsten Ausfall (sowohl WebUI als auch MqTT Verbindung)

Ich habe folgende Lösungsansätze ausprobiert:
- Neuflashen der DTU
- Test mit 7.35 
- Test mit 7.45
- MqTT Konfig gelöscht
- Unterschiedliche Netzteile ausprobiert
- Nur einen Inverter konfiguriert
- Konfig. Einrichtung mit Chrome anstatt Safari

Könnte es an dem ESP32 WROOM liegen?
Gibt es Erfahrungen über Stabilität?

Da, wenn es mit beiden Invertern funktioniert auch die MqTT Verbindung machmal für einen Inverter keine Daten kommen die Frage ob es einen Parameter in der Konfig der DTU gibt um die Datenübertragung etwas zu entlasten? 
Ich brauche nicht alle 30 Sekunden einen Wert. Das reicht auch in größeren Abständen.
Die WLAN Verbindung kann als absolut stabil angenommen werden. Der AP ist in unmittelbarer Nähe. Die WebUI ist auch völlig problemlos immer erreichbar.

Ich habe noch eine DTU mit 8266 unter 0.6.9 laufen. Diese ist völlig stabil.

**Comment by rejoe2** [comment]
>Ich habe noch eine DTU mit 8266 unter 0.6.9 laufen. Diese ist völlig stabil.

Läuft die zeitgleich?!? Die Inverter scheinen irgendwie ihre Lausch-Zeiten auf bestimmten Kanälen mit "ihrer" DTU zu syncen. Wenn dann eine weitere DTU dazukommt, kann das funktionieren, muss aber nicht.

**Comment by theunknownstarman** [comment]
Ist zwar eine gute Idee, aber die 8266 DTU ist außerhalb des Empfangsbereiches der anderen DTU. (Eine ist auf dem Dachboden, eine im Keller. 2 Stöckiges Haus).
Die DTUs laufen alle mit LOW Übertragungsleistung.

**Comment by rejoe2** [comment]
Es geht nicht darum, dass sich die DTU's gegenseitig sehen, sondern ob die mit den Invertern "sprechen"... 
Schalte den ESP8266 ab und erhöhe das Abfrageintervall auf dem ESP32 (30 sec. default sind sehr wenige messages).

**Comment by theunknownstarman** [comment]
Ich bin jetzt mal auf ein 10 Sekunden Intervall für die Inverter.
Mit dieser Einstellung steht die Verbindung zu den beiden am ESP32 konfigurierten Invertern innerhalb kürzester Zeit.

Ich lasse das jetzt mal ein bis zwei Tage laufen und beobachte.

Sollte das Problem noch bestehen, dann schalte ich im zweiten Schritt den 8266 ab um das Problem etwas einzugrenzen.

**Comment by kiu77** [comment]
Nur als Hinweis: Ich habe an einer DTU mit ESP32 zwei Inverter mit 5s Intervall der Abfrage.
Aktiviere ich eine zweite DTU innerhalb 1 m Distanz zur ersten mit 5s Interval und einem der beiden Inverter, klappt das trotzdem zuverlässig. Muss also nicht an einer zweiten DTU liegen.

**Comment by knickohr** [comment]
Wieso müßt ihr eigentlich immer Kuddelmuddel machen. Zum Test EINE DTU, nicht mehr und nicht weniger, alles andere kann, muß aber nicht funktionieren.

Ist ein Elko verbaut ?

**Comment by theunknownstarman** [comment]
Ergebnis bis heute:

Die DTU lief absolut stabil bis heute Morgen um ca. 7:15 Uhr. Danach waren wieder beide Inverter nicht erreichbar. (Vor dieser Uhrzeit wurden allerdings bereits von beiden Anlagen Werte über Solarerzeugung gemeldet)
Die Deaktivierung der zweiten DTU (auf dem Dachboden) brachte keine Besserung.

Seit 07:15 Uhr ist keinerlei Verbindung mehr zu den Invertern mehr möglich.
Die DTU wurde mehr als 10 mal rebootet. Längere Zeit stromlos gemacht.

Die WLAN Verbindung steht stabil. MqTT Übertragung (senden) zum Home Assistant ist stabil - ohne Werte - vorhanden.

**Comment by lumapu** [comment]
zwei DTUs zur gleichen Zeit ist definitiv `unsupported` und kann deshalb hier nicht als `bug` geführt werden. Das ist definitiv experimentell - ich bin nicht dagegen, aber dann führen wir es als `question` oä.

**Comment by theunknownstarman** [comment]
Scheinbar habe ich mich falsch ausgedrückt. Die zweite DTU ist bereits offline und das Problem ist nach wie vor vorhanden. Insofern kann ich ausschließen, dass es an einer zweiten DTU liegt (die über zwei Stockwerke mit entsprechenden Betondecken gegeneinander abgeschirmt ist).

Im Übrigen ist mein Szenario nicht so abwegig, denn es kann ja durchaus zwei Reihenhäuser nebeneinander geben, wo beide Parteien mittels einer DTU ihre Wechselrichter überwachen wollen ...

Mein nächster Plan ist ein Austausch der DTU gegen ein neues Gerät. In den nächsten ca. 2 Tagen werde ich berichten.

**Comment by lumapu** [comment]
achso, ich finde deine letzte Antwort schon wieder zweideutig 😉, weiß jetzt aber sicher, dass nur eine DTU Strom hat.
Lass einfach den Satz mit den Betondecken und gegenseitiger Abschirmung weg, dann ist jedem klar wie deine Situation ist.

Natürlich ist das ein gegebenes Szenario mit den Reihenhäusern und da gehe ich auch davon aus, dass es funktioniert. Es dürfen halt jeweils nur die eigenen Wechselrichter abgefragt werden, denn es ist immer eine Peer-to-Peer Kommunikation.
Das ganze sollte sich wie WLAN verhalten, da darf auch jeder eins (oder mehrere) haben, trotzdem funktonieren sie 'nebeneinander'.

**Comment by knickohr** [comment]
Du hast immer noch nicht die Frage nach dem Elko beantwortet. Oder habe ich was überlesen ?

**Comment by theunknownstarman** [comment]
sorry. Habe ICH überlesen.

Bei der DTU handelt es sich um ein Fertiggerät von einem Händler. Deshalb gehe ich davon aus, dass ein ELKO vorhanden ist, wenn dieser notwendig ist.

**Comment by lumapu** [comment]
diese Händler ... wenn du wüstest was da draußen los ist 🙄

**Comment by knickohr** [comment]
Eigentlich will ich es genau genommen gar nicht wirklich wissen 😞

Und nein, zu 95% ist da aus Geiz-macht-geil-Gründen kein Elko verbaut. Nur schnell den Euro einsacken.

**Comment by rmayergfx** [comment]
Eigentlich wieder mal der Klassiker. Händler verkauft AhoyDTU als Fertiggerät @lumapu sieht keinen Cent davon und soll hier im Forum noch die Probleme lösen.
@theunknownstarman 
Stell hier doch mal einen Link zu dem gekauften "Fertigmodul" ein, damit man sich davon ein Bild machen kann. Alles andere ist Glaskugel lesen.

**Comment by theunknownstarman** [comment]
Das Modul wurde nicht als "Fertigmodul inkl. Software" verkauft sondern NUR die Hardware!

**Comment by rmayergfx** [comment]
Naja, was anderes darf er ja auch nicht ohne mit den Lizenznbestimmungen zu kollidieren.
Hilft dir aber auch nicht weiter, denn du hast die Probleme. Daher wäre es schon wichtig was da verkauft wurde und wie es aufgebaut ist.
Und da du selbst oben geschrieben hast:

> Fertiggerät von einem Händler

ist hier einiges an Spielraum in der Interpretation. Für mich ist ein Fertiggerät genau das was der Name sagt. Anschliessen und fertig.

**Comment by theunknownstarman** [comment]
Ich schließe das Thema und vermerke für mich, dass ich ein Einzelfall bin und es hier im Thread für MICH zu diesem Problem keine Hilfe gibt.

**Comment by theunknownstarman** [comment]
Ich schließe das Thema und vermerke für mich, dass ich ein Einzelfall bin und es hier im Thread für MICH zu diesem Problem keine Lösung gibt.

**Comment by rmayergfx** [comment]
Warum denn das? Es wurde nirgendwo gesagt das du keine Hilfe bekommst, aber du musst uns schon dabei helfen. Warum stellst du nicht die nötigen Informationen dazu ein?

**Comment by kiu77** [comment]
rmaiergfx hat recht. Beleidigtsein bzw. die dahinter liegende Anspruchshaltung ist nicht angemessen. Zumal es ja die Bereitschaft zur Hilfe gab.

**Comment by theunknownstarman** [comment]
Bitte nichts reininterpretieren.

Ich habe weder eine Anspruchshaltung auf Hilfe, noch bin ich beleidigt. 

Mir ging es in meinem Ticket alleinig um eine mögliche Lösung für mein Problem bzw. die Hoffnung, dass ich nicht der einzige bin, der so eine Fehlersituation hat. Offensichtlich bin ich mit diesem Problem eher ein Einzelfall oder sogar der einzige.

Die Tips, die hier formuliert wurden, habe ich alle ausprobiert.  

Zu der DTU bzw. dessen Inhalt (ob mit oder ohne Elko) kann ich nichts sagen, da das Gerät verschlossen und versiegelt ist. Da auf dem Gerät noch Garantie ist tausche ich es aus, um zu sehen ob es evtl. ein hardwarebedingter Fehler vorliegt. Bilder über dessen Inhalt gibt es nicht. Dies ist auch nicht ungewöhnlich, da Händler selten ihre Geräte in offenem Zustand fotographieren.

An einem Handlerbashing werde ich mich nicht beteiligen, da dies nicht der Lösungsfindung dient.

**Comment by rmayergfx** [comment]
Handlerbashing, was soll das denn nun schon wieder? Es geht einzig und alleine darum zu wissen was da verbaut wurde, nicht mehr und nicht weniger. Zur Info, Espressif ESP-WROOM-32 findet man auf einigen Boards, leider gibt es auch da einiges an Spreu. Daher wäre es immer sinnvoll zu wissen was im Endeffekt da verbaut/gekauft wurde. Wenn das Gerät verschlossen und versiegelt ist und man nicht reinsehen kann, sollte es zumindest in der Doku stehen oder ein Schaltplan mit dabei sein.
Zudem hat es der Händler ja auch bestimmt mit einer Version von OpenDTU oder AhoyDTU getestet und mit dieser Version sollte es zumindes auch laufen! Die von dir genannten Versionen sind reine Entwicklerversionen und nicht als "stable" gekennzeichnet. Daher solltest du vielleicht auf die Version gehen, mit der dieses Elektronikmodul vom Händler getestet wurde.

**Comment by lumapu** [comment]
Das wichtige ist wohl nicht die Wirkung des Elko alleine, sondern eine Kombination mit der Leitung bzw. einem Widerstand.
Ich finde Klasse was in issue #1083 herausgefunden wurde und zeugt mMn. davon, dass das NRF Modul nicht die Spannung belastet, sondern auf der Powerleitung eine Störung aussendet. 
Ich bin mir relativ sicher, dass man das hier besprochene Problem mit Modifikationen dieser Art zu einem verlässlichen Begleiter bringen kann .

**Comment by knickohr** [comment]
Ein ähnliches Problem besteht wohl auch mit dem ePaper Display. Zumindest erstmals bei mir. Ein Elko rein und gut ist. Ob es jetzt noch besser ist, da einen Widerstand rein zu machen wäre ein Versuch Wert.

Aber was wir hier mittlerweile alle gelernt haben :  Es geht nicht ohne Elko !  Nicht wenn man Lanzeitstabilität und Funktionssicherheit gewährleisten will. Das sollten sich alle PCB-Entwickler und DTU-Bauer hinter die Ohren schreiben !  Umso wichtiger ist es auch, das wir keine Schaltpläne (Fritzings) mehr raus geben ohne Elko (und Widerstand).

**Comment by theunknownstarman** [comment]
Finaler Endstand:

Die DTU wurde gegen eine Neue ausgetauscht und seither ist kein Ausfall der Inverter Verbindungen mehr feststellbar.
Die zweite DTU ist ebenfalls wieder in Betrieb und es sind keine Störungen feststellbar.
