### ISSUE TITLE
[Bug] Nach flashen des Fusionsboard V1 oder ESP S3 geht nix mehr weder Ota noch VSC

### ISSUE THREAD

**Issue by teletapi** [lumapu/ahoy#1141]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.46

### Github Hash

6b721cb

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

Fusionsboad V1 mit Epaper und ESP32 S3 devkit mit SSH1106

Beim ESP32 funktioniert alles

### Debug Serial Log output

```shell
Kein log möglich, zeigt nix an
```

### Error description

Nach flashen des ESP32 S3 geht garnix mehr, beim Fusionsboard ist es ähnlich nach mehrfachen abstecken ist das Board zwar wieder erreichbar jedoch endlos langsam weder ein reboot funktioniert noch andere änderungen werden übernommen der

**Comment by rmayergfx** [comment]
Probiere doch mal mit den https://esphome.github.io/esp-web-tools/ ob damit das Board wieder funktioniert.
Danach kannst du die passende Firmware auch per OTA einspielen. Wenn es mit ESPHome auch nicht mehr geht, hat vllt. das Board einen Bug/Defekt.

**Comment by teletapi** [comment]
Das Board läuft ja wieder es geht nicht darum das das Board nicht läuft aber die 07.46 ist defekt da geht beim S3 und allen Fusionsboards nix mehr

**Comment by rmayergfx** [comment]
Das ging aus deiner Fehlermeldung nicht hervor. Bitte in Zukunft eindeutig dazuschreiben wenn es mit Version 7.45 noch geht und mit 7.46 nicht mehr und welche Fehler genau auftreten! 
Mit "endlos langsam" kann man nichts anfangen, bitte mal ins Log schauen und dementsprechend hier posten!

PS: Am besten das gleich in den Titel mit reinschreiben, z.B.
V7.46 not working with Fusionsboard V1 and ESP S3

**Comment by lumapu** [comment]
kann das auch jemand anderes bestätigen? Ja gestern war dort eine Änderung, siehe issue #1106

**Comment by DGK110** [comment]
Kann das leider auch bestätigen.

Meine Fusion S3 DTU ist nach Update auf 0.7.4.6 tod!

**Comment by knickohr** [comment]
https://discord.com/channels/984173303147155506/1029761098381017098/1149113574980071585
