### ISSUE TITLE
Feature-Request: CMT2300A GPIO Pins einstellbar in der oberfläche von Ahoy 

### ISSUE THREAD

**Issue by Dirk-Ahoy** [lumapu/ahoy#1150]
Ich würde darum bitten die Pin-Belegung vom CMT2300A auch komplett frei wählbar/ einstellbar zu machen in der Weboberfläche.

Wenn man eine fertige Platine kauft die z.B. OpenDTU Default belegung hat funktioniert CMT nicht mit Ahoy da einige GPIO Pins fest im Code sind.   so geht TX nicht - weiter unten hatte das ja schon mal jemand geschrieben der dann auf opendtu gewechselt ist.

Default CMT Belegung  von openDTU

            "clk": 12,
            "sdio": 14,
            "cs": 27,
            "fcs": 26,
            "gpio2": -1,
            "gpio3": -1

So wäre man flexibel und könnte auch Platinen mit NRF+CMT frei über das Webinterface  belegen.

Vielen Dank im Voraus 

Teste ich gerne bin ja auch im Chat jeden Tag

**Comment by knickohr** [comment]
Oh, schau mal, Issue #1046 scheint ähnlich zu sein 😉

**Comment by lumapu** [comment]
sind beide heute noch gefixt .. `0.7.50` ist im Anmarsch 😁

**Comment by Dirk-Ahoy** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/141040118/0dc3c372-f057-4cf1-acaa-12c9615ec61f)

Vielen dank fürs schnelle einbauen - leider funktioniert das speichern noch nicht nach reboot immer wieder SCK 18 und SDIO 23

**Comment by Dirk-Ahoy** [comment]
in dem exportiertem json file sind bei CMT nur die "vorherigen" 3 Werte drin - ich vermute das dass überhaupt noch nicht gespeichert wird - müssten ja jetzt 5 Werte sein.

**Comment by Jakobi88** [comment]
Danke für's Einbauen @lumapu :)

Selbes Spiel wie bei @Riker18 - es werden keine anderen Belegungen für SCLK und SDIO gespeichert als als die voreingestellten ;)

**Comment by lumapu** [comment]
ok, dann gehe ich mal reparieren, habe schon eine Vermutung

**Comment by Dirk-Ahoy** [comment]
sonst guck auch mal im discord da gibts auch priobleme beim update vom fusion - kann aber auch sein das es damit zusammenhängt

**Comment by lumapu** [comment]
ja, das SPI kann nicht mehr korrekt initialisiert werden, echt eigenartig. Bin noch nicht dazu gekommen.

**Comment by DanielR92** [comment]
Könnte hier die Lösung sein? ****s://github.com/*spressif/esp-idf/issues/2455

**Comment by Dirk-Ahoy** [comment]
guten morgen, hab kurz die 51 getestet - das speichern der CMT Ports geht leider immer noch nicht.  in der exportierten Config weiterhin nur 3 Werte drin.

muss erst mal arbeiten - teste heute Nachmittag mal mit einem werksreset.

**Comment by Dirk-Ahoy** [comment]
hab noch schnell  einen werks-reset gemacht dann geht der NRF auch nicht mehr da sind dann die GPIOS default vom CMT drin da ist noch was vertauscht.   CMT speichern geht weiterhin nicht.

**Comment by knickohr** [comment]
Hier geht’s weiter :  Issue #1159

**Comment by lumapu** [comment]
gefixt in `0.7.53`

**Comment by Jakobi88** [comment]
Frage am Rande:
ist der GPIO3 vom CMT2300A zwingend nötig? Mein PCB hat offenbar keine Verbindung zwischen GPIO3 und dem ESP32...
