### ISSUE TITLE
[Bug] Logo erscheint Nachts nicht mehr im ePaper

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1151]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Version

0.7.49, vielleicht auch schon 0.7.48

### Build & Flash Method

ESP Tools (flash)

### Setup

MQTT, ePaper, Fusion-Board

### Error description

Gerade eben festgestellt das das Ahoy-Logo nicht mehr bei DTU Offline im ePaper erscheint, trotz angehaktem „Turn off while inverters are offline“.

Problem kann schon seit der 0.7.48 bestehen, habe nicht darauf geachtet.

**Comment by lumapu** [comment]
laut Code kann das nicht sein, hast du die DTU neu gestartet nachdem das Setting aktiv gemacht wurde? -> klar, aber ich muss das fragen 😉

**Comment by lumapu** [comment]
evtl. ist dein `TotalPower` noch auf einem Wert > 0 hängen geblieben.

**Comment by knickohr** [comment]
Du hast Recht, es ist tatsächlich ein Wert bei 1,2W hängen geblieben 😵

Ist das nicht sinnvoll das es wenn die DTU offline geht, bzw. Wenn alle Inverter offline gehen das zu Nullen ?  Ja ich weiß, jetzt sind wir wieder bei der Nullen-Diskussion.

Egal, wenn man es weiß, dann ist es auch OK. Kommt wahrscheinlich von dem Gewitter, wurde zu schnell dunkel und die Inverter konnten nicht mehr sauber die State-Machine durchlaufen.

**Comment by lumapu** [comment]
dann brauchen wir evtl. einen Schwellwert

**Comment by knickohr** [comment]
Nee, man müßte das von der State-Machine abhängig machen. Wenn (alle Inverter) offline, dann aus die Maus.

**Comment by knickohr** [comment]
Oder man koppelt das an den Night behavour ?

Aber das stelle ich erst mal zur Diskussion. Nicht das jetzt wieder welche aufschreien 🫣

**Comment by knickohr** [comment]
Konnte es bis jetzt nicht verifizieren, gehe aber davon aus das es nicht mehr vorkommt wenn ein Inverter noch ein paar Milliwatt stehen läßt.

**Comment by knickohr** [comment]
Mach mer mal dicht 😉

Bisher nicht mehr aufgetreten.

**Comment by knickohr** [comment]
Verdammt !

Gerade erst zu gemacht und schon wieder auf machen. Er hat es wieder getan, bei einem Inverter sind knapp 2W hängen geblieben und somit erscheint das Logo Nachts nicht 😢

![IMG_1277](https://github.com/lumapu/ahoy/assets/63048210/5d658f31-450a-4311-bb35-bb8aba7a6146)

**Comment by lumapu** [comment]
hast du auch die 15 Minuten abgewartet? Wir hängen doch jetzt an der Statemachine

**Comment by knickohr** [comment]
Ja habe ich. War bis vor einer Stunde immer noch ohne Logo 😅

**Comment by You69Man** [comment]
@lumapu Der Fix den du hierfür in commit 181cc6fc gemacht hast, wirkt imho nur auf die mono Displays. 
Die mDisplayData Struktur wird vom ePaper (noch) nicht verwendet (wäre aber auch mal gut).

Vorerst müsste man daher also auch hier (in Display.h) noch folgendes ändern:
```
#if defined(ESP32)
        else if (mCfg->type == 10) {
        # mEpaper.loop(totalPower, totalYieldDay, totalYieldTotal, nrprod); -> alt
            mEpaper.loop((allOff) ? 0.0 : totalPower, totalYieldDay, totalYieldTotal, nrprod); 
            mRefreshCycle++;
        }
```

**Comment by lumapu** [comment]
@You69Man wird genauso übernommen, danke für den Hinweis

**Comment by knickohr** [comment]
Auch hier kann man zu machen, ist nicht mehr aufgetreten. Hoffentlich ! 😅
