### ISSUE TITLE
Not possible to add more than 4 Inverters.

### ISSUE THREAD

**Issue by aukator** [lumapu/ahoy#1153]
Hey my problem is to add more than 4 Inverters. Already done an update to 0.7.36.
But the Button "add Inverter" does nothing.
Thx

**Comment by teletapi** [comment]
Sollte aber bekannt sein das beim ESP8266 nur noch 4 Inverter unterstützt werden ich glaub alles was höher als die 0.6.9 ist,
 bin nicht ganz sicher

**Comment by aukator** [comment]
Danke, hab’s durch oberflächliche Suche nicht gefunden. 
Dankeschön das hilft mir. Lg

**Comment by aukator** [comment]
Denke kann somit geschlossen werden.
