### ISSUE TITLE
Details Webgui, System

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1154]
Hi, happy with version, 7.50, ESP32, Build b06f8e9.
I am not using MqTT and since MqTT info is moved to system, it is  labelled ‘False’ and red (other than  CMT2300A; not enabled ).

I would call it 'Icing on the cake' if this could be changed.
Kind regards

**Comment by lumapu** [comment]
what do you want to be changed? The color or the text? Please give an example

**Comment by Peertje-62** [comment]
Dear Lukas,
I like uniformity, Short and sweet.
NRF24L01 – connected and green
CMT2300A – Not enabled and red

I am not using Mqtt = enabled  – false and red 

my proposal would be:
an option to disable Mqtt – not enabled and red.
If enabled and working – connected and green.
If enabled and not working – false and red.

If possible, no hurry, until now it’s working nice 0.7.50 esp 32
I am well aware that I am not the only user.
Other users may have different ideas.

Kind regards
Herman

**Comment by Peertje-62** [comment]
and may be '' Sunrise & Sunset'' instead of Sun, in system.
sorry

**Comment by lumapu** [comment]
This is how it is in `0.7.50`:
MqTT not enabled:
![grafik](https://github.com/lumapu/ahoy/assets/22733082/289a8ec4-a9ad-4d07-a2cd-298364d6b4e5)

MqTT enabled and connected:
![grafik](https://github.com/lumapu/ahoy/assets/22733082/2467b058-f056-49be-994d-eb2f094253c7)

MqTT enabled but not connected:
![grafik](https://github.com/lumapu/ahoy/assets/22733082/bc915af9-ee2f-4dcf-8d19-060541ad5aec)

Should I change anything, I think your request is already met.

**Comment by Peertje-62** [comment]
Hi, I am using 7.50, mine looks differend, what did I do wrong? or do I get it wrong!
(also Night behaviour if disabled could be red)
![ahoy](https://github.com/lumapu/ahoy/assets/144957788/96deb834-c9f4-4285-9b84-c4b35c4293bf)
good night

**Comment by Peertje-62** [comment]
v0.7.51:I don't see any differences, it doesn't matter
Kind regards, Herman
![Ahoy v0 7 51JPG](https://github.com/lumapu/ahoy/assets/144957788/7f703b9d-29dc-449c-b869-307cd9a62625)
