### ISSUE TITLE
CMT Pin belegung wird nicht gespeichert

### ISSUE THREAD

**Issue by teletapi** [lumapu/ahoy#1159]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.51

### Github Hash

GIT SHA: 77ba278 :: 0.7.51

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

Keine änderung

### Error description

Fusionsboard V2 mit FW.07.51 und Epaper, CMT enable geht und wird auch gespeichert
Ändern der Pinbelegung CMT kann nicht gespeichert werden getestet habe ich die vorgeschlagene Belegung SCLK von Pin 6 auf "Off" nach speichern und neustart wurde "off" nicht übernommen und Pin 6 ist wieder hinterlegt
Siehe discord "reference-board"

**Comment by lumapu** [comment]
gefixt in `0.7.53`

**Comment by Dirk-Ahoy** [comment]
53er Version per webtool geflasht da kein Update ging.

Default-Config noch verdreht siehe Bild - wenn man sie aber ändert und speicher ist nach einem reboot CMT und NRF verbunden :)


![grafik](https://github.com/lumapu/ahoy/assets/141040118/a76ec68f-d9ef-424b-bcd7-f6e58738a243)

**Comment by teletapi** [comment]
Ich schließe das dann mal dürfte ja jetzt funktionieren. Danke an alle

**Comment by Jakobi88** [comment]
@Riker18:
blöde Frage:
hast du es geschafft einen HMS-Inverter mit 
SCLK auf GPIO12 
SDIO auf GPIO 14
CSB auf GPIO 27
FCSB auf GPIO26

 zu verbinden?

Bei mir klappt's aktuell nicht :/

**Comment by Dirk-Ahoy** [comment]
Ja läuft

**Comment by Jakobi88** [comment]
@Riker18 Darf ich fragen, was du für eine Antenne auf der 868 Mhz-Seite verwendest??

**Comment by Dirk-Ahoy** [comment]
https://www.amazon.de/dp/B06Y1RNFBT?psc=1&ref=ppx_yo2ov_dt_b_product_details
