### ISSUE TITLE
MQTT Clientname ist immer AHOY-DTU

### ISSUE THREAD

**Issue by HFarryranz** [lumapu/ahoy#116]
AHOY :: 0.4.25

Meldet sich immer als AHOY-DTU beim MQTT-Broker an.

in mqtt.h in  void setup()   hat die Variable DEF_DEVICE_NAME  den Wert "AHOY-DTU"
Es sollte doch aber der Inhalt aus  mDeviceName darin stehen oder?

**Comment by stefan123t** [comment]
@HFarryranz schau mal in #119 bzw. https://github.com/stefan123t/ahoy/commit/1a679130d8d99e17dd921cfa918083b4260fdcb8
Vielleicht stimmt das was ich mir da zusammengereimt habe noch nicht ganz ?

**Comment by stefan123t** [comment]
@HorstG-57 hat das in PR #120 berücksichtigt.

**Comment by stefan123t** [comment]
fixed in #121
