### ISSUE TITLE
Mqtt ClientId wird nicht benutzt

### ISSUE THREAD

**Issue by ghost** [lumapu/ahoy#1161]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.36

### Github Hash

ba218edbdb1b0a168e0c721bc2259fcc97c57f8a

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Unwichtig

### Error description

Kurz und schmerzlos. Die gesetzte Mqtt client id wird nicht benutzt, stattdessen weiterhin {Device Name - die letzten 6 Zeichen der MAC Adresse}
`1694945121: New client connected from 192.168.178.56:60770 as AHOY-DTU-TEST-95E11A (p2, c1, k15, u'12345678').`

**Comment by lumapu** [comment]
der Code selbst spricht was anderes. Dort sieht alles korrekt aus, evtl. muss man mit Debug-Messages prüfen, ob die funktion angesprochen wird.

**Comment by ghost** [comment]
Das wundert mich auch. Habe es ja schließlich eingebaut, nur konnte ich es damals nicht kompilieren und dachte mir 'sieht gut aus, wird passen'.
Debuggen funktioniert nur über VS Code? Oder kann man noch anders loggen?

**Comment by lumapu** [comment]
ich würde es einfach über serielle Ausgaben debuggen. Damit kann man schnell feststellen, ob die erwartete Codestelle ausgeführt wird und kann gleichzeitig noch prüfen, ob die Inhalte erwartungsgemäß sind.
Eine Step-By-Step Debug Methode ist mir nicht bekannt.

**Comment by ghost** [comment]
Hab den Fehler gefunden, in der settings.h -> jsonMqtt fehlt der clientId Eintrag. Ich stelle einen PR #1174

**Comment by lumapu** [comment]
sehr gut, ich weiß die Stelle die du meinst. Ist zwar oben in der Struktur, aber nicht unten beim speichern und laden dabei 😄
