### ISSUE TITLE
Active Power Control in Live View auf Mobilgeräten

### ISSUE THREAD

**Issue by gone-for-coding** [lumapu/ahoy#1165]
Die Änderung vom Text in Active Power Control sorgt auf kleinen Mobilgeräten für relativ viel Platzverschwendung durch die Umbrüche.

Folgende Ideen hätte ich:

- Auf Mobilgeräten einen anderen Text anzeigen (z.B. wieder Limit)
- Generell abkürzen, z.B. APC mit HTML acronym Tag als Hover für den vollen Text
- Elemente anders sortieren könnte auch helfen

Einen Screenshot kann ich gerade leider nicht anhängen, da wirft Github einen Fehler egal in welchem Format.

**Comment by lumapu** [comment]
verstehe das Anliegen, mal sehen was sich am einfachsten implementieren lässt

**Comment by Gubi2023** [comment]
blaues Feld zu schmal für Yield total
![IMG_3974](https://github.com/lumapu/ahoy/assets/142897856/a75f4dda-b99b-4433-85b0-c47bb5ec145c)

**Comment by gone-for-coding** [comment]
Danke @lumapu! Sieht wieder gut aus :) Von mir aus können wir den hier zu machen oder für das andere Thema offen lassen.

**Comment by Ollipop030** [comment]
> blaues Feld zu schmal für Yield total

Scheint ein kleines Display am Handy zu sein. Kannst du im Browser vielleicht die Schriftgröße verkleinern? Oder hast du Bedienungshilfen eingeschaltet? Die Schrift sieht irgendwie so groß aus.

**Comment by Gubi2023** [comment]
stimmt, "grösserer Text" war eingestellt. Jetzt sieht es so aus:
![Unbenannt](https://github.com/lumapu/ahoy/assets/142897856/441bad90-955d-455c-84cb-b84ac201013b)

**Comment by Gubi2023** [comment]
könnte aber bei vierstelligen Anzeigen evtl. auch zu schmal werden(?)

**Comment by Ollipop030** [comment]
Och, ich denke bis da hin kommen hier noch ein paar Versionen. 🤣
