### ISSUE TITLE
v0.7.56 reboot without selecting import file

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#1167]
Just press Import Button on Settings without selecting a file:
![grafik](https://github.com/lumapu/ahoy/assets/105392164/34ddd2df-2d42-4e66-9e8c-53971a164112)
False message, there is no Upload done. Also reboot should not be executed.

**Comment by lumapu** [comment]
der Fehler oder Umstand ist so blöd, dass er schon wieder gut ist. Passiert mir auch regelmäßig 😂

**Comment by Otto-Normal** [comment]
Netzteil abziehen, anstecken. Dann klappt‘s nach dem Rebboot. Zumindest bei mir mit dem ESP8266

**Comment by rmayergfx** [comment]
@Otto-Normal 
Hast du überhaupt  gelesen um was es hier geht? Es wird ohne Validierung ein Reboot durchgeführt. Das geht auch ganz ohne stromlos.
