### ISSUE TITLE
Der Wert für Active Power Control in W ist manchmal nicht formatiert

### ISSUE THREAD

**Issue by GeThi255** [lumapu/ahoy#1171]
## Hardware
  * [x] ESP32

### Version / Git SHA: 
Version: 0.7.58

### Build & Flash Method:
* [x] AhoyDTU Webinstaller

Mir ist aufgefallen, dass der Wert für "Active Power Control" nicht immer richtig formatiert ist. Wenn ich z.B. über mqtt einen neuen max Limit Wert in Watt übergebe, wird dieser in Prozent mit einer Nachkommastelle angezeigt. Der Watt-Wert ist dann manchmal mit 15 Nachkommastellen und evtl. auch nicht ganz richtig.

Normalerweise übergebe ich immer nur neue Limit-Werte im 10er Abstand. Wahrscheinlich habe ich hier 310 W gesendet. In der Anzeige erscheint 20.6% und 309.000000000000006W.

 z.B. 20.6 %, 309.0000000000000000006W

![hc_1674](https://github.com/lumapu/ahoy/assets/23284486/7dd9c73b-7319-4c4d-b9d7-a6f5245eb761)

Runden auf 0 oder 1 Nachkommastelle wäre schön.

VG
Gerd

**Comment by knickohr** [comment]
Runden auf ganze Watt reicht, da man das Limit auch nur in ganzen Wart setzen kann.
