### ISSUE TITLE
HM 400 info

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1176]
Hardware , ESP32; nRF24L01+  external antenna (SMA) ### Power Stabilization: no 
### Version  0.7.56 , ESP Tools

Hi,
My 3e inverter (Hoymiles HM-400) does not show model in ''Info for inverter'' live
![HM 400](https://github.com/lumapu/ahoy/assets/144957788/6d5d1dc9-ea6a-4f3c-a4f7-bb7c695c2251)

**Comment by Peertje-62** [comment]
and in active power control

**Comment by rejoe2** [comment]
https://github.com/lumapu/ahoy/commit/923620f8ded66e5f24f084ca283b0dbb34f1a735

**Comment by Peertje-62** [comment]
What does that mean :923620f
regards

**Comment by rejoe2** [comment]
> What does that mean :923620f regards

just follow the link to the respective commit solving your problem.

So just update to the latest dev version, and see, if that works for you...

**Comment by Peertje-62** [comment]
Thanks
