### ISSUE TITLE
DTU startet sich urplötzlich neu, Timestamp 2 Std falsch!

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1178]
DTU startet sich urplötzlich neu, Timestamp 2 Std falsch!
![2023-09-24 09_28_53-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/57ad631a-1df0-43ff-99b0-94f814a56292)

_Originally posted by @Gubi2023 in https://github.com/lumapu/ahoy/issues/1177#issuecomment-1732510351_

**Comment by knickohr** [comment]
Welche Version hast Du ?  Ich hatte gestern einen ähnlichen Effekt, auch wenn ich das mit der Uhr nicht mehr kontrollieren kann. Aber bei mir war das Intervall auch auf 2,5s verstellt, obwohl ich 5s eingestellt hatte.

Bei mir war es die 0.7.59, genauer gesagt eine modifizierte Version (0.7.591) dessen mit einer erweiterten Funktion und anderem Radioprotokoll des NRF. Das ist auch der Grund warum ich noch keinen Issue aufgemacht habe, weil es eben keine offizielle Version ist. Scheint aber so, als ob der Bug im offiziellen Teil von Ahoy ist. Müssen wir weiter beobachten.

**Comment by Gubi2023** [comment]
Version 0.7.59

**Comment by knickohr** [comment]
Sag mal, wie konntest Du den Reboot im Log eigentlich so genau erwischen ?  Zufall ?  Denn eigentlich müßte nach/ einem Reboot das Log doch leer sein ? 🤔

Hast Du was an der IP verändert, oder hat die DTU eine neue IP bekommen ?

**Comment by Gubi2023** [comment]
das Log läuft in separatem Fenster, wird bei mir nicht gelöscht, auch nicht, wenn die DTU-Zeit neu startet...

**Comment by knickohr** [comment]
OK, habe ich noch nicht probiert. Dann kann ich auch davon ausgehen das sich die IP nicht geändert hat.

**Comment by Gubi2023** [comment]
Zusatz: DTU sendet/empfängt sporadisch 10 min. lang keine Signale vom WR
![2023-09-26 11_46_21-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/c798e4c6-54d1-4fe3-a25f-cf4e8e7da4db)

**Comment by lumapu** [comment]
siehe https://github.com/lumapu/ahoy/issues/1179#issuecomment-1735071508
wird sehr wahrscheinlich in der nächsten Version gefixt sein.

**Comment by Gubi2023** [comment]
#1214
