### ISSUE TITLE
[Bug] multiple Alarms are shown in unsorted order

### ISSUE THREAD

**Issue by servicemensch** [lumapu/ahoy#1187]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.36

### Github Hash

Ba218ed

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

-reboot ahoy at midnight 
- 2 inverter configured

### Error description

Alarms are Shows unsorted wenn multiple Alarms are Listen. Recognized on inverter 2.
Alarms schould be shown in the order of occurance, newest on top.

![IMG_1295](https://github.com/lumapu/ahoy/assets/66994162/cc0f023f-be1f-4339-9bc0-308010e14203)

**Comment by lumapu** [comment]
check with development version, there were changes on this part!
https://fw.ahoydtu.de

**Comment by lumapu** [comment]
is there an update? Do you checked it again with the other version?
