### ISSUE TITLE
Webseitenaufruf beim ESP32 dauert sehr lang

### ISSUE THREAD

**Issue by teletapi** [lumapu/ahoy#1194]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

board

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.60

### Github Hash

963e618

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

.

### Debug Serial Log output

```shell
.
```

### Error description

Ich habe beim ESP32 (38Pin) festgestellt das nachdem ich die 0.7.60 geflasht habe der Webseitenaufruf sehr langsam geht und auch der Wechsel zwischen den Menue seiten(SYStem,Update;Settings usw.) teilweise bis zu 20-25 Sekunden dauert.

Beim ESP32 S3 oder Fusionsboard konnte ich das nicht feststellen.

**Comment by HorstyS** [comment]
Das hatte ich auch am Anfang nach dem Upgrade. Hat sich wieder einigermaßen gelegt aber ist definitiv etwas langsamer als vor der .60

**Comment by rnwgnr** [comment]
Das gleiche bei mir mit der 0.7.60 auf nem ESP32 - mit der 0.7.59 ging das alles noch super zügig.

**Comment by knickohr** [comment]
Und da ist es wieder, das Schwuppdizitätsproblem 😢

Was viel schlimmer ist, es gibt Aussetzer im Abfrageintervall der Inverter. Bei meinen 13 Invertern wird mindestens einer pro Zyklus vergessen. Er wird nicht einmal abgefragt, also kommen auch keine Werte zurück. Kann man in der seriellen Konsole sehr gut erkennen, er wird einfach vergessen, also nicht mal ein TX gesendet.

Da es immer wieder ein anderer Inverter ist, manchmal auch mehrere pro Zyklus, gehe ich davon aus das es nicht inverterspezifisch ist.

(Ein Zyklus = Abfrage aller 13 Inverter)

**Comment by lumapu** [comment]
bin gespannt wo wir uns das wieder eingefangen haben, das waren leider einige Pull-Requests ...

**Comment by lumapu** [comment]
also ein Diff zwischen `0.7.59` (eaa69c5) und `0.7.60` (963e618) sieht nicht tragisch aus. Seid ihr sicher, dass es nicht schon vor `0.7.59` reingekommen ist?

Diff: https://github.com/lumapu/ahoy/compare/eaa69c5...963e618

**Comment by HorstyS** [comment]
Ziemlich. Ich hatte zuvor die .59 und sofort nach dem Update auf die .60 ist es passiert. 
Ich habe eine einfache Konfiguration mit nur einem Inverter, externer Antenne und ohne MQTT oder sonstigen Spielerein (aber ePaper Display). Aber wie gesagt, es hat sich nach ein paar Stunden ziemlich gelegt und ist wieder schneller geworden. Aber nicht so schnell wie meine zweite DTU mit der .59 (mit OLED Display).

**Comment by rnwgnr** [comment]
Bin mir auch sehr sicher das es von .59 auf .60 reingekommen ist, die .59 war super fluffig.

Mit der .60 verliert das Board auch immer wieder mal die WLAN-Verbindung, Aktualisierung des Displays nur alle 1 bis 2 Minuten auch bei kürzer eingestellten Intervallen.

Wollte über die Weboberfläche das Update auf .61 einspielen, bin aber mehrfach gescheitert. Nach dem Klick auf "Update" lädt die Seite entweder ewig oder bricht direkt mit nem Ladefehler ab.

Komm ich noch irgendwie an die .59? Bin recht neu im "DTU-Business". :)

**Comment by knickohr** [comment]
„ Wollte über die Weboberfläche das Update auf .61 einspielen, bin aber mehrfach gescheitert. Nach dem Klick auf "Update" lädt die Seite entweder ewig oder bricht direkt mit nem Ladefehler ab.“

Das deutet tatsächlich auf ein Schwuppdizitätsproblem hin. Habe ich auch immer gehabt. Lösung :  Die DTU im AP-Modus starten und dort den Update über OTA machen.

**Comment by lumapu** [comment]
> Komm ich noch irgendwie an die .59? Bin recht neu im "DTU-Business". :)

ja hier: https://fw.ahoydtu.de

**Comment by rnwgnr** [comment]
> Das deutet tatsächlich auf ein Schwuppdizitätsproblem hin. Habe ich auch immer gehabt. Lösung : Die DTU im AP-Modus starten und dort den Update über OTA machen.

Hab ich grad mal probiert, hat funktioniert. Komischerweise ist der AP scheinbar bei der Verbindung übers Notebook immer "abgestürzt" (Verbindung fehlgeschlagen, AP dann weg), übers Handy gings dann problemlos. Mit 0.7.59 schwuppt es jetzt wieder.

**Comment by teletapi** [comment]
Alsoi der Webseitenaufruf und die Menuewechsel funktionieren mit der 0.7.62 wieder Top beim ESP32

**Comment by teletapi** [comment]
Alsoi der Webseitenaufruf und die Menuewechsel funktionieren mit der 0.7.62 wieder Top beim ESP32

**Comment by teletapi** [comment]
Also der Webseitenaufruf und die Menuewechsel funktionieren mit der 0.7.62 wieder Top beim ESP32

**Comment by teletapi** [comment]
Ich musste das Issue wieder öffnen da ich versehentlich nicht die 0.7.62 auf den ESP32 geflasht hatte sondern das Stable, die 0.7.36 und nachdem ich dann die richtige 0.7.62 wieder geflasht habe erkannt habe das die Version 0.7.62 wohl fehlerhaft ist und dadurch nicht wirklich getestet werden kann

**Comment by knickohr** [comment]
Zu - Auf - Zu - Auf - Blinker 😂
Heute ist eh wieder Updatetag, gleich kommt die 63 😇

**Comment by teletapi** [comment]
closed

**Comment by rnwgnr** [comment]
Closed weil gefixed in .63?

**Comment by knickohr** [comment]
Korrekt
