### ISSUE TITLE
Keine Verbindung zu HM-350

### ISSUE THREAD

**Issue by NewBee51** [lumapu/ahoy#1196]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [x ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version:0.7.36
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [x] Setup settings (use our templates ... to be added)

**Comment by NewBee51** [comment]
Hallo Zusammen,

ich habe mir eine Ahoi - DTU mit dem Wemos D1 ESP32 gebaut. Das Aufspielen der Software hat gut funktioniert, die DTU ist auch im WLAN erreichbar und kann konfiguriert werden.

Leider lässt sich mein WR HM-350 nicht verbinden, die Seriennummer habe ich korrekt eingegeben.

Was kann ich sonst noch prüfen, testen ?

Viele Grüße

NewBee51

Pinning:

![image](https://github.com/lumapu/ahoy/assets/146536215/90c97372-0ae0-4f4c-8778-89526daab78f)

System Status:

![image](https://github.com/lumapu/ahoy/assets/146536215/025d5ded-63d3-44be-af5e-a5ca35e7e430)

**Comment by NewBee51** [comment]
Hier noch ein Auszug aus dem Serial Log:

14:09:16 I: (#0) resetPayload
14:09:16 I: (#0) prepareDevInformCmd 0x0b
14:09:16 I: TX 27B Ch23 | 15 82 84 26 43 80 49 19 40 80 0b 00 65 18 0f ec 00 00 00 00 00 00 00 00 12 ff 1e 
14:09:26 I: (#0) resetPayload
14:09:26 I: (#0) enqueCommand: 0x01
14:09:26 I: (#0) enqueCommand: 0x0b
14:09:26 I: (#0) prepareDevInformCmd 0x01
14:09:26 I: TX 27B Ch40 | 15 82 84 26 43 80 49 19 40 80 01 00 65 18 0f f6 00 00 00 00 00 00 00 00 78 46 dd 
14:09:36 I: (#0) resetPayload
14:09:36 I: (#0) prepareDevInformCmd 0x0b
14:09:36 I: TX 27B Ch61 | 15 82 84 26 43 80 49 19 40 80 0b 00 65 18 10 00 00 00 00 00 00 00 00 00 73 52 21 
14:09:46 I: (#0) resetPayload
14:09:46 I: (#0) enqueCommand: 0x01
14:09:46 I: (#0) enqueCommand: 0x0b
14:09:46 I: (#0) prepareDevInformCmd 0x01
14:09:46 I: TX 27B Ch75 | 15 82 84 26 43 80 49 19 40 80 01 00 65 18 10 0a 00 00 00 00 00 00 00 00 d9 26 ff 
14:09:56 I: (#0) resetPayload
14:09:56 I: (#0) prepareDevInformCmd 0x0b
14:09:56 I: TX 27B Ch3 | 15 82 84 26 43 80 49 19 40 80 0b 00 65 18 10 14 00 00 00 00 00 00 00 00 73 ad ca 
14:10:06 I: (#0) resetPayload
14:10:06 I: (#0) enqueCommand: 0x01
14:10:06 I: (#0) enqueCommand: 0x0b
14:10:06 I: (#0) prepareDevInformCmd 0x01
14:10:06 I: TX 27B Ch23 | 15 82 84 26 43 80 49 19 40 80 01 00 65 18 10 1e 00 00 00 00 00 00 00 00 d9 d9 14 
14:10:16 I: (#0) resetPayload
14:10:16 I: (#0) prepareDevInformCmd 0x0b
14:10:16 I: TX 27B Ch40 | 15 82 84 26 43 80 49 19 40 80 0b 00 65 18 10 28 00 00 00 00 00 00 00 00 72 ac f6

**Comment by rmayergfx** [comment]
Welches motherboard? Pinout prüfen, siehe https://ahoydtu.de/getting_started/

**Comment by rejoe2** [comment]
Und runter mit der Sendeleistung, wenn du nicht grade Dutzende von Metern weg bist vom Inverter!

**Comment by NewBee51** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/146536215/008de0b7-bee4-480f-9085-e1d23ea2771a)
Ich habe diese Platine - in der Beschreibung steht leider nur das Pinning für Open-DTU, ich brauche aber das für Ahoy.

**Comment by lumapu** [comment]
PCB gefunden, leider kein Schaltbild. Nach meiner Analyse (verfolgen der Leiterbahnen) musst du folgendes ändern:
* `IRQ` auf `GPIO17`
* `CE` auf `GPIO16`

Quellen, die ich genutzt habe (Pinout von Wemos D1 ESP32 und NRF24)
* https://github.com/turrican944/OpenDTU-PCB
* https://community.openmqttgateway.com/t/esp32-mini-kit-pinout-is-there-a-mapping-table-to-lolin-esp32-pinout/2320
* https://howtomechatronics.com/tutorials/arduino/arduino-wireless-communication-nrf24l01-tutorial/

**Comment by rmayergfx** [comment]
> ![grafik](https://user-images.githubusercontent.com/146536215/271789808-008de0b7-bee4-480f-9085-e1d23ea2771a.png) Ich habe diese Platine - in der Beschreibung steht leider nur das Pinning für Open-DTU, ich brauche aber das für Ahoy.


Wenn ihr schon spezielle Boards benutzt dann bitte auch gleich in die Anfangspostings mit reinschreiben und auch die Infos auf der Homepage zu den Boards lesen und verlinken damit man sich nicht noch erst alles zusammensuchen muss: https://github.com/turrican944/OpenDTU-PCB

> Das GPIO Pinning ist das Standartpinning vom AhoyDTU. OpenDTU muss entsprechend auf angepasst werden (Deviceprofil.json für OpenDTU mit und ohne Display). GPIO Pins OpenDTU:
IO17 IRQ
IO16 CE
IO5 CS
IO23 MOSI
IO19 MISO
IO18 SCK
IO22 SCL
IO21 SDA

**Comment by lumapu** [comment]
da hätte ich mir paar Minuten sparen können - habe nicht nachgeschaut, ob es irgendwo dokumentiert ist - naja jetzt ist es verifiiert 🙈

**Comment by NewBee51** [comment]
Guten Morgen, ich habe das Pinning jetzt ausprobiert, leider ohne Erfolg. Ich habe auch testweise einmal IO 16 und IO 17 getauscht. Immer noch keine Verbindung zum HM-350

**Comment by rmayergfx** [comment]
Hier das Pinout vom Wemos D1 ESP32 https://www.fambach.net/d1-mini-esp8266-modul-2-2/
Modul stromlos machen und die entsprechenden PINS vom ESP zum NRF mit dem Multimeter durchpiepsen! Hatte auch mal ein Mainboard von einem anderen Hersteller das leider nicht sauber durchkontaktiert war!

**Comment by NewBee51** [comment]
Hurra, es geht jetzt. Ich habe zuerst die Platine durchgepiepst, da war alles O.K. Danach habe ich nochmal alle Lötstellen am Funkmodul nachgelötet - und jetzt funktioniert es. Vielen Dank nochmal für die Unterstützung hier

**Comment by lumapu** [comment]
sehr cool, dann kann man hier zumachen!
