### ISSUE TITLE
NRF System Daten fehlen und kein WR wird gefunden

### ISSUE THREAD

**Issue by teletapi** [lumapu/ahoy#1200]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [X] I will attach/upload an Image of my wiring

### Version

0.7.62

### Github Hash

169eea7

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

.

### Debug Serial Log output

```shell
.
```

### Error description

Nachdem flashen auf die 0.7.62 fehlen in System Menue die Daten fürs NRF und es wird auch kein Wechselrichter mehr gefunden. Ich denke da hat sich iwo ein Fehler eingeschlichen
![Screenshot_2](https://github.com/lumapu/ahoy/assets/94724873/a1fded15-31c1-4836-8152-8620c7f969e3)

**Comment by Dirk-Ahoy** [comment]
Die Daten sind jetzt unter Live - aber NRF geht trotzdem nicht  - CMT geht

**Comment by rmayergfx** [comment]
Siehe: https://github.com/lumapu/ahoy/issues/1198

**Comment by lumapu** [comment]
@teletapi so sieht es jetzt aus:
![grafik](https://github.com/lumapu/ahoy/assets/22733082/9817f5fc-62ae-4f41-9afc-7f9868a978bc)

**Comment by dtuuser** [comment]
Bei mir klappt es auch wieder. Danke

**Comment by teletapi** [comment]
oh danke

**Comment by teletapi** [comment]
Closed
