### ISSUE TITLE
Update nicht möglich[Bug]

### ISSUE THREAD

**Issue by persil14** [lumapu/ahoy#1201]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.59

### Github Hash

3a29d6c

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Einstellungen nicht geändert, nur Update versucht

### Error description

Update auf 0.7.62 nicht möglich. Meldung Update: Neustart erfolgreich ... automatisches Neustart.. aber immer noch die 0.7.59?

**Comment by rmayergfx** [comment]
Same issue again?
https://github.com/lumapu/ahoy/issues/1160#issuecomment-1722527416

**Comment by lumapu** [comment]
hier bei der Fehlersuche in Version `0.7.62` nutze ich dauernd OTA und es funktioniert sicher in alle Richtungen.

**Comment by knickohr** [comment]
Versuch mal die DTU in den AP-Modus zu bringen und dann den Update zu machen.

**Comment by persil14** [comment]
Ok

edit by lumapu: removed email stuff

**Comment by kiu77** [comment]
Zeigt er auch auf dem Display die alte Version an oder nur im Browser?
Bei letzterem dann ein reload der Seite machen.

**Comment by persil14** [comment]
Display hab ich nicht. Zeigt im Browser die Version an. Aber auch vom Smartphone Android 13 nicht möglich. Grüße Peter 

Sent by from my Smartphone.  


Am 1. Oktober 2023, 20:25, schrieb kiu77:

Zeigt er auch auf dem Display die alte Version an oder nur im Browser?
Bei letzterem dann ein reload der Seite machen.

**Comment by knickohr** [comment]
Dann wird wohl nur noch ein Erase & Flash mit den entsprechenden Tools über die USB-Schnittstelle möglich sein.

**Comment by elisenjens** [comment]
Bei mir das gleiche Problem; OTA funzt nicht mehr; für USB Flash muss ich jedes Mal umbauen; wird OTA wieder zum Leben erweckt für 8266 oder muss ich nun die Hardware upgraden?

**Comment by lumapu** [comment]
hab eine Idee hierzu, evtl. könntest du testweise mal MqTT deaktivieren (IP von Broker löschen). Haben hier neulich was umgebaut, nicht dass das hi l in deinem Fall nötig wäre.

**Comment by elisenjens** [comment]
Bin erst morgen wieder zuhause; mach ich dann prompt.

**Comment by elisenjens** [comment]
Habe jetzt die die release-Version mit Erase installiert; dann hat das update auf 0.7.65 funktioniert: Warte jetzt auf Morgen wegen der Reset der Max-Werte...

**Comment by elisenjens** [comment]
Die MAX-Werte sind über Nacht gelöscht; mit der 0.7.65 komme ich heute aber nicht in die Live-Anzeige??? Nach Restart funzt es...

**Comment by lumapu** [comment]
die Max-Werte werden um 00:00 Uhr zurückgesetzt sobald der Haken dafür gesetzt ist. Hier sieht es nach einem heap Problem beim ESP8266 aus. Wie ist denn die `heap-frag`?

**Comment by elisenjens** [comment]
Muss ich morgen checken; jetzt liefert AHOY nix mehr

 Edit by lumapu: E-Mail nonsens entfernt

**Comment by elisenjens** [comment]
Heute das gleiche Bild: komme nicht mehr in die Anzeigen rein; kann deshalb auch nicht sagen, wie die heap-fraq zu dem Zeitpunkt aussieht; nach einem Reboot sieht es dann so aus:

Radio NRF


NRF24L01

connected


NRF24 Power Level

MIN (recommended)


NRF24 Data Rate

250 kbps

MqTT


connected

true


#TX

126


#RX

0

System Information


mac

98:CD:AC:1C:DE:17


sdk

2.2.2-dev(38a443e)


cpu freq

80


heap free

15424


sketch used

566


wifi rssi

-14


ts uptime

103


version

0.7.65


esp type

ESP8266


heap frag

24


max free_blk

10960


core version

3.1.2


flash size

4096


reboot reason

External System

Sun


Sunrise

6.10.2023, 07:29:33


Sunset

6.10.2023, 18:47:04


Communication start

6.10.2023, 07:29:33


Communication stop

6.10.2023, 18:47:04


Night behaviour

not communicating

 

 

Von: Lukas Pusch ***@***.***> 
Gesendet: Donnerstag, 5. Oktober 2023 21:54
An: lumapu/ahoy ***@***.***>
Cc: elisenjens ***@***.***>; Comment ***@***.***>
Betreff: Re: [lumapu/ahoy] Update nicht möglich[Bug] (Issue #1201)

 

die Max-Werte werden um 00:00 Uhr zurückgesetzt sobald der Haken dafür gesetzt ist. Hier sieht es nach einem heap Problem beim ESP8266 aus. Wie ist denn die heap-frag?

**Comment by elisenjens** [comment]
Heap fraq pendelt sich jetzt bei 24 ein

**Comment by elisenjens** [comment]
heap fraq nach 3 Std Laufzeit 25

**Comment by lumapu** [comment]
das ist komisch, die sollte wie bei mir relativ gering sein, habe nach 1 Tag und 17 Stunden eine `heap-frag` von 2 (auch auf einem ESP8266, nur dieser zeigt die fragmentation überhaupt an).

![grafik](https://github.com/lumapu/ahoy/assets/22733082/73497cdf-7f6c-4436-b7af-a6ec48670efb)

**Comment by elisenjens** [comment]
Du bist auch auf 66…

 

Von: Lukas Pusch ***@***.***> 
Gesendet: Freitag, 6. Oktober 2023 16:19
An: lumapu/ahoy ***@***.***>
Cc: elisenjens ***@***.***>; Comment ***@***.***>
Betreff: Re: [lumapu/ahoy] Update nicht möglich[Bug] (Issue #1201)

 

das ist komisch, die sollte wie bei mir relativ gering sein, habe nach 1 Tag und 17 Stunden eine heap-frag von 2 (auch auf einem ESP8266, nur dieser zeigt die fragmentation überhaupt an).

 <https://user-images.githubusercontent.com/22733082/273235818-73497cdf-7f6c-4436-b7af-a6ec48670efb.png>

**Comment by lumapu** [comment]
das macht hier keinen Unterschied

**Comment by elisenjens** [comment]
hab jetzt mit der .66 einen heap frag von 24 nach reboot

**Comment by lumapu** [comment]
kannst du mir einen Export deiner Einstellungen an contact@ahoydtu.de schicken?

**Comment by elisenjens** [comment]
Moin, heute Morgen ist der heap frag wieder 24, aber Ahoy funzt; ich komme in alle Optionen ohne Reboot. Trotzdem anbei die Einstellungen.

Viele Grüße Jens

 

Von: Lukas Pusch ***@***.***> 
Gesendet: Samstag, 7. Oktober 2023 07:42
An: lumapu/ahoy ***@***.***>
Cc: elisenjens ***@***.***>; Comment ***@***.***>
Betreff: Re: [lumapu/ahoy] Update nicht möglich[Bug] (Issue #1201)

 

kannst du mir einen Export deiner Einstellungen an ***@***.*** ***@***.***>  schicken?

**Comment by elisenjens** [comment]
Ein paar Tage lief es; heute kommen die Menüpunkte wieder nicht. Nach Neustart funzt es wieder und der Heap Frag = 26. Hat mein Export geholfen?

**Comment by elisenjens** [comment]
Auch heute funzt es nicht Heap Frag = 26; 25 scheint die magische Grenze zu sein; wird es in der 0.8 dazu Verbesserungen geben? Ich weiß nicht, ob ich da weiter testen soll...

**Comment by elisenjens** [comment]
meine Einstellungen haben keine Erkenntnisse gebracht?

**Comment by lumapu** [comment]
habe bis jetzt nichts bekommen 🤔. Könntest du es nochmal versuchen?

**Comment by elisenjens** [comment]
Na klar, hier nochmal in Anlage meine JSON

 

Von: Lukas Pusch ***@***.***> 
Gesendet: Sonntag, 15. Oktober 2023 12:06
An: lumapu/ahoy ***@***.***>
Cc: elisenjens ***@***.***>; Comment ***@***.***>
Betreff: Re: [lumapu/ahoy] Update nicht möglich[Bug] (Issue #1201)

 

habe bis jetzt nichts bekommen 🤔. Könntest du es nochmal versuchen?

**Comment by elisenjens** [comment]
JSON per Mail-Antwort angekommen?

**Comment by elisenjens** [comment]
das Beantworten der Mails mit Anhang funzt wohl nicht; deshalb hier nochmal meine JSON
[2023-10-15_15-47-17_v0.7.66_ahoy_setup.json](https://github.com/lumapu/ahoy/files/12909723/2023-10-15_15-47-17_v0.7.66_ahoy_setup.json)

**Comment by elisenjens** [comment]
@Lumapu: gibts Erkenntnisse aus meiner Konfig?

**Comment by lumapu** [comment]
sorry, ich habe nie in die Config geschaut. Könntest du nochmal die aktuelle Release-Version testen?

**Comment by elisenjens** [comment]
Update funzt in 0.8.21 OTA, aber morgens ist die DTU offline; muss nachts immer einen Reboot machen. War in den Vorversionen nicht so

**Comment by lumapu** [comment]
das ist aber nicht die Release Version

**Comment by elisenjens** [comment]
sorry, die Rel funzt
