### ISSUE TITLE
Several alarms „DTU command failed“

### ISSUE THREAD

**Issue by lille2000** [lumapu/ahoy#1202]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

O.7.63

### Github Hash

1bbe979

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

ESP8266 with two inverter (HM-600 and -350), e-ink display 

### Error description

After updating to 0.7.64 I had several alarms (~10 within one hour) inside inverter HM-350 which were never observed before „ DTU command failed”

**Comment by lille2000** [comment]
![IMG_1999](https://github.com/lumapu/ahoy/assets/86225787/1dcc8274-0e78-410d-aea5-7d9fdca32245)
![IMG_1998](https://github.com/lumapu/ahoy/assets/86225787/85a1fae9-2426-4cb6-9a1f-cef57a495711)

**Comment by Ollipop030** [comment]
Ist auch unter 0.7.63 der Fall. Der Inverter ist erst 3 Stunden wach, hab schon 23 Alarme "DTU command failed".

**Comment by knickohr** [comment]
Ist bekannt. Bis man genau weiß was der Fehler aussagt, müssen wir es erst mal akzeptieren. Und ein Bug ist es auf jeden Fall nicht, da die Meldung direkt vom Inverter kommt und somit uns was sagen will.

**Comment by lumapu** [comment]
habt ihr eine Art von Limitierung aktiv? Da ist bekannt, dass das der Fehler aus dem inverter kommt wenn man (ahoy) zu schnell den Wert zurückliest

**Comment by knickohr** [comment]
Ja und nein. Es kommt bei meinen HM-300ern sowohl bei dem limitierten als auch von den unlimitierten.

**Comment by MartinBachmannHD** [comment]
Ich hatte es auch einmal die letzten Tage im unlimitierten HM-600... 
Ob Ahoy aus versehen in einer der letzten Versionen doch 'irgend etwas' an den Inverter schickt, was der dann prompt nicht versteht?

**Comment by Ollipop030** [comment]
> habt ihr eine Art von Limitierung aktiv?

Ja in der Tat. Allerdings hatte ich bisher nie so viele Alarme. Bei den ganzen 0.7.5er Releases hatte ich vielleicht 8 Alarme den ganzen Tag, mit dem selben Zero Export. Habe heute nach 5 Stunden schon 39.

Nachtrag:

Grad mal die Logs vom Zero Export durchgesehen: Nach dem Senden des Limits wartet das Script auf das achknowledge vom Inverter, was eigentlich sofort zurückkommt. Der Timeout liegt bei 6 Sekunden. Es kommt hier seit einigen Versionen öfter zu einem Timeout. Die Zeitstempel im Log und in Ahoy passen da genau zusammen.

**Comment by lille2000** [comment]
> habt ihr eine Art von Limitierung aktiv? Da ist bekannt, dass das der Fehler aus dem inverter kommt wenn man (ahoy) zu schnell den Wert zurückliest

Nein, bei mir ist nichts limitiert. Es ist auch definitiv erst seit 0.7.63 so.

**Comment by knickohr** [comment]
Das ist schon vorher so 😉 Kommt nur bei dem einen oder anderen früher oder später.

**Comment by reserve85** [comment]
Bei mir ähnliches Phänomen, die ganze Kommunikation ist sehr schlecht geworden? RX no answer und RX Fail schießen in die Höhe seit Update von .60 zu .65. Seit heute Morgen über 30 Alarme.
Habe einen ESP32, nRF24L01+ und Kommunikation mit nur einem Inverter.
ZeroExport ist bei mir aktuell deaktiviert, ich hatte vorhin allerdings manuell von 60% auf 100% permanent gestellt (einmalig).

Ich kann nachher noch Bilder liefern, bin gerade unterwegs.

edit: 
<img width="524" alt="image" src="https://github.com/lumapu/ahoy/assets/111107925/26c3b895-2e2b-42e3-9456-b405b85fea7b">

auch über MQTT kommen nur noch sporadisch Werte:
<img width="303" alt="image" src="https://github.com/lumapu/ahoy/assets/111107925/3d19a234-5c95-425a-8fa2-ee6721558f68">

edit2: Downgrade auf .60 und alles läuft wieder problemlos. 0 Alarme und problemlose Kommunikation.
-> 
<img width="348" alt="image" src="https://github.com/lumapu/ahoy/assets/111107925/8f2d23fb-92c7-4a41-894b-14cba7aa09fe">

**Comment by lumapu** [comment]
ich sehe bei mir den Fehler auch, allerdings nur bei den inverter, bei den ich heute Morgen das neue Power-Limit-Popup getestet habe.
Habe einmal auf 99% limitiert, dann wieder auf 100%.
Die Fehler sind aber erst heute Mittag im Fehlerspeicher - echt komisch.

**Comment by Ollipop030** [comment]
Seit knapp 3 Stunden läuft bei mir wieder 0.7.59 mit laufendem ZeroExport. Beide Inverter seit dem kein Alarm mehr.

**Comment by BastyESP** [comment]
<img width="645" alt="image" src="https://github.com/lumapu/ahoy/assets/125681883/1239ae0a-3f76-407b-be48-de53194f6f40">

Mir geht das schon ein paar Versionen so, mal einen Tag fast nichts bzw. nur Start und 2-3, und heute von 3 Invertern "947+717+156" Alarme also mal eben knapp über 1800....

Zu dem was ich sehen kann als Alarm ist es faktisch nur die die Zwei, frage aber auch mit 2 DTU die Wechselrichter ab, bzw nur 2 Wechselricheter mit Open und 3 mit Ahoy....trotzdem müsste es ja dann Jeden Tag auftreten...ist aber nicht so.

Tagesende

Nur 1240 Alarme auf dem HM-800 alleine, auf dem HM-400 waren es nur noch 1186 Alarme und der HM-300 belegt mit nur 200 Alarme den dritten Platz.

Lass mir ja gefallen das es ab und zu Mal ne Anfrage gleichzeitig gibt bei den 2 DTU (was man ja nicht machen soll), aber komm ich überhaupt bei 9&11 sek auf die Chancen über 1000 gleichzeitige Abfragen, an einem Oktober Tag hinzubekommen?

**Comment by knickohr** [comment]
Es wäre schön, wenn ihr alle eure HW dazuschreibt, also ob ESP8266 oder ESP32 damit man das Problem, ich nenne es absichtlich nicht Bug, besser eingrenzen kann.

Als Beispiel :  Ich habe 13 Inverter an einem ESP32S3 (Fusion-Board) hängen und habe für heute genau 13 Fehler, alle lauten „Inverter Start“ 😉

**Comment by BastyESP** [comment]
ESP32 (30-PIN) 
0.7.63
3 Inverter
2627 Alarme
Da ich nur die letzten 10 jeweils sehe, lauten alle 2 - DTU Command Failed
Edit. da es oben ja kam, bei mir ist Nichts begrenzt!

Besonderheit, Abfrage von 2 Invertern parallel mit Open DTU.

Hoffe das war richtig so.

**Comment by You69Man** [comment]
Hatte seit der Früh weg die 0.7.63 auf einem ESP32 am laufen (1xHM800). Abgesehen von der Inverter Start Meldung (nur einmal, zur richtigen Uhrzeit) sehe ich keine weiteren 'Alarme' in der Live View. Oder wo sollten die sein?

**Comment by Ollipop030** [comment]
Bin auf dem ESP32. Habe gerade die Logs vom ZeroExport nochmal angesehen. Heute bis Mittag hatte ich ja die 7.63 drauf, da kam quasi im Minutentakt ein Timeout bei ackknowledge nach dem Limitsetzen. Danach lief ab kurz nach Mittag wieder 0.7.59. Da hatte ich diesen Fehler den ganzen Tag nur noch 1x, und Ahoy hatte auch nur noch einen Alarm.

**Comment by lille2000** [comment]
ESP8266, 2 Inverter HM-600 und 350, Häufigkeit bei beiden ca. 10x , abwechselnd. Heute ist der andere betroffen als gestern, kein Power Limit

Vielleicht hilft der Trace. Es ist zwar ein Offset von  2 Stunden im Log, aber sie sind definitiv zeitgleich aufgenommen.

```
05:34:45 I: TX 27 CH61 | [15 82 95 76 26 88 94] [57 42 80 05 00 65] 1b a7 f5 [00 00 00 00 00 00 00] 00 60 df 4d
05:34:45 I: TX 27 CH75 | [15 82 95 76 26 88 94] [57 42 80 11 00 65] 1b a7 f5 [00 00 00 00 00 00 00] 00 74 cb 59
05:35:15 I: TX 27 CH3 | [15 82 85 46 62 88 94] [57 42 80 05 00 65] 1b a8 [13 00 00 00 00 00 00] 00 00 34 0d 46
05:35:15 W: (#0) nothing received: complete retransmit
05:35:15 I: (#0) prepareDevInformCmd 0x11
05:35:15 I: TX 27 CH23 | [15 82 95 76 26 88 94] [57 42 80 11 00 65] 1b a7 f5 [00 00 00 03 00 00 00] 00 74 8f 1e
05:35:15 I: (#1) enqueCommand: 0x00
05:35:15 I: (#1) enqueCommand: 0x0b
05:35:15 I: TX 27 CH40 | [15 82 85 46 62 88 94] [57 42 80 00 00 65] 1b a8 [13 00 00 00 00 00 00] [00 00 31 08 43]
05:35:45 I: (#0) enqueCommand: 0x11
05:35:45 I: (#0) enqueCommand: 0x0b
05:35:45 I: TX 27 CH61 | [15 82 95 76 26 88 94] [57 42 80 11 00 65] 1b a8 [31 00 00 00 00 00 00] [00 00 81 99 35]
05:35:45 I: TX 11 CH75 | [15 82 95 76 26 88 94] 57 42 83 d8
05:35:45 W: (#1) nothing received
05:36:15 I: TX 27 CH3 | [15 82 85 46 62 88 94] 57 42 80 0b 00 65 1b a8 4f [00 00 00 00 00 00 00] 00 f9 ab 7f
05:36:15 I: TX 11 CH23 | [15 82 95 76 26 88 94] 57 42 83 d8
05:36:15 I: TX 11 CH40 | [15 82 95 76 26 88 94] 57 42 84 df
05:36:15 I: TX 27 CH61 | [15 82 95 76 26 88 94] 57 42 80 0b 00 65 1b a8 4f [00 00 00 00 00 00 00] 00 f9 ab 1b
05:36:15 I: TX 11 CH75 | [15 82 95 76 26 88 94] 57 42 82 d9
05:36:45 I: (#0) enqueCommand: 0x0b
05:36:45 I: TX 27 CH3 | [15 82 95 76 26 88 94] 57 42 80 0b 00 65 1b a8 6d [00 00 00 00 00 00 00] 00 58 2b 18
05:36:45 I: alarm ID incremented to 5
05:36:45 I: (#0) enqueCommand: 0x11
05:37:15 I: (#1) enqueCommand: 0x00
05:37:15 I: (#1) enqueCommand: 0x0b
05:37:15 I: TX 27 CH23 | [15 82 85 46 62 88 94] [57 42 80 00 00 65] 1b a8 8b [00 00 00 00 00 00 00] 00 f7 c3 d6
05:37:15 I: TX 27 CH40 | [15 82 85 46 62 88 94] 57 42 80 0b 00 65 1b a8 8b [00 00 00 00 00 00 00] 00 3c c9 1c
05:37:15 I: TX 11 CH61 | [15 82 85 46 62 88 94] 57 42 81 be
05:37:45 I: TX 27 CH75 | [15 82 95 76 26 88 94] [57 42 80 11 00 65] 1b a8 a9 [00 00 00 03 00 00 00] 00 47 16 e7
05:37:45 I: TX 11 CH3 | [15 82 85 46 62 88 94] 57 42 81 be
05:37:45 I: (#0) enqueCommand: 0x0b
05:37:45 I: TX 27 CH23 | [15 82 95 76 26 88 94] 57 42 80 0b 00 65 1b a8 a9 [00 00 00 00 00 00 00] 00 9d 49 7b
05:37:45 W: (#0) nothing received: complete retransmit
05:37:45 I: (#0) prepareDevInformCmd 0xb
05:37:45 I: TX 27 CH40 | [15 82 95 76 26 88 94] 57 42 80 0b 00 65 1b a8 a9 [00 00 00 00 00 00 00] 00 9d 49 7b
```

und die Alarme von inverter #0
![IMG_2001](https://github.com/lumapu/ahoy/assets/86225787/4483241a-75a6-44a5-a994-f82cc6506311)

Edit by lumapu: Übersichtlichkeit des Logs verbessert

**Comment by BastyESP** [comment]
<img width="523" alt="image" src="https://github.com/lumapu/ahoy/assets/125681883/30314d9f-5131-4c4b-bb6c-a65af398d568">
Bei mir gehts heute so weiter...bin schon bei >300

**Comment by knickohr** [comment]
Ich finde das echt spannend !  Ich habe keinen einzigen Alarm, eben außer dem Inverter Start. Scheint wohl ein Ressourcenproblem zu sein ?  Mein ESP32S3 arbeitet das sauber ab.

**Comment by technics42** [comment]
I just tested with ESP-8266, new installed 0.7.65 and HM-inverter is working without any of such alarms.

**Comment by BastyESP** [comment]
> Ich finde das echt spannend ! Ich habe keinen einzigen Alarm, eben außer dem Inverter Start. Scheint wohl ein Ressourcenproblem zu sein ? Mein ESP32S3 arbeitet das sauber ab.

An welcher Ressource solls denn liegen, ist der ESP32 in 6 Monaten, vollkommen verschlissen? Oder NRF Modul abgenutzt? Hab sogar den Kondensator damals nachgerüstet als ich das 2.42er ins Gehäuse verbaut habe und es auf Low gestellt...

Es ging ja bisher auch...und hätte man die Alarm anzeige nicht, würde es nicht mal auffallen...da ich eh nichts Steuer, oder Abfrage (bis auf Live View & Display) macht es auch keine schmerzen.

Kann auch Testweise z.b. mal einen Tag die OpenDTU offline nehmen...wenn es an den Parallelen abfragen liegen sollte, aber der 300er wird ja nur von der Ahoy abgefragt und hat auch schon 157 Alarme drauf...gut der rest zusammen über 2000. Aber es war ja vorher auch nicht so, erst seit ein paar Versionen steigert sich das ja bis auf über 1000 am Tag.

Was ich morgen auf jedenfall mal machen werde von Low weg auf High, ob es besser wird...heute lohnt es sich nicht mehr...bei zusammen unter 50w aus 4 Modulen...

**Comment by Ollipop030** [comment]
> An welcher Ressource solls denn liegen, ist der ESP32 in 6 Monaten, vollkommen verschlissen? Oder NRF Modul abgenutzt? Hab sogar den Kondensator damals nachgerüstet als ich das 2.42er ins Gehäuse verbaut habe und es auf Low gestellt...

Nein, wird wohl an Ahoy liegen. Versuche mal ein Downgrade auf 0.7.59, die Version hat auch heute nur den Alarm für den Inverterstart angezeigt. Wie @reserve85 schon angemerkt hat, ab der 0.7.60 ist wohl der Wurm drin.

**Comment by Ollipop030** [comment]
Gerade spaßeshalber mal die 0.7.65 probiert. DTU Uptime ist jetzt bei knapp 15 Minuten. Inverter 1 zeigt nur den Startalarm, Inverter 2 zeigt knapp alle 30 Sekunden einen Alarm. Scheint, als ob 1 Inverter fehlerfrei funktioniert, ab zweien häufen sich dann die Fehler.

Edit:

Ich habe testweise den 1. Inverter (der keinen Alarm verursacht) in Ahoy deaktiviert. Der Übriggebliebene 2. Inverter verursacht jetzt keinen Alarm mehr, seit 20 Minuten.

**Comment by lille2000** [comment]
Bei mir sind diese „invalid“ Alarme immer zeitlich gruppiert. Wenn ein Alarm eingetragen ist, dann folgt immer ein zweiter Alarm nach 30s. Dann ist immer einer Pause/Lücke bis zum nächsten Alarmpäarchen. 

„alleine“ treten die Invalids nicht auf, auch nicht drei hintereinander.

**Comment by Ollipop030** [comment]
Habe den zweiten Inverter wieder aktiviert und Ahoy neu gestartet. Komischerweise seit 2,5 Stunden keinen Alarm mehr gehabt. Ganz kurios. Bin gespannt, was dann morgen passiert.

Edit:
So, 3,5 Stunden. Jetzt produzieren beide Inverter wieder Alarme, der zweite gerade innerhalb von 5 Minuten 25 Stck, Zahl weiter steigend. Kein klares Muster zu erkennen.

**Comment by reserve85** [comment]
Wie sieht denn bei dir die Radio Statistik aus? Bei mir ist mit der V0.7.65 fast kein RX-Paket mehr erfolgreich empfangen worden.

**Comment by Ollipop030** [comment]
TX count	3366
RX success	1526
RX fail	10
RX no answer	550
RX fragments	9279
TX retransmits	2250

und 

TX count	3324
RX success	1978
RX fail	39
RX no answer	120
RX fragments	7017
TX retransmits	1162

Ist im Rahmen denke ich. Allerdings fällt auf, dass der Obere mehr als 4x so viele "no answer" hat als der Untere. Das ist auch der, der seit einer Stunde wieder Alarme ausgibt.

**Comment by knickohr** [comment]
Welcher Power Level ?

**Comment by Ollipop030** [comment]
> Welcher Power Level ?

Minimum.

**Comment by reserve85** [comment]
Ja beobachte das mal, bei mir konnte ich regelrecht zuschauen wie die fails hochzählten und gleichzeitig inverter errors auftraten.

**Comment by knickohr** [comment]
> > Welcher Power Level ?
> 
> Minimum.

Na, dann Dreh doch mal eins auf und beobachte ob die fail und no answer runter gehen.

**Comment by BastyESP** [comment]
Also ich hab ja wie angedroht auf High gestellt gehabt, gebracht hats nichts. 

HM-800 Alarme 1199
HM-400 Alarme 1681
HM-300 Alarme 89

Irgendwie sollte man die Anzeige einfach nicht beachten, dann gehts.

**Comment by lumapu** [comment]
kann mir einer (oder auch alle?) ein Log zukommen lassen, gerne auch an contact@ahoydtu.de
Würde mir das gerne mal ansehen, meine 3 inverter verhalten sich leider seit dem Report des Fehlers wie Musterknaben 😏

Edit: nicht vergessen den Haken unter `System-Settings` bei `Serial Debug` zu setzten. Sonst sehen wir nur die `TX` Pakete wie bei @lille2000

**Comment by BastyESP** [comment]
@lumapu 
Kannst du mal grob was zu schreiben, wie lange oder was man da abgeben muss? 
Dann mach ich das morgen Nachmittag gerne mal.

**Comment by lumapu** [comment]
das Log am besten aus der Webserial-Console kopieren, nachdem der Fehler `DTU command failed` gekommen ist

**Comment by lumapu** [comment]
ich habe das Gefühl, dass es mit den Retransmits zu tun hat, bin mir aber nicht sicher. Hier muss ich an einer saubereren Kommunikation arbeiten, sodass jeder Inverter einzeln verarbeitet wird, bis klar ist, ob man einen Timeout hat oder noch Retransmitted. Bisher durchlaufen wir die loop über alle Inveter von vorne und senden alles raus was noch offen ist - ein bisschen kuddelmuddel - historisch bedingt.

**Comment by lille2000** [comment]
Hier ist ein Debug-Log

[Logs_DTU_CommandFailed_075307.txt](https://github.com/lumapu/ahoy/files/12812869/Logs_DTU_CommandFailed_075307.txt)

Um ~08:00 habe ich in der WebGui gesehen, dass für 07:53:xx drei (!) "DTU Command failed" eingetragen waren (+ 1x "Inverter Start"). Also 4 Alarme ingesamt.
Seltsam ist: Um 07:59 springt der Zeitstempel plötzlich auf 6:00 zurück und die Alarmliste ist leer. 
Um 8:07 sind wieder drei (!) Einträge drinnen (2x Fail, 1x Start), einer fehlt immer noch.

**Comment by Ollipop030** [comment]
Ich habe gestern und heute mal 0.7.65 und 0.7.59 verglichen. Beide Tests mit exakt gleichen Einstellungen und laufendem Zero Export.

ESP32, NRF mit externer Antenne, Kondensator verbaut. Power Level minimum, knapp 3 Meter Abstand und nur Dämmung dazwischen.

**0.7.65:**

Uptime: 0 Days, 07:53:05 (wobei die Alarme sich erst nach drei Stunden Uptime häuften)

HM-1500 Alarms: 45

```
TX count        6644
RX success	3968
RX fail		75
RX no answer	222
RX fragments	13953
TX retransmits	2171
```


HM-300 Alarms: 82

```
TX count	6718
RX success	3557
RX fail		27
RX no answer	688
RX fragments	13434
TX retransmits	2761
```

```
heap free	176968
heap total	294708

```
Manchmal mehrere Alarme in wenigen Minuten, dann wieder für längere Zeit kein Alarm.


**0.7.59 (hier sind die TX/RX Counter noch kombiniert):**

Uptime: 0 Days, 07:54:54

HM-1500 Alarms: 1 (Startalarm)

HM-300 Alarms: 1 (Startalarm)

```
TX count	13184
RX success	9106
RX fail		26
RX no answer	123
RX fragments	24788
TX retransmits	4825
```
```
heap free	169704
heap total	289188
```

Morgen versuche ich mal eine 0.7.60er, dann mit höherem Power Level.

**Comment by BastyESP** [comment]
Also das was @lumapu fordert, wenn Fehler auftreten ist ja auch ein Geduldsspiel, da es mal wie schon beschrieben, es Minuten lang Fehler hagelt, und dann auch wieder lange ruhe ist...natürlich bewegt sich wenn man es anschaut, ewig nichts an der Alarm anzeige...hab es aber nun an 2 Alarmen hinbekommen, und schicke die Mail mal raus, wenn mehr benötigt wird, einfach was sagen, dann mach ich es morgen nochmal. Schicke erstmal die Mail raus...

**Comment by lumapu** [comment]
Zuerst, @BastyESP hat scheinbar 3 Inverter, 2x 1-Kanalig und 1x 2-Kanalig. Meiner Analyse nach alle 3 HM-Wechselrichter, daher alles über das gleiche Funkmodul und kein Mischbetrieb.

beim Log fällt auf, dass kurz vor der Message ein Kuddel-Muddel ist:
* der Inverter 1 wird abgefragt
* keine Antwort kommt
* nach 10s wird ein kompletter Retransmit angefordert (mit gleichem Timestamp)
* ursprüngliche Nachricht kommt komplett an, Alarm ID bei 0x02ef
* Inverter 1 ist wieder an der Reihe
* Antwort kommt normal, mit der Alarm ID 0x02f1 (2 höher als vorher)

Wir müssen noch mehr Logs sehen, aber ich habe die Vermutung, dass ein Retransmit (evtl. auch nur der complete-Retransmit) nicht 10s später mit dem gleichen Timestamp nochmal erfolgen darf.

**Comment by lumapu** [comment]
@BastyESP evtl. kannst du einfach nebenher die Webserial laufen lassen und bei Gelegenheit einfach alles per `STRG`+`C` rauskopieren und in einem Editor als Text-File speichern. Dann ist es kein Geduldsspiel mehr. Anschließend kannst du darin nach "alarm ID incremented to" suchen und die 50 Zeilen vorher und nachher mir schicken.

**Comment by BastyESP** [comment]
@lumapu Hab noch viele Zeilen, denn das Notebook lief noch, und die Konsole war offen, allerdings hab ich alle ca 10sek eine abfrage, wo wieder kommt das es Nacht ist und keine Kommunikation läuft, wären wenn ich auf Seite suche wohl 74 Alarme...nur wie ich in 10 sek, alles markieren und wenigstens mal sichern kann, ist mir ein rätsel.
 Editor würde mir ja reichen...evtl solltet ihr dafür mal ne Export als "txt" anbieten...

Würde jetzt mal Anbieten, nach Alarm zu suchen, und soviel wie möglich in den 10sek die ich habe zu Kopieren, und dir das zu senden...wäre das OK? Also ich versuch es mal und schicks dir als Mail.


Mail mit ca 30 Meldungen ist raus.

Ansonsten genau richtig, HM-800, HM-400 und HM-300 (allerdings werden die ersten beiden von 2 DTU abgefragt) daher bin ich wohl auch nicht der Idealfall für Fehlerlogs. Aber auch der 300er der nur von Ahoy abgefragt wird steht bei 128 Alarmen, der HM-800 hat heute nur 904 gehabt, und der HM-400 immerhin 1237.

**Comment by lumapu** [comment]
nur 904 😂
danke für die Mail. Nutze doch einfach die Tastenkombinationen in Windows: zuerst `STRG` + `A`, dann direkt `STRG` + `C`. Dann hast du alles im Zwischenspeicher und muss es im Editor der Wahl nur noch einfügen 😉
Wenn die das Scrollen stört kannst du einfach unter der Konsole auch auf `Auto-Scoll` klicken, dann steht dort `manual scroll` und du hast alle Zeit der Welt.

**Comment by lille2000** [comment]
Ich teile die Vermutung, dass die Inverter 2 identische Requests (= Retransmit mit der selben Payload inkl. dem Zeitstempel) nicht mögen. Vermutlich wird die erste Nachricht empfangen und sogar beantwortet. Die Antwort geht vollständig verloren. Die DTU sendet die identische Nachricht nochmal und der Inverter lehnt die Nachricht als „verbraucht/bereits geantwortet“ ab und trägt einen Fehler ein. 

vielleicht sollte ein Retransmit die Zeitstempel  vor dem erneuten Senden aktualisieren.

**Comment by BastyESP** [comment]
Der Tipp mit Strg+A war Spitze, damit ging es, hab es mir mal als txt gespeichert, aber hast ja erstmal wahrscheinlich Auswahl.
Das mit dem Manual scroll etc wollte ich alles nicht probieren...da die DTU wohl vor 2h abgekackt war (zumindest Uptime knapp über 2h, und ich nur von den Bestand im Browser gelebt habe...wenn der neu Läd sind alle Daten weg...

**Comment by lumapu** [comment]
ja dieser Kuddel-Muddel muss weg. 

So muss es sein:
1. Inveter wird abgefragt
2. Antwort wird geprüft, bei fehlenden Nachrichten wird neu angefragt
3. Antworten werden geprüft, wenn vollständig -> ok, wenn nicht -> failed
4. nächster Inverter wird abgefragt

zwischen 1. und 3. sollte max. ca. eine Sekunde sein und nicht wie jetzt teilweise 10s.

@BastyESP super, ja dein letztes Log ist sehr umfangreich, das verdaue ich morgen 😉. Im Schnelldurchlauf habe ich gesehen, dass Fehlereinträge für alle 3 Inveter dabei sind, das ist perfekt.
Das Log ist nur im Browser gespeichert, nicht im ESP. Evtl. kannst du morgen mal paar Stunden auf die zweite DTU verzichten und nochmal für mich loggen.

**Comment by Ollipop030** [comment]
Habe auch mal mitgeloggt. Lief knapp eine Stunde ohne Alarm. ESP32, 0.7.66

[Log.txt](https://github.com/lumapu/ahoy/files/12828160/Log.txt)

**Comment by lumapu** [comment]
@Ollipop030 danke für dein Log. Du hast scheinbar ein sehr kurzes Intervall. Was mir hier auffällt wäre die sofortige Abfrage des gesetzten Powerlimits schon nach einer Sekunde. Evtl. sollte man hier die Zykluszeit beachten (Ahoy).
Noch ein Hinweis bzgl. der SN: Wenn du sie unkenntlich machen willst, dann bitte auch bei allen TX nach der 15 die nächsten 4 Gruppen unkenntlich machen und bei RX identisch nach der 95.
Evtl. sollten wir hier einen Feature-Request anlegen, der quasi privacy hier automatisch aktiviert.

z.B.
```
TX 27 CH3 | 15 ** ** ** ** 85 37 85 60 80 0b 00 65 1f b1 7b 00 00 00 00 00 00 00 00 b2 09 8c 
```

**Comment by Ollipop030** [comment]
> Du hast scheinbar ein sehr kurzes Intervall. Was mir hier auffällt wäre die sofortige Abfrage des gesetzten Powerlimits schon nach einer Sekunde.

Das ist der wohl meiner Nulleinspeisung geschuldet, sieht dann so aus:
```
2023-10-06 10:13:52,146 INFO     Ahoy: Inverter "HM-1500": setting new limit from 397 Watt to 402 Watt
2023-10-06 10:13:52,829 INFO     Ahoy: Inverter "HM-1500": Limit acknowledged
2023-10-06 10:13:52,830 INFO     Ahoy: Inverter "HM-300": setting new limit from 79 Watt to 80 Watt
2023-10-06 10:13:53,514 INFO     Ahoy: Inverter "HM-300": Limit acknowledged
```
Ist alles sehr schnell verarbeitet, war aber bisher unkritisch, siehe auch meinen Beitrag von gestern.

**Comment by lumapu** [comment]
keine Kritik am eingestellten Intervall, ich will nur verstehen wie es zu dem Fehlercode kommen könnte. War eher selbstkritisch gemeint 😉

**Comment by stefan123t** [comment]
> @Ollipop030 danke für dein Log. Du hast scheinbar ein sehr kurzes Intervall. Was mir hier auffällt wäre die sofortige Abfrage des gesetzten Powerlimits schon nach einer Sekunde. Evtl. sollte man hier die Zykluszeit beachten (Ahoy). Noch ein Hinweis bzgl. der SN: Wenn du sie unkenntlich machen willst, dann bitte auch bei allen TX nach der 15 die nächsten 4 Gruppen unkenntlich machen und bei RX identisch nach der 95. Evtl. sollten wir hier einen Feature-Request anlegen, der quasi privacy hier automatisch aktiviert.
> 
> z.B.
> 
> ```
> TX 27 CH3 | 15 ** ** ** ** 85 37 85 60 80 0b 00 65 1f b1 7b 00 00 00 00 00 00 00 00 b2 09 8c 
> ```

Es sollte noch die Inverter Nummer #1..16 erkennbar sein oder noch besser die Modell Nummer und das Produktionsdatum also die ersten sieben/acht Stellen der Seriennummer stattdessen verwenden ?

**Comment by stefan123t** [comment]
> Zuerst, @BastyESP hat scheinbar 3 Inverter, 2x 1-Kanalig und 1x 2-Kanalig. Meiner Analyse nach alle 3 HM-Wechselrichter, daher alles über das gleiche Funkmodul und kein Mischbetrieb.
> 
> beim Log fällt auf, dass kurz vor der Message ein Kuddel-Muddel ist:
> 
> * der Inverter 1 wird abgefragt
> * keine Antwort kommt
> * nach 10s wird ein kompletter Retransmit angefordert (mit gleichem Timestamp)
> * ursprüngliche Nachricht kommt komplett an, Alarm ID bei 0x02ef
> * Inverter 1 ist wieder an der Reihe
> * Antwort kommt normal, mit der Alarm ID 0x02f1 (2 höher als vorher)
> 
> Wir müssen noch mehr Logs sehen, aber ich habe die Vermutung, dass ein Retransmit (evtl. auch nur der complete-Retransmit) nicht 10s später mit dem gleichen Timestamp nochmal erfolgen darf.

Wie kommt es dazu dass beim Retransmit nach 10 Sekunden der Timestamp immer noch gleich ist. Das würde für mich auch das Problem bei der Abfrage mit mehreren DTUs erklären, da ja beide DTUs ab und an mal eine Abfrage mit dem gleichen oder sogar einem “älteren” Timestamp als die andere DTU senden und dann der WR einen Protokollfehler mit der DTU vermerkt.
Ich versuche mich gerade zu erinnern die aller ersten Logs von der DTU WLite hatten auch retransmits drin aber mW nur von einzelnen Teilpaketen, oder waren da auch ganze Retransmits dabei ? Bei den Teilpaketen wurde der Timestamp mW nicht immer erhöht aber er war auch nicht niedriger als der vom WR (schickt der eigentlich einen außer in den Alarm Messages) … bei mir sind noch viele Fragezeichen. 

@BastyESP Ich hatte das in der Vergangenheit ja auch oft zu Hauf mit den (2) DTU command errors. Nach Umstellen auf LOW am NRF +PA/LNA ( das Ding mit der externen Antenne ) wurde es mit plötzlich viel besser. Davor hatte ich lange Zeit MIN, MAX und HIGH probiert, weil ich auf Sende/Empfangsprobleme getippt hatte: aber das war dann eher kontraproduktiv trotz Kondensator!

**Comment by BastyESP** [comment]
Hab gestern komplett verpasst das aufzunehmen, und als ich wieder dran gedacht habe, war es dann Dunkel -.-

P.s. Uptime der OpenDTU sind mittlerweile 30 Tage, da komm ich mit Ahoy schon alleine weil ich die vielen Versionen Installiere nicht hin -.-
<img width="608" alt="image" src="https://github.com/lumapu/ahoy/assets/125681883/6e71a422-2ad8-4c85-b823-1c77a485fa04">


Bin ja erst hochgegangen auf LOW auf HIGH, um es zu versuchen, hat aber nichts verbessert, das ich auf MIN besser fahre, bezweifel ich beinahe, der HM-400, war eher empfangstechnisch schon mein Sorgenkind, hatte früher als ich nur die 2 (HM-800 + HM-400) Aktiv hatte, immer HIGH, weil ich auf LOW, sonst teilweise nur alle 0,5-1min vom HM-400 antworten erhalten habe, nach dem ich ein Gehäuse gedruckt hatte, und die Verhältnisse besser wurden (War vorher nur in so einem kleinem Shelly 1PM Karton reingestopft + der Ort wo es jetzt steht ist minimal höher), hab ich den Kondensator verbaut und LOW versucht, lief  bisher eigentlich bisher ganz gut, kann aber MIN auch gerne versuchen...will mich davor nicht streuben...hab eben nur die vorherigen Sorgen mit den Schlechten erreichbarkeiten schon gehabt. LOW lief bisher gut...

Die beiden HM (800/400) liegen Quasi flach auf einem extra Blech, was sie abschirmt vor Sonnenstrahlung, auf einem Trapezblech Dach, das schränkt natürlich die Funkerei etwas ein, kann mal schauen auf was die OpenDTU funkt...die macht mir in den Sinne aber auch keinerlei sorgen, schaue selten ins Menü rein, und das Display (1,54" OLED) macht was es soll...

<img width="301" alt="image" src="https://github.com/lumapu/ahoy/assets/125681883/8ef8b17a-c6bd-40bf-8128-dc1fe3630e42">

Würde ich jetzt mal als LOW übersetzen...

Mein Problem wäre jetzt auch einfach zu Lösen (Schalter womit man die Alarm anzeige ausschalten kann) ;) denn es läuft ja auch mit den Tausenden Alarmen...allerdings bin ich ja nicht der einzige der das hat, nur ich bin der einzige Pflegefall der nebenher noch ne zweit DTU mitlaufen lässt ;)

**Comment by Ollipop030** [comment]
> Evtl. sollten wir hier einen Feature-Request anlegen, der quasi privacy hier automatisch aktiviert.

Erledigt: #1211

**Comment by lumapu** [comment]
@stefan123t beim retransmit muss der alte timestamp geschickt werden, sonst passt der CRC nicht.
Ich glaube den kompletten retransmit haben wir eingeführt oder besser gesagt @Sprinterfreak glaube ich, der war damals uns allen ein gutes Stück voraus.

Falsch ist aus meiner Sicht der retransmit nach 10s, der muss viel eher kommen. Bin schon dran es zu reparieren.

**Comment by lille2000** [comment]
Mit 0.8.1 habe ich nach einem Tag keine Alarme „DTU command failed” mehr gehabt. 
 Andere Auffälligkeiten habe ich nicht bemerkt.

**Comment by lille2000** [comment]
Bisher nicht mehr aufgetreten, kann als gelöst geschlossen werden. 👍

**Comment by Ollipop030** [comment]
Hab auch keine Alarme mehr.
