### ISSUE TITLE
 DTU sendet/empfängt sporadisch 10 min. lang keine Signale vom WR

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1204]
DTU sendet/empfängt sporadisch 10 min. lang keine Signale vom WR
![2023-09-26 11_46_21-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/c798e4c6-54d1-4fe3-a25f-cf4e8e7da4db)

_Originally posted by @Gubi2023 in https://github.com/lumapu/ahoy/issues/1178#issuecomment-1735205119_

**Comment by Gubi2023** [comment]
Das Problem tritt mit 7.64 immer noch auf.

**Comment by Gubi2023** [comment]
![2023-10-02 15_17_54-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/93c3d68b-415d-44bc-99f8-311e1a55655d)

**Comment by dtuuser** [comment]
Platform
ESP32-D0WD-V3

nRF24L01+ plus (powerlevel Low)

Antenna
external antenna

Power Stabilization
Elko (~100uF)

Eigenes Netzteil 500mA

------------------------------------------------------------

Bei mir auch mit ESP32
Aber erst seit dieser Version

**Comment by knickohr** [comment]
Bitte auch hier etwas zur HW dazu schreiben. Es wäre schön, wenn ihr auch den einleitenden Fragebogen ausfüllt. So ist es nur Stochern im Nebel und man sieht eventuell das Problem nicht. Danke !

**Comment by technics42** [comment]
I just tested with ESP-8266, new installed 0.7.65 and HM-inverter is working.

**Comment by rmayergfx** [comment]
> I just tested with ESP-8266, new installed 0.7.65 and HM-inverter is working.

Not useful! Didn’t you read the comment from @knickohr?
We need all information about the used hardware and inverter for the checklist!

**Comment by technics42** [comment]
I wrote I am using ESP-8266 and using HM-inverter. (HM-type not HMS-type)
What else "HW" information do you need? ( I don't think there is another option than NRF24L01+ to connect to inverters)

I would say, my information is useful.
Just saying "we need **all** information" is pretty useless.
(If you just reply, you don't get any checklist.)

**Comment by lumapu** [comment]
hier wäre hilfreich wie lange tatsächlich das Log analysiert wurde, @Gubi2023 du schreibst für 10 Minuten kein Signal, aber wie häufig tritt das auf? Jede Stunde / 2x Tag / etc.?

**Comment by Gubi2023** [comment]
ich habe das Verhalten jetzt nochmals genauer beobachtet. Die DTU startet immer wieder ohne ersichtlichen Anlass neu, dann sind im Webserial 10 Min keine Daten. Starte ich das Webserial in einem neuen Fenster, läuft die Kommunikation sofort weiter. Mir ist nur die Ursache des Neustarts nicht klar. Manchmal alle 30 min dann läuft sie wieder 14 Std am Stück.... Könnte es am fehlenden Kondensator liegen?

**Comment by knickohr** [comment]
Ach jetzt !

Der Aussetzer kommt nach einem Reboot.

**Comment by lumapu** [comment]
Hier haben wir ein anderes Problem, wie @knickohr schon schreibt. @Gubi2023 wie ist dein `heap-frag` Wert? ist er kleiner als 10?
Hast du @knickohr seine goldenen Ahoy-Regeln (Kondensator, etc.) beachtet?

**Comment by Gubi2023** [comment]
Hast du @knickohr seine goldenen Ahoy-Regeln (Kondensator, etc.) beachtet?
wo finde ich die?
 @Gubi2023 wie ist dein heap-frag Wert? ist er kleiner als 10? unterschiedlich: mal auf 12, mal auf 2.
das ärgerliche ist, dass jedesmal beim reboot die ganzen max-Werte gelöscht werden. war das schon immer so?

**Comment by Gubi2023** [comment]
<img width="563" alt="Screenshot 2023-10-06 094111" src="https://github.com/lumapu/ahoy/assets/142897856/1851ac9e-5698-44d2-a268-050f49c00c7f">

**Comment by dtuuser** [comment]
Platform
ESP32-D0WD-V3

nRF24L01+ plus (powerlevel Low)

Antenna
external antenna

Power Stabilization
Elko (~100uF)

Eigenes Netzteil 500mA

Heute nochmal in Ruhe die neueste Version eingespielt. Nach Update und Reboot kommen die Werte. Dann 10 Minuten kein Empfang. Nach 10 Minuten dann wieder Werte. Usw.
Mit der 60er Version kein Problem. Empfang topp, keine Empfangslücken

**Comment by knickohr** [comment]
Ist der Serial Debug aktiviert ?  Wenn ja, schalte den mal aus ob es dann besser wird.

**Comment by dtuuser** [comment]
Nein, Serial Debug ist aus

**Comment by dtuuser** [comment]
Vielleicht hilft das weiter....oder ich interpretiere das falsch

Im Webserial Fenster erscheinen manchmal mehrere Abrufversuche innerhalb einer Sekunde

13:31:28 I: TX 11 CH61 | 15 80 40 51 95 89 95 62 48 82 a5 
13:31:28 I: TX 11 CH75 | 15 81 86 70 88 89 95 62 48 82 5e 
13:31:28 I: TX 11 CH3 | 15 80 40 51 95 89 95 62 48 82 a5 
13:31:28 I: TX 11 CH23 | 15 81 86 70 88 89 95 62 48 82 5e 

Und beim Alarm erscheint dann umgehend ein weiterer Eintrag 

DTU command failed 2

**Comment by dtuuser** [comment]
Update
Habe gestern mal den ESP komplett gelöscht und die 66 direkt installiert. 
Problem bleibt bestehen

**Comment by lumapu** [comment]
bitte nochmal mit aktueller `0.8.x` testen

**Comment by Gubi2023** [comment]
> ich habe das Verhalten jetzt nochmals genauer beobachtet. Die DTU startet immer wieder ohne ersichtlichen Anlass neu, dann sind im Webserial 10 Min keine Daten und der Zeitstempel ist anschliessend um 1 Std. falsch. Starte ich das Webserial in einem neuen Fenster, läuft die Kommunikation sofort weiter mit richtigem Zeitstempel. Mir ist nur die Ursache des Neustarts nicht klar. Manchmal alle 30 min dann läuft sie wieder 14 Std am Stück.... Könnte es am fehlenden Kondensator liegen?

Dieses Verhalten ist auch noch mit V8.10 zu beobachten.

**Comment by Gubi2023** [comment]
> Hast du @knickohr seine goldenen Ahoy-Regeln (Kondensator, etc.) beachtet? wo finde ich die? @Gubi2023 wie ist dein heap-frag Wert? ist er kleiner als 10? unterschiedlich: mal auf 12, mal auf 2. das ärgerliche ist, dass jedesmal beim reboot die ganzen max-Werte gelöscht werden. war das schon immer so?

Leider habe ich auf  diese Frage keine Antwort bekommen...

**Comment by rmayergfx** [comment]
@Gubi2023 
Welche Hardware nutzt du? Ist ein Elko verbaut, kann irgendwie keine Info von deinem System im Thread sehen.
Hast du denn mal ein anderes Netzteil ausprobiert. Hatten die Tage erst das Problem das ein defektes Netzteil solche Fehler produziert hatte. Sporadische Reboots hatte ich bisher noch keine.

**Comment by dtuuser** [comment]
Ich bekomme das hier im Webserial, obwohl nach Sonnenuntergang keine Abfragen mehr laufen sollten

18:58:21 I: heuristic test mode
18:58:21 I: (#0) request timeout: 500ms
18:58:41 I: heuristic test mode
18:58:41 I: (#0) request timeout: 500ms

**Comment by knickohr** [comment]
Du hast die Optionen bei den Invertereinstellungen nicht gesetzt. Das ganze ist jetzt unter Settings - Inverter - Edit zu finden 😉

**Comment by Gubi2023** [comment]
Version 8.13: Merklwürdig: bei schlechtem Wetter läuft die DTU sehr stabil durch, kaum scheint die Sonne habe ich wieder ständige Neustarts (teilweise mehrere pro Std.)  "Verschluckt"  sich da die Datenabfrage vielleicht?   Habe übrigens das Netzteil getauscht, bringt keine Veränderung...
<img width="1028" alt="Screenshot 2023-12-05 115329" src="https://github.com/lumapu/ahoy/assets/142897856/8aed0a58-87bd-4da1-816d-b6362859b571">

**Comment by Gubi2023** [comment]
> > ich habe das Verhalten jetzt nochmals genauer beobachtet. Die DTU startet immer wieder ohne ersichtlichen Anlass neu, dann sind im Webserial 10 Min keine Daten und der Zeitstempel ist anschliessend um 1 Std. falsch. Starte ich das Webserial in einem neuen Fenster, läuft die Kommunikation sofort weiter mit richtigem Zeitstempel. Mir ist nur die Ursache des Neustarts nicht klar. Manchmal alle 30 min dann läuft sie wieder 14 Std am Stück.... Könnte es am fehlenden Kondensator liegen?
> 
> Dieses Verhalten ist auch noch mit V8.65 zu beobachten. V8.59 lief da stabiler!

**Comment by Gubi2023** [comment]
Leider auch noch mit Release 8.83 immer wieder Neustarts der DTU ohne ersichtlichen Anlass. Manchmal alle 20 min, dann läuft sie wieder 2 Std am Stück. Das ärgerliche ist, dass jedesmal beim reboot die ganzen max-Werte gelöscht werden. war das schon immer so bzw. kann man die irgendwie wiederherstellen?? Ich verfüge über keinerlei Datenspeicherung wie z.B. Grafana und weiss auch nicht, wie man so etwas einbindet... (Kein Computerfreak)

**Comment by Gubi2023** [comment]
Hallo, liest das überhaupt noch jemand oder muss ich einen neuen Issue öffnen?
heute auf V0.8.91 upgedatet, seither wieder ständige Neustarts der DTU. Mit 0.8.89 lief sie 2 Tage durch!

**Comment by Gubi2023** [comment]
und wieder mal: 
V0.8.93 sehr stabil,
V 0.8.94 DTU-Neustarts im Minutentakt!!

**Comment by lumapu** [comment]
dann bitte ein serielles Log, damit ich nachvollziehen kann wo es hakt. 

Nein ESP8266 läuft seit 11 Stunden stabil, auch nach Zugriffen auf das Webinterface, heap_frag bei 2
Habe die `all` Variante am laufen, ein Wechselrichter und MqTT aktiv

**Comment by Gubi2023** [comment]
[0.8.94 - 6af07f5.txt](https://github.com/lumapu/ahoy/files/14623375/0.8.94.-.6af07f5.txt)

**Comment by Gubi2023** [comment]
ESP8266, kein Display, kein Mqtt, 240316_ahoy_0.8.94_6af07f5_esp8266-all.bin geladen

**Comment by lumapu** [comment]
ich meine ein USB Log, sorry. Dein Log ist wenig aussagekräftig.
Ich würde dir im allgemeinen empfehlen das Log nicht mit unnötigen Informationen zu fluten.
So wurde ich es einstellen:

![Screenshot_2024-03-16-13-04-19-04_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/lumapu/ahoy/assets/22733082/0073369f-7ac8-49c2-9e5f-86defcb11ef4)

**Comment by Gubi2023** [comment]
tut mir leid, ich bin nur ein "dummer" Anwender, mit USB-Logs kann ich nicht dienen...

**Comment by Gubi2023** [comment]
ESP8266, kein Display, kein Mqtt,:  ab V0.8.94 bis 8.97 habe ich ständige Neustarts der DTU im Minutentakt, egal welche FW geladen wurde (.min  -all). V8.93 läuft halbwegs stabil.
und nein, USB-Logs kann ich keine machen. (weiss nicht, wie das gehen soll)
Wurde ab da was grundlegendes geändert?

**Comment by lumapu** [comment]
https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md

-> neuer Webserver ab 0.8.94

**Comment by Gubi2023** [comment]
na schön, dann bleibe ich eben auf 0.8.93, wenn mein Webserver das nicht ab kann.

**Comment by Gubi2023** [comment]
oder gibt es eine Abhilfe??

**Comment by Gubi2023** [comment]
tja, auch mit V0.8.112 habe ich immer noch sporadische unerklärliche Neustarts der DTU, obwohl  ich inzwischen ESP32 verwende.... (V0.8.97 lief problemlos durch)

Senden in Dauerschleife! 
[complete_retransmit.txt](https://github.com/lumapu/ahoy/files/15107284/complete_retransmit.txt)

**Comment by rmayergfx** [comment]
@Gubi2023 
Ist ein Elko verbaut?
Die Frage wurde bis heute von dir nicht beantwortet.
Wie sind die Einstellungen der Status LEDs?

**Comment by Gubi2023** [comment]
@rmayergfx:
ich habe jetz ein neues Gerät im Einsatz:  AllianceApps OpenDTU mit ESP32 (AZ-Delivery ESP32 NodeMCU Module WLAN WiFi Development Board mit CP2102)EBYTE NRF24L01+ Funkmodul mit Antenne
Adapter-PCB mit Kondesator 16V 100 uF
Status-LEDs sind auf default

**Comment by rmayergfx** [comment]
Somit sind wir nicht mehr bei einem Standard ESP32 sondern du musst auch das entsprechende Paket für OpenDTU nehmen:
ahoy_v0.8.112\ESP32-S3 240424_ahoy_0.8.112_b291ad1_opendtufusion-de.bin
Wie soll man da helfen wenn du die Boards tauschst wie deine Unterhosen :-)

Spaß beiseite. Das richtige BIN einspielen und erneut testen.
LED bitte alle auf OFF stellen!
Welche Sendeleistung steht beim Modul in den Settings vom WR?

Mit welchem WLAN bist du verbunden? 2.4GHz oder 5GHz?

**Comment by Gubi2023** [comment]
@rmayergfx : 
jetzt verwirrst du mich aber: Ich hab die DTU seit ca. 3 Wochen im Einsatz und immer die _esp32-wroom32-de.bin FW verwendet (auf Empfehlung von metachuh, der hat mir auch die DTU empfohlen), lief auch immer halbwegs. Z.Zt. hab ich V103 drauf, mit der gehts.  LEDs sind alle aus, Sendeleistung 100%, WLAN geht doch nur 2,4 GHz!

**Comment by rmayergfx** [comment]
@Gubi2023 
Dann frag doch mal bei metachuh nach, er hat dir das Board ja empfohlen.
Welches Board hast du denn nun gekauft? Bei  AllianceApps  gibt es ja 3 verschiedene Platinen:
AllianceApps OpenDTU
AllianceApps OpenDTU Fusion
OpenDTU Fusion - Community Edition

Wie weit ist denn der WR von AhoyDTU entfernt?
Sind in der Nähe irgendwelche AccessPoints, Repeater oder Dect-Stationen?

**Comment by Gubi2023** [comment]
wie geschrieben: AllianceApps OpenDTU. Wie gesagt: Mit V103 geht alles! Warum spielen dann auf einmal die anderen Faktoren eine Rolle?
WR-DTU 2m  Repeater 1200AX 2m sonst nix

**Comment by rmayergfx** [comment]
@Gubi2023 
Die o.g. Faktoren haben schon immer eine Rolle gespielt. Elko, Netzwerkstörungen durch andere WLAN Geräte, Netzteile das defekt ist oder zu geringe Leistung. Daran wird sich auch in Zukunft nichts ändern.
Auch die 103 ist eine Entwicklerversion. Bleib doch einfach auf der für dich passenden Version und warte ab. Warum möchtest du immer die aktuellste dev auf dem System haben, wenn eine Version für deine Umgebung stabil läuft, dann bleib doch auch bei dieser.

@lumapu 
Zwecks der richtigen Binary, welche ist für das normale AllianceApps OpenDTU am besten geeignet?
So wie ich das sehe ist das ja nur eine Platine und die Standard Bauteile, da sollte das \ESP32\xxxx_esp32-wroom32-de.bin 
doch eigentlich laufen.

**Comment by Gubi2023** [comment]
@rmayergfx:
Danke für deine Erläuterungen.
zu deiner Frage: Im Prinzip hast du recht; wenn es euch stört, dass ich meine Erfahrungen zur neuesten dev einbringe, lasse ich es bleiben ;-) V0.8.113 läuft übrigens seit Mitternacht anstandslos....

**Comment by rmayergfx** [comment]
Bitte jetzt nicht so argumentieren. Für Feedback ist man jederzeit dankbar, aber dann bitte auch mmit den entsprechenden Eckdaten. Wenn du dieses Issue hier selbst mal von Anfang an durchliest, wirst du feststellen, das du nun 3x die Hardware getauscht hast und leider auf einige Fragen überhaupt keine Antwort gegeben hast. Wie soll man dann als Entwickler einen Fehler eingrenzen?

**Comment by Gubi2023** [comment]
@rmayergfx 
können wir diese Diskussion irgendwo über PN weiterführen?

**Comment by rmayergfx** [comment]
PN Sind nicht öffentlich und somit für Dritte nicht einsehbar, das ist auch gut so, aber für einen Issue vollkommen irrelevant. 
Aus meiner Sicht ist das Thema soweit abgeschlossen, die Release 113 läuft bei dir stabil, also kann von mir aus hier abgeschlossen werden, wüsste auch nicht was ich noch per PN diskutieren sollte.

**Comment by Gubi2023** [comment]
@rmayergfx
Ich hätte dir gerne noch mein Sicht zu dem Issue mitgeteilt, da das etwas aus dem Ruder läuft. 
Im Übrigen ist das Problem mit den sporadischen Neustarts bei mir immer noch vorhanden, sprich ich lass den Issue weiterhin offen

**Comment by rmayergfx** [comment]
V0.8.113 läuft übrigens seit Mitternacht anstandslos....
Im Übrigen ist das Problem mit den sporadischen Neustarts bei mir immer noch vorhanden, sprich ich lass den Issue weiterhin offen
Diese Aussagen passen nicht zueinander... ich lass das jetzt so mal stehen, bin hier nun raus.

**Comment by Gubi2023** [comment]
tja, sporadisch heisst sporadisch; kaum hatte ich ich es geschrieben, ist die DTU wieder ausgestiegen... (Nach 16 Std)
Und solange sie nicht mehrere Tage durchläuft, ist es für mich nicht ok.
