### ISSUE TITLE
Cannot connect to Inverter anyhow 

### ISSUE THREAD

**Issue by oodsplanet** [lumapu/ahoy#1215]
## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [x] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ x] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.7.36
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

 I have bought a "ready made" ESP8266 version with internal antenna which should work.

1)  After entering the settings for the inverter and restarting I get the info that the Inverter is available, but no data received until now which seems to be OK.
 
    ( )  Inverter #0: HM800Gartenhaus (v0) is available but no data was received until now
    (!) time not set. No communication to inverter possible

2) BUT after doing a time-Sync from the browser the inverter isnt available anymore 

   System Infos:
  Inverter #0: HM800Gartenhaus (v0) is not yet available

I dont understand whats wrong!. 
AhoyDTU is powered by a USB 2A powerplug
inverter is ~5m away and producing ~200W (very cloudy  day)

**Comment by oodsplanet** [comment]
I have tried now:
- new nRF with external Antenna
- connect DTU to my WLAN router and use NTP server for time information 
again 
No signal from invertet received

any help, idea?

**Comment by oodsplanet** [comment]
Serial out:
11:59:31 I: (#0) Requesting Inv SN 1141******
11:59:31 I: (#0) enqueCommand: 0x01
11:59:31 I: (#0) enqueCommand: 0x0b
11:59:31 I: (#0) prepareDevInformCmd 0x01
11:59:31 I: TX 27B Ch40 | 15 84 24 11 47 85 04 97 22 80 01 00 65 32 4f 83 00 00 00 00 00 00 00 00 26 94 7f 
12:00:01 I: (#0) enqueued cmd failed/timeout
12:00:01 I: (#0) resetPayload

**Comment by lumapu** [comment]
have you tried to exchange the CE and CS pin in the settings?
There was recently a change, so maybe the schematics do not fit the default settings
good luck

**Comment by betaracer** [comment]
I had the same problem. NTP server now works, but no connection to the inverter.
(is not yet available). No idea what else I can do.

**Comment by lumapu** [comment]
Do you know your wiring? Does it match the settings given in Ahoy?

**Comment by oodsplanet** [comment]
> have you tried to exchange the CE and CS pin in the settings? There was recently a change, so maybe the schematics do not fit the default settings good luck

I have purchased a pre-wired station, and it should function as it was advertised. However, the microinverter does not seem to respond.

I have also replaced the HF module and used two new ones with antennas, both with older and newer versions, so I don't believe the wiring is the issue, but I will double-check it.

Unfortunately, I haven't seen any results. Is there an easy way to check if the microinverter is responding and sending a signal?

**Comment by betaracer** [comment]
After replacing the WLAN module, I couldn't receive anything again at first. Then it worked for a few minutes, then again not. I was about to give up, but now everything is working again. It also worked for 5 months before. I hope it's stable now.

**Comment by Blaubaer9** [comment]
I have a simmilar problem with my setup no response from my HMS-1600-4T.
I using ESP8266 (from A-Z Delivery) and NRF24L01+ PA +LNA (DollaTek, SMA external antenna) CE and CS pin are right, board is hardwired with 100yF stabilized.

Connection and setup of the ESP was no problem, but I dont know how to verify that the NRF module is working.
Any sugestions?

![grafik](https://github.com/lumapu/ahoy/assets/150913146/20ce135b-59d6-46eb-a12f-22914c9111c9)

![grafik](https://github.com/lumapu/ahoy/assets/150913146/b5abd140-9ef7-44f3-aaea-b879b696a5f4)
![grafik](https://github.com/lumapu/ahoy/assets/150913146/ef2ae0d7-7f19-432f-9b15-a77acbf46688)

**Comment by Ollipop030** [comment]
> I have a simmilar problem with my setup no response from my HMS-1600-4T.

For HMS/HMT Series you need a ESP32 with CMT2300A. See this page for more information:

https://ahoydtu.de/getting_started/

**Comment by DanielR92** [comment]
Hello,

The MI/HM version uses a different frequency (2.4GHz) than the HMS/HMT version...they use 868MHz.
This means that an NRF cannot establish a connection directly with HMS/HMT.

If the appropriate module already exists, all you have to do is set the setting correctly in the web interface. Please check all values and, very importantly, reduce the power to the minimum first.

Since Maximal has almost a negative effect on itself.

If you have any further questions, please just reopen it and we'll take another look. Thanks.
Photos often help too.

**Comment by Sirius2971** [comment]
> have you tried to exchange the CE and CS pin in the settings? There was recently a change, so maybe the schematics do not fit the default settings good luck

Hi, do you have de schema of connection ESP32 (36 pins) to NRF24L01 + PA

**Comment by Sirius2971** [comment]
> have you tried to exchange the CE and CS pin in the settings? There was recently a change, so maybe the schematics do not fit the default settings good luck

Hi, do you have de schema of connection ESP32 (36 pins) to NRF24L01 + PA
Is this schema good?

![image](https://github.com/lumapu/ahoy/assets/156085421/86b2d449-4dfb-4b89-9975-1b56cba2195f)

**Comment by Sirius2971** [comment]
with the exchange of the CE and CS pin in the settings

**Comment by MuellLei** [comment]
Hello,
I have the same problem
![image](https://github.com/lumapu/ahoy/assets/156328086/7115f450-a10c-4ce5-a200-bc526c2dd94d)

I have checked that:
- wiring is correct (NRF24L01, ESP8266, capacitor 50V, 10uF)
- Settings made according to AHOY-DTU
- Serial ID of the inverter is correct

What else can I do?

**Comment by MuellLei** [comment]
in addition, the webserial:
![image](https://github.com/lumapu/ahoy/assets/156328086/fa28ebe2-15d1-4f72-95c6-1e9000701090)

**Comment by Sirius2971** [comment]
Hi ?

I have this message :
***@***.***

De : MuellLei ***@***.***>
Envoyé : jeudi 11 janvier 2024 15:01
À : lumapu/ahoy ***@***.***>
Cc : Sirius2971 ***@***.***>; Comment ***@***.***>
Objet : Re: [lumapu/ahoy] Cannot connect to Inverter anyhow (Issue #1215)


in addition, the webserial:
image.png (view on web)<https://github.com/lumapu/ahoy/assets/156328086/fa28ebe2-15d1-4f72-95c6-1e9000701090>

**Comment by Sirius2971** [comment]
Do you know if thesr settings are correct?
Thank you for your answer

***@***.***


De : MuellLei ***@***.***>
Envoyé : jeudi 11 janvier 2024 15:01
À : lumapu/ahoy ***@***.***>
Cc : Sirius2971 ***@***.***>; Comment ***@***.***>
Objet : Re: [lumapu/ahoy] Cannot connect to Inverter anyhow (Issue #1215)


in addition, the webserial:
image.png (view on web)<https://github.com/lumapu/ahoy/assets/156328086/fa28ebe2-15d1-4f72-95c6-1e9000701090>

**Comment by MuellLei** [comment]
Hello Sirius2971,
which setting do you mean?
I follow the instruction from: https://ahoydtu.de/getting_started/

And in first time (May 2023) all works fine, but after reinstallation this error now exists.

BR,
MuellLei

**Comment by Sirius2971** [comment]
Thank you, I followed alao the instructiond from ahoydtu, with the esp 32 with 36 pins. Somebody says to me that I had to restart my inverter Hoymiles 1500, but it doesn't work either. I tried also with other connections because there are several frizing, but none of these are working, I always received the message inverter not available.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
