### ISSUE TITLE
[Bug] Power Limit wird via MQTT nicht gesendet

### ISSUE THREAD

**Issue by Alech385** [lumapu/ahoy#1216]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

 0.7.36

### Github Hash

ab1234

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Setup ist soweit i. O. Kommunikation zu den Invertern ist einwandfrei. 

### Error description

Hallo, ich habe einen HM-600 Inverter die Kommunikation mit der AhoyDTU (ESP32) sowie mit meinem Smart Home System läuft via MQTT einwandfrei. Leider habe ich das Problem, dass ich den Wert "Power Limit" nicht erhalte. Also das Topic: 

"<TOPIC>/<INVERTER_NAME_FROM_SETUP>/ch0/PowerLimit"  wird einfach nicht aufgerufen, alle anderen Werte jedoch schon. Hat jemand das gleiche Problem? Ich benötige den Wert, da ich eine Nulleinspeisung umsetzen möchte. 

Vielen Dank im Voraus! 

Grüße

**Comment by lumapu** [comment]
sind die anderen topics aktuell?
Nur zur Kontrolle: Du willst den gelesenen Power Limit Wert wissen, der automatisch per MqTT gesendet werden sollte?
Was steht in den Feld oder gibt es das überhaupt nicht?

**Comment by Alech385** [comment]
Die anderen Topics sind aktuell. Das Topic für PowerLimit wird  über MQTT irgendwie nicht gesendet.

**Comment by lumapu** [comment]
bei mir ist der Wert da, wurde gleich bei der ersten Inverterkommunikation aktualisiert:
![grafik](https://github.com/lumapu/ahoy/assets/22733082/680652ee-0345-4c48-99c8-515c79223675)

Es ist allerdings der Wert in `%` und nicht in `W`

**Comment by Alech385** [comment]
Hallo nochmal, 
ich bekomme tatsächlich nur folgendes vom Umrichter: 
![image](https://github.com/lumapu/ahoy/assets/133127891/6041faf0-aa6e-4135-82e3-0314b87e95eb)

**Comment by Alech385** [comment]
Hi, ich habe meinen fehler gefunden. Das Topic gibt mir ja nur eine Rückmeldung, wenn ich den Wert für PowerLimit selbst setze.
