### ISSUE TITLE
0.8.1 keine Kommunikation mit den Invertern

### ISSUE THREAD

**Issue by Ollipop030** [lumapu/ahoy#1221]
Moin moin,

grad von 0.6.6 auf die 0.8.1 auf einem ESP32 geupdated. Hier scheint es genau einmal zu einer Kommunikation zu kommen, wenn die DTU startet, danach nicht wieder.

Es werden viele Fehler gezählt:

![image](https://github.com/lumapu/ahoy/assets/121013633/14234a98-619f-4494-9d4d-21ad2ed78a98)

Hier noch ein kurzes Log:
[Log.txt](https://github.com/lumapu/ahoy/files/13259779/Log.txt)

**Comment by knickohr** [comment]
Ich würde da mal ansetzen :  15:14:45 W: local buffer to small for payload fragments

Sieht so aus als ob das Datenpaket von Deinem 4-Ch WR nicht mehr rein paßt.

**Comment by dtuuser** [comment]
Bei mir nicht mehr die 10 Minuten Pausen wie bei der 7.66. Aber manchmal 2 bis 3 Minuten kein Empfang

**Comment by lumapu** [comment]
ok, Problem erkannt. Es wurden maximal 10 Fragmente zugelassen. In der nächsten Version wird das verdoppelt. Diese Alarmabrage bereitet mir zunehmend Kopfschmerzen .. ich hoffe wir bekommen das vernünftig in Griff.

**Comment by Gubi2023** [comment]
bei mir sind auch mit 8.1 die 10-minütigen Pausen noch vorhanden... und anschliessend default-Zeit 
![2023-11-08 10_57_56-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/cb63f5ca-9a6b-4717-a691-d1392c5dcfb7)

**Comment by knickohr** [comment]
Du hast keine Unterbrechung von +10 Minuten, sondern von -50 Minuten. Da stimmt was mit der Uhr (NTP ?) nicht !

**Comment by rmayergfx** [comment]
@knickohr 
was bedeuten diese Werte?
11:48:35 I: Status: | -6 0 -6 -6 -6
11:50:05 I: Status: | -6 2 -6 -6 -6
11:50:35 I: Status: | -6 4 -6 -6 -6
11:51:35 I: Status: | -6 2 -6 -6 -6
11:52:35 I: Status: | -6 4 -6 -6 -6

Das wechselt bei mir ständig hin und her und 

Uptime: 2 Days, 19:10:49

kann ich auch nicht nachvollziehen, woher kommt das 19:10:49?

Wo finde ich dazu informationen?

**Comment by knickohr** [comment]
Das ist die Heuristik. Er versucht den besten Sendekanal aus den 5 möglichen zu ermitteln. Eine -6 ist schlecht, eine 4 gut. Es sollte mindestens ein Kanal mit >0 dabei sein, dannn steht eine gute Verbindung.

Mach Dir da mal keinen Kopp, das ist ganz neu und der allererste Wurf. Dashalb auch noch keine Doku.

2 Tage, 19 Stunden, 10 Minuten, 49 Sekunden Uptime 😅

**Comment by Ollipop030** [comment]
Hab heute morgen die 0.8.3 installiert, der HM1500 hat wieder eine stabile Verbindung, allerdings werden fleißig Fehler gezählt.
![image](https://github.com/lumapu/ahoy/assets/121013633/ee592742-f304-420c-800f-1e47f555d074)

Komischerweise aber nicht beim HM300:
![image](https://github.com/lumapu/ahoy/assets/121013633/2cfc4686-c12e-4e18-91ca-2c8b0b39ea74)

**Comment by Ollipop030** [comment]
Bezüglich des Fehlerzählers habe ich nochmal einen Vergleich gemacht, Power Level auf LOW.

Hier die Version 0.8.7:
![08 1](https://github.com/lumapu/ahoy/assets/121013633/fc99457d-1316-4295-9b90-51d1f8203dc8)
![08 2](https://github.com/lumapu/ahoy/assets/121013633/1d348af1-b156-461f-84b7-a211db4ae602)

Und hier die Version 0.7.64:
![07 1](https://github.com/lumapu/ahoy/assets/121013633/53388701-3261-420d-8f79-ab92503ad9d6)
![07 2](https://github.com/lumapu/ahoy/assets/121013633/bc41b56c-fa86-47fa-850f-c0c9e5cd7d42)


Mal eine Frage in die Runde: Bin ich der einzige mit dem Phänomen? Ich hatte erst meine Nulleinspeisung in Verdacht, weil ich hier ständig Timeouts bekomme beim Limit setzen mit den Versionen >0.8. Die habe ich für diesen Vergleich aber ausgeschaltet.

**Comment by Gubi2023** [comment]
Bei mir sieht es auch nicht viel besser aus: DTU hat sich vor 2,5 Std neu gestartet, seither nachstehende Statistik:![grafik](https://github.com/lumapu/ahoy/assets/142897856/bbadeafe-4797-4240-96f7-3251f7465a26)
 
Konfiguration: ESP8266  Version 8.7

**Comment by knickohr** [comment]
@Ollipop030 

RX fail in Verbindung mit sehr wenige no answer deutet darauf hin das Du mit zu wenig Power sendest. Denn würde Dich der Inverter verstehen und nicht antworten, dann wäre es genau anders herum.

Aaaber wenn ich mir die Summe aus fail und no answer anschaue, dann ist die neue Version nicht schlechter als die alte. Denn beide Summen sind ungefähr gleich, was ja auch die Anzahl der success deutlich macht.

**Comment by rmayergfx** [comment]
@knickohr 
Danke für den Hint. Ich habe gerade bei mir auch mal nachgesehen und musste leider feststellen, das irgendeines der Updates von 0.7.59 auf 0.8.xx mir die Einstellungen im Bereich Inverter gelöscht hat. Ich hatte plötzlich dort nur noch MIN (recommended) drinstehen und auch "Pause communication during night " war wieder deaktiviert.
Aktuell bin ich auf 0.8.7 und die Werte sind nun, nachdem ich wieder auf HIGH gesetzt habe wesentlich besser geworden.

> CH qualities: 4 -6 -4 -6 -6

@lumapu 
Könntest du bitte im Popup zu den Radio Statistics die eingestellte Sendeleistung mit anzeigen, damit man nicht erst in die Untermenues muss?

**Comment by Ollipop030** [comment]
> das Du mit zu wenig Power sendest

Danke, probiere ich mal. In der Vergangenheit hieß es ja, so niedrig wie möglich.

> dann ist die neue Version nicht schlechter als die alte

Bei meiner Nulleinspeisung schon. Die 0.7er Versionen laufen wunderbar, die 0.8er Releases sind für mich leider unbrauchbar, damit bekomme timeouts im Minutentakt. 

> Könntest du bitte im Popup zu den Radio Statistics die eingestellte Sendeleistung mit anzeigen, damit man nicht erst in die Untermenues muss?

Könnte ahoy nicht anhand der hohen Fehlerzahl die Sendeleistung selbst einstellen?

**Comment by knickohr** [comment]
so niedrig wie möglich, so hoch wie nötig 😉

Soweit sind wir noch nicht. Erst mal muß die Kommunikation (wieder) stabil funktionieren.

**Comment by Ollipop030** [comment]
Kurzer Zwischenstand mit Powerlevel HIGH:

![2](https://github.com/lumapu/ahoy/assets/121013633/8b6e199b-ca78-4e8c-be9e-c8faa13ffd5c)

![1](https://github.com/lumapu/ahoy/assets/121013633/5b80dd46-84cf-41de-83b4-e5133eefe8f1)

Übrigens Kondensator ist verbaut, externe Antenne vorhanden. 
Probiere morgen mal noch ein wenig herum, jetzt ist dunkel.

Falls irgendwelche Logs benötigt werden sagt bescheid.

**Comment by Gubi2023** [comment]
> Kurzer Zwischenstand mit Powerlevel HIGH:

Wie hast du den Power Level auf high bekommen? bei mir kommt Fehlermeldung beim speichern....

**Comment by Ollipop030** [comment]
> Wie hast du den Power Level auf high bekommen? bei mir kommt Fehlermeldung beim speichern....

Die Fehlermeldung hab ich nicht. Ich kann das problemlos wechseln, bei beiden Invertern. Bin auf einem ESP32, in #1232 habt ihr ja beide den 8266. Vielleicht kommt der Fehler nur dort?

**Comment by rmayergfx** [comment]
Dito kann ich so bestätigen. Habe schrittweise auf dem ESP32 auf 0.8.7 erhöht. Keinerlei Probleme beim Speichern.

**Comment by Gubi2023** [comment]
Merkwürdig: mit dem Handy kann ich die Änderungen speichern, nur am PC bekomme ich eine die Fehlermeldung....

**Comment by rmayergfx** [comment]
> Merkwürdig: mit dem Handy kann ich die Änderungen speichern, nur am PC bekomme ich eine die Fehlermeldung....

Welches Betriebssystem? Welcher Browser? Hast du schon mal den Cache am Browser gelöscht? Das ist ganz wichtig, gerade bei neuen Releases. Manchmal hilft auch die Seite zwangsweise neu zu laden (Mit Shift und Reload Button) der einzelnen Seite. Damit zwingst du diese Seite neu zu laden ohne den lokalen Cache zu nutzen. 
Bevor ich es ganz vergesse, natürlich auch den eventuell vorhandenen Adblocker/Skriptblocker abschalten, da passieren oft auch merkwürdige Dinge.
