### ISSUE TITLE
Update dev ahoy_v0.8.2

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1223]
Hi, Sorry to bother but 
last ahoydtu_dev.zip contains ahoy_v0.8.1 instead of ahoy_v0.8.2
Kind regards

## Hardware
  * [ ] ESP8266
  * [x ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [x ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by knickohr** [comment]
Last build has failed.

![IMG_1349](https://github.com/lumapu/ahoy/assets/63048210/e2abd89a-d509-4e6f-b17e-0318c0f47b9d)

**Comment by Peertje-62** [comment]
Okay, Thx
