### ISSUE TITLE
Radio statistics 

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1227]
THX so far
I am happy with 8.5. 
(and not skilled in programming)
I think it would be meaningful, useful & fun to send the Radio statistics for inverter (per inverter) via MQTT,
to make it visible in Grafana, without the use of the web-interface.
hope to hear from you
kind regards
Peertje

**Comment by knickohr** [comment]
See Issue #1199 (Wishlist) 😉

**Comment by Peertje-62** [comment]
Hi, thx
I am sorry,
that is where I 've looked could not find it.
tried to add it, could not add it  there
hope you can, (or will)
kind regards Peertje

**Comment by Peertje-62** [comment]
thx
