### ISSUE TITLE
Inverter option 'Include inverter to sum of total' not working

### ISSUE THREAD

**Issue by SilverSurfer2000** [lumapu/ahoy#1230]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.7

### Github Hash

?

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

3 inverters
MQTT enabled
Inverter intervall 5s

### Error description

I unchecked the new option 'Include inverter to sum of total (should be checked by default)' in the inverter settings (one of three inversters), but the values are still added to the totals section (AC Power, Yield, etc.). Save and reboot was done.

**Comment by knickohr** [comment]
Blöd gefragt, den Reboot haste aber gemacht ?  Das Save bei dem Reboot nicht vergessen !

**Comment by SilverSurfer2000** [comment]
![Screenshot 2023-11-14 113857](https://github.com/lumapu/ahoy/assets/94550683/84031181-976d-4335-9f91-ee447c76159e)
Freilich, bereits mehrfach.
