### ISSUE TITLE
Verbesserungsvorschlag: Eingeblendetes Feld verschiebbar machen

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1233]
Wäre es möglich, das angezeigte Fenster verschiebbar zu konfigurieren?

![282785256-bbadeafe-4797-4240-96f7-3251f7465a26](https://github.com/lumapu/ahoy/assets/142897856/8c4b7c40-11df-48b1-8831-6be2ec6470dc)

**Comment by lumapu** [comment]
macht aus meiner Sicht wenig Sinn, da die Inhalte im weißen Fenster nicht aktualisiert werden

**Comment by Gubi2023** [comment]
ja, aber das weisse Feld deckt mir die Daten darunter ab, die ich gerne sehen würde.

**Comment by lumapu** [comment]
dann mach das weiße Feld doch wieder zu 😉
