### ISSUE TITLE
0.8.9 (ESP8266) 3 Inverter antworten nicht mehr [Bug]

### ISSUE THREAD

**Issue by mtet2** [lumapu/ahoy#1235]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.9

### Github Hash

49ef94c

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

`<div id="content"><div class="tabs tabs-tall "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="JSON durchsuchen" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">
  |  
-- | --
generic |  
wifi_rssi | -40
ts_uptime | 1054
ts_now | 1700383038
version | "0.8.9"
build | "49ef94c"
menu_prot | false
menu_mask | 61
menu_protEn | false
esp_type | "ESP8266"
system |  
ssid | "edi_FB"
ap_pwd | "esp_8266"
hidd | false
device_name | "AHOY-DTU3"
dark_mode | true
sched_reboot | false
mac | "BC:DD:C2:7B:18:3A"
hostname | "AHOY-DTU3"
pwd_set | false
prot_mask | 61
sdk | "2.2.2-dev(38a443e)"
cpu_freq | 80
heap_free | 17208
sketch_total | 2568192
sketch_used | 562
wifi_rssi | -40
ts_uptime | 1054
ts_now | 1700383038
version | "0.8.9"
build | "49ef94c"
menu_prot | false
menu_mask | 61
menu_protEn | false
esp_type | "ESP8266"
radioNrf |  
en | true
isconnected | true
dataRate | 2
mqtt |  
enabled | true
connected | true
tx_cnt | 84
rx_cnt | 0
interval | 0
heap_frag | 25
max_free_blk | 11848
core_version | "3.1.2"
flash_size | 4096
reboot_reason | "External System"
schMax | 12
mqtt |  
broker | "192.168.178.49"
clientId | ""
port | "1883"
user | ""
pwd | ""
topic | "ws_dtu3"
interval | "0"
ntp |  
addr | "192.168.178.1"
port | "123"
interval | "50"
sun |  
lat | "52.42561"
lon | "10.63059"
offs | 600
pinout |  
cs | 15
ce | 0
irq | 2
sclk | 0
mosi | 0
miso | 0
led0 | 255
led1 | 255
led_high_active | false
radioNrf |  
en | true
isconnected | true
dataRate | 2
serial |  
show_live_data | false
debug | false
static_ip |  
ip | ""
mask | ""
dns1 | ""
dns2 | ""
gateway | ""
display |  
disp_typ | 0
disp_pwr | false
disp_pxshift | true
disp_rot | 0
disp_cont | 60
disp_clk | 255
disp_data | 255
disp_cs | 255
disp_dc | 255
disp_rst | 255
disp_bsy | 255

</div></div></div></div>`

### Error description

Die Hardware läuft unter der 0.8.8 prima.
Unter der 0.8.9  RX no answer = 100% auf allen 3 Invertern.

Die Sicherungdateien sind identisch:
2023-11-17_15-13-58_v0.8.8_ahoy_setup.json
2023-11-19_07-19-10_v0.8.9_ahoy_setup.json

Wieder zurück auf die 0.8.8 und die Sache läuft wieder.
Auf die Lösung bin ich gespannt ;-)

**Comment by lille2000** [comment]
Bei mir ist es auch so: keine Kommunikation mit den Invertern seit 0.8.9. 
mit der selben Einstellung läuft es bis 0.8.8

**Comment by lille2000** [comment]
09:48:07 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 1
09:48:07 I: heuristic test mode
09:48:07 I: (#0) TX 27 CH61 | 15 #0 #0 #0 #0 88 94 57 42 80 01 00 65 59 cb c7 00 00 00 00 00 00 00 00 3d 0a dd 
09:48:07 W: RX other inverter:  82 95 76 26 82 95 76 26 81 27 1a 07 e5 04 4d 03 4a 00 68 00 00 00 00 e6 fb be 
09:48:07 I: (#0) request timeout: 500ms
09:48:07 I: (#1) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 1
09:48:07 I: heuristic test mode
09:48:07 I: (#1) TX 27 CH75 | 15 #1 #1 #1 #1 88 94 57 42 80 01 00 65 59 cb c7 00 00 00 00 00 00 00 00 3d 0a b9 
09:48:07 W: RX other inverter:  82 85 46 62 82 85 46 62 81 27 1e 07 e5 04 b9 04 de 00 66 00 00 00 00 48 3e b8 
09:48:08 I: (#1) request timeout: 501ms
09:48:22 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 2, s: 0, f: 0, n: 2 | p: 1
09:48:22 I: heuristic test mode
09:48:22 I: (#0) TX 27 CH3 | 15 #0 #0 #0 #0 88 94 57 42 80 01 00 65 59 cb d6 00 00 00 00 00 00 00 00 6d ca 5c 
09:48:22 W: RX other inverter:  82 95 76 26 82 95 76 26 81 27 1a 07 e5 04 4d 03 4a 00 68 00 00 00 00 e6 fb be 
09:48:22 I: (#0) request timeout: 500ms
09:48:22 I: (#1) Radio infos: -6 -6 -6 -6 -6 | t: 2, s: 0, f: 0, n: 2 | p: 1
09:48:22 I: heuristic test mode
09:48:22 I: (#1) TX 27 CH23 | 15 #1 #1 #1 #1 88 94 57 42 80 01 00 65 59 cb d6 00 00 00 00 00 00 00 00 6d ca 38 
09:48:22 W: RX other inverter:  82 85 46 62 82 85 46 62 81 27 1e 07 e5 04 b9 04 de 00 66 00 00 00 00 48 3e b8 
09:48:23 I: (#1) request timeout: 501ms

**Comment by GrisuXX** [comment]
Kann ich betätigen auch mit ESP32

**Comment by dtuuser** [comment]
Platform
ESP32-D0WD-V3

nRF24L01+ plus (powerlevel Low)

Antenna
external antenna

Power Stabilization
Elko (~100uF)

Eigenes Netzteil 500mA

------------------------------------------------------------

Bei mir auch keine Antwort. Zurück zur 0.8.5, wieder erreichbar

**Comment by GrisuXX** [comment]
PS: Der BUG in #1035 scheint mit der 0.8.7 und 0.8.8 behoben zu sein dafür aber werden die Daten nicht resetet wenn der Status "not available" ist. Und das Häckchenn entsprend gesetzt ist.

**Comment by mtet2** [comment]
> Platform ESP32-D0WD-V3
> Bei mir auch keine Antwort. Zurück zur 0.8.5, wieder erreichbar

Teste einfach mal die 0.8.8. Auf dem ESP8266 läuft die ganz gut.

**Comment by dtuuser** [comment]
> > Platform ESP32-D0WD-V3
> > Bei mir auch keine Antwort. Zurück zur 0.8.5, wieder erreichbar
> 
> Teste einfach mal die 0.8.8. Auf dem ESP8266 läuft die ganz gut.

Ist installiert und läuft. Hat aber 50% RX Fail

Mal sehen, ob Max Power unter Total noch  bei "Nicht erreichbar" genullt wird. War bei der 0.8.5 so

**Comment by mtet2** [comment]
> > > Platform ESP32-D0WD-V3
> > > Bei mir auch keine Antwort. Zurück zur 0.8.5, wieder erreichbar
> > 
> > 
> > Teste einfach mal die 0.8.8. Auf dem ESP8266 läuft die ganz gut.
> 
> Ist installiert und läuft. Hat aber 50% RX Fail
> 
> Mal sehen, ob Max Power unter Total noch bei "Nicht erreichbar" genullt wird. War bei der 0.8.5 so

Schau mal unter System nach ob: "reboot reason	Hardware Watchdog" zugeschlagen hat.

Bei mir HM600 (High) im Keller, HM1500 (Min) auf dem Dach und die DTU (ESP8266 0.8.8) in der Mitte.
Damit kommt man gut aus.

![HM600_1](https://github.com/lumapu/ahoy/assets/120575424/884eb9f1-eb4d-4d28-8bc5-c9f890eafd5a)
![HM1500_1](https://github.com/lumapu/ahoy/assets/120575424/755c5bd0-83bb-41d5-8a09-9e4e7d18037a)

**Comment by dtuuser** [comment]
> > > > Platform ESP32-D0WD-V3
> > > > Bei mir auch keine Antwort. Zurück zur 0.8.5, wieder erreichbar
> > > 
> > > 
> > > Teste einfach mal die 0.8.8. Auf dem ESP8266 läuft die ganz gut.
> > 
> > 
> > Ist installiert und läuft. Hat aber 50% RX Fail
> > Mal sehen, ob Max Power unter Total noch bei "Nicht erreichbar" genullt wird. War bei der 0.8.5 so
> 
> Schau mal unter System nach ob: "reboot reason Hardware Watchdog" zugeschlagen hat.
> 
> Bei mir HM600 (High) im Keller, HM1500 (Min) auf dem Dach und die DTU (ESP8266 0.8.8) in der Mitte. Damit kommt man gut aus.
> 
> ![HM600_1](https://user-images.githubusercontent.com/120575424/284052063-884eb9f1-eb4d-4d28-8bc5-c9f890eafd5a.png) ![HM1500_1](https://user-images.githubusercontent.com/120575424/284052066-755c5bd0-83bb-41d5-8a09-9e4e7d18037a.png)

Bei mir ESP32 finde ich keinen Reboot Grund unter System.... komisch

**Comment by Gubi2023** [comment]
Super, sehr schnelle Fehlerbereinigung! 8.10 installiert:  öfter mal was neues... Aber was bedeuten die ganzen Hiroglyphen? sind die irgendwo erklärt?  C:\Users#
![grafik](https://github.com/lumapu/ahoy/assets/142897856/f2863e7a-85ae-447e-821e-48cd8a01fc5f)

**Comment by lumapu** [comment]
@Gubi2023 du hast den 'privacy mode' eingeschaltet, der ist neu in dieser Version 😉

Edit: Moment, da ist irgendwas falsch, teilweise "privatisiert" teilweise nicht .. wie geht das?

**Comment by Gubi2023** [comment]
oberer Teil ist Version 7.6.5....,.

**Comment by lumapu** [comment]
ah danke für die Aufklärung 😉 konnte es im Code nicht nachvollziehen, jetzt verstehe ich auch warum

**Comment by mtet2** [comment]
Noch eine Anmerkung zur 0.8.10. Die "Radio statistics for inverter" Prozentrechnung hat sich im Ergebnis halbiert.
Wo in der 0.8.8 die Addition der 3 Prozentwerte noch ca. 100 % ergaben, sind es jetzt nur noch ungefähr 50 %.
Wie ist das zu bewerten?

**Comment by dtuuser** [comment]
Bei mir addiert aktuell 86,26

**Comment by lumapu** [comment]
an der Stelle wird gerade heftig geschraubt - verzeiht wenn hier der ein oder andere Fehler passiert - wichtig ist, dass die Inverter überhaupt kommunizieren 😅.
Vielen Dank fürs reporten - das bitte immer weiter tun, dann wissen wir schneller wo es gerade klemmt.

**Comment by dtuuser** [comment]
Aktuelle 0.8.12 liefert leider keine Daten

Inverter #0: Garten is available but no data was received until now

10:24:03 W: Inverter serial does not match

**Comment by Gubi2023** [comment]
komisch, bei mir funzt es tadellos...

**Comment by mtet2** [comment]
Anmerkung zur 0.8.12 (ESP8266) Die "Radio statistics for inverter" Prozentrechnung.
Jetzt aber nicht übertreiben;-) 2050 %
Es werden keine Daten vom Inverter 0 angezeigt.
Inverter 3 ist ausgeschaltet (nicht angeschlossen)
![Screenshot 2023-11-21 at 11-49-55 Index](https://github.com/lumapu/ahoy/assets/120575424/78b1e297-4868-4910-93ce-cbbb3e4964e1)
![Screenshot 2023-11-21 at 11-27-42 Live](https://github.com/lumapu/ahoy/assets/120575424/d5d8ad7c-6cb0-4760-a8af-de6d72994ebb)
![Screenshot 2023-11-21 at 11-34-38 Live](https://github.com/lumapu/ahoy/assets/120575424/7a1955c3-de12-4231-b4e7-9a5e618a5943)

![Screenshot 2023-11-21 at 11-47-36 Live](https://github.com/lumapu/ahoy/assets/120575424/381ed341-0d15-406c-8ed7-49527ed4338c)
![Screenshot 2023-11-21 at 11-28-46 Live](https://github.com/lumapu/ahoy/assets/120575424/1ebfa534-3ccb-451a-b3fb-897899d09504)

**Comment by Gubi2023** [comment]
bei mir sieht es gar nicht schlecht aus:   
<img width="556" alt="Screenshot 2023-11-21 125957" src="https://github.com/lumapu/ahoy/assets/142897856/3bcefe31-aa3a-43da-80f3-07a87ab9254a">

**Comment by dtuuser** [comment]
> komisch, bei mir funzt es tadellos...

Nach 2 mal Reboot jetzt wieder Daten. Aber immer mal einige Minuten kein Empfang.

Immer mal wieder Serial does not match

**Comment by exo1987** [comment]
Bei mir das selbe Problem. Nach zweimal Rebooten geht es. Wobei MQTT ständig nur UNDEF auf bestimmten Kanälen schickt. Teilweise kommen mal die Watt Leistungen richtig, aber meistens nur UNDEF

**Comment by reserve85** [comment]
Bei mir auch das gleiche. 
Die 0.7.60 läuft bei mir wirklich seit Monaten **tadellos**, die neuen 0.8.xx versionen sind bei mir im Vergleich von der Kommunikation wesentlich schlechter. Ständige Aussetzer und teilweise minutenlang keine Kommunikation, die Successrate geht in den Keller. Egal ob mit oder ohne laufender Nulleinspeisung.
Mir ist natürlich klar, dass es die DEV-Version ist. Bitte nicht als gejammer sehen, ich wollte nur anmerken was ich bei mir beobachten konnte.

**Comment by exo1987** [comment]
Ich kann bestätigen, das mein ESP32 AhyoDTU mit 0.7.6.0 am Besten lief. Zwar bekomme ich einen Haufen Alarmmeldungen (DTU command failed), aber zumindest klappt der Abruf bei einer Einstellung von 5 Sek. ca. alle 25 Sekunden. Sobald ich auf höhere Versionen wechsel, habe ich höhere Failed-Raten als Success.

**Comment by Ollipop030** [comment]
@reserve85 @exo1987 

Ich die beiden Versionen vor ein paar Tagen verglichen, siehe hier:
https://github.com/lumapu/ahoy/issues/1221#issuecomment-1810169236

Ich hoffe aber, das die 0.8er Versionen sich noch wieder verbessern werden.

**Comment by exo1987** [comment]
Danke Ollipop! Bei der 0.7.64 habe ich trotzdem nicht so gute Werte wie du erhalten. Welches Abfrageintervall hast du eingestellt? Ich war bei 5Sek. und hatte fast so viele fails wie success

**Comment by reserve85** [comment]
Bei mir ist das **viel** gravierender, ich bekomme mit der 0.8.12 z.B. nahezu keine Kommunikation zustande. Da läuft quasi gar nichts mehr. Wenn ich das ein paar min laufen lassen, dann habe ich TX Count = 105 und RX Success = 4. Also absolut unbrauchbar, es werden mir da nichtmal die ausgelesenen Werte in der Oberfläche angezeigt. Da brauch ich gar nicht weiterprobieren. Mit der 0.7.60 TX Count = 3263 und RX Success = 2962. Beides mit Powerlevel "LOW".

**Comment by Ollipop030** [comment]
> Welches Abfrageintervall hast du eingestellt?

Bei mir 6 Sekunden. Die Fails wurden aber mehr, als ich das Powerlevel erhöht habe.

**Comment by exo1987** [comment]
Ich habe heute auch mal die 0.7.64 installiert und das Powerlevel auf low mit 6Sek Abfrageintervall gesetzt und bekomme miserable Werte...
![image](https://github.com/lumapu/ahoy/assets/25977333/024b5077-6a2a-4461-9eb0-06a62e0ca27c)
Weiß jmd an was das liegen kann?

**Comment by Ollipop030** [comment]
> Weiß jmd an was das liegen kann?

Probiere mal ein wenig mit dem Powerlevel herum. Bei mir bekomme ich mehr fails je höher das eingestellt ist.

**Comment by exo1987** [comment]
Danke für deine Rückmeldung. Die AhoyDTU hängt ca. 40cm vom WR entfernt. Auf MIN bekomme ich die stabilste Verbindung, aber leider überzeugen die Werte immer noch nicht ganz. Das ist jetzt 0.7.36... läuft irgendwie noch am stabilsten...

![image](https://github.com/lumapu/ahoy/assets/25977333/774d42e0-b11a-45fa-a193-046c4449ab3d)

**Comment by Ollipop030** [comment]
Vergrößer mal den Abstand zwischen DTU und Wechselrichter. Bei mir sind es knapp 3 Meter, und das war der Tag heute mit 0.7.60:

![image](https://github.com/lumapu/ahoy/assets/121013633/a38a6ef3-73f0-43d2-9364-57d85f66486e)

**Comment by exo1987** [comment]
Danke für den Input. Habe die DTU nun auch 3-4 Meter entfernt platziert, 0.7.60 aufgespielt und das Power Level auf MIN gestellt. Morgen mal schauen, ob es stabiler läuft!

**Comment by mtet2** [comment]
> Danke für den Input. Habe die DTU nun auch 3-4 Meter entfernt platziert, 0.7.60 aufgespielt und das Power Level auf MIN gestellt. Morgen mal schauen, ob es stabiler läuft!

Gibt es schon neue Erkenntnisse?

Ich habe soeben die 0.8.13 getestet. Sie liefert wie die 0.8.11/.12 bei mir (ESP8266) keine brauchbaren Messwerte.
Die 0.8.10 läuft, hat aber öfter reboots: "reboot reason Hardware Watchdog" oder "Exception"

**Comment by Senderti** [comment]
Mit meinem HM-1200 und dem ESP32 läuft zuletzt Nur die 0.8.10, alle jüngeren Versionen ergeben keine Kommunikation.

**Comment by lumapu** [comment]
wir sind noch an der Kommunikation dran, daher vor dem Update einfach kurz checken, ob's überhaupt verändert wurde. Leider ist zZt. die Zeit zum Entwickeln und Testen sehr kurz - ich bin mir aber sicher, dass wir dieses Jahr noch eine brauchbare Version generieren.
https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md

**Comment by Senderti** [comment]
Danke für den Hinweis, ich teste sofern das changelog irgendwie vielversprechend klingt. Ich habe nur einen Inverter und bislang ist die jüngste funktionierende Version 0.8.10.
