### ISSUE TITLE
Ahoy 0.8.10 "Inverter serial does not match" HMT-1800-6T

### ISSUE THREAD

**Issue by Screambear** [lumapu/ahoy#1237]
## Hardware
  * [ ] ESP32

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller

Hallo,

ich habe beide Module parallel laufen.
Leider bekomme ich von meinem HMT-1800-6T keine Daten. In der Konsole steht immer "Inverter serial does not match". Habe die Serial mehrmals gegengecheckt diese stimmt. Hardware funktioniert. Mit OpenDTU werden die Daten empfangen. Ich mag aber die AhoyDTU irgendwie lieber. Deshalb würde ich mich freuen wenn wir das zum laufen bekommen würden.

Edit:

Beim weiteren Testen ist mir aufgefallen das diese Meldung nur bei der von mit ausgewählten Frequenz von 864.45MHz auftritt. Bei anderen Frequenzen 863.00 und 867.00 kommt die Meldung nicht, ABER Daten empfange ich trotzdem keine.

**Comment by lumapu** [comment]
könntest du einen kurzen Log-Auszug bereitstellen? Habe auch zwei HMS (gleiche Kommunikation wie HMT) daher funktoniert Ahoy hier grundsätzlich.
Freut mich zu hören, dass du Ahoy einsetzen willst.

**Comment by jogybaer0815** [comment]
Leider auch bei mir: Hoymiles HMS-1600 wird nicht kommuniziert. Ich habe testweise jetzt OpenDTU aufgespielt und der Kontakt ist da.
Ich würde auch gerne wieder auf Ahoy zurückflashen, da die gesamte Oberfläche toll gelungen ist.

**Comment by jogybaer0815** [comment]
@lumapu 
Webserialausgabe:
```
14:59:18 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
14:59:18 I: (#0) TX 863.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 65 f2 36 00 00 00 00 00 00 00 00 29 13 3f 
14:59:18 I: (#0) RX  30ms | 0-4dBm | 
14:59:18 W: Inverter serial does not match
14:59:19 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
14:59:19 I: (#0) TX 863.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 65 f2 37 00 00 00 00 00 00 00 00 b9 1e a3 
14:59:19 I: (#0) request timeout: 500ms
14:59:19 I: (#0) TX 868.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 0c 14 2d 51 51 
14:59:33 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
14:59:33 I: (#0) TX 863.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 65 f2 45 00 00 00 00 00 00 00 00 1b 62 0f 
14:59:33 I: (#0) RX  30ms | 0-110dBm | 
14:59:33 W: Inverter serial does not match
14:59:34 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
14:59:34 I: (#0) TX 863.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 65 f2 46 00 00 00 00 00 00 00 00 eb 76 e8 
14:59:34 I: (#0) request timeout: 500ms
14:59:34 I: (#0) TX 868.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 0c 14 2d 51 51 
```
hoffe, es hilft

P.S. Die Ziffern hinter 'TX 863.00Mhz | ' sollen jetzt aber nicht die Serial des Inverters darstellen? Wenn doch, wird nur die 5. bis 12. Ziffer korrekt ausgegeben - oben durch die Stars ersetzt (1.bis 4. fehlt in der Ausgabe und die '15' wäre falsch) 

PPS.: Ausgabe stammt von Version 0.8.12 aber downgrade auf 0.8.10 zeigt gleiches Bild - auch V 0.813 leider

Edit by lumapu: made code better readable

**Comment by lumapu** [comment]
@jogybaer0815 @Screambear  ging schon irgendeine Ahoy-Version? Nicht, dass da was generelles falsch ist. Hier wäre jetzt tatsächlich eine Seriennumer interessant, dann kann ich es im Code entsprechend gegenchecken.

**Comment by jogybaer0815** [comment]
Leider hat noch keine Version funktioniert. Das Release 0.7.36 war für mich nicht configurierbar (CMT)
Ich könnte noch weitere Versionen unter 0.8.1 testen, wenn ich den Link zur bin finden würde.

**Comment by Screambear** [comment]
Sorry fürs lange nicht melden. Bin derzeit leider bei der OpenDTU angekommen. Wo mir da aber die WebUI einfach nicht zusagt.

Bei mir ging auch noch keine Version mit dem CMT. Habe die selbe Ausgabe wie jogybear. Getestet habe ich 0.7.7 (da kann ich aber nicht sagen ob es an der konfiguration etc. lag) 0.8.8 und 0.8.10

**Comment by jogybaer0815** [comment]
... bei Ahoy ist wohl mehr Herzblut "eingearbeitet" :) 
Wundert mich, dass bei lumapu die HMS Daten liefern und unsere taub sind...

Hier die von OpenDTU ausgelesenen Daten: 
Seriennr. xx6484661652
Produktionsjahr: 2022
Produktioswoche: 46
Modell: HMS-1600
Erm.max.Leistung: 1.600W
Bootloader-Version 0.1.0
Firmware-Version 1.0.18
Firmware-Erst.datum: 2022-08-26
Hardware-Teilenr. 270680324
Harware-Version 01.00

**Comment by redscho** [comment]
Hallo zusammen, 
ich habe bis jetzt ähnliche Erfahrungen gemacht, dass die HMS-1600-T4 Serie bei mir bis jetzt mit keiner Ahoy Version kommunizierte. In der "System"-Übersicht unter Ahoy wird suggeriert das CMT2300A "connected" ist und die DTU Radio ID 81xxxxxx wird angezeigt. 
In der Webserial habe ich auch die Meldung: "Inverter serial does not match"

Die Serial habe ich schon geprüft, und in der S-Miles Cloud war diese auch eingetragen und hat funktioniert. 

Hardware DTU: 
ESP32
CMT2300A Module
external antenna (SMA)
AhoyDTU Webinstaller

Hardware HMS-1600-T4:
Hardwarevers.: H00.04.00
Softwarevers.: V01.00.16
SN: 116490917xxx

Ahoy Versionen getestet: 0.8.9; 0.8.10; 0.8.12; 0.8.13 immer das gleiche Bild, dass "Inverter serial does not match"

**Comment by lumapu** [comment]
könnt ihr nochmal ein log ohne die Sterne hochladen? Dafür in den Einstellungen unter `System` den Haken bei `Privacy Mode` entfernen. Zusätzlich bitten den Haken bei `Print whole traces in Log` setzen.

**Comment by redscho** [comment]
> könnt ihr nochmal ein log ohne die Sterne hochladen? Dafür in den Einstellungen unter `System` den Haken bei `Privacy Mode` entfernen. Zusätzlich bitten den Haken bei `Print whole traces in Log` setzen.

Hallo Lukas, hier mein Log...
```
12:10:53 I: (#0) request timeout: 500ms
12:10:53 I: (#0) TX 868.00Mhz | 56 90 91 72 81 81 00 17 65 02 15 21 0c 14 2d 51 05 
12:11:03 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
12:11:03 I: (#0) TX 863.00Mhz | 15 90 91 72 81 81 00 17 65 80 01 00 65 72 f9 c7 00 00 00 00 00 00 00 00 ec 25 75 
12:11:03 I: (#0) request timeout: 500ms
12:11:03 I: (#0) TX 868.00Mhz | 56 90 91 72 81 81 00 17 65 02 15 21 0c 14 2d 51 05 
12:11:13 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
12:11:13 I: (#0) TX 863.00Mhz | 15 90 91 72 81 81 00 17 65 80 01 00 65 72 f9 d1 00 00 00 00 00 00 00 00 8c c3 e5 
12:11:13 I: (#0) RX  30ms | 0-36dBm | 
12:11:13 W: Inverter serial does not match
12:11:14 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
12:11:14 I: (#0) TX 863.00Mhz | 15 90 91 72 81 81 00 17 65 80 01 00 65 72 f9 d2 00 00 00 00 00 00 00 00 7c d7 02 
12:11:14 I: (#0) RX  37ms | 0-38dBm | 
12:11:14 W: Inverter serial does not match
12:11:15 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
12:11:15 I: (#0) TX 863.00Mhz | 15 90 91 72 81 81 00 17 65 80 01 00 65 72 f9 d3 00 00 00 00 00 00 00 00 ec da 9e 
12:11:15 I: (#0) RX  37ms | 0-39dBm | 
12:11:15 W: Inverter serial does not match
12:11:16 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
12:11:16 I: (#0) TX 863.00Mhz | 15 90 91 72 81 81 00 17 65 80 01 00 65 72 f9 d4 00 00 00 00 00 00 00 00 dc fc 8f 
12:11:16 I: (#0) RX  37ms | 0-36dBm | 
12:11:16 W: Inverter serial does not match
12:11:17 I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 1, s: 0, f: 0, n: 1 | p: 30
12:11:17 I: (#0) TX 863.00Mhz | 15 90 91 72 81 81 00 17 65 80 01 00 65 72 f9 d5 00 00 00 00 00 00 00 00 4c f1 13 
12:11:17 I: (#0) request timeout: 500ms
12:11:17 I: (#0) TX 868.00Mhz | 56 90 91 72 81 81 00 17 65 02 15 21 0c 14 2d 51 05 
```

Edit by lumapu: log übersichtlicher gestaltet

**Comment by lumapu** [comment]
hast du den GPIO3 bei dir richtig konfiguriert?

**Comment by jogybaer0815** [comment]
Bei mir wird über GPOIO2 und 3 mit dem CMT kommuniziert und das läuft unter OpenDTU.
So habe ich es dann auch unter Ahoy eingestellt und unter der System-Übersicht wird auch (grün?) angezeigt, dass die Kommunikation läuft

**Comment by lumapu** [comment]
komisch ist, dass bei RX 0-Bytes empfangen wurden. GPIO2 wird bei Ahoy nicht benötigt, nur GPIO3, der GPIO3 wird bei der Systemübersicht nicht geprüft, daher denke ich liegt hier der Fehler.
(Die Anzeige `(#0) RX  37ms | 0-39dBm | ` ist von meiner Seite her nicht optimal, es heißt 0 bytes mit -39dBm empfangen)

so sieht es bei mir aus (HMS-2000-4T)
```
15:27:11 I: (#0) TX 863.00Mhz | 15 80 42 38 10 81 00 17 65 80 0b 00 65 73 27 bf 00 00 00 00 00 00 00 00 44 4c 01 
15:27:11 I: (#0) RX  80ms | 27-69dBm | 95 80 42 38 10 81 00 17 65 01 00 01 01 19 01 18 00 10 00 10 00 2d 00 2d 00 05 88 
15:27:11 I: (#0) RX 129ms | 27-68dBm | 95 80 42 38 10 81 00 17 65 02 27 83 00 05 18 b5 00 7d 00 7d 00 a8 00 c1 00 00 eb 
15:27:11 I: (#0) RX 179ms | 27-69dBm | 95 80 42 38 10 81 00 17 65 03 00 00 00 01 00 00 00 05 0e 62 00 05 54 4d 00 04 ff 
15:27:11 I: (#0) RX 229ms | 27-69dBm | 95 80 42 38 10 81 00 17 65 04 00 00 09 2f 13 87 00 58 b9 19 00 03 00 01 00 25 e5 
15:27:11 I: (#0) RX 270ms | 15-69dBm | 95 80 42 38 10 81 00 17 65 85 00 03 59 c3 90 
15:27:11 I: (#0) Payload (66): 00 01 01 19 01 18 00 10 00 10 00 2d 00 2d 00 05 27 83 00 05 18 b5 00 7d 00 7d 00 a8 00 c1 00 00 00 00 00 01 00 00 00 05 0e 62 00 05 54 4d 00 04 00 00 09 2f 13 87 00 58 b9 19 00 03 00 01 00 25 00 03 
```

**Comment by jogybaer0815** [comment]
> hast du den GPIO3 bei dir richtig konfiguriert?

Was soll da wie eingestellt werden?
Unter 
OpenDTU cmt: clk: 12, cs: 27, fcs: 26,  sdio: 14
Analog habe ich das übernommen. Die Abkürzungen sind ja leider nicht gleich.
Ahoy cmt: csb: 27, fcsb: 26, irq: 34, dio: 14, clk: 12 en: true (der json Sicherung entnommen)
Ist das nicht korrekt?

**Comment by lumapu** [comment]
kommt auf deine Hardware an, ich weiß nicht ob `GPIO3` an `GPIO34` deines ESPs hängt. Den Rest hast du auf jeden Fall richtig übersetzt.

**Comment by jogybaer0815** [comment]
> kommt auf deine Hardware an, ich weiß nicht ob `GPIO3` an `GPIO34` deines ESPs hängt. Den Rest hast du auf jeden Fall richtig übersetzt.

GPIO3 und GPIO34 sind an meinem ESP32-Mini nicht belegt - habe gerade nochmal nachgesehen: oben hatte ich **_irq: 34_** geschrieben, weil so aus der json entnommen, aber das ist unrichtig. 
Fehlt da noch eine Leitung? (auf der ich gerade stehe)
Hmm: die cmt hat doch gar kein irq...

**Comment by lumapu** [comment]
ja da fehlt dann scheinbar eine Leitung. Ahoy benötigt neben den SPI Pins auch eine Interrupt-Leitung (IRQ). Dafür muss vom CMT der Pin `GPIO3` mit einem ESP Pin (nach Wahl) verbunden werden.

**Comment by jogybaer0815** [comment]
Ich finde leider keinen Anschluss an der CMT2300A mit GPIO3 (bzw IRQ wie bei der NRF24L01).

Habe hier den Link mit Pinout, wie ich es verschaltet habe: [Github](https://github.com/tbnobody/OpenDTU/discussions/844)

**Comment by blueline13** [comment]
@jogybaer0815 
Schau dir bitte mal das Bild an. Findest du in deinem verlinkten Post ein paar Einträge tiefer.

Dort ist der GPIO3 vom Modul zu sehen. Im Gegensatz zu OpenDTU braucht ahoy diesen Pin für die Kommunikation mit dem CMT Modul. Verbinde bitte den GPIO3 vom CMT2300 mit einem noch freien GPIO vom ESP vebindest und trage den GPIO vom ESP in ahoy ein.

<img width="162" alt="Unbenannt" src="https://github.com/lumapu/ahoy/assets/56932380/8bb2bd83-a44b-4980-9b93-8f3ee8b0b850">

**Comment by jogybaer0815** [comment]
Danke für den Tipp - das wird auch bei den anderen Leidgenossen das "Problem" lösen.
Ich mache mich gleich an die Arbeit und berichte über das Ergebnis (aber ich bin optimistisch).

**Comment by redscho** [comment]
> ja da fehlt dann scheinbar eine Leitung. Ahoy benötigt neben den SPI Pins auch eine Interrupt-Leitung (IRQ). Dafür muss vom CMT der Pin `GPIO3` mit einem ESP Pin (nach Wahl) verbunden werden.

Ohh, das könnte die Lösung sein, da Wahrscheinlich auf dem PCB der GPIO3 vom CMT2300 nicht auf den ESP verbunden ist. Ich werde morgen mal eine feine Litze auf dem CMT zum Pin7(GPIO3) auf mein ESP-WROOM-32 auf den PIN33 legen und nochmals testen. 

Viele Dank für eure Unterstützung.

![ESP32-36-Pin-Pinout](https://github.com/lumapu/ahoy/assets/115403452/6a7fa535-9161-4a61-9eb4-179cf5c4c20e)
![Screenshot_20231208-175440~2](https://github.com/lumapu/ahoy/assets/115403452/35b6f573-375b-43b2-9b5a-382282045c32)
![Screenshot_20231208-152203~2](https://github.com/lumapu/ahoy/assets/115403452/42c4f2ed-e225-4982-94be-6b4212d4838e)
![Screenshot_20231208-152117~2](https://github.com/lumapu/ahoy/assets/115403452/e0beea79-0ecb-4690-aef8-e830d33cb557)
![Screenshot_20231208-152108~2](https://github.com/lumapu/ahoy/assets/115403452/b5078c62-3de6-48e5-96f3-348151c352b3)
![234539934-4c0f1b23-f0ee-44ac-aceb-3c2eac46861f](https://github.com/lumapu/ahoy/assets/115403452/39b343a5-a792-476c-b0eb-a41fb446a033)

**Comment by lumapu** [comment]
dann machen wir einen Feature-Request daraus, um den `GPIO3` in Zukunft nicht mehr zu brauchen

**Comment by jogybaer0815** [comment]
Ja prima: hier dauert es leider etwas länger, da mit angelöteter GPI03 <-> GPI03 ließ sich die 0.814 an 2 Rechnern nicht flashen - Kabel ab und es klappt mit dem flashen -> GPIO3 am Esp32mini ist TXD und dann geht das flashen nicht

**Comment by redscho** [comment]
> dann machen wir einen Feature-Request daraus, um den `GPIO3` in Zukunft nicht mehr zu brauchen

👍🏼 oder wir weisen darauf hin das bei einigen PCB's dieser Pin7 vom CMT nicht durchgeschliffen ist. Hab jetzt mal die Verbindung reingelötet, muss aber bis morgen warten, da ich gerade keine Sonne ☀️ hier habe.

EDIT: Bei meinem zweiten ESP32 hat es heute funktioniert! Nummer eins muss ich jetzt erst noch prüfen.

**Comment by jogybaer0815** [comment]
> dann machen wir einen Feature-Request daraus, um den `GPIO3` in Zukunft nicht mehr zu brauchen

oder einfach die Infos auffrischen. Auf diesen Anschluss (GPIO3 vom CMT2300A) wäre ich nicht mehr gekommen. Dachte Ahoy und OpenDTU sind Geschwisterchen :)

```19:28:50 I: (#0) RX  82ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 01 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 c0 
19:28:50 I: (#0) RX 132ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 02 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 4b 
19:28:50 I: (#0) RX 182ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 03 00 00 01 35 00 00 00 00 00 30 00 00 00 00 00 00 c7 
19:28:50 I: (#0) RX 232ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 04 00 00 09 25 13 87 01 25 00 00 00 0c 03 e8 00 b1 0e 
19:28:50 I: (#0) RX 273ms | 15-11dBm | 95  *  *  *  *  *  *  *  * 85 00 03 55 5d 4e 
19:28:50 I: (#0) Payload (66): 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 00 00 01 35 00 00 00 00 00 30 00 00 00 00 00 00 00 00 09 25 13 87 01 25 00 00 00 0c 03 e8 00 b1 00 03 
19:29:05 I: (#0) RX  83ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 01 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 c0 
19:29:05 I: (#0) RX 132ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 02 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 4b 
19:29:05 I: (#0) RX 182ms | 27-12dBm | 95  *  *  *  *  *  *  *  * 03 00 00 01 33 00 00 00 00 00 30 00 00 00 00 00 00 c1 
19:29:05 I: (#0) RX 232ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 04 00 00 09 26 13 86 01 24 00 00 00 0c 03 e7 00 b1 02 
19:29:05 I: (#0) RX 273ms | 15-12dBm | 95  *  *  *  *  *  *  *  * 85 00 03 2b 2c 41 
19:29:05 I: (#0) Payload (66): 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 00 00 01 33 00 00 00 00 00 30 00 00 00 00 00 00 00 00 09 26 13 86 01 24 00 00 00 0c 03 e7 00 b1 00 03 
```
So wie es ausschaut, klappt jetzt alles. Habe den Inverter am Netz/Netzteil, um zu testen.

Vielen lieben Dank an alle für die Unterstützung und nun kann auch das Projekt unterstützt werden und eigentlich hier auch geschlossen werden (bug ist es ja nicht mehr wirklich)

**Comment by redscho** [comment]
> > dann machen wir einen Feature-Request daraus, um den `GPIO3` in Zukunft nicht mehr zu brauchen
> 
> oder einfach die Infos auffrischen. Auf diesen Anschluss (GPIO3 vom CMT2300A) wäre ich nicht mehr gekommen. Dachte Ahoy und OpenDTU sind Geschwisterchen :)
> 
> ```
> 19:28:50 I: (#0) RX 132ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 02 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 4b 
> 19:28:50 I: (#0) RX 182ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 03 00 00 01 35 00 00 00 00 00 30 00 00 00 00 00 00 c7 
> 19:28:50 I: (#0) RX 232ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 04 00 00 09 25 13 87 01 25 00 00 00 0c 03 e8 00 b1 0e 
> 19:28:50 I: (#0) RX 273ms | 15-11dBm | 95  *  *  *  *  *  *  *  * 85 00 03 55 5d 4e 
> 19:28:50 I: (#0) Payload (66): 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 00 00 01 35 00 00 00 00 00 30 00 00 00 00 00 00 00 00 09 25 13 87 01 25 00 00 00 0c 03 e8 00 b1 00 03 
> 19:29:05 I: (#0) RX  83ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 01 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 c0 
> 19:29:05 I: (#0) RX 132ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 02 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 4b 
> 19:29:05 I: (#0) RX 182ms | 27-12dBm | 95  *  *  *  *  *  *  *  * 03 00 00 01 33 00 00 00 00 00 30 00 00 00 00 00 00 c1 
> 19:29:05 I: (#0) RX 232ms | 27-11dBm | 95  *  *  *  *  *  *  *  * 04 00 00 09 26 13 86 01 24 00 00 00 0c 03 e7 00 b1 02 
> 19:29:05 I: (#0) RX 273ms | 15-12dBm | 95  *  *  *  *  *  *  *  * 85 00 03 2b 2c 41 
> 19:29:05 I: (#0) Payload (66): 00 01 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 2e 00 00 00 fc 00 00 00 00 01 39 00 01 00 62 00 00 01 33 00 00 00 00 00 30 00 00 00 00 00 00 00 00 09 26 13 86 01 24 00 00 00 0c 03 e7 00 b1 00 03 
> ```
> 
> So wie es ausschaut, klappt jetzt alles. Habe den Inverter am Netz/Netzteil, um zu testen.
> 
> Vielen lieben Dank an alle für die Unterstützung und nun kann auch das Projekt unterstützt werden und eigentlich hier auch geschlossen werden (bug ist es ja nicht mehr wirklich)

Habe es davor schon unterstützt 😉. Dem GPIO3 habe ich auch keine Beachtung geschenkt, da er mir nicht untergekommen ist in der Doku was ich gelesen habe. Vielen Dank auch von mir an alle Helfer!

**Comment by lumapu** [comment]
vielen Dank fürs Feedback - ich ändere die Labels auf gefixt 😀 Danke für eure Unterstützung. Ich bräuchte irgendwie noch die CMT Komponente für Fritzing, dann kann ich die Doku auf https://ahoydtu.de/getting_started/ vervollständigen.
Ich packe in unsere Wishilst #1199 noch den Punkt, CMT ohne `GPIO3`.

**Comment by jogybaer0815** [comment]
Hilfreich wäre bisweilen auch, auf www.ahoydtu.de/getting_started unter 4 Pinout den CMT2300A hinzuzunehmen.

Das CMT-Bauteil zu zeichnen ist nicht so aufwändig... bis dahin hänge ich hier eine Verdrahtung an:
![cmt2300a-esp32mini-gpio3](https://github.com/lumapu/ahoy/assets/61113650/5a4811e1-6fb6-4ac0-a5a5-fb64ba384693)

**Comment by lumapu** [comment]
> Das CMT-Bauteil zu zeichnen ist nicht so aufwändig... 

dann muss ich mir die Zeit dafür mal nehmen, oder kannst du es mir zukommen lassen?

**Comment by jogybaer0815** [comment]
ich muss mich da erst reinlesen

**Comment by jogybaer0815** [comment]
Nicht besonders präzise, aber zur Illustration sollte es reichen:
[CMT2300A.fzpz.zip](https://github.com/lumapu/ahoy/files/13637532/CMT2300A.fzpz.zip)

**Comment by jogybaer0815** [comment]
> > Das CMT-Bauteil zu zeichnen ist nicht so aufwändig...
> 
> dann muss ich mir die Zeit dafür mal nehmen, oder kannst du es mir zukommen lassen?

Nicht besonders präzise, aber zur Illustration sollte es reichen: (den Schaltplan zu erstellen klappt nicht - Fritzing weigert sich stoisch)
[CMT2300A.fzpz.zip](https://github.com/lumapu/ahoy/files/13637532/CMT2300A.fzpz.zip)

**Comment by jogybaer0815** [comment]
Es gibt das CMT2300A inkl Breakoutboard und Antenne, das zu empfehlen ist:
[blinkyparts.com](https://shop.blinkyparts.com/de/Ebyte-Funkmodul-CMT2300A-868-915MHz-Breakoutboard/blink238542.1)

**Comment by lumapu** [comment]
danke ich probiere es aus

**Comment by SmashDde** [comment]
DANKE für den Hinweis CMT2300A GPIO3 > RX0 GPIO3! 
Schon mehrfach kurz davor gewesen den ganzen Krempel gegen die Wand zu werfen! 😄 Jetzt klappt es mit der AhoyDTU [GIT SHA: 7c08d93 :: 0.8.31](https://github.com/lumapu/ahoy/commits/7c08d93)

Auch, wenn ich mich jetzt hier so ins Gespräch rein mogel... wollte eben ein "Danke!" für die Info da lassen. Hab viel länger rumgestochert und rumprobiert wie nötig.

**Comment by lumapu** [comment]
ja die Doku hinkt gewaltig hinterher 🙄

**Comment by stefan123t** [comment]
@jogybaer0815 hier ist das Fritzing Bauteil für das CMT2300A Breakout Board von @tbnobody & Blinky Parts.
[EBYTE E49 900M20S CMT2300A_breakout.fzpz.gz](https://github.com/lumapu/ahoy/files/13847345/EBYTE.E49.900M20S.CMT2300A_breakout.fzpz.gz)

Das hatte ich irgendwann im Sommer 2023 mal gebastelt, nachdem wir da immer noch kein Fritzing davon hatten :stuck_out_tongue_winking_eye: 
https://discord.com/channels/984173303147155506/993500210271629393/1141477467987640331

Und hier noch mal alle meine Fritzing Schematics für OpenDTU, bzw. AhoyDTU inkl. dem o.a. Fritzing Part.
Der GPIO3 ist bei meinem CMT + NRF Schaltplan dummerweise auch noch nicht verdrahtet :roll_eyes: 
[CMT2300A.zip](https://github.com/lumapu/ahoy/files/13847351/CMT2300A.zip)

Laut @Knickohr fehlen da glaube noch die Kondensatoren und die Display Varianten.
https://discord.com/channels/984173303147155506/1029761098381017098/1093154731876159588
Ich bin natürlich immer noch nicht dazu gekommen die Displays und vor allem den Kondensator reinzubasteln :shrug:  

@lumapu abgesehen von der Doku scheint es ja das selbe Problem beim CMT2300A wie beim NRF24L01+ zu sein, daß AhoyDTU/OpenDTU nicht erkennen ob der GPIO3 bzw. IRQ vom RF Modul connected ist.
Könnte man beim CMT2300A wie beim NRF24L01+ ebenfalls einen TX IRQ auf GPIO3 setzen um das ggf. abzuprüfen ?

Die nächsten beiden Kommentare enthalten die alten Fritzings von Knickohr und mir als Bilder.

**Comment by stefan123t** [comment]
![OpenDTU_NRF24+CMT2300A_schem](https://github.com/lumapu/ahoy/assets/11159753/b5ec2532-d60c-4cc6-99d8-5a8bc959293b)
![OpenDTU_NRF24+CMT2300A_bb](https://github.com/lumapu/ahoy/assets/11159753/ce26021e-f951-4a5a-9674-056b70de6c38)
![OpenDTU_CMT2300A_schem](https://github.com/lumapu/ahoy/assets/11159753/f764a052-4d95-4d79-ae4d-b03e340a877a)
![OpenDTU_CMT2300A_bb](https://github.com/lumapu/ahoy/assets/11159753/1e343f5a-3bd2-4712-b91c-3561fd1dccd0)
![OpenDTU_NRF24_schem](https://github.com/lumapu/ahoy/assets/11159753/b669c960-6d7b-45a5-b0c0-2b5f7f733f80)
![OpenDTU_NRF24_bb](https://github.com/lumapu/ahoy/assets/11159753/94e7e8fa-42d1-45df-a9b3-1badaa5fa902)

**Comment by stefan123t** [comment]
Und hier die Fritzings von @Knickohr für die Displays:

![Fritzing_ePaper_ESP32](https://github.com/lumapu/ahoy/assets/11159753/77e98d1a-e5f3-4e0c-8378-09c4cf99891c)
![Fritzing_Nokia_D1](https://github.com/lumapu/ahoy/assets/11159753/605f7d84-8574-43d6-9a0b-9b04f4afa159)
![Fritzing_Nokia_ESP32](https://github.com/lumapu/ahoy/assets/11159753/2786d8d3-9c01-48ba-a4f7-6afa82a4eb0c)
![Fritzing_OLED_8266](https://github.com/lumapu/ahoy/assets/11159753/d89beb38-61bd-4d5f-9484-f73a5a9a3a17)
![Fritzing_OLED_D1](https://github.com/lumapu/ahoy/assets/11159753/b1d8cbe7-7f94-4b8c-93b8-d1b5cdd0454f)
![Fritzing_OLED_ESP32](https://github.com/lumapu/ahoy/assets/11159753/75fd1317-263a-4f9e-aff8-788bad8ff858)

**Comment by lumapu** [comment]
@stefan123t seit letzer Woche habe ich sowohl Schaltbilder als auch Fritzings auf https://ahoydtu.de/getting_started in der Rubrik `Zusammenbau HMS / HMT DTU`. Ich habe das `CMT2300A` selbst gezeichnet und eingefügt. Einzig eine Steckplatine kann man mit dem Board nicht sinnvoll machen - was ja auch der Wirklichkeit entspricht 😉.

Ja man kann das CMT2300A so konfigurieren, dass man einen TX Interrupt auf dem GPIO3 ausgibt - oder man kann den GPIO evtl. auch manuell auslösen. Habe hier die Möglichkeiten noch nicht ausgelotet, hier ist das RFPDK unser Freund.

**Comment by stefan123t** [comment]
@lumapu doch mit dem Breakout Board von Blinky Parts ist das CMT2300A Modul eigentlich sogar pin-kompatibel mit den üblichen NRF24L01+ Pinouts. Deswegen hatte ich das verwendet. 
Evtl. stimmt bei meinem Schematic Symbol irgendwas mit der Skalierung oder den beiden Pins GND / VCC noch nicht, die Verbindungen dazu werden immer etwas schief auf dem Rastermaß. 
Schau Dir ggf. mal die oben **versteckten Kommentare** an, ich wollte nur den Thread / Issue nicht zu unübersichtlich werden lassen :wink:

**Comment by lumapu** [comment]
schon gesehen, aber wenn sich einer ein CMT2300A kauft, hat er nicht gleich auch das Breakout-Board da es mWn. noch kein Standard ist.

**Comment by knickohr** [comment]
@stefan123t 
Du mußt die Verbindung mal von der anderen Seite routen. Ist ein alt bekanntes Problem vom Fritzing 😞
