### ISSUE TITLE
Development version 0.8.8 Frequenzband 868 nicht wählbar

### ISSUE THREAD

**Issue by Frudel1** [lumapu/ahoy#1238]
Ich bin gerade dabei meinen Wechselrichter mit der DTU zu verbinden.
Ich kann das Frequenzband 868 nicht anwählen es hört bei 867 auf.
Jemand eine Idee?

Vielen Dank

**Comment by lumapu** [comment]
Es heißt immer 868MHz, erlaubt ist aber mWn. nur der Bereich von 860 bis 867MHz. Ich werde dem nochmal nachgehen, implementieren lassen sich weitere Frequenzen sehr leicht.
