### ISSUE TITLE
[Suggestion] add date an release No to download file

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#1242]
If possibel on GIT,  add  date and Relese to download name. Actually it is always the same name ahoydtu_dev. Would be much easier not to rename each file at download to manage the releases locally. 
e.g. 
ahoydtu_dev_2023.11.20_v0.8.12.zip

**Comment by rmayergfx** [comment]
@lumapu 
is this an official link? Never seen this. 
Prefer to download from git with the changes suggested.

**Comment by Peertje-62** [comment]
Hi, 
found it on Discord, (search fw.ahoydtu.de)
Because apparently several users are looking for the various versions of the ahoy-dtu.
bye

**Comment by Peertje-62** [comment]
actually you should post your request here:
https://github.com/lumapu/ahoy/issues/1199
bye

**Comment by lumapu** [comment]
the reason behind the identical name was the direct link from https://ahoydtu.de page. In future it can be changed, meanwhile I suggest to use this download listing:
https://fw.ahoydtu.de

**Comment by rmayergfx** [comment]
THX, so now i know it is an official link, don´t want to have scam on my device.
I think it would be also a good idea to change the link on the homepage not to point directly to the latest dev, but to the https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md so everyone can first check, if it is really necessary to load the dev.
Also i don´t understand why the dev is placed on different pages without login and on GIT we need to login to get the dev. 
From my Point of view, this makes no sense to have the dev on different locations /symlink with different name conventions.
To many options to fail.

**Comment by lumapu** [comment]
now the dev builds include a version number, should be fixed

**Comment by DanielR92** [comment]
Then we can close this issue here. :)
