### ISSUE TITLE
[Bug] millis()/micros() overflow handling in hmRadio.h

### ISSUE THREAD

**Issue by You69Man** [lumapu/ahoy#1244]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.12

### Github Hash

53186973

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Die Überlauflogik im hmradio.h sieht für mich nicht korrekt aus, ich glaube da 'verschluckt' er sich (ca. ab Zeile 129):
Die Abfrage muss immer (((unsigned)millis() - (unsigned)starttime) < (unsigned)difftime) lauten, sonst funktioniert so etwas nicht.
```
            uint32_t startMicros = micros() + 5110;
            uint32_t loopMillis = millis() + 400;
            while (millis() < loopMillis) {
                while (micros() < startMicros) {  // listen (4088us or?) 5110us to each channel
```

Hab in der git history nachgeschaut, das war früher schon mal anders (d.h. richtig):
```
            uint32_t startMillis = millis(); // + 400;
            uint32_t startMicros = micros(); // + 5110;
            while (millis() - startMillis < 400) {
                while ((unsigned long)(micros() - startMicros) < 5110) {  // listen (4088us or?) 5110us to each channel
```

Das ist mit commit bf772756 "improved set limit and radio statistics" reingekommen.

**Comment by lumapu** [comment]
ok, der Überlauf wird aus meiner Sicht in beiden Fällen vernachlässigt. Ich weiß nicht, ob der cast auf `unsigned long` hier noch was auswirken kann.
Danke für den Hinweis. Besonders kritisch ist der `micros` Teil, da dieser Zähler mWn. schon nach 11 Tagen überläuft.

**Comment by You69Man** [comment]
Stimmt, der Cast ist bei unsigned Long nicht mehr notwendig (bei unsigned short wäre er es schon), es ging mir bei meinem abstrakten Beispiel jedoch darum, auf den 'unsigned' Aspekt hinzuweisen, wegen dem das Overflow Handlung ja funktioniert, wenn man es richtig macht. Beim ursprünglichen code (wie zitiert) funktioniert der Überlauf korrekt.
Grund: 

unsigned long a, b, c;

a = 0xFFFFFFFE;
b = 0xFFFFFFFF;
c = b - a; // -> 1

a = a + 1; // -> 0xFFFFFFFF
b = b + 1; // -> 0x0000000 Überlauf
c = b - a; // -> 1!

Ich mache das übrigens auch immer so, das funktioniert sehr zuverlässig, und braucht kein weiteres Überlaufhandling. Nur richtig schreiben muss man es halt (so wie es ja auch im ursprünglichen Code war) ;)

PS: Der micros() läuft übrigens bereits nach 70 Minuten über!

**Comment by haraldhotzbehofsits** [comment]
Die 5110 als auch die 400 sind magic numbers, die 5110 wird 2 mal verwendet, eigentlich 2 mal mit dem gleichen statement:

startMicros = micros() + 5110;

**Comment by You69Man** [comment]
> Die 5110 als auch die 400 sind magic numbers, die 5110 wird 2 mal verwendet, eigentlich 2 mal mit dem gleichen statement:
> 
> startMicros = micros() + 5110;

Ja, das ist mir auch schon aufgefallen. Das Problem kommt leider mehrfach vor, nicht nur bei diesen 'magic numbers', sondern ist auch an anderen Stellen systematisch falsch (sorry @lumapu, das ist nicht böse gemeint, aber leider wahr). Ich würde gerne helfen, das zu bereinigen, aber ich verstehe teilweise leider einfach nicht die kommunikationstechnischen Hintergründe und Zeiterwartungen der Inverter, und ich würde da wahrscheinlich vieles nur verschlimmbessern. Ich könnte maximal nur noch ein paar Stellen aufzeigen, die mir verdächtig erscheinen, aber ich will auch nicht nerven...

**Comment by LeSpocky** [comment]
> ok, der Überlauf wird aus meiner Sicht in beiden Fällen vernachlässigt. Ich weiß nicht, ob der cast auf `unsigned long` hier noch was auswirken kann. Danke für den Hinweis. Besonders kritisch ist der `micros` Teil, da dieser Zähler mWn. schon nach 11 Tagen überläuft.

Ich denke das kommt drauf an wie breit `unsigned long` auf dem Target ist?  Im Zweifel kann man da einfach `uint64_t` nehmen, wenn man einen breiteren Integer haben will, der nicht so schnell überläuft.

Was allgemein Regeln und Empfehlungen zum Handling von so Überläufen angeht, schaut Euch mal die SEI CERT Coding Standards an:

- [Rule 04. Integers (INT)](https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152052)
- [Rec. 04. Integers (INT)](https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87151979)

**Comment by You69Man** [comment]
Es war ja wie gesagt schon mal richtig (siehe oben), und müsste daher einfach nur wieder so gemacht werden, wie es war ...

**Comment by lumapu** [comment]
> Ja, das ist mir auch schon aufgefallen. Das Problem kommt leider mehrfach vor, nicht nur bei diesen 'magic numbers', sondern ist auch an anderen Stellen systematisch falsch (sorry @lumapu, das ist nicht böse gemeint, aber leider wahr). Ich würde gerne helfen, das zu bereinigen, aber ich verstehe teilweise leider einfach nicht die kommunikationstechnischen Hintergründe und Zeiterwartungen der Inverter, und ich würde da wahrscheinlich vieles nur verschlimmbessern. Ich könnte maximal nur noch ein paar Stellen aufzeigen, die mir verdächtig erscheinen, aber ich will auch nicht nerven...

ja bitte schreib mir wo die Fehler sind. An den Stellen wollte ich einfach die Operations in den loops reduzieren, indem die Summe nur einmal gemacht werden muss und in der Schleife lediglich verglichen wird - war gut gemeint aber ist wohl nach hinten losgegangen.
Danke, dass ihr euch den Code antut - genau deswegen liebe ich Open-Source 🎉

**Comment by You69Man** [comment]
fixes in #1298
