### ISSUE TITLE
Bug ?  Time Stamp

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1245]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [X] I will attach/upload an Image of my wiring

### Version

0.8.11

### Github Hash

ba8d1f3

### Build & Flash Method

ESP Tools (flash)

### Setup

DTU interval 30 seconds

### Error description

Hi,
With older versions I had a time stamp every 30 seconds , alternate , HM600 & HM 300.
Now with 0.8.11 according to GUI both at the same time?
Hope to hear from you,
Kind regards
![ahoy](https://github.com/lumapu/ahoy/assets/144957788/e7c768e7-25f5-41ca-a498-9ff3104ab080)

**Comment by lumapu** [comment]
Yes this was the initial idea of communcating. All requests are aligned in a queue. Once the first inverter has answered the second one is communicating. The interval is now an interval, in all versions before 0.8.x the interval was more like a communication break.

**Comment by Peertje-62** [comment]
thx
