### ISSUE TITLE
Bad Radio Statistics with 0.8.xx

### ISSUE THREAD

**Issue by Otto-Normal** [lumapu/ahoy#1249]
## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ x] external antenna (SMA)

### Power Stabilization:
* [ x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.12
Github Hash: _______

### Build & Flash Method:
* [ x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hallo,
die Funkverbindung zu meinem HM 1500 ist trotz Updates auf diverse 0.8.xx Versionen ziemlich instabil.
Viel stabiler lief die Version 0.7.59. Nachfolgende Version haben mich immer wieder zum Downgrade veranlasst.
Damit dies quantitativ bewertet werden kann habe ich mal Screenshots 0.7.59 vs. 0.8.12 beigefügt. 

Ich hoffe dies hilft für Optimierungen.

Besten Dank vorab!
![IMG_0229](https://github.com/lumapu/ahoy/assets/129395924/6221e17a-8010-41d5-a472-32419928f480)
![IMG_0225](https://github.com/lumapu/ahoy/assets/129395924/75fbe642-4299-47f0-beb2-16419dce124f)

**Comment by khbraemer** [comment]
Dem kann ich nur beistimmen. Die Version 7.59 lief bei mir wochenlang ohne Probleme. Alle 8.xx liefen bei mir sehr schlecht, besonders in Bezug auf die  Verbindung zum Wechselrichter HM 1500. Oft wurde der Wechselrichter garnicht gefunden. Jetzt habe ich die Version 8.13 installiert, und siehe da, die Verbindung zum Wechselrichter wird nach kurzer Zeit einwandfrei aufgebaut. (max 2 min). Die Version 7.59 baute die Verbindung innerhalb von 30 s auf. Die DTU mit ESP 32 hängt seit Monaten immer an der gleichen Stelle, ca. 1m vom Repeater und ca. 8m vom Wechselrichter entfernt mit Low Power.

**Comment by Dirk-Ahoy** [comment]
Das Problem ist bekannt - ist aber gerade Zeitmangel bei den Devs, wird aber noch gefixt - die neue Heuristik arbeitet noch nicht richtig.  

Bitte auch mal in den neuen Einstellungen gucken - default ist der Powerlevel auf MIN
