### ISSUE TITLE
Negative Temperaturen vom Inverter sind mit drei Nachkommastellen dargestellt.

### ISSUE THREAD

**Issue by lille2000** [lumapu/ahoy#1251]
Das ist kein Fehler, eher „unhübsche“ Darstellung
Bei negativen Temperaturen  sind die Temperaturen auf 3 Nachkommestellen angegeben.  (0.8.13)
![IMG_2193](https://github.com/lumapu/ahoy/assets/86225787/37b20dda-86b7-46e7-964b-9891b4f181a1)

**Comment by BastyESP** [comment]
Hatte ich gestern auch bei einem Inverter -0.699, aber gestern waren sie auch schnell wieder alle vormittags 11.20-11.40uhr mit AhoyDTU Offline, mit Open noch Online hatte dazu auch was in Discord geschrieben, scheint aber kein anderer das Problem zu haben.

Hab aktuell mit OpenDTU 5w auf 2 Invertern (werden nur 2/3 damit abgefragt), und 0 Erzeugung laut AhoyDTU die 3 Abfragt...da scheint was komplett intern abgeschmiert zu sein, hatte ich noch gar nicht in den ganzen Monaten, das es Abgeschmiert aber die Web Version problemlos läuft. 0.8.13 ist es bei mir übrigens...

edit: Nach einem Reboot ist die Ahoy auch wieder mit im Boot...

**Comment by LeSpocky** [comment]
> Hatte ich gestern auch bei einem Inverter -0.699, aber gestern waren sie auch schnell wieder alle vormittags 11.20-11.40uhr mit AhoyDTU Offline, mit Open noch Online hatte dazu auch was in Discord geschrieben, scheint aber kein anderer das Problem zu haben.

Das kann ich so nicht unterschreiben.  Bei mir werden negative Temperaturen auch mit mehreren Nachkommastellen dargestellt, development version 0.7.57 aktuell.

**Comment by lille2000** [comment]
Heute war es endlich mal wieder kalt genug.  Die Darstellung ist nun schöner. 
![IMG_2244](https://github.com/lumapu/ahoy/assets/86225787/f19517b5-12fc-44e3-b171-598ce83d2aa6)

**Comment by lille2000** [comment]
Ticket wir geschlossen
