### ISSUE TITLE
AhoyDTU Hoymiles HM800 - Reactive Power 0

### ISSUE THREAD

**Issue by Wind06** [lumapu/ahoy#1256]
Hi,

I have an installation with 2 HM1500 which is working ok.
I installed a new Inverter HM800, which is also working ok apparently.
but on AhoyDTU the HM800 do have a reactive power reported to 0

is it normal ?

Your help will be very much appreciated.

![Capture d’écran 2023-12-06 à 12 02 55](https://github.com/lumapu/ahoy/assets/64360875/dd977bfe-e6d6-4472-91c8-bc79ea95cd06)

**Comment by You69Man** [comment]
On Onduleur_3 the reactive power of 0var is at least consistent with a power factor of 1 (even if it's not very plausible).
More strange are Onduleur_1 and _2, where the reactive power is 18.2var while the power factor is shown as 1.

**Comment by Wind06** [comment]
Thanks for your answer, is there something I can do ? 
Or just let the installation as it is ?
apparently the Ac Power seems to be closed to the actual weather condition.

**Comment by kiu77** [comment]
Interesting too is that the Power Limits are over 100%
;-)

**Comment by Wind06** [comment]
Currently using hoymiles-DTU with zero export set. Sometimes the % is very strange.
When I disable the zero export from hoymilesDTU, AhoyDTU report 484% ….

That’s one of the reason why I want to use AhoyDTU with zero export but I have a DDSU666 as a smart meter.

**Comment by Wind06** [comment]
Hello, After a factory reset and also changed Pins connections according to ESP8266 recommandation the power limit is back at 100% which is more accurate :-)

No change for the reactive power.
