### ISSUE TITLE
Reset YieldDay At Midnight not working

### ISSUE THREAD

**Issue by Jumperm** [lumapu/ahoy#1257]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.12

### Github Hash

Wo finde ich diesen?

### Build & Flash Method

ESP Tools (flash)

### Setup

Mit 0.7.46 keinen Probleme

### Error description

Keine Nullung der YieldDay um Mitternacht. Bei erstem verbinden der DTU Übernahme des Wertes des Vortages. Ich lese die Werte per API aus.

rest:
 - authentication: basic
    scan_interval: 5
    resource: http://192.168.1.99/api/inverter/id/0
    sensor:
     - name: "BKW Tagesertrag"
        unique_id: ahoy_HM300_yield_day
        device_class: energy
        unit_of_measurement: "Wh"
        state_class: measurement
        value_template: '{{ value_json.ch[0][7] }}'

![IMG_0278](https://github.com/lumapu/ahoy/assets/6853816/06cc1d82-dcc4-46ff-9f4e-a9b3237c21d0)
![IMG_0277](https://github.com/lumapu/ahoy/assets/6853816/13b6047b-4769-49a7-a119-9509edb4e37e)

**Comment by knickohr** [comment]
Doch, es nullt, aber irgendwoher kommen wieder alte Werte 😲

**Comment by Jumperm** [comment]
Ich lese das per API aus. ich Frage mich halt, woher der Wert des Vortages kommt!

**Comment by knickohr** [comment]
Wahrscheinlich noch in irgendeiner Variable vorhanden. Das hatten wir schon mal.

**Comment by Jumperm** [comment]
> Wahrscheinlich noch in irgendeiner Variable vorhanden. Das hatten wir schon mal.

Aus dem WR/DTU oder im Homeassistant?

**Comment by knickohr** [comment]
WR kann man ausschließen, DTU wäre möglich, und wenn es aus HA kommt, dann ist der Issue hiermit geclosed (andere Baustelle) 😉

**Comment by Jumperm** [comment]
Da ich weder an Homeassistant noch am WR etwas geändert habe gehe ich von einem Bug in der DTU aus. ich hab im Ursprungscode nochmal meine Rest API Anfrage des Homeassisant gepostet.

**Comment by Jumperm** [comment]
Ohne mein zutun wurde heute Morgen wieder bei 0 angefangen. Kein Neustart oder Ähnliches durchgeführt!
Ich beobachte das mal weiter. 

Edit nach 4 Tagen: Weiterhin wird um Mitternacht zurückgesetzt und beim Starten des WR wird der letzte Stand des Vortages übernommen.

**Comment by Jumperm** [comment]
Es ist ein Ahoy Problem. Nach dem flashen auf die aktuelle 0.8.23 wird der korrekte Wert aus dem WR abgerufen. Oder im Hintergrund wurde es gefixed.

Edit nach einem Tag: Heute bei Tagesbeginn wurde wieder der vortages Wert  übernommen. 😕

**Comment by strepwo** [comment]
@Jumperm kannst du mal 0.8.29 testen? Da ist es möglicherweise repariert

**Comment by Jumperm** [comment]
> @Jumperm kannst du mal 0.8.29 testen? Da ist es möglicherweise repariert

Mach ich mit der 0.8.35
