### ISSUE TITLE
MQTT :  umbenennen eines Topics und „mit Leben“ füllen

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1265]
Mir ist seit der ersten 0.8.x aufgefallen das es den alten Topic „topic/comm_disabled“ nicht mehr gibt und durch den neuen Topic „topic/dis_night_comm“ ersetzt wurde.  Diesen gibt es jetzt sowohl für jeden Inverter einzeln als auch global. Der globale ist leider momentan noch ohne Funktion.

Vorschlag : 
- Umbenennen des globalen Topics wieder zurück nach „topic/comm_disabled“
- Mit Leben füllen :  true bei Nacht und false bei Tag (wie vorher beim alten „topic/comm_disabled“
- Die anderen inverterspezifischen Topics können so bleiben

Somit wäre die Abwärtskompatibilität wieder hergestellt 😉

**Comment by knickohr** [comment]
Kein Enhancement, sondern die alte Funktion vom Topic wieder herstellen 😉

**Comment by lumapu** [comment]
dann doch ein bug

**Comment by knickohr** [comment]
Nein, einfach nur vergessen worden 😅

**Comment by knickohr** [comment]
Funzt wieder 👍
