### ISSUE TITLE
Feedback Versionen und Verhalten

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#1266]
## Hardware
ESP32

### nRF24L01+ Module
nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
external antenna (SMA)

### Power Stabilization:
100uF Electrolytic Capacitor 

### Build & Flash Method:
AhoyDTU Webinstaller

### Inverter
2 x HM-800

Kurzes Feedback:
0.8.13 lief gut.
Nach Update auf 0.8.19 war das Setup irgendwie zerschossen.
Im Log stand: "Inverter serial does not match". In den Settings stand aber der richtige Wert.
Also neu geflachst und nochmal auf 0.8.19 upgedatet. Jetzt lief es, aber der Balken links
für die Feldstärke der Inverter war von 4 auf 3 Striche runter.
Nach Update auf 0.8.21 dauert es ein paar Minuten, bis die Werte von beiden invertiert 
kamen (schnell der eine, langsam der andere) und es läuft, aber der linke Balken hat nur noch
einen einzigen Strich, was ja nicht so gut ist.

**Comment by lumapu** [comment]
duplicate #1268
