### ISSUE TITLE
Heuristic again

### ISSUE THREAD

**Issue by You69Man** [lumapu/ahoy#1269]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.21

### Github Hash

c06705d

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Die heuristic update nicht korrekt. Grund vermutlich:

heuristic.h Zeile 106
 if(RF_TX_TEST_CHAN_1ST_USE == ih->txRfChId) {
                        // switch back to original quality
                        ih->txRfQuality[ih->txRfChId] = ih->saveOldTestQuality;
                    }
RF_TX_TEST_CHAN_1ST_USE  ist 0xFF, das txRfQuality[] beherbergt aber nur 5 Kanäle, also Indexüberlauf...

**Comment by lumapu** [comment]
sehe den Fehler nicht, ich hoffe du hast gesehen, dass es zwei verschiedene Variablen sind:
* `ih->testChId`
* `ih->txRfChId`

dadurch sehe ich keinen Indexüberlauf. Danke für deinen Hinweis.

**Comment by You69Man** [comment]
Das sollte wahrscheinlich so sein, ist es aber nicht:
![Unbenannt](https://github.com/lumapu/ahoy/assets/6373072/b1a805ef-3f73-467c-aa46-4eb8aa87346a)

**Comment by lumapu** [comment]
ah Zeile `106`, ich habe in `78` geschaut, sorry. Das ist der Nachteil von doppeltem Code 😉

**Comment by lumapu** [comment]
fix ist nicht so schwerwiegend wie angenommen, der Code in der `if` Condition wird nie aufgerufen, hier der fix:

```patch
diff --git a/src/hm/Heuristic.h b/src/hm/Heuristic.h
index 4b3705d..c3ce5cc 100644
--- a/src/hm/Heuristic.h
+++ b/src/hm/Heuristic.h
@@ -103,7 +103,7 @@ class Heuristic {
                     // graceful evaluation for big inverters that have to send 4 answer packets
                     updateQuality(ih, RF_TX_CHAN_QUALITY_OK);
                 } else if((rxFragments - ih->lastRxFragments) < 2) {
-                    if(RF_TX_TEST_CHAN_1ST_USE == ih->txRfChId) {
+                    if(RF_TX_TEST_CHAN_1ST_USE == ih->testChId) {
                         // switch back to original quality
                         ih->txRfQuality[ih->txRfChId] = ih->saveOldTestQuality;
                     }

```

Vergleiche mit original Code von @oberfritze

https://github.com/oberfritze/ahoy-all-in-one/blob/b12a161165c0a8c1b17dc8fb0c44acf009592d58/src/hm/hmInverter.h#L734-L741

**Comment by You69Man** [comment]
PR #1270
Du warst schneller :)

**Comment by You69Man** [comment]
Danke für den Hinweis auf den Originalcode von Oberfritze!
Damit hab ich jetzt auch noch den anderen Heuristik-Bug, wodurch die verlorenen Pakete nicht mehr zu einer Abwertung der Qualitätszahlen führen gefunden
-> Habe noch einen commit zum #1270 dazugehängt!

Der 'Invalid'-Status ist meiner Meinung nach invalid :)
