### ISSUE TITLE
[HMS-1000] data the inverter failed to parse and the data didn't come out.

### ISSUE THREAD

**Issue by aditiyagio** [lumapu/ahoy#1271]
### Platform

ESP32 WROOM 32D

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [x] I will attach/upload an Image of my wiring

### Version

Development 03. Version 0.8.18

### Github Hash

-

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup
Config:
SCLK = GPIO12 (HSPI MISO)
SDIO = GPIO14 (HSPI CLK)
CSB   = GPIO17
FCSB = GPIO26
GPIO3 = GPIO34
-

### Debug Serial Log output

```shell
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 7, s: 0, f: 0, n: 7 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 9B 00 00 00 00 00 00 00 00 9E F5 8D 
I: (#0) RX  59ms | 14 -86dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 8, s: 0, f: 0, n: 7 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 9B 00 00 00 00 00 00 00 00 9E F5 8D 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 9, s: 0, f: 0, n: 8 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 B9 00 00 00 00 00 00 00 00 3F 75 8E 
I: (#0) RX  59ms | 14 -84dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 10, s: 0, f: 0, n: 8 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 B9 00 00 00 00 00 00 00 00 3F 75 8E 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 11, s: 0, f: 0, n: 9 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 D7 00 00 00 00 00 00 00 00 5D 91 66 
I: (#0) RX  58ms | 14 -84dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 12, s: 0, f: 0, n: 9 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 D7 00 00 00 00 00 00 00 00 5D 91 66 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 13, s: 0, f: 0, n: 10 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B8 F5 00 00 00 00 00 00 00 00 FC 11 65 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 14, s: 0, f: 0, n: 11 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 13 00 00 00 00 00 00 00 00 5D A2 90 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 15, s: 0, f: 0, n: 12 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 31 00 00 00 00 00 00 00 00 FC 22 93 
I: (#0) RX  58ms | 14 -85dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 16, s: 0, f: 0, n: 12 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 31 00 00 00 00 00 00 00 00 FC 22 93 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 17, s: 0, f: 0, n: 13 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 4F 00 00 00 00 00 00 00 00 5E 0B 66 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 18, s: 0, f: 0, n: 14 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 6D 00 00 00 00 00 00 00 00 FF 8B 65 
I: (#0) RX  59ms | 14 -83dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 19, s: 0, f: 0, n: 14 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 6D 00 00 00 00 00 00 00 00 FF 8B 65 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 20, s: 0, f: 0, n: 15 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 8B 00 00 00 00 00 00 00 00 9B 69 05 
I: (#0) RX  58ms | 14 -82dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 21, s: 0, f: 0, n: 15 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 8B 00 00 00 00 00 00 00 00 9B 69 05 
I: (#0) request timeout : 500ms from freq : 868000Hz
W: Desired frequency is out of EU legal range! (863 - 870MHz)
I: (#0) TX 915.00Mhz | 56  *  *  *  * 81 00 17 65 02 15 21 20 14 ED 4D BA 
I: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 22, s: 0, f: 0, n: 16 | p: 30
I: (#0) TX 868.00Mhz | 15  *  *  *  * 81 00 17 65 80 01 00 65 7A B9 A9 00 00 00 00 00 00 00 00 3A E9 06 
I: (#0) RX  59ms | 14 -83dBm | D6  *  *  *  *  *  *  *  * 02 01 17 3C B0 
 Tes Data SuccesI: (#0) Radio infos: -6 -6 -6 -6 -6 | t: 23, s: 0, f: 0, n: 16 | p: 30

### Error description
Here I use a HMS microinverter, and for DTU I use the E49 900M20S. I'm trying to read the data from the HMS inverter, but the problem is that the RX is right, but for the data of the inverter failed to parse and the data didn't come out. Maybe if anyone can help me ask for help.

**Comment by aditiyagio** [comment]
### Error description
Here I use a HMS microinverter, and for DTU I use the E49 900M20S. I'm trying to read the data from the HMS inverter, but the problem is that the RX is right, but for the data of the inverter failed to parse and the data didn't come out. Maybe if anyone can help me ask for help. @lumapu

**Comment by lumapu** [comment]
you only get packet number 2, but never number 1 and the last one.
Which inverter do you have?

**Comment by aditiyagio** [comment]
i have inverter HMS-1000 Series. @lumapu

**Comment by aditiyagio** [comment]
is there anything that can we check or test to find the root cause of my problem? @lumapu

**Comment by lumapu** [comment]
have you tried a newer version since then?
You are the first one who has such a problem. How far is the distance to your inverter?
Do you think there is much other traffic in the 868MHz band?

**Comment by aditiyagio** [comment]
Yeah, I'm using the latest firmware development, and I've tried it in a radius of 4 meters, but it's not working. And actually, the RX on my serial logs does not appear if the HOY_BOT_FREQ_KHZ settings are not changed to 915 MHz. and after I change the HOY_BOT_FREQ_KHZ, the Rx on the log serial appears. @lumapu

**Comment by aditiyagio** [comment]
<img width="339" alt="image" src="https://github.com/lumapu/ahoy/assets/133744927/f1fccfc2-c7d5-4961-9985-453fb554525d">

@lumapu

**Comment by lumapu** [comment]
are you located in the US? Sorry didn't know that. Can you try to be more clear? 
What do you mean by "on my serial logs does not appear"? What appears once you change the BOOT_FREQ?

**Comment by lumapu** [comment]
are there any news?

**Comment by aditiyagio** [comment]
My location is in Southeast Asia, specifically in Indonesia. My problem remains the same, my device still cannot read data from the HMS-1000 inverter @lumapu

**Comment by aditiyagio** [comment]
Do you have any suggestions regarding my problem? What steps should I take to be able to access data from the inverter? @lumapu

**Comment by lumapu** [comment]
you don't have to change the `HOY_BOT_FREQ_KHZ` because you already got data from your inverter on `868MHz` (as I can see in your log above).
Can you have another try with the latest release (`0.8.36)` and post another log with this version?

**Comment by aditiyagio** [comment]
okay, i will try first @lumapu

**Comment by aditiyagio** [comment]
<img width="479" alt="image" src="https://github.com/lumapu/ahoy/assets/133744927/f1b44d65-4c0c-4a8d-bcc0-57ac9341fb9c">

**Comment by aditiyagio** [comment]
here's the log using firmware version 0.8.36 @lumapu

**Comment by aditiyagio** [comment]
![20240102](https://github.com/lumapu/ahoy/assets/133744927/b33ede4f-c172-44a0-a62d-bad73f654960)

**Comment by aditiyagio** [comment]
@lumapu please insight

**Comment by lumapu** [comment]
can't see any RX in your Log. Do you know if your inverter sends in `868MHz` oder `915MHz` band?
Do you have a SDR (software defined radio) with you?

**Comment by nazmibojan** [comment]
Hi @lumapu , I'm Nazmi and currently helping @aditiyagio in this project. In Indonesia I think we use the different frequency for sub-1GHz. We are using this DTU from Hoymiles: https://www.hoymiles.com/product/dtu/lite-s/ and it's worked. I think in Indonesia we use 915 or 923 MHz frequency. So if we use different frequency with Europe, in which part of the code that we need to change?

**Comment by lumapu** [comment]
it's not that easy because of several points where you need to adjust.
Maybe I can try to add an option to select different frequency for the range you mentioned.
Do you know on which frequency the inverter starts? Do you have a SDR with you?

**Comment by nazmibojan** [comment]
I see. Currently we dont have SDR but we consider to purchase it. Is RTL-SDR enough to detect it? Or we need Hack-RF in this case @lumapu ?

**Comment by lumapu** [comment]
Yes RTL SDR should be enough. You only need to measure 915MHz for HMS / HMT series.

**Comment by nazmibojan** [comment]
Oke @lumapu . We will get back to you soon. Thanks a lot

**Comment by nazmibojan** [comment]
Hi @lumapu, we already check the RF signal using RTL-SDR. We think this inverter is using 915MHz frequency. You can check the picture belom.

![WhatsApp Image 2024-01-24 at 12 42 01 PM](https://github.com/lumapu/ahoy/assets/17125575/024f476a-37b7-4a8e-8bca-89e9bcb826ee)

We also record the video when running DTU device to communicate with HMS-1000: https://drive.google.com/file/d/11lKiyDBvDaRQ-CVo3md8meCGIAihnjdl/view?usp=sharing

Wdyt @lumapu ?

**Comment by lumapu** [comment]
wow really good, I'll check it.

**Comment by aditiyagio** [comment]
hello @lumapu , have you done to check for this?  I will wait for the good news ✌️

**Comment by lumapu** [comment]
sorry had no time so far. I think I can build a special version for you, which ESP are you using?

**Comment by lumapu** [comment]
please check `0.8.66` (https;//fw.ahoydtu.de). I've added a region selector to `/system` as well as the compared frequencies for this region.
Please reboot your DTU once you changend the region to have the ability to set the correct frequency.

As you have a original Hoymiles DTU with you be sure to turn it off once you try to communicate using AhoyDTU. It isn't possible to have two DTUs talking to the same inverter.

**Comment by nazmibojan** [comment]
Thanks @lumapu !
We will try it tomorrow and get back to you about the results

**Comment by lumapu** [comment]
please try the latest development Version `0.8.68` https://fw.ahoydtu.de

**Comment by aditiyagio** [comment]
@lumapu wow this works, I'm using development3 firmware 0.8.67
<img width="599" alt="Screenshot 2024-01-30 115621" src="https://github.com/lumapu/ahoy/assets/133744927/6f4efeb4-4975-41b4-b1dd-ac2a72b4a1f2">

**Comment by aditiyagio** [comment]
<img width="700" alt="Screenshot 2024-01-30 115841" src="https://github.com/lumapu/ahoy/assets/133744927/4ab05e05-41b7-4598-9f67-375ec908b5cc">

@lumapu

**Comment by lumapu** [comment]
thank you for the response. That is good news.

**Comment by lumapu** [comment]
@nazmibojan how is your DTU performing with the new version?

**Comment by nazmibojan** [comment]
Sorry @lumapu , maybe we can check this next week. Because our DTU device is currently using by another team until next week. We will get back to you soon Lukas
