### ISSUE TITLE
Angebot: Syslog als Ersatz für Web-Serial

### ISSUE THREAD

**Issue by fsck-block** [lumapu/ahoy#1273]
Ich habe auf Basis der development03 eine Unterstüzung für Langzeit-Logging via syslog implementiert.
Dieses Logging benutzt/ersetzt die Ausgaben über Web-Serial und sendet die Daten an einen syslog-server zur Speicherung.

Wenn hierfür Interesse besteht kann ich dieses Feature (derzeit mit syslog IP-Adresse als #define) auch als PR einbringen. 

Bitte um Rückmeldung.

**Comment by lumapu** [comment]
ja! sehr cool interessiert mich - gerade für uns dev's sehr hilfreich 😎

**Comment by fsck-block** [comment]
Schau' mal in PR #1274 rein, ob's gefällt.
