### ISSUE TITLE
Nur 4 Inverter möglich?

### ISSUE THREAD

**Issue by walter2323** [lumapu/ahoy#1275]
Leider kann ich nicht mehr als 4 Wechselrichter hinzufügen.
Lässt sich dies beheben?

## Hardware
  * [x] ESP8266

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by knickohr** [comment]
Korrekt !

Mit einem ESP8266 sind ressourcenbedingt nur 4 Inverter möglich.

Mit einem ESP32 sind bis zu 16 Inverter möglich.

**Comment by teletapi** [comment]
Ja hol dir einen ESP32 dann gehn 16 WR

**Comment by walter2323** [comment]
Da liegt also das Problem!
Vielen Dank euch für die schnelle Lösung!!!!

**Comment by walter2323** [comment]
Ich habe auf einen ESP32 gewechselt. Unfassbar wie schnell alles funktioniert! Ich sage Nochmals Danke!!!
![IMG_20231220_142117](https://github.com/lumapu/ahoy/assets/153988127/3e6c0e47-08a4-4816-8431-bbbbbb68a513)

**Comment by dtuuser** [comment]
Was ist denn das für eine Display Anzeige mit der Kurve?

**Comment by walter2323** [comment]
> Was ist denn das für eine Display Anzeige mit der Kurve?

Lediglich die neueste Version von OpenDTU...

**Comment by dtuuser** [comment]
Danke für die Rückmeldung. Dachte es wär ein verstecktes Feature von Ahoy
