### ISSUE TITLE
Serialnumber / Seriennummer nicht eintragbar

### ISSUE THREAD

**Issue by WeWantCode** [lumapu/ahoy#1278]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.56

### Github Hash

3b4365a697d6dba1b8f50950405dc9a26df2b8db

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Currently in the beginning and still setting up my DTU Ahoy. 

Ich hatte zuerst die 0.7.36 drauf, allerdings wohl etwas auf meinem CMT Board falsch verbunden, da mir aus der Doku nicht klar war wo die zwei anderen Pins hin müssen und das IRQ = GPIO3 ist. 
Nach dem Upgrade auf 0.7.56 kann ich alle Ports einstellen und jetzt ist laut Ansicht mein CMT "aktiv" (siehe Screenshot)

![grafik](https://github.com/lumapu/ahoy/assets/153938596/d9263b77-93d0-4c42-a713-ffb0858ed601)

Ich habe einen STM32, mit SH1106 OLED angeschlossen und ein CMT2300A. Am CMT und am STM32 hängen je ein Kondensator.
Das Display funktioniert. Das CMT bisher noch nicht.

### Debug Serial Log output

```shell
Unklar wo ich das finden kann, liefer ich nach, wenn ich mehr Infos kriege wie ich da dran komm.
```

### Error description

System Config meldet das Inverter-Serienummer nicht erlaubt ist. 

Mein Inverter hat Seriennummer 141 xxx xxx xxx. 
In der System Config wird das Feld der Inverternummer rot gefärbt. Wenn ich mit der Maus drüber geh kommt eine Hilfsmeldung "Bitte wählen Sie einen Wert, der nicht größer ist als 138999999999."

Kann ich eine neuere Version verwenden, damit meine Seriennummer geht? Kann ich bei den Settings was ändern, damit meine Seriennummer erlaubt wird?
Per Handy kann ich mich direkt auf die DTU des Inverters verbinden. Dort sehe ich auch das der Inverter aktiv ist und Leistung liefert.

**Comment by WeWantCode** [comment]
Update : 
Mit 0.8.22 lässt sich die Seriennummer wohl eintragen. Kommunikation kommt aber trotzdem nicht zustande. Da mein Modul aber noch nie gefunkt hat würde ich vermuten das der Fehler irgendwo in meinem Aufbau liegt. 

Frage zum WLAN: 
Trage ich dort mein WLAN ein, das ich in der Interverter-DTU eingetragen habe (mein Haus-WLAN) oder trage ich dort das WLAN der Inverter DTU ein?

**Comment by knickohr** [comment]
Schreib mal ein bißchen was zu dem Inverter. Die ersten 6 Stellen der Seriennummer wären hilfreich, die geben das Modell an.

Das ist das WLAN von Deinem Heimnetz. So wie sich das in Deiner Beschreibung oben liest, hast Du ein WLAN-Modell des Inverters, erkennbar an dem W hinter der Zahl. Diese HMS-xxxW-2T werden (noch) nicht unterstützt 😉

Wenn Du eine zweite Hoymiles DTU laufen hast, dann blockiert diese die Kommunikation mit Ahoy. Also entweder Hoymiles DTU oder Ahoy DTU, beides geht (meistens) nicht gut !

**Comment by WeWantCode** [comment]
Alles klar, danke für die Hilfe. 

Seriennummer, erste 6 Stellen: 141292xx xxxx. Ja, ich habe eine **Wifi-Version** des Wechselrichters. Einen HMS-800**W**-2T

Die DTU des Inverters ist im Hoymiles Inverter verbaut. Wie man die abschalten kann ist mir nicht klar. Aber ich denke dann wäre der Wechselrichter auch nicht mehr per App erreichbar. Die DTU im Wechselrichter spannt ein WLAN auf und kann dort angesprochen werden. Weshalb diese die Kommunikation mit der Ahoy stören sollte versteh ich grad nicht. Ich dachte die Ahoy snifft mit was der Wechselrichter sendet?

Kann ich irgendwie helfen, wie die HMS-xxxW-2T unterstützt werden können. Bin selber Programmierer, wenn auch nicht Hardwarenah normalerweise, aber wenn mir jemand sagt was hilft oder welchen Trace man sich schnappen kann mach ich gern mit.

**Comment by WeWantCode** [comment]
Ok, aus der Ahoy Website war mir nicht klar das die HMS-xxxx**W**-2T Modelle anders sind als die HMS-xxxx-2T Serie. Hab jetzt vermutlich die falsche Hardware gekauft, finde ich schade. Bitte ergänzen auf der Ahoy Site wenn möglich, damit der nächste nicht nochmal in die Falle tappt!

Für alle die mehr wissen will, kann man vermutlich hier: https://github.com/lumapu/ahoy/issues/1189 weiterlesen.

**Comment by knickohr** [comment]
Nicht HMS-2T, die funktionieren 😉

HMS-**W**-2T

**Comment by DanielR92** [comment]
The comment is already written on the main site: 
⚠️ Warning: HMS-XXXXW-2T WiFi inverters are not supported. They have a 'W' in their name and a DTU serial number on its sticker

Can be closed here.

**Comment by stefan123t** [comment]
Wir sollten die Eintragung von HMS-xxx**W** (WiFi Modelle mit built-in DTU-BI) nach Möglichkeit mit einem Warnhinweis versehen.

Die wöchentliche DTU und Inverter Serialnumber sind übrigens identisch:

DTU-SN: 4143 923 12345
Mikro-SN: 1412 923 12345

**Comment by Loetnase** [comment]
@stefan123t 
Das finde ich super von dir.
Vieleicht kann der Fehler von vorne herein vermieden werden.
Danke

**Comment by lumapu** [comment]
> Wir sollten die Eintragung von HMS-xxx**W** (WiFi Modelle mit built-in DTU-BI) nach Möglichkeit mit einem Warnhinweis versehen.
> 
> Die wöchentliche DTU und Inverter Serialnumber sind übrigens identisch:
> 
> DTU-SN: 4143 923 12345 Mikro-SN: 1412 923 12345

hast du eine Liste der Wifi-Modell Seriennnummern?

**Comment by stefan123t** [comment]
@lumapu nein leider noch nicht!
Aber wir haben bei OpenDTU mal angefangen mit einer Liste, aber ich habe bisher nur HMS-800W-2T nach dem o.g. Schema.

DTU-SN: 4143 923 12345
Mikro-SN: 1412 923 12345

* https://github.com/tbnobody/OpenDTU/issues/714
* https://github.com/tbnobody/OpenDTU/issues/1324
* https://github.com/tbnobody/OpenDTU/issues/2061

* https://github.com/tbnobody/OpenDTU/issues/519
  hier geht es zwar speziell um HERF Inverter, die verwenden das für OEMs gedachte `sn92long()` Serial Number Format mit einem anderen Charset:
  * https://github.com/tbnobody/OpenDTU/issues/1751

**Comment by stefan123t** [comment]
> @stefan123t Das finde ich super von dir. Vieleicht kann der Fehler von vorne herein vermieden werden. Danke

War doch Deine Idee :stuck_out_tongue_winking_eye: wenn mich nicht alles täuscht!

Wir müssten mal sehen ob die Serial IDs der HMS-xxx**W** wirklich unterschiedlich sind von den HMS-XXX ohne Built-In WiFi DTUBI ?

Könnte man die alte Tabelle mal mit den HMS-800 und HMT-800 Modell Nummern aktualisieren ?
Ich habe weder die HMS/HMT-Modelle noch ein HMS-xxx**W** Modell.

Seriennummern
https://github.com/lumapu/ahoy/blob/5ebfe5a8fb5bcc833b64a0dd083686031808cec8/doc/hoymiles-format-description.md#seriennummern
