### ISSUE TITLE
Active Power Limit (0)

### ISSUE THREAD

**Issue by XTeslaX** [lumapu/ahoy#128]
Ich habe einen HM-600 im Einsatz und ein Update auf 0.5.2 gemacht. Jetzt produziert der HM-600 nicht mehr. Bei Active Power Level ist 0 eingetragen. Änderungen auf 600 werden nicht gespeichert. Ein Neustart hat nichts geholfen.

**Comment by mslookup** [comment]
Schau mal in den Issue https://github.com/grindylow/ahoy/issues/125, Lösung ist schon im Pull request https://github.com/grindylow/ahoy/pull/127 enthalten. Entweder selbst im Code ändern oder den Merge des Pull requests abwarten.

**Comment by stefan123t** [comment]
Vielleicht sollten wir noch eine Checkbox dazu machen oder bei PowerLimit 0 gar nichts senden ? Die Original Hoymiles unterstützt mW auch nur 2-100% der max Leistung.

**Comment by lumapu** [comment]
@XTeslaX bitte die neueste Version 0.5.5 Git-SHA g6276957 verwenden
