### ISSUE TITLE
Yield Correction Nachkommastellen "rotes Fenster"

### ISSUE THREAD

**Issue by Dirk-Ahoy** [lumapu/ahoy#1280]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.27

### Github Hash

d31f392

### Build & Flash Method

was already installed

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Yield Correction mit Nachkommastelle macht einen roten Kasten, speichern geht  zwar - aber ob es genau genommen wird kann ich nicht sagen ;)

**Comment by knickohr** [comment]
Der rote Kasten sagt das etwas nicht stimmt. Eben die Nachkommastellen 😉

Ich weiß nicht, ob es prinzipiell ohne Nachkommastellen sein muß, oder ob nur . und , getauscht werden müssen ? 🤔

Nachtrag :
![IMG_1500](https://github.com/lumapu/ahoy/assets/63048210/b9e2d159-49c5-4786-a0ea-ff2f9089edbb)

. und , ist es offenbar 😅

**Comment by lumapu** [comment]
ist im Release `0.8.36` schon gefixt, daher mache ich hier gleich zu 😉
