### ISSUE TITLE
0.8.28 breaks mqtt data

### ISSUE THREAD

**Issue by jogybaer0815** [lumapu/ahoy#1288]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.28

### Github Hash

5a52677

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

HMS1600

### Error description

0.8.28 stoppt den mqtt Datenstrom nach kurzer Zeit - Daten werden nach kurzer Zeit (0-5min) nicht mehr aktualisiert.
0.8.27 läuft problemlos. 
Mehrfach umgeflasht und reproduzierbar

**Comment by knickohr** [comment]
Ist bekannt und wird schon gefixed.
