### ISSUE TITLE
Feature Request: Verbesserungsvorschlag: Art des Setzens des PowerLimits

### ISSUE THREAD

**Issue by mslookup** [lumapu/ahoy#129]
Einen Vorschlag zur Verbesserung der PowerLimit Funktion:
- Standardmäßig die PowerLimit Einstellung in der GUI auf -1, und damit auf Unbegrenzt, stellen.

Vorher sollte jedoch noch Bug https://github.com/grindylow/ahoy/issues/130 gefixt werden.

Ich bin heute früh, wie viele andere (https://github.com/grindylow/ahoy/issues/128) auch, erstmal mit https://github.com/grindylow/ahoy/issues/125 an der 0W Grenze gehangen, was mich zu diesem Verbesserungsvorschlag führt.
Nach einem Update von Ahoy steht der Wert ja standardmäßig auf 0, was 0 Watt bedeutet. Eventuell ist es möglich das ganze so anzupassen, dass der Wert standardmäßig auf -1, und damit unbegrenzt, steht.

Danke euch, ihr seid spitze!🥇

**Comment by lumapu** [comment]
man kann doch auch einfach die 0 erkennen und dann nicht begrenzen, wenn man den WR ausschalten will gibt es doch noch andere CMDs . Dann wäre der Default nach dem Reset auch gleich mit behoben.

**Comment by mslookup** [comment]
Auch möglich :)

**Comment by stefan123t** [comment]
:+1: 
* "0" dürfte eigentlich kein valides PowerLimit sein. Laut Hoymiles ist ActivePowerLimit auch nur zwischen 2-100% definiert. 
  D.h. "0" dürfte keinen Wert von 0 als ActivePowerLimit setzen und sollte m.E. somit ignoriert werden.
  In der DTU-Pro wird ab 30W pro MPPT geregelt und dann m.W. auch nur in 30W Schritten. (Vielleicht ist das aber auch die AntiReflux Regelung für die MI-Wechselrichter, dort ist die Einschaltschwelle nochmal höher als bei den aktuellen HM-Invertern).
  + Zusätzlich sollte sowohl im GUI als auch per MQTT/JSON Kommando ein Flag mitgegeben werden wenn es permanent gespeichert werden soll. Der Default sollte remanent / temporär sein.
  + Alternativ könnte er bei "0" per MQTT ggf. auch das Shutdown Kommando senden.
* "-1" sehe ich wie @mslookup auch als unlimited an, vielleicht sollte dann das ActivePowerLimit auf das maximal Zulässige des WR gesetzt werden ?

**Comment by lumapu** [comment]
@mslookup bitte die neueste Version 0.5.5 Git-SHA g6276957 verwenden
