### ISSUE TITLE
parallel zu Hoymiles DTU?

### ISSUE THREAD

**Issue by drezino** [lumapu/ahoy#1291]
## Hardware
  * [ ] ESP8266
  *  ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
*  external antenna (SMA)

### Power Stabilization:
*   100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
*  AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

habe hier 5 HM-800 und bekomme bei allen die Meldung "Inverter ... is not yet available", im Terminal wird aber connected angezeigt.

Mein Bruder verwendet die originale Hoymiles DTU zum auslesen. Da ich aber plane über MQTT und ohne Cloud die Daten zu erfassen habe ich mir eine Ahoy DTU angeschafft. Die Wechselrichter funken auf alle Fälle Daten und Seriennummern stimmen auch. Der Empfang der Daten mit mehreren unterschiedlichen DTUs sollte eigentlich möglich sein, oder spricht etwas dagegen?

**Comment by Joh49** [comment]
ich betreibe 2 HM1500 an einer Original DTU und greife mit 2 Ahoy DTU's mit Display zusätzlich darauf zu. Das geht gut, vielleicht etwas mehr Alarme als üblich jedoch der Leistungswert kommt alle 2 Minuten und eine non persistente Leistungsreduzierung wird schnell umgesetzt. Softwarestand 7.59. Bin sehr zufrieden.
