### ISSUE TITLE
Limiter - Fehler bei Leistunswerte

### ISSUE THREAD

**Issue by Stef293** [lumapu/ahoy#1292]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.7.36
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [x] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hallo Zusammen,

ich habe einen HM-400 an einem 25,6 V / 100 A Akku für eine Nachteinspeisung angeschlossen, diese möchte ich dynamisch mit der Limitbegrenzung steuern, hierbei tritt ein Fehler im WR auf. 
Ich kann den Limiter bis 50% = 200 W einstellen, diese Werte sind stabil und entsprechen den Vorgaben. Wenn ich Werte hierrüber hinaus > 200W/50% (egal als % oder W) angebe zeigt der WR den korrekten Limit Wert in der Liveansicht an, selbst die Einspeisewerte in der Liveansicht stimmen. Aber die Einspeisesteckdose geht wiederholbar auf viel höhere Werte.
Dieses Problem scheint weiter unabhängig von der verwendeten Ahoy Firmware Version zu bestehen. Getestet mit 0.7.36 und 0.8.28.  

Bsp.: 
51% = Soll 205W ist 220W
55% = Soll 215W ist 265W
60% = Soll 240W ist 354W

Besteht hier ein Zusammenhang mit dem Akku?

**Comment by Ollipop030** [comment]
So was Ähnliches gab es hier schon einmal, siehe #1168.

Aber kein Plan wo da der Fehler liegt.
