### ISSUE TITLE
Bug: Setzen des PowerLimits auf -1 (unbegrenzt) funktioniert nicht

### ISSUE THREAD

**Issue by mslookup** [lumapu/ahoy#130]
Hallo zusammen,
leider funktioniert das Setzen des PowerLimits auf -1 (unbegrenzt) noch nicht fehlerfrei bei mir (ggf. Bug bei allen?).

Sobald ich den Wert auf -1 setze und speichere, laufen die WR auf "Standgas":
![grafik](https://user-images.githubusercontent.com/66677275/183295716-d5528964-be0b-4aa4-adbb-359e01a6aeab.png)

Ändere ich den Wert auf z.B. 3000, gehen beide wieder los...
![grafik](https://user-images.githubusercontent.com/66677275/183295480-fe1292ed-578c-425c-b055-03f55cd81d0f.png)

Scheint, als wäre da irgendwo noch ein Bug drinnen.
VG mslookup

**Comment by lumapu** [comment]
sieht so aus als gäbe es ein maximales Limit, evtl. muss man das auf z.B. 3000W nach oben begrenzen. -1 wird bei einem unsigned int16 zum Maximalwert 65535

**Comment by ghost** [comment]
Mein HM600 läßt sich ohne Probleme auf 800 W einstellen - mehr habe ich nicht getestet, weil sinnlos.

Noch eine Anmerkung: Ich betreibe den HM600 z . Z mit einem Modul. Dabei habe ich- mit einem 340 W peak Modul  - 320 W Leistung erreicht. Wenn ich unter 0.5.2 400 W Limit einstelle, ist das Maximum pro Modul 200 W.

**Comment by mslookup** [comment]
@Solateur: Es geht mir mit der -1 weniger darum, die Drosselung auf den maximal möglichen Wert zu stellen, sondern die PowerLimit Funktion komplett zu deaktivieren. Meines Wissens nach macht das in der Config des Hoymiles einen Unterschied…

**Comment by ghost** [comment]
@mslookup: Meine Anmerkung bezog sich auf die Vermutung von lumapu: "sieht so aus als gäbe es ein maximales Limit, evtl. muss man das auf z.B. 3000W nach oben begrenzen."

**Comment by mslookup** [comment]
@Solateur :D achso - ja jetzt wo du's sagst

**Comment by lumapu** [comment]
@mslookup bitte die neueste Version 0.5.5 Git-SHA g6276957 verwenden
