### ISSUE TITLE
Version 8.30      added info if grid profile was not found 

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1300]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

8.31

### Github Hash

????

### Build & Flash Method

was already installed

### Setup

Im setup Read Grid Profile abgewählt

### Error description

ich habe in den Settings Read Grid Profile abgewählt und erhalte trotzdem die Meldung:   Grid Profile for inverter HM600
Unknown Profile  (Etwas verwirrend...)

**Comment by knickohr** [comment]
Vielleicht hat die DTU es noch gar nicht gelesen ?  Es dauert eine Weile bis es ausgelesen wird.

**Comment by Gubi2023** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/142897856/1d3db496-1ab1-4082-ac2d-3b1b75241990)
ich meine, der "Show" button sollte gar nicht angezeigt werden, wenn in den Settings Read Grid Profile abgewählt wird.

**Comment by Gubi2023** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/142897856/51724f41-8b47-49ca-a194-c82f7ae12141)
auch nicht schlecht, die Lösung.
Respekt, wie ihr immer so schnell reagiert!
