### ISSUE TITLE
[Bug] Release ZIP ahoy_v0.8.34 is empty

### ISSUE THREAD

**Issue by bentolor** [lumapu/ahoy#1301]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0-7-36

### Github Hash

ba218ed

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

not relevant

### Error description

Thanks for the new release.

Nota bene: The release ZIP at https://github.com/lumapu/ahoy/releases/tag/ahoy_v0.8.34 only contains the readme, but not release artefact.

**Comment by lumapu** [comment]
oh, thank you for reporting

**Comment by lumapu** [comment]
fixed manually
