### ISSUE TITLE
ESP32 8.34 bin lässt sich bei mir nicht updaten

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#1302]
Die 
231229_ahoy_0.8.34_3178325_esp32.bin
aus 
https://fw.ahoydtu.de/fw/release/ahoy_v0.8.34/ESP32/
lässt sich bei mir nicht einspielen. 
Nach dem Reboot ist die alte Version noch drauf. Habe wohl noch die 31 drauf.

**Comment by Dirk-Ahoy** [comment]
mach mal einen reboot über die Weboberfläche und wenn sie dann noch nicht da ist noch mal probieren - hier und da hängt das update schon mal.

**Comment by knickohr** [comment]
Updaten, wenn success kommt, sofort den Stecker ziehen. Aber nicht vor dem success !

Und wenn das auch nicht hilft, in den AP Booten und da das Update machen.

**Comment by dtuuser** [comment]
Hammer..... hat geklappt.  
Reboot über Weboberfläche und dann die gleiche bin nochmal geupdatet.

Danke für den Tipp und die super Programmierarbeit
