### ISSUE TITLE
[Bug]  Wifi Ch 13 problem:    0.8.36 läuft nicht auf ESP8266, 0.8.34 schon / 0.8.36 won't work on ESP8266, 0.8.34 does

### ISSUE THREAD

**Issue by cptechnik** [lumapu/ahoy#1307]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.36

### Github Hash

ba218ed

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Set 
SSID,-Wifi password, inverter sn, 

### Error description

Online flash tool installiert 0.7.36
von 0.7.36 oder von 0.8.34 aus (Aktualisierung auf 0.8.34 kein Problem)
aktualisiere ich übers WebIF auf 0.8.36 oder 0.8.38 
Nach dem boot, zeigt Daten im Display an, WebIF ist aber nicht oder nur kurz zu erreichen, bricht Datenübertragung ab, und ist dann nicht mehr zu erreichen.
Serielle Konsole zeigt immer
`I: com loop duration: 1503ms`
Es fühlt sich an, als wäre er mit was beschäftigt, oder lahmt...
Flashen mit dem Online-Flash-Tool auf 0.7.36 klappt immer wieder

--

flash with online-tool to 0.7.36
(evt. update to 0.8.34 - no problem)
update via webif to 0.8.36 or 0.8.38 completet with reboot,
after that, displays run, get ip from dhcp, but webif not reachable or only very short with connection break, so webif not usuable... other services not tested. - feels like sleeping or stressed...
flashing with online tool to 0.7.36 always possible

**Comment by cptechnik** [comment]
ok one step ahead...
ich habe die WLAN Einstellungen weggelassen und er läuft stabil... 
(im AP Modus, sofern man das ohne Sonne sagen kann)
... ergo... WLAN ...
aber nicht nur dass er die Verbindung verliert, sondern er startet auch schonmal beim Verbindungsversuch neu...
in der 0.8.36 vermisse ich aber die Einstellung zur Power (WLAN-Power?)

**Comment by cptechnik** [comment]
ähhhh... ch13?

... ich habe mal mein WLAN auf Kanal 9 geändert,.... war vorher auf Kanal 13... könnte das ein Problem sein... in der neuen Firmware (Generation)?


I changed my wifi channel from 13 to 9 and i have no problems... until now... 
check-check... waiting for errors...

**Comment by Jumperm** [comment]
Ähnliches Problem bei meinem ESP8266. Habe Release und aktuelle Dev 0.8.38 frisch geflashed.
Bin auf 0.8.30 zurück und die läuft gerade.
Im Log stand etwas von:
I: comm ...

**Comment by cptechnik** [comment]
> Ähnliches Problem bei meinem ESP8266.

Also auch das mit Kanal 13, lässt sich das mit dem Verstellen im Router beheben?

...also ich kann nämlich sagen, 
durch das verstellen des WLAN Kanals im Router/Accesspoint funktioniert die Ahoy wie sie soll...

**Comment by Jumperm** [comment]
In meinem Mesh ist auf dem nahem Accessppoint Kanal 13 aktiv. Scheinbar habe ich dadurch Übertragungsfehler auf der DTU durch ihre Trägheit. Bei Gelegenheit muss ich mal den Kanal Manuel ändern und die aktuelle FW aufspielen.

**Comment by Jumperm** [comment]
> > Ähnliches Problem bei meinem ESP8266.
> 
> Also auch das mit Kanal 13, lässt sich das mit dem Verstellen im Router beheben?
> 
> ...also ich kann nämlich sagen, durch das verstellen des WLAN Kanals im Router/Accesspoint funktioniert die Ahoy wie sie soll...

Sehr spannend.

Ich habe den Kanal 1 fixiert und nun läuft die DTU butterweich...

Ich rate mal ins Blaue und behaupte, dass eventuell etwas in der WIFI Bibliothek des 8266 defekt ist, weil die ESP32er damit wohl kein Problem haben.

**Comment by Jumperm** [comment]
Scheint doch ein Problem des ESP zu sein. Nach einem Kaltstart schlägt die Verbindung fehl.
https://olimex.wordpress.com/2021/12/10/avoid-wifi-channel-12-13-14-when-working-with-esp-devices/
Wenn der 8266 sich erstmalig verbunden hat geht es. Dann kann er auch wochenlang durchlaufen.
