### ISSUE TITLE
Sunrise & Sunset

### ISSUE THREAD

**Issue by zappoXX** [lumapu/ahoy#1308]
Moin,

habe mich heute einmal mit der Option "Sunrise & Sunset" beschäftigt. Ich kann dort den Offset (pre sunrise, post sunset) einstellen, also vor Sonnenaufgang, nach Sonnenuntergang, allerdings nur zusammen. Nun ist es aber so das es bei Sonnenaufgang noch ziemlich düster ist, die Radio Statistics schon ordentlich "No answer" zählen und dadurch die Statistik verfälscht ist. Besser wäre es die beiden Punkte "pre sunrise, post sunset separat zu behandeln, damit man nur z.B. 20 min 
nach Sonnenaufgang einstellen kann.

**Comment by Andy-Op** [comment]
Mal Danke dass das hier Thema ist. Ich suche das Leistungsmerkmale in Verbindung mit einer PIN-Ausgabe am ESP um eine Nachteinspeisung zu steuern. Ich würde dann von OpenDTU hier her wechseln. Hat sich da schon jemand dran versucht?

![Relaissteuerung_Einspeisung_Balkonkraftwerk](https://github.com/lumapu/ahoy/assets/134189338/cf5e88f2-35d1-4d2d-8d80-cb6b99cbe810)

**Comment by DanielR92** [comment]
Guten Morgen zusammen,

@zappoXX hmm da könnte ich dir Recht geben. Zwecks Statistik kannst du jedoch (je nachdem was du einsetzt) selbst dafür sorgen das die Daten "richtig" aufgenommen werden...

@Andy-Op Verstehe ich dich richtig, du möchtest ein Pin am Ahoy so Einstellen das sobald "produziert" wird, etwas am Ausgang High/Low schaltet?

**Comment by Andy-Op** [comment]
@DanielR92 ich möchte tagsüber einen 100 Ah 9S LiFePO4 laden (Tag, Zeit zwischen Sunrise und Sunset low) und Nachts als Grundlastkompensation einspeisen (Nacht, Zeit zwischen Sunset und Sunrise high). Wenn ihr Sunrise und Sunset schon habt muss es doch ein Leichtes sein den Zeitabschnitt zu bestimmen, alle Minute zu prüfen, ein Flag zu setzen und an einem PIN des ESP auszugeben.

**Comment by knickohr** [comment]
Ihr könnt solche Wünsche in die Wunschliste #1199 eintragen.

Bezüglich unterschiedlichen Settings wäre es relativ einfach das zu implementieren.

Bezüglich Ein-/Ausgabe über Pins halten wir uns etwas zurück. Denn ansonsten wurden wir da eine Lawine ins Rollen bringen. Außerdem ist es beim ESP8266 eh schon „aus die Maus“.  Ja, beim ESP32 gibt es genügend.

**Comment by knickohr** [comment]
Na schaut mal an !  So schnell kann’s gehen 😉

**Comment by Dirk-Ahoy** [comment]
klappt aber noch nicht auch nach speichern kommt unter System Fehlermeldung "Invalid Date"   bei Start/Stop. - siehe Screenshot im Discord

**Comment by Ghost30121978** [comment]
Hallo
Hier ein Screenshot 
![Screenshot_2024-01-02-09-32-14-265_com mi globalbrowser](https://github.com/lumapu/ahoy/assets/127692631/3c9cbb55-b8ac-41a0-90b7-a30ee89b9c09)

**Comment by roku133** [comment]
Es ist ein reines Anzeigeproblem auf der Weboberfläche.
MQTT-Parameter comm_start und comm_stop bzw. REST-API ts_offsSr und ts_offsSs sind korrekt.

**Comment by knickohr** [comment]
Gut zu wissen 👍

**Comment by zappoXX** [comment]
Super wie schnell neue Features eingefügt werden... wenn jetzt noch bei Sunrise & Sunset für jeden Zeitpunkt, also Sonnenaufgang und Sonnenuntergang positiver wie negativer Offset, z.B. Sonnenaufgang 08:38 Uhr +20 min. (um 08:38 Uhr ist es nämlich noch nicht wirklich hell und der Wechselrichter sendet auch noch keine Daten, bei mir heute Morgen um 08:59 Uhr) dann ist diese Funktion perfekt.

**Comment by lumapu** [comment]
ok, leider ist grad die `0.8.40` draußen 😉 - in der nächsten Verison

**Comment by roku133** [comment]
Anzeige funktioniert jetzt in v0.8.41 👍

**Comment by knickohr** [comment]
Heute fliegen die Versionen wieder 😂

**Comment by Andy-Op** [comment]
Macht mir doch bitte noch die Tag/Nacht Pin-Ausgabe. Dann teste ich ob das so zu gebrauchen ist.

**Comment by knickohr** [comment]
Eine LED die den Status von comm_disabled anzeigt 😉

**Comment by lumapu** [comment]
@knickohr das ist eine geniale Idee, wie es dann doch wieder für alle passt 😉

**Comment by knickohr** [comment]
Das ist doch genau das was @Andy-Op will. Machen wir’s doch so wie bei den anderen LEDs 😉

Er kann sich dann sogar den Pin und ob Active high/low aussuchen.

**Comment by zappoXX** [comment]
Die Offset Funktion funktioniert einwandfrei, ich habe 15 min. nach Sonnenaufgang eingestellt und genau dann startet auch die Kommunikation. Allerdings... unter System/Kommunikation Start wird alles richtig angezeigt, in der AhoyDTU Übersicht ist die Zeitangabe aber falsch...
![001](https://github.com/lumapu/ahoy/assets/151444544/5fe984b3-b621-4cfe-8e7f-e1139a89576d)



![002](https://github.com/lumapu/ahoy/assets/151444544/adf22e13-17e0-467d-b8e1-bacdfe6b01e8)

**Comment by lumapu** [comment]
wird in der nächsten Version behoben sein, danke für den Hinweis

**Comment by knickohr** [comment]
Ahhh verdammt, Morgens muß man negative Werte eintragen wenn die Kommunikation schon vor Sonnenaufgang starten soll 🤪 Ist ja auch logisch 🫣

Der oben beschriebene Bug mit der falschen Anzeige ist aber nur ein Anzeigeproblem ?

**Comment by lumapu** [comment]
ja genau, wird heute noch behoben 😊
