### ISSUE TITLE
Webseite / WebInstaller: Error 404 

### ISSUE THREAD

**Issue by cptechnik** [lumapu/ahoy#1320]
File not found
Image nicht gefunden wenn man flashen will...

![IMG_20240102_204811192](https://github.com/lumapu/ahoy/assets/5541222/6562734d-a31c-4ec6-b7ab-8056ff65fba9)

**Comment by Sozpeed** [comment]
Geht bei mir seit drei Tagen auch nicht, selbe Fehlermeldung.

**Comment by stefan123t** [comment]
Die ESP8266 Version 0.8.36 wurde m.W. vom git Action Build Prozess nicht erfolgreich gebaut.
Ein erneutes Bauen der alten Version ist so weit ich weiß auch nicht automatisch möglich.
Könnt Ihr nicht einfach eine neuere Version installieren ?

@lumapu ist die 0.8.36 die aktuelle stable / master Release Version ?

**Comment by Sozpeed** [comment]
Hallo Stefan,

vielen Dank für deine Informationen, da wäre ich in 100 Jahren nicht drauf gekommen. 

Da ich wenig Ahnung habe, hat alles etwas länger gedauert. Aber es hat funktioniert.

Vielen herzlichen Dank.

Mit freundlichen Grüßen

Lars Morgenroth

 

Von: stefan123t ***@***.***> 
Gesendet: Donnerstag, 4. Januar 2024 15:29
An: lumapu/ahoy ***@***.***>
Cc: Sozpeed ***@***.***>; Comment ***@***.***>
Betreff: Re: [lumapu/ahoy] Webseite / WebInstaller: Error 404 (Issue #1320)

 

Die ESP8266 Version 0.8.36 wurde m.W. vom git Action Build Prozess nicht erfolgreich gebaut.
Ein erneutes Bauen der alten Version ist so weit ich weiß auch nicht automatisch möglich.
Könnt Ihr nicht einfach eine neuere Version installieren ?

@lumapu <https://github.com/lumapu>  ist die 0.8.36 die aktuelle stable / master Release Version ?

**Comment by lumapu** [comment]
habe es soeben gefixt, es hat ein `.bin` im `manifest.json` gefehlt.

**Comment by cptechnik** [comment]
danke,danke,DANKE!


...PS: er hat mit 8.36 immer noch Probleme mit Kanal 13, aber das liebe Kinder, ist ein anderes Problem...

**Comment by cptechnik** [comment]
...stimmt... also falls niemand was dagegen hat...
