### ISSUE TITLE
Sunset&Sunrise als Schaltausgang am ESP32

### ISSUE THREAD

**Issue by Andy-Op** [lumapu/ahoy#1323]
erst mal vielen Dank, das ihr euch mit der 0.8.42 dem Thema angenommen habt. Ich bin neu bei ahoyDTU und mein Schwerpunkt ist im analogen Bereich. Daher bitte ich Rücksicht walten zu lassen, wenn mir die Dinge rund um den ESP32 nicht so vertraut sind. Bauen will ich bzgl. einer Nachteinspeisung am Balkonkraftwerk das hier:

![Relaissteuerung_Einspeisung_Balkonkraftwerk](https://github.com/lumapu/ahoy/assets/134189338/95fa658f-2976-495c-bef8-be17fda121a7)

Ich hatte hier noch einen DTU-Bausatz V3.0 aus folgender Quelle rumliegen:

https://wechselrichter-versand.de/Informationen/Anleitung-openDTU-HM/

Die Platine bietet Synergien zum Einbau eines Optokopplers. Herfür habe ich den 230 Volt Zweig umfunktioniert. Mit dem 1mm Bohrer 3 Löcher für den IC-Sockel gebohrt. Masse liegt gerade neben an. Das passt. Mit einem PC817 bin ich bei einem Primärstrom von 20mA, Das ergibt einen Vorwiderstand von (3,3V-1,3V)/0.02A = 100 Ohm . 20mA sind wohl an der Grenze dessen was der ESP32 dauerhaft an Output erlaubt. Low-Power Optokoppler wie TLP621−4 sind Pin-kompatibel. Der Vorwiderstand ist dabei auf 180 Ohm zu vergrößern. Hierbei habe ich unterstellt, dass ich Nachts ein high von 3,3 Volt bekomme.

![Integration_Optokoppler_1](https://github.com/lumapu/ahoy/assets/134189338/a47b2f6b-729e-4f2e-9a07-054bdf7cf6b4)
![Integration_Optokoppler_2](https://github.com/lumapu/ahoy/assets/134189338/1355311f-d838-4963-99c0-52c597588870)

Gibt es einen 3,3 Volt high? Wo soll dann denn der 100 Ohm hin?

**Comment by mtet2** [comment]
z.B. GPIO 13 oder 14 siehe Bild. Und dann den Pin im Setup auch aktivieren.
Kleiner Tip noch: "Die Lötstellen der IC-Fassung sehen überwiegend wie kalte Lötstellen aus".
Die würde ich nachlöten.
![GPIO_13_14](https://github.com/lumapu/ahoy/assets/120575424/df610bec-0543-4730-b17a-fbf0631695ac)

**Comment by Andy-Op** [comment]
Moin, den GPIO14 dann wohl weniger:
![GPIIO_PIN_ESP32](https://github.com/lumapu/ahoy/assets/134189338/aa0a9e27-2b88-4eff-a337-0ddffc5d1949)
P.S.: Die Lötstellen sind verbleit und top. Da täuscht das Bild.

**Comment by Andy-Op** [comment]
Hab die 0.8.42 drauf, Geo-Daten sind eingetragen. Wo genau erfolgt die GPIO Zuweisung/Aktivierung?

**Comment by mtet2** [comment]
Hier ein Beispiel für einen ESP8266
![Screenshot 2024-01-04 at 19-32-33 Setup](https://github.com/lumapu/ahoy/assets/120575424/0e689451-d830-48c6-ac53-4f2414a4108e)

**Comment by Andy-Op** [comment]
Ich vermute dann mal System Config > Status Led > Night time

**Comment by Andy-Op** [comment]
Der Schaltausgang reagiert. Es kommen 2,83 Volt als high raus, beim Booten bleibt GPIO13 low. Bei meinem 100 Ohm sind es nun ~16mA die den PC817 aufsteuern. Für meine Verwendung ausreichend. Jetzt hatte ich irgendwo gelesen, dass, wenn ich die Geodaten eingegeben habe, ich auch die Sunset und Sunrise Zeiten angezeigt bekommen. Diese Zeiten habe ich noch nicht gefunden.

![Integration_Optokoppler_3](https://github.com/lumapu/ahoy/assets/134189338/0cdec5c3-def1-471e-8dc0-2eade9b096fa)

**Comment by mtet2** [comment]
Na dann weiter suchen ;-)
![Screenshot 2024-01-05 at 11-33-59 System](https://github.com/lumapu/ahoy/assets/120575424/874e3b44-09f4-46a7-8a75-a93c457eedfb)

**Comment by knickohr** [comment]
Also sehe ich das richtig ?  Bei euch funktioniert die LED ?  Bei meinem Fusion-Board leider irgendwie nicht, obwohl wenn ich die LED an einen anderen Schaltausgang einer anderen Funktion lege tut es. Nur eben beim dem neuen Night Time nicht 😞 Scheint wohl ein Problem vom Fusion-Board zu sein.

**Comment by mtet2** [comment]
Ja, bei mir funktioniert die LED am D2.
Am ESP8266 habe ich den D2 GPIO4 genommen, weil er bei mir frei war und er auch für Relaisbeschaltung geeignet sein soll. Die "LED polarity" auf  high active gesetzt, damit der Optokoppler nachts einschaltet.  ;-) 
Das statische Schalten des Optokopplers funktioniert auch noch mit 10 mA IF Strom sicher, so das man auch mit einem 200 Ohm Vorwiderstand arbeiten kann.

**Comment by knickohr** [comment]
Ja, es funktioniert 🫣

Es funktioniert nur genau anders herum wie erhofft. Also wenn die LED (aktiv high) an ist, dann ist es Nacht. Kein Problem, man muß es nur wissen 😂

**Comment by Andy-Op** [comment]
Ich werde an meiner nachgeschalteten Treiberstufe C1 auf 470uF vergrößern. Dann kann ich auch einen Reboot überbrücken. Habt ihr sonst noch irgendwelche Watchdogs am laufen die rebooten?

**Comment by Andy-Op** [comment]
Moin, noch ein Wunsch an Tag 2: Ich würde gerne den aktuellen Schaltstatus der LED auf der Web-Oberfläche sehen. Könnte auch so was wie Tag-/Nachtansicht sein. Oder dort wo man die LED aktiviert nebenan. Leer not defined, schwarz aus, grün an. Das wäre im Störungsfall hilfreich. Beim Aufbau der Website müsste ja genug Zeit da sein.

**Comment by knickohr** [comment]
Da hast Du doch den Status Deines Pins :

<img width="467" alt="image" src="https://github.com/lumapu/ahoy/assets/63048210/2347e1b9-932d-4cc9-b3b1-ef2726a1290c">

**Comment by Andy-Op** [comment]
Du schaltest ja schon die Hintergrundfarbe. Grün müsste high sein, gelb low und weiß nicht definiert. Ist das so?

Ich würde da auch einen andere Bezeichnung verwenden: Not defined/aktiv high/inaktiv low. Dazu gäbe es die Korrespondierende: Not defined/aktiv low/inaktiv high.
