### ISSUE TITLE
[feature request] Show Time an Date of MaxPower Values.

### ISSUE THREAD

**Issue by Thoric67** [lumapu/ahoy#1324]
Hallo,

Ich würde gerne den Zeitpunkt der MaxPower Werte sehen, entweder per Mouseover oder wie bei den Alarms.

Mit freundlichen Grüßen

Thomas

## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: HM700
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [x] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.34
Github Hash: 3178325

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by knickohr** [comment]
Siehe Wunschliste #1199

**Comment by Gubi2023** [comment]
siehe https://github.com/lumapu/ahoy/issues/1123#issue-1867952141

**Comment by zappoXX** [comment]
Moin,
hab gerade gesehen das Max AC Power im Menü durchschimmert... tritt seit Version 0.8.43 bei mir unter iOS mit allen Browsern auf (Safari, Chrome, Firefox), aber ist halt nur eine optische Geschichte...

![ahoy](https://github.com/lumapu/ahoy/assets/151444544/4f607ab8-9012-425b-94f4-867fd19eb98d)

**Comment by Gubi2023** [comment]
Am Handy ist der Mouseover schlecht ausführbar, ziemliche Fummelei, bis das Datum angezeigt wird....

**Comment by lumapu** [comment]
bei mir (Android) geht es sehr gut, ich muss einfach nur auf den MaxPwr klicken und sehe dann den Wert.
@zappoXX wird es bei dir dauerhaft angezeigt, oder nur wenn du es angezeigt hattest passiert der GUI Bug?

**Comment by zappoXX** [comment]
Ja, sofort beim Klick auf‘s Menü… Dauerhaft!!

**Comment by Gubi2023** [comment]
bei mir wird der Max-Wert nur angezeigt, wenn ich mit Mouseover das Datum aktiviert habe. und nach aktualisieren der Seite ist er weg.
Korrektur: Wert lässt sich verschieben, bleibt aber sichtbar...
![signal-2024-01-06-143106](https://github.com/lumapu/ahoy/assets/142897856/f1a2c548-8695-4522-93de-951f6c58fcd8)

**Comment by zappoXX** [comment]
Ja… genau wie bei mir!!!

**Comment by lumapu** [comment]
da bin ich leider kein Experte, evtl. findet sich ja hier ein HTML / CSS Experte 😇

**Comment by gone-for-coding** [comment]
Kann es sein, dass der Zeitstempel umgerechnet wird? Eventuell Zeitzone/Sommerzeit oder ähnliches?

Bei mir steht im Tooltip 13:58 Uhr obwohl das Maximum um 11:58 Uhr war. Zu dem Zeitpunkt wo ich das gesehen habe, war es tatsächlich auch erst kurz nach 13 Uhr, lag also in der Zukunft.

**Comment by lumapu** [comment]
@gone-for-coding guter Punkt, muss ich mir anschauen.

**Comment by gone-for-coding** [comment]
> @gone-for-coding guter Punkt, muss ich mir anschauen.

Heute sieht es bisher allerdings richtig aus. Falls es noch Mal auftritt, melde ich mich.

**Comment by gone-for-coding** [comment]
@lumapu 
Jetzt ist es wieder falsch. Pop-Up sagt 13:47 Uhr, aber da war er schon deutlich unter dem Maximum was um 12:21 Uhr war.

**Comment by lumapu** [comment]
wenn kann es nur 1 Stunde offset sein, da wir aktuell Winterzeit haben und versehentlich die Zeitzone zweimal addiert wird, aber was "krummes" kann ich mir nicht vorstellen wie bei dir 1,5h

**Comment by gone-for-coding** [comment]
> wenn kann es nur 1 Stunde offset sein, da wir aktuell Winterzeit haben und versehentlich die Zeitzone zweimal addiert wird, aber was "krummes" kann ich mir nicht vorstellen wie bei dir 1,5h

Zeitzone oder Sommer/Winterzeit kann es nicht sein. Es ist jetzt 13:02 Uhr und ich habe seit >30 Minuten rund 430W. Peak war 457W um 12:10 Uhr. Dennoch wird im Tooltip 13:01 Uhr angezeigt. Ich habe auch mehrfach komplett neu geladen.

Um 13:07 Uhr zeigt er noch immer 13:01. Jetzt um 13:08 wurde der Tooltip auf 13:08 aktualisiert, obwohl die Leistung kontinuierlich abnimmt. Sehr seltsam.

**Comment by lumapu** [comment]
allerdings seltsam, dann stimmt die Logik dahiner womöglich nicht

**Comment by lumapu** [comment]
hab den Fehler 😊. Der Timestamp wurde immer dann aktualisiert, wenn einer der DC-Kanäle ein neues Maximum erreicht hatte, nicht wie erwartet der AC-Channel.
fix kommt gleich ...

**Comment by Gubi2023** [comment]
bleibt der mouseover oder wird der  geändert? wie gesagt, mit I-Phone ziemliche Fummelei

https://github.com/lumapu/ahoy/issues/1199#issuecomment-1880025893


vielleicht wird  der der Anzeigefehler damit auch gleich beseitigt..#
https://github.com/lumapu/ahoy/issues/1324#issuecomment-1879510917

**Comment by lumapu** [comment]
@Gubi2023 und wie 😇?

**Comment by Gubi2023** [comment]
https://github.com/lumapu/ahoy/issues/1199#issuecomment-1880025893

**Comment by lumapu** [comment]
den verstehe ich nicht 😂. Habe aber glaube ich was gefunden, einfach morgen mal mit der `0.8.52` testen
