### ISSUE TITLE
0.8.43 ahoy übermittelt per MQTT nur Leistungswert eines Inverters

### ISSUE THREAD

**Issue by tester277** [lumapu/ahoy#1326]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [X] I will attach/upload an Image of my wiring

### Version

0.8.43

### Github Hash

Dev

### Build & Flash Method

was already installed

### Setup

Na

### Debug Serial Log output

```shell
n/a
```

### Error description

Nach Update 0.8.43 werden inkorrekte Werte über MQTT übermittelt.
Ich habe 2 Inverter in meinem Setup. Es wird mit der 0.8.43 nur die Gesamtleistung eines Inverters gesendet (abweichend vom Live View hier die Summe der Leistung beider Inverter). Mit 0.8.42 gibt es diesbezüglich keine Probleme.

**Comment by RealNBB** [comment]
Bestätige. Selbes Problem hier auch.

**Comment by rmayergfx** [comment]
Bitte Titel anpassen [Bug] ist etwas wenig aussagekräftig.

**Comment by tester277** [comment]
> Bitte Titel anpassen [Bug] ist etwas wenig aussagekräftig.

Erledigt sorry

**Comment by lumapu** [comment]
sehe es bei mir auch, bin schon dran es zu fixen

**Comment by knickohr** [comment]
Leider mit der 44 noch nicht gefixed, das Total AC Power wackelt bei meinen 16 Invertern wie ein Kuhschwanz 😱

![IMG_1565](https://github.com/lumapu/ahoy/assets/63048210/23fbad8a-fc83-4006-9dc4-54184a5b524f)

sieht für mich so aus als ob nur jeweils die Daten von dem abgefragten Inverter übergeben werden.

**Comment by RealNBB** [comment]
> sehe es bei mir auch, bin schon dran es zu fixen

Leider besteht das Problem weiterhin mit 0.8.44

**Comment by blueline13** [comment]
bei mir sieht das so aus. 
![grafik](https://github.com/lumapu/ahoy/assets/56932380/03b2893d-e0f8-408a-870a-6ec60801d265)

Nachtrag:
Die ganzen Werte unter mqtt.0.DTU.total spielen verrückt. Die Werte unter den einzelenen Invertern sind alle OK.

**Comment by tester277** [comment]
Bei mir wird der Wert eines (beliebigen1/2) Inverters angezeigt, dabei frage ich das Topic total/P_AC ab.
Leider bei mir nicht gelöst.

**Comment by lumapu** [comment]
hatte es zuerst falsch verstanden (heute Mittag). Jetzt sehe ich was ihr meint, wird dann in der `0.8.45` gefixt.

**Comment by knickohr** [comment]
Funktioniert wieder mit der 45 👍

**Comment by tester277** [comment]
Ja ich kann auch bestätigen, dass der Total Wert der Leistung mit der 45 wieder stimmt.
Danke für das schnelle Bug Fixing!
