### ISSUE TITLE
keine Produktion mehr

### ISSUE THREAD

**Issue by Parodontitis** [lumapu/ahoy#133]
Moin,

habe die 0.5.4 Version geflasht. Mein Active Power Limit war auf 0. Egal was ich jetzt eingebe: -1, 600, 650 wird zwar in der UI angezeigt, aber die Produktion bleibt bei 0.

![grafik](https://user-images.githubusercontent.com/41056353/183630897-323d7ee7-1cbe-4f13-8c4e-05423f9e5940.png)

P.S. Die Sonne knallt wie verrückt!

**Comment by HFarryranz** [comment]
Teste mal 1000.
Oder zuerst 10 und dann wieder 600.

**Comment by Parodontitis** [comment]
Habe den Wechselrichter vom Strom gezogen. 5 Min später ging es mit 600 wieder.
