### ISSUE TITLE
MQTT :  Yield Day nur wenn alle Inverter online

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1331]
Der Bug besteht schon sehr lange, kam mit irgendeiner 0.7.x rein.

Der Wert von Yield Day, Topic topic/total/YieldDay wird nur ausgegeben wenn alle Inverter im Status 2 sind. Ich vermute auch das es beim Yield Total, Topic topic/total/YieldTotal genauso ist.

In der WebGUI und auf dem Display ist es OK.

![IMG_1575](https://github.com/lumapu/ahoy/assets/63048210/5c491ad9-aa97-4b72-86bc-1b063ed99bad)

![IMG_1574](https://github.com/lumapu/ahoy/assets/63048210/f0092b21-115b-4445-92db-b9a532790d2a)

**Comment by lumapu** [comment]
Hat sich das nicht geändert in den letzten Versionen? Ich finde es ist jetzt viel sauberer implementiert.
Aber es geht um die Totalwerte oder? War das nicht ein Feature, dass dieser Wert nur übertragen wird, wenn alle da sind?
Evtl. sollten wir es umbauen, sodass wir eine bestimmte Zeit warten und dann den Totalwert ausgeben, unabhängig davon ob alle online sind.

**Comment by knickohr** [comment]
Oh, ich bin noch bei 460001 😅

Korrekt, die Totalwertte.

Ist das wirklich so ?   Nun ja, DA heißt das der Inverter was liefert. Das macht er auch im Status 1 und 3 der State-Machine 😉

**Comment by tester277** [comment]
@knickohr -mich würde interessieren, was das für eine Visualisierung für die Netzfrequenz ist. In das mit Grafana erstell?
Wenn ja wie heißt das Panel? 
Vielen Dank

**Comment by knickohr** [comment]
Node-Red, siehe #413

**Comment by lumapu** [comment]
Die Totalwerte werden nur gesendet, wenn alle Inverterstati > `STARTING` sind
```cpp
enum class InverterStatus : uint8_t {
    OFF,
    STARTING,
    PRODUCING,
    WAS_PRODUCING,
    WAS_ON
};
```

**Comment by knickohr** [comment]
Korrektur :
„>=starting „
Oder „>off“ 😉

**Comment by knickohr** [comment]
Das Problem hierbei ist :
Wenn nicht alle Inverter einmal gleichzeitig im Status 2 „Producing“ sind, wird kein Wert ausgegeben, bzw. immer nur 0. Und momentan bei der Wetterlage mit auch noch Schnee auf den Modulen kann das sehr lange dauern.

Steht bei mir heute immer noch auf 0, obwohl im Display und der WebGUI bereits 112Wh rein kamen 😉

**Comment by knickohr** [comment]
Funktioniert bei der 49 noch nicht 😉

**Comment by lumapu** [comment]
der Vergleich ist aber jetzt `!= OFF`

**Comment by knickohr** [comment]
Ich glaube ALLE Inverter ist es, aber laß das mal so, muß mal genauer da drauf schauen.

**Comment by knickohr** [comment]
Öhmmm *räusper*

![IMG_1598](https://github.com/lumapu/ahoy/assets/63048210/9e10ac06-9459-4de2-bbad-a20582cd46b6)

Und das über 6 Stunden 😱 Sieht für mich so aus, als würde mindestens immer ein Inverter offline sein. Da ist irgendwo ein ganz dicker Hund drin.

Eben noch schnell die „goldene“ Version drauf gemacht und siehe da, selbst in dem Schummerlicht kommen tröpfelnd die einzeln YieldDay rein und werden summiert, obwohl der eine oder andere Inverter bereits sich schlafen legt.

Ach ja, es ist die neue 51 die ich heute drauf hatte.

**Comment by lumapu** [comment]
dann habe ich es doch nicht falsch gesehen. Hast du zufällig auch in der WebUI geschaut?

**Comment by knickohr** [comment]
Jupp, da ist es korrekt, sowie auf dem Display.

**Comment by You69Man** [comment]
> Jupp, da ist es korrekt, sowie auf dem Display.

Heißt das, du hast die 51 drauf, und keine reboots oder "settings-kaputt" in Zusammenhang mit Display?

**Comment by knickohr** [comment]
Nein, es ist soweit alles OK. Nur wie „drüben“ mal geschrieben :  Wenn ich eine neue Version drauf klatsche dann ist es kaputt. Und wenn ich Glück habe kann ich in den AP booten und mir die Settings neu importieren. Es ist definitiv was mit den Settings.

Da fällt mir gerade ein, vielleicht sollte ich mal kalt booten nach einem Update auf die „neuen“ Versionen. Vielleicht tritt dann das Problem auf, weil er nach einem Softboot die Settings nicht liest ?  Oder liest er die immer nach einem boot ?

**Comment by lumapu** [comment]
Settings werden immer gelesen, aber wie immer: ein Powercylce hat schon viele Probleme behoben

**Comment by knickohr** [comment]
Nun ja, dann würden ja nach dem er kaputt ist, er sich bei einem Neustart berappeln. Tut er aber dann nicht mehr. Egal, ist nicht Thema dieses Issues, das muß ich auch noch testen 😉

**Comment by lumapu** [comment]
ein neuer Versuch, ich denke diesmal hab ich's erwischt 😉

**Comment by Linki84** [comment]
Hallo @lumapu 
Hat wirklich geklappt mit der 0.8.53
![Screenshot_20240113-081128~2.png](https://github.com/lumapu/ahoy/assets/151095860/569a8823-2106-4e87-8a31-2332f7dfddb7)

Jedoch in der Übersicht wird der Wechselrichter erst bei 3,1W als verfügbar und produzierend angezeigt
![Screenshot_20240113-081255~2.png](https://github.com/lumapu/ahoy/assets/151095860/f5a4b86c-3146-4914-9044-f54d6c13a8a1)

![Screenshot_20240113-081226~2.png](https://github.com/lumapu/ahoy/assets/151095860/c1c2d6d1-f702-4354-9bad-c00290a956e1)

**Comment by knickohr** [comment]
Funktioniert 👍 Ab der ersten Wh 😎
