### ISSUE TITLE
.47 nicht im Downloadverzeichnis

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#1333]
Wollte gerade die 47er installieren. Leider finde ich diese nicht im fw.ahoydtu.de dev Verzeichnis

**Comment by Dirk-Ahoy** [comment]
bitte macht doch kein Issue für sowas auf, das macht nur unnötig Arbeit - es wird gerade an vielen Stellen sehr viel umgebaut und wenn das mal ein Build nicht klappt ist das so.   Amen

**Comment by dtuuser** [comment]
Okay. Dachte, dass es nicht bekannt ist
