### ISSUE TITLE
ahoy_0.8.48_3c5be9a_esp8266-de Schönheitsfehler

### ISSUE THREAD

**Issue by mtet2** [lumapu/ahoy#1335]
Danke für die tolle Programmierarbeit.
In der neuen DE-Version sind mir 3 Schönheitsfehler in der Übersetzung aufgefallen.
siehe Bilder:
![Screenshot 2024-01-07 at 23-16-45 System](https://github.com/lumapu/ahoy/assets/120575424/f87c4fd7-f209-45a8-ab33-b5ea0422c099)
![Screenshot 2024-01-07 at 23-16-18 System](https://github.com/lumapu/ahoy/assets/120575424/91062d8b-7d7d-42c6-aff6-d06022cf9cbb)
![Screenshot 2024-01-07 at 23-15-19 Index](https://github.com/lumapu/ahoy/assets/120575424/669ad01f-f5be-4a7b-9909-376cb07819c1)

**Comment by Gubi2023** [comment]
Fehlermeldungen werden nicht übersetzt(?)
<img width="736" alt="Screenshot 2024-01-09 133025" src="https://github.com/lumapu/ahoy/assets/142897856/ca532d34-d5bb-4a5f-ab26-7a226454cc38">
