### ISSUE TITLE
Download-Link zu Dev-Release geht seit 0.8.46 nicht mehr

### ISSUE THREAD

**Issue by BerziOnline** [lumapu/ahoy#1340]
Die letzte Version bei welcher der Link noch funktionierte war die 0.8.46.

Das Issue hier soll sich nicht damit befassen, damit ich weiß wo ich sie sonst herbekäme - es soll nur aufzeigen, dass seither der Link nicht mehr geht. 

![2024-01-09_08-04](https://github.com/lumapu/ahoy/assets/46005508/f80f937b-c74a-4f75-92ce-2839ae755ed4)

Was mir aufgefallen ist, ist dass sich die Dateinamen seither in den Releases geändert haben:
https://fw.ahoydtu.de/fw/dev/ahoy_v0.8.46/ESP32/
=>
https://fw.ahoydtu.de/fw/dev/ahoy_v0.8.49/ESP32/

Eventuell haut das irgendeinen Ablauf kaputt, der dann die Zip-Datei für den Download-Link auf der Startseite erstellen müsste.

**Comment by huaak** [comment]
..eigentlich fehlt im Link (ver 0.8.51) nur das /fw vor dem /dev ..also statt aktuell "https://fw.ahoydtu.de/dev/"
müsste es "https://fw.ahoydtu.de/fw/dev/" heißen..

**Comment by Gubi2023** [comment]
war ich zu schnell, oder hat sich noch ein Fehler eingeschlichen??
![grafik](https://github.com/lumapu/ahoy/assets/142897856/56753b86-a47b-405b-bde8-6a0d7867d8a0)

**Comment by lumapu** [comment]
bei mir geht's

**Comment by Gubi2023** [comment]
Mit dem Handy lande ich hier.  
![IMG_4946](https://github.com/lumapu/ahoy/assets/142897856/651d44fa-d004-47de-aca8-197a7a4ba55c)

mit dem PC gehts nicht....

**Comment by Gubi2023** [comment]
war doch zu schnell, jetzt gehts. Danke!
