### ISSUE TITLE
Nach Settings-Änderung DTU nicht mehr erreichbar... V0.8.49

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1342]
### Platform

ESP8266

### Assembly

I did the assebly by myself

 Antenna

circuit board

### Power Stabilization

no Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.49

### Github Hash

???

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Setup-Änderung

### Error description

1.: in der deutschen Übersetzung wurde bei den Settings aus "Reset 'max' values at midnight" plötzlich "Maximalwerte bei Sonnenuntergang zurücksetzen". Was stimmt nun??
2. als ich die Settings änderte, erschien nach Safe eine neue Maske, die es bisher nicht gab.
3. nach Bestätigung versuchte das Programm plötzlich auf eine andere IP-Adresse  sich zu verbinden, die es nicht gab. Seither ist meine DTU nicht mehr erreichbar....
<img width="673" alt="Screenshot 2024-01-09 132826" src="https://github.com/lumapu/ahoy/assets/142897856/01bbde67-8de2-44b9-9071-744968ae59cf">

**Comment by soelli22** [comment]
Hast du ein Display an deiner DTU? Damit habe ich habe bemerkt, das mit der 0.8.49 und .48 die DTU ständig neu bootet. (DTU war über web Zugriff kaum erreichbar.)
Mit der 0.8.45 läuft alles normal. Ich verwende ein ESP32. Wenn ich meine Inverter lösche, läuft es normal hoch. Bin zurück auf die .45, dann passt es.

**Comment by Gubi2023** [comment]
nein, kein Display. DTU ist "tot",  blinkt auch nicht mehr....

**Comment by lille2000** [comment]
Ich kenne die selbe Fehlermeldung von Firmware-Updates. An und zu brechen die FW Updates mit “Netzwerkzeitüberschreitung” ab. Da hilft auch kein Reboot der DTU, es bricht wieder nach ein paar Sekunden später ab. Irgendwann geht es dann und danach ist die DTU tot, da hilft nur noch neu aufsetzen per USB.  Danach geht wieder alles. 
ingesamt hatte ich jetzt 4x den Fall.

**Comment by knickohr** [comment]
Könnt ihr euch erinnern was ihr geändert habt ?

**Comment by Gubi2023** [comment]
2. als ich die Settings änderte,(im Inverter-Menue) erschien nach Safe eine neue Maske, die es bisher nicht gab, sieht so aus.
![2024-01-10 09_43_17-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/f9bce266-9885-4da2-aef6-2a9ade6a6bd7)
Nach Drücken der Next-Taste kam obige Fehlermaske. Meine alte IP-Adresse war http://192.168.178.60

**Comment by knickohr** [comment]
Das Komma sieht mir nicht gesund aus 😵

**Comment by Gubi2023** [comment]
du meinst im WLAN-Namen? hat bisher noch nie gestört: 
 
![Uploading Screenshot 2024-01-10 111109.jpg…]()

**Comment by Gubi2023** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/142897856/55dc7771-5bfa-4063-a542-c43e2705c821)

**Comment by knickohr** [comment]
Das stört vielleicht die Fritte nicht, aber die DTU

**Comment by Gubi2023** [comment]
die DTU läuft seit 1 Jahr mit diesem WLAN. Jetzt stört es plötzlich??

**Comment by knickohr** [comment]
Siehe #1345

**Comment by lumapu** [comment]
nein, die SSID ist nicht das Problem. Die obige Seite (Setup Wizard) wird aufgerufen, wenn man hinter der IP irgendwas eingibt, das der ESP nicht zuordnen kann, zB. http://192.168.178.60/Gubi2023
Der Next Button ist fest auf die IP `192.168.4.1` kodiert, da diese Seite nur für die Ersteinrichtung gedacht ist.

**Comment by Gubi2023** [comment]
habe jetzt die 8.52 installiert. Läuft anfangs problemlos, aber sobald ich irgendwelche Settings ändere, ist die DTU wieder scheintot 
siehe https://github.com/lumapu/ahoy/issues/1345#issuecomment-1887229972    
ich habe Minimalkonfig, also ESP8266 ohne Display

**Comment by Gubi2023** [comment]
zurück auf 8.44: Settingsänderungen problemlos möglich.

**Comment by lumapu** [comment]
wie sieht es mit neueren Versionen aus, im besten Fall mit der aktuell neuesten?

**Comment by Gubi2023** [comment]
meine DTU ist gestern abgeraucht, kann erst morgen wieder testen....

**Comment by lumapu** [comment]
oh was heißt das? FW oder HW?

**Comment by Gubi2023** [comment]
mein NRF-Modul hatte den Geist aufgegeben, ich hoffe das neue tutet.

**Comment by Gubi2023** [comment]
8.59: Änderungen der Settings jetzt problemlos möglich
