### ISSUE TITLE
Fehlermeldungen werden nicht übersetzt(?)

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1343]
Fehlermeldungen werden nicht übersetzt(?)
<img width="736" alt="Screenshot 2024-01-09 133025" src="https://github.com/lumapu/ahoy/assets/142897856/ca532d34-d5bb-4a5f-ab26-7a226454cc38">

_Originally posted by @Gubi2023 in https://github.com/lumapu/ahoy/issues/1335#issuecomment-1883500761_

**Comment by Gubi2023** [comment]
Version 0.8.49

**Comment by lumapu** [comment]
ja genau, bisher wurden nur die statischen HTML Seiten übersetzt, die anderen Themen folgen bald, erfordern aber noch eine Struktur die heute noch nicht da ist.
Der issue ist gut für alle, denen das bis dahin auch auffällt. Ich denke die Deutsche Version ist für viele schon viel einfacher zu verstehen als bisher.

**Comment by Gubi2023** [comment]
8.50.: Sieht bisher gut aus,(Respekt für die schnelle Umsetzung!!) 
ich lass ihn mal noch offen, falls noch Fehler auftauchen...

**Comment by Gubi2023** [comment]
<img width="734" alt="Screenshot 2024-01-11 144614" src="https://github.com/lumapu/ahoy/assets/142897856/ac3ae77b-3c9c-423a-8253-2f32f39bc351">

Werden Ereignismeldungen auch noch übersetzt?

**Comment by lumapu** [comment]
Freiwillige vor 😇
