### ISSUE TITLE
Übersetzungsfehler in deutsch ?

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1346]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.49

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Änderung in Settings-Inverter

### Error description

 in der deutschen Übersetzung wurde bei den Settings aus "Reset 'max' values at midnight" plötzlich "Maximalwerte bei Sonnenuntergang zurücksetzen". Was stimmt nun??

**Comment by lumapu** [comment]
mitternachts ist richtig, Wird in der nächsten Version gefixt.

**Comment by lille2000** [comment]
Nur ein Vorschlag: 
Vielleicht kann man die Abkürzung “Begr.”  mit “Limit” ersetzen
![IMG_2319](https://github.com/lumapu/ahoy/assets/86225787/3f69eb5f-d45d-4868-a3d0-68e8a72f8dc5)
.

**Comment by lumapu** [comment]
ok, es hieß halt früher "Power Limit" und heißt jetzt wie bei Hoymiles "Active Power Control" (APC). Aber dennoch finde ich "Limit" hier auch besser als das abgekürzte "Begr."

**Comment by huaak** [comment]
..spricht etwas dagegen in der deutschen Version aus dem doch recht sperrigen 
"Zuletzt empfangene Daten wurden angefragt um: *Zeitstempel*" 
ein "Zuletzt empfangene Daten um: *Zeitstempel*" zu machen?!..

**Comment by huaak** [comment]
..achja, in der lang.json ist in Line 94 & 104 ein kleiner Typofehler: "Verindung" statt "Verbindung"..

**Comment by Gubi2023** [comment]
Send und Save wird nicht übersetzt (?)
![grafik](https://github.com/lumapu/ahoy/assets/142897856/dd977931-c695-4d16-8169-1eb5d3f673ce)

**Comment by Gubi2023** [comment]
<img width="544" alt="Screenshot 2024-01-11 144246" src="https://github.com/lumapu/ahoy/assets/142897856/8e208c1e-ae8d-4d1d-b594-aca23e922ab9">

ich würde das Fragezeichen weglassen...

**Comment by Gubi2023** [comment]
blaue Felder auch übersetzen oder so lassen?
<img width="491" alt="Screenshot 2024-01-12 011152" src="https://github.com/lumapu/ahoy/assets/142897856/17cf2f64-8fba-48b0-a22f-2445dfcafeb1">

**Comment by zappoXX** [comment]
![1](https://github.com/lumapu/ahoy/assets/151444544/42d48ab2-69b6-4e4f-a319-6451837ecce6)

**Comment by zappoXX** [comment]
"am" statt "um" würde hier meiner Meinung nach besser passen...

![1](https://github.com/lumapu/ahoy/assets/151444544/2508c129-c160-43de-b782-a68a725b1a6e)
