### ISSUE TITLE
Yield total via WEB API not available?

### ISSUE THREAD

**Issue by stormbreaka** [lumapu/ahoy#1349]
Hello together,

is there a WEB API (but not inverter/id/x) for receiving the total yield in kWh? Up to now this is only available with the "inverter/id/0-x". For the power I use "/api/index" with the entries "cur_pwr". I thought there is something in "/api/live", but the content does not include any yield data information. It only includes field names with their units and no values.

Can you also approve this in version 0.8.36?

Greets :)

## Hardware
  * [ ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by lumapu** [comment]
yes that's correct. We changed the API a long time ago. The reason behind was the amount of data which has to be transfered.
