### ISSUE TITLE
Fusionsboard ab Version 0.8.52 mit CMT Bootschleife

### ISSUE THREAD

**Issue by teletapi** [lumapu/ahoy#1355]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.50

### Github Hash

e4cb948

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

ohne

### Debug Serial Log output

```shell
kein Log
```

### Error description

Sobald beim Fusionsboard die 0.8.52 oder 0.8.53 (bei der 51 bin ich nicht sicher hab ich nicht probiert) geflasht wird egal ob per Ota oder VSC Flash und das CMT ist aktiviert in den System Configs beginmt eine dauer Bootschleife. Man kann mit etwas Glück in den System Configs das CMT Häckchen entfernen und speichern danach ist die Bootschleife weg.
Von der 0.8.52 konnte ich auch nicht downgraden bei der 0.8.53 konnte ich wieder downgraden auf die 0.8.50 die auch wieder mit CMT funktioniert.
Display 1309 2,42"

**Comment by teletapi** [comment]
Gleiches gilt im übrigen auch für den ESP32

**Comment by lumapu** [comment]
du denkst ich kann es bei mir reproduzieren?
Werde es gleich testen.

**Comment by teletapi** [comment]
https://discord.com/channels/984173303147155506/1144045244166443159

Wir sind hier schon seid einer ganzen Weile am testen und kommen nicht so richtig weiter

**Comment by You69Man** [comment]
See also #1354

Ergänzung 14.1.: Ich fürchte #1354 ist doch was anderes. Dort geht es um einen sporadischen, seltenen Reboot, während dieser Reboot sofort auftritt.

**Comment by knickohr** [comment]
Bitte mal dazu schreiben, ob ein Display dran hängt, und welches.

**Comment by Dirk-Ahoy** [comment]
Fehler ist jetzt gefunden - sollte bald gefixt werden.   Bis dahin Display abstellen oder den Graphen auf >0 % stellen - dazu muss es aber Nacht sein oder Antenne abmachen das kein Empfang vom Wechselrichter ist.

**Comment by You69Man** [comment]
Siehe #1360
