### ISSUE TITLE
Angebot: Info über compilierte Module in version string

### ISSUE THREAD

**Issue by fsck-block** [lumapu/ahoy#1358]
Da nun auch MQTT wie andere Module auch an/abschaltbar ist nimmt damit die Anzahl der möglichen Varianten pro SW-version weiter zu. Es ist vielleicht in Zukunft bei Fehlermeldung hilfreich zu wissen, welche Module enthalten sind.

Ich habe dafür eine kleine Änderung implementiert bei welcher eine Kennung zur Versionkennung je nach compiliertem Modul zugefügt wird. Z.b. für die 0.8.54 mit Prometheus, Display und History in Deutsch: -> "0.8.54-PDH-de"
Mögliche Werte:
P - Prometheus
M - MQTT
D - Display
H - History
A - AP Only
Y - Syslog
S - Simulator
sowie die Sprach-variante (en,de)

Steht als PR  #1357  zur Verfügung

**Comment by knickohr** [comment]
Noch schöner wäre es man könnte sich diese Module im Git auswählen und es baut für Dich dann diese Version.

**Comment by fsck-block** [comment]
Stimmt, dann brauchst du um so mehr die Info was rein gebaut wurde.
Allerdings übersteigt das aktuell meine Fähigkeiten.

**Comment by knickohr** [comment]
Kannst Du die Sprache auch noch mit kenntlich machen ?  Oder ist das eine andere Ecke. Mir fiel bei der 54 auf das sie offenbar beides kann. Mal ist sie DE, mal EN 😵

**Comment by fsck-block** [comment]
Sprache geht über `#define LANG_DE`.
Kann ich mal rein machen.

**Comment by fsck-block** [comment]
Das würde dann so aussehen:
![version-lang](https://github.com/lumapu/ahoy/assets/58307481/0951c5c6-ad59-4f64-b43f-aae426e8b8c8)

Und da ich gerade selbst auf seltsame Yield-Werte reingefallen bin kommt noch dazu:
Y - Syslog
S - Simulator

**Comment by lumapu** [comment]
wird in `0.8.55` gemerged 😊, siehe auch Kommentar dort
