### ISSUE TITLE
ESP8266 crash nach dem Power Limit MQTT Kommando (v.0.5.3)

### ISSUE THREAD

**Issue by FSys77** [lumapu/ahoy#136]
Mein ESP8266 crasht reproduzierbar wenn ich via MQTT das Power Limit Kommando absetze (xyz/devcontrol/0/11). Manchmal gleich beim ersten Versuch, manchmal klappt ein Versuch, manchmal sogar zwei - aber dann stürzt er wieder ab. QS ist auf 0. Zwischen den MQTT Publish Kommandos warte ich immer 30-60 Sekunden.

Eventuell ist die Pubsubclient Lib das Problem. Siehe: https://discord.com/channels/984173303147155506/992022163307638887/1006891174562385971

Ohne dieses Kommando läuft der ESP8266 stabil.

Serial Log: https://github.com/grindylow/ahoy/files/9299844/serial.log

**Comment by hubsi5** [comment]
Es gibt schon eine neue 0.5.5 Version

**Comment by DanielR92** [comment]
Kann man dieses Beitrag nun closen?

**Comment by stefan123t** [comment]
@FSys77 bitte mit der v0.5.9 überprüfen und ggf. als gelöst schließen. Danke

**Comment by aschiffler** [comment]
solved by update
