### ISSUE TITLE
[Bug] History Charts does not contain the whole day

### ISSUE THREAD

**Issue by lille2000** [lumapu/ahoy#1361]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.53

### Github Hash

Unbekannt

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

—

### Error description

There is no history data on display and Webgui at the end of the day.
Some versions ago I had a graph of the whole day ( between sunrise and sunset)

Now it‘s different: It seems that that the displayed timespan is only the last some hours & not taking into account that communication is paused during night)

—> There are two issues:
1) Buffer to small
2) History buffer is filled even during night pause 

webgui (after one sunny day):

![IMG_2321](https://github.com/lumapu/ahoy/assets/86225787/c60ebaae-f537-4153-85e9-78fb46e9e739)

**Comment by lille2000** [comment]
![Uploading IMG_2323.jpeg…]()

**Comment by lille2000** [comment]
![IMG_2323](https://github.com/lumapu/ahoy/assets/86225787/35541e64-ce20-4725-9f75-143bcbed5a0e)
![IMG_2322](https://github.com/lumapu/ahoy/assets/86225787/67ab71d4-1339-48a0-b663-999ca0e4b452)

**Comment by knickohr** [comment]
Check the uptime of the DTU

**Comment by lille2000** [comment]
Uptime: 1d10h

**Comment by You69Man** [comment]
fix for display graph is in work

**Comment by You69Man** [comment]
PR: #1364

**Comment by lille2000** [comment]
Das externe Display wurde bisher nicht mehr zu früh zurückgesetzt. ✅👍

Die Webgui  zeigt maximal die letzten 200 Messwerte ( alle 15s Einsen ) an und stoppt auch zum Inverterstop.  200 Messwerte sind nicht viel, aber ich habe in einem anderen Issue  gesehen, dass amm der Form schon gearbeitet wird.

**Comment by lille2000** [comment]
Hier #1336 steht, dass die letzten 256  Messpunkte in der Webgui angezeigt werden.  Es ist also kein Bug sondern Feature.

Ich beobachte die Displayanzeige noch einige ZZage und schließe danach das Ticket.

BTW:
256 Werte, alle 15s gemessen = 64 Minuten History.  Das ist nicht viel bzw. mir bringt diese Webgui-Anzeige in dieser Form leider keinen Mehrwert (da ich am Nachmittag eh nicht mehr viel Licht habe) 
Es ist mir aber klar, dass  die kleinen Mikroprozessoren nicht viel RAM haben…

**Comment by knickohr** [comment]
Dann müßt ihr halt das Inverter Intervall höher setzen 😉

**Comment by dtuuser** [comment]
Beim 5 Minuten Intervall würde man 16 Stunden darstellen können
