### ISSUE TITLE
kleinere Fehler in Grid-Profile-Anzeige

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1365]
in eurer Grid-Profile-Anzeige haben sich m.E. 2 kleinere Fehler eingeschlichen. Siehe Bild
![2024-01-16 09_53_10-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/3de592b5-b8d1-4569-a8e7-1608bf75491f)

**Comment by stefan123t** [comment]
@lumapu der Divisor ist mW ein Fehler in der HM Firmware der für bestimmte Versionen so von Hoymiles gefixt wurde, dass der Wert einfach mit einem anderen Divisor im Grid Profile steht.
