### ISSUE TITLE
[Bug] Einstellungen speichern ohne sofortigen Neustart --> Wizard

### ISSUE THREAD

**Issue by Loetnase** [lumapu/ahoy#1366]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.56 + 0.8.57

### Github Hash

f4a8224

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

ESP32 mit ePaper und ESP8266 mit Nokia mit 0.8.56 und 0.8.57

### Error description

Ist das so gewollt? 
Ich wollte einfach mal zwischendurch meine Einstellungen speichern und noch was anderes umstellen, 
dann lande ich aber bei dem wizard.
Das habe ich schon mit der 8.56 bemerkt, ist jetzt aber auch in der 8.57 am ESP32 und ESP8266 so
<img width="1016" alt="Bild1" src="https://github.com/lumapu/ahoy/assets/120967249/468a0cf9-7787-42cd-a3c2-876a3230f7f5">
<img width="965" alt="Bild2" src="https://github.com/lumapu/ahoy/assets/120967249/cfd390aa-94f2-4b54-81ee-266ece7f50b3">
<img width="739" alt="Bild3" src="https://github.com/lumapu/ahoy/assets/120967249/c8998add-7a2c-4489-aa70-108c0e201749">

**Comment by lille2000** [comment]
Ich hatte das auch einmal vor ca. einer Woche:
Ich hatte das Display in den Einstellungen geändert und danach „ speichern mit Reset“ ausgeführt. Dann kam dieser WLAN Screen.

Nach dem Neustart war meine Änderung des Display nicht gespeichert. Der nächste Versuch war dann erfolgreich (ohne WLAN Screen)

**Comment by lille2000** [comment]
Da gab es was ähnliches, aber so richtig wurde nicht geklärt, wieso es zu dem WLAN Screen kam. 

Dort hieß es: „Tippfehler in der Adresse“  zb statt „/live“ —> „/live1“ 

aber es wurde nicht geklärt, wie ein Speichern zu Tippfehler in der Browseradresse führen kann.
 
 #1342
