### ISSUE TITLE
[Bug] 0.8.57 MQTT yield day ab dem zweiten Tag = 0

### ISSUE THREAD

**Issue by MiniOh** [lumapu/ahoy#1368]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.57

### Github Hash

-

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

-

### Error description

Hallo, 

in der Version 0.8.57 wird yield day über MQTT als 0 ausgegeben "ab dem zweiten Tag".
Nach einem Reboot wird yield day korrekt ausgegeben, nach einer Nacht (ohne Neustart der DTU) wird inverter/total/YieldDay
als 0 zurück gegeben. In der GUI stimmen die Werte.
Wenn man manuell "an Tag 2" einen Rebbot ausführt, wird yield day wieder richtig ausgegeben.

Werte und Gesamtertrag um Mitternacht zurücksetzen - JA
Werte bei Sonnenuntergang zurücksetzen - NEIN
Werte zurücksetzen, sobald der Wechselrichter nicht erreichbar ist - NEIN
Maximalwerte mitternachts zurücksetzen - NEIN
Kommunikation starten ohne gültige Zeit (sinnvoll im AP Modus) -NEIN
Grid-Profil auslesen - JA

Beste Grüße

**Comment by tester277** [comment]
Kann ich für identische Hardware bestätigen. Nach Reboot am 2 ten Tag wird YieldDay wieder angezeigt und auch weiter per mqtt entsprechend übermittelt/aktualisiert.
Wobei folgende Settings bei mir auf nein stehen:
Reset values and YieldDay at midnight
Reset values at sunset
Reset values when inverter status is 'not available'
Reset 'max' values at midnight
Start without time sync (useful in AP-Only-Mode)

Danke und Grüße

**Comment by lumapu** [comment]
ok, habt ihr `disable night communication` in den Invertersettings an?

**Comment by tester277** [comment]
Bingo - Pause communication during night ist aktiv und Reboot Ahoy at midnight ist (logischerweise) nicht aktiv.

**Comment by lumapu** [comment]
ok, dann haben wir den Übeltäter, ich überlege, wie wir das trotzdem schön hinbekommen

**Comment by MiniOh** [comment]
> ok, habt ihr `disable night communication` in den Invertersettings an?

Bei mir ist die Option aus.

Kein Neustart nachts.
Keine Disable Night Communication

**Comment by MiniOh** [comment]
![image](https://github.com/lumapu/ahoy/assets/27901554/650a61cc-30ad-4150-a6ea-99c4320acaf5)

**Comment by lumapu** [comment]
verstanden, das kann die aktuelle Logik tatsächlich gerade nicht, bruache irgendein event um eine Variable, die den Wert zurücksetzt - bin am überlegen.

**Comment by MiniOh** [comment]
Ok, also ein nächtlicher Neustart würde das "Problem" dann erst mal
umgehen?

Blöde Frage. Seit wann besteht das Verhalten und warum war es vorher nicht da?
Ich hatte die Optionen Reboot und Pause Communication nicht verändert.

**Comment by lumapu** [comment]
ja würde es. Wir haben genau an dieser Stelle geschraubt, da es immer wieder zu viele MqTT Übertragungen gab in der Vergangenheit. Ich werde das hoffentlich die Tage fixen können, dann kannst du die Option wieder wie zuvor stellen.
