### ISSUE TITLE
[Bug] Warnmeldung bei Firmwareupdate

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1370]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.58

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Firmwareupdate

### Error description

wenn ich beim Update die Sprache nur von englisch auf deutsch ändere (gleiche Firmware 8.58), erhalte ich folgende Warnmeldung 
<img width="813" alt="Screenshot 2024-01-17 012339" src="https://github.com/lumapu/ahoy/assets/142897856/3aa24d4f-3783-447b-afb8-4cc6a28d7fae">
in Gegenrichtung (deutsch auf englisch) kommt  keine Warnung

**Comment by zappoXX** [comment]
Bei mir auch...

![1](https://github.com/lumapu/ahoy/assets/151444544/85dcda55-89b6-4470-8078-5862249f25e0)

**Comment by knickohr** [comment]
Kommt nur einmal. Wenn ihr aber eine ältere Firmware aufspielt als die 58 dann kann es wieder auftreten. Ist kein Bug, wurde mit der 57 eingeführt, sollte ab jetzt bei neueren Versionen nicht mehr auftreten.

**Comment by Gubi2023** [comment]
Der englische und der deutsche Text passt nicht ganz zusammen: da u.U. in deutsch (Punkt fehlt übrigens im Text) fehlt im englischen.
Vorschlag: may statt does

**Comment by lumapu** [comment]
ist leider nicht ganz trivial aus den beiden Strings das environment korrekt zu extrahieren. Ich bemühe mich hier in Zukunft noch nachzubessern

**Comment by Gubi2023** [comment]
> Kommt nur einmal. Wenn ihr aber eine ältere Firmware aufspielt als die 58 dann kann es wieder auftreten. Ist kein Bug, wurde mit der 57 eingeführt, sollte ab jetzt bei neueren Versionen nicht mehr auftreten.
8.59:  Warnmeldung kommt immer noch, jetzt in beiden Richtungen. englischer Text unverändert, beim deutschen ist der Punkt jetzt vorhanden.
ausserdem ist auch bei englischer Firmware ein deutscher Text vorhanden   
<img width="1112" alt="Screenshot 2024-01-19 001012" src="https://github.com/lumapu/ahoy/assets/142897856/95fb6556-5d9e-4c58-af11-e14f9d233546">

**Comment by MetaChuh** [comment]
zum thema multilingual localization:
multilingual localization is more complicated than one thinks at first glance.

bearbeitung seit einführung kostet, auch bei diesem projekt, den devs bis jetzt mehr zeit, als genau wie vorher zu antworten, warum es ahoy dtu nur auf englisch gibt/gab.

siehe: andere projekte, open source, sowie major companies, die jahre lang mit den problemen zu kämpfen hatten und haben, dass zb. durch string lengths, plötzlich dieser oder jener button/div/zeile entweder nicht mehr lesbar ist, bzw. durch overflow zeilenumbrüche die optik nicht mehr ist wie vorher, ganz zu schweigen von online übersetzten texten, wenn grad' kein native speaker da war (letzteres nicht hier, jedoch in fast jeder von alexibexi vorgelesenen anleitung)

**Comment by lumapu** [comment]
@Gubi2023 danke für deine Hinweise, der deutsche Text in der englischen Version kommt aus deinem Browser, Stelle den auch auf english dann passt's 😉
Ich glaube langsam haben wir das multi language in Griff, ist echt unglaublich wie viele eine Deutsche Version wollen
