### ISSUE TITLE
[Bug]: Am Handy  Settings-Inverter-Edit/Delete nicht sichtbar

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1372]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.58

### Github Hash

0.8.59

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Setup Inverter

### Error description

öfters mal mas neues: Am Handy (Iphone und Android)  kann seit V8.58 das Fenster Settings-Inverter nicht mehr verschoben werden, somit sind die Buttons -Edit/Delete nicht erreichbar.
![signal-2024-01-19-094357](https://github.com/lumapu/ahoy/assets/142897856/79b442aa-d14a-4d31-bd43-79263d7d745a)
Ausserdem sind in 8.59 die Texte dazu auf deutsch, obwohl englische Firmware geladen

Edit: nach mehrmaligem aktualisieren der Seite sind die Texte englisch....

@MetaChuh deinen Hinweis habe ich gesehen  https://github.com/lumapu/ahoy/issues/1370#issuecomment-1899386591

**Comment by Gubi2023** [comment]
V8.63:  Verhalten noch unverändert; über Handy keine Settings-Änderungen möglich, da die Buttons im Inverter-Feld nicht mehr sichtbar sind!

**Comment by MetaChuh** [comment]
dirty workaround für jetzt: handy im querformat halten.

ps: erinnert mich grad an apple's erstes kommentar zum iphone 4 antenna problem:
it's not broken, people are just holding it wrong 😂

**Comment by Gubi2023** [comment]
jetzt ok. Danke 👍
