### ISSUE TITLE
[Bug] mqtt daten  "Yield Day" werden nicht mehr gesendet

### ISSUE THREAD

**Issue by Oxbow6** [lumapu/ahoy#1375]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.36

### Github Hash

x

### Build & Flash Method

ESP Tools (flash)

### Setup

MqTT Brocker mit 60 sec. intervall

### Debug Serial Log output

```shell
total
YieldTotal = 904.753
P_AC = 574.1
P_DC = 604
```

### Error description

Seit dem update auf die Version 0.8.36 habe ich keine total Yield Day Daten mehr auf meinem OpenhaB. 
Habe mir mal mit einem MQTT Explorer das angeschaut und die Ahoy sendet keine total yield Day daten mehr über MQTT.
Vor dem Update hat das aber noch funktioniert.

**Comment by Gubi2023** [comment]
wird in "history" auch nicht angezeigt. 
<img width="1280" alt="Screenshot 2024-01-20 124848" src="https://github.com/lumapu/ahoy/assets/142897856/1f84892a-bd6d-4b89-9da3-cfb9b0bcfa71">
gleiche Ursache??

**Comment by lumapu** [comment]
@Gubi2023 nein, unten steht ja alle 86400s (also jeden Tag ein Strich).

Die Releaseversion sollte das noch ohne weiteres können. Kannst du bitte die aktuelle Dev testen?
https://fw.ahoydtu.de/fw/dev/ahoy_v0.8.60/

**Comment by Gubi2023** [comment]
ok, hab ich fehlinterpretiert.
deshalb nochmals meine Frage: wäre es möglich, beim total yield per day "updated" in Std/Min. anzugeben? (86400sec ist etwas sperrig...)
https://github.com/lumapu/ahoy/pull/1336#issuecomment-1890446205

<img width="1280" alt="Screenshot 2024-01-20 160225" src="https://github.com/lumapu/ahoy/assets/142897856/10dc0f1d-21e4-4d09-9a2c-de8b458b864b">

**Comment by Oxbow6** [comment]
Hallo 
Auch mit der v08.60 Version habe ich das gleiche Problem, es werden keine Yield Day über MQTT gesendet. 
Wenn ich aber den Discovery Config (homeassistant) sende funktioniert die Yield Day Anzeige für einen Tag, danach habe ich weider das gleiche Problem.

**Comment by lumapu** [comment]
@knickohr ist unser MqTT Experte, er hätte sich doch schon längst gemeldet, wenn das nicht mehr funktioniert - wobei er momentan jeden Tag eine neue Version testet.

**Comment by knickohr** [comment]
Das wäre mir sofort aufgefallen 😉

Wenn der Topic inverter/total/YieldDay oder inverter(total/YieldTotal gemeint ist, kann ich keine Probleme feststellen. Bei den einzelnen Invertern habe ich nicht nachgeschaut und nutze die auch nicht.

**Comment by Oxbow6** [comment]
Hallo 
es geht um den  inverter/total/YieldDay, der nach 24 Stunden dann plötzlich nicht mehr läuft. Auch wird dieser nicht auf Null gesetzt sondern hat immer noch den Wert vom letzten Tag. Habe die Daten extra über einen MQTT Explorer kontrolliert.

**Comment by lumapu** [comment]
also das gleiche wie in #1368 ?

**Comment by Oxbow6** [comment]
So in der Art, das Problem sollte ja gelöst worden sein ab der Version 0.8.57, denn ich benutze die Version 0.8.60
Bei mit steht im MQTT Explorer am 2 Tag einfach der Wert vom Vortag drin und dieser verändert sich auch nicht. 
Erst nach einem Discovery Config (homeassistant) wird der Wert dann korrekt angezeigt.

total
YieldTotal = 926.717
YieldDay = 10565.9
P_AC = 4.7
P_DC = 13.9

**Comment by lumapu** [comment]
hast du Akku bzw. 24h Betrieb?

**Comment by Oxbow6** [comment]
Nein
über Nacht schalte ich die Kommunikation der Wechselrichter aus.

**Comment by lumapu** [comment]
ich kann das nicht nachvollziehen, auch heute kamen wieder die Daten korrekt rein. Anbei meine Einstellungen

![grafik](https://github.com/lumapu/ahoy/assets/22733082/42f7ede2-03b5-4f81-b3f2-e6beb128cd91)

**Comment by Oxbow6** [comment]
Das sind aktuell meine Einstellungen:


![Ahoy1](https://github.com/lumapu/ahoy/assets/150791180/56872b64-3d7a-4986-a73e-e0ac41edb4c4)

**Comment by Oxbow6** [comment]
Hallo 
Ich habe nun aktuell die Version 0.8.62 am laufen und mit dieser habe ich das Problem nicht mehr, Obwohl laut Log hier nichts am MQTT geändert worden ist. Ich werde das weiter beobachten

**Comment by tester277** [comment]
Sorry aber ich habe wohl ein Problem bei meinen Abfragen, das hier geschriebene ist nicht korrekt.
> Bei mir tritt der Fehler seit gestern  auf (Version 0.8.64). Was hat sich geändert? Habe einen Inverter außer Betrieb (gestern tagsüber) genommen. Bis zum Ende gestern sind Daten via mqtt in meiner Datenbank. Seit heute nicht mehr. Da hilft auf kein  restart.

**Comment by tester277** [comment]
Entschuldigt für das hin und her. Habe es geprüft. Die total Werte fehlen seit gestern. Es sind nur die Werte des letzten (verbliebenen) Inverters vorhanden. So gesehen ist das eher works as designed. Wozu doppelt identische Werte für einen Inverter erfassen…
![IMG_0651](https://github.com/lumapu/ahoy/assets/65363917/0c088553-362b-4068-96f5-c5c2e6aaa5ab)

**Comment by lumapu** [comment]
kann nicht folgen. Du meinst warum werden die Totalwerte bei nur einem Inverter gesendet?

**Comment by tester277** [comment]
Situation vorher:
Inverter 1 und Interter 2 sind in Betrieb - es werden Totalwerte für beide Inverter übermittelt, zusätzlich wird die Summe beider Inverter als Total übertragen (3 Werte).
“Fehler“ Situation:
es ist nur ein Inverter (1) dauerhaft in Betrieb, dann gibt es nur den Totalwert des einen Inverters, es wird zusätzlich kein Total mehr gebildet und übermittelt. Wenn ich den Inverter 2 (nicht in Betrieb) auch in der Konfiguration deaktiviere, dann erhalte ich wieder den Totalwert. Also eigentlich kein großes Problem.

**Comment by lumapu** [comment]
das ist absichtlich so. Der Zustand war garnicht so einfach herzustellen - @knickohr weiß ein Lied davon zu singen.
Hätten wir es nicht so implementiert, würde der Yield sehr stark hin und herspringen, wenn einzelne Inverter mal nicht erereichbar sind ...

**Comment by knickohr** [comment]
Bei „nicht erreichbar“ ist nicht nur deaktiviert oder ausgeschaltet gemeint, es reicht schon wenn mal zwischendrin keine Produktionsdaten kommen. Das Ganze zappelt dann wie ein Kuhschwanz hin und her.

**Comment by tester277** [comment]
Bei mir war es nur ein Übergangszustand. Ich sehe da keinen Fehler der unbedingt korrigiert werden müsste.

**Comment by Oxbow6** [comment]
Hallo
Ich hätte noch eine andere Frage, besteht die Möglichkeit über MQTT auch die Maximale Leistung aller Wechselrichter abrufen?  im Ordner Total habe ich aktuell nur diese 4 Werte.
Gruss und Danke

total
YieldTotal = 1092.71
YieldDay = 1532.35
P_AC = 2297.7
P_DC = 2418.2

**Comment by knickohr** [comment]
Ist doch drin, für jeden Inverter und für jeden seiner Channels 😉

![IMG_1801](https://github.com/lumapu/ahoy/assets/63048210/9d8dafb2-57f9-4143-a697-c3b19d0a4788)

Nur der gesamte Totalwert nicht.

**Comment by Oxbow6** [comment]
Hallo Knickohr
Ich würde gerne nur den Totalbetrag abgefragt haben, denn sonst müsste ich alle 32 Channels einzeln abfragen und das geht dann wieder auf die Performance meiners Openhabs.

**Comment by knickohr** [comment]
OK, der Issue ist noch auf, aber wenn Du möchtest, kannst Dubdas auch in die Wunschliste rein schreiben :  #1199

**Comment by Oxbow6** [comment]
Hallo Knickohr
Ich verwende nun die Version 0.8.75 mit dem Mqtt MaxPower und das funktioniert super. Vielen Dank

![maxPower](https://github.com/lumapu/ahoy/assets/150791180/8ca6afd5-362b-46af-bd0b-59e8423da53b)

**Comment by Oxbow6** [comment]
Hallo Knickohr
Ich habe noch ein kleines Problem mit dem MQTT MaxPower, plötzlich gegen den Abend stimme die Werte nicht mehr überein.
Vermute mal dass dies immer noch Sonnenuntergang passiert
Hast Du eine Vermutung ?
zb : Ahoy 2338.9W
MQTT 1450 W

**Comment by knickohr** [comment]
Ein oder mehr Inverter ?
Wenn mehr, dann werden die fehlenden nicht mehr addiert.

**Comment by Oxbow6** [comment]
Hallo
Es sind mehere Inverter ( 7 Stück )

**Comment by knickohr** [comment]
Ja, dann werden nur die momentan aktiven aufsummiert.

**Comment by Oxbow6** [comment]
Habe nun zum testen die Version 0.8.81 aufgespielt. 
Mit der bekomme ich keine Live AC und DC Daten über MQTT.

**Comment by lumapu** [comment]
das wurde mit der 0.8.82 gefixt

**Comment by emmrichd** [comment]
Ich habe das Problem, mit missing Total day, in der 0.8.155 - 5feb293 immer noch. ESP32

**Comment by emmrichd** [comment]
Könnte daran liegen, dass einer meiner Wechselrichter nicht aktiv ist. Die Logik, warum dann kein Total kommen sollte erschließt sich mir aber nicht.

**Comment by panticz** [comment]
Wenn mehrere Inventer in AHOY konfiguriert sind wird anscheinend der Wert von `total/YieldDay` nicht an MQTT übermittelt wenn einer der Inverter nicht erreichbar ist. Erst wenn dieser deaktiviert wird (`Enabled` checkbox abwählen) dann werden die `total/YieldDay` Daten wieder übermittelt.

https://github.com/lumapu/ahoy/issues/1823
