### ISSUE TITLE
[Bug] Fehler in radio statistics?

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1382]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.6.1

### Github Hash

???

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Radio-Statistic

### Error description

hat sich in den Radio Statistics wieder ein Fehler eingeschlichen? die Summe der Rx ergeben keine 100% mehr

**Comment by Gubi2023** [comment]
hat sich in den Radio Statistics wieder ein Fehler eingeschlichen? die Summe der Rx ergeben keine 100% mehr
![grafik](https://github.com/lumapu/ahoy/assets/142897856/f8f4b51c-895a-4aa0-8b75-dea18961a9af)

**Comment by lumapu** [comment]
kam durch eine Änderung rein und wurde jetzt gefixt.
