### ISSUE TITLE
Ahoy DTU number of Inverters more that 4 

### ISSUE THREAD

**Issue by UVILG** [lumapu/ahoy#1386]
Hallo, 
Ich habe 6 Hoymiles HM Inverter am laufen. Diese wurden bisher mittels einer DTU auf Basis der Version 0.5.66 ausgelesen. 
Nun habe jetzt eine neue DTU aufgesetzt und Version 0.8.36 benutzt. Diese lässt jedoch nur 4 Inverter (default) zu. 
Wie kann ich die Config ändern bzw. gibt es ein fertiges file dazu wo die Anzahl der Inverter nicht begrenzt ist ? 
Vielen Dank 
## Hardware
  * [X ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [X nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [X ] external antenna (SMA)

### Power Stabilization:
* [X ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.36__
Github Hash: _______

### Build & Flash Method:
* [X ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Dirk-Ahoy** [comment]
Du musst einen ESP32 nehmen der langsame ESP8266 unterstüzt nur noch 4

**Comment by UVILG** [comment]
> Du musst einen ESP32 nehmen der langsame ESP8266 unterstüzt nur noch 4

Ok vielen Dank

**Comment by MetaChuh** [comment]
@UVILG 

wenn du selber kompiliertst, kannst du in `src/config/config.h` für den esp8266 folgende parameter ändern, um die erlaubte inverterzahl zu erhöhen:
` #define MAX_NUM_INVERTERS   4` auf 8 oder mehr setzen.

auszug aus der config.h:

```
// number of configurable inverters
#if defined(ESP32)
    #if defined(CONFIG_IDF_TARGET_ESP32S3)
        #define MAX_NUM_INVERTERS   32
    #else
        #define MAX_NUM_INVERTERS   16
    #endif
#else
    #define MAX_NUM_INVERTERS   4
#endif
```

wenn nicht, dann auf die version 0.6.x downgraden, die dieses limit noch nicht hatten und als stabil gelten.
(0.6.0-0.6.9)

info: das limit wurde für esp8266 auf 4 inverter aus stabilitätsgründen fixiert, da die neueren ahoy dtu versionen viel mehr speicherlast haben, und auf dem esp8266 dadurch mehr ungewollte reboots verursachten.

**Comment by UVILG** [comment]
> @UVILG
> 
> wenn du selber kompiliertst, kannst du in `src/config/config.h` für den esp8266 folgende parameter ändern, um die erlaubte inverterzahl zu erhöhen: ` #define MAX_NUM_INVERTERS 4` auf 8 oder mehr setzen.
> 
> auszug aus der config.h:
> 
> ```
> // number of configurable inverters
> #if defined(ESP32)
>     #if defined(CONFIG_IDF_TARGET_ESP32S3)
>         #define MAX_NUM_INVERTERS   32
>     #else
>         #define MAX_NUM_INVERTERS   16
>     #endif
> #else
>     #define MAX_NUM_INVERTERS   4
> #endif
> ```
> 
> wenn nicht, dann auf die version 0.6.x downgraden, die dieses limit noch nicht hatten und als stabil gelten. (0.6.0-0.6.9)
> 
> info: das limit wurde für esp8266 auf 4 inverter aus stabilitätsgründen fixiert, da die neueren ahoy dtu versionen viel mehr speicherlast haben, und auf dem esp8266 dadurch mehr ungewollte reboots verursachten.

Top ! Vielen Dank
