### ISSUE TITLE
Falsche Anzeige auf Display

### ISSUE THREAD

**Issue by Edibo63** [lumapu/ahoy#1389]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.64

### Github Hash

?

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

update auf 0.8.64

### Error description

In der Anzeige im epaper  steht WIFI not connected.
Es funktioniert aber alles.

**Comment by Edibo63** [comment]
Korrektur:  ist ein ESP32

**Comment by knickohr** [comment]
Kann ich nicht bestätigen 😲

**Comment by Edibo63** [comment]
Stand den ganzen Tag auf not connected, war aber verbunden und Zugriff möglich.
Reboot zeigte keine Änderung.
Update nochmal gemacht danach kurz Stromversorgung weg.
Jetzt zeigt es wieder die IP an.
