### ISSUE TITLE
Das subscribe in der Reconnect Procedure sollte doch nur nach einem conect ausgeführt werden und nicht bei jedem Duchlauf

### ISSUE THREAD

**Issue by HorstG-57** [lumapu/ahoy#139]
Das subscriebe wird bei jedem MQTT Connect check ausgeführt.
Es müsste aber nur nach einem Connect ausgeführt werden.

Habe ein PR #138 erstellt in dem ich das angepasst habe.

**Comment by aschiffler** [comment]
Wurde eingepflegt.

**Comment by stefan123t** [comment]
Laut Hinweis in #176 noch nicht hinreichend behoben. Bitte weitere Änderungen als PR gegen development. Danke!

**Comment by aschiffler** [comment]
merged the "mqttfix" from @tastendruecker123 PR #179
