### ISSUE TITLE
V0.8.68: "Einstellungen" nur in englisch

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1393]
Ich habe V0.8.68  in deutsch geladen. Bei "Einstellungen" wird die Seite incl. Unterseiten nur auf englisch angezeigt

**Comment by mtet2** [comment]
Kann ich beim ESP8266 nicht bestätigen.
Mischt sich vielleicht der Browsercash ein?

**Comment by Gubi2023** [comment]
scheint so... habs grad mit anderem PC versucht, da geht es...

**Comment by lumapu** [comment]
STRG + F5 ist dein Freund, damit kannst du den Cache umgehen
