### ISSUE TITLE
[Bug] Inverter lassen sich nicht mehr per DTU über API/MQTT/Live wieder einschalten oder neu starten

### ISSUE THREAD

**Issue by blueline13** [lumapu/ahoy#1397]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.70

### Github Hash

*

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

*

### Error description

1) Abschalten des Inverter per API/MQTT/Live
2) Inverter kann nun nicht mehr per DTU neu gestartet oder eingeschaltet werden. Bei der Live Ansicht kommt der Hinweis das der Inverter keine Kommandos mehr annimt. Auch bei MQTT und API reagiert er nicht mehr.
3) Zurück auf die 0.8.68, schon läuft es wieder.

Kann es sein das es eine Folge von dem hier ist : "prevent sending commands to inverter which isn't active #1387" was in der 0.8.70 eingebaut wurde. Das würde ja bedeuten, dass alle Inverter die mit Batterie betrieben werden keine Chance mehr haben den Inverter Abends einzuschalten.

**Comment by lumapu** [comment]
ok, da habe ich wohl einen Denkfehler drin, da auf den Status produzierend geprüft wird, was ja im abgeschalteten Zustand nie zutreffen kann.
Der Status muss auf available geprüft werden, dann sollte es mAn. wieder funktionieren. Fix kommt bald 😉

**Comment by lumapu** [comment]
bitte mit `0.8.71` nochmal testen

**Comment by blueline13** [comment]
Ich habe das eben probiert mit der 0.8.71. Leider keine Änderung. Wenn ich den Inverter per LIVE ausschalte, dann versuche ihn wieder einzuschalten, kommt die Meldung "Fehler: Leistungsbegrenzung / Ansteuerung aktuell nicht möglich" Also keine Veränderung zur 0.8.70. Auch API und MQTT gehen dann nicht um ihn wieder einzuschalten.

**Comment by lumapu** [comment]
Fehler kann ich jetzt nachvollziehen, (auch weil es gerade Tag ist 😇). Behebung kommt in der nächsten Version.

**Comment by blueline13** [comment]
Ja die 0.8.72 läuft wieder .... DANKE !!!!
