### ISSUE TITLE
kann ESP32 nicht flashen  HM-1500 ist noch nicht verfügbar

### ISSUE THREAD

**Issue by nom56** [lumapu/ahoy#1399]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Peertje-62** [comment]
Hi there, is not much info to go on!
try : 
https://github.com/esphome/esphome-flasher/releases/tag/1.4.0
ore ;
https://3printd-solution.eu/Ahoy-openDTU-Fusion-fuer-HM-HMS-HMT-mit-Display
regards

**Comment by nom56** [comment]
HM-1500 ist noch nicht verfügbar. AhoyDtu immer offline

**Comment by nom56** [comment]
HM-1500 ist noch nicht verfügbar
