### ISSUE TITLE
com loop duration

### ISSUE THREAD

**Issue by sommer05** [lumapu/ahoy#1405]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.3.6

### Github Hash

??wo finde ich den

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

kein mqtt

### Debug Serial Log output

```shell
18:29:40.577 -----
18:29:40.577 I: com loop duration: 503ms
18:29:40.578 -----
18:29:50.576 -----
18:29:50.576 I: com loop duration: 502ms
18:29:50.577 -----
```

### Error description

ich habe jetzt 3 verschiedene boards mit ver 0.8.36 probiert (esp32, esp8266 D1 mini, esp8266 lolin) bei allen dreien läuft 0.7.36 problemlos , sobald ich mit denselben settings auf 0.8.xx update bekomme ich bei allen dreien diese meldung im log und nichts wird in der live ansicht mehr angezeigt. hab mich schon durchgegoogelt aber nicht wirklich was dazu gefunden, vielleicht kann mir ja jemand helfen, wahrscheinlich nur eine kleinigkeit für euch für mich aber....
danke im voraus

**Comment by knickohr** [comment]
Den Inverter enabled ?

![IMG_1811](https://github.com/lumapu/ahoy/assets/63048210/be683353-98ed-4001-beb4-6d1d6d0310cf)

**Comment by sommer05** [comment]
ja danke ist natürlich enabled, habe echt alles schon 100* überprüft und finde keine lösung ...

**Comment by Joh49** [comment]
schon bei den Reitern Input und Radio nachgesehen, ob es was zu ergänzen gibt? 
Die Serialnummer neu eingeben vielleicht klemmt da was.

**Comment by blueline13** [comment]
Wie ist der Status vom NRF Modul unter System. ist da alles grün?

**Comment by sommer05** [comment]
> schon bei den Reitern Input und Radio nachgesehen, ob es was zu ergänzen gibt? Die Serialnummer neu eingeben vielleicht klemmt da was.

überprüft alles richtig

**Comment by sommer05** [comment]
> Wie ist der Status vom NRF Modul unter System. ist da alles grün?

ist grün und schreibt connected

**Comment by UVILG** [comment]
ich habe gestern die aktuellste Version aufgespielt. Nach der Verbindung bekomme ich die Meldung  I : com loop duration: 403ms
was war die Ursache bei dem auch hier beschriebenen  Problem ?
