### ISSUE TITLE
Sortierung der passwortgeschützten Begriffe in "Settings"

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1408]
es wäre schön, wenn die Begriffe in den Settings links und rechts die gleiche Reihenfolge hätte...
<img width="777" alt="Screenshot 2024-02-06 150049" src="https://github.com/lumapu/ahoy/assets/142897856/03380210-114d-40fc-bda6-00a4988eee2e">

**Comment by knickohr** [comment]
Habt ihr Sorgen !  😲🤪😉

**Comment by Gubi2023** [comment]
sind halt so die Kleinigkeiten fürs perfekte Design . Ansonsten seid ihr ja wirklich super !!!
 😲🤪😉

**Comment by knickohr** [comment]
Ja, ist doch OK. Ist halt historisch so gewachsen,

**Comment by lumapu** [comment]
ist nicht ohne weiteres möglich, da die Sortierung auf der Makse (Code im Hintergrund) basiert. Ich denke das werde ich nicht fixen, da es in unnötig größerem Code resultiert.

**Comment by Gubi2023** [comment]
ok, war nur Schönheit, wenn der Aufwand zu gross ist, kein Problem.
