### ISSUE TITLE
0.8.74 Falsche Anzeige Leistungsbegrenzung

### ISSUE THREAD

**Issue by elisenjens** [lumapu/ahoy#1409]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.74

### Github Hash

1f0b15c

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Standard

### Error description

Leistungsbegrenzung wird falsch angezeigt nach Update

**Comment by Gubi2023** [comment]
Duplikat zu #1406

**Comment by Gubi2023** [comment]
toll! obwohl ich immer noch die 8.74 drauf hab, ist die Anzeige wieder richtig (?)
