### ISSUE TITLE
[Bug] 0.8.76 : Suspect statement: using float as boolean

### ISSUE THREAD

**Issue by fsck-block** [lumapu/ahoy#1416]
In Methode `void app::updateNtp(void)` steht
```
   ...
    if ((mSunrise == 0) && (mConfig->sun.lat) && (mConfig->sun.lon)) {
   ...
```
Da `sun.lat` und `sun.long` als `float` deklariert sind ist diese Bedingung aus meiner Sicht etwas suspect.

**Comment by lumapu** [comment]
da gebe ich dir Recht, danke für den Hinweis
