### ISSUE TITLE
Beschriftung der Achsen im Gesamtverlauf

### ISSUE THREAD

**Issue by elisenjens** [lumapu/ahoy#1420]
## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.76_._.__
Github Hash: _______

### Build & Flash Method:
* [x ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

Ich würde es sehr hilfreich finden, wenn beide Achsen eine Beschriftung/Dimension hätten.

**Comment by Gubi2023** [comment]
https://github.com/lumapu/ahoy/pull/1336#issuecomment-1890441168
