### ISSUE TITLE
0.8.78 hängt sich im laufenden Betrieb auf

### ISSUE THREAD

**Issue by elisenjens** [lumapu/ahoy#1423]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.78

### Github Hash

c290273

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Standard ohne MQTT

### Error description

von Zeit zu Zeit (täglich) kann ich Ahoy per LAN nicht erreichen; nach Stecker raus/rein läuft sie wieder

**Comment by Gubi2023** [comment]
dito

**Comment by lumapu** [comment]
Leider kann man ohne Log an diesem Fehler wenig ausrichten, da ich ihn bis dato noch nicht gesehen habe. Gibt es ein Indiz wann es besonders häufig passiert?

**Comment by elisenjens** [comment]
Bei mir war das mehrmals täglich spontan; seit der .81 hab ich das nicht mehr (vlt. liegt es daran, dass ich jetzt komplett neu installiert habe und das ein Update-Problem war).
