### ISSUE TITLE
ESP32 und OLED - (Immer noch?) Reboots

### ISSUE THREAD

**Issue by HorstyS** [lumapu/ahoy#1424]
## Hardware
  * [] ESP8266
  * [X] ESP32
  * [ ] Raspberry Pi

Modelname: WROOM
Retailer URL: ______

### nRF24L01+ Module
* [X] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [X] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [X]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.79
Github Hash: _______

### Build & Flash Method:
* [X] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

hi,

ich bin leider etwas "raus" aus den ganzen issues, aber ich kann mich noch erinnern, dass es mal probleme gab mit ständigen reboots. ich habe das verhalten bei einer meiner beiden ESP32 DTUs auch, allerdings erst seit einer 0.8.7x version. wenn daten vom inverster ankommen ist alles tutti, so wie ich das sehe, und sie läuft stabil. nachdem dann aber der inverter abends keine daten mehr sendet fängt sie an ständig zu rebooten. mal alle paar sekunden, mal hält sie ein paar stunden in der nacht durch und fängt wieder an. das OLED display scheint sich wohl auch nicht mehr auszuschalten. ich habe aktuell keine entsprechenden logs dazu, kann diese aber vermutlich morgen nachreichen, wenn notwendig.
ist das thema (noch) bekannt und offen? liegt das am display?
ich bin mal zurück auf die 0.8.56 und dort tritt das problem nicht auf.
die zweite DTU läuft übrigens auch mit der 0.8.56 und einem ePaper. die lasse ich auch erst mal so, damit ich über MQTT die daten weiterhin bekomme ;)

**Comment by You69Man** [comment]
Ich betreibe auch eine Kombination aus ESP32 Wroom, OLED, PIR, MQTT mit aktuellster FW und kann nur sagen, dass ich schon lange keine Boot Probleme hatte. Ein 'Einfrieren' oder Nicht-Abschalten des Displays hätte ich auch noch nie festgestellt.  Kannst du mal ein paar Screenshots deiner Settings posten, vielleicht sehen wir da ja etwas.

**Comment by HorstyS** [comment]
Klaro :)

![Bildschirmfoto vom 2024-02-12 14-00-05](https://github.com/lumapu/ahoy/assets/101665247/80f3e5d0-e53c-482b-985e-8e32f00d0922)
![Bildschirmfoto vom 2024-02-12 13-59-49](https://github.com/lumapu/ahoy/assets/101665247/20d22202-44da-4ae1-b52a-712794f20aa8)
![Bildschirmfoto vom 2024-02-12 13-59-40](https://github.com/lumapu/ahoy/assets/101665247/95f729b6-80ce-407e-9b19-f267359d05cc)
![Bildschirmfoto vom 2024-02-12 13-59-32](https://github.com/lumapu/ahoy/assets/101665247/ed4a0862-843f-4799-9442-f9c4363090e9)
![Bildschirmfoto vom 2024-02-12 13-59-20](https://github.com/lumapu/ahoy/assets/101665247/5da78ee9-bdb9-4265-a542-7041b365ba33)
![Bildschirmfoto vom 2024-02-12 13-59-08](https://github.com/lumapu/ahoy/assets/101665247/07623ed4-4efe-4d87-88e0-7084e896b652)
![Bildschirmfoto vom 2024-02-12 13-58-58](https://github.com/lumapu/ahoy/assets/101665247/c7a3f944-2f80-4639-a94b-06e1e585a662)
![Bildschirmfoto vom 2024-02-12 13-58-34](https://github.com/lumapu/ahoy/assets/101665247/9f8f363c-0d6c-4190-b817-9d158c03c59b)
![Bildschirmfoto vom 2024-02-12 13-58-27](https://github.com/lumapu/ahoy/assets/101665247/374548a2-ef77-4054-b688-960390212135)
![Bildschirmfoto vom 2024-02-12 13-58-09](https://github.com/lumapu/ahoy/assets/101665247/412905b2-e7f5-495a-85f3-3423815f0759)
![Bildschirmfoto vom 2024-02-12 13-57-56](https://github.com/lumapu/ahoy/assets/101665247/e2a4e5a8-6a29-48dd-8565-a8f4de15b071)

**Comment by HorstyS** [comment]
![Bildschirmfoto vom 2024-02-12 13-57-33](https://github.com/lumapu/ahoy/assets/101665247/d15e21ce-60df-433e-a6be-cbdeacd02fe2)

**Comment by You69Man** [comment]
Ich habe jetzt deine Einstellungen mit meinen verglichen.

Hier aktuelle Einstellungen bei mir, die anders sind, als bei dir:
* Display: "Turn off while inverters are offline" : Aus
* Display / Screensaver: Motion
* Inverter / Advanced: "Pause communication during night (lat. and lon. need to be set)" :  Aus
* Inverter : "Reset values and YieldDay at midnight." : Aus
* Inverter / Interval: 5s
* MQTT : An

Bei allen anderen Einstellungen die auch noch unterschiedlich sind, kann ich mir beim besten Willen nicht vorstellen, dass sie hier einen Einfluss haben könnten.

Ich stelle jetzt einmal für einen Tag lang meine Einstellungen auf deine um, und schaue, ob es irgendwelche Reboots oder Display Effekte gibt!

**Comment by You69Man** [comment]
PS: Übrigens, ich verwende doch kein Wroom32 Board, wie oben von mir behauptet, sondern ein Wemos D1 Mini ESP32 Board, allerdings mit dem Wroom32 firmware target.
Außerdem habe das Display auf den GPIO Pins 13 und 14 angeschlossen, nicht auf 21 und 22 wie bei dir. Das sollte hier aber auch keinen Unterschied machen (der ESP32 multiplext die I2C intern auf 'beliebige' Pins).

**Comment by HorstyS** [comment]
ich hatte zwischen ca. 17:15 uhr gestern und heute ca 7:30 uhr nur zwei reboots. jeweils um diese uhrzeit. das display war (zumindest bis ich ins bett gegangen bin und aufgestanden bin) aus.
mal schauen wie es sich nun unter tags verhält.
mal eine frage: wenn ich ein update über das UI anstoße, wird vermutlich nur ein in place update gemacht? gibt es denn eine möglichkeit über das UI ein full update inkl. dem vorherigen kompletten löschen des geräts so wie über die DTU website im internet? vielleicht würde das einige solcher probleme beheben? oder ist hierfür generell die seite im netz zu nutzen?

**Comment by You69Man** [comment]
Meine DTU läuft nun seit >24 Std mit deinen Einstellungen ohne einen einzigen Reboot durch. Auch das Display hat sich über Nacht brav ausgeschaltet und morgens wieder ein. Daran liegt es also wohl nicht.

Zur Info noch: Unabhängig von den Einstellungen schaltet sich das Display nach Power on oder nach einem Reboot immer für 60 Sekunden ein. Wenn du also in einer schnellen Reboot Schleife hängst, kann es sein, dass es deshalb nie ausschaltet. Das müsstest du dann aber daran sehen, dass immer wieder einmal der Startscreen erscheint.

Was du jetzt noch probieren könntest wäre einmal deine Settings komplett zu löschen und alles neu zu konfigurieren. Vielleicht versteckt sich irgendwo noch ein verwaister Parameter aus einer alten Firmwareversion und macht irgendeinen Unfug.

**Comment by HorstyS** [comment]
meine DTU hat sich seit gestern Abend wieder sehr oft gebootet. heute morgen eigentlich immer im minutentakt. seit der inverter wieder nun seit ein paar minuten wieder liefert ist die DTU stabil. und ja, der startscreen kommt dann immer wieder ;)

ich habe auch die vermutung, dass es an irgend einem (obsoleten, falschen, ...) flag o.ä. liegt der durch ein update das ganze verursacht. vermutlich würde sich das verhalten durch einen wipe und einer neuinstallation einer aktuellen DEV version beheben lassen, aber die frage ist ob es für die entwicklung wichtig ist herauszufinden was/warum das verhalten so auftritt.

**Comment by You69Man** [comment]
Nützlich  zur Fehlersuche wäre noch ein logfile das während des rebootens aufgezeichnet wurde. Wenn du ein häufiges Rebooten hast , sollte das einfach einzufangen sein. Entweder mit dem Weblog oder mit USB Serieller und Putty.

**Comment by dtuuser** [comment]
Bei mir, ESP32 mit ssd1306 Display, keine automatischen Reboots. Update seit Version 7 immer über Download der englischen Datei aus fw.ahoy.....  und Einspielen über die Updateseite in Ahoy. Falls das mal nicht einggespielt wird, dann muss ich vorher manuell per Web rebooten,  aber zu 90% läuft das Update durch.

Nochmals an die Programmierer..... Klasse Arbeit

**Comment by HorstyS** [comment]
> Nützlich zur Fehlersuche wäre noch ein logfile das während des rebootens aufgezeichnet wurde. Wenn du ein häufiges Rebooten hast , sollte das einfach einzufangen sein. Entweder mit dem Weblog oder mit USB Serieller und Putty.

sie läuft nun seit gut 6,5 stunden ohne reboot, und ich denke, dass sie bald anfangen wird die kommunikation mit dem inverter wieder aufzunehmen.
mit weblog meinst du die webconsole im UI? und mit USB Serieller was? die DTU am rechner anstecken und dann per putty darauf zugreifen? oder kann man den SSH zugang irgendwie aktivieren und dann per WLAN darauf zugreifen?

**Comment by You69Man** [comment]
> mit weblog meinst du die webconsole im UI? 

Ja genau. Dort dann einfach mit dem Copy Button rauskopieren.

>und mit USB Serieller was? 

die DTU am rechner anstecken und dann per putty darauf zugreifen? 
Ja das wäre die zweite Möglichkeit

>oder kann man den SSH zugang irgendwie aktivieren und dann per WLAN darauf zugreifen? 

SSH Zugang zur DTU ist mir nicht bekannt

**Comment by HorstyS** [comment]
da steht leider nichts spannendes drin. wenn die DTU neu bootet sieht man das nur am zeitversatz des abfragerhythmus (bei mir 15 sek.):

17:08:41.000 I: (#0) no communication to the inverter (night time)
17:08:56.000 I: (#0) no communication to the inverter (night time)
17:09:11.000 I: (#0) no communication to the inverter (night time)
17:09:26.000 I: (#0) no communication to the inverter (night time)
17:09:41.040 I: (#0) no communication to the inverter (night time)
17:09:56.000 I: (#0) no communication to the inverter (night time)
17:10:48.000 I: (#0) no communication to the inverter (night time)
17:11:03.000 I: (#0) no communication to the inverter (night time)
17:11:18.040 I: (#0) no communication to the inverter (night time)
17:11:33.000 I: (#0) no communication to the inverter (night time)
17:11:48.000 I: (#0) no communication to the inverter (night time)

wenn ich sonst nichts spannendes mehr liefern kann würde ich meine DTU einfach mal platt machen und mit einer aktuellen DEV version beglücken. vermutlich ist das verhalten dann auch nicht mehr reproduzierbar.

**Comment by You69Man** [comment]
> da steht leider nichts spannendes drin. wenn die DTU neu bootet sieht man das nur am zeitversatz des abfragerhythmus (bei mir 15 sek.):

Der Log ist vermutlich vom Webserial. Kannst du bitte auch ein Log von der USB seriellen liefert? Dort würde man sicherlich wesentlich mehr sehen.

**Comment by HorstyS** [comment]
> Der Log ist vermutlich vom Webserial. Kannst du bitte auch ein Log von der USB seriellen liefert? Dort würde man sicherlich wesentlich mehr sehen.

korrekt.
wie ist hier die vorgehensweise? am pc anstecken, laufen lassen und wenn er abends neu bootet das log ziehen? oder bleibt das log auch erhalten wenn die DTU stromlos war und neu gestartet wird?

**Comment by You69Man** [comment]
> > Der Log ist vermutlich vom Webserial. Kannst du bitte auch ein Log von der USB seriellen liefert? Dort würde man sicherlich wesentlich mehr sehen.
> 
> korrekt.
> wie ist hier die vorgehensweise? am pc anstecken, laufen lassen und wenn er abends neu bootet das log ziehen? oder bleibt das log auch erhalten wenn die DTU stromlos war und neu gestartet wird?

Am besten dann, wenn du die häufigen reboots siehst (Abends?) einmal mit einem seriellen Terminal (z B. PuTTY) auf die COM der Ahoy verbinden (115200 Baud). Wenn du dann den Reboot siehst, den Log mit Copy Paste rauskopieren.

**Comment by HorstyS** [comment]
also, folgendes habe ich beobachtet:
wenn ich die DTU an ihrem üblichen ort mit ihrer aktuellen stromversorgung habe fängt sie am abend irgendwann an immer wieder selbstständig zu booten.
wenn ich sie an meinen PC hänge passiert das nicht. im putty steht dem entsprechend natürlich nichts spannendes (no communication...night time). es könnte evtl. an der spannungsversorgung liegen....aber wieso passiert das dann nicht mit einer 0.8.56?!....
ich habe jetzt mal auf die aktuelle DEV version upgedated und beobachte das heute abend mal. wenn es damit wieder auftritt würde ich mir mal die stromversorgung vornehmen.

**Comment by lumapu** [comment]
bleibt spannend, wenn es mit 0.8.56 ging und jetzt wegen einem Mehrverbrauch (den ich mir erstmal nicht erklären kann) nicht mehr gehen soll, dann war es schon immer sehr kitzlig.

**Comment by HorstyS** [comment]
latest news zu dem thema:
ich habe gestern auf die 0.8.83 via UI upgedated und die DTU läuft nun seit fast 24 Stunden wieder stabil ohne neustart. die stromversorgung und der aufstellort ist der selbe wo ich zuvor die probleme hatte.
keine ahnung was das nun gewesen sein kann.
wenn ihr wollt kann ich diesen issue schließen...oder jemand anderes :)

**Comment by HorstyS** [comment]
ahhhhhh.......zu früh gefreut. nachdem ich den letzten post abgesetzt habe hat die DTU wieder angefangen neu zu booten. :(
ich denke ich werde sie mal komplett platt machen und ein frisches bin-file hochladen...

**Comment by HorstyS** [comment]
so, ich habe dann gestern mittag den wipe und die neuinstallation durchgeführt. die einstellungen habe ich per hand vorgenommen. ich bin auch bei der aktuellen stable version geblieben. seitdem kein neustart über nacht. aktuell produziert der inverter und die daten kommen an.
was auch immer das problem verursacht hat scheint nun wieder verschwunden zu sein.
ich schließe damit meinen post.
