### ISSUE TITLE
ESP8266 - Nach Update von 0.8.36 auf 0.8.83 leuchtet die blaue LED dauerhaft !?

### ISSUE THREAD

**Issue by mroenne2022** [lumapu/ahoy#1435]
## Hardware
  * [ X] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

### nRF24L01+ Module
* [X] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ X] circuit board
* [ X] external antenna (SMA)

Bei meinen beiden ESP8266 leuchtet nach dem Update von 0.8.36 auf 0.8.83 die blaue LED dauerhaft. Zuvor war das nicht der Fall , lediglich immer kurz zum Zeitpunkt des Sendens hat sie kurz "aufgeblinkt" ! Kann man das ggf. abstellen ? Auf den ersten Blick hab ich da nichts gefunden !

**Comment by lumapu** [comment]
Das liegt daran, dass die blaue LED beim ESP8266 am Pin D4 hängt.
In unserer Standardkonfiguration ist dieser mit dem IRQ des NRF24 verbunden und dürfte daher nur kurz blinken.
Geändert haben wir das Verhalten von dem Pin CE des NRF24, dort liegt nun die meiste Zeit ein high Pegel an.
Ich nehme an, dass in deiner Hardware an Pin D4 des ESP der CE Pin des NRF24 hängt. Ist das der Fall, dann benötigst du nur einen Lötkolben um die Pins D3 und D4 zu tauschen. Danach nicht vergessen gleiches auch in der Konfiguration von Ahoy zu tauschen.

**Comment by mroenne2022** [comment]
@lumapu 
Das war offensichtlich die Lösung. Eine DTU war mit Steckverbindung, deshalb konnte ich mal eben tauschen (in der Software/Konfig ebenfalls getauscht). LED nun aus 👍 Ich geh davon aus das die DTU morgen weiterhin Daten liefert.  Vielen Dank für Info und Erklärung 😀

**Comment by lumapu** [comment]
ja hoffen wir dass, morgen wissen wir mehr. Danke für's Feedback

**Comment by mroenne2022** [comment]
@lumapu 
DTU läuft prima wie zuvor, blaue LED bleibt aus. 
Alles bestens, nochmals vielen Dank 👌
Dann können wir hier schließen denk ich.

**Comment by DB1BMN-collection** [comment]
Guten Morgen,

 ja, das dauerhafte Leuchten der blauen LED auf dem 8266 habe ich auch bemerkt in der letzten Beta 0.8.82 und beim Release 0.8.83. Hatte aber die Vermutung, dass es an den häufigen Abstürzen wegen der Diagramme liegt und habe wieder auf die 0.8.36 downgegradet, siehe #1436 

Beim ESP8266 ist es ja so, dass die blaue LED an IO02/D4 gegen GND gezogen wird, damit sie leuchtet.

In den vorherigen Versionen bis 0.8.36 war sie ja dauerhaft aus, d.h. D4 und somit Chip-Enable lagen dauerhaft auf High.

Gibt es einen triftigen Grund (außer Stromsparen?), dass man jetzt D4/CE dauerhaft auf Low legt und nur kurz zum Kommunizieren den nRF enabled?

Sorry, ich habe das Projekt längere Zeit nicht verfolgt, bin aber beeindruckt von den neuen Funktionen *thumbsup*, weiter so!

**Comment by lumapu** [comment]
Das hat nur technische Gründe, bzgl. Strom sparen haben wir Module die Richtung Sonne schauen 😉.

**Comment by fila612** [comment]
@lumapu: was würde passieren wenn die Pins nicht so einfach geändert werden können, weil z.B. die Platine das nicht hergibt? Hat dies technische Auswirkungen oder leuchtet einfach nur die LED dauerhaft? ich habe aktuell den CE an D4 und kann nur den IRQ zwischen D1/D2/D3 wählen, da es hier in der Vergangenheit immer Probleme mit diversen ESPs gab, habe ich einen Jumper eingebaut - bei CE aber nicht :(

**Comment by lumapu** [comment]
die LED leuchtet halt, nichts weiter. Man muss es nicht ändern, deswegen habe ich versucht Ahoy so flexibel wie möglich zu halten und alle Pins frei konfigurierbar zu machen. Der eine ESP kann's besser der andere nicht.

**Comment by You69Man** [comment]
Ein schwarzer Edding Stift könnte Abhilfe schaffen ;-)

**Comment by DB1BMN-collection** [comment]
Ja, das mit dem Edding steht sogar schon in meiner Anleitung drinne ;-)

Hm, könnte man denn nicht den Idle-Zustand des CE-Pinis in Software konfigurierbar machen?
Und erst wenn eine Kommunikation stattfindet dann den gewünschten Zustand annehmen und ggf. eine Seutup-Time abwarten, bevor man den /CS runterzieht? - Mit nem Radio-Button oder so ließe sich das doch leicht umschalten, oder?

Oder nimmt es das nRF-Modul übel, wenn man ständig an seinem CE wackelt?

**Comment by LeSpocky** [comment]
Ich hab auch einen 8266 aka D1 mini mit blauer LED an D4 und CE dran. Tagsüber verhält sich das wie zuvor mit der version 0.7, es blinkt nur kurz beim Senden/Empfangen mal auf und ist die meiste Zeit dazwischen aus. Nachts leuchtet die LED aber dauerhaft und das nervt eher. Wie wäre denn das Verhalten nach dem Tauschen von D2 mit D4? Wie würde es dann leuchten und blinken tags und nachts?

**Comment by mroenne2022** [comment]
@LeSpocky 
Nach dem Tausch blinkt die blaue LED nur immer 1x ganz kurz auf wenn Daten abgefragt/gesendet werden, ansonsten ist sie aus. So war es vor dem Tausch bei den vorherigen Versionen auch.
Allerdings hab ich D3 und D4 getauscht,  nicht D2 !! Das ist auch jetzt am Abend so.
