### ISSUE TITLE
Schreibfehler in der deutschen Übersetzung

### ISSUE THREAD

**Issue by QuickStopGroceries** [lumapu/ahoy#1442]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.8.3

### Github Hash

5ebfe5a

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

..

### Error description

Bitte dem Wort "deaktiviert" noch das zweite i spendieren. :)
![Bildschirmfoto 2024-02-20 um 07 41 00](https://github.com/lumapu/ahoy/assets/122892891/ef946fd6-129a-4187-9f85-9c24c011a4b6)

**Comment by Gubi2023** [comment]
Webserial auf deutsch: "Days"  mit Absicht nicht übersetzt?

![2024-02-20 17_11_36-Web Konsole – Mozilla Firefox](https://github.com/lumapu/ahoy/assets/142897856/8246e258-3285-4f24-899a-ea50e6c4cc76)

**Comment by lumapu** [comment]
wir übersetzen alles @Gubi2023 😅. Danke für die Hinweise

**Comment by Gubi2023** [comment]
8.85: gefixt "Tage"

**Comment by Gubi2023** [comment]
> wir übersetzen alles @Gubi2023 😅. Danke für die Hinweise

![grafik](https://github.com/lumapu/ahoy/assets/142897856/40ca08f9-fb13-4ae2-b015-c5f8bcaec44d)
 Lässt sich das auch übersetzen, oder ist das ne andere Baustelle??

**Comment by MetaChuh** [comment]
@Gubi2023 

richtige baustelle.
ist derzeit hardgecoded in `web/html/serial.html`
hat wahrscheinlich niemand bemerkt, weil man's erst nach action button klicken sieht.

```js
 80                   try {
 81                       return document.execCommand("copy");  // Security exception may be thrown by some browsers.
 82                   } catch (ex) {
 83                       alert("Copy to clipboard failed" + ex);
 84                   } finally {
 85                       document.body.removeChild(ta);
 86                       alert("Copied to clipboard");
 87                   }
```

**Comment by Gubi2023** [comment]
<img width="416" alt="Screenshot 2024-02-24 154519" src="https://github.com/lumapu/ahoy/assets/142897856/d55c4826-97db-44e7-a24d-a466c200165f">


danke!

**Comment by Gubi2023** [comment]
bei der Kopierfunktion wurde eine Abfrage eingebaut  "weitere Abfragen ... verbieten. Klicke ich diese an, wir trotzdem weiterhin im Kopf die Vers.Nr  eingetragen. Siehe Video; Ist das so gedacht?



https://github.com/lumapu/ahoy/assets/142897856/fa0e6703-4ef8-4701-9111-68dcc91f1a93

**Comment by Gubi2023** [comment]
ausserdem ist der Text auch in der englischen Version auf deutsch  
<img width="381" alt="Screenshot 2024-03-01 000727" src="https://github.com/lumapu/ahoy/assets/142897856/3ab22770-89e2-422a-8014-f8ab1df5cb86">

**Comment by MetaChuh** [comment]
hi @Gubi2023 

danke für's video, das erleichtert vieles 👍

dies kommt nicht von ahoydtu.

`Weitere Aufforderungen von [URL] verbieten` ist keine funktion in ahoydtu, sondern entweder eine browserfunktion eines browsers den ich nicht kenne, oder ein plugin (js oder werbeblocker plugin) in einem browser.
diese generieren den text selbst, und wählen die localization sprache anhand deiner browser spracheinstellung.

standard ansicht in chromium/chrome, egal wie oft man auf kopieren klickt:

<img width="544" alt="Bildschirmfoto 2024-03-01 um 00 30 42" src="https://github.com/lumapu/ahoy/assets/45773305/504781f6-9798-4d87-8dbc-6e71215edfce">

standard ansicht in safari, egal wie oft man auf kopieren klickt:

<img width="545" alt="Bildschirmfoto 2024-03-01 um 00 30 04" src="https://github.com/lumapu/ahoy/assets/45773305/5f5e49de-bd8e-46ff-ba15-b062d2d35be0">

probier mal einen anderen browser den du hast, der keine plugins installiert hat, und klicke dann öfters auf kopieren.

**Comment by Gubi2023** [comment]
ok, du hast recht. Mein Standardbrowser ist Firefox, da kommt diese Meldung. Bei Chrome kommt sie nicht.

**Comment by MetaChuh** [comment]
@QuickStopGroceries 

dein anliegen wurde bereits in v0.8.85 mit dem fehlenden i in `Wechselrichterabfrage deaktiviert (Nacht)` gefixed.
darum bitte dieses issue selbständig schließen.
danke dir.
