### ISSUE TITLE
Bei API Leistungssteuerung erhalte ich seit 0.8.80 Werte über 100% in der Anzeige

### ISSUE THREAD

**Issue by jimknopf63** [lumapu/ahoy#1444]
## Hardware
  * [ ] ESP8266
  * [ X] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [X ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ X] external antenna (SMA)

### Power Stabilization:
* [ X]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.80
Github Hash: _______

### Build & Flash Method:
* [X ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Ich arbeite mit der Nulleinspeisung von reserve85  (V1.66). Ab der Version 0.8.80 zeigt mir Ahoy teilweise utopische Leistungswerte in der Übersicht (u.a. zwischen 100-180% entsprechende Wattzahl) Im Log von der Nulleinspeisung von reverse85
stehen aber die realistischen Leistungswerte die übertrage werden. Ist das jetzt ein Ahoy Problem oder eins der Nulleinspeisung?

**Comment by tester277** [comment]
Hallo jimknopf,
das ist ein Konfigurationsproblem Deiner Nulleinspeisung.
Vergleiche mal die Reihenfolge der Inverter und die Max Werte (HOY_MAX_WATT =  ) in Deiner Konfiguration mit der Reihenfolge in Ahoy. Wenn Du auf der neuen Ahoy Version bist, mußt Du auch die Nulleinspeisung auf 1.77 updaten.

**Comment by MetaChuh** [comment]
@jimknopf63 

für ahoy dtu v0.8.80 brauchst du mindestens zeroexport v1.75, da es ahoy dtu api änderungen gab.

ich empfehle höher upzudaten, z.b. ahoy v0.8.83 und [zeroexport v1.77](https://github.com/reserve85/HoymilesZeroExport/blob/main/CHANGELOG.md)

**Comment by reserve85** [comment]
So ist es, @jimknopf63 du musst sowohl AHOY als auch das Script aktualisieren, dann gehts wieeder. 
Es sind die letzten Wochen mehrere API-Changes aufgekommen (u.A. wurde der Faktor entfernt was bei dir das Problem ist).

**Comment by MetaChuh** [comment]
@jimknopf63 

freut uns, dass du's mit den gegebenen informationen deine anfragen lösen konntest 👍
und danke für's selbständig, unaufgeforderte schließen der issue 🙏👍

(für semi off topic leser: warum das danke ?:
manche user informieren in privaten open source projekten leider nicht, wenn ihre probleme gelöst sind, da sie für sie selbst gelöst sind, und deshalb nicht mehr privat wichtig, was massiv offene community issues in kleineren projekten hinterlässt, obwohl die grundfragen und funktionalität des original issues abgedeckt wurden)

sharing is caring as you did, it's much appreciated at all open source communities 🙏❤️

hugs and greetings,
MetaChuh
