### ISSUE TITLE
Radio statistics for Inverter

### ISSUE THREAD

**Issue by technics42** [lumapu/ahoy#1447]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.84

### Github Hash

f500999

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Inverter intervall set to 15 sec.

### Error description

Radio statistics for inverter are showing something like this:
Inverter loss rate	lost 65526 of 11 	595690.91 %
DTU loss rate	lost 30 of 61 	49.18 %

What is the meaning of those values?
The first one surely is wrong, regardless of the meaning.

**Comment by rejoe2** [comment]
Most likely you have a second DTU running, when Inverter loss rate gets negative (or to high, which in this case is the same)?

The inverter responds back how many requests he received and how many messages have been sent. Then this will be compared with the counts from the AhoyDTU. If the inverter has more sents than requests from DTU side (to be precise: from all DTU's, the first comparison will turn to "negative" (it's calculated as uint16_t variable...)

**Comment by technics42** [comment]
Ok, this will be the reason.
I always update new version to a second HW and keep it running some time in parallel to the prior version.

So, first value is loss-rate reported by inverter and second one is loss-rate reported by DTU itself.

**Comment by rejoe2** [comment]
> So, first value is loss-rate reported by inverter and second one is loss-rate reported by DTU itself.

Not exactly. The inverter sends two values, (received and send), which then are compared with what AhoyDTU has counted as send and received... So it's always both sides compared in the loss rates.

**Comment by technics42** [comment]
So how exactly are "inverter loss-rate" and "DTU loss-rate" calculated? If the first one is using values from inverter and DTU, this will also be wrong on any restart of DTU, or?
(I really want to understand those values)

**Comment by rejoe2** [comment]
For details see parseGetLossRate() in Communication.h. Ahoy requests last values from inverter first and uses that as base. So no real problem with restarts...

**Comment by technics42** [comment]
Ah, all those losses are calculated by using inverter values and not only getting the values from only the named system.

So, it's always the "receiver's" loss-rate:
inv. loss-rate = not rec. msg by inv. / sent msg. by DTU

DTU loss-rate = not rec. msg by DTU / sent msg. by inv.

**Comment by rejoe2** [comment]
You are welcome to contribute to the docu...
