### ISSUE TITLE
[Bug]Webserial: Text ändert sich von deutsch auf englisch

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1448]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

8.85

### Github Hash

b6afec1

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

deutsch intalliert

### Error description

kleiner Schönheitsfehler: wenn ich im Weblog auf  automatisch  scrollen klicke, ändert sich der text ins englische. Siehe Video

https://github.com/lumapu/ahoy/assets/142897856/f9e2f0da-90c8-48c7-abb9-90e62f54a126

Edit: Fehler war in älteren Versionen auch schon vorhanden

**Comment by knickohr** [comment]
Das ist kein Fehler von Ahoy, sondern allein dem Cache von Deinem Browser geschuldet. Leere ihn mal und der Spuk hat ein Ende.

**Comment by Gubi2023** [comment]
hab ich gemacht. Fehler bleibt!!

**Comment by Gubi2023** [comment]
ok! danke für das schnelle Bugfix!
