### ISSUE TITLE
[Bug] ESP LED permanent on, but set to off

### ISSUE THREAD

**Issue by jolo1581** [lumapu/ahoy#1453]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8,83

### Github Hash

5ebfe5a

### Build & Flash Method

was already installed

### Setup

![grafik](https://github.com/lumapu/ahoy/assets/53423977/3bad239b-caee-4380-80af-56ebae55fdf0)

### Error description

Since new version it is not possible to power off the blue LED of ESP.
Also it seems to me, it is permanent on, if Ahoy is connected to inverter

**Comment by MetaChuh** [comment]
@jolo1581 

the blue led is connected to d4 (gpio2)
you have ce on d4, instead of irq

the correct wiring should be:
```
cs  d8
ce  d3
irq d4
```

this way the blue led only flashes briefly if irq is triggered

please see the [`ahoydtu schematics`](https://ahoydtu.de/getting_started/):

![](https://ahoydtu.de/img/fritzing/esp8266_nrf_ssd1306_sch.png)

![](https://ahoydtu.de/img/fritzing/esp8266_nrf_ssd1306.png)

**Comment by jolo1581** [comment]
This should Not be the problem.
It worked fine in older versions

**Comment by MetaChuh** [comment]
believe me,
just do it, or downgrade to a previous version that worked for you regarding the led.
it's all documented, all changes, and all why the changes ... your choice.

@lumapu imho this issue can be closed too

**Comment by mroenne2022** [comment]
@jolo1581 
If you can , change the cable d3 and d4 and  in Setup too  - then it works fine with 0.8.83 and the blue led is off. I have already changed my dtu's last week,  now the problem is solved.

**Comment by DB1BMN-collection** [comment]
Hi, just a stupid (?) Question: How do you change the D3 and D4?

**Comment by mroenne2022** [comment]
@DB1BMN-collection 
Change the Cable CE and IRQ on NRF Modul and change it in the Settings from Ahoy too and the problem is solved.
![Ahoy_Wemos](https://github.com/lumapu/ahoy/assets/114778920/56ce9172-1e12-469c-8e3d-782753961536)

**Comment by DB1BMN-collection** [comment]
Ah, I understand, you have no PCB 😅
OK, in my Case I will have tu cut PCB traces and do some crosses with bodge wires.
Will try it tomorrow. My Eyes are tired for tonight.
Thanks!

**Comment by mroenne2022** [comment]
@DB1BMN-collection 
Yes,right. I have only cable between NRF and esp8266,  so it was easy to change.

**Comment by DanielR92** [comment]
Problem solved, closed now. Please reopen when something is not working properly.
