### ISSUE TITLE
deutsche Version: Uptime/ESP-Time ist noch englisch

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1455]
In der Index-Übersicht sind  Uptime/ESP-Time nicht übersetzt, ausserdem steht hier auch noch "Days"
Absicht oder übersehen?

![2024-02-20 17_10_04-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/a2a1f96c-5fc0-4b82-9756-7f86c2d85ea1)

**Comment by tictrick** [comment]
Bist Du auch im Discord vertreten?

**Comment by Gubi2023** [comment]
> Bist Du auch im Discord vertreten?

nein

**Comment by tictrick** [comment]
https://discord.gg/WzhxEY62mB

**Comment by Gubi2023** [comment]
tut mir leid, Discord ist mir zu kompliziert. Brauche ich das überhaupt??

**Comment by Gubi2023** [comment]
und noch einer(?)  Einstellungen MQTT

<img width="976" alt="Screenshot 2024-02-26 193743" src="https://github.com/lumapu/ahoy/assets/142897856/0bd335f4-8d66-4f7e-b254-27da4acfb7e7">
