### ISSUE TITLE
Kein Devicename und kein MQTT Connect

### ISSUE THREAD

**Issue by hubsi5** [lumapu/ahoy#146]
Die neuen Versionen funktionieren bei mir leider nicht.
Ich kann keinen Devicenamen vergeben und wohl deswegen bekomme ich keine MQTT Verbindung.
Den Devicenamen kann ich zwar reinschreiben aber bei Save und Neustart ist er wieder weg.
MQTT Problem hängt wohl mit diesem zusammen.

Bin nun wieder auf 0.5.6 zurück, da funktioniert wieder alles.

**Comment by ghost** [comment]
Kann ich bestätigen:
Den Devicenamen kann ich zwar reinschreiben aber bei Save und Neustart ist er wieder weg.

**Comment by stefan123t** [comment]
@DanielR92 kannst Du das wieder reparieren ?

**Comment by DanielR92** [comment]
Hups, stimmt <form hätte als erstes oben stehen sollen.
@lumapu danke für denn schnellen fix.
