### ISSUE TITLE
Verlaufsanzeige ohne Login im Browser sichtbar [Bug]

### ISSUE THREAD

**Issue by hhammerl** [lumapu/ahoy#1462]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

round dot

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.86

### Github Hash

D94E2765F8A2F13496F041CB465C6030 

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Update FW

### Error description

When I open the webpage, no login is required to see Verlauf

**Comment by knickohr** [comment]
Please check this Setting :

![IMG_1965](https://github.com/lumapu/ahoy/assets/63048210/7665cb03-79cc-44f1-8460-3f20bd2ea45c)

**Comment by hhammerl** [comment]
Hi knickohr,

thanks allot, I did not know that up to now
