### ISSUE TITLE
[Bug] Anzeige der Alarme so korrekt?

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1470]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.88

### Github Hash

2bc6610

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

V08.88

### Error description

Ist die Alarmanzeige korrekt?
bei mir werden die Alarme doppelt und 3-fach angezeigt und die Reihenfolge ist verwirrend (nicht chronologisch)

<img width="620" alt="Screenshot 2024-03-02 162311" src="https://github.com/lumapu/ahoy/assets/142897856/f986a593-8e08-475e-8c06-3b91804d0205">

**Comment by knickohr** [comment]
Das ist weder ein Bug noch ein Feature, das kommt leider genau so aus dem WR raus. Wenn man das zusammen ziehen wollte, müßte man alle Meldungen speichern und dann die Frage wie lange ?

**Comment by Zordandi** [comment]
> Das ist weder ein Bug noch ein Feature, das kommt leider genau so aus dem WR raus. Wenn man das zusammen ziehen wollte, müßte man alle Meldungen speichern und dann die Frage wie lange ?

Werden im WR eigentlich nur 10 Fehlermeldungen gespeichert oder wurde die Begrenzung auf 10 wegen dem Speicherverbrauch im ESP gemacht?

**Comment by knickohr** [comment]
Nein, im WR können mehr sein. Wieviele weiß ich nicht.

**Comment by lumapu** [comment]
die Grenze in Wechselrichter kennen wir bis dato nicht, ist aber auch nicht wichtig, da wird zyklisch die neuesten Meldungen abholen und das sich in Grenzen hält.
Die Überlegung wäre die Limitierung von 10 Meldungen beim ESP32 zu erhöhen.

**Comment by Gubi2023** [comment]
meine Frage wäre trotzdem, wieso die Reihenfolge in der Darstellung nicht chronologisch ist, ist das ein FIFO oder wie werden sie angezeigt?

**Comment by lumapu** [comment]
frage bei Hoymiles nach, wie geschrieben geben wir nur das wieder was der Wechselrichter uns an Infos bereitstellt.

**Comment by Zordandi** [comment]
> meine Frage wäre trotzdem, wieso die Reihenfolge in der Darstellung nicht chronologisch ist, ist das ein FIFO oder wie werden sie angezeigt?

Die 10 Einträge sind hardcoded und aktuell als Ringpuffer implementiert. Ja, wäre durchaus überlegenswert das zu ändern und chronologisch anzuzeigen.

**Comment by lumapu** [comment]
ich prüfe was möglich ist, schön wäre es, wenn dadruch die Code-Size nicht unverhältmismäßig steigt.

**Comment by Zordandi** [comment]
> ich prüfe was möglich ist, schön wäre es, wenn dadruch die Code-Size nicht unverhältmismäßig steigt.

Meine letzte Programmiererfahrung ist lange her, aber ich glaube es ist alles dafür bereits vorhanden ohne extra sortieren zu müssen. Mit mAlarmNxtWrPos und  alarmCnt und den fixen 10 (ich würde hier eine Konstante einführen statt hardcoden) sollte man in der Webausgabe die richtige Startposition im Array berechnen können. Quasi ein FifoBuffer realisiert mit Ringpuffer und Zeiger.

**Comment by lumapu** [comment]
die Frage ist, ob der Wechselrichter die Reihenfolge einhält, aber ja den Zeiger haben wir schon, den müsste man nur noch über die API verfügbar machen - danke für den Hinweis

**Comment by Gubi2023** [comment]
Alarmanzeige jetzt ok, über eine Erweiterung  mit mehr Einträgen würde ich mich freuen! (in Whishlist aufnehmen?)

**Comment by knickohr** [comment]
Das Problem ist das diese Alarme zwischengespeichert werden müssen um sie zeitlich zu sortieren und auf Anfang und Endezeit zu warte.

**Comment by lumapu** [comment]
ich glaube er meint diesen Zwischenspeicher, den können wir auf alle Fälle anheben

**Comment by Gubi2023** [comment]
noch nicht getestet, da z.Zt. nicht so viele Meldungen auflaufen 😉

**Comment by Gubi2023** [comment]
habe jetzt 15 Meldungen angezeigt, allerdings andere als in alter Version mit 10 Meld. Was stimmt jetzt?

![Screenshot 2024-09-23 154747](https://github.com/user-attachments/assets/2c6ab62e-6db5-42f4-b138-09e22d28334e)
![2024-09-23 15_39_08-Greenshot](https://github.com/user-attachments/assets/ccbcece2-4688-4e5a-ab9a-663f2d4e7906)

oder sind die Meld. auf 15 stattt 50 begrenzt und die weiteren werden weggelassen oder nicht angezeigt?

**Comment by lumapu** [comment]
die Meldungen starten jeden Tag aufs neue

**Comment by Gubi2023** [comment]
weiss ich doch, sind aber vom gleichen Tag!  nur mit 2 versch. Versionen ausgelesen

**Comment by lumapu** [comment]
hab gerade nochmal deine Screenshots angeschaut. Die Alarme sind doch die gleichen, nur in der neueren Version sind es mehr (alle) und sortiert.

**Comment by Gubi2023** [comment]
einer fehlt, das wäre der 16. Deswegen meine Frage  
![Screenshog](https://github.com/user-attachments/assets/450cc235-50c5-41c7-a112-44a4f6781eff)

oder gibt es ne scrollfunktion, die ich nicht sehe?

**Comment by knickohr** [comment]
Na schieb das Ganze doch mal nach oben.

https://github.com/user-attachments/assets/ee22cc91-b30c-482f-b638-c2c73fad085c

**Comment by Gubi2023** [comment]
hab ich versucht, ging aber nicht...🤷‍♂️

**Comment by stefan123t** [comment]
@Zordandi ich glaube der WR kann zwei Mal zehn Events speichern. Wir fragen aber m.W. nur die ersten zehn ab.
Man kann glaube auch ein paar AlarmIDs als gelesen markieren bzw. erst ab einer bestimmten ID die Alarme auslesen.

Das ist aber m.W. bisher noch nicht implementiert, schau mal hier: 
* [DEVINFO_ALL (0x15)](https://github.com/lumapu/ahoy/wiki/Protocol#welche-device-info-req_arw_dat_all-0x15-sub-kommandos-gibt-es) [Alarm Data (0x11) / Alarm Update (0x12)](https://github.com/lumapu/ahoy/wiki/Protocol#wie-sieht-das-device-info-kommando-alarm-data-0x11--alarm-update-0x12-aus-)
* [DEVCONTROL_ALL (0x51)](https://github.com/lumapu/ahoy/wiki/Protocol#welche-device-control-devcontrol_all-0x51-sub-kommandos-gibt-es) CleanState_LockAndAlarm (0x14)

Wir könnten auch @broth-itk bitten ob er die Events mal mit der DTU auslesen und die Kommandos tracen kann ?
Dann hätten wir aktuelle Traces mit den ganzen Befehlen wie sie die Hoymiles DTU verwendet.

Interessant wären auch die Fehlermeldungen aus #1471 die man m.E. sogar relativ gut provozieren kann.

**Comment by knickohr** [comment]
Ahoy sammelt jetzt bis zu 50 Events pro Tag. Was und wieviel allerdings im Inverter „drin“ ist, weiß ich nicht.

**Comment by Gubi2023** [comment]
soeben getestet mit V0.8.152:   21 Ereignisse; wurden alle richtig angezeigt. Issue wird geschlossen
