### ISSUE TITLE
v.0.5.9 - Anzeige der Leistugnsbegrenzung im Web

### ISSUE THREAD

**Issue by hubsi5** [lumapu/ahoy#148]
habe nun die neueste Version.
Leistungsbegrenzung per MQTT auf 1000W.
Funktioniert. Wird auch begrenzt.
Nur auf der Webpage steht noch immer 1500W.
Also begrenzt wird die Leistung nur im Web steht noch immer Limit 1500W

**Comment by aschiffler** [comment]
Hi,
kann ich nicht nach vollziehen. Ein kurzer Review des Codes und eigener Test zeigt dieses Verhalten nicht.
- Welches Build hast Du? g2df60b8 0.5.9
- Ggf. warten bis die Seite aktualisiert ist.

**Comment by hubsi5** [comment]
Habe extra 5 Minuten gewartet und noch extra den Inet Browser refreshed.
Version: g87a5209  0.5.9

**Comment by aschiffler** [comment]
Hi,
versuche mal diese binary.
https://github.com/aschiffler/ahoy/actions/runs/2846619040
Das ist die dich ich genutzt habe. Der Unterschied ist nur ein Define in der app.h. siehe:
https://github.com/aschiffler/ahoy/commit/03879d6aed085b4fe32c493968ac71b5066a0cb2

**Comment by aschiffler** [comment]
closed due to inactivity
