### ISSUE TITLE
[Bug]0.8.90 minimal don´t work correctly

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1480]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.90

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

installed 0.8.90-minimal

### Error description

latest version don`t work correctly at me. No settings possible

**Comment by mellow5** [comment]
I can confirm on the ESP32 neither the minimal nor the standard build worked. Even had to flash via serial because update section wasn't working.

**Comment by DB1BMN-collection** [comment]
Yes the settings buttons are not working anymore. Neither from Desktop-PC nor from smartphone.
You can omit reflash via USB, when you go to "AhoyDTU"-Startpage then to "Update".
Just downgraded back to 0.8.89.

**Comment by Gubi2023** [comment]
kaum gefunden, schon gefixt! Super!
