### ISSUE TITLE
Idee: automatische Berechnung des Zeitintervalls zur ganztäglichen Anzeige auf dem Display

### ISSUE THREAD

**Issue by dixy245** [lumapu/ahoy#1485]
Wäre es nicht möglich das Zeitintervall für die Aktualisierung der Werte aus der Differenz zwischen der Sonnenuntergangszeit und Sonnenaufganszeit zu berechnen, damit auf dem Display ganzjährig automatisch der ganze Tag angezeigt wird?

(SONNENUNTERGANSZEIT - SONNENAUFGANGSZEIT) : 255 = Zeitinterval  für die Aktualisierung

ggf. könnte man hierzu für die Zeitintervall Auswahl die "Auto(matik)" Einstellung nach o.a. Formel hinzufügen.

***************

Natürlich könnte man auch noch die derzeitig einstellbaren Minuten um Sonnenauf- und Sonnenuntergang wahlweise für die Berechnung der Zeitachse mit berücksichtigen.

(SONNENUNTERGANSZEIT +/- eingestellter Zeitversatz - SONNENAUFGANGSZEIT +/- eingestellter Zeitversatz) : 255 = Zeitinterval  für die Aktualisierung

Auswahl: "Auto(matik) inkl. Zeitversatz"

**Comment by You69Man** [comment]
>auf dem Display ganzjährig automatisch der ganze Tag angezeigt wird

Was meinst damit? Was genau fehlt dir am Display?
Die Zeitberechnung zwischen Sonnenaufgang und Untergang wird bereits gemacht weil sie z. B.  für die Skalierung des Diagramms benötigt wird, welches ja auch von Sommer bis Winter optimal dargestellt werden soll.

**Comment by dixy245** [comment]
Ah, das wusste ich nicht, dass dieses bereits implementiert wurde.  D.h. auf dem OLED Display wird der Zeitrange den Sonnenstunden bereits angepasst? 
Der "Verlauf" -> Gesamtleistung im Browsermenü wird im Intervall "Wechselrichter" -> Intervall [s] in max. 255 Balken dargestellt. Wenn man hier das Intervall auch automatisch berechnen lassen könnte, so dass eine 255 Balken Tageskurve entsteht wie auch auf dem Display? Hinzufügen von Intervall auf auto?
 
Daten bei mir heute: Tagesmaximum: 924 W. letzter Wert: 2 W.
Maximalwert: 94 W. aktualisiert alle 15 Sekunden

**Comment by You69Man** [comment]
> D.h. auf dem OLED Display wird der Zeitrange den Sonnenstunden bereits angepasst?

Richtig.

Im Webdiagramm wird nicht skaliert. Dort ist meines Wissens aktuell noch ein Ringpuffer implementiert, der die Daten hinten wieder rausschiebt, wenn das Abtastintervall hoch ist, und die Daten nicht mehr im Puffer Platz haben.

**Comment by lumapu** [comment]
Das Webdiagramm ist noch total Basic, ich hatte leider noch keine Zeit mich näher damit zu befassen. Die Grafik auf dem ext. Display ist Dank @You69Man tip top 👍
