### ISSUE TITLE
nRF24L01+ Module not connected

### ISSUE THREAD

**Issue by ralfberger** [lumapu/ahoy#1487]
* * Erledigt * *
Lösung: Löten statt Breadboard 

## Hardware
  [ x]  ESP8266
  
### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
I hope it comes from China and it only says HW 237 on the circuit board

### Antenna:
 [x ]  external antenna (SMA)
 
Version: 0.8.83

![ahoy](https://github.com/lumapu/ahoy/assets/63057484/63f24fd0-f3fc-4b7d-a024-32da2dc6853e)

Fehler: nRF24L01+ Module   not connected

Wie soll ich not connected interpretieren? Heißt das dass der ESP8266 keine Verbindung zum Funkmodul  hat oder heißt es das dass Funkmodul keine Verbindung zum Wechselrichter hat.
Ich habe die Pin Belegung mehrfach geprüft, diesen Fehler schließe ich aus. Leider habe ich kein Ersatzmodul zum testen. 
Ich habe im Netz gelesen das die Module sehr störanfällig gegen elektromagnetischer Strahlung sind. Eine Abschirmung mit Alufolie hat keine Besserung gebracht.

In English
How should I interpret "not connected"? Does this mean that the ESP8266 has no connection to the radio module or does it mean that the radio module has no connection to the inverter?
I have checked the pin assignment several times, I rule out this error. Unfortunately, I don't have a replacement module to test. 
I have read online that the modules are very susceptible to interference from electromagnetic radiation. Shielding with aluminum foil has not brought any improvement.

**Comment by MetaChuh** [comment]
hi @ralfberger 

wenn du zb. von ahoydtu v0.6.9 upgegradet hast:

kontrolliere deine pin settings.
bei deinem nrf24+ modul muss eingestellt sein:
CE D4
IRQ D3

seit v0.7.36 wurden diese beiden pins in den default einstellungen getauscht.

**Comment by lumapu** [comment]
not connected heißt, dass Ahoy dein Funkmodul nicht erkannt hat. Es muss wohl irgendwas mit den SPI Pins nicht stimmen, oder mit dem Modul selbst. Prüfe nochmal die Pins SCK, CS, MISO, MOSI
Hat das Modul schon jemals funktioniert oder ist es ganz frisch aufgebaut?
Es gab leider schon öfter Meldungen über schlechte NRF24 Chargen, hoffentlich fällt deines nicht darunter.

**Comment by ralfberger** [comment]
aktuell ist "Interrupt Pin working" = true. Aber ansonsten immer noch "not connected"
@MetaChuh 
ich hatte vergessen zu schreiben das es eine Erstinstallation ist. Das mit der neuen Pin-Belegung sollte sich mittlerweile herumgesprochen haben :)
@lumapu 
Ja werde nochmals Prüfen und gleich ein neues Modul bestellen.
Gibt es Erfahrungen ob die Module mit iterierter Antenne besser, zuverlässiger sind als die mit externer Antenne?

**Comment by lumapu** [comment]
die von ebyte mit Schirmdeckel sind glaube ich die besten.
Du kannst bei deinem Modul auch nochmal die Bestückung genau anschauen, evtl. gibt es was offensichtliches zu sehen

**Comment by ralfberger** [comment]
Ich habe jetzt anstatt auf dem Breadboard  alles gelötet, und jetzt habe ich auch eine Verbindung.
Danke für eure Unterstützung!

**Comment by MetaChuh** [comment]
@ralfberger 

super, danke dir für die rückmeldung 👍

wenn alles bzgl. `nRF24L01+ Module not connected` für dich passt, schließe bitte dieses issue.

greetings,
metachuh
