### ISSUE TITLE
5 Platinen zu verschenken  - beendet

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#1488]
Ich hätte noch fünf Platinen für ESP32-38-Pin und NRF24L01+ zu verschenken.
Statt den auf dem ESP32-Board integrierten 3,3-V-Regler zu verwenden, ist
hier ein kleiner dreipoliger SMD-Regler für 3,3V vorgesehen (1=GND, 2=Out, 3=In),
wodurch das Funkmodul optimal entkoppelt wird. Man muss nicht unbedingt den
angegebenen Typ AMS1117-3.3 nehmen, es gibt auch Vergleichbare. Statt eines Elkos 
sind 2 kleine SMD-Vielschicht-Kondensatoren mit 22µF/10V vorgesehen (SMD 1210 oder 1206),
was ebenfalls positiv für die Stabilität ist.
Bestückt werden muss die Platine mit einem 38-poligen ESP32-BOB (mit aufgedruckter
Antenne oder SMA-Anschluss) und einem Funkmodul. Hier gehen Versionen mit
aufgedruckter Antenne oder das von eByte mit Schraubanschluss für eine 2,4GHz-Antenne.
Die Schaltung ist simpel und nachfolgend abgebildet.
Wer zuerst kommt, mahlt zuerst. Anfragen per Text-Datei in Ordner ablegen, siehe weiter unten.

Es wäre nett, wenn man dafür eine kleine Spende an lumapu vornimmt:
[https://www.paypal.com/paypalme/lupusch](url)
Die Briefmarke und den Briefumschlag spendiere ich.

![Platine](https://github.com/lumapu/ahoy/assets/43971413/5e8c96a4-a3ff-4c2c-b8d8-855216d33953)

![Schaltung](https://github.com/lumapu/ahoy/assets/43971413/013c6866-81b7-47ed-97e4-40b49a59c52c)

**Comment by dixy245** [comment]
Ich hätte sehr gern 2 Platinen, wie kommen wir zueinander? Gruß dixy

**Comment by kiu77** [comment]
Uff, jetzt merke ich grade, dass ich garnicht weiß, wie man in Github eine private Message verschickt...

**Comment by kiu77** [comment]
So eine Möglichkeit @dixy245 :
Ich habe temporär auf meinem NAS einen Ordner zur Ablage einer Textdatei freigegeben. Also Format = .txt
Da bitte eine Datei mit Nickname und kompletter Anschrift ablegen.

Link: [https://quickconnect.to/tomesc](url)
User: PCB
PW: AhoyDTU

**Comment by dknubben** [comment]
Ich benötige keine Platinen. Allerdings ist die Schenkung und der Spendenaufruf (danke dafür) von @kiu77 für dieses Projekt und den Hauptentwickler ein Anliegen, das ich ausdrücklich unterstützen möchte und weitere Nutzer von Ahoy dazu aufrufe.

PS/Edit: Hier investieren einige engagierte Menschen mit ihrem Wissen viel Freizeit in ein Open Source-Projekt. Das sollte entsprechend honoriert werden.

**Comment by dixy245** [comment]
> So eine Möglichkeit @dixy245 : Ich habe temporär auf meinem NAS einen Ordner zur Ablage einer Textdatei freigegeben. Also Format = .txt Da bitte eine Datei mit Nickname und kompletter Anschrift ablegen.
> 
> Link: [https://quickconnect.to/tomesc](url) User: PCB PW: AhoyDTU

erledigt, vielen Dank. Der ESP32 liegt hier schon für seinen Einsatz bereit :-)
Bitte meine Datei wieder löschen, danke
Ah, sollte sich keiner weiter melden, nehme ich für meinen anderen Kollegen auch noch eine (dann 3 Stück) Der möchte auch auf ESP32 umswitchen.

**Comment by hartloeter** [comment]
Hallo, hast Du noch eine Platine. Ich würde eine nehmen
Gruß harti

Datei abgelegt

**Comment by kiu77** [comment]
3 sind weg und verpackt, zwei sind noch da.

**Comment by hartloeter** [comment]
Super, eine würde ich nehmen. Meine Daten habe ich hochgeladen

**Comment by kiu77** [comment]
Du bist schon mitgerechnet @hartloeter

**Comment by Lizzard44** [comment]
ich würde gerne eine nehmen. Möchte die aber nicht geschenkt haben!

Bisher nutze ich Ahoy auf einem ESP8266 aber das stürz ständig ab und würde es gerne mal mit einem ESP32 versuchen. 

Habe Dir mal was hoch geladen. ;) 
und meine Mailadresse vergessen. Ich hoffe es geht auch ohne.

**Comment by kiu77** [comment]
Hi @Lizzard44 , Es reicht völlig, wenn Du was an den spendest, der hier die Arbeit macht:
[https://www.paypal.com/paypalme/lupusch]
Dein Brief ist fertig und eingeworfen. Ich denke, es dauert bis Montag.

Jetzt ist noch eine Platine übrig.

**Comment by Lizzard44** [comment]
done!

**Comment by hartloeter** [comment]
Spende ist raus

**Comment by VitBeck** [comment]
Hi. Dann nehme ich die letzte, falls noch verfügbar.
Spende geht ebenfalls raus. 
Danke

**Comment by lumapu** [comment]
vielen Dank für die nette Idee, meine Frau hat heute Blumen bekommen 💐

**Comment by kiu77** [comment]
@VitBeck 
Sodele, die letzte Platine ist raus...

@lumapu 
You're welcome

Der Thread kann jetzt zu.

**Comment by VitBeck** [comment]
Die Spende ist raus. Danke

**Comment by dixy245** [comment]
Angekommen, Spende geht heute raus, lieben Dank

**Comment by kiu77** [comment]
Bei Fragen dann einfach melden...
Kontaktdaten hast Du ja.

**Comment by hartloeter** [comment]
Brief ist angekommen, leider ohne Inhalt. Umschlag hat einen Riss-Schade.

![Umschlag](https://github.com/lumapu/ahoy/assets/126253005/b9967295-3e82-4822-8edd-656344919c82)

**Comment by kiu77** [comment]
Shit, da hat jemand geklaut...
Hast Du schon die Bauteile besorgt?

**Comment by hartloeter** [comment]
ja habe ich schon
Pech gehabt

**Comment by kiu77** [comment]
Ich kriege morgen nochmal Platinen. Die sind minimal komplizierter, aber das kriegst Du hin.
Du hast also einen 38-poligen ESP32?

**Comment by hartloeter** [comment]
Ich nehme halt eine Lochrasterplatine

**Comment by kiu77** [comment]
Nein, ich würde Dir noch eine schicken...
Also 38-polig, nicht 30-polig?

**Comment by hartloeter** [comment]
ja 38 pol esp32

**Comment by kiu77** [comment]
Okay. Morgen geht nochmal ein Brief raus. Ich klebe die Platine dann innen fest.

**Comment by hartloeter** [comment]
vielleicht leicht einwickeln

**Comment by hartloeter** [comment]
Vielen Dank

**Comment by Lizzard44** [comment]
meine Platine ist unbeschadet angekommen. Vielen Dank dafür!

**Comment by hartloeter** [comment]
kann auch in  der Sortiermaschine passiert sein

**Comment by kiu77** [comment]
Sortiermaschine glaub ich weniger. Die Platine wiegt 12g und war auf ne Visitenkarte von mir geklebt, damit Du bei Problemen meine Kontaktdaten hast. Jetzt hat sie jemand anderes ;-)
Vielleicht hat sie jemand mit ner Kreditkarte verwechselt...
Aber ich machs morgen etwas anders...

**Comment by hartloeter** [comment]
ok

**Comment by VitBeck** [comment]
Danke. Die Platine ist heute unbeschadet angekommen. Welcher Chip auf Esp32 wäre der bessere, der CP2102 oder der CH9102x?

**Comment by kiu77** [comment]
Ich hatte beide. In der Praxis merke ich keinen Unterschied. Die machen ja bloß die Umwandlung USB/seriell und sind daher nur fürs flashen nötig.

**Comment by kiu77** [comment]
@hartloeter 
So, die Ersatz-Platine ist eingetütet und in den Umschlag geklebt. Melde Dich mal kurz telefonisch oder per Mail, wenn sie angekommen ist.

**Comment by hartloeter** [comment]
Danke mache ich klar

**Comment by hartloeter** [comment]
@kiu77  Hallo, die Platine ist eingetroffen und funktioniert. Vielen Dank noch einmal für Deine Mühe

**Comment by kiu77** [comment]
Super. Bei Fragen einfach anrufen...
