### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by oversponged** [lumapu/ahoy#1490]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

board

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.83

### Github Hash

5ebfe5a

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Alle Einstellungen sind Standart

### Error description

Nach dem Update auf 0.8.83 kann ich keine befehle mehr mit der Web Konsole senden.

**Comment by MetaChuh** [comment]
@oversponged 

danke dir für's issue schließen.
was war bei dir die ursache und lösung ?
