### ISSUE TITLE
Unknown Grid Profile for inverter HMS-2000-4T

### ISSUE THREAD

**Issue by falumamx** [lumapu/ahoy#1493]
Unknown Profile
Please open a new issue at https://github.com/lumapu/ahoy and copy the raw data into it.

13 00 20 01 00 00 08 98 07 90 00 01 0A 8C 00 01 10 00 17 70 16 A8 00 01 18 38 00 01 20 00 00 01 30 03 05 14 0A 8C 07 90 18 38 16 A8 40 00 07 D0 03 E8 50 00 00 00 17 84 01 90 27 10 70 00 00 01

**Comment by lumapu** [comment]
are you from Mexico? I searched for the profile and found `MEX_NOM_220V`.
I will include that now, it will be included in next version coming today `0.8.92`

**Comment by falumamx** [comment]
Yes, I'm form Mexico.
By the way, the microinverter is connected in split phase 120 V AC / 240 V AC,
Thank you!

**Comment by MetaChuh** [comment]
hola @falumamx

ya tuvistes tiempo para comprobar sí te funciona el update para el grid profile de méxico ?
si no, porva' descarga la última dev release de aqui:
[`https://fw.ahoydtu.de/fw/dev/`](https://fw.ahoydtu.de/fw/dev/)
y da nos tu feedback despues.
(en teoria debería funcionar cualquier versión a partir de v0.8.92, pero mejor que te descargas la más ultima v0.8.95)

saluditos soleados,
metachuh

**Comment by falumamx** [comment]
Hola, ha funcionado perfecto 👍🏼
