### ISSUE TITLE
Setting Inverter HM-1500 Interval can not change in newer Versions [Bug]

### ISSUE THREAD

**Issue by Andy811963** [lumapu/ahoy#1494]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

board

### Connection picture

- [X] I will attach/upload an Image of my wiring

### Version

08.91

### Github Hash

?

### Build & Flash Method

ESP Tools (flash)

### Setup

Inverter Intervall can not chance more then 5 Sek.

In older Version it work. 

### Error description

Inverter Intervall HM-1500 
can not chance more then 5 Sek.
In older Version it work. 
![Screenshot 2024-03-10 200658](https://github.com/lumapu/ahoy/assets/133586706/04a827c2-e860-41f9-a334-058dd7f7deeb)

**Comment by MetaChuh** [comment]
@Andy811963 

the interval has been fixed, and the option removed for stability reasons.

greetings,
metachuh

**Comment by lumapu** [comment]
Can you please be more detailed regarding the issue with interval?
If I understand correctly you can set every value up to 5s but no higher values?

You also can answer in German if you like.

**Comment by Andy811963** [comment]
Ja genau so ist es.
Alles was ich einstelle funktioniert nicht.
Das Abfrage-Intervall ist immer 5. Egal was ich einstelle.
Angezeigt wird aber immer 30. Das habe ich vor Wochen mit einer alten Version mal so eingestellt.
Ich möchte gerne das Intervall auf 60 Sekunden setzen.
Wenn das gesperrt ist wozu ist dann das Eingabefeld siehe Bild oben.

**Comment by knickohr** [comment]
Na dann schau mal in den Inverter-Settings

![IMG_2106](https://github.com/lumapu/ahoy/assets/63048210/d65a5452-b32a-48bc-998a-b760c1317110)

**Comment by lumapu** [comment]
verstehe nicht warum es gesperrt sein sollte, komisch was hier wieder los ist ...

**Comment by knickohr** [comment]
Ich glaube hier wird was durcheinander geworfen. Einmal das Abfrageintervall der Inverter und das andere Mal das Anzeigeintervall im Live-View ?

**Comment by lumapu** [comment]
per default steht aber 15s drin, woher kommen dann die 5s? Kommt auch sicher "successfully saved"? Habe gerade bei einem ESP8266 das Interval erfolgreich von 15s auf 34s geändert

**Comment by Andy811963** [comment]
Hallo zusammen,
habe den Fehler gefunden.
Ich benutze zum Anzeigen und ändern den Brave-Browser. Scheinbar überträgt der nicht alle HTML Daten.
Habe jetzt mal mit dem Edge das verstellt damit geht es.
FireFox sollte wohl auch gehen.
Der Brave Browser blockiert ja einiges.
Vielen Dank an alle die sich dem Problem oben angenommen haben.
Gruß Andy B.

**Comment by MetaChuh** [comment]
@Andy811963 

danke für dein feedback.

es hat uns verwirrt.
zuerst dachte ich du meinst den extra update intervall des web interfaces, das entfernt wurde, dann @lumapu 's gedanke, dass wirklich der inverter update intervall plötzlich nicht mehr funktioniert.

wenn für dich alles passt in den major browsern (chrome/chromium/edge/firefox/safari/opera) dann schließe bitte dieses issue.

vielen dank und greetings,
deine ahoy dtu community
