### ISSUE TITLE
No connect to inverter after update to 0.893

### ISSUE THREAD

**Issue by Hanz2420** [lumapu/ahoy#1499]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.93

### Github Hash

0c39f1d 

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Keines , nach dem Fehler "Inverter  #0: ... ist gerade nicht verfügbar" habe ich versucht den Power Level anzupassen(Min, Low, High), aber keine Änderung. Beim Standard IRQ=D4(GPIO2) kommt immer Fehler "Interupt Pin funktioniert = unbekannt / gelb". Wenn ich auf IRQ= D3(GPIO0) ändere, wird der Fehler dann wenigstens nicht mehr angezeigt: Interupt Pin funktioniert = JA - grün. Aber trotzdem kommt kein Connect zum Inverter Hoymiles HM-600 mehr zustande

### Error description

Nach Update: Wechselrichter #0: .... ist gerade nicht verfügbar
Alle Anzeigen bleiben auf null, im Web und auf der Anzeige des DTU
Auch nachdem ich den Inverter gelöscht und wieder neu eingetragen habe, habe auch ein Reset auf Factory Def. durchgeführt und alles neu eingerichtet - aber kein Änderung.. es gibt keinen Kontakt zum Inverter... Vor dem Update lief es seit Mai 23 (mit der damaligen FW stabil).... hätte ich mal nicht ein Update eingespielt..

Kann jemand helfen ? habe ja bereits andere Probleme hier gelesen, allerdings bringt aktuell kein Downgrade der FW (230817_ahoy_0.7.36_ba218ed_esp8266 probiert) - Fehler bleibt bestehen:
![error 1](https://github.com/lumapu/ahoy/assets/163449907/5b7f5120-6746-46ab-ae73-ab8b730970a5)

![DTU-Sys 1](https://github.com/lumapu/ahoy/assets/163449907/935f5347-ada3-405e-84f3-71eeaf26a80c)

![Ahoy-leer 1](https://github.com/lumapu/ahoy/assets/163449907/faeee222-f15e-448d-be25-329e22511123)
![Seetin 1](https://github.com/lumapu/ahoy/assets/163449907/22887ad5-c58c-48eb-b001-328e87fb25ac)

**Comment by Dirk-Ahoy** [comment]
Dein Pinsetting ist falsch - guck mal hier unter Punkt 4  

https://ahoydtu.de/getting_started/

**Comment by Hanz2420** [comment]
Danke dir, allerdings...
IRQ musste ich auf 3 setzten, sonst gibt es zusätzlich noch den Fehler (wie beschrieben:  

Interrupt Pin funktioniert	unbekannt - gelb ...

![image](https://github.com/lumapu/ahoy/assets/163449907/9826ed54-6975-4e2d-bc63-b09186963119)

wenn ich es so setze:
![image](https://github.com/lumapu/ahoy/assets/163449907/79f696fa-f11c-4133-8a6d-22f1b99d4f21)

Oder hast du ein anderes Setting gemeint ?

**Comment by Dirk-Ahoy** [comment]
Der wird erst grün beim senden - von welcher Version hast du das Update gemacht?   Unter Punkt 4 in dem Link steht das da was geändert wurde - wenn du eine Version vor 0.7.34 hattest kann das die Ursache sein. Dann am besten umpinnen oder halt die Settings passend ändern wie es da steht.


Da es jetzt dunkel ist kann man ja auch nicht mehr testen.

**Comment by Hanz2420** [comment]
Ja hatte Version vom Mai 23 - kann dir nicht sagen welche. Kam mit der Box aus der Bucht...
Habe es seit gestern versucht, auch immer laufen gelassen.. blieb den Tag über auch immer so..
Also Umpinnen  in den Settings auf D4 wie unter 4.  So beschrieben ? - ist ja der Standard.. der auch so nach dem Update eingestellt war -aber halt nix mehr lief..
![image](https://github.com/lumapu/ahoy/assets/163449907/c23e7901-9782-4b82-a68a-4c47c9d1da19)

Ich lass es laufen und gucke morgen für nochmals..
Ich berichte dann..
thx und schönen Abend...

**Comment by kiu77** [comment]
Tatsächlich wurde die Belegung in der Firmware verändert. Also die Pins CE und IRQ tauschen, dann müsste es klappen...

**Comment by lumapu** [comment]
ich denke hier ist alles gesagt und kann das geschreibene nur bestätigen. Vielen Dank an alle Beteiligten. @Hanz2420 kannst du bitte morgen nochmal Feedback geben - hoffentlich mit Erfolg.

**Comment by lumapu** [comment]
im Zweifel sollte die erste Anlaufstelle unsere Dokumentation sein:
https://docs.ahoydtu.de/de/latest/faq.html#mein-wechselrichter-wird-nicht-erkannt

**Comment by Hanz2420** [comment]
So dann ?

![image](https://github.com/lumapu/ahoy/assets/163449907/dd85e858-0c89-4552-80c8-4a8ee47e76aa)

**Comment by kiu77** [comment]
Ja, wenn Du die alte Verdrahtung hast. 
Einfacher ist es aber, die Leitungen Board zu nRF24 bei CE und IRQ zu vertauschen, dann kannst Du die Default-Einstellungen der neueren Firmware verwenden.

**Comment by Hanz2420** [comment]
Es hat leider nicht funktioniert. Ich habe die DTU komplett gekauft - also nix mit Löten..
![image](https://github.com/lumapu/ahoy/assets/163449907/09c8b12c-c5ee-48ea-a22e-5e779e387aa7)

![image](https://github.com/lumapu/ahoy/assets/163449907/038ea197-442c-4d77-8a07-de346fad2171)

zusätzlich bleibt die Anzeige jetzt auch noch schwarz (LCD am DTU Kästchen),nachdem ich es eimal vom USB-Kabel (Strom) getrennt habe. Hatte ich ach gestern schon - nur finde ich in dieser FW jetzt nicht mehr das Setting für das Display...

Please Help !

**Comment by Hanz2420** [comment]
Habe auf [GIT SHA: 7b030a3 :: 0.8.91] zurück "geladen", da gibt es dann eine Display Einstellung die im Standard dann auf "keins" steht. Hab das erste Display ausgewählt, dann zeigt es wieder etwas en. Allerdings ist das Hauptproblem:
![image](https://github.com/lumapu/ahoy/assets/163449907/d55e8726-b1cd-40c8-b742-e2937148278d)

weiterhin vorhanden..

Was mache ich denn falsch ? Hab nur vorgestern die alte FW (Stand Mai 23) upgedatet und dann war's geschehen...

thx

**Comment by Dirk-Ahoy** [comment]
Entweder an den Verkäufer wenden oder die Kiste aufmachen und schauen wie die Belegung ist.   

Bitte schau mal die einstellungen beim Wechselrichter durch ob der auch eingeschaltet ist da hat sich ja einiges geändert in den letzten Monaten da oben der Pin jetzt grün ist sieht es ja gar nicht so schlecht aus.

Ansonsten mal ein Log posten hier vom Webserial

**Comment by Hanz2420** [comment]
So habe das Problem wohl gelöst. Mit den Pins und Belegung funktioniert es nur so:
![image](https://github.com/lumapu/ahoy/assets/163449907/26dd84a2-643f-4815-8346-a348089e180a)

![image](https://github.com/lumapu/ahoy/assets/163449907/9aa84934-b518-4205-8f53-0064b6555d16)

Aber das wichtigste, die DTU benötigt jetzt ständig (jedenfalls zum ersten Connect) eine Internetverbindung, nur die Systemzeit via Browser senden genügt nicht mehr. Was habt ihr da verändert ? Warum "schwätzt" die DTU jetzt immer mit dem Web ? Hatte es extra via Pihole und Router Setting nur im LAN belassen ... Bitte mal darstellen warum jetzt ein Internet Zugang nötig ist ?

Thx
Hanz

**Comment by lumapu** [comment]
der Fehler mit dem Internetzugang ist bekannt und wird als nächstes angegangen. Schaue auch in den anderen issues, Stichwort ist hier `NTP`

**Comment by Hanz2420** [comment]
danke für die Info -  werde ja dann sehen wenn es neue Updates gibt. Danke euch auch für die Tipps - sehr guter Service !

Hanz
