### ISSUE TITLE
Wo ist bei 0.8.93 das Leistungsdiagramm [ESP8266]? (Tagesverlauf)

### ISSUE THREAD

**Issue by firedp** [lumapu/ahoy#1500]
Wo ist bei 0.8.93 dieses Leistungsdiagramm geblieben? (Tagesverlauf)

**Comment by knickohr** [comment]
Changelogs lesen, wenn man schon immer an der neuesten DEV klebt 😉

https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md#development-changes

Unter 0.8.92 findet man die Antwort.

**Comment by cibis8** [comment]
OK das mit der History hab ich gecheckt (ist für mich auch nicht so relevant).  Doch wo ist denn die Display Config abgeblieben? Ab Version 92 finde ich diese in keinem der DEVs mehr. Auch kommt beim Updaten neuerdings der Hinweis: Warning your environment may not match the update file! Update geht zwar dann trotzdem weiter (beim Drücken von Continue, aber ich finde bei keinem der Update Files die Display Einstellungen :(

**Comment by firedp** [comment]
In 94 ist doch wieder alles da?
Habe jetzt mutig auf 8266 all de 0.8.94
Da kam zwar die Meldung das mein Chip nicht geeignet wäre, aber all heißt all :-)
Alles läuft super und viel schönere Diagramme drin. TOP

**Comment by cibis8** [comment]
@firedp Ich habe nochmals auf die 0.8.94 aktualisiert.. bei den -all Versionen (englische sowie die deutsche) enthalten bei mir weder die eine noch die andere eine Display Config!  Bin nun wieder zurück zur 0.8.89. Auch was dieser Hinweis soll, das meine Umgebung nicht mit dem Update zusammen passen solle habe ich erst ab der Version .92 erhalten.. Also irgendwas stimmt hier nicht, hatte noch nie Probleme mit Updates! .. naja ausser das mal irgendeins weniger stabil lief (kein Zugriff via IP Adresse) und dann durch ein Neustart behoben wurde. Solche Eigenheiten waren bisher nie.

**Comment by lumapu** [comment]
@cibis8 dein Problem heißt "Broswer-Cache". Da du versch. Versionen der gleichen Firmwareversion ausprobierst aktualisiert sich noch nicht der Browser-Cache. 
Entweder du löschst ihn manuell oder du lädst z.B. die Settings Seite mit `STRG+F5` (das umgeht den Cache).

**Comment by cibis8** [comment]
@lumapu Danke für den Hinweis... hmm hätte ich auch drauf kommen können :) nun geht's bzw. ist die Display Config wieder da. Morgen kann ich dann auch noch berichten, ob das Display was anzeigt - das war mit Versionen ab der .90 leider nicht immer der Fall. Seltsamerweise hatte ich dieses Problem mit der Browser Cache und dem Refresh bisher nie gehabt bei Vorgänger Versionen.. und ich teste relativ viele DEVs..

**Comment by lumapu** [comment]
wenn du genau schaust, dann hängt oben an der URL auch die Version mit dran. Wahrscheinlich hast du bisher immer verschiedene Verisonen getestet - und jetzt das erste Mal verschiedene Build-Varianten einer Version.

**Comment by cibis8** [comment]
das kann möglich sein.. und was hat es mit diesem "Warning" beim Updaten zu tun?

**Comment by lumapu** [comment]
leider haben in Vergangenheit versch. Leute versucht z.B. eine ESP32 Firmware auf einem ESP8266 zu installieren. Diese Meldung soll einfach dazu da sein, dass man sich bewusst ist was man gerade macht.

**Comment by Hanz2420** [comment]
Moinsen, die Grafik (Tagesverlauf - also hab nur eine gefunden) werden doch nur in der HTML-Ansicht im Browser angezeigt oder kommen die doch irgendwie auf das kleine Display auf der DTU ? 
habt ihr da mal Beispiele ?
Ich finde nur dieses:
![image](https://github.com/lumapu/ahoy/assets/163449907/b043d213-c1dc-4251-8636-1a50eb89144d)

thx 
Hanz

**Comment by lille2000** [comment]
Der Tagesverlauf ist auch an Display.
Dazu muss man das „Verhältnis“ auf zb 50% stellen.

hier ist ein älteres Bild:
![IMG_2390](https://github.com/lumapu/ahoy/assets/86225787/e980bde0-31bf-4514-a36e-b8b10dd65e61)

**Comment by Zordandi** [comment]
> Der Tagesverlauf ist auch an Display. Dazu muss man das „Verhältnis“ auf zb 50% stellen.

Was auch etwas versteckt ist: Und man muss den Standort unter Sonnenaufgang -untergang einstellen. Sonst kann das Diagramm Start/Ende nicht berechnen.

**Comment by tobi119** [comment]
> Was auch etwas versteckt ist:

Wo kann ich es finden (V 0.8.95)? Was muss ich sonst einstellen, um den Graf auf dem Display zu erhalten?
Ist der Tagesverlauf auch auf dem ePaper Display möglich?

**Comment by lumapu** [comment]
nein auf dem ePaper kann man keinen Graphen anzeigen (bisher, weiß nicht, ob da jemand dran ist).
