### ISSUE TITLE
ESP8266 Mqtt not in minimal version? 

### ISSUE THREAD

**Issue by Elarion245** [lumapu/ahoy#1505]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 08.95
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

I switched to the minimal version of ESP8266, as the normal one only lasts about 4 days prior to a reboot.
as I am not using a display I wanted to switch to the minimal version (0.7.36 managed 15 days without reboot and more).
My issue with the minimal version is, that there is no mqtt connection possible. Both ahoy and HomeAssistant report mqtt connected = false.
Using the non minimal version it connects immediately. The behavior is the same in 94 and 95.

Based on the change logs I would have expected mqtt to be working in the minimal version?

**Comment by MetaChuh** [comment]
@Elarion245 

please use this version: [`240316_ahoy_0.8.95_4fc61dc_esp8266.bin`](https://fw.ahoydtu.de/fw/download/dev%2Fahoy_v0.8.95%2FESP8266%2F240316_ahoy_0.8.95_4fc61dc_esp8266.bin)

i know it is confusing at the moment, but our intent is to keep the esp8266 ahoy platform alive for as long as possible, even though it's sometimes a task to fit windows 3.11 on a c64 with all the new features ... hence the many different releases to choose, instead of just a few, and dropping support for smaller platforms.

note: the minimal versions do not and never did include mqtt.

hope this helps and thanks.

greetings,
metachuh

**Comment by Elarion245** [comment]
Thanks a lot! This one is working fine. So takeaway is to use the version without any suffix in my case.

**Comment by Peertje-62** [comment]
8266.bin
only MqTT
this version is the prefered 8266 version, most stability

8266-minimal.bin
nothing except basic functions
use this version for debugging purposes

8266-all.bin
MqTT
Display
History
everything included without looking to stability

8266-prometheus.bin
MqTT
Display
History
Prometheus
everything + Prometheus

https://github.com/lumapu/ahoy/issues/1495#issuecomment-1987343702

regards

**Comment by MetaChuh** [comment]
@Elarion245 

thank you for your feedback, and for your detailed, complete, and helpful information of this issue.
we are very glad you had success with the given answers 👍
if all topics regarding this issue have been fulfilled for you, please close it.

greetings & enjoy your solar power with the newest ahoy features

-----
@Peertje-62 

thx for giving your time to re-post the list of the current esp8266 releases and what they contain 👍
much appreciated, as it helps our community a lot, especially if necessarily repetitive, and occasionally explaining the reasons 🙏

greetings & knuffel
metachuh
