### ISSUE TITLE
Frage: Bei zwei Wechselrichter, zeigt das Display die aktuelle Leistung von jeden Wechselrichter an?

### ISSUE THREAD

**Issue by ralfberger** [lumapu/ahoy#1509]
## Hardware
  * [x ] ESP8266

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s  

### Antenna:
* [x ] circuit board
* [ ] external antenna (SMA)

### Version / Git SHA: 
Version: 0.8._83
Github Hash: _______

Bevor ich mir ein Display kaufe und anschließe, kann mir jemand sagen, welche Werte das Display anzeigt. Ich habe mir diverse Youtube  Videos angesehen aber leider finde ich dort auch keine Antwort.  
Auf Bildern und im Video  sehe ich, dass die aktuelle Leistung und auch die Gesamt Leistung angezeigt wird. 
Ich habe in der DTU zwei Wechselrichter eingerichtet. Da wäre es schön wenn ich die  aktuelle Leistung von jeden Wechselrichter ablesen könnte.

**Comment by lille2000** [comment]
Es wird jeweils die Summe im Display angezeigt (Leistung , die Energiemenge des Tages und die Gesamtenergie)

**Comment by Peertje-62** [comment]
Hi, 
https://github.com/lumapu/ahoy/issues/1247#issuecomment-1836115942

https://discord.com/channels/984173303147155506/1065266691463974972/1179850228464107541

regards
![Display Ahoy 8 13](https://github.com/lumapu/ahoy/assets/144957788/2778e150-a5b5-48e0-bf7a-4b84c251c815)

**Comment by Peertje-62** [comment]
Hi,
I would also suggest you use an esp 32 instead of an 8266  as the 8266 is reaching its limits with the current software,
even better and more stable;
https://3printd-solution.eu/Ahoy-openDTU-Fusion-fuer-HM-HMS-HMT-mit-Display
bye

**Comment by MetaChuh** [comment]
@ralfberger 

hier noch ein foto von der graph am display (made by @You69Man)
die grafik lässt sich sogar beliebig von 2-4 zeilen höhe frei konfigurieren, und auch alternierend in frei konfigurierbarem anzeigezeit prozentverhältnis abwechselnd darstellen.

![294759553-3995e576-f34d-4b18-be69-bf5a1121b377](https://github.com/lumapu/ahoy/assets/45773305/a62521e1-1fd0-4c71-96e8-0d5ce8a11c38)

**Comment by ralfberger** [comment]
Vielen Dank!
Ich hatte gehofft das ich die Werte der einzelnen Wechselrichter sehen könnte bzw ich einstellen könnte das nur WR 1 oder WR2 angezeigt wird.  Aber ich werde die DTU trotzdem um ein Display erweitern. 

@MetaChuh  Leider sehe ich keine Bild, ist der Link i.O.?
@Peertje-62  der discord  Link verlangt eine Anmeldung .

**Comment by MetaChuh** [comment]
@ralfberger sorry, war ein typo bei der bild url.
hab's oben gefixed

**Comment by ralfberger** [comment]
Ja, die Darstellung des Graphen sieht toll aus. :+1:
