### ISSUE TITLE
Feature Request: Set powerlimit persistent/non-persistent/disabled option in config page 

### ISSUE THREAD

**Issue by oxylog** [lumapu/ahoy#151]
Ich fände es als feature sehr gut wenn man zwischen diesen 3 Optionen für das Powerlimit wählen könnte. 
Das erleichtert es Usern IMHO generell mit diesem Feature umzugehen - manch einer braucht kein Limit -> Disable -> weniger übertragen fehlerhafte Werte auf ihren Inverter

**Comment by aschiffler** [comment]
Siehe commit von heute.
