### ISSUE TITLE
Doku: Zeilen teilweise abgeschnitten

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1511]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.93

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Doku

### Debug Serial Log output

```shell
Screenshot
```

### Error description

in der Doku sind teilweise die Zeilen abgeschnitten. Siehe Anlage
![2024-03-19 11_34_36-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/7e8076c1-c700-46a7-b2c0-7153db38fae6)

**Comment by mroenne2022** [comment]
Durch "wischen" nach links kann man den Text rüberschieben und die einzelnen Zeilen bis zum Ende lesen  -  zumindest am Smartphone ist es so möglich.

**Comment by Gubi2023** [comment]
ja, aber nur am Smartphone.... Am PC geht das nicht
Edit: Mit viel Fummelei  schon.
Also Schönheitsfehler(?)

**Comment by mroenne2022** [comment]
Der Scrollbalken erscheint wenn man rüberfährt mit der Maus, ist eigentlich ok. Wenn er sichtbar wäre dann wäre es perfekt. Ich kann nicht beurteilen wieviel Arbeit man reinstecken muss um ihn dauerhaft sichtbar zu machen, ich denke wir können damit leben :-)
