### ISSUE TITLE
display 2.42 pouce 

### ISSUE THREAD

**Issue by jacques3629** [lumapu/ahoy#1513]
## Hardware
  
  * [ ok ] ESP32
  
Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Good morning

Ahoydtu Works wonderfully  HM+HMS

Sorry if this question has already been asked
not being very young, I would simply like to display the power in Walt on the 2.42 inch screen au maxi (exit the rest of the information).
Is this possible

THANKS

**Comment by kiu77** [comment]
Not with this software - or only if you modify and compile the software yourself...

**Comment by Peertje-62** [comment]
Hallo & I am 62,
You could try Ahoy 0.8.36 or 0.8.34, https://github.com/lumapu/ahoy/releases
has other display information : less
Back up or write down the settings before you change the firmware
good luck 
regards

**Comment by jacques3629** [comment]
> Hallo & I am 62, You could try Ahoy 0.8.36 or 0.8.34, https://github.com/lumapu/ahoy/releases has other display information : less Back up or write down the settings before you change the firmware good luck regards

thanks for the information
I haven't found anything that allows me to delete information
I just want to keep the WATT
to be able to view further

Sincerely
08.36
![8 36](https://github.com/lumapu/ahoy/assets/127342238/f305b083-5a37-4e5f-9dc5-12422efecb44)

8.95
![8 95](https://github.com/lumapu/ahoy/assets/127342238/791065ff-3479-4acb-b181-c0ef9b67e59e)


![boiboite ](https://github.com/lumapu/ahoy/assets/127342238/1f5cdaab-dfe4-4a48-8e38-506386c5f27c)

**Comment by lumapu** [comment]
What do you mean by "pouce"? 
The display contents are fixed, so the simple answer is: no
As @kiu77 mentioned your only change to do so will be compile your own firmware which simply modifies what is displayed.

**Comment by MetaChuh** [comment]
@lumapu

pouce is inches in french.

as far as i can understand, this feature request is an accessibility option request (bedienungs und sehhilfen option), to display only the current momentary wattage as large as possible.
(example 6191 W at the given example picture, full screen, with no other information on the display)

@jacques3629 thank you for your picture, i love your wooden case.

greetings, metachuh

**Comment by jacques3629** [comment]
Good morning

@MetaChuh
thank you for my little wooden box, it is not expensive at all, made from bamboo on AliExpress, lots of choice
bedienungs und sehhilfen option is a good suggestion for the evolution of the software
maybe in the future ahyo-dtu will support larger oled displays

@lumapu: create my own firmware, I don't know how to do it, I don't have your talent :)

**Comment by jacques3629** [comment]
Sorry bad handling, I don't want to close

**Comment by MetaChuh** [comment]
hi @jacques3629 
i'm glad you found how to re-open this accessibility issue.

unfortunately we are currently not familiar enough with the display routines, to provide a quick and optional, customizable setting to only display a specific value as large as possible with our spare time, but we do understand such assisting needs.

@You69Man we're all still amazed by your graph and personal adjustability since day 1 of your initial pull request.
if your time and personal interest allows it, could you please have a look at this and share your thoughts ?
much appreciated, with no pressure, wishes, or demands.

greetings & hugs
metachuh

**Comment by jacques3629** [comment]
@ MétaChuh, lumapu no worries, continue to do the excellent work
I recently discovered home automation
I had a lot of fun doing ahyo-dtu, I'm not at all in the programming world, that doesn't stop me from trying to follow your progress
and yet I got there thanks to you, also to the forum

Sincerely
