### ISSUE TITLE
Formatierung Powerlimit [Bug]

### ISSUE THREAD

**Issue by mellow5** [lumapu/ahoy#1517]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.95

### Github Hash

4fc61dc

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Ich glaube das Formatierungsproblem gibt es schon seit ein paar Versionen.

### Error description

Formatierung des Powerlimts passt teilweise nicht. Es werden sehr viele Nachkommastellen dargestellt. Siehe #1171 
Im commit 3dd1b4e wurde die src/web/html/visualization.html angepasst. Ich vermute hier wird der auf eine Dezimalstelle gerundete Wert mulitpliziert und anschließend durch 100 dividiert was dann vmtl. wieder zu den vielen Nachkommastellen führen kann.

**Comment by MetaChuh** [comment]
die binary precision verfolgt uns alle, ständig, in allen projekten 😉

hier ein diff vorschlag mit .toFixed(1) rundung, wie bei mehreren anderen werten in `src/web/html/visualization.html`:

```diff
---119 pwrLimit += ", " + (obj.max_pwr * obj.power_limit_read / 100) + "&nbsp;W";
+++119 pwrLimit += ", " + (obj.max_pwr * obj.power_limit_read / 100).toFixed(1) + "&nbsp;W";
```

greetings,
metachuh

**Comment by MetaChuh** [comment]
hi @mellow5 
die rundung ist ab ahoydtu v0.8.96 gefixed.
wir konnten in den tests keine weiteren optischen fehler, in der web anzeige, bezüglich issue #1517 finden.

bitte lade dir [`dev
ahoy_v0.8.97`](https://fw.ahoydtu.de/fw/dev%2Fahoy_v0.8.97/) herunter, und schließe dieses issue, wenn es für dich funktioniert.

thx & greetings,
metachuh
