### ISSUE TITLE
Vorschlag: "update" und "Import"- Buttons erst freigeben, wenn Datei eingetragen ist

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1519]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0-8.95

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Bedienung

### Error description

wäre es möglich,  "update" und "Import"- Buttons erst freizugeben, wenn auch eine entsprechende Datei angewählt wurde?
für mich ist es immer wieder verwirrend, wen die DTU neu gestartet wird und ich weiss gar nicht, was gerade geladen wird....

**Comment by Gubi2023** [comment]
danke, so finde ich es besser...

**Comment by Gubi2023** [comment]
hallo, was mir gerade noch aufgefallen ist: könnte man den Eintrag noch auf den richtigen Typus überprüfen (Json bei Import bzw. .bin bei update) oder ist der Aufwand zu gross?

**Comment by MetaChuh** [comment]
hi, danke dir für die info.

ist imho browserseitig mit javascript nicht zu viel aufwand.

man könnte zb. die passende dateiendung (.json bzw. .bin) browserseitig überprüfen, und solange diese dateiendung nicht vorhanden ist, den <kbd>Aktualisieren</kbd> bzw. den <kbd>Import</kbd> button deaktivieren und ausgrauen.

ps: wir hatten wir uns so gefreut, dass so viele issues von fast allen community membern selbst als erledigt geschlossen wurden, da fällt ein einziges re-opened issue nicht auf 😉

**Comment by Gubi2023** [comment]
schön, ich kann es leider nicht, da ich wie schon erwähnt weder Programme lesen noch schreiben kann. Würde mich freuen, wenn es realisiert würde, da ich schon versehentlich falsche Dateitypen eingetragen und mir die DTU dadurch abgeschossen habe. MfG

Ich mach ihn danach auch brav wieder zu  😉

**Comment by Gubi2023** [comment]
Hallo, finden meine letzten Wünsche keine Berücksichtigung???
https://github.com/lumapu/ahoy/issues/1519#issuecomment-2063387440

**Comment by lumapu** [comment]
mach am besten einen neuen issue auf, der hier ist abgearbeitet (das ursprüngliche Thema)
