### ISSUE TITLE
Hm 600 shows always 0 production

### ISSUE THREAD

**Issue by stratis63** [lumapu/ahoy#1523]
Hi
Ahoy installed fine, but although added a HM 600 inverter shows always 0 production.
I installed a normal Wlite DTU from Hoymiles  and it shows normally the production so i guess the inveryter  broadcasting is ok
Is the re a way to run a debugging to see where is the problem?
## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [x ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [x] Setup settings (use our templates ... to be added)

**Comment by MetaChuh** [comment]
> Is the re a way to run a debugging to see where is the problem?

hi @stratis63 
yes, the easiest way is to check the system status page as seen at the screenshot below, if the nrf24+ module is working. 

<img width="715" alt="Bildschirmfoto 2024-03-23 um 21 36 13" src="https://github.com/lumapu/ahoy/assets/45773305/f717e9d6-b039-4566-978c-9dfedc469e09">

in addition: please verify if the physical wiring of `CE`and `IRQ` to your esp8266.
it is important that it matches the settings at the ahoydtu web interface,
and that they are connected to D3 and D4 in the correct order.

greetings,
metachuh

**Comment by stratis63** [comment]
thanks i did check 3 times already and the wiring is correct i  ll do it
again tomorrow morning, Now  its night in Greece
Its an old HM inverter  and the Low  module (the one without the ant)
but i was wondering if there is a PING command to see if the module is
communicating with the inverter

**Comment by MetaChuh** [comment]
hi and thanks for the detailed info.

no need to recheck the wiring a 4th time.
the age of the hm-600 does not matter, as we have your confirmation, that the wlite still can communicate correctly. 
did your nrf24+ module work before on other 2.4ghz devices or with your hm-600 ?

edit regarding ping command via nrf24+:
no there is not, but we have the web console, which tracks the communication as shown at the screenshot below.
if you encounter anything suspicious, please post it here either as a screenshot, or as a copy paste text.

<img width="1505" alt="Bildschirmfoto 2024-03-23 um 22 18 45" src="https://github.com/lumapu/ahoy/assets/45773305/f880d10c-d059-4a4f-a9c4-f9fb9509678b">

**Comment by stratis63** [comment]
thank you for the info, 
i interchaged the pins of CE and IRQ accordingly and started getting the production
