### ISSUE TITLE
Keine Funkverbindung Woran kann es liegen?

### ISSUE THREAD

**Issue by JKRPVHM-600** [lumapu/ahoy#1525]
![screen](https://github.com/lumapu/ahoy/assets/164860141/947561fa-eda7-457c-8e5b-aced2d0edcfb)

## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by knickohr** [comment]
Was hast Du verändert ?  Oder muß ich die Glaskugel raus holen ?

Ein bißchen was dazu schreiben wäre vielleicht hilfreich um uns wenigsten eine Richtung zu geben wie wir an der Kugel rubbeln müssen 😢

**Comment by JKRPVHM-600** [comment]
Hallo ich habe das Ahoy Teil komplett zusammengebaut gebraucht gekauft. Verändert habe ich also nichts zu dem was der Vorbesitzer zusammengebaut hat. Nun wollte ich es in Betrieb nehmen und bekomme leider keine Funkverbindung zum WR HM-600 hin. Der WR und die Ahoy Einheit sind ca. 10m weit enternt voneinander, stehen im Freien, ohne Mauern. 
Welche Angaben brauchst Du um mir einen Hinweis zu geben.
Vielen Dank für die Unterstützung.

PS Ich bin Laie ;-(

**Comment by JKRPVHM-600** [comment]
Kann es an den beiden NEINS liegen?
![screen png2](https://github.com/lumapu/ahoy/assets/164860141/defd6631-9d44-4fe3-ab10-2cc25092264a)

**Comment by knickohr** [comment]
Ahhh, jetzt 😉

Na geht doch 😇

Du siehst das es keine Interruptverbindug gibt. Und ja es liegt an dem ersten Nein.
Wenn Du uns jetzt noch die Pinout Configuration zeigst, dann haben wir das Problem vermutlich in wenigen Minuten gelöst.

**Comment by JKRPVHM-600** [comment]
Hilft das? Liebe Grüße
![IMG_20240325_110223](https://github.com/lumapu/ahoy/assets/164860141/97c24f2e-fba9-4f66-8a88-1db103685d48)
![IMG_20240325_110312](https://github.com/lumapu/ahoy/assets/164860141/c469e5aa-5c1c-4010-987e-d9951380dbb0)
![IMG_20240325_110434](https://github.com/lumapu/ahoy/assets/164860141/04ef9157-b84d-4182-b9f5-5e32a620a519)
![IMG_20240325_110548](https://github.com/lumapu/ahoy/assets/164860141/88f70233-b5c0-4f88-b32c-fd2418f8c1c7)

**Comment by JKRPVHM-600** [comment]
Ach so es ist eine Funkeinheit mit einer externen Antenne.

**Comment by JKRPVHM-600** [comment]
Skizze
![IMG_20240325_111554](https://github.com/lumapu/ahoy/assets/164860141/813fd8de-de6b-4879-9e35-fc48d8f6b4aa)

**Comment by knickohr** [comment]
Das meine ich nicht. Das hier :

![IMG_2235](https://github.com/lumapu/ahoy/assets/63048210/f5d30be7-2f29-4563-88a1-4b0cd0f12964)

Und ich hoffe Du hast nicht allzuviel Geld in diesen wackerligen Aufbau investiert. Da fallen mir noch mindesten 3 weitere Gründe ein warum es nicht funktioniert 😟

**Comment by JKRPVHM-600** [comment]
hm 15 € inkl. Versand :-( 
Hier der Screenshot
![screen png3](https://github.com/lumapu/ahoy/assets/164860141/5bf92aa7-2902-4166-b48a-6f352fad3f01)

**Comment by JKRPVHM-600** [comment]
![IMG_20240325_112156](https://github.com/lumapu/ahoy/assets/164860141/5c812c61-3c86-43cf-8829-9138c4712c1b)

**Comment by knickohr** [comment]
Dreh mal D3 und D4 um.

**Comment by JKRPVHM-600** [comment]
geil!!!! es geht!

Vielen vielen Dank!

**Comment by knickohr** [comment]
🙇
