### ISSUE TITLE
0.8.98 - 2024-03-24

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1526]
Good morning,
Cannot find 0.8.98 - 2024-03-24 on https://fw.ahoydtu.de/fw/dev/

Regards

## Hardware
  * [ x] ESP32 OpenDTUFusion

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [x ] external antenna (SMA)

### Power Stabilization:
* none

### Build & Flash Method:
* [x ] ESP Tools

**Comment by knickohr** [comment]
Ein Blick in die Github Actions sagt uns das es keine 0.8.98 gibt, bzw. etwas schiefgelaufen ist.

![IMG_2234](https://github.com/lumapu/ahoy/assets/63048210/e1ff3335-8280-49e4-a960-5be572364942)

**Comment by Peertje-62** [comment]
Thx
