### ISSUE TITLE
240325_ahoy_0.8.98_f47cb10_esp8266-all-de: History fehlt

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1528]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.98

### Github Hash

f47cb10

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

update auf esp8266-all-de

### Error description

240325_ahoy_0.8.98_f47cb10_esp8266-all-de: History fehlt

**Comment by lumapu** [comment]
duplicate #1530

**Comment by Gubi2023** [comment]
tut mir leid, in der 8.100 fehlt immer noch in der "_all-de_" Version die History, und in den Settings ist kein Display enthalten;
in der all-Version sind sie vorhanden!
