### ISSUE TITLE
V0.8.98: keine Werte bei Total Power Today /Sunset-Sunrise fehlt in System

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1530]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.98

### Github Hash

f47cb10

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

update auf esp8266-all

### Error description

V0.8.98: keine Werte bei Total Power Today /Sunset-Sunrise fehlt in System

**Comment by lumapu** [comment]
das liegt am defekten NTP Sync, gefixt in `0.8.100` 😉

**Comment by Gubi2023** [comment]
V0.8.100: Sunset-Sunrise fehlt immer noch in System  

edit: nach mehrmaligem aktualisieren wird es angezeigt......

**Comment by lille2000** [comment]
Bei mir fehlt „History“ immer noch in der Menüleiste mit 0.8.100. (esp8266 de all)
Unter Setting fehlt „Display“.
 
Das Display selbst funktioniert und die Webseite /history läd auch.

**Comment by MetaChuh** [comment]
@lille2000 

> Das Display selbst funktioniert und die Webseite http://ahoydtu_ip/history läd auch.

hab's gerade getestet: "Verlauf" weg und "Display Konfiguration" weg passiert auch bei esp32 in allen -de versionen.
pin einstellungen des displays waren nach 0.8.100 english version hin und her flashen weg.

**Comment by Gubi2023** [comment]
fixed mit 0.8.101
