### ISSUE TITLE
V8.100:Fehlermeldung beim öffnen der Webside[Bug]

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1533]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.100

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

update auf V0.8.100

### Error description

heute nacht von 0.8.93 auf V0.8.100 upgedatet.
Heute morgen DTU nicht mehr sichtbar/erreichbar.
Nach Spannungswiederkehr war DTU zwar sichtbar, aber beim Versuch, eine Webseite auszuwählen, kam Fehlermeldung. Siehe Screenshot
<img width="896" alt="Screenshot 2024-03-27 084052" src="https://github.com/lumapu/ahoy/assets/142897856/9e2f7d5e-82a9-43d8-b7bb-e8df7f28da51">

**Comment by MetaChuh** [comment]
hi @Gubi2023 

ich hab's erst am esp32 ausprobiert mit den 4 major browsern, da gehts.
werd' gleich einen esp8266 mit der -all version flashen zum testen mit mehrfach reboot und viel und schnell herumklicken.

hast du die -all genommen oder die kleine ?

in der zwischenzeit: hilft bei dir browser cache leeren ?

<img width="1001" alt="Bildschirmfoto 2024-03-27 um 09 03 30" src="https://github.com/lumapu/ahoy/assets/45773305/55f4beb4-e086-48a4-9b94-e44fa94433b4">

**Comment by Gubi2023** [comment]
@MetaChuh 
danke für die schnelle Rückmeldung. ich teste immer alle für mich relevante (ESP8266) neue Versionen an, bei allen gleiche Fehlermeldung. 
Im 2. oder 3. Versuch gehts dann, aber Verbindung bricht seit 8.94 ständig ab bzw. DTU startet sich ständig neu. Bin deshalb zurück auf 8.93

**Comment by MetaChuh** [comment]
hmmmm ... 
bei einem esp8266 gehts, den anderen esp8266 habe ich gerade mit dem gleichen ota upgrade in einen perma bootloop geschossen.

was mir jetzt erst auffällt:
egal ob esp8266 oder esp32, der menüpunkt <kbd>Verlauf</kbd> mit der grafik ist bei allen in v0.8.100 weg (so wie oben am screenshot)

... jedoch im browser manuell auf die url `http://ahoydtu_ip/history` gehen, funktioniert 😳

**Comment by MetaChuh** [comment]
~~ja, web interface am esp8266 auch die englische spinnt bei mir in edge und chrome total.
safari geht meistens nach refresh.~~

edit: lag nur an js blocker browser plugins, web interface geht normal.

ich lass trotzdem mal eine esp8266 mit v0.8.100-en, mit 5s api poll intervallen als test laufen, um zu sehen wie lange bis zum reboot.

edit:
noch keine reboots seit 2h am esp8266 mit v0.8.100-en, trotz 5s dauer api polls 👍

<img width="864" alt="Bildschirmfoto 2024-03-27 um 12 51 24" src="https://github.com/lumapu/ahoy/assets/45773305/5e0cd98d-a85a-4479-9c50-05cb5c26b0f6">

**Comment by kiu77** [comment]
@MetaChuh 
Ja, bei mir ist es das Gleiche mit ESP32: Der Menüpunkt Verlauf bzw. history ist weg. Mit Deinem Direktlink geht es dann. Sonst läuft alles soweit mit der 100er.

![Bildschirmfoto 2024-03-27 um 13 09 03](https://github.com/lumapu/ahoy/assets/43971413/66714511-de9c-4ed9-b059-0f173c628464)

**Comment by Gubi2023** [comment]
edit:
noch keine reboots seit 2h am esp8266 mit v0.8.100-en, trotz 5s dauer api polls 👍

du Glücklicher, bei mir läuft die V8.100 gar nicht, inzwischen zickt sogar die 8.93! (DTU nicht mehr erreichbar, obwohl sie in derFritzbox angezeigt wird!)

**Comment by kiu77** [comment]
Oh, in solche quasianalogen Fällen half bei mir auch nur komplett neu flashen mit erase des flash Speichers und dann updaten. 
Evtl. hilft auch Strom weg und nach dem Hochbooten kurz via WLAN unter der http://192.168.4.1 zugreifen. Wenn das geht, dann kann man zumindest die Einstellungen sichern, falls noch nicht geschehen.

**Comment by Gubi2023** [comment]
merkwürdig: heute nacht V0.8.101 geladen, lief störungsfrei bis 9 Uhr (bis dahin kein Zugriff mit PC). Dann Webseite mit Chrome geöffnet, seither wieder DTU-Neústarts im Minutentakt! Woran kann das liegen??

**Comment by MetaChuh** [comment]
@Gubi2023 

ich hab' wieder vergessen ob du api oder mqtt verwendest, aber ein beispiel szenario, mit dem ich dies am kleinen esp8266 jederzeit reproduzieren kann, ist:

1) die dtu wird via api in 2-5 sekunden intervallen für alle inverter/id hintereinander sequenziell abgefragt.
(wenn die api abfragen zb. via async await parallel gespawnt werden, dann sogar bei 5-10 sekunden intervallen und auch höher)
2) der watchdog triggert einmalig und verursacht einen dtu reboot.
in dieser zeit sind alle api queries noch bis zu ihrem timeout aktiv, und ohne extra check ob noch eine query läuft, bleiben diese aktiv, und es kommen weitere queries hinzu, bis die dtu wieder nach dem reboot antwortet.
3) die überlast an offenen gleichzeitigen queries (curl, async fetch, file_get_contents, etc.) führt dazu, dass der watchdog erneut triggert und die dtu rebootet.
(bei sehr kurzen query intervallen löst dies einen boot loop aus, solange bis man alle api queries anhält)

bei mir hab ich folgende tweaks für die api queries eingebaut, damit ich meine aktuelle regel/steuerperformance zuverlässig und ohne reboots schaffe:
1) vor api query mache ich ein socket test, ob die ip der dtu generell erreichbar ist (ist viel schneller als ping oder nc port 80 check)
2) dann wird überprüft, ob noch eine vorherige query abfrage für den nächsten geplanten endpoint existert.
3) erst wenn keine weitere query in einem anderen spawn läuft, wird diese endpoint query durchgeführt.
4) failsafe: wenn ein endpoint der api `null` liefert, sende ich der dtu einen sofortigen rebootbefehl.
(speziell für esp8266, wo langanhaltende `null` response öfters unter last passieren kann)

wie ist dein setup ?

**Comment by Gubi2023** [comment]
@MetaChuh: tut mir leid, ich verstehe nur Bahnhof.
Ich habe einen ESP8266, NRF24 ohne externe Antenne und ohne Elko. Ich frage den WR in 20 sec.Intervallen ab.
MqTT verwende ich nicht, da ich keinen IO-Broker oder ähnliches habe, d.h ich greife nur über die Webseite auf die DTU zu...
Ich kann weder Progamme lesen, geschweige denn schreiben oder interpretieren.
Mir fällt nur auf, dass wenn ich nicht auf die DTU zugreife, alles anstandslos funktioniert und sobald ich die Webseite öffne, die DTU sich ständig neu startet. (Seit V0.8.94) mit V 0.8.93 läüft sie tagsüber, erst gegen Abend startet sie sich dann auch wieder in unregelmässigen Abständen neu, ohne dass ich etwas gemacht hätte.

**Comment by kiu77** [comment]
> ESP8266, NRF24 ohne externe Antenne und ohne Elko

Kein Wunder. Den Elko sollten Du mal nachrüsten, zumindest. Ein NRF24 ohne externe Antenne? Um den Typ zu bestimmen könntest Du mal ein Foto davon einstellen...

**Comment by MetaChuh** [comment]
@Gubi2023 

danke dir für die info 👍

ja, das nutzen des web interfaces verursacht ebenfalls am schwachen esp8266, leider mit neueren versionen, 
reproduzierbar die reboots, plus die zeitweise fehlenden bedienelemente bis zum seite im browser aktualisieren.
(das web interface greift wiederum parallel auf verschiedene api endpoints in der dtu zu, um diese daten dann anzuzeigen)

frage:
ist ein upgrade bei dir auf ein esp32 modul möglich ?
(falls du die aktuelle selbst gebaut hast)
oder der wechsel auf eine fertige opendtu fusion ?

ps:

> ohne Elko

ich stell mal schmunzelnd den timer, wie lange es ab jetzt dauert, bis (...) dies findet, und die berechtigte wöchentliche prädigt hält 😉

**Comment by Gubi2023** [comment]
Ich hab das Teil fertig gekauft mit Gehäuse. Bei einem Wechsel aus ESP32 bräuchte ich alles neu, incl. Gehäuse.
Open-DTU geht ja angeblich mit ESP8266 nicht..
Elko nachrüsten ist nicht so einfach, da ich mir das nicht mehr zutraue (zu zittrig/ zu mini)
![Uploading grafik.png…]()

**Comment by Gubi2023** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/142897856/8a8af8cf-131f-4554-98c8-212538da24db)

**Comment by MetaChuh** [comment]
verstehe, danke dir für die info 👍

in diesem fall empfehlen wir nahezu immer die fertige opendtu fusion:

- opendtu fusion ist fix und fertig aufgebaut mit gehäuse (und vielen elkos)
- opendtu fusion hat doppelt so viel speicher, im vergleich zu standard esp32 modulen (8mb statt 4mb)
- opendtu fusion hat beide funkmodule fix eingebaut (nrf24+ und cmt2300a, falls bei dir irgendwann ein hms/t dazukommen sollte)
- opendtu fusion kommt vorinstalliert mit opendtu, ~~und lässt sich über das mitgelieferte usb kabel, direkt aus dem chrome - browser mit dem [AhoyDTU Web Installer](https://ahoydtu.de/web_install/) bespielen.~~
(edit: das opendtu fusion board wird im aktuellen web installer noch nicht unterstützt)

hier sind die beide meistgenutzten kauf-links für die fertige opendtu fusion:

[`OpenDTU Fusion bei AllianceApps (Hersteller)`](https://shop.allianceapps.io/products/allianceapps-opendtu-fusion)
[`OpenDTU Fusion bei Amazon`](https://www.amazon.de/AllianceApps-OpenDTU-kompatibel-Hoymiles-Wechselrichtern/dp/B0CCK45WMZ/ref=sr_1_1?__mk_de_DE=ÅMÅŽÕÑ&crid=3PE8WIDCI5EIH&dib=eyJ2IjoiMSJ9.y48O-TiVHOtNZ4aJ-osJHxrtAL9hGKNjx-gd0a9V2T5uRpMAi2SDYLcpjr2-HpLrbsY__TRLXEPsna2_UDcJfiI_C_jj7MjE3C1xZp1d1NY.HncuqsEcFCxjCHP-38jMIwRCpvoibzcenqL2xFHJiWw&dib_tag=se&keywords=opendtu+fusion&qid=1711628306&sprefix=opendtu+fusion%2Caps%2C119&sr=8-1) (auch vom hersteller, aber versand über amazon)

foto der opendtu fusion:
<img width="530" alt="Bildschirmfoto 2024-03-28 um 13 25 10" src="https://github.com/lumapu/ahoy/assets/45773305/14ad7f1e-7ba6-4949-a144-f2d1713fcf6b">

**Comment by kiu77** [comment]
Bez. Elko. Du könntest ihn nachträglich so drauflöten (oder löten lassen):

![317722850-8a8af8cf-131f-4554-98c8-212538da24db Kopie](https://github.com/lumapu/ahoy/assets/43971413/21b0e49a-53b0-420c-8707-56bef9d478ef)

**Comment by Gubi2023** [comment]
@kiu77 
danke, versuch ich als Soforthilfe. 
@MetaChuh 
Wenn nichts nützt: würde AllianceApps OpenDTU auch gehen, da ich mein Balkonkraftwerk vermutl. nicht erweitern werde ?

**Comment by MetaChuh** [comment]
> würde AllianceApps OpenDTU auch gehen, da ich mein Balkonkraftwerk vermutl. nicht erweitern werde ?

ja, jede esp32 basierte und open source fähige dtu die zumindest ein nrf24+ funkmodul hat, geht für dein uns mitgeteiltes szenario.

die opendtu fusion hat nur zusätzlich das funkmodul für die neuen hoymiles hms/hmt inverter.
falls du dieses zweite funkmodul nicht brauchen wirst, gibt es auch die um ca 15.- günstigere standard version:

links:
[`OpenDTU bei AllianceApps (Hersteller)`](https://shop.allianceapps.io/products/allianceapps-dtu-mit-opendtu)
[`OpenDTU bei Amazon (via Hersteller)`](https://www.amazon.de/AllianceApps-kompatibel-Hoymiles-Wechselrichtern-HM-Serie/dp/B0C8YVN598/ref=sr_1_2?__mk_de_DE=ÅMÅŽÕÑ&crid=293FXY3NHSS2K&dib=eyJ2IjoiMSJ9.y48O-TiVHOtNZ4aJ-osJH6LzxzWRAtFyvMAF2GPS_5wQQjlU4zbK1xWmg_Gpyy-NWxEnxDKFIdAqGapstJW2019NFkjt9lbdd2QdF0dtgwfH34kjBZ4nCbkaVuS9d63I4v2qjy1T7w6zV5lVIsd2Hq2nhFl9mBQhInf_jWl3XO5WTBjg0hiXMj5qd3k5ZQtcdWwe8RJuwx6udYQtPd4gb6bXxTBLwwX4F5GY8iCwfIr63OIOoNppHfDzdZGsFyEdWzFeNtpfr13h2qwPee41l7brTrOJGYoTWj0L1ZrRw2E.7sGTA_jQ8FdLdTn6AyTMJa0ta4vm6ALmqvwUNYeePXc&dib_tag=se&keywords=opendtu&qid=1711665771&refinements=p_n_free_shipping_eligible%3A20943778031&rnid=20943777031&sprefix=opendtu%2Caps%2C109&sr=8-2)

**Comment by kiu77** [comment]
@Gubi2023 
das von MetaChuh empfohlene Modell hat weiter den Vorteil eine externen Antenne für das Funkmodul, was bessere Funkverbindung mit dem inverter mit sich bringt.

**Comment by Gubi2023** [comment]
Habe heute mal nach längerer Zeit wieder meine 8266 reaktiviert (V0.8.123) 
Fehlermeldung vom ursprünglichen Issue  kommt immer noch...
![grafik](https://github.com/lumapu/ahoy/assets/142897856/875e6ead-df21-4ec8-9568-fa89af1c3a84)

**Comment by Gubi2023** [comment]
jetzt auf  #1725
