### ISSUE TITLE
[Bug] 0.8.100 history is missing in ESP32_de and ESP8266_de

### ISSUE THREAD

**Issue by tavoc** [lumapu/ahoy#1534]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.100

### Github Hash

GIT SHA: 4b75e72 :: 0.8.10

### Build & Flash Method

ESP Tools (flash)

### Setup

the newest update removed the history button in the webinterface. I was coming from 0.8.97 (by the way I very much like the new look of the history).

The ESP32 and ESP8266 (booth german version) looks the same.
By adding /history on ESP32 I can see it, on ESP8266 it is an empty page
![esp32](https://github.com/lumapu/ahoy/assets/6911803/2d0f9546-25e9-4e32-a2d9-a76a7f6701da)
![esp8266](https://github.com/lumapu/ahoy/assets/6911803/1a21e92e-4326-4f45-bbb2-cdd55c27ca46)

### Error description

the newest update removed the history button in the webinterface. I was coming from 0.8.97 (by the way I very much like the new look of the history).

The ESP32 and ESP8266 (booth german version) looks the same.
By adding /history on ESP32 I can see it, on ESP8266 it is an empty page

**Comment by Gubi2023** [comment]
see also  #1530

**Comment by Di-Di-Du** [comment]
on my ESP8266 with 0.8.100 (german version), I can see the history correct, wehen adding "/history" beehind the IP in the browser adress line.

**Comment by Gubi2023** [comment]
see #1533

**Comment by MetaChuh** [comment]
confirmed for all -de versions.

additionally the display config is unavailable, alternating display graphs/text might not switch, and the display parameter might be reseted to factory.

**Comment by kiu77** [comment]
Beim Fixen könnte noch was verbessert werden, denn mir fiel mir noch was Sprachliches auf:
Beim Verlauf wäre oben besser: "Leistungsverlauf letzte 20 min"
Und dann unten "Leistungsverlauf heute".
Denn es dreht sich ja nicht um eine Gesamtleistung, also nichts Kumuliertes, sondern um einen Verlauf.

**Comment by tavoc** [comment]
das sind nicht immer 20 Min. Beim ESP32 ist es bei mir eine Stunde. Ich glaube es gibt bereits ein Issue, wo das Wording geändert wurde

**Comment by Gubi2023** [comment]
Aktualisierung ist abhängig vom eingestellten Intervall beim WR

**Comment by kiu77** [comment]
@Gubi2023 
Ahja. Das macht Sinn. Ein Speicher für soundsoviele Messungen, daher. Bei mir 5s für 2 Inverter. Vermutlich also 240 oder 120 Messungen für den kurzfristigen Verlauf.
Demnach wäre also folgende Beschriftung sinnvoll:
Beim Verlauf wäre oben besser: "Leistungsverlauf letzte XX min", wobei XX ja errechnet und angezeigt werden kann.
Und dann unten "Leistungsverlauf heute".

**Comment by kiu77** [comment]
Hab nochwas bei History gefunden: Oben wird die korrekte Ortszeit angegeben und unten ist man schon eine Stunde weiter...

![Bildschirmfoto 2024-03-27 um 17 32 40](https://github.com/lumapu/ahoy/assets/43971413/bc5be949-7392-455a-a0c8-e27ca3060a62)

**Comment by tavoc** [comment]
das unten ist die errechnete Zeit des Sonnenuntergangs. Oben rollierend

**Comment by kiu77** [comment]
@tavoc 
Schon klar, aber die Zeit unten ist falsch. 1h zuviel. Außerdem müssen die Zeiten der letzten eingelesenen Daten unten und oben zeitsynchron sein. Sind sie aber nicht.

**Comment by Gubi2023** [comment]
ja, aber die Anzeigen sollten trotzdem an denselben Stellen anfangen und enden

**Comment by kiu77** [comment]
@Gubi2023 
Anfangen sollten sie oben und unten zu unterschiedlichen Zeiten, da der obere Graph ja ein Zoom des Endes des unteren ist. Aber enden bzw. die letzten Werte sollten sich auf die gleiche Zeit beziehen.
Es sieht so aus, als sei unten die aktuell noch aktive Winterzeit ignoriert und vorzeitig auf Sommerzeit geschaltet worden, aber eben nur unten.

**Comment by Gubi2023** [comment]
@kiu77 sorry, hast recht, hab mich falsch ausgedrückt

**Comment by Gubi2023** [comment]
V0.8.101: sieht erst mal gut aus, History und Display config werden angezeigt

**Comment by tavoc** [comment]
Die V.0.8.101 funktioniert auf dem ESP32. Menüpunkt Verlauf ist wieder da.

Auf einem ESP8266 fehlt es jedoch weiterhin:
<img width="1111" alt="image" src="https://github.com/lumapu/ahoy/assets/6911803/9e85b86f-8a5f-48c3-9c3f-cddf84ada653">


wenn man history manuell eingibt, dann ist die Seite leer:

<img width="527" alt="image" src="https://github.com/lumapu/ahoy/assets/6911803/85a3dfc5-2556-4530-bf4d-7cda7f00c2ae">

**Comment by lumapu** [comment]
@tavoc welche ESP8266 Variante hast du installiert? Du benötigst die `esp8266-all-de` oder `esp8266-all`

**Comment by tavoc** [comment]
klassisches Layer8 Problem, Dankeschön. Geht mit der all Version (hatte vorher immer nur die _de genommen)

**Comment by MetaChuh** [comment]
@tavoc 

anbei noch ein screenshot und der firmware link von [`240327_ahoy_0.8.101_2a4c836_esp8266-all-de.bin`](https://fw.ahoydtu.de/fw/download/dev%2Fahoy_v0.8.101%2FESP8266%2F240327_ahoy_0.8.101_2a4c836_esp8266-all-de.bin)

falls elemente mit der `esp8266-all-de` auf englisch erscheinen, bitte wieder den browser cache leeren.

<img width="1006" alt="Bildschirmfoto 2024-03-28 um 09 30 16" src="https://github.com/lumapu/ahoy/assets/45773305/ca57a188-ee2e-4955-8366-95ae4e3d043d">

**Comment by kiu77** [comment]
Bei mir hat das Update auf 0.8.101 die Display-Konfiguration gelöscht.
Die Zeiten des Verlaufs stimmen jetzt.
Haben sich die Defaultwerte für das Display (Bildschirmschoner) verändert?

**Comment by MetaChuh** [comment]
@kiu77 

super dass es jetzt bei dir klappt 👍

> Bei mir hat das Update auf 0.8.101 die Display-Konfiguration gelöscht.
Haben sich die Defaultwerte für das Display (Bildschirmschoner) verändert?

ja, das konnte passieren, wenn man zufällig in den einstellungen auf speichern geklickt hat, während das element `display konfiguration` nicht vorhanden war.
dies sollte jetzt nicht mehr passieren.
(defaultwerte sind nach wievor `aus/standard`)

> Die Zeiten des Verlaufs stimmen jetzt.

ja, das ist ebenfalls gefixed 👍

edit: default wert für bildschirmschoner ist `off`.

**Comment by kiu77** [comment]
@MetaChuh 
Danke für die Erläuterung!

**Comment by tavoc** [comment]
@lumapu mir fällt auf wie bereits @kiu77  festgestellt, dass die Zeiten doch nicht stimmen:
<img width="923" alt="image" src="https://github.com/lumapu/ahoy/assets/6911803/de7f870c-5451-4244-a351-98279dc87297">


Es ist grade 15:50. Aber unten sind wir schon nach 16 Uhr.
Der obere Wert sieht auch eher wie 15:40 aus

Die NTP Zeit von Ahoy ist aber korrekt: 15:50

**Comment by kiu77** [comment]
@tavoc 
Du hast nicht die aktuelle Firmware 0.8.101?
Bei .98 war ein Versatz von 1h der Fall. 
Ich habs gerade bei mir überprüft:
Mit der neuesten Beta ist der 1h-Versatz unten weg.

@lumapu 
Aber: Die untere Skala ist noch nicht wirklich genau, zeitlich. Jetzt geht sie geschätzt um 15-25 Minuten vor.
Das sieht man erst gegen Abend, wenn man genau drauf schaut.

![Bildschirmfoto 2024-03-29 um 16 08 44 Kopie](https://github.com/lumapu/ahoy/assets/43971413/810280f6-21bd-42c8-90b8-9098c10f512d)

**Comment by tavoc** [comment]
Das Foto ist von der 101 Version, siehe unten rechts

**Comment by kiu77** [comment]
Ach ja.
Dann ist der Fehler bei Dir größer. Vermutlich hängt er mit der Abfragerate zusammen, bei mir 5s.

**Comment by Gubi2023** [comment]
ihr habt Probleme! das ist doch Pillepalle, er geht doch um die Tendenz!

**Comment by kiu77** [comment]
@Gubi2023 
Na und? Dass es nicht das Wichtigste ist, dürfte klar sein, auch ohne Deinen Hinweis.

**Comment by MetaChuh** [comment]
@Gubi2023 

es ist ein gutes zeichen, wenn man sich post issue bereits mit dem feinschliff beschäftigen kann, da dies bedeutet, dass die eigentliche aufgabe in diesem issue bereits erfüllt wurde.

was in post solution, in einem issue diskutiert wird, und wann es geschlossen wird, bleibt entscheidung des besitzers eines issues, in diesem fall @tavoc, bzw. entscheidung des project owners, falls das abschließen in seltenen fällen vergessen wird.

greetings metachuh.

**Comment by lumapu** [comment]
ich weiß, dass bei den Skalen irgendwas schief geht, beim oberen Grafen seit Anfang an.
Bei Gelegenheit nehme ich mich drum Thema an.
