### ISSUE TITLE
MDNS geht nicht mehr.

### ISSUE THREAD

**Issue by lille2000** [lumapu/ahoy#1538]
Esp8266
Display
All-De
2 Inverter (Hm)

Seit einiger Zeit erreiche in die Webseite ( immer nur per IPhone probiert) nur noch über über die IP-Adresse, nicht mehr die Adresse http://solar.local
Von einem PC im selben Netzwerk klappt es.

Nun bin ich darüber gestolpert, das es Probleme seit IOS17 und den esp8266 gibt:

(https://github.com/esp8266/Arduino/issues/9046)

ggf. könnte man man prüfen, ob die vorgeschlagene Lösung auch hier sinnvoll ist.

**Comment by lumapu** [comment]
danke für den Hinweis, ist in der nächsten Version eingebaut, für ESP8266 und ESP32

**Comment by lille2000** [comment]
Vielleicht war die Ursache aber auch #1543 ?
Mit 0.8.102 geht mDNS auf alle Fälle wieder. 👍

**Comment by lumapu** [comment]
ich weiß es nicht, so geht's auf jeden Fall wieder.
