### ISSUE TITLE
power limits not working in 0.5.10?

### ISSUE THREAD

**Issue by duenengeist** [lumapu/ahoy#154]
Hi, 
I have an HM600. Limit worked fine for me in 0.5.1. Now I am on the most recent 0.5.10 and my inverter does not limit.

![Bildschirmfoto_2022-08-14_10-44-22](https://user-images.githubusercontent.com/10466558/184529530-8901842a-6cfa-49f0-9301-4e15e731189e.png)

Any ideas what I can check?

Carsten

**Comment by MubiTec** [comment]
I have the same Problem

**Comment by lumapu** [comment]
which is the version which destroyed this feature? Came it up from 0.5.1 to 0.5.2?
It's easier to find the issue if we don't have to diff that many versions.

**Comment by duenengeist** [comment]
> It's easier to find the issue if we don't have to diff that many versions.

I see, unfortunately I jumped directly from 0.5.1 to 0.5.10...

**Comment by MubiTec** [comment]
Sorry, I cannot help, too. I come directly from 0.4.26. I am not @home,perhaps I can test <0.5.10 Version later

**Comment by duenengeist** [comment]
I also can try to check later today ...

**Comment by MubiTec** [comment]
At 0.5.8 it works. Testing now 0.5.9
... 0.5.9 do not work. Just be something between 0.5.8 and 0.5.9
If there is anything to test pleasw let me now

**Comment by lumapu** [comment]
Ok I the issue just be related to the callback function of MQTT I changed recently For now I don't understand why the issue occurs.
We have to verify if the Mqtt callback is called once the subscribed topic is changed.

Other idea because of your screenshot. You set a persistent limit inside the setup to 100W? Did you reboot your device after changing the setting?
In past the were some voices which said that sometimes the Ahoy software send an additional zero with the limit, do a limit of 100W became 1000W.

**Comment by MubiTec** [comment]
I changed it not via mqtt, I changed it via setup Page and did a reboot all Times after it

**Comment by duenengeist** [comment]
> Other idea because of your screenshot. You set a persistent limit inside the setup to 100W? 
Yes in the setup via Webbrowser
> Did you reboot your device after changing the setting?
Yes

I can try to set it to 10W...

**Comment by lumapu** [comment]
In the last versions was no change regarding persistent limit as far as I know.
Thank you for checking the versions.

**Comment by duenengeist** [comment]
I guess the limit is off by a factor of 10. I set 1W on my HM600 and it limits now to 10W (roughly):
![Bildschirmfoto_2022-08-14_13-50-27](https://user-images.githubusercontent.com/10466558/184535515-26226ab9-aa72-406e-a909-904594ddfd5c.png)
 
On my HM600 a limit of 10W now does limit to 50W (from the Voltage at the panels I can tell there is enough radiation and the inverter is clearly limiting)
![Bildschirmfoto_2022-08-14_14-10-00](https://user-images.githubusercontent.com/10466558/184536235-0376f2f3-169b-40a1-847a-887ba2647e62.png)

Just to double-check: if I take out the limit (set to 600W) the inverter produces at MPP:
![Bildschirmfoto_2022-08-14_14-16-26](https://user-images.githubusercontent.com/10466558/184536469-a186d471-96b1-48ee-8715-255dc7ea35fd.png)

**Comment by duenengeist** [comment]
Ich habe noch mal ein wenig experimentiert mit verschiedenen Werten für das Limit. Der WR limitiert in der 0.5.10, wenn ich über das Webinterface recht kleine Werte setze (10, 20, 50) aber die gemessene Ausgangsleistung passt nicht. Auch nicht mit dem Faktor 10. Irgendwas scheint mit der Berechnung nicht zu stimmen.

**Comment by duenengeist** [comment]
Inzwischen bin ich mir recht sicher: die Werte sind in %. Ich kann bei mir Werte zwischen 2% und 100% setzen und es wird akzeptiert. Vielleicht in der Webpberfläche von "W" auf "%" ändern?

**Comment by fila612** [comment]
Falls dem so ist, wäre doch eine Vorauswahl z.B. via Dropdown-Menü eine gute Möglichkeit, oder?

**Comment by aschiffler** [comment]
Bitte beachten:
1. Die Einstellung des Limits gilt bzw. ist implementiert für WR der 3. Generation
2. Limits die kleiner sind als 2% der Spitzenleistung werden vom WR nicht angenommen
3. Debug-Option: Im seriellen Log via USB findet man "...has accepted pwr limit" oder "... has not accepted pwr limit" ggf. hilft dies für das Verständnis.
4. Aktuell >0.5.1 & < 0.5.12 ist es so, dass es beim Setzen des Limits via MQTT zu einem anderen Regelverhalten kommen kann wie beim Setzen via HTML Setup-Page. Dies liegt daran, dass es z.Zt. so ist, dass das eingestellte Limit via MQTT beim nächsten Power-Cycle des WR (vermutlich DC=0W) seitens des WR wieder verworfen wird.
