### ISSUE TITLE
[Bug] MDNS broken since 0.8.98 

### ISSUE THREAD

**Issue by fsck-block** [lumapu/ahoy#1543]
Beim merge von "new network" in v. 0.8.98 wurde das MDNS feature nicht vollständig übernommen.

Für die Funktion von MDNS ist es notwendig dass regelmäßig die Funktion `MDNS.update()` aufgerufen wird. 
Bis zum o.g. merge war dieser Aufruf in `ahoywifi::tickWifiLoop()` zu finden.

Desweiteren scheint der Ticker `everySec(std::bind(&AhoyNetwork::tickNetworkLoop, mNetwork), "net");` nicht mehr dauerhaft zu funktionieren, da er nicht bei den `app::regularTickers()` mit dabei ist.

Ein Lösung wäre den "net" ticker in die  `app::regularTickers()` aufzunehmen und den Aufruf von `MDNS.update()`  in `AhoyWifi::tickNetworkLoop case NetworkState::GOT_IP:` aufzunehmen.

Falls gewünscht kann ich einen PR beisteuern.

**Comment by lumapu** [comment]
danke für den Hinweis, habe es gerade eingebaut und werde es mit der nächsten Version veröffentlichen
