### ISSUE TITLE
Grid - Profil lesen HMS2000 Ahoy  0.8.101 DEV Meldung : Unbekanntes Profil : Bitte erstelle einen neuen Issue ....

### ISSUE THREAD

**Issue by rolandl1969** [lumapu/ahoy#1546]
Meldung beim Gridprofil auslesen :

Unbekanntes Profil
Bitte erstelle einen neuen Issue auf https://github.com/lumapu/ahoy und kopiere die Rohdaten hinein. 

00 01 03 E8 00 00 03 E8 00 00 00 00 00 00

**Comment by lumapu** [comment]
das ist aber ein sehr kurzes Grid Profile

**Comment by rolandl1969** [comment]
![Meldung](https://github.com/lumapu/ahoy/assets/156771642/9038e4d8-d867-4418-9692-a0990f433d90)

Das ist die komplette Meldung. Der gleichzeitig betriebene HM1500 kann problemlos ausgelesen werden.

**Comment by lumapu** [comment]
ich finde leider inm iner Sammlung kein Gridprofile mit dieser ID (0x0001). Evtl. bedeutet das, das kein Gridprofile gespeichert ist.

**Comment by rolandl1969** [comment]
Mit 0.8.102 klappt das Auslesen wieder :-)
![Meldung_102](https://github.com/lumapu/ahoy/assets/156771642/a4ebb6c5-cad2-48cf-a0c3-ff6e604ff53e)

**Comment by lumapu** [comment]
eigenartig, dass es den Aussetzer gab, danke für's schließen 👍
