### ISSUE TITLE
APC wird regelmäßig nicht angezeigt

### ISSUE THREAD

**Issue by keinprofi** [lumapu/ahoy#1555]
Moin zusammen,

über Ostern habe ich mal mein HoymilesZeroExport Projekt komplett neu aufsetzen müssen, da ich das System zerschossen habe.
Aktuell nutze ich einen Raspi für das v.g. Script und einen weiteren Raspi am Stromzähler mit einem per UART angeschlossenen Sensor.

Bei dieser Aktion fiel mir nun auf, dass die AhoyDTU (V. 0.8.83) ziemlich häufig kein APC anzeigt. Dies wirkt sich dann offenbar auch auf die Justierung der Wechselrichter und der damit verbundenen Erzeugung des Stroms aus, soll heißen dass das nicht nur eine reine optische Angelegenheit ist. Das Phänomen betrifft alle 3 WR und das unregelmäßig soweit ich das gesehen habe.

Ich nutze 3 WR. Die Ahoy-DTU nutze ich seit rund 2 Jahren (grundsätzlich) ohne Probleme. Ob das von mir genannte Problem schon länger besteht kann ich nicht sagen, es ist mir eben erst am letzten WE aufgefallen. Die Bilder dienen zum besseren Verständnis was ich meine.

![Ahoy1_crop](https://github.com/lumapu/ahoy/assets/131543857/a102ae16-9236-434a-a4f6-d9690c6664b6)
![Ahoy2_crop](https://github.com/lumapu/ahoy/assets/131543857/4affd7f3-e96f-4bdd-ae4c-d07b49aa4c3c)
![Ahoy3_crop](https://github.com/lumapu/ahoy/assets/131543857/54f1e801-23a1-4dab-ab0a-563471e089e4)

Die WR sind weiterhin verbunden, Strom wird offenbar erzeugt.
Hat jemand ähnliche Erfahrungen oder weiß warum das so ist, bzw. wie ich das beheben kann? Welche Infos braucht ihr ggf. noch von mir?

Beste Grüße
Karsten

## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

**Comment by lumapu** [comment]
könntest du noch dein Abfrageintervall und auch die Frequenz mit der du neue Limits setzt nennen?

**Comment by keinprofi** [comment]
![Ahoy4_crop](https://github.com/lumapu/ahoy/assets/131543857/db263e41-77da-4fa2-bc3a-7038449343dc)


Und die Werte werden alle 10 Sekunden geschrieben. Das passt so nicht...
Ist der Wert von 15 Sekunden mit dem Update gekommen? Ich meine da "damals" 3 Sekunden drin gehabt zu haben.
Hab da jetzt mal 5 Sek. eingetragen.

**Comment by lumapu** [comment]
kann gut sein, dass wir den Wert mal geändert haben. Aber eher um 0.8.0 herum, nicht in letzer Zeit

**Comment by keinprofi** [comment]
ja, habe das update auch erst am WE gemacht, im Winter lief das alles noch mit alten Versionen.

Was ich gesehen habe läuft das auch besser jetzt.

Danke für den Tipp!

**Comment by knickohr** [comment]
Nach dem Setzen eines Limits kommt erst ma N/A, was auch korrekt ist. Je nach Intervall (Abfrage der Inverter) kommt es dann verzögert, vorausgesetzt es wurde in der Zwischenzeit kein neues Limit gesetzt.

**Comment by keinprofi** [comment]
> Nach dem Setzen eines Limits kommt erst ma N/A, was auch korrekt ist. Je nach Intervall (Abfrage der Inverter) kommt es dann verzögert, vorausgesetzt es wurde in der Zwischenzeit kein neues Limit gesetzt.

Dann lag es definitiv am Abfrageintervall der WR. Kleine Ursache - große Wirkung.
Nochmals danke an euch, ich hatte den Punkt echt nicht mehr auf dem Schirm!
