### ISSUE TITLE
Permanenter Neustart der Ahoy DTU [Bug]

### ISSUE THREAD

**Issue by Tiezy** [lumapu/ahoy#1559]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

08103

### Github Hash

7ee1f99 

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Coming from 08.97 and update to 08.101 leads to permanent reboot of the DTU. For short time the DTU can be entered via the webinterface and there is mentioned that the NTP timeserver is not available. I tried also 08.103 but same issue remains.  It looks like also that the WLAN connection / password was lost as the DTU open the Ahoy access point but entering the wlan name and password doesn't solve the issue.
In case of downgrade back to 08.97 everything works fine as expected. Provision of log seems to be impossible as the DTU permanent reboots.
What I'am doing wrong??
Thanks for your feedback. Maybe I'am the only one?

**Comment by Tiezy** [comment]
I missed to add that a manual NTP sync via webinterface failed with the Error: ERR_PROTECTED same as sync via browser.

**Comment by lumapu** [comment]
'protected' feels like a password protected DTU. Is that right?
We fixed recently with 102 the NTP issue. Can you check 102 or 103 again?
Do you have configured the default NTP server?

You can also answer in German if preferred.

**Comment by SebiWolze** [comment]
Guten Abend,

habe selbiges Problem, allerdings mit der letzten Stable Version.
Geflasht, 192.168.4.1 -> alles super.
Eigene WIFI Daten rein, reboot.
Er zeigt an, dass er sich mit meinem WLAN verbindet, macht ein NTP Update, allerdings 2 Stunden vor unserer Zeit -> nicht mehr erreichbar.
Exakt 2 Pings gehen nach jedem Reboot durch, danach nicht mehr erreichbar bis ich neu flashe, danach wieder über 192.168.4.1 zu erreichen.

<img width="524" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/879bdd3d-2339-4e23-9ab0-d868b0af410a">

**Comment by Tiezy** [comment]
Danke schon mal für die Rückantwort. Die Fragen kann ich wie folgt beantworten.

- 'protected' feels like a password protected DTU. Is that right? Jawohl das ist korrekt.
- We fixed recently with 102 the NTP issue. Can you check 102 or 103 again? 103 zeigt das gleiche Verhalten.
- Do you have configured the default NTP server? Ja habe ich. Hat sich dazu etwas geändert also muss man beim update von 08.97 auf 08.101 / 08.103 die NTP setting z.B. neu eingeben?

mfg

**Comment by edw00d4711** [comment]
Ich habe das gleiche Problem. Ich bin schon auf eine USB-C ESP gewechselt, weil ich dachte, die Platine hat einen Schaden. Aber da das gleiche Problem. Ständige Reboots. Fehler mit dem NTP zu verbinden.

Hab jetzt mal ESP Home geflashed. Das läuft einwandfrei im WLAN. Ich versuche es jetzt mal mit der .103

**Comment by edw00d4711** [comment]
.103 macht auch Probleme sobald ich einen Inverter hinzufüge.
Im Log sehe ich nur:
```
I: Network connected


-------------------
Welcome to AHOY!

point your browser to http://192.168.9.70 (Station)
to configure your device
-------------------

[  5112][E][ESPmDNS.cpp:169] addServiceTxt(): Failed setting service TXT
I: [NTP]: 2024-04-03 17:31:16 UTC
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400df66f  PS      : 0x00060830  A0      : 0x800e04a2  A1      : 0x3ffb2150  
A2      : 0x00000001  A3      : 0x3ffc3de8  A4      : 0x3ffc9fdc  A5      : 0x3ffc39e0  
A6      : 0x3ffcaff0  A7      : 0x00000001  A8      : 0x00000001  A9      : 0x00189730  
A10     : 0x00000000  A11     : 0x80000001  A12     : 0x8008fff0  A13     : 0x3ffb2150  
A14     : 0x00000003  A15     : 0x00060823  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x40090208  LEND    : 0x40090216  LCOUNT  : 0x00000001  


Backtrace: 0x400df66c:0x3ffb2150 0x400e049f:0x3ffb2190 0x40197c39:0x3ffb21d0 0x400d375d:0x3ffb21f0 0x400eb6b3:0x3ffb2230 0x400f09f6:0x3ffb2270 0x40108915:0x3ffb2290




ELF file SHA256: e1bff542de77c8a0

E (2239) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
Terminal disconnected: BreakError: Break received
```

**Comment by lumapu** [comment]
ah ok, ich weiß bescheid, wird wieder rückgängig gemacht, die 104 ist im anrollen 😊

**Comment by Tiezy** [comment]
Hallo Lukas,

super mit der 104'er sieht es besser aus, ABER: direkt nach dem update startet die DTU wieder mit permanenten Reboots.
Die Webside der DTU kam aber trotz der dauernden reboots hoch und ich konnte lesen das die NTP Zeitsync nicht funktioniert. Es funktionierte nun aber der Zeitsync über den Browser (wahrscheinlich gerade im richtigen Moment den Buttom gedrückt) und die DTU läuft nun durch. Ein manueller NTP sync über das Webinterface Menue / settings / NTP Server funktionierte ebenfalls.

Also läuft da beim Startup noch was nicht ganz rund. Also zumindestens bei mir :-).

Danke für dein Engagement.

**Comment by lumapu** [comment]
leider kann ich den NTP Fehler bisher noch nicht nachstellen. Würdet ihr bitte bestätigen, dass der Fehler in 0.8.106 weiterhin auftritt?
Ich habe mal die stable Release 0.8.83 installiert (mit Erase) und eingerichtet. Danach bin ich dann per OTA auf die 0.8.106 gegangen.

**Comment by Tiezy** [comment]
Also nach dem update von 08.103 auf die 0.8.106 habe ich folgendes beobachtet. Das Problem mit permanenten reboots besteht immer noch. Offensichtlich ist der NTP Server beim starten nicht erreichbar. Ein Zeitsync über den Browser klappt manchmal. Ich habe jetzt mal den DTU reset für Mitternacht und das lesen des Grid Profiles deaktiviert und reboot after successfull save angeklickt. Danach hatte die DTU das Netzwerkpasswort wohl wieder vergessen und der neue Setup Wizard kam hoch. Nach korrektem Eintrag startet die DTU aber auch hier nicht von selbst neu. Der Wizard muss abgebrochen werden und das Netzwerk manuell in der Weboberfläche eingetragen werden. Downgrade zur 0.8.97 und alles läuft.

**Comment by hrolofs** [comment]
Schau auch mal ob du "System Config/Reboot Ahoy at midnight" aktiviert hast und schalte das gegebenenfalls aus. Bei mir hat das all die NTP/Reboot Probleme bei den 0.8.1XX Versionen wohl beeinflusst. 

Hab das bei meinen DTUs vor dem updaten von 0.8.97 auf die 0.8.106 ausgeschaltet und das update lief sauber durch. 

Wenns das war, die Option nach dem Update ausgeschaltet lassen. Bei mir geht der Dauer Reboot direkt wieder los wenn ich die Option setze.

**Comment by sebastianrothe** [comment]
Also bei mir geht die 106 mit beiden Einstellung (Reboot at Midnigh an/aus).

**Comment by hrolofs** [comment]
Nach Aktivierung Save&Reboot gemacht? Bei mir gehen die beiden DTUs danach in den Dauer reboot.

**Comment by sebastianrothe** [comment]
Ja, habe mehrfach neugestartet (von Hand). Kommt alles wie gewollt hoch (ESP8266).

Kannst du mal deine Timezone überprüfen? Die war bei mir noch von vor der Zeitumstellung auf `+1`, muss aber jetzt auf `+2`.

**Comment by hrolofs** [comment]
Habs gerade nachgeschaut, steht auf +1. Bin nicht sicher ob das jetzt +2 sein muß. Urzeit im Display und Web-page ist ja richtig. Habs mal auf +2 geändert und reboot. Uhrzeiten in der Anzeige sind immer noch richtig. Keine Ahnung worauf die DTU diesn Parameter anwendet. 

Danach die Midnight Option aktiviert. Und nach einem Reboot geht die DTU wieder in den Dauer Boot Modus.

Ich hab als DTU nur ESP32 und ESP32-S3. Kann das nicht mit einem ESP8266 testen.

Muß jetzt erstmal die DTU neu aufsetzen. ;-)

**Comment by sebastianrothe** [comment]
Laut https://time.is/Leipzig#time_zone ist `+2` richtig. 

Dann scheinen sich die ESPs da anders zu verhalten. Sorry :)

**Comment by Ollipop030** [comment]
Auf meinem ESP32 (WROOM 30 Pin) macht die DTU auch alle paar Minuten einen Neustart. Reboot at midnight an oder aus spielt keine Rolle, längste Uptime war heute 30 Minuten.

**Comment by lumapu** [comment]
fiexd mit 107?

**Comment by edw00d4711** [comment]
Leider nicht für ESP32. Da scheint der Build nicht durchgelaufen zu sein. 
https://fw.ahoydtu.de/fw/dev%2Fahoy_v0.8.107/
Auch unter den "Actions" nicht. Aber ich vermute es verlinkt auf das gleiche Verzeichnis

**Comment by lumapu** [comment]
ja sorry, leider ist der build gestern nicht durchgelaufen. Werde es später nochmal probieren.

**Comment by hrolofs** [comment]
@sebastianrothe 
> Laut https://time.is/Leipzig#time_zone ist `+2` richtig.

Ist Definitionssache und hängt von ab wie das implementiert ist.

Vorsicht: Klugscheißer Modus on

Wir leben in der MEZ, die einen Offset von +1 Stunde zur UTC hat.

Zusätzlich hat die MEZ noch eine DST (Daylight Saving Time), zusätzlicher temporärer Offset von +1 Stunde

Das ergibt aktuell einen Offset zur UTC von + 2 Stunden.

Manchmal konstruiert man daraus eine MESZ mit +2 Stunden zur UTC. Dazu müsste es dann 
aber auch einen negativen DST Offset für die Winterzeit geben.

Windows gibt z.B. für uns immer "(UTC+01:00) Berlin" an. Im Sommer halt mit zusätzlichem 
DST Offset von + 1 Stunde.

Klugscheißer Modus off

Man kann das auch ganz anders sehen bzw. interpretieren. 

Hängt halt davon ab wie's implementiert bzw. programmiert wurde. ;-)

**Comment by Ollipop030** [comment]
Version .108 läuft bisher ohne Reboot.

**Comment by edw00d4711** [comment]
Bei mir läuft es auch mit .108. Dafür das epaper nicht mehr. Aber das ist ein anderer Thread

**Comment by Tiezy** [comment]
Hallo Lukas,
als issue opener kann ich dir mitteilen das es mit der 0.8.108 nun tadellos klappt, Keine reboots nach dem Update und das update selbst verlief ebenfalls reibungslos.
Prima, Vielen Dank
