### ISSUE TITLE
Neuer Ahoy User - nach Einwahl in Heim-WLAN und NTP Settings verhält sich DTU wie ein Stein[Bug]

### ISSUE THREAD

**Issue by SebiWolze** [lumapu/ahoy#1561]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.97

### Github Hash

abc1234

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Freshly installed latest stable / 0.8.97 / 0.8.103

### Error description

<img width="779" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/f882b137-bac5-4de6-89ad-5954ccea7bdf">
<img width="525" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/b80775ce-03c8-43d7-ab60-25d84b80a026">

Ich hoffe deutsch ist okay, übersetze sonst gern noch auf Englisch.

Heute ESP32 "Wroom" erhalten, mit nrf24 und Display verkabelt.
Über Webinstallier die letzte stable geflasht.
Mit Wifi AP verbunden, eigene WLAN Daten + NTP (Fritzbox eingetragen).
Save.

Danach bekomme ich noch genau 2 Pings, danach ist Ende.
Nochmal geflasht, selbiges Fehlerbild.

Hier ein paar Issues gelesen, 0.8.97 geflasht.
Selbes Fehlerbild.
Mit 0.8.103 exakt das selbe.

2 Pings gehen durch, danach ist vorbei.

Hier noch eine Console Ausgabe mit latest Stable:
<img width="710" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/a32a53d4-7d06-4e0c-96ac-01c305371b6a">

EDIT: Kann es irgendwas mit der Zeitumstellung zu tun haben, da ich hier so viele NTP Probleme lese, und bei mir nach NTP Update die Zeit 2 Stunden vor unserer Zeit angezeigt wird..?

EDIT2: Nochmal frisch geflasht, nochmal eine andere SSID für meinen Rasenmäher Roboter (2,4Ghz only) eingetragen.
7 Pings gingen durch, danach wieder nichts mehr.
<img width="512" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/d28a830a-1061-4041-a3e1-7589281fe7f1">

Console zu dem Zeitpunkt:
<img width="470" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/00b60d6e-ad9d-4479-bd6d-21f1a9b418de">

EDIT3: Diverse Reboots gemacht, entweder gar kein Ping geht durch oder 1-2, danach erneut nichts mehr.
Heimisches WLAN läuft tadellos, ich bin mit meinem Latein an dieser Stelle am Ende :(

Arbeite im Bereich IT-Sec, Netzwerk/WLAN/ESP ist für mich täglich Brot, Antworten dürfen gerne technischer Natur sein.

Vielen Dank!

**Comment by MetaChuh** [comment]
@SebiWolze 

> Arbeite im Bereich IT-Sec, Netzwerk/WLAN/ESP ist für mich täglich Brot, Antworten dürfen gerne technischer Natur sein.

sehr gut, wegen folgender procedure:

bitte flashe deinen esp32 mit einem anderen, non dtu related, projekt, zb. mit micropython, und richte damit das wlan ein.
beobachte bitte dann das ping verhalten erneut.

reason:
crosscheck der stabilen funktionalität des esp32 wifi modules dieses esp32 boards, mit alternativer, non related firmware.

alternative procedure:
crosscheck der identischen firmware auf einem weiteren, ähnlichen (esp32 board eines anderen herstellers) oder baugleichen esp32 board (zweites board des gleichen herstellers)

thx & greetings,
metachuh.

**Comment by lumapu** [comment]
herzlich willkommen 😊

Die NTP Fehler waren eher so, dass hat keine Zeit geholt wurde, daher denke ich, dass das hier was anderes ist.
Wenn ich es richtig verstanden habe, ist kein Zugriff auf die web UI möglich, da nur zwei pings durchgehen.
Wurde per AP irgendwas neben dem lokalen WiFi konfiguriert?
Lese des öfteren in letzter Zeit Probleme beim ESP32, aber nicht beim letzten stable Release

**Comment by knickohr** [comment]
Statische IP in Ahoy oder DHCP ?  Wenn Du statische IP hast, dann hoffentlich auch ein Gateway und DNS eingetragen ?

**Comment by SebiWolze** [comment]
> @SebiWolze
> 
> > Arbeite im Bereich IT-Sec, Netzwerk/WLAN/ESP ist für mich täglich Brot, Antworten dürfen gerne technischer Natur sein.
> 
> sehr gut, wegen folgender procedure:
> 
> bitte flashe deinen esp32 mit einem anderen, non dtu related, projekt, zb. mit micropython, und richte damit das wlan ein. beobachte bitte dann das ping verhalten erneut.
> 
> reason: crosscheck der stabilen funktionalität des esp32 wifi modules dieses esp32 boards, mit alternativer, non related firmware.
> 
> alternative procedure: crosscheck der identischen firmware auf einem weiteren, ähnlichen (esp32 board eines anderen herstellers) oder baugleichen esp32 board (zweites board des gleichen herstellers)
> 
> thx & greetings, metachuh.

Installiere gerade ESP32 Home, gebe danach direkt Info.

**Comment by SebiWolze** [comment]
> Statische IP in Ahoy oder DHCP ? Wenn Du statische IP hast, dann hoffentlich auch ein Gateway und DNS eingetragen ?

Wenn es an der IP liegen "würde", dann wäre diese ja nicht mal erreichbar und dann wieder nicht.
Im DHCP ist keine Reservierung eingetragen.
Ich habe es natürlich bereits mit einer static IP probiert, auch hier 1:1 selbes Fehlerbild.

Und ja, DNS und GW sind auch korrekt eingetragen.
GW ist ja erst einmal zweitrangig da sich ESP und meine Geräte im selben Netz/Subnetz befinden.

**Comment by SebiWolze** [comment]
> herzlich willkommen 😊
> 
> Die NTP Fehler waren eher so, dass hat keine Zeit geholt wurde, daher denke ich, dass das hier was anderes ist. Wenn ich es richtig verstanden habe, ist kein Zugriff auf die web UI möglich, da nur zwei pings durchgehen. Wurde per AP irgendwas neben dem lokalen WiFi konfiguriert? Lese des öfteren in letzter Zeit Probleme beim ESP32, aber nicht beim letzten stable Release

Danke fürs Willkommen :-)
Nein, nichts weiter konfiguriert.

In weiteren Versuchen dann NTP Server geändert.
Dann mal die IP static eingetragen. Dann 1. SSID, dann 2. SSID.
Ich habe wirklich alles probiert was mit dem Thema Netzwerk zusammenhängt.
Aber sobald die Settings drin sind und ein Reboot durchlief immer das beschriebene Fehlerbild.

**Comment by SebiWolze** [comment]
> @SebiWolze
> 
> > Arbeite im Bereich IT-Sec, Netzwerk/WLAN/ESP ist für mich täglich Brot, Antworten dürfen gerne technischer Natur sein.
> 
> sehr gut, wegen folgender procedure:
> 
> bitte flashe deinen esp32 mit einem anderen, non dtu related, projekt, zb. mit micropython, und richte damit das wlan ein. beobachte bitte dann das ping verhalten erneut.
> 
> reason: crosscheck der stabilen funktionalität des esp32 wifi modules dieses esp32 boards, mit alternativer, non related firmware.
> 
> alternative procedure: crosscheck der identischen firmware auf einem weiteren, ähnlichen (esp32 board eines anderen herstellers) oder baugleichen esp32 board (zweites board des gleichen herstellers)
> 
> thx & greetings, metachuh.

Okay nun wirds unangenehm... (hätte es selbst testen müssen!):

<img width="1211" alt="image" src="https://github.com/lumapu/ahoy/assets/20840531/6897449f-661c-4f97-9024-52864e967e63">

ESP32 Home selbes Fehlerbild.
Nach Connect 2 Pings, dann Schicht im Schacht.

Also ESP32 im Eimer?

**Comment by MetaChuh** [comment]
@SebiWolze
oje.

nicht zwingend komplett im eimer.
probier mal im wifi router andere kanäle im 2.4ghz bereich aus.
einige semi-faulty esp wifi module funktionieren dennoch auf spezifischen kanälen.

greetings,
metachuh

**Comment by SebiWolze** [comment]
> @SebiWolze oje.
> 
> nicht zwingend komplett im eimer. probier mal im wifi router andere kanäle im 2.4ghz bereich aus. einige semi-faulty esp wifi module funktionieren dennoch auf spezifischen kanälen.
> 
> greetings, metachuh

Sind Ubiquiti Wifi 6 LR APs.
Ich spiele mal etwas rum.
Gibt Erfahrungen welche 2,4Ghz Kanäle besser funktionieren?

**Comment by lumapu** [comment]
ich habe keine Erfahrung auf dem Gebiet, wieder daher sagen: ja kaputt
Finde gut, dass sich das Fehlerbild so eindeutig zeigt und damit klar wird wie es weiter geht.
Ist der erste Fall, wo ich von einem defekten ESP32 höre.
Du könntest den ESP noch 'nackt' machen und alles ablöten wie zb. NRF24, display und co. (Ich habe keine Idee was du schon dran gebaut hast)

**Comment by SebiWolze** [comment]
Habe soeben mein Rasenmäher WLAN fest auf einen Kanal gesetzt, BSS Transition abgeschaltet, APs rebooted.
Und... der Ping läuft nun seit 10min durch.

Ich installiere mal AHOY neu und melde mich dann.

Wenns daran lag fresse ich einen Besen und entschuldige mich eure Zeit gestohlen zu haben :(

**Comment by MetaChuh** [comment]
nur subjektive negativ und positiv erfahrungen, da stark abhängig von der auslastung in der umgebung.
rest ist leider trial and error.

recommended range: zwischen 1 und 11 und nicht darüber (ch12 und vermehrt ch13 gelten, vor allem auf den kleineren esp8266 als manchmal problematisch)

je nach umfeld und position des esp's, gibt es auch vereinzelt beeinträchtigungen, wenn mikrowellenherde in der nähe angeschalten werden, jedoch afawk nur wenn die mikrowellenherde in betrieb sind.

**Comment by SebiWolze** [comment]
Läuft nun auf Channel 6.
Läuft stabil.
Keinerlei Abbrüche mehr.

Ich werd verrückt...

Oh man oh man!

Danke euch allen!!!

**Comment by MetaChuh** [comment]
> Wenns daran lag fresse ich einen Besen und entschuldige mich eure Zeit gestohlen zu haben :(

don't worry,
statistisch gesehen ist dies für uns ein gutes bis perfektes issue handling, in den punkten short issue response time, short feedback response time, und hoffentlich short solution time.

greetings,
from all of us

**Comment by knickohr** [comment]
Ohne jetzt klug zu scheißen !  Mit Ubiquiti gab es schon öfters Probleme hier, vor allem mit mehreren APs.

Und ich würde trotzdem das GW eintragen, auch wenn’s das gleiche Subnet ist.

**Comment by Jumperm** [comment]
Hier hatten wir bereits das Thema der Mesh Systeme und Kanälen
https://github.com/lumapu/ahoy/issues/1307#issuecomment-1874609611
Bisher war das aber eher für Channel 12+ problematisch.

**Comment by Gubi2023** [comment]
ich dachte, das Channel-Problem wäre nur bei ESP8266 ?? Er hat doch anscheinend ESP32

**Comment by MetaChuh** [comment]
hi @SebiWolze 

wenn bei dir alles mit kanal 6 passt, bitte dieses issue als completed/solved schließen.
thx & greetings
