### ISSUE TITLE
Interrupt Pin working   False mit Antennenverlängerung

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#1564]
Hallo zusammen, 
nachdem ich seit Anfang an einen ESP8266 mir NRF24+ mit 3m Antennenverlängerung im Einsatz hatte, habe ich am Wochenende einen ESP32 mit ESP32-D0WD-V3 CHIP "zusammengebaut". Diesen wollte ich "nur" gegen den ESP8266 tauschen. Leider bekomme ich mit der 3m Verlängerung immer Interrupt Pin working False.  Mit der normalen Antenne kommt sofort True. Da ich den ESP im Keller liegen habe, wollte ich die nach Außen gelegte Antenne verwenden. 
Einen Test ESP32 mit o.g. Chip habe ich seit ca. 6 Monaten inkl. Display als Firmwareupdatertest laufen.  Auch damit klappt das Verlängerungskabel nicht.
Kondensatoren habe ich verbaut.
Hat jemand einen Tipp, warum ESP8266 funktioniert und ESP32 nicht?

**Comment by slg60** [comment]
Was nutzt du denn für eine Stromversorgung?

**Comment by dtuuser** [comment]
Den ESP8266 hatte ich parallel (nur Spannung) mit einer WEBCam an einem USB Port an einem ASUS Router. Die WEBCam zog 300mA und die restlichen 200mA haben bis zu 180 Tage ohne Reboot mit der 5.62 Version gereicht.

Der ESP32 läuft an dem Router nicht. Egal ob mit oder ohne Verlängerung. Interrupt Pin working ist dann immer False.
Er hat jetzt ein 2A USB Netzteil bekommen. Aber läuft nur ohne Verlängerung.

Ich teste das jetzt mal mit der normalen Antenne, habe aber die Befürchtung, dass es mit dem WR bei 14m Entfernung und einer 30cm Wand dazwischen zu Empfangsproblemen kommt, sobald im Garten zusätzliche Hindernisse wie Pool usw. aufgebaut werden. Daher die Antenne direkt im Garten.

**Comment by kiu77** [comment]
Du hast wahrscheinlich auch die Leistung des NRF24 höher gestellt, oder? Probier mal mit maximal low.

**Comment by dtuuser** [comment]
ne, von Anfang an immer low

**Comment by kiu77** [comment]
Das wundert mich aber mehr als üblich. Du kannst ja mal testweise den Antennenausgang kurzschließen. Läuft die Sache dann (was ich vermute), kommen wohl Störsignale über das lange Antennenkabel, denn die HF-Belastung reicht m.E. nach nicht für einen Absturz aus.

**Comment by Peertje-62** [comment]
Hi (my German is a bit rusty so I write in English, I can read German)

Does the ''old'' setup with the ESP 8266 and cable still work?
Which firmeware do you use on the ESP32?
(I would not recommend to short circuit the radio module ever)
maybe a broken antenne cable use an multi meter to check the cable!
regards Herman

**Comment by dtuuser** [comment]
Ja, der ESP3266 lief mit langen Kabel und 5.64 sehr stabil. Update auf eine neuere Version habe ich nicht mehr gemacht, da ich den ESP32 für stabiler halte und ich eine neuere Version haben möchte, da die neuen Versionen bei Unwettern und WR offline den Tageswert behalten. 
Und die History finde ich mega. Aktuell hat der ESP32 die 104. Auf einem Testsystem mit ESP32 und Display habe ich die 103

**Comment by Peertje-62** [comment]
Hi, 
In day time,
reconnect the  ESP3266 & cable again , does it still work? , if not cable defect you could measure it also.
I also would recommed you to use release 0.8.83 (or dev 0.8.97)
Regards

**Comment by Loetnase** [comment]
Nur aus Interesse, 
was hast du da verlängert, mit einem koaxialen Antennenkabel den Antennenstummel vom NRF24 oder mit einem 8 artigen normalen Kabel den NRF24 vom ESP8266?

**Comment by dtuuser** [comment]
Mit einem Koaxial Kabel die schwarze Antenne durch die Wand nach draußen verlängert.  Mit ESP8266 klappte das und mit dem ESP32 nicht mehr.

**Comment by dtuuser** [comment]
Hatte gerade etwas Zeit zum Testen.
Mit Version 8.110
Umschrauben im laufendem Betrieb. Kleine schwarze Antenne gegen die mit 3m Verlängerung. Empfang ist stabil.
Nach Reboot. Empfang ohne Probleme.
Nach "Stromausfall" (ziehen des Steckernetzteils (altes 2A Ladegerät vom Handy)) auch Empfang ohne Probleme.

Wurde seit der 8.108 irgendwas an der NRF24 geändert? Oder ist das bei mir jetzt eher Mr.Zufall?

**Comment by lumapu** [comment]
nachdem was ich gesehen habe wurde nichts geändert, also Zufall

**Comment by dtuuser** [comment]
Danke für die Rückmeldung. Ich beobachte das weiter. 

Schließe hier aber jetzt

**Comment by Blueschnulli** [comment]
Hi, seit dem letzten update habe ich das selbe Problem "
Interrupt Pin working false" zuvor 2 Jahre lang ohne Probleme, jetzt keine Verbindung mehr zu den Wechselrichtern, zudem gibt es keine Einstellmöglichkeit mehr zu Einstellen der Sendeleistung der NRF24

**Comment by Loetnase** [comment]
Ja seit zwei Jahren hat sich einiges getan.
Welche Version 0.1.??? hast du denn jetzt drauf?
Was für einen ESP hast du ESP32 oder 8266?
Ist die gelbe Leitung zwischen IRQ/GPIO16 und der Kondensator 100µF am NRF24 verbaut? Display und die zwei anderen Kondensatoren sind nice to have.
![grafik](https://github.com/user-attachments/assets/808acb87-1cbf-4720-b4fe-e66aeec090ad)

Probier mal diese Einstellungen für den NRF24

![grafik](https://github.com/user-attachments/assets/ff6973a7-7be8-4935-97a5-1fa29659367a)

Und hier die Einstellungen NRF24 Sendeleistung
![grafik](https://github.com/user-attachments/assets/a01b8296-aafd-4036-9a8d-ef1c45e1fd37)

Viel Erfolg
