### ISSUE TITLE
WiFi-Wizzard auf dem Mac, Umlautfehler im Button.

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#1569]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

≥ 0.8.97

### Github Hash

123

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

standard

### Debug Serial Log output

```shell
-
```

### Error description

Nur was Minimales:
Auf dem Mac gibt es einen Umlautfehler im Button "Prüfen" des Wizards.

![Bildschirmfoto 2024-04-05 um 10 59 41](https://github.com/lumapu/ahoy/assets/43971413/c5a98466-2da3-4751-a033-1a4f6a19e954)

**Comment by Gubi2023** [comment]
Fehler ist beim Windows-PC genauso vorhanden...

**Comment by MetaChuh** [comment]
zur ergänzung:
```diff
--- AhoyDTU versucht eine Verindung mit deinem Netzwerk herzustellen
+++ AhoyDTU versucht eine Verbindung mit Deinem Netzwerk herzustellen
```

**Comment by kiu77** [comment]
Des is halt wegen des Inderned, gell?

**Comment by lumapu** [comment]
> zur ergänzung:
> 
> ```diff
> --- AhoyDTU versucht eine Verindung mit deinem Netzwerk herzustellen
> +++ AhoyDTU versucht eine Verbindung mit Deinem Netzwerk herzustellen
> ```

ich musste jetzt 3x Mal lesen um den "groben" Fehler zu sehen 😊

**Comment by lumapu** [comment]
der Umlautfehler ist mir noch unklar, aber wahrscheinlich kommt der von der durchgehenden Großschreibung.

**Comment by Gubi2023** [comment]
> > zur ergänzung:
> > ```diff
> > --- AhoyDTU versucht eine Verindung mit deinem Netzwerk herzustellen
> > +++ AhoyDTU versucht eine Verbindung mit Deinem Netzwerk herzustellen
> > ```
> 
> ich musste jetzt 3x Mal lesen um den "groben" Fehler zu sehen 😊
Tippfehler ist auch in"  **_Verbindung_** mit Deinem Netzwerk hergestellt" so drin....

**Comment by lumapu** [comment]
@Gubi2023 verstehe nicht was du meinst. Ich habe zwei Fehler in dem Satz gesehen und behoben

**Comment by Gubi2023** [comment]
@lumapu : das Wort "Verbindung" ist in der Maske "Verbindung herstellen" und "Verbindung hergestellt" vorhanden.
(Kann die Masken leider nicht reproduzieren)

**Comment by lumapu** [comment]
danke für Aufklärung, jetzt hab ich's verstanden

**Comment by Gubi2023** [comment]
V8.108: in dieser Maske scheint der Tippfehler noch drin zu sein.    
<img width="974" alt="Screenshot 2024-04-10 173122" src="https://github.com/lumapu/ahoy/assets/142897856/1a0ac387-f68e-4f1a-88a4-6efe562e85f2">

**Comment by MetaChuh** [comment]
@kiu77 (aka pcbway-style sponsor für die gesamte community 😉)

schon 0.8.110 getestet, ob jetzt alles passt ?

@Gubi2023 die "Verindung" ist auch behoben.

thx

**Comment by kiu77** [comment]
0.8.110 läuft den ganzen tag problemlos.
