### ISSUE TITLE
Feature Request: Übertragung des unlimitierten P_AC-Wertes

### ISSUE THREAD

**Issue by Tjossul** [lumapu/ahoy#1570]
Hallo,

ist es möglich, den oben genannten Wert ebenfalls zu übermitteln?

Bsp.: Der WR hat gerade 1000 W AC. Ich muß auf 600 W limitieren. Neu wird jetzt P_AC natürlich limitiert angezeigt - 600 W. Ich würde aber unabhängig davon auch gern wissen (ohne aktiv die Limitierung aufheben zu müssen), was unlimitiert zur Verfügung stünde.

Vielleicht gibt es den Wert a auch schon irgendwo, und ich habe ihn nur übersehen?!

Vielen Dank und viele Grüße.
T.

**Comment by knickohr** [comment]
Das ist technisch nicht möglich weil der WR ja überhaupt nicht weiß was das Solarmudul gerade unlimitiert liefern könnte. Dazu müßte der WR ja die Leistung auch ausgeben und der Verbraucher es abnehmen.

**Comment by MetaChuh** [comment]
intern gibt es das nicht.

in den externen steuerungen berechne ich das so:
`p_ac_solar_unthrottled = opendtu_data[inverters][serial][AC][0][Power][v] / opendtu_data[limit/status][serial][limit_relative] * 100;`

optional: fail-safe gedeckelt auf den maximalwert des inverters:
```
if(p_ac_solar_unthrottled > opendtu_data[limit/status][serial][max_power]) 
{
	p_ac_solar_unthrottled = opendtu_data[limit/status][serial][max_power]
}
```

zusatz, da du die bezechnung `p_ac` verwendet hattest, hier cross project für ahoydtu:
`p_ac_solar_unthrottled = ahoydtu_data[inverter/id][x][ch][0][2] / ahoydtu_data[inverter/id][x][power_limit_read] * 100;`

greetings,
metachuh

**Comment by Tjossul** [comment]
Oh, super - das hilft mir (bei meinen Steuerungen) tatsächlich sehr!

Danke, Mann!

Grüße!
T.
