### ISSUE TITLE
[Bug] Haken bei Zugriffsschutz lassen sich teilweise nicht löschen

### ISSUE THREAD

**Issue by lille2000** [lumapu/ahoy#1574]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.97

### Github Hash

?

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

de-all, Display, Inverter, kein MQTT 

### Error description

Ich kann die Haken bei „Zugriffsscutz“ nicht alle löschen. 
Man kann alle Haken löschen und nach dem Reboot ist es wie vorher eingestellt, bis auf: 
Wenn ich versuche, den letzten Haken bei „Index“ zu entfernen, werden nach den Reboot wieder alle angehakt bis auf „Daten“ und „Verlauf“.

Im json Export fehlen auch alle Einstellungen zum „Zugriffsschutz“

**Comment by Peertje-62** [comment]
Hi,
the work around would be (for now) to set no admin password.
regards

**Comment by MetaChuh** [comment]
@lille2000 
kannst du rausfinden, wieviele versionen du zurückgehen musst, damit dies wieder funktioniert ?
bzw gegebenfalls bei interesse versuchen auch neuere versionen zu probieren, ob sich diesbezüglich was ändert ?

**Comment by MetaChuh** [comment]
ahhhh, ich glaube ich verstehe:
ja, wenn man ein passwort gesetzt hat, und dann trotzdem alle haken versucht zu entfernen, gehen alle haken in werkseinstellung.

also ist @Peertje-62 's antwort kein workaround, sondern die korrekte vorgangsweise.
bitte lösche das passwort aus der ahoydtu einstellung, wenn du den schutz komplett deaktivieren willst, statt passwort zu lassen und alle haken abwählen.

fehlt dies in der doku ?
ich bilde mir ein es war irgendwo drin

**Comment by MetaChuh** [comment]
> Im json Export fehlen auch alle Einstellungen zum „Zugriffsschutz“

diese sind vorhanden, nur nicht leicht erkennbar: `"prot_mask": 60,`
geht nach dem 7 bit binär schema 1+2+4+8+16+32+64
60 zb ist 0011110 wobei 0 deaktiviert und 1 aktiviert bedeutet.

das entspricht vertikal im web interface den 7 optionen:
`Index        ` &#9744;
`Daten        ` &#9744; 
`Web Konsole  ` &#9745;
`Einstellungen` &#9745;
`Update       ` &#9745;
`System       ` &#9745;
`Verlauf      ` &#9744;

**Comment by lille2000** [comment]
Danke, dann habe ich das tatsächlich übersehen.
