### ISSUE TITLE
Ahoy update 0.8.83 (rel) to 0.8.106 (dev) - WiFi disconnect

### ISSUE THREAD

**Issue by nexulm** [lumapu/ahoy#1575]
After upgrading from 0.8.83 due to the HomeAssistant MQTT discovery issue to the latest development version 0.8.106 my AhoyDTU (based on ESP8266) isn't reachable anymore.
DTU was in AP mode afterwards, connection via SSID AHOY-DTU was pssoible and the Installation Wizard Welcome with setup for WiFi network occurs.
Stopping the wizard shows the old working NRF24 configuration and setup including MQTT but the WiFi "home" connection isn't working anymore. "Next" button to configure up the WiFi network again doesn't seem to wrok for me at all. 
Any suggestion w/o reflashing the device?

Maybe I'll give it a try later to reflash it via the AHOY-DTU WIFI network on 192.168.4.1 before doing it from scratch via USB-reflashing. :-(

**Comment by nexulm** [comment]
After downgrading to 0.8.84 via AHOY-DTU SSID to have the HA MQTT discovery fix available the DTU is working again w/o any further configuration steps.
...BUT...
Updating to the latest dev (here: 0.8.106) isn't working for me out of the box.

**Comment by Gubi2023** [comment]
i also have always problems with connecting to home-Wlan by OTA. Maybe all three input boxes must be filled correctly, that transformation to home-Wlan works.... So when i let second input-box empty and use tooltips, it doesn´t work

**Comment by lumapu** [comment]
Thank you for reporting, I will look into that. The itention is to fill only the first and last field.

**Comment by nexulm** [comment]
> i also have always problems with connecting to home-Wlan by OTA. Maybe all three input boxes must be filled correctly, that transformation to home-Wlan works.... So when i let second input-box empty and use tooltips, it doesn´t work

OTA was working for me since updating from the official releases...
0.7.36 => 0.8.34 => 0.8.36 => 0.8.83
...and doesn't work anymore with dev 0.8.106 yesterday (OTA update OK but not connected to configured WiFi anymore, only AHOY-DTU AP was available).
I'll stay with 0.8.84 for now and wait for the next release with a fix by lumapu. :-)

**Comment by Gubi2023** [comment]
same behaviour at me with V0.8.110:
every morning the DTU only is reachable over AHOY-DTU AP. After Power off/on it is visible in my home-Network and works!
(Es nervt aber, wenn man jeden morgen das Teil áus und wieder einstecken muss) Bin ich der einzige mit dem Problem??

siehe auch https://discord.com/channels/984173303147155506/1029761098381017098/1228075094904143954

**Comment by Jawada74** [comment]
> same behaviour at me with V0.8.110: every morning the DTU only is reachable over AHOY-DTU AP. After Power off/on it is visible in my home-Network and works! (Es nervt aber, wenn man jeden morgen das Teil áus und wieder einstecken muss) Bin ich der einzige mit dem Problem??
> 
> siehe auch https://discord.com/channels/984173303147155506/1029761098381017098/1228075094904143954

I have the same behavior even during daytime and even after resetting at the morning now. DTU looses wlan connect.  After  reboot via unpluggin WLAN  reapppears  without any problem. I f any additional info are need feel fre to ask.
( Gleiches Problem hier mit der V0.8.110 kam von einer V0.8.97  seltsam ist, das es jetzt auch tagsüber passiert obwohl am morgen resettet wurde.. Wenn ich noch weiter in fo bereitstellen soll einfach bescheid geben)

**Comment by technics42** [comment]
Just fyi, I am using v0.8.101 and don't have this issue, although disabling wifi at night.

**Comment by Jawada74** [comment]
I reverte from 08.110 to 08.97 and ervthing is fine again.

**Comment by nexulm** [comment]
like to confirm that 0.8.111 fixes this issue for me. 0.8.84 was running before (= stable v0.8.83 + HA MW
DTU was directly accessible for me as expected after updating and is now running for mor than 2h.

AhoyDTU WebUI:
You are using development version 0.8.111. In case of issues you may want to try the current stable release: 0.8.83

**Comment by Gubi2023** [comment]
tja, bei mir hat die DTU auch mit 0.8.111 das heimische WLAN verloren, nur über AHOY-DTU-AP erreichbar. 2x in 24 Std.
Ursache unklar.

**Comment by Jawada74** [comment]
Habe jetzt auch das update von 0.8.97  auf 0.8.111 gemacht und bei mir ist die erste Nacht gut verlaufen. WLAN-Verbindung war morgens noch da. Ich beobachte weiter...

**Comment by lumapu** [comment]
sehr gemischte Gefühle hier. Gibts schon neue Erkenntnisse?

**Comment by nexulm** [comment]
Da ich das Ticket geöffnet habe schließe ich es hiermit auch. :-)
Der gemeldete Fehler ist behoben und die 0.8.111 läuft bei mir seit 4 Tagen zu diesem Thema unauffällig und stabil.
Weitere hier gemeldete Instabilitäten (?) sollten dann imho in einem neuen spezifischen Ticket eröffnet oder fortgeführt werden.
Danke lumapu für den schnellen Bufix!
