### ISSUE TITLE
Falsche und doppelte Summary (sporadisch)

### ISSUE THREAD

**Issue by slg60** [lumapu/ahoy#1579]
## Hardware
  * [X] CMT2300
  * [X] ESP32
  

### Version / Git SHA: 
Version: 0.8.101

Bekomme immer mal wieder eine falsche und doppelte Summary.

![Screenshot_20240409-133106~2](https://github.com/lumapu/ahoy/assets/165797359/a9ad5ba1-5f2f-4ce4-882e-588f5e42e741)

Problem tritt sporadisch beim Aufruf über ein Android Smartphone Google Pixel8 mit Chrome Browser auf. Die Summary wird gedoppelt und die Werte stimmen alle nicht. Beim nächsten aktualisieren ist alles wieder normal und alle Werte passen wieder. Das Problem lässt sich nicht wirklich provozieren, tritt nur hin und wieder auf. Ist da was bekannt?

**Comment by slg60** [comment]
Das Problem konnte ich übrigens bei älteren Versionen mit einem 8266 und nrf auch schon mal beobachten....

**Comment by Peertje-62** [comment]
Hi,
occasionally, I´ ve had the same, think it is the BROWSER-Cache.
https://de.wikipedia.org/wiki/Browser-Cache
Regards

**Comment by lumapu** [comment]
Das Verhalten ist bekannt. Evtl. baue ich mal eine Sperre ein, weiß aber nicht wie viel das bringt.

**Comment by geronet1** [comment]
Das hab ich öfters gesehn wenn die Netzverbindung etwas lahm war.. man kann ja in Chrome die Geschwindigkeit drosseln

**Comment by lumapu** [comment]
danke für den Tipp, dann kann man besser an den Problem arbeiten 😃

**Comment by Dirk-Ahoy** [comment]
Ich hab das auch nur mal sporadisch am Handy - könnte echt mit der Geschwindigkeit der Netzwerkverbindung zu tun haben...

**Comment by slg60** [comment]
Die Frage ist, wenn das aus dem Cache kommt, warum nur manchmal und warum solche Fantasie Werte. Die total Werte zb hat die Anlage noch gar nicht geschafft, stehe noch unter 100kwh.

**Comment by kiu77** [comment]
Ich hab das selten gehabt, aber wenn dann, wenn sich der ESP verheddert hatte und sehr träge reagiert hat.

**Comment by Gubi2023** [comment]
Problem tritt auch mit 0.8.127 noch sporadisch auf

![IMG_6607](https://github.com/lumapu/ahoy/assets/142897856/8b8038b0-083f-4f3f-bcf0-9a9c4cb26bd1)

**Comment by stefan123t** [comment]
Irgendwie schraubt er ja zweimal das HTML Dokument mit `<total> <total>` und den darunterliegenden Elementen zusammen.
Das sollte man also definitiv in den Developer Tools bzw. Source Code der Seite sehen können.
Auf der anderen Seite wäre es natürlich hilfreich, wenn man zu dem Zeitpunkt auch ein USB Console Log hätte, da sieht man dann ob und wo im Programm etwas schief geht.
Wie häufig ist das Problem denn ? Sporadisch ist ja eher alle paar Wochen oder so ?

**Comment by Gubi2023** [comment]
so oft schau ich nicht mit dem Handy drauf, aber heut hatte ich es 2x. Kommt aber nur kurz, nach ein paar sec. ist die Anzeige wieder normal.  Mich störts auch nicht weiter.
