### ISSUE TITLE
Mit ePaper kein nrf24 Empfang

### ISSUE THREAD

**Issue by Loetnase** [lumapu/ahoy#1580]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.106

### Github Hash

435aa17

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Mit ePaper habe ich keinen nrf24 Empfang.
ePaper deaktiviert, funktioniert die Kiste
![NRF24 mit Epaper](https://github.com/lumapu/ahoy/assets/120967249/ea0e94f7-ff9f-47d7-96f0-21d9b83c369a)
![NRF24 ohne Epaper](https://github.com/lumapu/ahoy/assets/120967249/9c616d77-9f67-427d-b1d3-060b3c0ca4bf)

### Error description

Mit ePaper habe ich keinen nrf24 Empfang.
ePaper deaktiviert, funktioniert die Kiste
![NRF24 mit Epaper](https://github.com/lumapu/ahoy/assets/120967249/daff8a19-aa1f-471
![NRF24 ohne Epaper](https://github.com/lumapu/ahoy/assets/120967249/283e1664-6a90-4657-8ec7-ccc0b13e9976)
2-9e2c-032712fc3e6c)

**Comment by MetaChuh** [comment]
hi @Loetnase 

ja, das e-paper ist ein krampf 😉
von störungen, reboots bis bootloops, keine graph, dafür schöne geisterbilder, schon alles gehabt.
(nur gekauft weil knickohr mir den floh ins ohr gesetzt hat, dann schnell wieder ausgemustert)

habs aber vor kurzem aus mangel an oled displays wieder reaktiviert, auf einer fusion mit standard fusion pinbelegung für e-paper und integriertes nrf modul und es geht halbwegs.
nrf stabil, ungeplante reboots "nur" 2 bisher (uptime 2t 16h mit epaper)

vielleicht hilft dir dieses pinout auch am ESP32-DOWDQ6:

<img width="902" alt="Bildschirmfoto 2024-04-09 um 18 03 46" src="https://github.com/lumapu/ahoy/assets/45773305/18ada68b-f821-49eb-84ca-aeec290a365e">

<img width="907" alt="Bildschirmfoto 2024-04-09 um 18 04 32" src="https://github.com/lumapu/ahoy/assets/45773305/71e67fc7-be5f-4533-a9f3-80f75a9be88c">

**Comment by lumapu** [comment]
für das epaper haben wir noch keinen SPI Hal, der ermöglicht die gleiche die Schnittstelle wie NRF, CMT und ETH zu verwenden. 
Daher kann es momentan nicht funktionieren. 
Die Geisterbilder sind bekannt, treten aber nicht überall auf. Reboots wegen epaper wäre mir neu.

**Comment by Edibo63** [comment]
Nachdem bei mir das gleiche Problem mit epaper auftritt - ohne reboots- ist es vielleicht besser 1573 zu closen und nicht in 2 verschiedenen issues weiterzumachen

**Comment by lumapu** [comment]
sehr gerne 😊

**Comment by knickohr** [comment]
Einspruch euer Ehren !

Das Problem tritt erstmalig mit der Version 0.8.104 auf. Alle Versionen davor funktionieren mit ePaper und nRF am ESP32 (kein S3 !)

Und ja, ePaper, nRF und CMT funktionieren nur mit dem Fusion-Board.

Ich muß wohl wieder öfters offizielle Ahoy-Versionen testen anstatt mich in ZE verewigen 🤪

**Comment by edw00d4711** [comment]
Bei mir lief es auch vorher. Jetzt leider nicht mehr. Und ich komme von weit unten. 231230_ahoy_0.8.35_86ff9f0_esp32.bin und davor lief es auch. Ich musste mal eines Tages das Verzeichnis einmal aufräumen :) Bitte wieder fixen.

Vielen Dank!

**Comment by knickohr** [comment]
103 funktioniert

Aber wenn Du von der 35 kommst wirst Du vermutlich auf noch andere Probleme stoßen 🫣

(Die aber mit den richtigen Einstellungen gelöst werden können)

**Comment by MetaChuh** [comment]
@Loetnase 
irgendwelche updates bei dir wegen dem e-paper display ?
egal ob pinbelegung ändern oder ältere firmware probieren ?

bei mir: gestern nacht noch 0.8.10 auf das fusion board mit dem waveshare e-paper (in der revision die auch knickohr hat) geflasht und funktioniert in punkto nrf24+ noch immer ohne hal, keine ahnung warum.

wenn du willst kann ich das nochmal auf einem az-delivery esp32 d0wd-v3 d1 mini mit nrf24l01+pa+lna und dem e-paper heute abend testen, was anderes hab' ich grad' nicht da.

**Comment by Loetnase** [comment]
@MetaChuh @knickohr 
zumindest keine positiven, ich habe heute Morgen mal die 0.8.110 eingespielt, das brachte keine Änderung. 
Dann schrittweise zurück, 0.8.103 läuft wieder, ab 0.8.104 geht mit ePaper nichts mehr.
In der Web Konsole bleibt das nach NTP bei der 104 einfach stehen.
![grafik](https://github.com/lumapu/ahoy/assets/120967249/a18f96d3-803d-4d96-9228-cde1b88289c6)
Mit deaktiviertem ePaper sieht das dann so aus, da kommen die Radio Infos und los geht es.
![grafik](https://github.com/lumapu/ahoy/assets/120967249/0c92a159-b791-4f6d-83d1-adbfacc55456)
Mit der 0.8.110 sieht das genau gleich aus.
Der Aufbau läuft schon längere Zeit, normaler ESP32, DukeWolle Board, Ebyte, ePaper 
Kannst ja mal testen aber oben schrieb lumapu das das aktuell nicht gehen kann.
Wäre aber schön wenn du was findest

**Comment by lumapu** [comment]
Gestern haben wir hoffentlich die Ursache gefunden. In diesem Branch https://github.com/lumapu/ahoy/tree/epd2_hal sind alle Änderungen enthalten, die rein theoretisch sogar Ethernet, CMT, NRF und ePaper am ESP32 unterstützten.
Wichtig ist zu wissen, dass pro SPI (HSPI, VSPI) nur 3 Geräte angemeldet werden dürfen und sich der CMT als zwei Geräte an dem SPI Bus anmeldet. Die Entscheidung an welchem Bus sich ein Gerät anmeldet hängt nur vom konfigurierten SCK ab.
Beispiel:
* HSPI (SCK = 14)
  * NRF
  * CMT
* VSPI (SCK = 18)
  * ePaper
  * Ethernet

demnach wäre sogar auf dem VSPI noch ein Gerät frei - da kommt dann irgendwann noch eine SPI-SD-Karte dazu 😉. Es geht natürlich auch in anderen Kombinationen, ich will diese aber nicht alle skizzieren.

[spi_fix_ahoy_preview_0.8.111.zip](https://github.com/lumapu/ahoy/files/15030670/spi_fix_ahoy_preview_0.8.111.zip)

Ich freue mich auf euer Feedback und würde das sehr gerne in den development Branch überführen und sehr bald auch ein Release draus machen.

**Comment by knickohr** [comment]
@lumapu 

Ist das mit dem Fusion-Board gegengeprüft ?  Es sind mittlerweile mehrere Hundert Boards im Umlauf, da kann man nicht so schnell mal ein paar Pins verändern 😲

Das würde mächtiges Geschrei geben 🫣

**Comment by lumapu** [comment]
@knickohr genau das ist mir heute Nacht auch gekommen - ich hatte ja auch geschrieben, dass noch keine Tests stattgefunden haben (oder nur sehr rudimentäre). Für das Fusion Board ist definitiv noch eine Änderung nötig. Danke für den Gedankenanstoß.

**Comment by Loetnase** [comment]
@lumapu @knickohr 
Das sieht für mich gut aus, 
die Standart 0.8.111 vom Server zeigt bei mir noch immer den gleichen Fehler wie oben,
die Zeit wird geholt und das war es, mit der 0.8.103 funktionier es aber.
Mit Display deaktiviert an Standart 0.8.111 funktioniert es auch wieder, also identisch zu meinem Post von oben. 

![grafik](https://github.com/lumapu/ahoy/assets/120967249/20835e97-0f02-4a77-94ad-fec20ca63bfd)

aber mit dem spi_fix von oben funktioniert es bei mir am normalen ESP32, DukeWolle Board, Ebyte, ePaper,
ruckzuck kamen nach dem Neustart die Werte
![grafik](https://github.com/lumapu/ahoy/assets/120967249/8ffbdd54-8772-40d1-b406-d7d48616f501)

Ich danke dir bzw. euch für den unermüdlichen Einstz

**Comment by Edibo63** [comment]
Habe von 0.8.103de auf preview 0.8.111 upgedatet.
NRF streht wieder auf connected.

**Comment by Loetnase** [comment]
@Edibo63 
bekommst du auch Daten und funktioniert das ePaper?

**Comment by Edibo63** [comment]
epaper funktioniert und Daten kommen rein.
Reboots konnte ich bis jetzt nicht festellen.

**Comment by Loetnase** [comment]
@lumapu @knickohr 
Das sieht für mich gut aus, 
die Standart 0.8.111 vom Server zeigt bei mir noch immer den gleichen Fehler wie oben,
die Zeit wird geholt und das war es, mit der 0.8.103 funktionier es aber.
Mit Display deaktiviert an Standart 0.8.111 funktioniert es auch wieder, also identisch zu meinem Post von oben. 

![grafik](https://github.com/lumapu/ahoy/assets/120967249/20835e97-0f02-4a77-94ad-fec20ca63bfd)

aber mit dem spi_fix von oben funktioniert es bei mir am normalen ESP32, DukeWolle Board, Ebyte, ePaper,
ruckzuck kamen nach dem Neustart die Werte
![grafik](https://github.com/lumapu/ahoy/assets/120967249/8ffbdd54-8772-40d1-b406-d7d48616f501)

Ich danke dir bzw. euch für den unermüdlichen Einsatz

Das hatte ich vor Tagen schon geschrieben, aber wohl nicht abgeschickt
Aber jetzt verspätet :-)

**Comment by MetaChuh** [comment]
@Loetnase 

danke und dein post ist jetzt doppelt drin, einmal vor 3 tagen und einmal von jetzt 😄
doppelt hält besser 😉

(wahrscheinlich hat sich nur der browser die session id beim erstellen gemerkt, und auch nach 3 tagen submit verzögerung, hat github dadurch dein original init datum als publish datum verwendet)

**Comment by lumapu** [comment]
jetzt muss ich es nur noch für das Fusionboard oder den ESP-S3 allgemein lösen

**Comment by MetaChuh** [comment]
@lumapu 

ich hab' grad ein fusion board mit e-paper und 2 aktiven nrf24+ hm invertern online zum testen, falls du was brauchst.
bei mir geht alles mit der normalen 111 und epaper.

![IMG_5130](https://github.com/lumapu/ahoy/assets/45773305/1bb67a52-0c76-4ab2-bc8c-c26bf8fdff0f)

**Comment by lumapu** [comment]
die Herausforderung wäre ESP32-S3 (aka Fusion) mit ETH, ePaper, NRF und CMT 😉. Ich hoffe die 0.8.112, die jetzt dann veröffentlicht wird kann das.

**Comment by edw00d4711** [comment]
Moin zusammen,

danke für die kontinuierliche Weiterentwicklung. 
Leider hab ich nicht alles verstanden... :) Was muss ich jetzt wie stecken und im Menu konfigurieren? Gibt es dafür ein Fritzing?

Danke!

**Comment by Loetnase** [comment]
@edw00d4711 da brauchst du aber mindestens einen ESP32 wie im Plan und funktionier aktuell aber nur unter ahoy.
CMT2300 anstatt NRF24 geht natürlich auch. 
Wenn du mehr zum epaper wissen möchtest, komm rüber ins Discord #support-ahoy
![grafik](https://github.com/lumapu/ahoy/assets/120967249/ac0bcaab-c62e-4faf-93da-cd915f3fc0f9)
![grafik](https://github.com/lumapu/ahoy/assets/120967249/4ca6f673-fae7-4b3d-bb0e-b4d2938d0610)

**Comment by edw00d4711** [comment]
@Loetnase Vielen Dank! Ich kontrollier erst mal meinen Aufbau und korrigiere den ggf. Ansonsten komme ich gerne in den Discord.

**Comment by Edibo63** [comment]
0.8.112 läuft problemlos.
Vielen Dank.

**Comment by Loetnase** [comment]
Also ich würde jetzt sagen das ursprüngliche Problem ist gelöst.
ePaper und NRF24 am ESP32 laufen bei mir wieder.

Dann hat sich bei mir aber leider das "Ghosting" am ePaper gezeigt welches ich vorher noch nie hatte.
Das werde ich aber noch ein bisschen anschauen und in einem neuen Issue melden. 
Schaut mal bei euch ob ihr da was am ESP32 und ePaper etwas vergleichbares seht.
![20240503_091846-1](https://github.com/lumapu/ahoy/assets/120967249/965f5b33-680f-473e-9eec-cdcf2a3c945f)
Somit werde ich dieses Issue schliesen.
Danke für eure Mithilfe.
