### ISSUE TITLE
link "Unterstütze bei der Dokumentation" funktioniert nicht mehr

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1587]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.100

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Seite "Index"

### Debug Serial Log output

```shell
Index
```

### Error description

Link geht ins Leere Siehe Video

https://github.com/lumapu/ahoy/assets/142897856/8e189290-0e39-4140-99a5-bbae8c861026

**Comment by MetaChuh** [comment]
hihihi, da passt ja der aufruf `Unterstütze bei der Dokumentation` haargenau 😂

**Comment by Gubi2023** [comment]
geht jetzt
