### ISSUE TITLE
MQTT send Button schickt ungültige Informationen ALARM_MES_ID

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#1591]
extra hier nochmal mit einem neu aufgesetzten dev 0.8.110 getestet:
![grafik](https://github.com/lumapu/ahoy/assets/105392164/8c61b198-5b03-45ba-a3c3-8f76b79f0df7)

Im Hintergrund läuft zur Überwachung der MQTT Explorer mit. Sobald ich in den Settings von AhoyDTU auf den Button
Discovery Config drücke, werden die Topics an HomeAssistant geschickt, im MQTT Explorer erscheint dann sofort ch0_ALARM_MES_ID das aber ungültig ist:

homeassistant/sensor/xxxx/ch0_ALARM_MES_ID

Wie kann das sein?

**Comment by knickohr** [comment]
Der Topic ist eigentlich obsolet. Die Daten kommen jetzt über einen JSON-Payload unter dem Topic …/alarm_data

**Comment by rmayergfx** [comment]
@knickohr 
Ich habe im Hintergrund MQTT Eplorer offen um zu sehen was passiert. Gehe ich in AhoyDTU auf den Button Send, erscheint automatisch ch0_Alarm_MES_ID, und das dürfte doch eigentlich gar nicht sein. Ich lösche das Topic und sobald ich auf den Button senden (Discovery Config ) gehe erscheint das Topic und das dürfte doch gar nicht sein, das macht mich stutzig.

**Comment by knickohr** [comment]
Dann isr dieses Discovery nicht mehr in Ordnung.

**Comment by rmayergfx** [comment]
Was meinst du damit? Fehler bei AhoyDTU?

**Comment by lumapu** [comment]
ja, wird entfernt, danke für den Hinweis

**Comment by rmayergfx** [comment]
Gerade getestet.... Fehler ist nicht mehr da....

**Comment by knickohr** [comment]
Bei der Gelegenheit kannste LastAlarmCode auch gleich raus nehmen 😉
