### ISSUE TITLE
calculation error (?)

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1592]
### Platform

ESP32

### Assembly

the DTU was already assembled

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.11

### Github Hash

4587c1c

### Build & Flash Method

ESP Tools (flash)

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Hello, hope I can clarify a calculation error,
have 2 inverters; HM 600 Max 456 Watt at 3:54 PM, HM300 Max 306 Watt 11:19 AM, in the web gui (Total) this adds up to 762 Watt Max which is not correct. In ''History'' the Max is 541 Watt which is the correct value (Also according to Grafana) Kind regards
![Max History](https://github.com/lumapu/ahoy/assets/144957788/146f1c7b-cd58-4661-9037-4cd881d8971c)
![Total](https://github.com/lumapu/ahoy/assets/144957788/3ce0c995-0dfe-460b-8fe2-fbe91148d582)

**Comment by hrolofs** [comment]
It looks that 762 are the sum of both max values and 541 are the max of the summary value of both inverter.

**Comment by kiu77** [comment]
Yes, this is not the first time mentioned. We have to wait until this will be fixed someday ;-)

**Comment by lumapu** [comment]
I'm waiting too 😂 - just a joke - have that on my list but was not solved until now

**Comment by Peertje-62** [comment]
Good Morning,
Must have missed it
Thx for the answer anyway
Have a nice day
regards ;-)
