### ISSUE TITLE
Nach Crash verbindet sich Ahoy nicht mehr mit dem stärksten AP

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#1596]
Seit der Version 103 verbindet sich das WiFi von Ahoy nicht mehr mit dem stärksten verfügbaren AP nach einem ungewollten Crash.

Ein weiterer manueller Reboot löst das Problem wieder.

**Comment by MetaChuh** [comment]
sprich er blieb bei dir im ap mode ?

**Comment by knickohr** [comment]
Nein, er verbindet sich bei mir mit dem zweitbesten AP

**Comment by Gubi2023** [comment]
kann ich so bestätigen, das beste WLAN wird nicht mehr gefunden/angezeigt

**Comment by knickohr** [comment]
Doch, angezeigt wird es. Und nach einem weiteren manuellen Reboot ist alles wieder OK.

**Comment by lumapu** [comment]
könnt ihr bitte nochmal ab der 0.8.112 testen?

**Comment by lumapu** [comment]
wie ist hier der aktuelle Status? Hat sich was geändert, oder weiterhin vorhanden?

**Comment by knickohr** [comment]
Mit der 0.0.123 nicht mehr beobachtet. Werde aber noch etwas warten mit dem closen 😉

**Comment by knickohr** [comment]
Leider ist es mit der 123 nachbeinem Crash immer noch 😢

**Comment by knickohr** [comment]
Das Problem scheint neuerdings auf die neue Funktion „dynamisches Smart-Repeating“ geschuldet zu sein. Denn Ahoy verbindet sich jetzt immer erst mit dem stärksten AP, fällt aber nach einigen Minuten bis Stunden wohl auf den von der Fritz!Box zugewiesenen AP zurück.
