### ISSUE TITLE
Wizard even after configuration

### ISSUE THREAD

**Issue by Argafal** [lumapu/ahoy#1597]
0.8.111 [GIT SHA: 388cd89](https://github.com/lumapu/ahoy/commits/388cd89)

Wenn ich auf /visualization geht, öffnet sich /wizard. Mein AHOY ist schon konfiguriert und im WLAN. Klickt man auf "stop wizard", wird man auf die nicht existierende 192.168.4.1 umgeleitet. @Dahlienhaus konnte das Problem ebenfalls reproduzieren.

**Comment by Argafal** [comment]
Is someone able to correct my typo in the title: "evven" -> "even"?

**Comment by MetaChuh** [comment]
@Argafal 

> Is someone able to correct my typo in the title: "evven" -> "even"?

yes ... for example you can 😉
just hit the <kbd>Edit</kbd> button on the right side of the title, as seen at the screenshot below:

<img width="143" alt="Bildschirmfoto 2024-04-24 um 15 45 42" src="https://github.com/lumapu/ahoy/assets/45773305/7f3ac8fe-97af-4b56-9b2d-560bc895a1fa">

**Comment by Argafal** [comment]
> @Argafal
> 
> > Is someone able to correct my typo in the title: "evven" -> "even"?
> 
> yes ... for example you can 😉 just hit the Edit button on the right side of the title, as seen at the screenshot below:
> <img alt="Bildschirmfoto 2024-04-24 um 15 45 42" width="143" src="https://private-user-images.githubusercontent.com/45773305/325245124-7f3ac8fe-97af-4b56-9b2d-560bc895a1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjY4MjIsIm5iZiI6MTcxMzk2NjUyMiwicGF0aCI6Ii80NTc3MzMwNS8zMjUyNDUxMjQtN2YzYWM4ZmUtOTdhZi00YjU2LTliMmQtNTYwYmM4OTVhMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzNDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNWJhZjVmYWUyOTAzNWEzMzIxNTRkYjE1NDk4N2Y5ZWI2MTE1ZjY5NGRiYjM3YmY4MTUzNjg0YjZmYzIwYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LUT3sVXCtWSvt3oOX36XUk8_JIRngNTcvJxWcsjzQbI">

Nice, thanks for pointing that button out to me!

**Comment by lumapu** [comment]
@Argafal das heißt nicht `/visualization` sondern `/live`. Aber allgemein ist da mit dem Wizard noch was im Argen

**Comment by MetaChuh** [comment]
@lumapu 

kannst du das reproduzieren ? ich noch nicht.

wenn ich auf `http://ahoy_ip/visualization` gehe
(oder egal was nicht existiert) 
werde ich korrekt auf `http://10.10.10.41/index` umgeleitet.

jedoch glaube ich das da was dran sein kann, nachdem dahlienhaus dies reproduzieren konnte.
kann der browser cache schuld sein ?

**Comment by lumapu** [comment]
das kann man reproduzieren, indem man mit dem AP des ahoy verbunden ist, da dann der Default `http://192.168.4.1/wizard` ist. Wenn der AP aus ist, dann kommt man nach `http://192.168.4.1/index`
