### ISSUE TITLE
dark mode - pop up´s X for closing them is in black

### ISSUE THREAD

**Issue by tqma1** [lumapu/ahoy#1598]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.111

### Github Hash

388cd89

### Build & Flash Method

ESP Tools (flash)

### Setup

dunkler Modus aktiviert

### Error description

Im dark Mode - dunkler Modus sind die X zum schliessen der Fenster leider auch in schwarz und somit eigentlich unsichtbar.
Man findet diese nur in dem man mit der Maus darüberfährt.
Betrifft alle Versionen

**Comment by MetaChuh** [comment]
das ist ein feature: extra-dark mode 😉

<img width="821" alt="Bildschirmfoto 2024-04-24 um 16 21 21" src="https://github.com/lumapu/ahoy/assets/45773305/641b07ec-eabc-4b67-a24c-488a6b292996">

![image](https://github.com/lumapu/ahoy/assets/45773305/72cd7632-7579-40f4-8679-41d4277f8577)

**Comment by Ollipop030** [comment]
Bei mir im Brave siehts so aus:

![image](https://github.com/lumapu/ahoy/assets/121013633/7d2d7aec-2863-42a7-b992-f3d0993f6cf2)

.111 englisch, ESP32.
