### ISSUE TITLE
[Bug] No Internet but WLAN - DTU not working

### ISSUE THREAD

**Issue by jschwed** [lumapu/ahoy#1603]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.83

### Github Hash

idontknow

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Hoymiles HM 800 
NRF24L01
invertert: intervall set to 15 sec

### Error description

currently we don't have an internet connection
local WLAN is fine, router+access point are working. I can access local devices within home WLAN

when checking http://ahoy-dtu/live the data shown there is outdated/ not updated

I can access DTU/ahoy settings incl. ie login, settings, system...
seems like the the inverter/ DTU needs an internet connection to visualize inverter live data, which is strange. It should be local, right?

Any further questions/ info I need to provide, please let me know.

**Comment by MetaChuh** [comment]
@jschwed 

try to sync your time from your browser on the ahoydtu (see screenshot)
by using: set system time <kbd>FROM BROWSER</kbd>

the ahoydtu time has to be set in order to communicate with the inverters.

<img width="1131" alt="Bildschirmfoto 2024-05-01 um 20 38 08" src="https://github.com/lumapu/ahoy/assets/45773305/316d2e6e-3b2e-4d9f-a0ed-eda1b07a7778">

note:
alternatively, once you have internet again, you can update your ahoydtu with the latest developer firmware, which supports inverter communication without a valid time.

firmware download for ota installation:
https://fw.ahoydtu.de/fw/dev%2Fahoy_v0.8.114/

direct firmware update via web browser:
https://solar.metacontrol.eu/ahoydtu-webflasher/

**Comment by jschwed** [comment]
thanks! 
you're right, system time is 1970-01-01 ....
I tried your solution, but it doesn't work.

a) when changing the settings, system time is shown correct, but polling does not start.
b) when changing the settings, save and reboot --> system time is again at 1970-01-01

**Comment by Gubi2023** [comment]
ist das nicht dieses Fehlerbild?  https://github.com/lumapu/ahoy/issues/1593#issuecomment-2069639290

**Comment by MetaChuh** [comment]
@Gubi2023 

> ist das nicht dieses Fehlerbild? https://github.com/lumapu/ahoy/issues/1593#issuecomment-2069639290

danke dir.
ich bin mir nicht ganz sicher, weil das betraf den reinen ap modus ohne wlan.
hier ist die dtu mit dem lokalen wlan verbunden, jedoch das internet ausgefallen/gesperrt.
nach zeit aus browser setzen, sollte eigentlich die inverterkommunikation mit der alten v0.8.83 funktionieren.

@jschwed 
if you have a mobile hotspot, you could download and update your dtu to v0.8.114 (links above)
then activate the inverter setting `Start communication without valid time`

screenshot of this setting (german version)
<img width="611" alt="Bildschirmfoto 2024-05-02 um 13 01 18" src="https://github.com/lumapu/ahoy/assets/45773305/63ff8561-e414-4c33-bed6-74dd568e13ec">

greetings,
metachuh

**Comment by jschwed** [comment]
@Gubi2023 : I don't see it's the same error. WLAN (local network) is fine and DTU logged in as-well, ie I could login into settings.

@MetaChuh : thanks. Internet is back since this morning. I would prefer not to go to a beta version this time, but will check with the next release.

Thanks for your quick responses! Great experience. 
From my pov this bug can be closed, but can also keep it open if you need a final test from my side with the next release.
Best regards!

**Comment by MetaChuh** [comment]
@jschwed 

many thanks for your feedback and congrats that your internet is working again 👍

regarding the next release vs. dev versions:
we can understand this.

regarding the closing of this issue:
we'd prefer, if possible, that you close this issue yourself (at the next release) if satisfied, as it most certainly fixes this scenario.
if you don't have time to do so, no problem.

thanks and greetings,
metachuh

**Comment by jschwed** [comment]
@MetaChuh : sure, will do. Looking forward to the next release! :-)
