### ISSUE TITLE
[Bug]V0.8.116: added max inverter temperature leider nicht komplett sichtbar

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1605]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.116

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

update letzte dev

### Error description

 screenshot PC
![IMG_5803](https://github.com/lumapu/ahoy/assets/142897856/bea8be3f-beef-4137-8ea7-de585bf333c9)

Screenshot I-Phone
![IMG_5807](https://github.com/lumapu/ahoy/assets/142897856/291bc2c7-5968-45de-952d-615705cbb64a)

**Comment by Loetnase** [comment]
Könnte man die maxtemperatur nicht einfach unter die aktuelle Temperatur schreiben, ohne Datum und ohne Sekunden? Ich gehe davon aus das ist die maximale Temperatur des Tages, nicht sei letztem dtu Start. In etwa so wie auf meinem Bild unten dran.
Das ist aus einem Screenshot vom tablet. Ist auch oben abgeschnitten.
![20240505_215246](https://github.com/lumapu/ahoy/assets/120967249/f035ce59-1457-45ae-adbc-9ea2ff307936)

**Comment by Gubi2023** [comment]
nicht perfekt, aber besser...
![ahoy](https://github.com/lumapu/ahoy/assets/142897856/ec03a9e2-313a-4bb2-8b03-5f16f065974c)
