### ISSUE TITLE
ESP32 116 bootet um 0 Uhr

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#1607]
Moin zusammen,

mein ESP32 mit der DEV 116 bootet um Mitternacht, obwohl der Haken nicht gesetzt ist. 
Auch ein Setzen --> Neustarten --> Wieder wegnehmen --> Neustarten  hat nicht geholfen.

**Comment by mellow5** [comment]
Ich schließe mich dem an. Ich habe es schon seit der 0.8.115 bemerkt.

**Comment by jimknopf63** [comment]
Kann ich nicht bestätigen, meiner läuft seit 18 Std. mit DEV 116. Das entspricht der Zeit des Updates. Auf zwei ESP32 in verschiedenen Haushalten. Vllt wichtig. Habe nur NRF Antenne verbaut und 1.3 Display

**Comment by dtuuser** [comment]
Bei mir auch nur NRF24 mit externer Antenne und Display. Bei einer anderer DTU ohne Display mit 113 keine Probleme.

**Comment by kiu77** [comment]
Bei mir wird um Mitternacht auch neugestartet (oder die Uptime falsch angezeigt). Es sollten nur die Werte um Mitternacht gelöscht werden.

![Bildschirmfoto 2024-05-07 um 12 25 38](https://github.com/lumapu/ahoy/assets/43971413/4080a13c-7d82-480b-8bcf-9a9f27699c58)

**Comment by Loetnase** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/120967249/c25c964f-e602-4e9b-9650-ed5a01aa2c1f)
Kann ich nicht bestätigen, meiner lief seit gesten Morgen durch, zumindest laut Uptime.
ESP32 mit ePaper und NRF24 :thinking:

**Comment by kiu77** [comment]
@Loetnase 
Wie sind denn Deine Einstellungen?

**Comment by MetaChuh** [comment]
verified: ich kann den reboot um 00:00h mit v0.8.116 reproduzieren.
einstellungen wie bei @kiu77

**Comment by dtuuser** [comment]
Bei mir auch nach Re-Update. Reboot um 0 Uhr

**Comment by GrisuXX** [comment]
Dito, auch bei mir um 0Uhr ein reboot.
Mit ESP32, NRF24 und obigen Einstellungen
Ohne Display.

**Comment by Loetnase** [comment]
Da muss ich euch enttäuschen, bei mir kein Reboot, bei drei parallelen Systemen 
![grafik](https://github.com/lumapu/ahoy/assets/120967249/d4ea0618-0260-47d7-8f54-884e364f13da)
schaut auch mal hier 
https://discord.com/channels/984173303147155506/1075313280312152156/1237678682261291028
da stehen alle meine Einstellungen

**Comment by Loetnase** [comment]
Passt das hier gerade vom Discord da auch irgendwie mit ins Bild
![grafik](https://github.com/lumapu/ahoy/assets/120967249/7a62ad97-47ec-4963-b334-ee66f7fcdfca)

**Comment by kiu77** [comment]
@Loetnase 
Du hast andere Einstellungen bei den invertern, setzt die Werte also nicht Nachts zurück.
Das hat immerhin weitergeholfen, als man zumindest den oberen Haken bei den invertern gesetzt haben muss, wenn man einen Reset ernten will.

**Comment by Loetnase** [comment]
Okay, das passt.
Ich will und brauche ja auch keinen Reset. 
Wenn ich die alten Werte sehe bis der Inverter aufwacht ist das für mich gut.

**Comment by Dirk-Ahoy** [comment]
Hab das gleiche Problem - alle DTUs mit .116 rebooten püntktlich um 0:00  Habe nur Werte und Gesamtertrag um Mitternacht zurücksetzen aktiv.

**Comment by sumerland** [comment]
Gleiches Problem unter 116 mit selbstgebauter DTU, NRF24 und ohne Display. Habe nun auch alle Haken bzgl Wertereset rausgenommen. Werden die eh genullt wenn der Inverter aufwacht?

**Comment by MetaChuh** [comment]
@sumerland

> selbstgebauter DTU, NRF24 und ohne Display

dies macht wahrscheinlich keinen unterschied, jedoch super, dass du dies unaufgefordert teilst.
much appreciated.

> Habe nun auch alle Haken bzgl Wertereset rausgenommen. Werden die eh genullt wenn der Inverter aufwacht?


wenn unsere theoretische analyse stimmt, dann ja.
ausnahme sind inverter mit batterieeinspeisung.

thx & greetings

**Comment by Loetnase** [comment]
@sumerland 
Das musst du anders rum sehen. Wenn der Inverter einschläft bleiben die letzten Werte in der DTU stehen z.B. Tagesertrag bis am Morgen der Inverter wieder aufwacht und neue Werte schickt welche mit 0 beginnen. 
Wenn du nur die Werte anschaust (wie ich) ohne irgendwelche Auswertungen dahinter ist das passend. Wenn jemand z.B. Tageswerte oder Maxwerte  abspeichert macht es Sinn die um Mitternacht zu nullen. Oder bei Batterieeinspeisung wenn der Inverter dauernd Strom hat und nie schlafen geht.

**Comment by dtuuser** [comment]
Topp. Kein Reboot mehr.
Vielen Dank

**Comment by GrisuXX** [comment]
Heute Nacht kein Reboot mit der 0.8.117 👍

**Comment by MetaChuh** [comment]
@dtuuser 

super, danke dir für das feedback.
wenn bei dir alles bzgl. reboot um 00:00h passt, schließe bitte dieses issue.

verified: v0.8.117 auch bei mir kein reboot mehr um 00:00h, thx @lumapu 

greetings,
metachuh
