### ISSUE TITLE
[Bug] 8266 always starts in AP-mode since 0.8.112

### ISSUE THREAD

**Issue by IgelCampus** [lumapu/ahoy#1608]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.111

### Github Hash

388cd89

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Standard single inverter setup

### Error description

When updating to any version after 0.8.111 the AHOYDTU AP-mode is used instead of the configured WIFI connection.
Just tried this with 0.8.115 and 0.8.116 again with the same result. The last reliable version was 0.8.111 where the WIFI connection is established pretty much immediately after booting.

FYI: I am using several Mikrotik cAP ac access points for the WIFI.

**Comment by MetaChuh** [comment]
@IgelCampus

can you please try to set the mikrotiks to fixed 2.4ghz channel 11, and report if this problem still persists on an esp8266 after a reboot and/or initial setup ?

thx & greetings,
metachuh

**Comment by IgelCampus** [comment]
I modified the Mikrotik configuration to always use channel 11 but unfortunately ahoy is still always in AP mode after a reboot. When completing the wizard, ahoy connects to the correct wifi network and is reachable as expected. But after the next reboot the game starts again.

**Comment by rori1977** [comment]
I can confirm the exact same behaviour. Reproducible when updating from 111 to 115, from 115 to 116. And also today when upgrading to 118.

After reboot, page opens on the "Wizard"-Page. 
When clicking "Stop wizard" it redirects to 
http://192.168.4.1/index

**Comment by lumapu** [comment]
will work on this topic next, thanks for confirming.

**Comment by cibis8** [comment]
Bei mir das gleiche.. ab der 111 kann ich keine statische IP mehr definieren... er nimmt sich eine aus dem DHCP Bereich.

**Comment by lumapu** [comment]
sorry forget about this one, need to focus on this ... please remind me if I do not respond within one week

**Comment by lumapu** [comment]
is it related to static IP configuration? As I tried now with 0.8.122 I can't see the issue here. Will now try with static IP.
For static IP there is another issue around here.

**Comment by cibis8** [comment]
Nach dem Update auf eine Version höher 111 kann ich nicht mehr eine feste IP eingeben. Geht nur noch via DHCP.

**Comment by rori1977** [comment]
I upgraded from 118 to 123 without any problems upon restart today.

**Comment by IgelCampus** [comment]
I can also report success after upgrading from 111 to 123. Restart and Wifi reconnect just worked fine.

**Comment by IgelCampus** [comment]
Unfortunately the fix is unstable and reboots the 8266 every few minutes.

**Comment by rori1977** [comment]
The wizard-issue is fixed for me, however, I can confirm that 123 is not as stable as 118 (which had an uptime of 18 days when I upgraded). 123 seems to reboot at least one or twice a day for me.
