### ISSUE TITLE
Frage, wie mach ich es richtig damit die Maximalwerte gelöscht werden?

### ISSUE THREAD

**Issue by ralfberger** [lumapu/ahoy#1609]
## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna (SMA)

### Version / Git SHA: 
Version: 0.8.8.3

* Wechselrichter : Hoymiles HM1500

Frage, muss ich noch etwas aktivieren damit die max. Tageswerte Mitternachts gelöscht werden?
_'Kommunikation während der Nacht pausieren'_ ist auch aktiviert, aber die Werte werden nicht gelöscht.
![Screenshot_1](https://github.com/lumapu/ahoy/assets/63057484/8396a498-475a-4d14-a19a-3d890a99ee25)

![Screenshot_1](https://github.com/lumapu/ahoy/assets/63057484/25b428e5-434e-429a-ace8-00665509c43a)

Ich speichere die Werte in InfluxDB, und dort steht morgens als erster Wert der vom Vortag. Da mir der Unterschied zwischen  "_Werte und Gesamtertrag um Mitternacht zurücksetzen_" und "_Max## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna (SMA)

### Version / Git SHA: 
Version: 0.8.8.3

* Wechselrichter : Hoymiles HM1500

Frage, muss ich noch etwas aktivieren damit die max. Tageswerte Mitternachts gelöscht werden?
_'Kommunikation während der Nacht pausieren'_ ist auch aktiviert, aber die Werte werden nicht gelöscht.
![Screenshot_1](https://github.com/lumapu/ahoy/assets/63057484/8396a498-475a-4d14-a19a-3d890a99ee25)

![Screenshot_1](https://github.com/lumapu/ahoy/assets/63057484/25b428e5-434e-429a-ace8-00665509c43a)

Ich speichere die Werte in InfluxDB, und dort steht morgens als erster Wert der vom Vortag. Da mir der Unterschied zwischen  "_Werte und Gesamtertrag um Mitternacht zurücksetzen_" und "_Maximalwerte mitternachts zurücksetzen_" nicht bewusst ist, habe ich beides aktiviert, oder ist es besser wenn ich nur eins von beiden auswähle?
Danke und Grüße

imalwerte mitternachts zurücksetzen_" nicht bewusst ist, habe ich beides aktiviert, oder ist es besser wenn ich nur eins von beiden auswähle?
Danke und Grüße

**Comment by MetaChuh** [comment]
@ralfberger 

ja, beides aktivieren, wie auf deinem screenshot, ist die korrekte einstellung.
`Werte und Gesamtertrag um Mitternacht zurücksetzen` und `Maximalwerte mitternachts zurücksetzen`,

wichtig, falls du einen oder mehrere der inverter für batterie einspeisung verwendest:
dann müssen diese inverter zusätzlich täglich um 23:59h per reboot befehl neu gestartet werden,
damit auch inverterseitig die werte zurückgesetzt werden.
(sonst holt sich die ahoydtu nach ihrem eigenen wertereset die noch nicht zurückgesetzten werte aus dem inverter zurück)

<img width="839" alt="Bildschirmfoto 2024-05-09 um 11 13 36" src="https://github.com/lumapu/ahoy/assets/45773305/6c585bc7-4c99-4d48-acad-ab40be214c9f">

greetings,
metachuh

**Comment by ralfberger** [comment]
Nein ein Batteriespeicher habe ich nicht. 
Merkwürdig das die Werte trotzdem nicht zurückgesetzt werden. 
Ich werde Ahoy neu starten und abwarten was mir morgen angezeigt wird.
* * * EDIT * * *
was mir gerade aufgefallen ist, das dass Feld für Breiten- und Längengrad leer ist. Ich weiß das ich die Daten eingetragen und auch gespeichert habe.

**Comment by MetaChuh** [comment]
> was mir gerade aufgefallen ist, das dass Feld für Breiten- und Längengrad leer ist. Ich weiß das ich die Daten eingetragen und auch gespeichert habe.

super dass du nachgeschaut hast, eventuell kann fehlende lat long das auslösen.
hab' ich noch nicht getestet.

**Comment by lumapu** [comment]
nein Längen- und Breitgrad haben damit nichts zu tun. Du könntest mal auf Webserial gehen und in einem neuen Tab / Fenster auf `http://[IP]/debug` gehen. Danach solltest du im Webserial eine Ausgabe ähnlich dieser bekommen:

```
20:51:17.961 I: webSc, tmt: 1, rel: 1
20:51:17.962 I: prot, tmt: 1, rel: 1
20:51:17.962 I: net, tmt: 1, rel: 1
20:51:17.963 I: uart, tmt: 1, rel: 5
20:51:17.963 I: hist, tmt: 1, rel: 1
20:51:17.963 I: tSend, tmt: 1, rel: 5
20:51:17.963 I: ntp, tmt: 17113, rel: 0
20:51:17.974 I: Sunri, tmt: 1715281191, rel: 0
20:51:17.974 I: mqttS, tmt: 1, rel: 1
20:51:17.975 I: mqttM, tmt: 3, rel: 60
20:51:17.975 I: midNi, tmt: 1715292000, rel: 0
```

Du solltest entwender `midNi` oder `mid2` finden. Die große Zahl `1715292000` ist der Timestamp der nächsten Triggerung. Das sollte auch der Mittacht deiner Zeitzone entsprechen, hier kannst du den Timestamp konvertieren: https://www.unixtimestamp.com/
`Your Time Zone | Fri May 10 2024 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)`

**Comment by ralfberger** [comment]
Es immer noch so das die Max Werte nicht um Mitternacht gelöscht.
@lumapu 
`11:01:10.123 I: webSc, tmt: 1, rel: 1
11:01:10.124 I: prot, tmt: 1, rel: 1
11:01:10.124 I: uart, tmt: 3, rel: 5
11:01:10.125 I: hist, tmt: 1, rel: 1
11:01:10.125 I: tSend, tmt: 8, rel: 10
11:01:10.125 I: mqttS, tmt: 1, rel: 1
11:01:10.126 I: wifiL, tmt: 1, rel: 1
11:01:10.128 I: mqttM, tmt: 40, rel: 60
11:01:10.130 I: midNi, tmt: 1715378400, rel: 0
11:01:10.133 I: ivCom, tmt: 1715368084, rel: 0
11:01:10.136 I: Sunri, tmt: 1715368144, rel: 0
11:01:10.139 I: ntp, tmt: 21580, rel: 0`

Der konvertierte Timestamp sollte korrekt sein.
`GMT 	Fri May 10 2024 22:00:00 GMT+0000
Your Time Zone 	Sat May 11 2024 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)`

NTP-Server ist meine Fritzbox. Die angezeigte Systemzeit ist auch i.O.

Edit:
Wenn ich Ahoy neu starte sehe ich realistische Max-Werte. 
![Screenshot_20240510_112124](https://github.com/lumapu/ahoy/assets/63057484/28f10b7c-e6d7-4aa4-92e9-9185c182ec00)

**Comment by Starfoxfs** [comment]
Ok dann schließe ich mich hier mal an, wie kann ich den Tagesertrag zurücksetzen ?

Ich hatte 0.7.x Firmware drauf und seitdem ich 0.8.83 drauf hab addiert er anscheinend den Tagesertrag jeden Tag weiter.

Sollte man den Gesamtertrag zurücksetzen ?!? ist der dann nicht auf 0 ?

**Comment by MetaChuh** [comment]
@Starfoxfs 

wie sind deine einstellungen im vergleich zu unserem screenshot oben ?
(der dark mode screenshot)

ggf bitte auf die dev version 0.8.118 updaten und testen.

diese kannst du entweder hier [`ahoy_v0.8.118`](https://fw.ahoydtu.de/fw/dev%2Fahoy_v0.8.118/) als ota file für dein esp board manuell herunterladen,
bzw hier [`Ahoy Community WebFlasher`](https://fw.ahoydtu.de/tools/webflasher/) mit automatischer board-erkennung direkt aus chrome via usb upgraden

**Comment by Starfoxfs** [comment]
Aktuell ist nur Grid-Profil auslesen aktiviert sonst nichts.

![2](https://github.com/lumapu/ahoy/assets/62878094/0c9c1331-a2bd-4337-a1ae-20a3a51f4bc0)

**Comment by Starfoxfs** [comment]
So wie es oben im "Dark Mode" Screenshot ist scheint es zu funktionieren. Dachte erst Gesamtertrag zurücksetzen setzt mir den gesamten Ertrag vom Wechselrichter auf 0 aber dem ist nicht so. Bezieht sich wohl auf die von Ahoy DTU gesammelten Daten über den Gesamtertrag.

**Comment by MetaChuh** [comment]
@Starfoxfs 

> So wie es oben im "Dark Mode" Screenshot ist scheint es zu funktionieren.

perfekt 👍

> Dachte erst Gesamtertrag zurücksetzen setzt mir den gesamten Ertrag vom Wechselrichter auf 0 aber dem ist nicht so.

ja, da hast du recht bezüglich der deutschen übersetzung.

das kann verwirren, weil ja nur der tagesertrag zurückgesetzt wird, und nicht der inverterseitig gespeicherte gesamtertrag seit der ersten inbetriebnahme.

in der englischen firmware ist es korrekt angegeben:

`lang.json` :
```
"token": "INV_RESET_MIDNIGHT",
"en": "Reset values and YieldDay at midnight",
"de": "Werte und Gesamtertrag um Mitternacht zur&uuml;cksetzen"
```

**Comment by ralfberger** [comment]
Ich habe meine Einstellungen (siehe oben) getestet und es scheint zu funktionieren. Die TagesMax Werte sind am nächsten Tag auf Null. Meine Vermutung ist das es **nicht** an der DTU lag sondern an ein vor Mitternacht abgeschaltetes Wlan. 
Auch wenn alles jetzt funktioniert, warum wird die Abfrage zum  Sonnenuntergang gestoppt?
Oder ist das die deutsche Übersetzung zu `Kommunikation während der Nacht pausieren `
![Ahoi3](https://github.com/lumapu/ahoy/assets/63057484/f584122a-b7bf-465a-9bf5-9dbc9b88db18)
