### ISSUE TITLE
<TOPIC>/<INVERTER_NAME_FROM_SETUP>/ch0/PowerLimit

### ISSUE THREAD

**Issue by andewo** [lumapu/ahoy#1611]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version:0.8.83
Github Hash: 5ebfe5a

Hallo in die Runde,

kann mir jemand sagen ob dieses Topic "PowerLimit" noch zur Verfügung steht. Bekomme es nicht in HA geladen. Habe mir MQTT Explorer geladen - unter ch0 gibt es noch 12 topics - PowerLimit ist nicht dabei. Würde das gerne in HA für die Nulleinspeisung verwenden - ggf. muss ich das anders lösen....habe auf die aktuelle Ahoy-version upgedated...

**Comment by lumapu** [comment]
das Powerlimit ist verschoben worden und kann jetzt unter `<TOPIC>/ctrl/limit/0` gefunden werden (für den ersten Inverter). Wenn dort nur eine Zahl reingeschrieben wird, dann wird es prozentual interpretiert, mit einem `W` als absolute Wattangabe.

**Comment by andewo** [comment]
Hallo Lumapu, vielen Dank für die Rückinfo. Leider habe ich mich nicht eindeutig ausgedrückt. Kann man den Wert PowerLimit auch auslesen ? Ich kann den Wert mit <TOPIC>/ctrl/limit/0 setzen - Danke hierfür. Ich möchte danach aber auch den Wert auslesen können - so wie er in der Ahoy Übersicht angezeigt wird. 100% , 80% etc.

**Comment by blueline13** [comment]
@andewo 
Du findest den aktuellen geschrieben wert im folgendem Feld: *DTU*/*Inverter*/ack_pwr_limit 

Den Topic kannst du als Acknowledge betrachten das der WR das Limit akzeptiert. Du solltest aber eine aktuelle Developer Version benutzen. Früher wurde da nur der Zeitstempel aktualisiert. Ich kann leider nicht genau sagen ab wann das geändert wurde.

**Comment by andewo** [comment]
@blueline13 - diesen Wert lese ich bereits erfolgreich aus. Dieser gibt aber nur den Wert TRUE or FALSE zurück nicht aber den aktuell gesetzten relativen oder absoluten Wert so wie er dann in der Ahoy-Live-Übersicht erscheint.

**Comment by blueline13** [comment]
@andewo 
Deswegen sagte ich ja eine aktuelle Developer. Die 0.8.118 unterstützt das, deine Version hat das noch nicht. Sieht dann so aus:

![grafik](https://github.com/lumapu/ahoy/assets/56932380/b02a66db-f6fe-4870-a96b-d70d751e7d57)

**Comment by andewo** [comment]
@blueline13 - ok - an eine Developer-Version habe ich mich bis dato noch nicht ran getraut. Das werde ich mir mal anschauen. Wäre natürlich schön wenn das auch in eine aktuelle stabile Version Einzug hält...Nochmals vielen Dank für den Hinweis und den Beispiel - Screen-shot.
