### ISSUE TITLE
Bitte Tagesertrag zum Verlauf hinzufügen

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#1614]
Ist es möglich im Bereich Verlauf den Ertrag mit hinzuzufügen?
![grafik](https://github.com/lumapu/ahoy/assets/105392164/8dd592fa-07ce-4d03-b345-cb4c7ee999cb)

Bei mir erscheinen leider nur max Werte (Peak) der Anlage über den zeitlichen Verlauf.
Nicht verwirren lassen, der Screenshot wurde nach einem Reboot gemacht, daher sind nur die Werte die aktuell vom WR ausgelesen wurde mit drin und keine Historie.

**Comment by lumapu** [comment]
finde ich sinnvoll, interessanter Weise schaue ich auch immer auf den Grafen und danach noch auf live im den Gesamtertrag zu sehen 😃
gehört zu #1199
