### ISSUE TITLE
Invertereinstellungen in V0.8.118 

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1618]
in den WR-Einstellungen der neuesten Version wurde eine Funktion geändert: aus reset max-Values at midnight (oder so ähnlich) wurde  "inlude reset max-Values" (Incl. Tippfehler...) siehe screenshot  
Ich  hatte bisher nur diesen  Haken  gesetzt und damit meine Max-Werte um Mitternacht gelöscht, aber jetzt bewirkt er allein anscheinend  nichts mehr(?) (meine Max-Werte incl. Temp.+Zeitstempel blieben erhalten)    ![2024-05-12 09_06_30-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/c5115925-5ab5-424e-92ea-db51817c075b)

**Comment by MetaChuh** [comment]
hi @Gubi2023 ,

die option `Reset values and YieldDay at midnight` muss zusätzlich angehakt werden.

ich werd' sicherheitshalber heute nacht ebenfalls mit v0.8.118 ausprobieren, ob die max werte korrekt genullt werden.
(bin noch auf 0.8.117)

**Comment by Gubi2023** [comment]
wozu ist dieser Haken dann noch da? dann  kann man ihn  gleich weglassen...

**Comment by MetaChuh** [comment]
> wozu ist dieser Haken dann noch da? dann kann man ihn gleich weglassen...

ja und nein: manche user wollten zwar die tagesertragswerte zurücksetzen, jedoch die maximal erreichten werte über mehr als einen tag behalten.
beide felder in kombination deckten bisher diese szenarien ab.

**Comment by lumapu** [comment]
genau wie @MetaChuh geschrieben hat, kann man damit auswählen, ob die max-Werte auch zurückgesetzt werden sollen oder nicht. Ich finde es sehr sinnvoll.
Im Prinzip hat sich unter der Haube nicht viel getan, die Bennung des Hakens war falsch.

**Comment by Gubi2023** [comment]
mir ist es auch nur aufgefallen, weil erst mit der 0.8.118 die max-Werte nicht mehr gelöscht wurden, sonst wurden sie immer auch nur mit dem einen Haken gelöscht....

**Comment by Gubi2023** [comment]
ich hätte noch eine Frage zu "Werte bei Sonnenaufgang/untergang zurücksetzen":  werden sie zu diesem Zeitpunkt gelöscht, oder 
zu Start bzw. Ende der Kommunikation? (weil andernfalls die Wert  verzögert bzw zu früh gelöscht würden)

**Comment by lumapu** [comment]
Die Werte werden zum Zeitpunkt des errechneten Sonnenauf- bzw. untergangs zurückgesetzt. Es handelt sich genau um die Zeiten, die man unter `/system` sehen kann
