### ISSUE TITLE
Setup-Problem: Inverter-Daten lassen sich nicht speichern - v0.5.14

### ISSUE THREAD

**Issue by roku133** [lumapu/ahoy#162]
nach Update von v0.5.10 auf v0.5.14:

Daten im Inverter-Abschnitt des Setups lassen sich mit der v0.5.14 (ge3b9abc) nicht mehr speichern, Einträge sind nach dem Speichern wieder verschwunden. Erase Settings bringt vor oder auch nach dem Update keine Verbesserung.
Alle anderen Änderungen wie z.B. MQTT-Daten werden problemlos gespeichert.

Work-around aktuell - Fallback auf alte Version, funktioniert weiter problemlos

**Comment by aschiffler** [comment]
Danke für die Hinweise. Das Thema Kompatibilität beim Upgrade wurde bisher nicht ausreichend betrachtet.
Ohne es zu testen schlage ich nochmals folgendes Vorgehen vor:
1. flashen von v0.5.10 und dann dort /erase auf rufen oder per klick auf den button "erase settings not wifi"
2. flashen von v0.5.14 und dann wie gewohnt versuchen den inverter anzulegen.

EDIT:
ab 0.5.12 wurde im Setup ein drop-down für das Setting der Leistungslimitierung ergänzt. Dadurch wurde das layoute des EEPROM geändert. Vermutlich bedingt dies das Problem.

**Comment by roku133** [comment]
genau das habe ich bereits erfolglos versucht - selbst das Löschen vor dem Update nützt nichts (siehe Problembeschreibung oben) ...
Factory Reset bringt auch keinen Erfolg.

**Comment by eeprom23** [comment]
Habe genau das gleiche Problem !

**Comment by stefan123t** [comment]
Wie Andreas schrieb hängt es vermutlich mit dem neuen Setting zum PowerLimit zusammen. Dies muss sowohl in defines.h als auch in den entsprechenden Erase/SaveSettings Methoden berücksichtigt werden.

Hier noch der Hinweis auf #164 das diese Probleme in Zukunft hoffentlich hinfällig macht ?

**Comment by thymjan** [comment]
Kann auch die Verbindungsdaten zum Inverter nicht mehr speichern.

**Comment by stefan123t** [comment]
Stefan123t:

@lumapu  kannst Du evtl nochmal in die defines.h schauen :eyes: wir kämpfen gerade mit einem settings/EEPROM Problem in #162 im master & develop branch. Du hattest doch das letzte Mal einige Klammern gesetzt damit die Berechnungen innerhalb der #defines korrekt sind. Jetzt gibt es auch einige structs aber noch keine length/len Funktion darüber. Vielleicht haben wir irgendwo ein paar Bytes vergessen anzupassen ?

@aschiffler  Du hattest doch die PFPower.Desc Werte mit double/word Länge hinzugefügt. Sind die je zwei Bytes / WR auch drin ?

Lumapu:

ich kann mir vorstellen, dass stefan123t es auf den Punkt gebracht hat. Kann erst morgen Abend testen, aber schaut doch mal bzgl Klammern hier:
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/app.cpp#L878

neu den oberen beiden write könnte es was bringen, genau beim read:
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/app.cpp#L828

**Comment by klahus1** [comment]
Moin Moin zusammen,

das Problem dürfte etwas tiefer liegen:

hmInverter.h
![grafik](https://user-images.githubusercontent.com/104840514/185266321-98853fdb-1325-4787-899b-2478c23eeb5e.png)

hmSystem.h:
![grafik](https://user-images.githubusercontent.com/104840514/185266414-463ec143-a170-4620-aa22-99e8850da8c2.png)

app.cpp:
![grafik](https://user-images.githubusercontent.com/104840514/185266746-ceabb6ce-f153-4cf3-9d9d-e3a1751d3d2d.png)

web.cpp:
![grafik](https://user-images.githubusercontent.com/104840514/185266847-6876e7e6-3bff-422c-8526-ae1cd84aec2b.png)


Da `mInverter[pos].initialized` in `hmInverter.h` mit `false` initialisiert wird, 
kann zwar ein neuer Inverter in `web.cpp` via `iv = mMain->mSys->getInverterByPos(i, false);` angelegt werden, 
weil `|| false == check` `mInverter[pos].initialized` nicht relevant ist.

Sollen jedoch in app.cpp mit `void app::saveValues(void)` die Werte gespeichert werden, 
wird der Zeiger auf den Inverter mit `iv = mSys->getInverterByPos(i);` geholt -> ` bool check = true` . 
Also wird an dieser Stelle mit `mInverter[pos].initialized = false` `NULL` zurückgegeben. 
Mit ` if(NULL != iv) {` wird das Speichern übersprungen.

So müsste die "dead-loop" entstehen.

Es könnte also geschaut werden, ob, wo und wie `mInverter[pos].initialized` initialisiert werden muss.

Viele Grüße
Klaus

**Comment by fila612** [comment]
> EDIT: ab 0.5.12 wurde im Setup ein drop-down für das Setting der Leistungslimitierung ergänzt. Dadurch wurde das layoute des EEPROM geändert. Vermutlich bedingt dies das Problem.

Also ich nutze die 5.13 derzeit produktiv (Update von 5.10 via OTA) und habe keine Probleme, einzig die Fehlenden Inverter-Daten nach dem Update haben mich überrascht. Habe diese neu eingetragen und wurden auch beim Speichern übernommen.

Heute morgen habe ich die 5.14 aus dem dev-branch auf meinem Testsystem via OTA von 5.10 kommende installiert und kann nun auch keine Inverter Daten speichern.
Also es müsste an 5.14 liegen, 5.13 hat den Fehler bei mir nicht.


EDIT1:
gerade im Testsystem einen Reboot gemacht, die Felder im Inverter waren leer(!), nach dem Reboot erkenne ich in der Serial Konsole auf einmal die SN meines Inverters und siehe da, nun stehen sie auch im Setup - kurios.
Leider ist das PowerLimit nun gar nicht mehr auswählbar. -dropdown klappt nicht aus.
![Bildschirmfoto 2022-08-18 um 07 21 25](https://user-images.githubusercontent.com/29542374/185300354-2eac13c6-ee5b-4953-84ca-7271b7c7f63a.png)

EDIT2:
ich hab den Wer nun auf 100 gesetzt, laut Konsole waren dies Watt. Danach konnte ich das Dropdown wieder nutzen und auf Prozent umstellen. Funktioniert hat das ganze OHNE Reboot:
07:26:11.431 > I: Power limit for inverter 0 set to 100W
07:26:11.434 > I: Power Limit Control Setting 0
[...]
07:26:23.727 > I: Inverter has not accepted power limit set point
07:26:28.486 > I: Requesting Inverter SN 114181302071
07:26:32.264 > I: Power limit for inverter 0 set to 100%
07:26:32.268 > I: Power Limit Control Setting 1
[...]
07:26:43.574 > I: Inverter 0 has accepted power limit set point 100 with PowerLimitControl 1

**Comment by aschiffler** [comment]
Wie @klahus1 schon schrieb, denke ich liegt das Problem in den Änderungen die mit diesem commit rein gekommen sind. https://github.com/grindylow/ahoy/commit/9073d2a82cb90a9377a93f8ceb59dd39921c1760
Vielleicht kann @a-marcel hier noch mal helfen.

**Comment by aschiffler** [comment]
@stefan123t Zu den neuen Adressen in den defines.h.
Es gibt ein neues define für die zusätzlichen 2 bytes pro inverter (Power.Desc) siehe hier https://github.com/grindylow/ahoy/blob/e3b9abc5ffd4f1728048490b26e1ee15ee54aa2e/tools/esp8266/defines.h#L171
Die Länge bzw. wieviel Speicher reserviert ist wird mit dem gleichen define wie die 2 bytes für das PowerLimit pro inverter gesetzt siehe hier:
https://github.com/grindylow/ahoy/blob/e3b9abc5ffd4f1728048490b26e1ee15ee54aa2e/tools/esp8266/defines.h#L90

Sollte m.E. passen.

**Comment by aschiffler** [comment]
> Es könnte also geschaut werden, ob, wo und wie mInverter[pos].initialized initialisiert werden muss.
@klahus1 Die Lösung scheint mir doch nahe liegend.
Am Ende dieser Schleife muss initialized auf true gesetzt werden für jeden inverter. Macht auch Sinn m.E. da man an dieser Stelle die mandatory field: Adresse, Namen eingetragen hat.
https://github.com/grindylow/ahoy/blob/e3b9abc5ffd4f1728048490b26e1ee15ee54aa2e/tools/esp8266/web.cpp#L294

**Comment by lumapu** [comment]
@aschiffler Ich habe hierzu eine Idee, die beim refaktorieren geboren wurde aber noch nicht umgesetzt ist.
Mich stört sowohl beim Lesen sie auch speichern der Einstellungen die for loop for die Inverter. Gut, die wird evtl. bleiben aber wesentlich einfacher.

Die Idee: Alle Einstellungen der Inverter (SNo, Name, PwrLim, Modul Pwr und Name) in ein weiteres struct zu packen und auch dieses als Block zu speichern. In der hmInverters.h dann in den Settings vom Inverter auch wieder auf das struct verweisen und keine Daten doppelt vorhalten.
Das könnte auch zukünftige Versionen (z.B. JSON Settings) vereinfachen.

**Comment by a-marcel** [comment]
> Wie @klahus1 schon schrieb, denke ich liegt das Problem in den Änderungen die mit diesem commit rein gekommen sind. [9073d2a](https://github.com/grindylow/ahoy/commit/9073d2a82cb90a9377a93f8ceb59dd39921c1760)
> Vielleicht kann @a-marcel hier noch mal helfen.

Hallo, das tut mir dann leid, das meine Änderungen scheinbar dran schuld sind das einige Probleme hier haben. In dem Fall kann mein PR zurückgenommen werden oder jemand der esp8266 inklusive webversion nutzt müsste das Anpassen (ich habe und nutze das leider nicht).

Hintergrund meines PRs ist, das ein Array mit einer festen Größe (MAX_NUM_INVERTERS) definiert wird und CPP bei ESP32 dann das union object mit default werten füllt. 

Demnach, wenn man 3 WR als maximale Anzahl angibt, dann hat man auch 3 WR wobei aber serial.u64 mit einen default wert (maximal int wert) gefüllt ist. Und diese werden dann auch mit jedem loop abgefragt. 

Mein PR sollte ja einer von den ersten sein, der die hm* Dateien auf ESP32/ESP8266 vorbereitet, aber ich gebe zu, das ich die web.cpp (Webseite) nicht nutze und demnach nicht sauber getestet hab.

Sollte keiner den Fehler in web.cpp beheben können, dann bitte meinen PR reverten.

Vielen Dank und sorry für die Unannehmlichkeiten. 

(P.s.: bin leider nicht am Computer und kann das jetzt die Tage nicht fixen)

**Comment by aschiffler** [comment]
@a-marcel Es bedarf sicher keiner Entschuldigung. Ich denke wir haben es mit dem letzten commit gelöst. Und vom logischen Sinn her ist es auch von Vorteil was Du eingebracht hast.
