### ISSUE TITLE
Max Power + Yield Today not resetted

### ISSUE THREAD

**Issue by elisenjens** [lumapu/ahoy#1620]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.118

### Github Hash

85e3dea

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Standard

### Debug Serial Log output

```shell
no log
```

### Error description

Like some versions before: Max Power + Yield Today are not resetted even though "Reset values and YieldDay at midnight" and "Inlude reset max values" are flagged.

**Comment by Starfoxfs** [comment]
Ich hab hier ein sagen wir mal ähnliches Problem, ich hab die 0.8.83 installiert und seitdem extrem hohe Tageswerte. Hab ich hier was falsch gesetzt in den Einstellungen des Wechselrichter (siehe Bild unten) ?


![1](https://github.com/lumapu/ahoy/assets/62878094/d0168c00-94a9-4dac-b6b7-095bd4ea866c)
![2](https://github.com/lumapu/ahoy/assets/62878094/2bf26405-f125-45a2-b9d3-d47dc945a4ef)

**Comment by ralfberger** [comment]
@Starfoxfs 
Hast du die entsprechenden Optionen jetzt gesetzt und werden die Max Werte gelöscht?

**Comment by Starfoxfs** [comment]
:Edit: Muss revidieren, die Werte werden **nicht** gelöscht ist wohl wirklich ein Bug.

Heute hat er auf die Werte von gestern wieder aufaddiert.

Firmware 0.8.83
Wechselrichter Hoymiles HM-1500

gesetzt ist: 

Wechselrichter editieren:
- [✓ ] Kommunikation während der Nacht pausieren (Breiten- und Längengrad müssen gesetzt sein

Wechselrichter Einstellungen:
- [✓  ] Werte und Gesamtertrag um Mitternacht zurücksetzen ('Kommunikation während der Nacht pausieren' muss gesetzt sein)
- [ ✓ ] Maximalwerte mitternachts zurücksetzen
- [✓  ] Grid-Profil auslesen

 Trotzdem kein zurücksetzen Mitternachts.

WLAN ist Abends bei uns aus, in der Version 0.7.xx ging es aber noch einwandfrei mit dem zurücksetzen auch mit ausgeschaltetem WLAN Abends.

**Comment by lumapu** [comment]
danke für den Hinweis mit dem WLAN, das wird es wohl sein

**Comment by elisenjens** [comment]
hat bei mir in den älteren Devs aber funktioniert; hab nichts geändert an meiner Konfig

**Comment by ralfberger** [comment]
Das mit dem WLan kann ich bestätigen. Ich hatte auch das WLan vor 0.00 **off** und um 6:00 wieder **on**.
Jetzt geht es erst um 0.30 Uhr off und vor Sonnenaufgang auf on, seit dem werden die max Werte resettet.
Seit gestern nutze ich `0.8.118_85e3dea_esp8266-all-de`  und werde das Wlan so einstellen das es um 11:30 Uhr off ist und um 6:00 Uhr on ist um zu sehen ob dann die Werte resettet werden.

**Comment by elisenjens** [comment]
working again in 0.8.119 THX
