### ISSUE TITLE
Unable to write letter of Serial

### ISSUE THREAD

**Issue by Maeckes89** [lumapu/ahoy#1623]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Modelname: Vroom 32
Retailer URL: ______

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.118
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

The Serial of my Hoymiles HMS-1600 is something like ####A###F#CF (# is a number)

But I'm unable to write a letter in the Serial-field in the inverter setup. So - what to do?
I can only write letters like "e" and "+". Apart from these both only numbers.

**Comment by MetaChuh** [comment]
i cannot reproduce this.

i had no problem to enter a serial like `1164A008F2CF` as seen at the screenshots below.
also the inverter type and channel count is detected correctly.

can you use another browser or clear the browser cache ?

<img width="713" alt="Bildschirmfoto 2024-05-14 um 18 37 49" src="https://github.com/lumapu/ahoy/assets/45773305/8f70ea41-f89f-43b6-b901-00e099f35dcd">

<img width="701" alt="Bildschirmfoto 2024-05-14 um 18 38 03" src="https://github.com/lumapu/ahoy/assets/45773305/a1cb8288-7ef1-45de-9427-8acebe38b9ff">

**Comment by lumapu** [comment]
are you sure that you have a HMS-1600 or could it be a HMS-1600W

**Comment by lumapu** [comment]
@Maeckes89 are there any updates?

**Comment by LnBsN** [comment]
Bonjour,

Je me retrouve avec le même problème, j'ai un micro onduleur HMS-1000-2T comportant 2 lettres dans le numéro de série, sauf que je ne peux écrire que des chiffres.
Auriez vous une solution pour écrire le numéro de série avec chiffres et lettres ?

Il s'agit de : 
La version 0.8.83
ESP 32 
Radio CMT2300A

Cordialement

**Comment by lumapu** [comment]
you can use the development version:

https://fw.ahoydtu.de/fw/dev/

**Comment by LnBsN** [comment]
> Vous pouvez utiliser la version de développement :
> 
> https://fw.ahoydtu.de/fw/dev/

Bonjour,

Cela a fonctionné avec la version .127
Merci pour votre aide !

Cordialement

**Comment by Leitzbach1** [comment]
I had the same issue, i just changed the html input field type="number" to type:"text" and could enter letters.
