### ISSUE TITLE
[Bug] Inverters can not be deleted (v0.8.118)

### ISSUE THREAD

**Issue by MetaChuh** [lumapu/ahoy#1625]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.118

### Github Hash

85e3dea 

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

Inverters can not be deleted in v0.8.118

i've added an hms-1600 inverter for another issue, and noticed that i can not delete any inverter, newly added or existing.
the `ja` button does not do anything.
tested on mac & pc browsers: chrome & safari and mobile iphone safari.

<img width="726" alt="Bildschirmfoto 2024-05-14 um 18 56 22" src="https://github.com/lumapu/ahoy/assets/45773305/9001e3a4-34a4-4361-99f0-6a34ac0851f9">

**Comment by Gubi2023** [comment]
komisch, bei mir gehts....

**Comment by rmayergfx** [comment]
Wurden vorher auf allen Systemen der Browsercache gelöscht?
Erstelle ein Backup, setze die Einstellungen zurück und spiele das Backup wieder ein.

**Comment by MetaChuh** [comment]
@Gubi2023 
endlich was was bei dir geht und bei mir nicht mehr 😄👍
heads up info: wir sind grad' am isolieren, weil es noch reproduzierbar ist ... wissen jedoch nicht was dies auslöst.

@rmayergfx 
danke dir, genau so haben wir gestern dieses testszenario zurückgesetzt.
spezifisch: backup erstellt, json in einem editor modifiziert, die modifizierte config wieder eingespielt.
beim rest sind wir dahinter, damit keiner in der community das gleiche szenario hat.

thx & greetings,
metachuh

**Comment by lumapu** [comment]
habt ihr die Dev-Konsole vom Browser angeschaut? Ob's evtl. ein Javascript Problem gab

**Comment by MetaChuh** [comment]
ja, keine fehler in der js console.
ich flashe sobald ich zeit habe noch eine dtu und beobachte dies auf reproduzierbarkeit.

passiert ist es, nachdem ich einen hms mit hex sn eingetragen hatte.
wenn ich es nicht auf einem weiteren esp reproduzieren kann, dann schließe ich dieses issue, da es anscheinend selten auftritt.

**Comment by MetaChuh** [comment]
update:

dieses issue tritt nur bei meiner testdtu auf.
bei allen neu geflashten dtus tritt dieser fehler nicht auf.
alle inverter lassen sich beliebig anlegen und löschen.

thx & closing

**Comment by Fr33man85** [comment]
Naja, bei meinem vor kurzem über das online Tool geflashten esp32 hab ich das Problem jetzt auch. Kann meinen hm-600 nicht löschen.

Selber verhalten wie oben beschrieben.

GIT SHA: 5ebfe5a :: 0.8.83

Werde es mal mit dem Backup work around versuchen
