### ISSUE TITLE
A second Hoymiles Inverter can not be added

### ISSUE THREAD

**Issue by Maddiehn22** [lumapu/ahoy#1627]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.83

### Github Hash

5ebfe5a

### Build & Flash Method

ESP Tools (flash)

### Setup

Add a MQTT server with 5 seconds respond time

### Error description

Another Hoymiles Inverter with serial number above 138999999999 (in my case (141xxxxxxxxx617)) can not be added
and marked red in the serial number entry field 
![grafik](https://github.com/lumapu/ahoy/assets/128905323/a4219e1e-f53d-4faa-a334-18fdafee93c1)

**Comment by Ollipop030** [comment]
Shouldn't the serial number be 12 characters long?

![image](https://github.com/lumapu/ahoy/assets/121013633/8971fb54-9ac8-49e0-8e77-8d6e5cbb6055)

**Comment by Maddiehn22** [comment]
12 characters are given on the labele oft the inverter.

**Comment by Maddiehn22** [comment]
The shown screenshot is with typo :-(

**Comment by Ollipop030** [comment]
What inverter do you have?

**Comment by Maddiehn22** [comment]
Hoymiles HM-800

**Comment by Ollipop030** [comment]
I´m not sure, but should the serial number start with 11? Since it´s Gen 3.

https://github.com/lumapu/ahoy/wiki/Hardware#wie-ist-die-serien-nummer-der-inverter-aufgebaut

**Comment by knickohr** [comment]
Is it really a HM not a HMS or HMT or something with H….-W…. ?

**Comment by Maddiehn22** [comment]
Dear all,
disregard! My neighbour sent me the type plate of his inverter.
It is NO HM800 but a  HMS-800-2T WiFi.
Sorry for disturbance.

**Comment by Maddiehn22** [comment]
The inverter is NO HM800 but a  HMS-800-2T WiFi.
Sorry for disturbance.
