### ISSUE TITLE
HoyDtuSim and other unmaintained tools/

### ISSUE THREAD

**Issue by DeeJayMykel** [lumapu/ahoy#163]
Hallo,
ich bekomme beim Kompilieren folgende Meldung:
ModWebserver.h:55:33: error: 'getSerialNoTxt' was not declared in this scope
   55 |     out += "<h3>S/N " + String (getSerialNoTxt(wr)) + "</h3>";
      |                                 ^~~~~~~~~~~~~~
exit status 1
'getSerialNoTxt' was not declared in this scope

Leider bin ich kein Programmierexperte. Kann mir jemand sagen in welcher Zeile bzw. Tab ich diese eintragen kann?
Vielen Dank.

**Comment by stefan123t** [comment]
@DeeJayMykel das unter HoyDtuSim ist die Software von Hubi. MW stellt er die immer wieder auf Anfrage ins Forum. Die meisten hier im ahoy Repo arbeiten an der ESP8266 Variante die auch als Vorlage für die ESP32 Variante (OpenDTU) von Thomas dient.
Raspberry Pi wird auch mehr oder weniger aktiv hier maintained (Jan-Jonas S & Daniel R).
Kurz ich weiß es leider nicht welchen Stand die HoyDtuSim Software vom 28.4.2022 aktuell hat.

**Comment by stefan123t** [comment]
Ich vermute Hubi pflegt seine Urversion HoyDtuSim unter https://github.com/hm-soft/Hoymiles-DTU-Simulation/

@aschiffler vielleicht sollten wir das Verzeichnis zugunsten eines Links auf Hubis Repo entfernen. Vielleicht machen wir das genauso mit einem Verzeichnis OpenDTU oder anderen Repos die hiervon abstammen aber sich bereits verselbständigt haben ?

**Comment by stefan123t** [comment]
Andere Repos:
MI-1200..1500, MI-600, etc ?
https://github.com/Ziyatoe/DTUsimMI

ESPHome Variante von marcel-a
https://github.com/a-marcel/ahoy/tree/main/tools/esphome

ESP32 OpenDTU von tbnobody
https://github.com/tbnobody/OpenDTU/

https://github.com/tbnobody/OpenDTU/blob/master/docs/Wiring_ESP32.fzz

??? von O Freddy
https://github.com/OFreddy/hm_poll

**Comment by DeeJayMykel** [comment]
Danke für die schnelle Antwort.

**Comment by stefan123t** [comment]
@aschiffler 
Reopened to add the info to our Readme.md and delete the HoyDtuSim and eventually other directories under tools/ which are unmaintained.
