### ISSUE TITLE
Active Power Control: Am nächsten Tag immer wieder auf 100 % HM-1500

### ISSUE THREAD

**Issue by Andy811963** [lumapu/ahoy#1634]
## Hardware
  * [ *] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname:  HM-1500
Retailer URL: ______

### nRF24L01+ Module
* [ *] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [* ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ *] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.119
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [* ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [*
![20240519_164929](https://github.com/lumapu/ahoy/assets/133586706/81d9bad2-4808-4eb0-9121-d056bd33d5c5)
![Screenshot 2024-05-18 200315](https://github.com/lumapu/ahoy/assets/133586706/d188f820-82c9-47ae-bd84-dc028877a640)
![Screenshot 2024-05-19 164210](https://github.com/lumapu/ahoy/assets/133586706/49f14d23-7960-43ac-9ae4-f4bb24210dac)
 ] Setup settings (use our templates ... to be added)

**Comment by Gubi2023** [comment]
Haken gesetzt??  
![Screenshot 2024-05-19 172227](https://github.com/lumapu/ahoy/assets/142897856/37c072ff-d876-4acb-b46d-287ed96b17bf)

**Comment by MetaChuh** [comment]
@Andy811963 
aktiviere `Leistungsbegrenzung dauerhaft speichern (im Wechselrichter)` und klicke auf `Anwenden` wie auch am screenshot von @Gubi2023

sonst wacht der inverter immer mit 100% factory default auf, sobald die sonne rauskommt.

<img width="715" alt="Bildschirmfoto 2024-05-19 um 17 25 34" src="https://github.com/lumapu/ahoy/assets/45773305/dfaf93b3-599a-4273-873c-113615a1f767">

**Comment by Andy811963** [comment]
Hallo zusammen,

Danke für die schnellen Antworten.

Aber ich finde den Haken nicht bei mir ?!

Gruß Andy
![Screenshot 2024-05-19 181758](https://github.com/lumapu/ahoy/assets/133586706/51b9e560-09b7-49ec-b683-b7dfe627b008)

**Comment by Gubi2023** [comment]
@MetaChuh   Ah! Er arbeitet noch mit V0.7.51! da kenne ich mich nicht mehr aus (zu alt)

**Comment by Andy811963** [comment]
Hallo,

wie kann ich die Version erhöhen ?
Habe regelmäßig die Updates gemacht. Nun 08.120.
Sorry für die blöde frage, habe aber nur Halbwissen.

**Comment by knickohr** [comment]
Wähle da mal aus persistant und prozent.

![IMG_2628](https://github.com/lumapu/ahoy/assets/63048210/ca5bde9b-4db4-4641-8014-db2ebb09c648)

Aber hat sich ja erledigt wenn Du auf die 120 bist.

**Comment by MetaChuh** [comment]
@Andy811963 

ich verstehe.
du findest die einstellung nicht, weil sie in der neuen version an einer anderen stelle und nicht mehr in serial/control ist.

anleitung:
klicke auf daten, dann auf die leistungsbegrenzung wie auf diesem screenshot:

<img width="877" alt="Bildschirmfoto 2024-05-19 um 21 15 06" src="https://github.com/lumapu/ahoy/assets/45773305/b3a9dbf3-b6c3-4a02-8c25-147a8649db1f">

danach kommst du zu diesem fenster:

<img width="715" alt="Bildschirmfoto 2024-05-19 um 17 25 34" src="https://github.com/lumapu/ahoy/assets/45773305/a450a385-f913-4e26-a591-7f334aa784ff">

> Sorry für die blöde frage, habe aber nur Halbwissen.

keine sorge, es gibt keine blöde fragen, maximal ab und zu blöde antworten

greetings,
metachuh

**Comment by Andy811963** [comment]
Danke für die Tipps
