### ISSUE TITLE
Skalierung der Gesamtleistung falsch

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1635]
bei den neueren Devs gibt es ein Problem mit der x-Achsen-Skalierung bei der Anzeige der Gesamtleistung. Der linksseitige Inhalt wird bei jedem Abfrageintervall gelöscht und die Anzeige nach rechts geschoben, sodass links eine Lücke entsteht und rechts der Inhalt aus dem Anzeigefenster geschoben wird. Bei mir wird dann pünktlich jede halbe Stunde die Skalierung neu kalibriert und das Spiel geht von vorne los. siehe Screenshot

<img width="913" alt="Screenshot 2024-05-19 160935" src="https://github.com/lumapu/ahoy/assets/142897856/ce4d3a35-55d9-4297-9442-8f4620375853">

Mein Abfrage-Intervall beträgt 15 sec. 
Bei 5-sekündigem Abfrage-Intervall scheint es aber zu funktionieren

**Comment by strepwo** [comment]
hab was gefunden:
in history.html, Funktion calcScale(), wird bei der Berechnung von ts_pad anscheinend davon ausgegangen, dass man den oberen Plot an seiner Dauer < 1800 sec erkennen kann:
                s.ts_pad = (s.ts_dur < 1800) ? 0 : s.ts_start % 1800
 Aber wenn man als Abfrage-Intervall z.B. 15 sec eingestellt hat, ist ts_dur = refresh * value.length = 15 * 256 = 3840 > 1800..

Ich gucke mal weiter.. eigentlich geht es nur darum, dass man schöne Plots hat, wo alle Werte angezeigt werden; und dass die Zeiten stimmen (vor allem rechts, bei den neusten Werten).. eine Fallunterscheidung 'oben' vs 'unten' sollte nicht nötig sein

**Comment by strepwo** [comment]
hab vermutlich eine Lösung, siehe patch:
[history_patch.txt](https://github.com/lumapu/ahoy/files/15375412/history_patch.txt)
bisher: der ts_pad wurde so eingestellt, dass der Plot der Messwerte mit dem Plot des Grid zusammenpasst
neu: der Plot des Grid wird mit der korrekten Zeit gemacht; dadurch kann ts_pad entfallen, und dann gibte auch keine Probleme mehr damit. Kurzer Test sieht gut aus: alle Werte da, Zeiten stimmen. Bitte testen

**Comment by Gubi2023** [comment]
ich hoffe, das kann jemand übernehmen, ich kanns nicht testen....

**Comment by lumapu** [comment]
ich teste und werde es übernehmen, wenn es passt. @strepwo echt cool, dass du dich da reingefuchst hast und den Code 'verstanden' hast. Mir gefällt, dass es jetzt weniger Code als davor ist - wäre ja cool, wenn damit das Problem gelöst wurde.

**Comment by lumapu** [comment]
mit 5s Intervall geht's weiterhin, daher empfinde ich es mal als gut und schicke es später ins Rennen, vielen Dank nochmal @strepwo 

![grafik](https://github.com/lumapu/ahoy/assets/22733082/07ab6f90-d1b8-40dc-b538-b3c4b6010b40)

**Comment by strepwo** [comment]
ok super 
'Code verstanden' - so halb, ist schon etwas kompliziert.. eher ein 'educated guess' :-)

Was man jetzt noch machen könnte/sollte: die Werte für den unteren Tages-Plot sind momentan einfach jeder x.te Messwert - besser wäre, diese zu mitteln (im C-code), das gibt die Gesamtleistung besser wieder. Oder anders gesagt: ein anti-aliasing einbauen.

**Comment by lumapu** [comment]
evtl. willst du diesen Wunsch einfach in #1199 formulieren, dann vergessen wir es auch nicht 😊

**Comment by Loetnase** [comment]
Wäre es möglich diese Info, wie auf der Seite Daten, auch mit darzustellen?
![grafik](https://github.com/lumapu/ahoy/assets/120967249/f91cb0e5-e02c-497a-b1e4-3867183df987)
Ich schreibe es auch mal in die #1199

**Comment by Gubi2023** [comment]
mit 15 sec- Abfrage funktioniert es jetzt tadellos, gelegentlich teste ich noch andere Abfrageintervalls.

**Comment by Gubi2023** [comment]
Test mit 30 und 25 sec. Abfrage ebenfalls ok. 
Vielen Dank für den schnellen Fix!!
