### ISSUE TITLE
getNtpTime failed

### ISSUE THREAD

**Issue by Hardy3eich** [lumapu/ahoy#1636]
## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [x ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0_.6_.__9
Github Hash: _____15ec6a0__

### Build & Flash Method:
* [x ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

ahoy DTU does not get the time and I have to click on "get time from browser" but this worked before.

is there anything I cn do about this? Power-level of nrf24I01+ ist set to MIN

perhaps the time server pool.ntp.org:123 is no more available

**Comment by Hardy3eich** [comment]
My mistake, I had forbidden the ahoy-DTU from “calling home” in the router a few weeks ago. I took out the lock and now the time is correct again.

**Comment by MetaChuh** [comment]
@Hardy3eich 

thank you for your cause and solution feedback.
if this issue is solved for you, please close it.

greetings,
metachuh

**Comment by Loetnase** [comment]
Maybe you can take your router as your timeserver. Most of the router can do that.

**Comment by Hardy3eich** [comment]
I tried that and though my fritz.box should work as a time server it does not work with these settings

![image](https://github.com/lumapu/ahoy/assets/133273946/f676ee90-e3c8-466c-a8ba-4b85c144eb57)

and does not work with corresponding IP 192.168.178.1

**Comment by Loetnase** [comment]
set your port to 123
![Screenshot_20240524-071116_Firefox](https://github.com/lumapu/ahoy/assets/120967249/aebbce63-6051-433e-9334-86187469e232)
and make the hook in
![Screenshot_20240524-075239_Firefox](https://github.com/lumapu/ahoy/assets/120967249/81d80036-7ef5-44ad-ac74-b9489310912f)
i have it working

**Comment by DanielR92** [comment]
I think it is now working, I closed this topic. 
Reopen when not pls.
