### ISSUE TITLE
Feature Request: HTML Titel änderbar

### ISSUE THREAD

**Issue by geronet1** [lumapu/ahoy#1639]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.93 ETH

### Github Hash

1b73e49

### Build & Flash Method

VSCode - Platform IO (build & flash)

### Setup

-

### Error description

Ich hab drei Fenster mit Ahoy offen und man kann sie nicht unterscheiden da immer nur Index im Titel steht.
Am besten wäre es wenn man einen Hostnamen im Setup setzen kann und dieser erscheint im Titel als auch auf der Hauptseite links oben.

**Comment by rmayergfx** [comment]
@lumapu 
Bitte den Tag BUG entfernen. Ist ja kein Bug sondern ein Feature Request.

@geronet1 
Habe bei mehreren AhoyDTU mir so beholfen, das ich den DarkMode an- bzw. ausgeschaltet habe. Somit sieht man zumindest optisch schon mal einen kleinen Unterschied bei 2 verschiedenen Systemen. Bei mehreren wird es dann schon etwas komplizierter.
Zudem ändert sich der Titel ja mit dem jeweils angewählten Untermenue, Index, Daten Verlauf. 
Ich empfehle dir eine lokale Hilfsseite zu bauen mit 3 iFrames, da kannst du über die Frames den jeweiligen von dir gewünschten Titel der WR schreiben, und im iFrame die Seite deiner Wahl aufrufen und hast mit einem Aufruf immer alle 3 Ahoy in einer Ansicht.
Siehe https://www.a-coding-project.de/ratgeber/html/frames
```
<frameset cols="33%, 33%, 33%" > 
<frame name="linkerFrame" src="http://IP_AHOYDTU_1/history">
<frame name="mittlererFrame" src="http://IP_AHOYDTU_2/history">
<frame name="rechterFrame" src="http://IP_AHOYDTU_3/history">
</frameset> 
```
@lumapu 
Denk mal darüber nach, ob man vielleicht in AhoyDTU für die Webseite die Hintergrundfarbe selbst definieren kann in einem Feld bei den Settings, dann könnte sich jeder die passende Farbe selbst aussuchen und man hätte eine optische Unterscheidung.

**Comment by lumapu** [comment]
passt zu #1199
