### ISSUE TITLE
Graph on the "small" display shows no values

### ISSUE THREAD

**Issue by wurschtbrot01** [lumapu/ahoy#1640]
Hello,
I have the problem that I can activate the graph on my small display and see it, but it remains empty without any "values"

I've already restarted it and reinstalled it
but the same problem always remains
![20240526_204352](https://github.com/lumapu/ahoy/assets/166860571/7025c5a6-1af2-45f3-be44-93052e79369e)
![20240526_204417](https://github.com/lumapu/ahoy/assets/166860571/de42c96c-a1a0-40cc-86fd-e29c3c2d7879)
![Unbenannt](https://github.com/lumapu/ahoy/assets/166860571/ac05c03e-dc55-4da7-84a2-d91621c051c8)

## Hardware
  * [ ] ESP32 ESP32-D0WD-V3

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [yes ] external antenna (SMA)

### Power Stabilization:
* [yes ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module

### Version / Git SHA: 
Version: 0.8.83
Github Hash: _______

### Build & Flash Method:
* [x ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

**Comment by Dirk-Ahoy** [comment]
Nach dem Nick ja in Deutsch :)  Du musst die Koordinaten von dir zu Hause im Menu eintragen sonst geht der Graph am Display nicht.

**Comment by wurschtbrot01** [comment]
> Nach dem Nick ja in Deutsch :) Du musst die Koordinaten von dir zu Hause im Menu eintragen sonst geht der Graph am Display nicht.

Hey Hey,
ja Deutsch ;)
alles klar... hab mal Längen und Breitengrade  eingefügt... nur leider sind meine WR schon offline ;)
werde morgen mal berichten.
Vielen Dank schonmal ;)

**Comment by Loetnase** [comment]
Installiere dir doch gleich die aktuelle DEV 8.122, da wurde einiges verbessert und verschönert. Auch die online Leistungsanzeige.
Längen und Breitengrade brauchst du dort aber auch.

**Comment by wurschtbrot01** [comment]
Danke an euch!!!
funktioniert jetzt und kann geschlossen werden ;)
![WhatsApp Image 2024-05-27 at 09 14 41](https://github.com/lumapu/ahoy/assets/166860571/804b4725-6f7a-4a95-9ac3-89a52c11ccba)
