### ISSUE TITLE
unable to use static IP [Bug]

### ISSUE THREAD

**Issue by technics42** [lumapu/ahoy#1643]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.122.

### Github Hash

4ca0562

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

no mqtt

### Error description

Using 0.8.101 I can use static IP - but when using 0.8.122 I am not able to use static IP
DTU is booting and displaying static IP (e.g. 192.168.0.43), but one cannot connect to it.
USB-log says:

I: Network connected
E: failed to set static IP!
E: failed to set static IP!
...

After some resets/reboots, DTU comes up with completely different IP (e.g. 192.168.0.16) and I am able to connect to this one. In settings my set IP is displayed, but not used.
If I save again and reboot, DTU is not reachable - same error: failed to set static IP
I tried different IP, no success - prior versions worked without problems.

**Comment by MetaChuh** [comment]
@technics42 

thx for the info.

i can currently not reproduce this behaviour with 0.8.122.
but i guess this could be, that the router has clogged this ip to a specific different mac address of a device that once had this ip.

to verify: can you downgrade to 0.8.101 and check again ?
if i'm correct, same will happen after downgrading 0.8.101, if the router is not rebooted.
if imy first ad-hoc thoughts are wrong, i'm intreagued about what could be the cause of this unexpected behaviour.

thx again & greetings,
metachuh

**Comment by technics42** [comment]
Version 0.8.101 is working fine - no problems to set IP and use this one. (also after downgrading)
When using 0.8.122 I am not able to use static IP - I am always getting error.
After rebooting some times, the DTU comes up with the first free IP assigned by DHCP.

**Comment by SebiWolze** [comment]
Same error with 0.8.122 - ESP32 Wroom here

**Comment by technics42** [comment]
Thank you - with version 0.8.123 I am able to use static IP again.

**Comment by DanielR92** [comment]
Then we can close this topic here? :)

**Comment by technics42** [comment]
I am closing it, although I can't use 0.8.123 due to restarting problems - and 0.8.124 was only built for ESP8266 as minimal version, which I don't want to use...
