### ISSUE TITLE
V0.8.123: nach 6 std. nicht mehr erreichbar[Bug]

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1651]
### Platform

ESP32

### Assembly

the DTU was already assembled

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.123

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

updated um 2 uhr von 0.8.122

### Error description

nachdem die 0.8.122 ohne Probleme 6 Tage durchlief, ist die 0.8.123 schon nach 6 St. nicht mehr erreichbar, auch per ping nicht, obwohl sie in der Fritzbox noch angezeigt wird; auch ein WLAN aus/ein der Fritzbox, das die Vorgängerversion wieder erreichbar machte, blieb erfolglos..

**Comment by Gubi2023** [comment]
![2024-05-31 12_59_12-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/6b5957fb-1a4d-463a-9b4d-d5dceed563d3)


Nach Spannung aus/ein der DTU lief sie wieder.

**Comment by technics42** [comment]
I guess it's related to the exceptions I am encountering. Maybe if you try to reach DTU by browser, it may cause a reboot and DTU would be available again (for some time).

**Comment by Dirk-Ahoy** [comment]
Also meine 4 DTUs sind alle durchgelaufen seit heut morgen 6:00 - alle erreichbar und kein reboot.

**Comment by dtuuser** [comment]
Meine auch seit dem Update vor 14 Stunden stabil ohne Reboot

**Comment by Tolbag** [comment]
Mein ESP8266 ist auch alle paar Tage, oft gegen Nachmittag, nicht mehr erreichbar. Netzteil an/aus startet ihn komplett neu, dann geht es sofort wieder.
Neugestartet per Software wird immer um Mitternacht.

**Comment by lumapu** [comment]
wie gut ist bei euch der WLAN Empfang?

**Comment by Gubi2023** [comment]
sehr unterschiedlicher Empfang, zwischen 1-3 Balken..
wenn ich die DTU neu starte, habe ich sehr guten Empfang, irgendwann wird er schlechter.
Hab jetzt die .124 drauf, gestern 3 Reboots, heute lief sie durch.
könnte es damit zusammenhängen, ob man die Webseite aufruft? Diesen Eindruck hatte ich manchmal.

**Comment by Gubi2023** [comment]
heute morgen 7:47 Uhr startete sich DTU wieder neu. Hab mal in HA den entsprechenden Zeitraum angeschaut, keine Auffälligkeiten. k.A. warum sie rebootet hat. (um die Zeit hab ich noch geschlafen)

**Comment by Gubi2023** [comment]
tja, bin grad im Urlaub, also keiner zuhause, aber meine DTU (V.126) rebootet sich trotzdem fröhlich  3-4mal am Tag vor sich hin. Ärgerlich, da dann ständig mein Verlauf beim Teufel ist.

**Comment by cibis8** [comment]
Bei mir auch sehr viele Reboots, bin wieder zurück zur .110, da danach ja das DHCP nicht mehr ging. Aktuell bleibe ich bei der 110. die lief ohne Probleme auch mehrere Tage/Wochen.

**Comment by Dirk-Ahoy** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/141040118/7669065c-0fdf-4129-bbfc-375b25dcd48f)

Kann mich nicht beschweren - das ist noch 123 -die 126 läuft auf 2 Fusion Board auch ohne Reboot bis jetzt.

**Comment by Gubi2023** [comment]
Ich habe jetzt beobachtet, dass ide Empfangsstärke zwischen DTU und WR kontinuierlich abnimmt. Anscheinend startet sich die DTU neu, wenn kein Empfang mehr da ist, die Empfangsstärke ist dann wieder auf max.  
![Screenshot 2024-06-29 161622](https://github.com/lumapu/ahoy/assets/142897856/366e39c1-7bea-4f51-a1a9-e48c61821abd)
![Screenshot 2024-06-29 161449](https://github.com/lumapu/ahoy/assets/142897856/875e6a62-ff82-448d-8bb2-0af450865eca)

**Comment by Gubi2023** [comment]
> wie gut ist bei euch der WLAN Empfang?
Ich habe jetzt beobachtet, dass die Empfangsstärke zwischen DTU und WR kontinuierlich abnimmt. Anscheinend startet sich die DTU neu, wenn kein Empfang mehr da ist, die Empfangsstärke ist dann wieder auf max.
![grafik](https://github.com/lumapu/ahoy/assets/142897856/b4a98f57-c61c-4830-85c7-4edd7ac14145)
![Screenshot 2024-06-29 161449](https://github.com/lumapu/ahoy/assets/142897856/59c867ec-fced-4927-a1d0-9aff009bc7e0)
siehe auch weblog
![Screenshot 2024-06-29 163204](https://github.com/lumapu/ahoy/assets/142897856/442320cf-0115-49e9-a75c-a9b6fc886b77)

**Comment by lumapu** [comment]
meinst du wirklich die Empfangsstärke der Wechselrichter oder evtl. den des WLAN Moduls? Ich habe beobachtet, dass bei schlechter WLAN Verbindung der Speicher durch MqTT von Ahoy vollläuft und den Reboot verursacht.

**Comment by Gubi2023** [comment]
Die Feldstärke zur Fritzbox zeigt immer 3 Balken, die in Ahoy schwankt wie oben angezeigt.
![Screenshot 2024-07-07 210902](https://github.com/lumapu/ahoy/assets/142897856/1d117aa5-5740-44fd-88ae-a0d007bf0538)

**Comment by Dirk-Ahoy** [comment]
Bei 1Mbits vom Repeater zur Ahoy kein Wunder -  solltest du mal was näher an die Fritzbox bringen oder an den Repeater.

**Comment by Gubi2023** [comment]
Das Teil steht direkt neben einer Fritzbox7560,  k.A. warum es sich nicht mit der verbindet....

**Comment by Dirk-Ahoy** [comment]
Steck die DTU doch mal 15min aus abends und guck dann ob sie sich mit der Fritzbox verbindet dann statt mit dem Repeater.

Und mal die 127 verwenden da hatte Lukas zwischen der 123 noch was geändert mit dem Wlan meine ich - bin aber gerade nicht sicher.

**Comment by Gubi2023** [comment]
Das Ding wird über mesh immer wieder mit nem anderen Repeater verbunden....
![Screenshot 2024-07-08 152652](https://github.com/lumapu/ahoy/assets/142897856/d7199855-3f84-4e6f-8210-73474b522905)


bin inzwischen auf 127

**Comment by lumapu** [comment]
@knickohr, du hattest irgendwas ähnliches geschrieben, dass AVM ein neues Feature eingeführt hat was evtl. zu diesem Verhalten führt.
Ich denke es war der hier:

* https://github.com/lumapu/ahoy/issues/1596

**Comment by knickohr** [comment]
Ja, genau das ist es !

Nochmal zur Verifikation :  Welche FW läuft auf der Fritte ?

**Comment by Gubi2023** [comment]
ich habe immer noch 2-3 reboots täglich, aber wie es aussieht, liegt es daran: MqTT läuft voll und bekommt die Pakete nicht abgeschickt, Ahoy bricht dann zusammen, da kein Speicher mehr da ist (siehe #1686) Deshalb mach ich den Issue zu und hoffe auf Beseitigung des MqTT-Fehlers.

**Comment by knickohr** [comment]
Das Problem MQTT sollte ab der 124, spätestens ab der 126 behoben sein. Es reconnected zwar weiterhin den Broker, aber es sollte nicht mehr booten. Außer der Broker meldet sich nicht mehr.

**Comment by Gubi2023** [comment]
ich habe Lukas am 7.7. nen coredump mit .127 geschickt, da war der Fehler noch drin... und mein broker sollte ständig erreichbar sein.
