### ISSUE TITLE
[Bug]Leistungsbegrenzungseingabe in Watt fehlerhaft?

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1662]
### Platform

ESP32

### Assembly

the DTU was already assembled

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.123

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

mit flole-Tool getuned

### Error description

wenmn ich die Leistungsbegrenzung in % angebe, wird sie immer übernommen, bei Eingabe in Watt macht er ,0 % draus...
Siehe screenshots   
![2024-06-04 14_14_58-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/f645dad3-8821-4ee1-9602-1e224bd340a5)

![2024-06-04 14_16_42-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/596f3581-952c-43b3-b3d9-cae0019ee71a)

![Screenshot 2024-06-04 144606](https://github.com/lumapu/ahoy/assets/142897856/f011e3a9-68af-4be3-ad17-f47ccacac99f)

**Comment by knickohr** [comment]
800W bei einem HM-600 ? 😲

**Comment by Gubi2023** [comment]
s.o.:
mit flole-Tool getuned
ausserdem: die Eingabe einer höheren Prozentzahl ging immer, ob sinnvoll oder nicht...

**Comment by dknubben** [comment]
@Gubi2023 
Bedeutet dies, dass AhoyDTU grundsätzlich auch nach dem Mod mit dem Flole-Inverter-Tool weiter uneingeschränkt funktioniert?
Hierzu konnte ich bisher keine Infos finden.

**Comment by stefan123t** [comment]
@dknubben flole hatte das Firmware Image der HM-600 so angepaßt, dass das selbe harte Limit wie bei einem HM-800 gilt. Ich vermute das ist lediglich ein max. Wert irgendwo im FW image. Die API und anderen FW code hat er zwar disassembled, um es zu verstehen, aber nicht angepaßt.
@Gubi2023 hat jetzt festgestellt dass bei Eingabe eines absoluten Wertes in W der HM-600 einen Prozentwert zurück meldet, dieser hat ggf. Rundungsfehler und daher die Angabe einer zusätzlichen Dezimalen. Umgekehrt bei Eingabe eines Prozentwertes wird m.W. dieser exakt angesteuert und auch an Ahoy zurück gemeldet.
Eventuell kommt der Rundungsfehler daher, dass wir bei HM-600 einen max. Wert von 600Wpp und nicht 800Wpp annehmen ?
Vielleicht sollte man also für die flole mod's unter den Anwendern eine Option einbauen, die das harte Limit durch den flole mod pro Inverter editierbar macht oder die Dezimale bei der Prozentangabe abschaffen, dann sind 79,9% auch wieder 80% ?

**Comment by Gubi2023** [comment]
ich glaube nicht, dass das was mit dem Flole-Tool zu tun hat.
Wenn ich z.B. 400W eingebe, kommt in der Anzeige 39,9% also 40 Prozent und nicht 400 Watt! 
<img width="800" alt="Screenshot 2024-06-05 101728" src="https://github.com/lumapu/ahoy/assets/142897856/ed064916-bc71-41bb-8bf7-7786a6087466">

**Comment by Gubi2023** [comment]
oder hat es früher richtig funktioniert? hab ich leider nie getestet...

**Comment by knickohr** [comment]
Ich kann es nicht nachstellen.

![IMG_2706](https://github.com/lumapu/ahoy/assets/63048210/cf9164c7-1733-4be6-aac2-916eca9517ca)

![IMG_2707](https://github.com/lumapu/ahoy/assets/63048210/7afd3b3d-8fce-4f27-a85e-2bf247559a2f)

![IMG_2708](https://github.com/lumapu/ahoy/assets/63048210/7ed8fb43-a701-4f9e-9687-17b1a641afc7)

![IMG_2709](https://github.com/lumapu/ahoy/assets/63048210/2980a486-2f24-4146-93d1-e5b066cfdace)

**Comment by Gubi2023** [comment]
na schön, vllcht liegts doch am Flole, ich schicks ihm mal...

**Comment by stefan123t** [comment]
Sag schöne Grüße und schau mal in #1644 da hat @Knickohr das m.E. relativ gut beschrieben.
Wenn Flole's mod die max peakpower des Inverters anpasst aber nicht die Serial Number anpasst dann geht Ahoy und OpenDTU von einem anderen Inverter Modell aus und es kommt in deren Folge zwangsläufig zu Rechenfehlern von Watt zu % und umgekehrt.

**Comment by Flole998** [comment]
Da der 2 in 1 auf 1000W erhöht werden kann und es dafür gar keine passende Seriennummer gibt bleibt nur die Option, eine manuelle Möglichkeit zur Eingabe der maximalen Leistung zu schaffen (sich da irgendwas "auszudenken" ist nicht praktikabel).

Wenn ahoy die Werte als Absolute bzw. Relative Werte an den Wechselrichter schicken würde (also nicht vorher da dran rumrechnen würde) dann würde es auch korrekt funktionieren (wobei dann die angezeigte maximale Leistung in W dann falsch ist sofern sie auf der Rückmeldung basiert, und nur die % stimmen, das ist aber dann ein kosmetisches Problem was im Betrieb nicht weiter stören sollte).

**Comment by stefan123t** [comment]
@Flole998 genau so ist es, Ahoy schickt die Werte in W oder % an den Inverter und liest dann nach ca. 5 Sekunden die Rückmeldung in %. Diese wird dann wieder umgerechnet anhand der max peak power Werte basierend auf der Serial ID bzw. deren Modell Prefix.
+1 für ein zusätzliches Feld pro Inverter das mit der max peak power vorbelegt wird aber eingestellt werden kann.

**Comment by Flole998** [comment]
Aha, da wird also doppelt gerechnet? Ich hätte erwartet, dass die Rückmeldung in Prozent akzeptiert wird und verwendet wird und nicht, dass man von Prozent auf Leistung und zurück auf Prozent rechnet..... Wobei es selbst damit passen müsste.

**Comment by Gubi2023** [comment]
oh,oh da hab ich ja mit meinem Issue wieder was ausgelöst... sorry!

**Comment by knickohr** [comment]
Das Problem ist das man zwar Limits in Watt als auch in % schicken kann. Aber man bekommt das gesetzte Limit leider nur in % vom Inverter zurück.

Mit der neuen „bedarfsoptimierten Leistungsregelung“ in Ahoy haben wir uns entschieden, diese Limits immer in W zu senden. Es macht es für die Benutzer einfacher und die Powermeter liefern auch W 😉

Um aber vergleichen zu können, muß mindestens einmal umgerechnet werden. Dazu brauchen wir die zurückgelieferten % und eben aus der Seriennummer das max. W was der Inverter kann.

**Comment by knickohr** [comment]
@Flole998 

Zum Thema Invertertuning, Pimping, aufbohren & Co.:
Wir werden in Ahoy keine Softwareänderungen machen um diese geänderte Firmware zu unterstützen. Das hat weniger mit Dir zu tun, als mit der Tatsache das die Benutzer die Garantie verlieren und aus sicherungstechnischen, bzw. brandschutztechnischen Gründen. Wir möchten nicht in die Schußlinie von Hoymiles geraten oder an einem manipulierten Gerät und deren Folgen Teil haben.

**Comment by Flole998** [comment]
@knickohr Ich nutze ahoy nicht und hab mich hier nur gemeldet weil jemand einen Bug in ahoy entdeckt hatte und einen Zusammenhang mit der veränderten Leistung vermutet hat. Insofern ist es mir persönlich relativ egal ob das nun in ahoy unterstützt wird oder nicht, primär stört es die Nutzer von euch (bzw. diejenigen, welche keine Lust haben das ganze zu forken und entsprechend anzupassen).

In openDTU scheint das ganze hingegen anders (bzw. "richtig") implementiert zu sein, dort wird die Eingabe unverändert an den Wechselrichter geschickt, sodass es dort korrekt funktioniert, sowohl bei relativen Werten als auch bei absoluten Werten.

**Comment by Gubi2023** [comment]
also ich kann mit dem Fehler leben, nur wegen mir muss man da keine Klimmzüge machen.... (ich geb eben % ein, da funktioniert es ja)

**Comment by knickohr** [comment]
„Jedwede Änderungen an der original Firmware von Hoymiles und die daraus resultierenden Fehler bzw. seltsame Verhaltensweisen werden von Ahoy nicht supportet. Bei Problemen wenden Sie sich bitte an den Entwickler der diese Änderungen an dem Wechselrichter vorgenommen hat.“

**Comment by Flole998** [comment]
Bei Problemen mit Ahoy macht es keinen Sinn die Leute zu irgendwem zu schicken der nichts mit Ahoy zutun hat. Wenn es dafür keinen Support von dir gibt ist das deine Entscheidung, nur wird niemand außerhalb des Ahoy-Projektes plötzlich support für Ahoy anbieten können und wollen. Besser wäre es also, wenn man sagt "Bitte Originalzustand wiederherstellen und das Problem damit reproduzieren, wenn es immer noch ein Problem gibt gerne erneut melden".

**Comment by knickohr** [comment]
Es ist kein Problem von Ahoy, es wurde gestern Abend ausgiebig von mehreren Testern und Entwicklern, einschließlich mir, nachgestellt und ausprobiert Wir konnten nie so einen Zustand erzeugen. Selbstredend konnten wir nur die original Firmware testen. Ich empfehle auf den Originalzustand zurück zu gehen und noch einmal zu testen. Sollte dann das Problem weiterhin bestehen müssen wir noch einmal testen, wenn es denn überhaupt möglich ist den Originalzustand wieder herzustellen. Aber das hast Du ja bereits geschrieben.

Nichtsdestotrotz stehen wir dieser Firmwaremodifikation sehr kritisch gegenüber.

**Comment by Gubi2023** [comment]
habe auf Originalfirmware zurückgerüstet und nochmals getestet. W-Eingaben werden wie bei Knickohr angezeigt. Problem liegt also wie auch oben erläutert am Flole-Tool. Deshalb mache ich den Issue jetzt zu.

**Comment by stefan123t** [comment]
Ich habe das Zitat hier gefunden: 

https://github.com/lumapu/ahoy/issues/1662#issuecomment-2150673252

Ist das von Hoymiles oder von @lumapu ?

Ich würde nicht sagen, dass wir die Modifikation mit dem @Flole998  Invertertool speziell supporten oder unterstützen müssen.

Das Missverständnis kommt nur bei den Usern auf, da sie einen HM-600 mit offiziellen max peak power 600W haben. Ahoy und OpenDTU senden das Limit verbatim als relative % oder absolute W Angabe an den Inverter und der setzt das ActivePowerLimit dementsprechend richtig. Nach 5 Sekunden fragen wir mit [SystemConfigParam](https://github.com/lumapu/ahoy/wiki/Protocol#systemconfigpara--0x05) den Inverter ob das neue Limit richtig angesteuert wurde und erhalten dabei nur einen relativen Prozentwert zurück. 

Diesen relativen Wert rechnen wir dann zur klaren Anzeige auch in eine absolute Wattangabe um. Hierbei wird die aktuell unveränderliche max peak power Angabe aus der Modellnummer verwendet.

Wenn diese also initial je Inverter auf zB 600W für einen HM-600 steht, müssten wir nach dem Mod mit dem Flole Invertertool mit 800W rechnen, damit auch der richtige Absolutwert rauskommt. 

Also einfach die max peak power Angabe fest vorbelegen aber editierbar machen, so dass Anwender mit Flole Mod den Wert und damit das Ergebnis anpassen können.

https://github.com/lumapu/ahoy/issues/1662#issuecomment-2149714717

Es ist also kein Bug sondern ein Feature (Request) 😃

**Comment by Gubi2023** [comment]
warum so kompliziert? Einfach darauf hinweisen, dass beim Einsatz des Flole-tools die Leistungsanpassung in % und nicht in Watt eingetragen werden muss und alles ist gut... (siehe ⁠flole-invertertool⁠ in discord)
