### ISSUE TITLE
Feature Request: Calculate daily History plot from Sunrise/Sunset

### ISSUE THREAD

**Issue by BenjiKimba** [lumapu/ahoy#1664]
## Hardware
  * [ ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by BenjiKimba** [comment]
Calculate a daily History plot from Sunrise/Sunset values in seconds, or unselect a box if you want to give in the seconds
manually to see a more detailed curve over a few hours.

**Comment by BenjiKimba** [comment]
![Resolution](https://github.com/lumapu/ahoy/assets/170186653/0f48916e-12a0-4051-9f44-10a2e77d183f)


And also to improve the resolution of the history curve.
The picture give the History from 9:00 to 15:00 with a resolution from 115 sec. per sample, alternately cloudy and sunny
wil give a not so smooth picture, for a whole day I need a resolution of 225 sec, per sample if the total samples of History are 256.
Better results can given by sampling with the default value of 15 sec., so divide 225/15=15, add 15 times the value in Watts and
divide it bij 15, it wil give a more real value over what happened in 255 sec.

**Comment by BenjiKimba** [comment]
![1636](https://github.com/lumapu/ahoy/assets/170186653/a7fb52fe-f842-46e2-a65f-1af800a02821)
This is how it looks at 16:36

**Comment by Gubi2023** [comment]
hello, the latest dev.  Versions have time Stamps in history, see screenshot   
![signal-2024-05-13-203734_002](https://github.com/lumapu/ahoy/assets/142897856/b1a4114e-97f0-4605-9ccc-029b0359f282)

**Comment by Gubi2023** [comment]
otherwise you have to wait for the next release...

**Comment by BenjiKimba** [comment]
Ah, thank you.
