### ISSUE TITLE
Fehlende Menü Eintäge /  Darstellung in der Web GUI, Warum?

### ISSUE THREAD

**Issue by ralfberger** [lumapu/ahoy#1665]
## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ x] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: 0.8.123

Ich bekomme nur diese Darstellung:
![Screenshot_20240607_145203](https://github.com/lumapu/ahoy/assets/63057484/2961eb48-f1ab-428e-98a4-04341ed3e7a0)

das restliche Menü fehlen, egal ob ich  FireFox oder Chrome nutze.

**Comment by Gubi2023** [comment]
Die Verbindung zur DTU ist unterbrochen. Entweder warten bis sie aufgebaut wird, oder DTU aus/einstecken

**Comment by ralfberger** [comment]
Ich verstehe deine Antwort nicht, wie meist du das? Ich habe doch eine Verbindung zum Webinterface, mein MQTT Broker empfängt auch fleißig alle Werte. Neustart bringt keine Veränderung. Das heißt für mich, die Verbindung zum Wechselrichter ist i.O. und die Verbindung von meinen PC zum ESP funktioniert auch.

**Comment by dknubben** [comment]
So sieht die Darstellung aus, wenn Javascript deaktiviert ist oder aus anderen Gründen blockiert wird.

**Comment by lille2000** [comment]
Selbe Thema wie hier #1619

**Comment by ralfberger** [comment]
@dknubben 
Danke für den Hinweis, aber an Javascript liegt es nicht. Ich habe sowohl verschiedene Browser und auch Rechner ausprobiert. 
Jetzt habe ich den ESP mehrmals Stromlos gemacht und jetzt bekomme ich alle Daten wieder angezeigt.

*** Edit ***
@lille2000
Auch wenn ich nur ein Wechselrichter habe, scheint das die Lösung zu sein. Danke für den Link, trotz suchen habe ich diese Info nicht gefunden.

**Comment by juepi** [comment]
Ich kenne das Problem von meinem Setup (auch ESP8266), ich hab schlechten WLAN Empfang und bin mir ziemlich sicher dass es daran liegt.
Nachtrag: im Menüpunkt "System" meldet mir mein ESP einen WiFi RSSI von -76.

**Comment by ralfberger** [comment]
Das kann sicher auch am schlechten Wlan Empfang liegen.  Bei mir ist es aber bestimmt so wie es lille2000 verlinkt hat.
[#1619](https://github.com/lumapu/ahoy/issues/1619)
Nach dem downgrade auf 0.8.97 läuft die DTU wieder stabil.

**Comment by lumapu** [comment]
wenn es ein ESP32 ist und dieser die Webserver-Ausfallerscheinungen gibt, wäre es sehr hilfreich, wenn ich dazu einen Coredump bekommen könnte. Unter `/system` gibt es dafür einen Button.

**Comment by ralfberger** [comment]
nein, ich nutze ein 8266.
