### ISSUE TITLE
restart Ahoy mit MqTT Befehl

### ISSUE THREAD

**Issue by DanielR92** [lumapu/ahoy#1667]
Es wurde gewünscht (wie im Titel zu lesen).
Sobald MQTT umgebaut wurde (Queue), kann dies auch mit aufgenommen werden.

**Comment by lumapu** [comment]
Queue ist doch schon umgebaut, oder auf was beziehst du dich?

**Comment by DanielR92** [comment]
Na, ich kann das aktuell nicht einbauen da pubMqtt.h::onMessage die Funktion es noch nicht hergibt die Daten korrekt auszuwerten. 

Ich bin hier noch etwas unzufrieden wie es aktuell gelöst ist.

**Comment by lumapu** [comment]
beziehst du dich auf Versionen vor `0.8.124` oder ab `.124` und neuer?
In der `.124` habe ich die Queue bereits umgebaut, wie es @fumanchi empfohlen hat. Also bei `onMessage(...)` wird der Inhalt in eienr `std::queue` eingereiht. Diese Queue wird dann in der `loop` durch eine leere ausgetauscht (`std::swap`) und anschließend die getauschte geleert. Alles ist per `mutex` threadsafe gestaltet.

**Comment by lumapu** [comment]
Ahoy subscribed hier ein neues topic. Wichtig für ioBroker Nutzer: nach dem über das topic ein reboot getriggert wurde, muss man den Wert wieder löschen, sonst befindet sich Ahoy in einer Bootschleife - das liegt daran, dass ioBroker den Wert beim Subscriben gleich wieder rausschickt.

![grafik](https://github.com/user-attachments/assets/40506a53-03ec-48b0-88c4-1079d2c245d0)

**Comment by knickohr** [comment]
Verbesserungsvorschlag :  Ahoy setzt diesen Wert vor dem Reboot selbst zurück 😉

Es ist eine Frage der Zeit bis „ein Dummer“ kommt und genau deswegen Issues aufmacht. Nur weil er vergessen hat das sein HA oder weißgottwas default retained Topics macht.

**Comment by lumapu** [comment]
ja habe auch schon darüber nachgedacht, finde es aber eigentlich ein Fehler von ioBroker und nicht von Ahoy.

**Comment by knickohr** [comment]
Das ist doch genau das gleiche wie mit den Werten die über Nacht nicht verfügbar sind und im HA n/a ausgeben 😞
