### ISSUE TITLE
[BUG] ESP32 (CMT2300A) crash with esp_core_dump_flash error

### ISSUE THREAD

**Issue by agoetz1984** [lumapu/ahoy#1681]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.83

### Github Hash

5ebfe5a

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

{"version":11,"wifi":{"ssid":"BR_WL","pwd":"","ap_pwd":"esp_8266","hidd":false,"dev":"AHOY-DTU","adm":"","prot_mask":61,"dark":true,"reb":false,"region":0,"timezone":1,"ip":"","mask":"","dns1":"","dns2":"","gtwy":""},"nrf":{"cs":5,"ce":4,"irq":16,"sclk":18,"mosi":23,"miso":19,"en":false},"cmt":{"csb":4,"fcsb":5,"irq":16,"dio":23,"clk":18,"en":true},"ntp":{"addr":"pool.ntp.org","port":123,"intvl":720},"sun":{"lat":0,"lon":0,"offs":0,"offsEve":0},"serial":{"show":false,"debug":true,"prv":true,"trc":true,"mqtt":false},"mqtt":{"broker":"","port":1883,"clientId":"","user":"","pwd":"","topic":"inverter","intvl":0},"led":{"0":25,"1":255,"2":26,"act_high":false,"lum":49},"plugin":{"disp":{"type":2,"pwrSafe":false,"screenSaver":1,"graph_ratio":0,"graph_size":2,"rotation":0,"contrast":140,"data":21,"clock":22,"cs":255,"reset":255,"busy":255,"dc":255,"pirPin":255},"cst_lnk":"","cst_lnk_txt":""},"inst":{"intvl":15,"en":false,"rstMidNight":false,"rstNotAvail":false,"rstComStop":false,"strtWthtTime":false,"rstMaxMidNight":false,"yldEff":1,"rdGrid":true,"iv":[{"en":true,"name":"BKV_JG","sn":141293330912,"freq":12,"pa":0,"dis":true,"yield":[0,0,0,0,0,0],"pwr":[440,440,400,400,400,400],"chName":["Li","Re","","","",""]}]}}

### Debug Serial Log output

```shell
<\n><\n>--------------------------------
Welcome to AHOY!
<\n>point your browser to http://172.17.14.154 (Station)
to configure your device
--------------------------------<\n>
Wifi event: 11
Wifi event: 10
[WiFi] AP disabled
Wifi event: 11
[WiFi] mDNS established: AHOY-DTU.local
I: [NTP]: 2024-06-17 14:27:58 UTC
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400dff48  PS      : 0x00060830  A0      : 0x80197aa0  A1      : 0x3ffb2190  
A2      : 0x3ffc39e0  A3      : 0x3ffc3de8  A4      : 0x3ffca6b8  A5      : 0x00000001  
A6      : 0x00000000  A7      : 0x3ffc3de8  A8      : 0x00000001  A9      : 0x3ffb2170  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x00000001  A13     : 0x3ffb2160  
A14     : 0x3ffcb808  A15     : 0x00000001  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400901e0  LEND    : 0x400901ee  LCOUNT  : 0x00000001  


Backtrace: 0x400dff45:0x3ffb2190 0x40197a9d:0x3ffb21d0 0x400d35b9:0x3ffb21f0 0x400eb13b:0x3ffb2230 0x400efa86:0x3ffb2270 0x40109209:0x3ffb2290




ELF file SHA256: 4f39b1ba370aa825

E (15312) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
E (521) esp_core_dump_flash: No core dum?<\0><24>?????????found!
E (521) esp_core_dump_flash: No core dump partition found!
I: Initializing FS ..
I:  .. done
I: Config Version: 11
I: Settings valid: true
<\n>---------<\n>AhoyDTU Info:
Version: 0.8.83
Github Hash: 5ebfe5a
<\n>---------<\n>AP MODE<\n>SSID: AHOY-DTU
PWD: esp_8266
IP Address: http://192.168.4.1
```

### Error description

Hello,

the ESP32 is in reboot loop after doing the configuration. 
Reflash, cleaning flash, slow flash other ESP, nothing works.
The device starts up, Display shows normal screen on the oled, CMT2300A is in connected state.
Everything looks fine and then reboot. Tryed many times to reflash, reconfig etc., nothing helps.
The OpenDTU CMT set from blinkyparts.com is used, everything is solderd perfect and connected well. 
Without the CMT Module connected it restarts to with same error.

Please help! 

Thanks a lot!

Andy

**Comment by knickohr** [comment]
It looks like your inverter is not enabled 😉

But try another neuer Firmware 83 is a way old.

**Comment by agoetz1984** [comment]
Nope, it was not a problem with the configuration.
The latest dev. release solved the issue. Thanks a lot.
