### ISSUE TITLE
ESP32 S3 (Alliance Fusion) flashen mit web_install

### ISSUE THREAD

**Issue by sibelle-labs** [lumapu/ahoy#1687]
Hallo miteinander,
beim flashen mit web_install (Chrome Browser) bekomme ich die Fehlermeldung  
Your ESP32-S3 board is not supported.
gibt's eine andere URL für die ESP32 S3's ?
Vielen Dank !

**Comment by Dirk-Ahoy** [comment]
https://fw.ahoydtu.de/tools/webflasher/

**Comment by sibelle-labs** [comment]
Das war's.
Vielen Dank !!!
