### ISSUE TITLE
Aktualisierung mit V0.8.127 zu langsam?

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1689]
mit der V0.8.127 werden meine Gesamtwerte teilweise nur verzögert aufaddiert. Das führt im Verlauf zu einem unschönen Sägezahnmuster (Aktualisierungsintervall 20 Sec.) Siehe Screenshots
![2024-06-25 10_06_25-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/52979fb8-c4d9-4d94-8690-f6c30a8f1ad6)

![2024-06-25 10_31_22-Greenshot](https://github.com/lumapu/ahoy/assets/142897856/c63580be-2eae-4cc8-a911-f7967fc71d25)

**Comment by technics42** [comment]
In your screenshot DC-power of inverter looks good - sum of panel's DC-power.
As far as I know, AC-power is read directly from inverter.
What about your power limit of 150%?
Are you using any kind of battery?

**Comment by dknubben** [comment]
Kann das mit Flole zusammenhängen? Ich habe das Tool zwar auch bei 3 HM-600 verwendet, aber nur auf jeweils max. 133% (knapp die 800 W). Auf mehr würde ich nie gehen. Der Leistungsverlauf ist dabei völlig in Ordnung. Evtl. mal auf originalen Zustand zurücksetzen und neu prüfen.

**Comment by Gubi2023** [comment]
wäre möglich. Habe jetzt auch gesehen, dass es bei höheren Wattzahlen richtig funktioniert. War also etwas vorschnell und mache deshalb den Issue wieder zu
