### ISSUE TITLE
V0.8.128: Meldungsanzeige

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1702]
Ist es Absicht, dass in der letzen Version der Meldungszähler auf 0 steht, obwohl ein Ereignis (Inverterstart) hinterlegt ist?

**Comment by knickohr** [comment]
Ja, „Inverster Start“ ist kein Alarm 😉

**Comment by Juergen2453** [comment]
Das stimmt so nicht ganz. Neueste Version 0.8.129

![s1](https://github.com/user-attachments/assets/4f64688f-daf8-4e3e-aeff-624e1060cfd4)

**Comment by Gubi2023** [comment]
ok, in 129 ist der Zähler wieder auf 1.

**Comment by knickohr** [comment]
Ich persönlich würde das nicht Alarm nennen sondern Event/Ereignis.

**Comment by Juergen2453** [comment]
Da steht doch "Meldungen : 1" -> "Meldungen von ..." . Nirgendwo steht da was von "Alarm"

**Comment by knickohr** [comment]
Ja, ab der 129

**Comment by Gubi2023** [comment]
in der englischen Version heisst es schon immer Alarms, aber nicht in deutsch....

**Comment by Juergen2453** [comment]
Es ist unbegreiflich. Es gab eine Frage, ich habe geantwortet mit Bild , es wurde bestätigt und das Thema geschlossen v. 129. Ob nicht richtig gelesen wird, in Deutsch steht da Meldungen und es bezog sich alles auf die v. 129. Wie unser Professor immer sagte:
Es gibt keine dummen Fragen, nur unqualifizierte Antworten.

**Comment by stefan123t** [comment]
Also Hoymiles nennt die Struktur intern AlarmData und Alarm Code / ID und die Zeilen sind dann wie in der 0.8.129 Events aus dem EventLog.

Evtl. dauert es auch einfach eine Weile bis der WR der DTU auf die Frage nach dem AlarmData Frame / EventLog ordentlich geantwortet hat.
Dann sind es eben erst 0 und später 1 ?

**Comment by Gubi2023** [comment]
nein, in der.128 wurde nicht hochgezählt, aber der Fehler wurde in der .129 berichtigt. Deshalb hab ich den Issue auch wieder geschlossen.
