### ISSUE TITLE
ERR_DUPLICATE_INVERTER in 0.8.129 bei Speichern Invertereinstellungen

### ISSUE THREAD

**Issue by Loetnase** [lumapu/ahoy#1705]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.129

### Github Hash

3c0c8ee

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Neue 0.8.129,  

### Error description

In der neuen 0.8.129 kommt bei Speichern nach Anschauen der Invertereinstellungen ohne Änderungen die Fehlermeldung: ERR_DUPLICATE_INVERTER
Es ist auch kein zweiter Inverter eingetragen. 
@brekemeier Die Ursache ist bestimmt in der Ausmerzung von issue #1700 zu suchen
![ERR_DUPLICATE_INVERTER_01](https://github.com/user-attachments/assets/2c5d44ac-c395-4a18-a6cf-eaee9ba101ca)

**Comment by brekemeier** [comment]
Die Exzeption muss bereits bei der Eingabe der Inverter-Seriennummer erfolgen. Sie wird weiterhin (0.8.129) akzeptiert. Erst bei den Einstellungen (speichern) wird die Fehlermeldung erzeugt. 
![ahoyInverterErr](https://github.com/user-attachments/assets/34d8a6ea-413a-4090-9bf1-9c2ea21c11ed)

**Comment by Loetnase** [comment]
Ohne eingetragenen zweiten Inverter sollte aber diese Fehlermeldung gar nicht kommen.
Ich habe nur mein System über OTA auf die 0.8.129 hochgezogen, dann die Einstellungen des einen eingetragenen WR durchgeschaut, dann dort speichern gedrückt und die Fehlermeldung erhalten. 
Mit nur einem Inverter sollte diese Fehlermeldung eigentlich nicht kommen.

**Comment by brekemeier** [comment]
Ich aktualisiere das Build auch über OTA und kann zweimal die gleiche SN eingeben und erhalte keine Fehlermeldung (ESP32Wroom32).

AhoyDTU addiert auch die Werte, wie vorgesehen. Erst bei der Anpassung der PV-Module meldet er den Fehler.

Gut, ist ja nur ein Hinweis.  ERR_DUBLICATE_INVERTER sollte bereits bei der Eingabe der SN erfolgen. Sonst ist alles gut, ich bin bei

einem Test, für mehrere Inverter, darauf gestoßen und Fehler sollen wir ja melden.

 

Von: loetnase ***@***.***> 
Gesendet: Montag, 15. Juli 2024 11:13
An: lumapu/ahoy ***@***.***>
Cc: brekemeier ***@***.***>; Mention ***@***.***>
Betreff: Re: [lumapu/ahoy] ERR_DUPLICATE_INVERTER in 0.8.129 bei Speichern Invertereinstellungen (Issue #1705)

 

Ohne eingetragenen zweiten Inverter sollte aber diese Fehlermeldung gar nicht kommen.
Ich habe nur mein System über OTA auf die 0.8.129 hochgezogen, dann die Einstellungen des einen eingetragenen WR durchgeschaut, dann dort speichern gedrückt und die Fehlermeldung erhalten.
Mit nur einem Inverter sollte die eigentlich nicht kommen.

**Comment by knickohr** [comment]
#1700

**Comment by knickohr** [comment]
Kann ich bestätigen. Egal was man an den Invertereinstellubgen macht, es kommt immer Duplicate. Vermutlich weil er den Inverter bereits kennt und beim Speichern eben nochmal die Seriennummer gespeichert werden will.

![IMG_2811](https://github.com/user-attachments/assets/599fbe90-1ad6-4752-84b9-07721853621b)

**Comment by haraldhotzbehofsits** [comment]
Ich habe etwas overpanneling gemacht und wollte die Leistung des "Panels" ändern, und habe auch diesen Effekt beobachtet.

**Comment by brekemeier** [comment]
Den Inverter löschen und neu einrichten! Schnellste Lösung!

**Comment by Gubi2023** [comment]
oder die .127 flashen, mit der gehts!

**Comment by knickohr** [comment]
Man kann natürlich auch das Settings-JSON editieren und neu importieren 🫣

Aber bitte, nur für die die auch genau wissen was sie da tun 😇

**Comment by Loetnase** [comment]
Eventuell könnte es auch etwas bringen die nächste Version abzuwarten 😇

**Comment by lumapu** [comment]
> Eventuell könnte es auch etwas bringen die nächste Version abzuwarten 😇

ja es geht endlich wieder weiter 😎 (hatte jetzt gute drei Wochen pausiert)

**Comment by knickohr** [comment]
Wir haben es trotzdem überlebt 😁🤪

**Comment by Loetnase** [comment]
Funktioniert wieder
Danke
