### ISSUE TITLE
[Enhancement] MQTT JSON Timestamp

### ISSUE THREAD

**Issue by MichiM2** [lumapu/ahoy#1707]
### Platform

ESP32

### Assembly

I did the assebly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.127

### Github Hash

8cdf364

### Build & Flash Method

ESP Tools (flash)

### Setup

.

### Error description

1.) For saving and reporting reasons it would be useful, to include a timestamp in every MQTT JSON-packages:
like i.e. Tasmota does:    {"Time":"2024-07-21T15:24:01","U_AC": ...

**Comment by knickohr** [comment]
Hier sind die timestamps :

![IMG_2817](https://github.com/user-attachments/assets/90ff24ed-edac-4ff7-9959-06388ac49d75)

**Comment by MichiM2** [comment]
Ja, schon. Aber die sind nicht *im* JSON. Ich archiviere .../ch0 bis .../chx für spätere Auswertungen. Da wäre es m.E. sinnvoll, wenn der Messzeitpunkt bei den zugehörigen Daten stehen würde und nicht in einem anderen topic.

**Comment by geronet1** [comment]
Die ../chx Topics sind nicht retained. Somit ist der Messzeitpunkt der Zeitpunkt, wann du das Topic empfängst.

**Comment by MichiM2** [comment]
Jein.
Ganz spitzfindig: das eine ist der Messzeitpunkt, das andere der Empfangszeitpunkt.
Meist stimmen die -zumindest in einem lokalen Netzwerk- natürlich überein. Das stimmt aber nicht mehr, wenn dazwischen ge-queued wird. Beispielsweise mit einem QOS=2 .
Meiner Erachtens gehört der Messzeitpunkt mit zu den Messdaten.

**Comment by lumapu** [comment]
das ist was für unsere Liste #1199 (Wishlist)

**Comment by lumapu** [comment]
habe den Timestamp eingebaut, finde es eine sinnvolle (einfache) Änderung.

So sieht das dann z.B. für CH1 aus:

```json
{
    "U_DC": 41.8,
    "I_DC": 8.49,
    "P_DC": 354.9,
    "YieldDay": 0,
    "YieldTotal": 123.456,
    "Irradiation": 88.725,
    "MaxPower": 354.9,
    "ts": 1722812839
}
```
