### ISSUE TITLE
Frage zu API LimitSet mit CURL

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#1708]
Hallo zusammen,
da ich in den letzten Tagen mehrfach das Problem hatte, dass mein Programm über CURL das Limit setzt, der WR das über Ahoy nicht umstellt. Dadurch regelt mein Programm ab diesem Zeitpunkt nicht richtig nach.

Laut "der" Suchmaschine, bekommt man bei einem CURL Aufruf über die Shell aus einem VB-Programm raus leider keine Rückmeldung, außer die ID des gestarteten Programmes.

Kenn jemand ein Work-Around?

**Comment by dtuuser** [comment]
Habe eventuell eine Lösung gefunden.   
Über  /api/inverter/id/0   den Wert ""power_limit_read": 100," auslesen und mit in die Verarbeitung aufnehmen.
So quasi, bevor das nächste Limit gesetzt wird, da drüber auslesen und vergleichen, ob es gesetzt wurde.

**Comment by stefan123t** [comment]
Ja richtig, das ActivePowerLimit braucht eijige Zeit bis es vom WR angenommen und bestätigt wurde. Sendet man bereits ein Neues Limit bevor der WR das Limit selbst bestätigt, dann kann er für längere Zeit nicht mehr antworten.
Das ist ein bekanntes Problem.

**Comment by dtuuser** [comment]
So, habe gestern Abend was herumprogrammiert. Lese jetzt das Limit aus dem WR aus. Da ich das Limit in Watt setze, muss ich umrechnen. Leider gibt es da immer etwas Unterschied zum eingestellten Wert.  150W als Limit geschickt. Als gesetztes Limit bekomme ich 25,32% zurück. Das wird dann umgerechnet 151,92W. 
Mal sehen wir sich das Programm die Tage verhält.

**Comment by stefan123t** [comment]
@dtuuser schau Dir mal die Dokumentation zum [SystemConfigParam](https://github.com/lumapu/ahoy/wiki/Protocol#systemconfigpara--0x05) Command an, das erhält vom Inverter nur eine relativen % Wert zurück und ist entsprechend Timing sensitiv!
