### ISSUE TITLE
Interrupt Pin working --> false

### ISSUE THREAD

**Issue by Schilli1-1984** [lumapu/ahoy#1710]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.83

### Github Hash

5ebfe5a

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

no MqTT, Inverter 15s

### Debug Serial Log output

```shell
13:42:05.402 -----
13:42:05.403 I: com loop duration: 403ms
13:42:05.403 -----
```

### Error description

Seit heute morgen werden keine Werte mehr angezeigt und es gab keine Verbindung mehr zum Wechselrichter (HM1500). Daraufhin habe ich die Software von 0.6.9 auf 0.8.83 upgedated. 
Schlussendlich habe ich festgestellt, dass der Interrupt Pin working auf "false" steht. Settings sind CE --> D4 und IRQ --> D3. Gibt es eine Möglichkeit, den IRQ mit einem anderen Pin zu "überbrücken", für den Fall dass hier ein HW-Fehler vorliegt? Der ESP8266 ist jetzt ca. 1,5Jahre alt und hat bis heute mehr oder weniger stabil funktioniert. 
![2024-07-24 15_48_16-Clipboard](https://github.com/user-attachments/assets/c6abf5aa-bd88-40a8-8017-bd9408d8bb50)
Vielen Dank für eure Hilfe!

**Comment by knickohr** [comment]
Dann prüfe mal die Einstellungen in den Setting

**Comment by mroenne2022** [comment]
@Schilli1-1984   Ich hab bei meinen ab 0.8.83 D3 und D4 getauscht , also wie folgt : CE -> D3 und IRQ ->D4 , dann sollte es laufen.

**Comment by Schilli1-1984** [comment]
hab ich leider auch schon alles versucht, ohne jeden Erfolg. Auch gerade den Tausch der Pins (physisch wie und in den Settings), es bleibt bei einem nicht arbeitenden "interrupt Pin" und damit der fehlenden Kommunikation mit dem WR :-(

**Comment by mroenne2022** [comment]
Hm...bei mir ging es problemlos, merkwürdig. ggf nochmal alles akribisch kontrollieren oder einfach nochmal zurück auf die alte Version und zurück tauschen und sehen ob die DTU an sich ok ist.

**Comment by Schilli1-1984** [comment]
Ich befürchte, dass sich aus welchen Gründen auch immer entweder am Kabel oder an einer der beiden Platinen ein Schaden eingeschlichen hat. Ich habe heute ca. 4h über diverseste Foren Fehlerlösungen gesucht, auf die 7er Version gewechselt, zurück auf die 0.6.9, jetzt wieder 0.8.83, alles ohne Erfolg. 
Ich bin zugegebenermaßen kein IT-Crack, wenn die Anweisungen zu technisch oder gar in Richtung Programmierung o.ä. gehen bin ich raus, aber alles "verständliche" ;) habe ich versucht. 
Ich probiere es jetzt mal noch mit einem Rücksetzen auf Werkseinstellung, vielleicht hat das ja irgendeinen Erfolg.

**Comment by mroenne2022** [comment]
Wenn der Rückfall auf 0.6.9 und der Rücktausch von D3/D4 kein Erfolg hatte, dann scheint eine Verbindung schadhaft zu sein. Ich glaube nicht das die Platine defekt ist.

**Comment by Schilli1-1984** [comment]
Nein, leider nicht. Interrupt Pin working --> false. 
Ich habe mir mal neue Kabel bestellt, sollen morgen kommen. Das wäre die einfachste und billigste Lösung.
![AhoyDTU](https://github.com/user-attachments/assets/899d37a1-2972-45d2-88f2-e248d2ea329d)
![Anschlusseinstellungen](https://github.com/user-attachments/assets/b026e90a-6de0-42f4-98cc-c77f27ea3ccf)
![Web Konsole](https://github.com/user-attachments/assets/277e817c-8041-44b0-a79b-d318694b6dc6)
Vielleicht wache ich ja morgen auf und alles läuft plötzlich wieder...und mir fehlt nur ein Tag in meiner Berichterstattungs-Excel ;).

**Comment by Gubi2023** [comment]
ich hatte mal auch so nen Fehler, da hatte das NRF-Modul den Geist aufgegeben. Die LED auf dem ESP hatte dann Dauerlicht.

**Comment by stefan123t** [comment]
Wenn Du Dir “neue Kabel” bestellst dann meinst Du bestimmt solche Dupont Steckverbinder. Die sind idR notorisch für schlechte Kontakte, da die zwar professionell gecrimpt sind aber die Adern einfach sehr dünn sind, manchmal nur eine oder wenige Adern als Litze.
Besser ist es den Aufbau auf einer Platine gelötet zu verwirklichen oder gleich das OpenDTU Fusion Board zu verwenden, das ist professionell verarbeitet und läuft einfach.

**Comment by Schilli1-1984** [comment]
> Wenn Du Dir “neue Kabel” bestellst dann meinst Du bestimmt solche Dupont Steckverbinder. Die sind idR notorisch für schlechte Kontakte, da die zwar professionell gecrimpt sind aber die Adern einfach sehr dünn sind, manchmal nur eine oder wenige Adern als Litze. 

genau die meine ich, sorry für die unprofessionelle Ausdrucksweise :-). 
Das mit dem "Aufwachen und alles läuft" hat leider nicht geklappt. Jetzt kommen heute hoffentlich nicht zu spät die neuen Steckverbinder und das neue NRF-Modul, und dann Daumen drücken dass es dann läuft.
Andernfalls ist das OpenDTU Fusion Board wahrscheinlich auch eine Alternative. Ich will doch nur meinen Strom sehen...Plug&play ohne weiteres rumgefummel, so sollte das laufen...schön wärs ;)

**Comment by mroenne2022** [comment]
Also ich kann sagen das die Steckverbinder nicht so schlecht sind, ich hab 2 DTUs gelötet und ein paar weitere alle mit Steckverbindern hergestellt, AhoyDTU sowie OpenDTU. Bisher noch NIE ein Problem mit den Verbindungen gehabt.
Bei meinem Bruder und einem Freund laufen 2 davon auch problemlos. Vielleicht gibt es da auch Unterschiede in der Qualität.

**Comment by dtuuser** [comment]
Bei mir war es mal das Netzteil. Nach dem Tausch ging es wieder.

**Comment by Schilli1-1984** [comment]
Stecker und NRF-Modul getauscht, mit 0.8.83 weiterhin keine Verbindung und die loop duration 403ms, downgrade auf 0.6.9 und jetzt steht die Verbindung zum WR wieder. Schade dass die 0.8.83 nicht lief, die neuen Features haben mich neugierig gemacht! Danke schon mal für die Tipps und den Zuspruch.
Und jetzt, wo es wieder läuft, trau ich mich nicht nochmal die 0.8.83 aufzuspielen und einfach mal länger zu warten :D

**Comment by kiu77** [comment]
Hat es da nicht eine Änderung der Pin-Belegung gegeben zwischen diesen beiden Versionen?

**Comment by Schilli1-1984** [comment]
meines Wissens nach nur von 6 auf 7 (Tausch D3 / D4), und dann beim Wechsel von 7 auf 8 wurde das wieder rückgängig gemacht. Ergo müsste beim Wechsel von 6 auf 8 die gleiche PIN-Belegung sein. Es sei denn, da gabs noch was anderes.

**Comment by kiu77** [comment]
An das Rückgängigmachung kann ich mich nicht erinnern. Ich kann es leider nicht vergleichen, da ich kein ESP286 Board mehr habe, sondern nur noch ESP32.

**Comment by mroenne2022** [comment]
Nein, zurück gedreht wurde der Tausch nicht. D3/D4 müssen m.E. getauscht werden, das hab ich einmal durchgeführt und nicht wieder zurück. Und zwar Kabeltausch UND im Setting. Damit sollte es laufen, bin ich eigentlich sicher.

**Comment by mroenne2022** [comment]
@kiu77 Wurde auch nie rückgängig gemacht

**Comment by Schilli1-1984** [comment]
Ok dann habe ich das irgendwo falsch rausgelesen / verstanden...also weißen und gelben Steckverbinder am esp tauschen und in den Einstellungen ändern. 
Beides erledigt, aber weiterhin keine Verbindung zum Wechselrichter. Log file sagt immer noch loop duration 403ms
![Anschlusseinstellungen_neu](https://github.com/user-attachments/assets/91ee0dc5-6d3b-4a9a-807a-2e6564ab602c)

![Wechselrichter](https://github.com/user-attachments/assets/ce00860e-a5b6-4173-b236-3bca6ca2d473)
Mit der alten Version war der Wechselrichter anfangs gelb (Verfügbar aber noch nichts empfangen), mit der neuen bleibt er beharrlich nicht erreichbar.
Kann ich noch irgendwas teilen, was eventuell Einblick in irgendeine fehlerhafte Einstellung gibt?

**Comment by mroenne2022** [comment]
Also ob es weiß und gelb ist weiß ich nicht,  es müssen CE und IRQ  am NRF Modul sein. Und die Belegung muss man sich 100% ig angucken um die Ports zu ermitteln. Bin sicher dann läuft es

**Comment by Schilli1-1984** [comment]
![Wemos_OpenDTU (1)](https://github.com/user-attachments/assets/44cddd37-cfa6-4648-8e20-ce7ea473b0c2)
Es entspricht exakt der Belegung, bis auf den Tausch von D3 und D4 (also CE hier leicht grau dargestellt) geht jetzt auf D3 und IRQ (gelb) auf D4. Der Rest ist unverändert und hat so ja auch in der 0.6.9 funktioniert.  
Notfalls gehe ich wieder auf die 0.6.9 zurück und hoffe, das wundersamerweise mit einer neuen Version in der Zukunft auch meine DTU dann zusammenarbeiten möchte ;)

**Comment by Schilli1-1984** [comment]
Oha, it's magic. Man muss nur lange genug warten und schimpfen, und plötzlich hat sich auch die 0.8.83 verbunden und im Moment geht alles.
Vielen Dank für euren support und Geduld!

**Comment by mroenne2022** [comment]
Glückwunsch! Aber "schimpfen" nützt mit Sicherheit nichts. Offensichtlich ist es jetzt richtig verbunden und vorher war ein Fehler drin. Das kann natürlich passieren ! Dieses Bildchen ist immer gut !
![NRF24L01-Pinout-NRF24L01-PA-LNA](https://github.com/user-attachments/assets/d123ed7a-d6e2-44c4-ad71-723b05e746b1)

**Comment by Gubi2023** [comment]
Also wenns jetzt geht, kannst du ja mal dir dev.Version 0.8.127 aufspielen.Hat viele neue Features https://fw.ahoydtu.de/fw/

**Comment by kiu77** [comment]
Das wird sie ohne Pintausch niemals tunVon meinem iPhone gesendetAm 25.07.2024 um 13:54 schrieb Schilli1-1984 ***@***.***>:﻿
Closed #1710 as completed.
