### ISSUE TITLE
nach Update kein 2.Login möglich [Bug]

### ISSUE THREAD

**Issue by jotroj** [lumapu/ahoy#1713]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [x] #1716

### Version

0.8.130

### Github Hash

GIT SHA: 24ceb3e :: 0.8.130

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

nur Update von 0.8.129 auf 0.8.130

### Error description

Nur nach Power OFF/ON startet Normalbetrieb wieder für live und  Login

**Comment by Gubi2023** [comment]
so, bei mir nun auch: Update .130 auf .131: DTU nicht mehr erreichbar! Anschluss an USB: Reboot in Dauerschleife!

**Comment by Gubi2023** [comment]
mit .132 gehts

**Comment by jotroj** [comment]
Update von 0.8.130 auf  0.8.141 : Login funktioniert

**Comment by jotroj** [comment]
Update von 0.8.130 auf  0.8.141 : Login funktioniert
