### ISSUE TITLE
bei ePaper, Ahoy Logo fehlt beim Start bei 0.8.131

### ISSUE THREAD

**Issue by Loetnase** [lumapu/ahoy#1714]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.131

### Github Hash

55e45c7

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

bei der 0.8.131 mit **ePaper** fehlt beim Start bei das Ahoy Logo :disappointed_relieved: 
und mit abgeschaltetem ePaper kommt ein Dauerreboot. Danke Gubi203

### Error description

bei der 0.8.131 mit **ePape**r fehlt beim Start bei das Ahoy Logo :disappointed_relieved: 
und mit abgeschaltetem ePaper kommt ein Dauerreboot. Danke Gubi203

**Comment by Gubi2023** [comment]
kann es sein, dass die .131 nur funktioniert, wenn E-Paper angeschlossen ist?? Hab kein E-Paper, nach Update Dauerreboot!

**Comment by Loetnase** [comment]
altes ESP8266 mit Nokia Display funzt auch mit 0.8.131.

**Comment by Gubi2023** [comment]
wie gesagt, ich habe ESP32, kein Display, auch nicht aktiviert und mit .131 Dauerreboot!

**Comment by Loetnase** [comment]
@Gubi2023 Probiere es mal mit den Einstellungenfürs ePaper, natürlich ohne ePaper dran
Vielleicht funzt es dann.
![grafik](https://github.com/user-attachments/assets/51291541-0f48-4263-a15d-6225bcd68833)

**Comment by Gubi2023** [comment]
nö, ich warte auf die nächste Version, das wäre eh nur ein workaround, von dem ich nicht weiss, ob er funktioniert.

**Comment by Gubi2023** [comment]
danke, update mit .132 funzt! =))

**Comment by Loetnase** [comment]
Habe auch gerade die 0.8.132 eingespielt, 
das Logo kommt auch beim Start :thumbsup: 
Würde auch sagen funzt :innocent: 

@lumapu Dankeschön

**Comment by Loetnase** [comment]
Das funzt 😇
und ich mache hiermit das Issue zu.
@lumapu Dankeschön
