### ISSUE TITLE
[Bug] v0.8.134 Deutsche Version teilweise nicht übersetzt (System)

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1717]
### Platform

ESP8266

### Assembly

the DTU was already assembled

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.134

### Github Hash

cd16b37

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Update von v127 auf v134

### Error description

Deutsche Version teilweise nicht übersetzt auf  der überarbeiteten System Unterseite.
(ESP8266, ESP32 habe ich noch nicht angeschaut)

**Comment by lumapu** [comment]
😂 ich hab schon drauf gewartet. Wird früher oder später behoben

**Comment by Gubi2023** [comment]
nix für ungut, wollt es nur mitteilen. Ansonsten ist die Erweiterung prima und sinnvoll.

**Comment by Gubi2023** [comment]
na, das ging ja fix :))   (wo find ich eigentlich die Smileys in Github??)  aber ein paar Kleinigkeiten hast du übersehen:  (ESP8266)
![Screenshot 2024-08-11 175636](https://github.com/user-attachments/assets/2c04d585-4cc7-425b-81e9-d09181c6c1b2)
![Screenshot 2024-08-11 175535](https://github.com/user-attachments/assets/a07e9d2f-fcc5-44a8-9e99-6529a927d276)
![Screenshot 2024-08-11 175459](https://github.com/user-attachments/assets/37fc7442-8bf0-4569-ae05-8587d2a670b6)

**Comment by lumapu** [comment]
bei Windows geht das mit WIN Taste und Punkt

**Comment by Gubi2023** [comment]
Hallo Lukas, zu früh zugemacht, die letzten 3 Fehler sind noch drin...

**Comment by lumapu** [comment]
es ist immer zu früh 😅, irgendwann muss man diesen Schritt gehen (nach einem halben Jahr mal wieder)

**Comment by Gubi2023** [comment]
Ok
