### ISSUE TITLE
Reboot after backup

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1721]
Hardware Opendtufusion; Antenna: external antenna (SMA); Version: ahoy_v0.8.133

Hi, it wants to reboot after backup settings:'' reboot AhoyDTU to apply all your configuration changes''.
No changes where made as far as I understand!
Kind regards

**Comment by Gubi2023** [comment]
maybe it is this issue?  https://github.com/lumapu/ahoy/issues/1454

**Comment by Peertje-62** [comment]
Hi, I think you are right, same issue;
But is closed
Should I close it (this one) to ?
regards

**Comment by Gubi2023** [comment]
i closed it, because its a feature and no bug...

**Comment by Peertje-62** [comment]
Thx,
and so will I,
Have a nice day
