### ISSUE TITLE
epaper reagiert ab Vers 0.8.134 nicht mehr

### ISSUE THREAD

**Issue by Edibo63** [lumapu/ahoy#1722]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.1.134

### Github Hash

c64f028

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Update von 0.8.132 auf 0.8.134

### Error description

Ab Vers. 0.1.134 reagiert das epaper Dislplay nicht mehr.
Es zeigt die Werte vor dem Update und ist wie eingefroren. Keine Reaktion of reboot oder Neustart.
Zurück auf 0.8.132 und alles funktioniert wieder.

**Comment by Falerion-git** [comment]
Ähnliche Erfahrung habe ich auch gemacht (openfusion board mit epaper). 
Ich konnte die DTU noch über die Weboberfläche erreichen und dann das epaper manuell wieder einstellen. War aber sehr instabil und ich brauchte mehrere Anläufe, um überhaupt das WLAN zu konfigurieren. 
Bin dann auch zurück auf v0.8.132, lief dann direkt.

**Comment by knickohr** [comment]
Das Problem kann ich ab der Version 134 mit den Plattformen ESP32 und ESP32-S3 bestätigen. Andere habe ich nicht getestet.

**Comment by knickohr** [comment]
Bestätigt, mit 138 geht das ePaper wieder 👍

**Comment by Edibo63** [comment]
mit 0.8.138 gehts wieder.
Vielen Dank.
