### ISSUE TITLE
History menu disappeared

### ISSUE THREAD

**Issue by jschwed** [lumapu/ahoy#1728]
### Platform

ESP8266

### Assembly

I did the assembly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.140

### Github Hash

ahoy_v0.8.140

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Setup not changed during update from 0.8.83 to 0.8.140

### Error description

Hi,
I was running 0.8.83 and updated to 0.8.140.
After the update "History" in the menu is gone.  
![grafik](https://github.com/user-attachments/assets/ccc37ca6-8a87-47ef-b269-b60855fc6251)

Before it was listed right after "Live".
Under Settings/Protection I can still see the option to protect the History page. 
Tried to protect the page, reboot --> no change. Changed back to unprotected, reboot --> no change.

Do I need to change the config somewhere with this release?

thx

**Comment by Dirk-Ahoy** [comment]
https://fw.ahoydtu.de/fw/download/release%2Fahoy_v0.8.140%2FESP8266%2F240816_ahoy_0.8.140_f1f4481_esp8266-all.bin

Please install this Version  :)

**Comment by jschwed** [comment]
Hi @Dirk-Ahoy , thanks a lot for the quick response! With the "all.bin" it works. 
I used the 240816_ahoy_0.8.140_f1f4481_esp8266.bin file in the first place.

@lumapu: the new graphs look great - the new "Total Power Today" is very useful!
