### ISSUE TITLE
Frage zu unterschiedlichen FW Varianten (*.bin, *all.bin und *minimal.bin)

### ISSUE THREAD

**Issue by CK1-CK** [lumapu/ahoy#1734]
Hallo alle zusammen

ich habe eine grundsätzliche Frage zu den unterschiedlichen FW Varianten.

Englische
- esp8266.bin
- esp8266-all.bin
- esp8266-minimal.bin 
- esp8266-prometheus.bin

Deutsche
- esp8266-de.bin
- esp8266-all-de.bin
- esp8266-prometheus-de.bin

Wie unterscheiden sich die Unterschiedlichen FW Varianten untereinander?

Speziell würden mich die **Unterschiede** zwischen der *.bin, *all.bin und *minimal.bin interessieren.

Leider habe ich dazu keine Doku gefunden.

Viele Dank schon im Voraus.
Grüße
CK1

**Comment by knickohr** [comment]
Aus dem Changelog ist zu entnehmen :

https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md#0892---2024-03-10

**Comment by Gubi2023** [comment]
und wo ist der Unterschied zwischen .bin und minimal.bin? gibts da echt keine Doku zu?

**Comment by Gubi2023** [comment]
siehe auch #1735

**Comment by CK1-CK** [comment]
Vielen Dank für die Links.

Ich habe es versucht nochmal übersichtlich dazustellen.


|       FW Tag/Feature       | MqTT  | Display | History/Verlauf | Prometheus |
|--------------------|-------|---------|-----------------|------------|
| esp8266            | X     | -       | -               | -          |
| esp8266-all        | X     | X       | X               | -          |
| esp8266-minimal    | -     | -       | -               | -          |
| esp8266-prometheus | ?     | ?       | ?               | X          |

**Comment by knickohr** [comment]
Diese Frage kann wahrscheinlich nur @lumapu beantworten.

**Comment by lumapu** [comment]
Danke für die Tabelle, ich habe sie vervollständigt:


 |       FW Tag/Feature       | MqTT  | Display | History/Verlauf | Prometheus |
 |--------------------|-------|---------|-----------------|------------|
 | esp8266            | X     | -       | -               | -          |
 | esp8266-all        | X     | X       | X               | -          |
 | esp8266-minimal    | -     | -       | -               | -          |
 | esp8266-prometheus | X     | X       | X.              | X          |

Diese Datei ist die beste Beschreibung der eingebauten Features:

https://github.com/lumapu/ahoy/blob/main/src/platformio.ini

**Comment by CK1-CK** [comment]
Ich denke es ist alles gesagt.

Hier ist die Lösung:
https://github.com/lumapu/ahoy/issues/1734#issuecomment-2305244571


Eventuell kann man diese Informationen in die Doku mit aufnehmen.

Grüße
CK1
