### ISSUE TITLE
bug: update von .140 auf .142 schlägt fehl

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1743]
### Platform

ESP32

### Assembly

the DTU was already assembled

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.142

### Github Hash

565a69e

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

update auf .142

### Error description

update von .140 auf .142 funktioniert nicht. DTU bekommt keine Verbindung zum NTP-Server und startet sich alle 15 sec. neu.
Neustartgrund panic,  coredump siehe discord

**Comment by Gubi2023** [comment]
![2024-08-28 23_52_12-Greenshot](https://github.com/user-attachments/assets/456195a7-8d73-41a6-8983-a77d27eb145e)

**Comment by Gubi2023** [comment]
Dauerreboot! DTU konnte nur über USB webflasher mit erase wieder zum laufen gebracht werden

**Comment by reserve85** [comment]
kann ich bestätigen, .142 ist bei mir nicht funktionsfähig. Etwa alle 10s Neustart...

**Comment by lumapu** [comment]
sorry, das war unbeabsichtigt. Danke für eure reports und Geduld mit mir 😇

**Comment by Gubi2023** [comment]
alles gut, nur wer nichts macht, macht keine Fehler  😉

**Comment by lumapu** [comment]
> alles gut, nur wer nichts macht, macht keine Fehler 😉

doch und zwar einen, einen ganz großen 😎

**Comment by Gubi2023** [comment]
0.8.143: funzt! danke für den schnellen Bugfix 😊👍

**Comment by DanielR92** [comment]
close?

**Comment by Gubi2023** [comment]
ich hab ihn mal offen gelassen, falls andere auch über diesen bug stolpern...l

**Comment by lumapu** [comment]
ich denke nicht, dass allzuviele die 142 installiert haben, daher mache ich zu.
