### ISSUE TITLE
Reboot at Noon

### ISSUE THREAD

**Issue by Peertje-62** [lumapu/ahoy#1754]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.145

### Github Hash

2a99097

### Build & Flash Method

ESP Tools (flash)

### Setup

Hm 600 & Hm 300
Openfusion DTU
MQTT

Hm 400
Openfusion DTU
MQTT

### Debug Serial Log output

```shell
-
```

### Error description

Unwanted reboot at 12:00, on my system and also on my neighbor's
Kind regards

**Comment by knickohr** [comment]
Jepp, und von einem weiteren User und von mir bestätigt. Liegt vermutlich an einem Bug in „Reboot Ahoy at midnight“.

**Comment by hrolofs** [comment]
same for me

**Comment by Ollipop030** [comment]
Wie läuft denn die .145 generell bei euch? Auf meinem ESP32 ist das Webinterface sehr träge, auch nach einem Reboot. Die Nulleinspeisung über REST API hat auch viele Aussetzer, MQTT ist aus.
Die .144 läuft deutlich besser, zumindest bei mir.

**Comment by Gubi2023** [comment]
bei mir ist die Aktualisierung an I-Phone sehr träge...

**Comment by lumapu** [comment]
habe gerade was gefunden: manche Tasks sind mehrfach registriert - bei euch u.U. noch mehr, je nachdem wie oft sich Ahoy neu mit dem Wifi verbunden hat, hier ein Auszug meiner DTU, seit 1 Tag und 20h am laufen, per Ethernet verbunden:

```
0.8.145 - 2a99097
---------------
21:29:29.745 I: webSc, tmt: 1, rel: 1
21:29:29.746 I: prot, tmt: 1, rel: 1
21:29:29.746 I: net, tmt: 1, rel: 1
21:29:29.746 I: ntp, tmt: 14199, rel: 43200
21:29:29.747 I: uart, tmt: 4, rel: 5
21:29:29.747 I: hist, tmt: 1, rel: 1
21:29:29.758 I: tSend, tmt: 2, rel: 5
21:29:29.758 I: mqttS, tmt: 1, rel: 1
21:29:29.758 I: mqttM, tmt: 42, rel: 60
21:29:29.759 I: mid2, tmt: 1727128800, rel: 0
21:29:29.759 I: ivCom, tmt: 1727153064, rel: 0
21:29:29.770 I: Sunri, tmt: 1727199006, rel: 0
21:29:29.770 I: mid2, tmt: 1727128800, rel: 0
21:29:29.770 I: midNi, tmt: 1727128800, rel: 0
21:29:29.771 I: mid2, tmt: 1727128800, rel: 0
21:29:29.781 I: mqSr, tmt: 1727153065, rel: 0

```

Den Output bekommt man, wenn man in einem Tab das Webserial aufmacht, in einem zweiten die Adresse `[IP_DER_DTU]/debug` aufruft. Im Webserial taucht dann ein ähnlicher Output auf.

**Comment by Peertje-62** [comment]
THX
