### ISSUE TITLE
144, 145 und 146 Problem beim Login

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#1755]
## Hardware
  * [ ] ESP32
 ### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 

Problem:
Bei diesen Firmware-Versionen kommt nach jedem Klick auf Login auch schön das Login-Fenster,
doch hat man das PW da eingegeben und auf Login geklickt, wird das Eingabefeld einfach gelöscht.
Man ist dann zwar eingeloggt, wird aber nicht mehr auch die Übersichtsseite zurückgeroutet,
was irgendwie nicht schön ist. Das abgebildete Fenster inkl. Link mit /login im Browser bleibt.
![Bildschirmfoto 2024-09-25 um 19 58 49](https://github.com/user-attachments/assets/3508d9fc-a266-49e6-999f-67425e5ece40)

**Comment by knickohr** [comment]
144, 145 und 146 !

**Comment by RealNBB** [comment]
ja ist "eigentlich" mit der 146 gefixt worden:

fix redirect after login

hab das Problem aber auch weiterhin mit der 146.

**Comment by lumapu** [comment]
leider habe ich es selbst nicht getestet, sondern meinte meine Änderung greift zu 100%. 
Ich sehe das Problem auch und werde einen weiteren Versuch starten es zu beheben.

**Comment by kiu77** [comment]
> 144, 145 und 146 !

Ja, peinlich, danke. Habs korrigiert...

**Comment by RealNBB** [comment]
Hi,

mit der 0.8.149 funktioniert alles wieder wie es soll, zumindest bei mir.

**Comment by kiu77** [comment]
Kann ich bestätigen: Bei mir auch!
