### ISSUE TITLE
NTP timeserver unreachable

### ISSUE THREAD

**Issue by RealNBB** [lumapu/ahoy#1756]
### Platform

ESP32

### Assembly

I did the assembly by myself

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.146

### Github Hash

83b386d

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Nothing changed

### Error description

Hi,

seit der 1.46 habe ich Probleme mit der Zeitsynchronisation. 
In diesem Fall gab es einen automatischen Restart um Mitternacht, dann das Problem mit der Synchronisation.

![image001](https://github.com/user-attachments/assets/09e06fce-4e5f-4b60-9915-5480a1effae8)

Grüße

**Comment by lumapu** [comment]
Hat Ahoy zu dem Zeitpunkt Netzwerkzugriff? Besteht Internetzugriff? Ist automatischer Neustart mitternachts aktiviert?

**Comment by RealNBB** [comment]
Hi, 3x ja! 

/Edit/

Okay....Kommando zurück. Am Wochenende hat ein Bagger bei uns im Ort das Stromkabel gekillt und dabei gleich noch die DSL-Leitung mit heraus gezogen. 
Scheint so, dass die Leitung zwar mittlerweile wieder läuft, aber offensichtlich noch nicht so ganz rund. Heißt, dass Problem liegt bei mir und nicht bei Ahoy.  

Ich schließe das hier daher mal.
