### ISSUE TITLE
Update to 0.8.151 reports succefull but Version shows 0.8.145

### ISSUE THREAD

**Issue by Jawada74** [lumapu/ahoy#1761]
### Platform

ESP32

### Assembly

the DTU was already assembled

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.145

### Github Hash

2a99097

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Inverter intervalls to 12 Sec.

### Error description

After updating from 0.8.145 to the 0.8.151 the DTU reports succefull update but shows 0.8.145.

**Comment by RealNBB** [comment]
Then try again! ;)

If it still doesn't work, make a backup of the config and reinstall it using Webflasher ("erase"). Then import the config and you're done.

**Comment by Gubi2023** [comment]
sometimes is usefull to refresh, then the actual version is visible

**Comment by Jawada74** [comment]
Refresh had no effect.

![image](https://github.com/user-attachments/assets/95ee84a2-32e4-461b-86fa-4082f43e2569)

**Comment by Gubi2023** [comment]
du hast nicht upgedatet! sonst wäre die uptime auf 0 Tage.

**Comment by Dirk-Ahoy** [comment]
einfach mal einen reboot machen dann sollte die neue version laufen

**Comment by knickohr** [comment]
Im AP booten und dann den Update machen. Hat bis jetzt immer funktioniert 😉

**Comment by Jawada74** [comment]
Seh ich auch so aber ich kann nur sagen das Update Läuft durch und ich bekomme die meldung Update successfull.  und das DTU bootet neu. Danach ist aber alles beim alten.
Ich schaue mal wie ich das AP booten hin bekomme.
Danke

**Comment by knickohr** [comment]
Wenn der Update mit Success durchläuft dann einfach manuell booten, also ausschalten und wieder Strom einschalten. Sollte genügen. Nicht auf den automatischen Reboot warten, aber unbedingt auf das Success warten !

**Comment by Jawada74** [comment]
Danke Knickohr genau das war es !!!
Einfach Stromlos gemacht und dann wieder angesteckt und schon war die 0.8.151 im display und im webGui.
Hätte ich auch alleine drauf kommen können.
