### ISSUE TITLE
Inverter disabled

### ISSUE THREAD

**Issue by themille** [lumapu/ahoy#1786]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Warum ist der Wechselrichter deaktiviert, aktivieren kann ich ihn nicht auch wenn ich den Haken setze und speicher.
![Screenshot 2024-11-14 094931](https://github.com/user-attachments/assets/cbb30778-0f90-4a24-98b4-b52abd94461f)
![Screenshot 2024-11-14 094910](https://github.com/user-attachments/assets/77e1abe4-e5a1-44c2-86fa-72210cfecdd0)

**Comment by Gubi2023** [comment]
bitte mehr Infos: welche DTU, welche Version? ggf. Screenshot von "System" senden

**Comment by themille** [comment]
@Gubi2023, stimmt, vielen Dank für den Hinweis
![Screenshot 2024-11-14 103107](https://github.com/user-attachments/assets/f8bc3dac-8939-4624-b4ca-f42bbe5ffe88)
![Screenshot 2024-11-14 103049](https://github.com/user-attachments/assets/3ec611e7-ce56-4df8-b400-cd9b5c2946c0)
inweis

**Comment by Gubi2023** [comment]
Interrupt unnown:  vermutlich pinmapping falsch

**Comment by themille** [comment]
![image](https://github.com/user-attachments/assets/50f00417-f42e-4366-87ed-d79b546b801d)

**Comment by themille** [comment]
Ich habe den ESP 32 so mit dem CMT2300 verbunden:

![image](https://github.com/user-attachments/assets/a62e60fb-e975-41bd-bced-3a7168e16465)

**Comment by knickohr** [comment]
Also ich sehe hier schon mal mindestens 2 Probleme : 
- der Interrupt vom CMT arbeitet nicht
- warum wird der Flash nicht angezeigt ?

Zeig uns auch mal die Settings mit den LEDs 😉

![IMG_3177](https://github.com/user-attachments/assets/aef69ab0-dfd8-46bc-9258-0dd0a4ef5ff5)

**Comment by themille** [comment]
![image](https://github.com/user-attachments/assets/040216a1-0bad-437c-ba79-9a158569c867)

**Comment by knickohr** [comment]
Jetzt komm schon, etwas mehr Info.

Welche Hardware, wie verkabelt, gekauft oder selber zusammen gestrickt, welche Module …

Bilder vom Aufbau wären auch nicht schlecht.

Meine Glaskugel arbeitet heute noch nicht, es ist kalt 😅

**Comment by Gubi2023** [comment]
woher hast du deine Pinbelegung? bei mir sieht sie ganz anders aus...

**Comment by themille** [comment]
Man ich bin doch totaler Anfänger.
Ich habe ein ESP32WROOM32 und ein CMT2300A von blinkyparts gekauft.
Habe diese beiden so verkabelt:
![image](https://github.com/user-attachments/assets/6caf2549-5961-45bf-947d-2fd5f7d9d692)
Mehr habe ich nicht gemacht.
Pinmapping dann so eingestellt:
![image](https://github.com/user-attachments/assets/a9b8ec11-32d3-4d0a-acd6-0996bae7b112)
Ist die Pinbelegung von blinkyparts

**Comment by themille** [comment]
habe jetzt einmal folgendes versucht:
![image](https://github.com/user-attachments/assets/ec34c0db-192d-4805-a233-23100272fa06)
![image](https://github.com/user-attachments/assets/e460608e-43bf-402c-a950-ce14bd421384)
 mit dem Ergebnis:
![image](https://github.com/user-attachments/assets/c8e6c38d-26ec-490e-ab17-065357c107ad)


Aber dass sich die Wechselrichter nicht aktivieren lassen, kann das überhaupt an der Pinbelegung liegen?

**Comment by themille** [comment]
ok, das Problem dass der WEchselrichter nicht genommen wird, liegt defintiv nicht an der Pinmapping.
Ich habe zwei WR vom TYP HM600 eingegeben und sie werden deaktiviert. Nur der HMS800 wird direkt deaktiviert nach Eingabe seiner Serialnummer (die sind ja mit Buchstaben)

**Comment by knickohr** [comment]
Der HMS ist aber ohne ein W in der Bezeichnung ?

**Comment by themille** [comment]
doch mit...HMS800W-2T

**Comment by knickohr** [comment]
Ich hau Dich gleich !
Das ist ein WiFi-WR, die funktionieren weder mit Ahoy noch mit OpenDTU 😞

**Comment by Gubi2023** [comment]
@ doku:  
immer dasselbe. wird Zeit, dass in der  Doku von Ahoy darauf hingewiesen  wird, dass WRs mit integriertem W-Lan von Ahoy nicht unterstützt werden!!

**Comment by knickohr** [comment]
![IMG_3178](https://github.com/user-attachments/assets/3ccb1030-e331-4593-bb87-e31c3324c2a9)

**Comment by themille** [comment]
alter sorry, das habe ich nirgends gefunden, tut mir leid

**Comment by Gubi2023** [comment]
okay, danke, wo ist das her? (englisch kann nicht jeder 😉)

**Comment by knickohr** [comment]
Auf der Gihub Seite von Ahoy.

Und in der Doku ist es auch drin : 

![IMG_3179](https://github.com/user-attachments/assets/c170a47c-5bcd-429c-97d9-0b0e2c82f85f)

**Comment by knickohr** [comment]
@themille 
> alter sorry, das habe ich nirgends gefunden, tut mir leid

Alles fein, wird leider gerne überlesen 😇

**Comment by Gubi2023** [comment]
@knickohr : Vorschlag vllcht noch auf discord.com  #faq-doku  verlinken?  Ich hab da leider keinen Zugriff...

**Comment by rmayergfx** [comment]
Also ehrlich, das steht dick und Fett auf der Homepage:
https://ahoydtu.de/
> November 2023: HMS-xxxxW Serie
> Leider kann Ahoy die Wechselrichter der HMS-xxxxW Serie (noch) nicht auslesen. Diese Wechselrichter haben eine integrierte DTU und kein Funkmodul mehr wie die drei vorherigen Generationen.

Steht auch so in der Doku von OpenDTU
https://www.opendtu.solar/hardware/inverter_overview/

Schwach finde ich von Blinkyparts das sie in ihrem Shop nicht darauf hinweisen, zumal sie ja auch Fertigmodule verkaufen.
Ich würde ihnen das ganze Zeug einfach zurückschicken.

Die Arbeit noch mehr in FAQs oder sonst irgendwo die Hinweise hinzuschreiben könnt ihr Euch wirklich sparen. Ich sehe es hier immer wieder. Hat eine E-Mail mehr als 3 Zeilen wird es nicht bis zum Schluß gelesen, Handbuch? Wofür, hab ich ein Problem wird es in den entsprechenden Kanälen abgesetzt, da werden Romane geschrieben was nicht geht bevor einer mal RTFM. Egal was solls. Thema ist durch und kann geschlossen werden. Schade um die investierte Zeit und Geld.

**Comment by stefan123t** [comment]
> Meine Glaskugel arbeitet heute noch nicht, es ist kalt 😅

![image](https://github.com/user-attachments/assets/0470fe53-1269-408c-b954-b274505528f6)
