### ISSUE TITLE
Störung Nachtkommunikation mit HMS Invertern

### ISSUE THREAD

**Issue by tester277** [lumapu/ahoy#1787]
### Platform

ESP32

### Assembly

the DTU was already assembled

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.152

### Github Hash

-

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Habe ein Fusion Komplett Gerät mit ESP32S3, daran sind insgesamt 4 WR(ausschließlich HMS) angeschlossen.

### Error description

Beim Betrieb in der Nacht gibt es nach einigen Tagen Kommunikationsaussetzer. Im  webserial sind hohe com loop Zeiten >1000ms es werden teilweise keine Daten angezeigt und die Lossraten gehen hoch.
z.B.
TX count | 44230 |  
-- | -- | --
23419 | 52.95 %
0 | 0 %
20811 | 47.05 %
55461 |  
17663 |  
lost 445 of 554 | 80.32 %
lost 65448 of 119 | 54998.32 %
Tagsüber gibt es solche Probleme nicht.
Wenn so etwas passiert, lässt sich das auch nicht z. B. über ein Neustart beheben. Bei Tageslicht ist dann das Problem weg.
Einen Auslöser (außer Nachtbetrieb) habe ich nicht entdeckt. Was kann ich zur Untersuchung beitragen?

**Comment by knickohr** [comment]
Sind alle Inverter betroffen ?  Oder nur einzelne, was sind das für welche ?

**Comment by tester277** [comment]
Zwei HMS WR sind an zwei verschiedene Akkusysteme angeschlossen, diese haben Nachts phasenweise ein Problem. Ein WR davon hat sowohl PV Modul als auch Akku System Growatt angeschlossen Zwei weitere HMS WR haben nur PV Module und die Nachtkommunikation ist auch im Setup disabled. HM WR sind bei mir nicht in Betrieb es ist also durchaus möglich, das es ein spezifisches CMT Problem ist.

**Comment by knickohr** [comment]
Das weiß ich schon.

Sind die Inverter die Aussetzer haben mehrkanalige ?

**Comment by tester277** [comment]
Beteiligt sind ein HMS 500 da sind 2 parallel geschaltete 24V Akkus dran ( also ein Channel) und ein HMS 1800 Channel/Input 1: PV Modul; Channel/Input 2 und 3 Akkusystem Growatt Noah; Channel/Input 4 nicht belegt.

**Comment by knickohr** [comment]
Bei dem 500er wäre es vielleicht sinnvoll aus den 24V-Batterien ein 48V-System zu machen.

Beim 1800er (ich denke es ist ein 4T) mal den Input 4 mit der Batterie belegen, mansche haben nur auf einem Input die Versorgung der Elektronik.

**Comment by tester277** [comment]
Zu Antwort 1) 48V System ist sicherlich eine gute Lösung, ich habe aber nur ein 24V Ladegerät. Ich glaube nicht, dass das der Auslöser für oben beschriebenenes Problem ist.
Zu Antwort 2) Der HMS hat 4Mppt. Tagsüber kommt der Inverter mit der Versorgung über Input 1 ohne Loss Rate klar.  
![image](https://github.com/user-attachments/assets/ec00a2e5-771b-4dc3-b209-6242e218a0f2)
Im Bild zu sehen die Watt Werte der beiden WR nach Sonnenuntergang (heute bei mir 17.29). Kurz nach 19 Uhr wieder normale Kommunikation. Das geht in der Nacht so weiter. Nur zur Klarstellung es ist kein MQTT Thema, in der Live Ansicht von Ahoy gibt es, solange das Problem besteht auch keine Werte.

**Comment by knickohr** [comment]
Das ist korrekt, aber nur einer versorgt die Elektronik im WR. Frag mal Dahlienhaus, der hatte das gleiche Problem das sein HMS, ich glaube es war ein 1800-6T Nachts immer aus ging.

**Comment by tester277** [comment]
Vielen Dank @knickohr für Deine unermüdliche Unterstützung hier. Wahrscheinlich werden die Werte nur korrekt erfasst und übermittelt solange alle WR bei denen die Einstellung „Pause communication during night“ deaktiviert ist auch tatsächlich online sind. Sonst kommt es zu solchen Aussetzern wie oben beschrieben, weil immer versucht wird, WR die gerade offline sind mit abzufragen. Ähnliches Thema: #1785.

**Comment by tester277** [comment]
Wahrscheinlich werden die Werte nur korrekt erfasst und übermittelt solange alle WR bei denen die Einstellung „Pause communication during night“ deaktiviert ist auch tatsächlich online sind. Sonst kommt es zu solchen Aussetzern wie oben beschrieben, weil immer versucht wird, WR die gerade offline sind mit abzufragen. Ähnliches Thema: https://github.com/lumapu/ahoy/issues/1785.
