### ISSUE TITLE
Ahoy-DTU spannt Netzwerk mit 5 GHz auf!

### ISSUE THREAD

**Issue by Gubi2023** [lumapu/ahoy#1795]
### Platform

ESP32

### Assembly

I did the assembly by myself

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an image of my wiring

### Version

0.8.152

### Github Hash

????

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

0.8.152

### Error description

seit einiger Zeit habe ich das Phänomen, dass meine DTU (von AllianceApps) nicht mehr erreichbar ist. Nach Spannungswiederkehr spannt die DTU ihr Ahoy-DTU-Netzwerk auf und in der Fritzbox wird mir folgendes angezeigt:
![Screenshot 2024-12-18 172131](https://github.com/user-attachments/assets/f0966b5b-e12f-4397-b6ff-2b1e5117daec)
Eine Zuweisung zu meiner Fritzbox geht dann auch nicht.

**Comment by knickohr** [comment]
Das wäre geil !  Kannst Du mal die genaue Bezeichnung des ESPs, am Besten Foto davon machen. Ich weiß das neuere ESPs auch 5GHz können, kann gut sein das die letzte Charge des S3 es nun auch können 😎

**Comment by Gubi2023** [comment]
hallo @knickohr , ich glaub ich muss dich da enttäuschen: ich hab die DTU schon im März gekauft, dürfte eigentlich kein S3 sein.   
![signal-2024-12-19-095320](https://github.com/user-attachments/assets/89faeb7e-71a5-4865-9e2c-b68e1e12cd66)

Wieso der trotzdem 5GHz macht, weiss ich nicht

**Comment by knickohr** [comment]
Ach, das ist gar kein Fusion-Board 😅

Nee, der kann definitiv KEIN 5GHz !

**Comment by Loetnase** [comment]
Frag mal bei AZ-Delivery nach, 
vielleicht kennen die Details dazu 😁

**Comment by Gubi2023** [comment]
Falscher Alarm! DTU wars doch  nicht.
