### ISSUE TITLE
where to download new versions? 

### ISSUE THREAD

**Issue by MubiTec** [lumapu/ahoy#186]
<0.5.15 in downloaded the New compiled versions at github Menü "actions". Thince there is a New github Procedere I do not really now how to find it.

Br!

**Comment by DanielR92** [comment]
Here you can download the newest release in a *.bin file.
https://github.com/grindylow/ahoy/releases/tag/refs%2Fheads%2Fmain

Or in the main page of this project in the right sidebar you can read Releases topic.

**Comment by MubiTec** [comment]
Thank you 😊
