### ISSUE TITLE
increase numb of inverters greater then 4 => setup error

### ISSUE THREAD

**Issue by DanielR92** [lumapu/ahoy#193]
When you change the line 46 in the config.h file, from 3 to 6. The setup page is later broken. See image.
![grafik](https://user-images.githubusercontent.com/25644396/185985976-6c9a38db-2bf5-4aec-a3c3-30591f83379b.png)

When its 4, then it work. 

Found by 'Skusi': Discord chat session.

**Comment by DanielR92** [comment]
Testes with 0.5.15 (dev)

**Comment by tastendruecker123** [comment]
Dem ESP8266 geht an dieser Stelle aufgrund der großen Strings der Arbeitsspeicher aus. Der ESP32 kann die Seite auch mit 6 WR darstellen. Hier das Debug Log vom 8266:

20:21:36.560 > [String] Reallocating large String(9290 -> 9308 bytes) '<p class=" ... 1" value="'
20:21:36.569 > [String] Reallocating large String(9308 -> 9370 bytes) '<p class=" ... ngth="16">'
20:21:36.575 > [String] Reallocating large String(9370 -> 9388 bytes) '<p class=" ... 2" value="'
20:21:36.583 > [String] Reallocating large String(9388 -> 9450 bytes) '<p class=" ... ngth="16">'
20:21:36.588 > [String] Reallocating large String(9450 -> 9468 bytes) '<p class=" ... 3" value="'
20:21:36.597 > [String] Reallocating large String(9468 -> 9474 bytes) '<p class=" ... ngth="16">'
20:21:36.605 > :oom(9488)@WString.cpp:195

Das "oom" dürfte wohl für "out of memory" stehen.

**Comment by Skusi** [comment]
Keine Chance das noch in den 8266 zu bekommen ? Kann man irgendwo noch was einsparen ?
In der Version 0.4.25 waren 6 Inverter kein Problem. Ist jetzt der Code schon soviel größer geworden ?

**Comment by lumapu** [comment]
bin dran den AsyncWebserver einzubauen, ich denke der kann das dann wieder. Bitte noch etwas Geduld.

**Comment by tastendruecker123** [comment]
Hat eher damit zu tun, wie der HTML Code intern produziert wird. Das ist momentan sehr speicherintensiv da viele String Objekte erzeugt werden. Wenn man das umschreibt, wird es auch mit mehr Invertern gehen. Oder anders ausgedrückt, es liegt gar nicht mal so sehr an der Inverter-Anzahl sondern eher an der Größe des HTML Codes von /setup und dessen Erzeugung.

**Comment by lumapu** [comment]
genau, deswegen gibt es in Zukunft das hier:

https://github.com/lumapu/ahoy/blob/asyncWeb/tools/esp8266/tmplProc.h

**Comment by aschiffler** [comment]
@lumapu Vergiss nicht yield() in den callbacks bzw. den gebundenen "server.on" Funktionen raus zunehmen. Sonst läuft der webservice nicht. richtig "stabil". Das ist meine Erkenntnis. Z.B. in /livedata.
https://github.com/grindylow/ahoy/blob/348ad4bd07ddde67cd017547b2afcafa486f2b09/tools/esp8266/app.cpp#L618

Ich habe heute auch den Async eingbaut. Habe dann alles gestasht und wieder zurück auf los.
Meine Erkenntnis, der AsyncWeb macht nur Sinn wenn wir die html Seiten in ein File-System legen. Sonst wird das unpflegbar.
Ich habe nicht wie du einen "tmplProcessor" genutzt sondern direkt alles einfach umgeschrieben.
Meistens mit request->send_P(200,html.c_str()) --> geht laut Doku bis 1400 Byte für "html". Also ohne streamresponse.
Aber diese Funktion ermutigt weiter dran zu bleiben:
https://github.com/me-no-dev/ESPAsyncWebServer#setup-event-source-on-the-server

**Comment by lumapu** [comment]
@aschiffler Danke für die Hinweise. Ich glaube dass yield wird von AsyncWebserver auch als Warnung gemeldet.
Wie läuft das mit HTML im Filesystem? Statische Seite mit Javascript, die verzögert über die Events die Daten nachläd? Das ist auf jeden Fall ein ganz neuer Ansatz und definitiv interessant.

**Comment by aschiffler** [comment]
@lumapu Ja genau. Statische Seite html +Java Script und dann via Xhr z.b. einen SSE Endpunkt der im Javascript mit einem Eventlistener überwacht und direkt verwendet wird.
Man reduziert dadurch auch das Daten Volumen da z.b. nicht der ganze html code, wie jetzt sondern nur ein json String über die offen gehaltenen Verbindung zwischen server und client transportiert wird.
Siehe OpenDTU

**Comment by stefan123t** [comment]
Would be good to add a #pragma error in case we have more than 4 and ESP8266

@aschiffler / @tastendruecker123 (baloo) is there a similar maximum for ESP32 at the moment ?

**Comment by tastendruecker123** [comment]
I'm currently working on a more streamlined version of /setup that doesn't consume much RAM. It's still rough around the edges and not as easy to deploy right now (because the LittleFS filesystem needs to be built and uploaded separately), but I have put it up on my repo (in /dev2). At least on the web interface side there's no practical limit on the number of inverters, and the setup page works fine with 12 inverters on an ESP8266.

**Comment by stefan123t** [comment]
@tastendruecker123 just read up on the discord what you are about to do. So the LittleFS can be uploaded / updated via Web Interface too or is this only possible via the tools in pio / Arduino IDE ?

Here is a guide to upload filesystem images via Arduino IDE

https://randomnerdtutorials.com/install-esp8266-nodemcu-littlefs-arduino/

I recall that some allow to upload both firmware and filesystem images but I dunno how it is done as the firmware.bin is stored in the (SPIFFS?) filesystem until flashed.
There is mention of AsyncElegantOTA to be capable of also uploading some files to the (SPIFFS) filesystem.

https://randomnerdtutorials.com/esp32-ota-over-the-air-arduino/

Though I do not know whether AsyncElegantOTA would equally well work with LittleFS nowadays and tutorials are just outdated or whether we need to stick with SPIFFS ?

Note: Sticking with SPIFFS may not be a bad decision in the first place if we are trying to append data to files as it is not using copy-on-write as LittleFS which would prevent lots of 4k block writes in such a use case.

See #164 for filesystem decision and #185 for the logging / append to file use-case. Thanks

**Comment by DanielR92** [comment]
Are we at now on a point, to close this issue? 
From my site it was only a hint for a "bug"... 

Also it is possible to write a secure part in, to limit in a ESP8266 to until 4 Inverter. 
When it is a ESP32, then we can increase the number.

What do you think about it?

**Comment by lumapu** [comment]
we should test it again using the development branch with AsyncWebserver.
For now the maximum number is set to 4 but not testet with grater numbers.

**Comment by DanielR92** [comment]
Next week I can test it (not with real inverter). Thanks for reply. 👍

**Comment by stefan123t** [comment]
I think this calls for SPIFFS/LittleFS storage just as #164 for storing the settings. This has some details about how to bundle / upload the bin and the filesystem image.

**Comment by dennsen79** [comment]
Hallo,

ich brauche ein fertige Firmware für meinen 8266 mit 6 Invertern. In der Version 0.5.17 gehen ja derzeit leider nicht mehr. Kann mir jemand eine Firmware bauen mit 6 Invertern in einer Version mit der es laufen würde?

Danke im Vorau!

**Comment by DanielR92** [comment]
Moin,

habe es gerade getestet. Also es sollte nun klappen:
![grafik](https://user-images.githubusercontent.com/25644396/195363748-a8954478-dfbd-4b8c-9201-c39a67050db9.png)

Da ich nicht so viele WR besitze, müsste das jemand anders testen.

[firmware_0.5.19.zip](https://github.com/lumapu/ahoy/files/9765710/firmware_0.5.19.zip)

**Comment by dennsen79** [comment]
Hallo,

Ich konnte die Firmware 0.5.19 mit fünf Invertern (4 x HM 300, 1 x HM 600) testen. Leider habe ich Probleme mit den empfangenen Daten über MQTT. Werte werden falsch dargestellt.

Hat jemand auch schon diese Version mit mehr als vier Geräten ausprobiert?

Kann mir jemand eine funktionierende Firmware für bis zu sechs Geräten oder genau fünf zur Verfügung stellen? Am besten die Version 0.4.25

Alternativ würden mir auch die Sourcen zur Version 0.4.25 reichen.

Vielen Dank im Voraus!

**Comment by lumapu** [comment]
bezüglich MQTT bitte nochmal mit aktuellem Release 0.5.28 testen
Die Firmware unterstützt 4 Inverter

**Comment by stefan123t** [comment]
@dennsen79 und @DanielR92 könnt Ihr mal das Issue mit dem aktuellen Release 0.5.28 oder Development 0.5.32 prüfen, wieviele Inverter da als Maximum gehen ?

@Skusi und @tastendruecker123 / baloo wir haben den AsyncWebServer ins o.g. Release mit eingebaut. Willst Du das Issue eventuell nochmal bewerten ?

**Comment by lumapu** [comment]
in der aktuellen development Version gehen bis zu 10 Inverter

**Comment by DanielR92** [comment]
Kann das jemand testen?

**Comment by Skusi** [comment]
Ich hab die 0.5.37 seit gestern mit 6 Invertern erfolgreich laufen !

**Comment by dennsen79** [comment]
Ich habe die 0.5.37 seit gestern mit 5 Invertern (4 x HM 300,  1 x HM 600) erfolgreich am laufen!

**Comment by stefan123t** [comment]
@lumapu ich glaube Du kannst das ins nächste Release übernehmen und hier zu machen.
