### ISSUE TITLE
Feature Request: MQTT command check data (<INVERTER_ID>)

### ISSUE THREAD

**Issue by DanielR92** [lumapu/ahoy#198]
The most User setup the DTU with a Serial from the inverter. When they try to send a command in mqtt for example with the command: "<CHOOSEN_TOPIC_FROM_SETUP>/devcontrol/<INVERTER_ID>/11", they could send

A.) inverter/devcontrol/0/11 
B.) inverter/devcontrol/11611151.../11 

It is recommended to change the code "hmSystem.h" in line 90. with a check of the length.
When the value is two chars long, then it is the position of the iv.

But when its longer 8 char, then pick it from the list with the specific ID. Or?

Issue found by strato354

```INVERTERTYPE *getInverterByPos(uint8_t pos, bool check = true) {
            DPRINTLN(DBG_VERBOSE, F("hmSystem.h:getInverterByPos"));
            if((mInverter[pos].initialized && mInverter[pos].serial.u64 != 0ULL) || false == check)
                return &mInverter[pos];
            else
                return NULL;
        }

**Comment by aschiffler** [comment]
The check shall be done in the mqtt callback.

**Comment by aschiffler** [comment]
This is now fixed (https://github.com/grindylow/ahoy/tree/ahoy_v0.5.16). The mqtt topic only supports the id of the inverter not the serial number in the topic path.
