### ISSUE TITLE
esp8266: no packets received

### ISSUE THREAD

**Issue by petit-miner** [lumapu/ahoy#20]
Hallo,
erstmal vielen Dank für das tolle Projekt und den Code!
Habe hier einen ESP8266 mit einem nrf24l01+ PA verbunden und habe das Problem das ich scheinbar keine Pakete erhalte.
Die Seriennummer habe ich von der Rückseite des Umrichters abgeschrieben, die Nummer habe ich mehrmals überprüft.
Initial hatte ich den ESP falsch mit dem NRF Modul verbunden, welches ich durch die Fehlermeldung auf der Indexseite sehen konnte. Dies konnte ich bereits beheben. Gibt es einen DebugModus oder andere Möglichkeiten zu testen warum ich keine Messwerte erhalte? 
Vielen Dank im voraus!
Gruß Marcel

**Comment by petit-miner** [comment]
Der IRQ Pin lag nicht an einem Pin der Interruptfähig ist. Nach dem ich den Fehler behoben habe läuft auch alles.

**Comment by lumapu** [comment]
Super, dass du es beheben konntest. Was mich auch freut, dass die Fehlermeldung auf der Indexseite zur Problembehebung beitragen konnte.

**Comment by stefan123t** [comment]
Hallo Lukas (@lumapu) vielleicht sollten wir die Auswahl der Interrupt PINs in der Setup Seite auf die Interrupt-fähigen PINs einschränken.
Marcel (@petit-miner), welcher PIN war denn bei Dir der Falsche, bzw. welchen ESP8266 verwendest Du und wie war er verschaltet/verdrahtet ?

**Comment by stefan123t** [comment]
Ich habe folgende [Anmerkung](https://randomnerdtutorials.com/interrupts-timers-esp8266-arduino-ide-nodemcu/) hierzu gefunden:
> The ESP8266 supports interrupts in any GPIO, except GPIO16.

**Comment by crbble** [comment]
Moin, da ich über das gleiche Problem gestoßen bin, auch beim Arduino MEGA 2560 sind nur die Pins 2, 3, 18, 19, 20, 21 interrupt fähig.
