### ISSUE TITLE
mqtt topic

### ISSUE THREAD

**Issue by gent99** [lumapu/ahoy#205]
setting mqtt topic doesn't work as expected: There's always /homeassistant prefixed ... that's not an ideal thing for those, using mqtt without using homeassistant too. Could that be fixed please?

Kind regards

**Comment by MubiTec** [comment]
I Think homeassistant is always there, your own topic is in Addition

**Comment by fila612** [comment]
Normally there is like @MubiTec said, can you please Share a Screenshot from a mqtt-tool?

**Comment by lumapu** [comment]
maybe we should add an extra checkbox and REST API call for that

**Comment by gent99** [comment]
> I Think homeassistant is always there, your own topic is in Addition

Yes. Did not see this.
