### ISSUE TITLE
HM-300

### ISSUE THREAD

**Issue by siegfriedhoellrigl1** [lumapu/ahoy#207]
Should the ESP8266 Software work with the HM-300 Inverter too ?

I have tried this with SW Version 0.4.19, 0.4.22 and with 0.4.25.
(because there are binary downloads on the internet for that...)

It seems that there es some interaction between the ESP and the RF Module.

But no values are recieved from the inverter.

**Comment by Chrischi-** [comment]
Look under releases for the 5.15

https://github.com/grindylow/ahoy/releases

You have to scroll to the bottom of the release notes and maybe you should test your setup right next to the microinverter to exclude reception problems.

**Comment by Matz3e** [comment]
Yes it's working with the HM-300. My ahoy 5.15 is running perfect. Try to go very close the the HM for the fist time.

**Comment by DirkausHH** [comment]
0.5.13 is working stable for some days with my HM-300.
In the beginning it took up to 30 minutes to receive first data, but now it's running fine.

**Comment by siegfriedhoellrigl1** [comment]
Would someone be so kind, and post a binary version of 0.5.13 ?
It seems to be a bit challenging to compile it.

**Comment by fila612** [comment]
please have a look at the "Actions" section on this page.

**Comment by aschiffler** [comment]
Close due to inactivity. Assume issue is fixed.
