### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by gent99** [lumapu/ahoy#208]
Hi, 

i cloned from here:

https://github.com/grindylow/ahoy.git

and get a lot of build failes

starting with

hmInverter.h:87:35: error: template declaration of 'const calcFunc_t<T> calcFunctions []'

Kind rergards

**Comment by lumapu** [comment]
can you share a bit more information on your environment and knowledge?
Are you using PlatformIO and is the ESP8266 board support installed?
Have you experience using PlatformIO with ESP?
Maybe you don't want to change anything on the code then look to the Github Actions for compiled binaries.

**Comment by gent99** [comment]
Of course. Installed platforms are Espressif 8266 2.7.4+9 and 1.8.0. My environment is set to env-esp8266-release. I was able to compile the code last week without any problems but it was on another machine, i didn't have access to right know, so i can't tell what the difference is. I talked to a friend and he thinks, that in platformio.ini the exact platform-version ist not set. So during compiling, the newest version is used. Perhaps this version is not the right one. So we have to know wich version we should use.

**Comment by stefan123t** [comment]
Could you check what happens if you install only one of the platforms for ESP8266 ?
Also there could be a problem with  later versions of ESP8266 platform vs. ESP32 eg. the HTTPS certs for ESP are only in the ESP32 platform files afaik.

**Comment by tastendruecker123** [comment]
In platformio.ini, try adding the following build flags under [env]:

build_flags = -std=gnu++14
build_unflags = -std=gnu++11

This is related the ESP32 build process, and depending on your local compiler settings, it may just be a warning or the build may fail.

**Comment by lumapu** [comment]
> In platformio.ini, try adding the following build flags under [env]:
> 
> build_flags = -std=gnu++14 build_unflags = -std=gnu++11
> 
> This is related the ESP32 build process, and depending on your local compiler settings, it may just be a warning or the build may fail.

should we add this generally to the platform.ini?

**Comment by tastendruecker123** [comment]
That would be a good idea.

**Comment by gent99** [comment]
No, it's not. With this flags, i got more than 1000 Errors during build.

**Comment by gent99** [comment]
This is my build environment WITHOUT the flags:
```
CONFIGURATION:` https://docs.platformio.org/page/boards/espressif8266/esp12e.html
PLATFORM: Espressif 8266 (2.7.4+9) > Espressif ESP8266 ESP-12E
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 2.7.4+9 
 - tool-esptoolpy @ 1.30301.220515 (3.3.1) 
 - toolchain-xtensa @ 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- RF24 @ 1.4.5
|   |-- SPI @ 1.0
|-- Time @ 1.6.1
|-- PubSubClient @ 2.8.0
|-- ArduinoJson @ 6.19.4
|-- DNSServer @ 1.1.1
|   |-- ESP8266WiFi @ 1.0
|-- ESP8266WebServer @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- ESP8266WiFi @ 1.0
|-- ESP8266HTTPUpdateServer @ 1.0
|   |-- ESP8266WebServer @ 1.0
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- EEPROM @ 1.0
|-- SPI @ 1.0
Building in release mode
```

On my other mac (with M1 Chip), it builds fine with the same platform

PLATFORM: Espressif 8266 (2.7.4+9) > Espressif ESP8266 ESP-12E

**Comment by tastendruecker123** [comment]
Can you post some of the build errors?

**Comment by gent99** [comment]
Here's a screenshot with all of them. I hope that will work and you could read everything
![Bildschirmfoto 2022-08-31 um 13 08 24](https://user-images.githubusercontent.com/3154493/187665145-417ad172-2e1c-4a95-bbe6-d38951c83466.png)

**Comment by tastendruecker123** [comment]
Are the /tools/esp8266/platformio.ini files identical between your Mac and the other machine?

**Comment by gent99** [comment]
I pulled the code from github (on both machines) and all i changed was the upload_port and monitoring_port. So they should be identical. I can verify this later, when i have access to both machines.

**Comment by bassetware** [comment]
For me the code won't compile, too. There are several errors called: error: "call of overloaded 'String(uint64_t&, int)' is ambiguous"
Cloned the code with vs-studio code and then tried to compile. 
Would be great if you would provide a compiled version. 
For ESP8266 compile fails in release mode with:
warning: Calling missing SConscript without error is deprecated.

**Comment by gent99** [comment]
OK, I found a solution: I uninstalled every Espressif 8266 platform Version of platformio.

Build worked now.

Now i have Espressif 8266 @ 4.0.1
