### ISSUE TITLE
Null Werte nach aktualisieren der Leistungsbegrenzung

### ISSUE THREAD

**Issue by Matze7779** [lumapu/ahoy#213]
Hallo,

Version 0.5.15
ioBroker
Hoymiles HM-1200

Immer wenn ich über MQTT einen neuen Wert in devcontrol.0.11.0 setze werden kurz alle anderen Werte (Leistungen usw) auf 0 gesetzt.
Auch direkt im Webbrowser (Ahoy-Visualisierung) verschwinden kurz alle Werte.

Ist es möglich dieses zu verhindern?

**Comment by aschiffler** [comment]
Hi,

ja das Problem ist bekannt und bzieht sich auf die Visualisierung und auf die Ausgabe per MQTT. Im nächsten Release 0.5.16 ist dies behoben.
