### ISSUE TITLE
Inverter Daten immer wieder falsch

### ISSUE THREAD

**Issue by mattenausohz** [lumapu/ahoy#216]
Hallo! Nach jedem Neustart sehe ich:

Receive success: 0
Receive fail: 1
Frames received: 0
Send Cnt: 5

Inverter 'Balkonkraftwerk (FW-Version: 0)' is not available and is not producing
Inverter 'Balkonkraftwerk (FW-Version: 0)' is not available and is not producing
Inverter '���������������� (FW-Version: 0)' is not available and is not producing

Ich habe nur einen Inverter und lösche immer wieder die Daten zu den beiden anderen. Was läuft hier schief?

Gruß,
Matthias

**Comment by lumapu** [comment]
wird mit dem nächsten Relase gefixt, bitte dev testen, dort wurde es schon gefixt.
Ansonsten mit einer einzelnen '0' speichern, dann sollte es auch verschwinden.
