### ISSUE TITLE
Update übernimmt keine Einstellungen!?

### ISSUE THREAD

**Issue by DennisXK** [lumapu/ahoy#223]
Hi Zusammen,

ich habe Heute auf zwei Wemos die Version 0.5.16 von 0.4.25 über die update Funktion durchgeführt. Leider muste sich feststellen, dass ich bei beiden alles neu einrichten bzw. einstellen musste. 

bei der 0.4.xx hat er alle Einstellungen übernommen. Ist das bebasichtigt oder war das weil ich so einen großen Sprung gemacht habe?

**Comment by aschiffler** [comment]
Hi,

ja das ist wegen des Versionssprungs.

VG
Andreas
