### ISSUE TITLE
AP-Passwort in Doku aufnehmen

### ISSUE THREAD

**Issue by helgeschneider** [lumapu/ahoy#224]
Hab eine Weile suchen muessen bis ich in der config.h das Passwort des APs fuer die Ersteinrichtung gefunden habe, vielleicht koennte man das in die Doku aufnehmen.
Passwort: esp_8266
IP zur Konfiguration: 192.168.1.1

**Comment by lumapu** [comment]
erledigt, Dank @thfcm
