### ISSUE TITLE
TOR_Erzeuger definieren

### ISSUE THREAD

**Issue by mesingerold** [lumapu/ahoy#225]
Hallo,

vorab ein großes Dankeschön an die Entwickler - super Arbeit 👍

System läuft unter v 0.5.15 perfekt, optimal wäre noch die Möglichtkeit einer Definition des Standard TOR_Erzeuger-Profils (Bsp: AT_TOR_Erzeuger_default) via Interface!!

Vielleicht findet ihr eine Möglichkeit,

Danke & LG

**Comment by stefan123t** [comment]
Siehe #96

**Comment by DanielR92** [comment]
Das müsste man hier diskutieren. Ich bin alles nur überflogen... habe ich richtig gelesen, das es die Möglichkeit gibt in der orig. DTU via Auswahl ein Profil zu aktivieren, der WR sich dann daran anpasst?

Oder geht es darum komplette Config des WR zu modifizieren?

**Comment by stefan123t** [comment]
@DanielR92 in der DTU Pro kannst Du ein sog. TOR bzw. Technische und Organisatorische Regeln für Betreiber und Benutzer von Netzen (TOR) / GridProfile auswählen. Dieses wird auf den WR geladen und dann arbeitet der WR nach den Anweisungen des GridProfiles. Dieses enthält ua die nationale Netzfrequenz, das obere und untere Netzspannungslimit etc pp.

Das müsste also De-ichirou einmal umstellen und tracen damit wir die Kommandos und Antworten vom WR haben.
Das ganze gehört aber mE bereits in das andere issue und braucht hier nicht doppelt diskutiert werden.

**Comment by stefan123t** [comment]
Bitte in #96 weiter diskutieren Danke

**Comment by stefan123t** [comment]
closed as duplicate of #96
