### ISSUE TITLE
devcontrol question

### ISSUE THREAD

**Issue by urpils4711** [lumapu/ahoy#227]
is there a more detailed description about setting up 
"The ahoy-dtu subscribes on the topic <CHOOSEN_TOPIC_FROM_SETUP>/devcontrol/# if the mqtt broker is set-up correctly. The default topic is inverter/devcontrol/#." ?

will this topic gemerated automaticly?

regads

**Comment by lumapu** [comment]
@urpils4711 das sollte weiterhelfen:

https://github.com/grindylow/ahoy/blob/main/tools/esp8266/User_Manual.md
