### ISSUE TITLE
HM-600 auf 800w bringen?

### ISSUE THREAD

**Issue by setje** [lumapu/ahoy#228]
Hallo zusammen,

ich habe verstanden, dass sich das Limit des HM-600 auf 800w statt 600w bringen lässt. Es scheint, als wäre der String bei 320w limitiert zu sein. Zumindest sehe ich das bei dem String, wo ich 2x 335w Module per Y-Adapter dran hängen habe, die jeweils in Ost/West ausgerichtet sind.  Wenn ich das Power-Limit auf z.b. 125% erhöhe, bleibt der String bei max. 320,40w stehen.
Mache ich etwas falsch bzgl. Power-Limit? Folgendes habe ich eingestellt:
<img width="638" alt="ahoy" src="https://user-images.githubusercontent.com/20984660/188148900-ceef1efb-416c-420c-8947-6822e57be7b2.png">

**Comment by duenengeist** [comment]
Hallo,
hat er die 125% denn akzeptiert? Afik werted die neueste Version doch die Rückmeldung des WR aus, oder?

**Comment by setje** [comment]
Hallo, wie kann ich das Prüfen? Im Visualization Frontend steht In der Überschrift: "HM-600 Limit 125 %"
<img width="985" alt="ahoy_2" src="https://user-images.githubusercontent.com/20984660/188152934-b01fe6c0-bd16-43f5-9dd8-967f176ee8b4.png">

**Comment by duenengeist** [comment]
OK, dann glaub ich mal auf der seriellen Console mitlesen. Habs bei mir auch probeweise grad mal eingestellt. Habe aber leider keine serielle dran, da auch "Funkgründen" der ESP im Gartenhaus montiert ist.

125% werden mir im Web-UI auch angezeigt, leider zu wenig Sonne, um zu sehen, wie weit er geht (ich habe 350Wp an jedem Kanal)

**Comment by lumapu** [comment]
evtl. bist du am Limit des Channels? Ich glaube nicht, das ein HM600 seine gesamte Leistung über einen Eingang beziehen kann.
Mit welchem maximalen Strom ist der HM600 angegeben?

-> 11.5A und 29-48V Leistung 240 - 380kWp
=> es sollte eigentlich noch nicht limitieren

**Comment by duenengeist** [comment]
Stimmt angegeben

![Bildschirmfoto_2022-09-02_15-29-57](https://user-images.githubusercontent.com/10466558/188156742-a36c316f-6152-4f66-adcc-dfb627053b5c.png)

sind 11,5A und wenn das Panel im MPPT vielleicht 36V hat sind das 400W per Channel. War hier nicht jemand, der eine 48V-Batterie dran hat, der könnte das ggf. einfacher testen. Wobei ich auch die Gefahr sehe, dass etwas kaputt geht...

**Comment by lumapu** [comment]
und wenn die Eingänge zu unterschiedlich sind? Der hat doch nur einen MPPT oder?
Komisch finde ich, dass die Leistung scheinbar konstant ist

**Comment by duenengeist** [comment]
Der HM600 hat m.E 2 MPPT, das ist an den unterschiedlichen Spannungen zu sehen (grade sind bei mir beide Panels gleich im Licht (Wolken), daher nicht viel Differenz). Beim HM-1200 sind je zwei Eingänge zusamengeschaltet, da sind die Spannunge dann immer genau gleich.

![Bildschirmfoto_2022-09-02_15-42-16](https://user-images.githubusercontent.com/10466558/188159452-73cfc5b4-241a-47d8-9019-0ae8e1cc6910.png)
![Bildschirmfoto_2022-09-02_15-42-49](https://user-images.githubusercontent.com/10466558/188159776-46bc0c92-d5e2-42dd-8a35-504f59c0e15c.png)

Der HM-1200 ist nur mein Testaufbau zum gebrauchte Panels prüfen, da über nix wundern :-)

PS: mein "Getippse" ist ja lausig, bin grade in einer abklingenden Coronainfektion und irgendwie Matsch im Kopf...

**Comment by lumapu** [comment]
Den HM1200 habe ich auch. Dass die Spannungen hier identisch sind liegt an meiner Implementierung. Wir haben in der Payload nur 2 Spannungen gefunden, daher würde jede kopiert um für alle Channels eine Spannung zu haben.
Ich habe allerdings auch getestet, dass zB. Eingang 1 und 2 auf die erste Spannung wirken.

**Comment by duenengeist** [comment]
Ich könnte das die nächsten Tage noch mal am Gerät nachmessen...

**Comment by stefan123t** [comment]
@duenengeist bisher war kein Limit über 100% möglich es sei denn es hat sich in den letzten Wochen hierzu Neues ergeben. Vielleicht mal mit @klahus1 oder @aschiffler  im Chat besprechen die hatten das ActivePower Limit ausgetestet und implementiert.
@aschiffler hatte mW auch eine Option eingebaut die aktuellen Settings in Prozent aus dem 0x05 SystemConfigPara auslesen.

**Comment by aschiffler** [comment]
Ja, das aktuell gesetzte Limit wird jedes mal wenn man es ändert ausgelesen. Also quasi geprüft ob es "angekommen" ist.

**Comment by Chrischi-** [comment]
@stefan123t 
im DEV-Branch sind derzeit auch keine 125 % möglich. Gerade mit dem Build von gestern getestet.

Mich würde aber auch interessieren, wie man dem Mikro-Inverter (HM-600) sagen kann, welche Panels
dran hängen und er somit nicht direkt bei jeweils ~320 W reguliert.

**Comment by duenengeist** [comment]
das Web-UI zeigt aber 125% an, siehe mein Screensaht oben...

**Comment by Chrischi-** [comment]
@duenengeist 
Ja alles gut! Mir ging es um die Entwicklungsversion, bei der es in meinem Fall nicht geht. 

Du nutzt ja die 5.15, oder?

**Comment by duenengeist** [comment]
ja, ich nutze die 5.15
