### ISSUE TITLE
esp8266 0.3.3 CH0_YieldDay Anzeige in kWH anstatt Wh?

### ISSUE THREAD

**Issue by rosch99** [lumapu/ahoy#23]
Auf der Webseite wird für YieldDay die Einheit "kWh" angegeben, leider sind es vmtl. aber nur "Wh" ;-)

Hardware:
Wemos D1 mini 0.3.3
HM1200 mit 2 Modulen an CH1 und CH2

**Comment by lumapu** [comment]
danke für den Hinweis, wird in der nächsten Version gefixt.
