### ISSUE TITLE
SSID mit Punkten

### ISSUE THREAD

**Issue by lalamite** [lumapu/ahoy#231]
1000 Dank für Eure Mühen.

mich bin von 0.5.5 auf 0.5.15 upgegraded.

Nach dem Firmware Update kann sich mein Ahoy nicht mehr mit meinem WLAN verbinden. Mit meinem Gast WLAN funktioniert es allerdings. Der einzige Unterschied zwischen den beiden WLANs ist, dass mein Haupt WLAN Punkte im SSID Namen hat, also so: Wlan…

kann hier etwas schief gegangen sein?

**Comment by lumapu** [comment]
muss man prüfen, evtl arbeiten wir hier mit strlen

**Comment by lumapu** [comment]
gerade nochmal nachgeschaut, sollte kein Problem sein, es hat nur eine maximale Länge

https://github.com/grindylow/ahoy/blob/main/tools/esp8266/web.cpp#L299

**Comment by lalamite** [comment]
> gerade nochmal nachgeschaut, sollte kein Problem sein, es hat nur eine maximale Länge
> 
> https://github.com/grindylow/ahoy/blob/main/tools/esp8266/web.cpp#L299

Hmm strange. Ich habe es 5 Mal probiert. Vorher (0.5.5) ging es aber nun bekomme ich es einfach nicht mehr zum Laufen. Router neu gestartet, lease erneuert etc. nichts hat funktioniert. WLAN Daten von Gastnetzwerk eingetragen und zack…verbunden.

**Comment by lumapu** [comment]
das muss nochmal verifiziert werden, habe aktuell keine Punkte in meiner SSID

@lalamite was steht denn auf der Setup Seite nach einem reboot im Feld SSID drin?

**Comment by DanielR92** [comment]
Seit 18 Tagen gab es keine Rückmeldung. Soll dies noch verfolgt werden?

**Comment by lumapu** [comment]
ich würde gerne noch wissen was passiert, hatte es aus den Augen verloren

**Comment by stefan123t** [comment]
@lumapu das könnte mit der überladenen WiFi Methode zum connect zusammenhängen. 
Die interpretiert Angaben mit Punkten vielleicht zuerst als IP Adresse und dann klappt der Fallback nicht. 
Keine Ahnung ob wir das nochmal öffnen müssten oder ob das kein Problem mehr ist ?

**Comment by lumapu** [comment]
@stefan123t ich auch nicht 😉
