### ISSUE TITLE
Feature Request: Sub1G Unterstützung für 3ph HMT-1800-6T, HMT-2250-6T und HMS-2200-4T 

### ISSUE THREAD

**Issue by Tool-use-today** [lumapu/ahoy#233]
Besten Dank für Eure Entwicklung! die "kleinen" Hoymiles in Fhem einzubinden ist so ziemlich chic gelöst.

Ich bekomme bald zwei HMT-2250-6T, also die dreiphasigen Geräte mit 6 Eingängen (immer 2 Panels auf einem MPPT). 

Wurde schon getested, ob die aktuelle Version auch mit diesen kompatibel ist, bzw. ist es in Planung, diese zu implementieren?

**Comment by aschiffler** [comment]
Getestet nein. Wenn es alles gut läuft ist das nur eine Erweiterung im Parser. Wenn Du die Geräte in Betrieb hast sende die Logs der Antworten mit aktiviertem "RF24-Debug". Verwende dazu in den ersten vier Stellen deiner Seriennummer 1161.

**Comment by ghost** [comment]
Quelle: https://github.com/stefan123t/ahoy/wiki/FAQ-Frequently-Asked-Questions#welche-ger%C3%A4te--funktionen-werden-nicht-unterst%C3%BCtzt

"Welche Geräte / Funktionen werden nicht unterstützt

    Werden Hoymiles HMT und HMS auch unterstützt ?

Nein HMT und HMS verwenden ein anderes Funkmodul und können daher (vorerst) auch nicht unterstützt werden. Ob die beiden Modelle auch die selben Kommandos verwenden ist bisher unbekannt."

**Comment by stefan123t** [comment]
Eventuell gehen HM-600T da die evtl nur einen anderen Anschluss haben. Aber HMS und die dreiphasigen HMT sind mW definitiv nur mit einem anderen Funkmodul und anderen Frequenzen zu erreichen. Siehe Discord #hms-serie

**Comment by Tool-use-today** [comment]
Ich habe mir heute die Betriebsanleitung der HMT Serie durchgelesen. Sie benutzt, ebenso wie die HMS Serie die Sub 1G Technologie, wie sie es nennen. Also irgendwas um die 900Mhz.

Ob ich mir die entsprechende DTU-Pro-S, Lite-S dazu kaufe, weiß ich noch nicht. Wenn ja, kann ich das Ding mal aufmachen und prüfen, ob intern die Kommunikation nach dem gleichen Schema läuft und nur ein andere Transmitter genutzt wird.

Evtl. hat das schon mal jemand auch in Bezug auf die HMS Serie gemacht?

**Comment by stefan123t** [comment]
HMT-1800-6T HMT-2250-6T datasheets :
https://www.hoymiles.com/wp-content/uploads/2022/08/User-Manual_HMT-18002250-6T_Global_EN_V202207.pdf

Also das T steht hier für Three Phase und es wird wohl offensichtlich ein sog Sub-1G Modul eingesetzt.
Die HMS und auch die dreiphasigen HMT verwenden einen anderen Übertragungsmodus Sub1G
Das ist korrekt, 868MHz soweit ich weiß, HM nutzt 2,4GHz.

> 6. Troubleshooting
This microinverter (SN:1382xxxxxxxx) can only work with the new Hoymiles DTU (DTU-Pro-S, DTU-Lite-S) with the following serial number.

| Model | Serial Number |
| --- | --- |
| DTU-Pro-S | 10FCxxxxxxxx 10FDxxxxxxxx |
| DTU-Lite-S | 10D7xxxxxxxx 10D8xxxxxxxx |

Und hier die DTU-Pro S https://www.shinetech-power.de/wp-content/uploads/2021/07/SNE-DTU-Pro-S.pdf
Hat offenbar auch eine FCC Registrierung mal nach der FCC ID suchen ?

Und hier das Sub1G Module von innen 
https://fcc.report/FCC-ID/2ARNB-HMS10/5204735
<details><summary><b>PARENTAL ADVISORY</b>: Contains Graphical details showing Bare Circuits! 
</summary>
<p>
<img src="https://user-images.githubusercontent.com/11159753/188844028-6cad6e3b-3422-4e46-aac4-28b63acf9e40.png">
<img src="https://user-images.githubusercontent.com/11159753/188843262-3d65542a-31d3-4816-a760-7c366b377dd6.png">
<img src="https://user-images.githubusercontent.com/11159753/188843333-89e7b819-ea07-4a49-a45c-122691db0d44.png">
</p>
</details>

Die Chips haben m.E. folgende Bezeichnungen:
* E230G8 AS2RPK JJ2019 GD ARM (GigaDevices)
* 300A E965 945

**Comment by Tool-use-today** [comment]
kann noch das manual mit Pinout dazugeben....


https://manuals.plus/hoymiles/hms101-sub-1g-transmitter-module-manual#axzz7eCe95wJA

ebenso gibt es einen parallel Thread:

https://www.mikrocontroller.net/topic/539369

**Comment by stefan123t** [comment]
Hier noch unsere bisherigen Erkenntnisse aus dem #hms-serie Kanal im Discord:

Also es gibt keinen HMT-600 und HM-600T ist die Trunk Version des HM-600, kann also auch mit nRF24L01+ gemonitored werden.
Für die HMS-600 und andere aus dieser Baureihe braucht es wohl die o.g. Sub-1G Funkmodule mit Frequenz von 868 MHz oder 915 MHz.

4.1 NRF Channel List
Depending on the program. the module can work on 915MHz for North America and 868MHz for Europe. Unless necessary, it’s forbidden to change the module program.

Read more: https://manuals.plus/hoymiles/hms101-sub-1g-transmitter-module-manual#ixzz7eD7IooaT

**Comment by stefan123t** [comment]
Habe noch ein NRF905 Module gefunden https://www.ebay.de/itm/155141668345 dafür gibt es auch eine Arduino Library https://github.com/ZakKemble/nRF905-arduino

There is some information on Zaks Blog: https://blog.zakkemble.net/nrf905-avrarduino-librarydriver/

The nRF905 is a radio transceiver IC similar to the well known nRF24L01, but operates at 433/898/915MHz instead of 2.4GHz, has a much longer range and a few extra IO pins. However, the nRF905 data rate is only 50Kbps compared to nRF24L01’s 2Mbps.

**Comment by stefan123t** [comment]
Der von Flole identifizierte CMOSTEK CMT2300A wird hier beschrieben
http://www.cmostek.com/products/wireless/transceivers/CMT2300A

**Comment by leowinterde** [comment]
Habe letzte Woche ein HMT-2250-6T in betrieb genommen, sobald das DTU-Pro-S hier ist kann ich auch etwas mitschneiden, sollte bedarf bestehen - ein hackrf liegt hier.

**Comment by stefan123t** [comment]
@LeoWinterDE bisher wurden die besten Ergebnisse mit einem/zwei Terminals an den TX/RX Testpunkgen auf dem Board der DTU gewonnen. Die HackRF Auswertung hat sich bei den nRF24L01+ Modulen als schwierig / aufwendig herausgestellt. Zu den CMT2300A haben wir Bezugsquellen über AliExpress / eBay gefunden. Mehr ggf im Discord Chat im Kanal #hms-serie.

**Comment by jelli123** [comment]
@LeoWinterDE Ein HackRF Mitschnitt wäre trotzdem interessant, um die Modulationsart zu bestimmen. Wäre doch prima, wenn das auch mit einem klassischen CC1101 ginge.

**Comment by Flole998** [comment]
Warum ein CC1101 verwenden wenn's doch die RFM300 gibt und man so quasi die ganze Parametrierung nur mitschneiden muss und durch eine eigene CPU an ein eigenes Funkmodul senden muss? Ich würde erstmal versuchen das ganze vom Grunddesign her nachzubauen, dann kann man am einfachsten bei Problemen nach unterschieden zum Original suchen.

Da ich aber weder Wechselrichter noch Funkmodul habe werde ich dazu leider nicht wirklich mehr beitragen können.

**Comment by stefan123t** [comment]
@Flole998 und @jelli123 beide Module CC1101 und RFM300 werden zwar zB auf der Bucht mit 868MHz angeboten. Aber zumindest das CC1101 ist 
1. ungeschirmt
2. i.d.R. ohne Antennenanschluss und nur mit einer festverlöteten Drahtdipolwendel versehen
und zumindest das RFM300 ist
3. viel teurer als ein CMT2300A

@Flole998 wie hast Du eigentlich das CMT2300A initial identifiziert, ich konnte bisher keine Chip IDs etc. zuordnen ?

Das von mir vorgeschlagene nRF905 Modul besitzt lediglich dieselbe Frequenz und fällt daher mE vorerst aus dem Kreis der potentiellen Kandidaten aus.

**Comment by jelli123** [comment]
@stefan123t Ob die Schirmung bei 868MHz tatsächlich ausschlaggebend oder eher eine Zulassungsfrage ist, wäre zu untersuchen. Selbst die 2. Oberwelle sollte außerhalb des 2.4GHz Bandes liegen. Es gibt aber auch geschirmte CC1101 Modelle.
Bei der Entwicklung auf den Original-Chip zu setzen führt sicher schneller zum Ziel. Mein Gedanke beim CC1101 war, dass es sehr schöne fertige und günstige Geräte zum Sniffen und Entwickeln gibt, die man direkt am PC oder RasPi verwenden kann. Siehe die beliebten CUL(W) oder den umflashbaren MaxCube (mit Ethernet Interface).

**Comment by Flole998** [comment]
@stefan123t Die Bezeichnung steht ja auf dem Chip drauf, so habe ich den erkannt.

Es wäre natürlich cool/witzig einen MaxCube als Gateway für diese Wechselrichter umzuflashen, da hat man Ethernet und eigentlich alles was man braucht.

**Comment by stefan123t** [comment]
Update von heute aus dem Discord #hms-hmt-serie:

Könnten wir die nRF-Bibliotheken einfach durch CC1101 ersetzen
Ein einfaches austauschen der Libary wird hier nicht wohl ausreichen. 
Die Aufrufe der Libary Funktionen werden nicht identisch sein...
Auch die Befehle für den Wechselrichter werden wahrscheinlich anders sein.

Man braucht also zwingend eine Bibliothek die die Low-Level TX/RX Buffer Kommunikation mit dem CC1101 oder einem anderen 868MHz Chip auf dem genutzten Modul übernimmt. Welche Bibliotheken und Chips haben wir denn eigentlich zur Verfügung ?

Hier der Link zu Texas Instruments CC1101 mit den Application Notes und Beispiel Code etc https://www.ti.com/product/CC1101
Und hier noch eine Bibliothek von Simon Monk basierend auf ElecHouse https://github.com/simonmonk/CC1101_arduino vermutlich ist aber die von SpaceTeddy besser gepflegt / aktueller ? https://github.com/SpaceTeddy/CC1101 
Vielleicht macht es sogar Sinn auf die folgende Universalbibliothek umzustellen dann hätten wir nur ein Interface und könnten sowohl nRF24 als auch CC1101 anbinden / -bieten ? https://github.com/jgromes/RadioLib

Bezüglich den Mitschnitten mit HackRF etc. das sollte eigentlich auch mit einem RTL-SDR gehen, da ja das 868MHz Band weit unter der oberen ~2.0GHz Grenzfrequenz des RTL-SDR liegt. Nur bei den 2.4GHz des NRF24 war ein HackRF notwendig.

Ich weiß nicht ob die Schrauben der DTU Pro S irgendwie mit Aufklebern versiegelt sind?

Aber die Testpunkte für TX/RX zwischen STM32 MCU und NRF24 waren bisher klar gekennzeichnet und eine/zwei USB2Serial Converter sind leicht angeschlossen damit kann man die Kommunikation quasi im Klartext mit einem Terminal mitschneiden. HackRF / RTL-SDR zu dekodieren ist da weit komplizierter und vermutlich nicht zwingend notwendig.

**Comment by FFW-Scripter** [comment]
Hier mal etwas Bildmaterial dazu
![photo_2022-11-15_12-01-16](https://user-images.githubusercontent.com/25364347/201909087-61cbc48a-00c9-440c-bd9f-942db8bb5204.jpg)
![photo_2022-11-15_12-01-19](https://user-images.githubusercontent.com/25364347/201909090-fce272e5-2a32-472f-a8cf-8b8ae6fd48b2.jpg)
![photo_2022-11-15_12-08-57](https://user-images.githubusercontent.com/25364347/201909092-be26ee80-4fe4-4e7d-bc59-a112465d4a26.jpg)
![photo_2022-11-15_12-01-21](https://user-images.githubusercontent.com/25364347/201909095-e3822412-5837-45ab-a304-7424f23dfc8c.jpg)
![photo_2022-11-15_12-01-18](https://user-images.githubusercontent.com/25364347/201909099-db8b6aae-6304-4b36-92a8-4d3155b89ccd.jpg)
![photo_2022-11-15_12-01-14](https://user-images.githubusercontent.com/25364347/201909102-fbf122e1-92d1-421a-a946-311ba60783e7.jpg)

**Comment by FFW-Scripter** [comment]
In Bild drei sind recht Eindeutig die Messpunkte für RX/TX sichtbar (FT-TX3/FT-RX3)

**Comment by Argafal** [comment]
@FFW-Scripter Was zeigen denn die Bilder? Eine Hoymiles DTU Pro S von innen, die Version für HMS und HMT? Ist das deiner oder hast du die Bilder irgendwo online gefunden?

Ich hab gerade zwei HMS-2200-4T gekauft und verfolge diesen Issue jetzt auch mit großer Spannung.

**Comment by FFW-Scripter** [comment]
Ja, das ist die DTU Pro S von innen. Mittlerweile hat @lumapu diese und noch eine weitere funktionierende zum mitschneiden.

**Comment by karrenbauer** [comment]
ich habe auch einen HMT-2250-6T und verfolge das Thema mit Spannung....

**Comment by lumapu** [comment]
in Discord sind schon mehr Details bekannt

**Comment by VincentSC** [comment]
Can you share a master-plan on [wiki](https://github.com/lumapu/ahoy/wiki/) once it's shared on Discord? I only see people buy hardware from Amazon, and have no idea if I can help anywhere

**Comment by mbay0r** [comment]
will this also include hms-2000-4T ?

**Comment by Budd1900** [comment]
Hallo, ich verfolge das Thema ebenso mit Spannung und könnte ggf auch aktiv oder auch nur mit ein paar Euro für Kaffee unterstützen. Wie kann ich im Discord beitreten bzw kann mir bitte jemand eine Einladung zukommen lassen? Wie können wir helfen?

**Comment by karrenbauer** [comment]
https://discord.com/channels/984173303147155506/993500210271629393

**Comment by karrenbauer** [comment]
einfach bei discord registrieren:
https://discord.com/channels/984173303147155506/993500210271629393

**Comment by Tobias007** [comment]
Hi, würde gerne bei Discord mitlesen - der Link oben geht allerdings nicht …

**Comment by lumapu** [comment]
@Tobias007  das ist der richtige Link:
https://discord.gg/WzhxEY62mB

**Comment by biasowicka** [comment]
Czy już działa na HMT-2250 ?

**Comment by lumapu** [comment]
@biasowicka can you write in English?

**Comment by FFW-Scripter** [comment]
> Czy już działa na HMT-2250 ?

EN: Not at the moment, @lumapu and others are wirking on it ;-)
PL: W tej chwili nie, @lumapu i inni nad tym pracują ;-)

**Comment by MiniOh** [comment]
Hallo,

gibt es bereits Pläne, wann die HMS Serie supportet werden könnte?

**Comment by PawelSpoon** [comment]
one should first read then buy :)
just received and started my HMT-1800-6T
what a surprise that its not supported yet ?

**Comment by lumapu** [comment]
> Hallo,
> 
> gibt es bereits Pläne, wann die HMS Serie supportet werden könnte?

Ich habe eine ESP32 Version, ich kann sie gerne später als weiteren Branch veröffentlichen. HMS läuft aktuell nur auf dem ESP32 

Bisher habe ich es nicht veröffentlicht, da der ESP8266 aus dem gleichen Code nicht mehr richtig läuft.

**Comment by 0x7878** [comment]
@lumapu würdest du deinen aktuellen Stand Veröffentlichen? Vielleicht kann ich unterstützen für den esp8266.

**Comment by lumapu** [comment]
bitte in #904 schauen, da ist auch schon eine Firmware, ansonsten im Branch `hms`.

**Comment by lumapu** [comment]
wir diskutieren in #904 weiter

**Comment by dnwalker** [comment]
Hallo,

wird auch der HMS-1800-4T unterstützt?

Der HMS-1800 ist ja aufgeführt aber es wäre schön wenn man eine sicherer Bestätigung für den HMS-1800-4T hätte-

Danke und Gruß
Dieter
