### ISSUE TITLE
Visualisierung mal mit Daten mal ohne Version 0.5.16

### ISSUE THREAD

**Issue by stevedee78** [lumapu/ahoy#239]
Hallo, habe gerade die 0.5.16 über die update Funktion eingespielt und ein Problem (siehe Video) fesgestellt. Unteranderem wechselt die Meldung "Inverter #0: HM-400 (v1) is available and is producing" zu "Inverter #0: HM-400 (v1) is available and is not producing" und zurück.

https://user-images.githubusercontent.com/25169154/188318552-4d203a86-9bc3-4aba-a20d-bdd67344a309.mp4

Git SHA: g7f01588

**Comment by Pony1966** [comment]
Beim HM600 auch

**Comment by DennisXK** [comment]
Wie weit ist die DTU vom WR entfernet?

**Comment by Pony1966** [comment]
3 Meter, wie bei der 0.5.15 die ja lief

**Comment by stevedee78** [comment]
> Wie weit ist die DTU vom WR entfernet? 

3-4m. Mit der 0.5.15 gab es keine Probleme.

**Comment by DennisXK** [comment]
Ok, weil mir ist das auch schon aufgefallen. Dachte es liegt an der Entfernung von ca 10m

**Comment by aschiffler** [comment]
Wie oft passiert das hintereinander. Ich vermute nur einmal.
Oder dauerhaft?

**Comment by stevedee78** [comment]
> Wie oft passiert das hintereinander. Ich vermute nur einmal.
> Oder dauerhaft?

Bei mir dauerhaft.

**Comment by Pony1966** [comment]
Dauerhaft , kleinster Intervall ca 7 sec pro Prod oder Prod Not.

**Comment by lumapu** [comment]
auf was steht im Setup die Auswahl für das powerLimit?

**Comment by Pony1966** [comment]
Absolute in Watt non persistent

**Comment by DennisXK** [comment]
Bei mir steht es auf „no power limit“

**Comment by stevedee78** [comment]
> auf was steht im Setup die Auswahl für das powerLimit?

No power limit

**Comment by stefan123t** [comment]
Sieht aus als wäre keine komplette Payload zurückgekommen. Ist aber nur eine Vermutung da dann ja evtl die aktuellen Werte überschrieben oder auf 0 gesetzt werden ?

**Comment by gandalfred** [comment]
Bei mir das gleiche. Wenn ich mehrmals die IP des Ahoy mit 0.5.16 anfrage kommt die verschwundene Anzeige dann wieder, bis sie dann nach weiteren Anfragen abermals wieder verschwindet. Mit 0.5.15 läuft das ohne Probleme.

**Comment by aschiffler** [comment]
Hi,
wurde nun gelöst. Es war ein Fehler im Parser für die einkanaligen WR. Ein Abgleich mit dem Projekt OpenDTU hat dies auch nochmals bestätigt.
Die letzte Alarm Message ID wurde falsch erfasst was dazu führt, dass ahoy "denkt" es liegt ein neuer Alarm vor und ruft diesen ab. Während dieses Abrufs belibt die Web-Anzeige leer. Somit passiert  dies zyklisch wenn der Alarm nicht korrekt gelesen werden kann vom WR.

Bitte nun mit dem dev-build testen.

Siehe:
https://github.com/grindylow/ahoy/commit/03a6b87cc1d889d6082c0b4e088d530f8990f914
