### ISSUE TITLE
Zero export

### ISSUE THREAD

**Issue by erwann56** [lumapu/ahoy#242]
Hello, first of all thank you for your work. I will soon buy a system with HOYMILES micro inverters. With the "horus pro" and a DDSU666, it is possible to configure the "zero export" function in RS485. Does your project allow this function? (If not, possible evolution?)

**Comment by aschiffler** [comment]
Hi,
pls. ask this in the discord discussion forum. Link see the README.md on the first page.

**Comment by erwann56** [comment]
Sorry
