### ISSUE TITLE
Visualization of inverter limit does not work

### ISSUE THREAD

**Issue by mathiaslehmann** [lumapu/ahoy#243]
Hello, thank you for this great project.  Unfortunately, since version 0.5.16, the visualization of the inverter limit no longer works.  100% is always displayed.  The limit is also no longer issued via MQTT.

Many Thanks

**Comment by hubsi5** [comment]
Die Limitierung sollte trotzdem funktionieren.
Anzeige stimmt bei mir auch nicht, aber mein Fall wurde geschlossen, warum auch immer.

**Comment by DirkausHH** [comment]
Mine is always showing 36%, but it's not limiting. 
This last is as it should, as I've set the limit to 100%.

**Comment by mathiaslehmann** [comment]
Yes limitation works.

**Comment by stefan123t** [comment]
See #239 for explanation of issue and solution in 0.5.17
