### ISSUE TITLE
Visualization general issues

### ISSUE THREAD

**Issue by DirkausHH** [lumapu/ahoy#245]
Hi all,

great project, thanks for your effort!
With the 0.5.16 the visualization doesn't work properly anymore, it's only displayed every second update cycle.
The other cycle all fields are blank, with the next update it is shown again...

**Comment by aschiffler** [comment]
Which inverter model?
For eg. HM400 there was a bug.

**Comment by stefan123t** [comment]
Possible duplicate of #243

**Comment by DirkausHH** [comment]
It's an HM-300.
I've updated to 0.5.17, the limit is now shown correctly.
Issue can be closed, I changed the location of my test setup, now it's working. 
No idea why the transmission failed exactly every second time...
