### ISSUE TITLE
DNS issues since v05.15

### ISSUE THREAD

**Issue by fubu2k** [lumapu/ahoy#252]
since v05.15 my PiHole is reporting DNS issues. An unknow (NaN) error ist reported every 5 seconds (see screenshot). 

![2022-08-30 -Pi-hole Unknown NaN Errors](https://user-images.githubusercontent.com/48277447/188561562-eff825cf-a7bf-43bc-9b34-53b5db5cd0cc.png)

**Comment by stefan123t** [comment]
I do see this repeats quite frequently and it may be related to the NTP / MQTT broker name resolution.
Could you try it with a later version 0.5.17 which should have these fixed ?

**Comment by fubu2k** [comment]
hello stefan, i tried version ahoy_v0.5.18_dev_build and the problem still exists.

**Comment by stefan123t** [comment]
Can you try to enable the Debug mode and figure out when/where it is issuing these queries according to the logfiles?
I am familiar with piHole only in principle what are these columns in your screenshot and why is it trying to resolve ahoy-dtu.iot with a lot of extra characters as a DNS name ?
@aschiffler This looks like a MQTT message to me isnt it ?

**Comment by fubu2k** [comment]
ahoy-dtu is the dns name for the controller - setup in the ahoy-gui. 
.iot is the domain, which is pulled to the controller via dhcp server. 
nslookup is resolving the dns name ahoy-dtu.iot successfully, but the unknow "NaN-Error" (not a number) still exists. 

iam trying to debug the pihole dns logfiles

**Comment by aschiffler** [comment]
That's not an issues of ahoy esp8266. I guess that the IP/DNS name of the MQTT broker is not set correct so the DNS query fails.

**Comment by fubu2k** [comment]
after debugging pihole log files in debug-mode dns is running fine. there are no errors in the log files. 
iam not using mqtt broker. the configuration in the setup menu is empty. maybe thats the problem?

**Comment by aschiffler** [comment]
Maybe "empty" is not "nothing". try to re-setup the ahoy by clicking erase-flash.

**Comment by fubu2k** [comment]
i fixed it by using 127.0.0.1 localhost ip for MQTT broker. 
After that i re-setup the ahoy. 
problem is fixed.

seems to be an configuration problem with a firmware update.

thanks :)
