### ISSUE TITLE
Feature Request: Support für MI-300+/MI-600+ & MI-1200+ Gen2 Inverter mit 0x08/0x09, 0x11/0x12 bzw. 0x36..0x39 Kommandos

### ISSUE THREAD

**Issue by stefan123t** [lumapu/ahoy#258]
Die Gen2 MI Inverter verwenden ein anderes Kommando ( 0x08/0x09, 0x11/0x12 bzw. 0x36..0x39 ) um Daten und Events vom Wechselrichter zu bekommen.
Dafür müssen Anpassungen an hmRadio.h und app.cpp vorgenommen werden um diese älteren Wechselrichter der 2ten Generation ebenfalls in AhoyDTU zu unterstützen.

**Comment by stefan123t** [comment]
Die Anfrage Pakete für die Informationen (DevInfo 0x15) werden mit sendTimePacket() erstellt und gesendet und mW in app::loop() der app.cpp in mehreren Paketen empfangen (hier braucht man nur eine Anfrage und es kommen N Antwort-Pakete) und dann die Payload mit processPayload(true) geparst.

https://github.com/grindylow/ahoy/blob/5402e9b0a2cf1c80012dcf62d89179693abc15b5/tools/esp8266/app.cpp#L74-L117

bzw.

https://github.com/grindylow/ahoy/blob/5402e9b0a2cf1c80012dcf62d89179693abc15b5/tools/esp8266/app.cpp#L155-L158

**Comment by aschiffler** [comment]
So ist es. Wobei das Verarbeiten der Antwort auch für nur ein Antwort Frame jetzt schon funktioniert. So wie andere "HM" Kommandos ja auch nur ein Antwort Frame haben können.

**Comment by rejoe2** [comment]
Achtung: Auf eine 0x09-Anfrage kommen ZWEI Antworten, es gibt keine separate Anfrage für0x88, und entsprechen kommen auf 0x11 dann 0x91 und 0x92 als Antwort.
Die "paarigen" Antworten liegen aber auf unterschiedlichen Kanälen.

Für die "kleinen" MI muss 0x09/0x11 gesendet werden (0x11, wenn 2 Kanäle da sind, die Typenerkennung habe ich in https://github.com/rejoe2/DTUsimMI/commit/cd557983d62213ed32ba590cd46ab78448ff5381#diff-94d7139c243e60bc36e646e935751a20b26a4e8041bdd4376f93373686788f52 integriert - mit der Sonderlocke, dass man weniger Eingänge setzen kann).

Ob das "Einpacken" irgendwie anders ist, weiß ich nicht, aber wenn jemand erst mal die in den "ahoy-Code" testweise integrieren könnte, kann ich ja mit dem 2. als Sniffer schauen, ob was zurückkommt?

Im Empfang ist bei denen zum einen eine kleine Ausnahme bei den "Wertemessages" (+80) zu beachten

siehe vielleicht am direktesten: 
https://github.com/rejoe2/DTUsimMI/blob/rejoe2-backhop-1/NRF24_SendRcvMIesp/NRF24_SendRcvMIesp.ino#L771-L780
```c
  VALUES[PV][0]=PV;
  VALUES[PV][1]=P_DC;
  VALUES[PV][2]=U_DC;
  VALUES[PV][3]=I_DC;
  VALUES[PV][4]=Q_DC;
  if (MI1500) {
  VALUES[PV][5]=STAT;
  VALUES[PV][6]=FCNT;
  VALUES[PV][7]=FCODE;
  }
```

Diese drei Werte kommen dann bei diesen Modellen aus den Status-Messages (0x09=>0x88, 0x11=>0x92), die in MI600DataMsg() ausgewertet werden:

https://github.com/rejoe2/DTUsimMI/blob/rejoe2-backhop-1/NRF24_SendRcvMIesp/NRF24_SendRcvMIesp.ino#L797-L820
```c
void MI600StsMsg (NRF24_packet_t *p){
  //-----------------------------------------------------------------------
  STAT = (int)((p->packet[11] << 8) + p->packet[12]);
  FCNT = (int)((p->packet[13] << 8) + p->packet[14]);
  FCODE = (int)((p->packet[15] << 8) + p->packet[16]);

  VALUES[PV][5]=STAT;
  VALUES[PV][6]=FCNT;
  VALUES[PV][7]=FCODE;
  /*if (waitSts) {
    RcvCH = channels[hoptx];
    radio1.setChannel(RcvCH);//setChannel(DEFAULT_RECV_CHANNEL);
    radio1.startListening();
    waitSts=0;
    rfQualOk = true;            //we got an answer - most likely within a reasonable time!
    tickMillis = millis() + tickDuration;
  }
  */
  if (p->packet[2] == 0x88)  {stsmsg[0]=1;}//port 1
  if (p->packet[2] == 0x92)  {stsmsg[1]=1;}//port 2
  sprintf(cStr," CH:%2i: MI300/MI600 status message",
  RcvCH);
  DEBUG_OUT.print(millis()); DEBUG_OUT.println(cStr);
}//--MI600StsMsg---------------------------------------------------------------------
```

**Comment by stefan123t** [comment]
@rejoe2 
die Modelle werden im AhoyDTU in hmSystem.h ausgewertet und anhand der IDs unterschieden:
https://github.com/grindylow/ahoy/blob/348ad4bd07ddde67cd017547b2afcafa486f2b09/tools/esp8266/hmSystem.h#L48-L57

Da sollte also noch ein switch in Zeile 48 mit 0x11 und 0x10 für die MI-Systeme.

**Comment by rejoe2** [comment]
Da hatte ich es geklaut und in die setup() wie folgt integriert:
````
uint64_t sn = SerialWR;
  longlongasbytes llsn;
  llsn.ull = sn;
  if(llsn.bytes[5] == 0x10) {
  switch(llsn.bytes[4]) {
    case 0x21: 
        { MI300 = 1; MI600 = 0; MI1500 = 0; 
        if (NRofPV==0) { NRofPV = 1; } 
        break; }
    case 0x41: 
        { MI600 = 1; MI300 = 0; MI1500 = 0; 
        if (NRofPV==0) { NRofPV = 2; } 
        break; }
    case 0x61: 
        { MI1500 = 1; MI600 = 0; MI300 = 0; 
        if (NRofPV==0) { NRofPV = 4; }
        break; }
  }
  MAXPOWER = NRofPV * PVPOWER;   
  MINPOWER = int(MAXPOWER / 10);
  }
  ````

**Comment by stefan123t** [comment]
@lumapu Vielleicht INV_TYPE_1CH in HM_TYPE_1CH bzw. MI_TYPE_1CH unterscheiden oder fällt uns das dann bei der Darstellung wieder auf die Füße ?

Aber besser wäre es wahrscheinlich ein p->gen = INV_GEN2_MI bzw. INV_GEN3_HM einzuführen ?
Dann kann man weiterhin die Darstellung mit INV_TYPE_XCH machen und an anderer Stelle (Senden & Payload Parser) einfach auf die INV_GEN2_MI / INV_GEN3_HM zugreifen.

**Comment by lumapu** [comment]
umbenennen geht immer, beide Varianten funktionieren. Die Erfahrung zeigt, dass man erst beim implementieren feststellt, welche besser / sauberer ist

**Comment by Ziyatoe** [comment]
> Aber besser wäre es wahrscheinlich ein p->gen = INV_GEN2_MI bzw. INV_GEN3_HM einzuführen ? Dann kann man weiterhin die Darstellung mit INV_TYPE_XCH machen und an anderer Stelle (Senden & Payload Parser) einfach auf die INV_GEN2_MI / INV_GEN3_HM zugreifen.

man muss ja beim rx-parsen auch unterscheiden können, darum braucht es INV_GEN2_MI oder?

**Comment by stefan123t** [comment]
@Ziyatoe wie heute im Discord #ahoy-esp8266 besprochen wäre es notwendig bei den Kommandos zwischen Gen2 und Gen3 zu unterscheiden.
* Gen2 : ein oder mehrere Cmd Request Paket(e) und je ein Cmd Response Paket. Keine Paket ID
* Gen3 : ein Cmd Request Paket und ein oder mehrere Cmd Response Pakete mit Paket ID.

Die Daten gehen dann evtl. auch über verschiedene Backends nrf24Radio.h bzw. cc1101Radio.h an die Wechselrichter raus.
