### ISSUE TITLE
Feature Request / Enhancment: display WIFI RSSI and RSSI to Inverter and send values via MQTT

### ISSUE THREAD

**Issue by andi-bar157** [lumapu/ahoy#260]
For trouble shooting and informative purposes it would be good if the signal strength of the wlan as well as the signal strength in the direction of the inverter would be displayed on the gui and could also be transmitted via MQTT.

Thank you for this awesome project and support.

**Comment by stefan123t** [comment]
@andi-bar157 there are two requests in this issue:

1. the RSSI for individual SSIDs
* this could be easily solved by adding an MQTT topic showing the current RSSI for the SSID which is  configured in setup.
* optional this would show a list of SSID ordered by RSSI in the setup UI to choose from in both AP  and STA mode.

2. the RSSI for the individual inverters can not be given. Though there are some similar values:
* start a AhoyDTU statistic counting the packets received per inverter and each of the five TX/RX channel combinations. This could greatly enhance our channel hopping algorithm for both TX and RX channels !
* there is a DevInfo Sub command to query the inverter for its RX/TX statistics: using MainCmd REQ_ARW_DAT_ALL 0x15 SubCmd GetLossRate 0x15. See #145 and Wiki https://github.com/stefan123t/ahoy/wiki/FAQ-Frequently-Asked-Questions#getlossrate--0x15
* nRF24 can yield a value for each target being above/below the RSSI threshold of 60/64dBm (value depending on source)

**Comment by DanielR92** [comment]
WiFi RSSI is now added in the version 0.5.18 - branch dev03
RSSI for inverter need some time to implement...
