### ISSUE TITLE
WR Status per MQTT

### ISSUE THREAD

**Issue by Sascha79** [lumapu/ahoy#268]
Hallo zusammen und danke an alle Beteiligten für die tolle Arbeit. 

Wäre es möglich, den WR Status

- is available and is producing
- is available and is not producing
- is not available

per MQTT zu senden? Oder wenigstens eine entsprechende ID.

**Comment by lumapu** [comment]
gute Idee, macht Sinn

**Comment by c1328** [comment]
Vielleicht lässt sich das leicht damit kombinieren, dass die Meldungen vom WR auch gleich in "sprechender" Form über MQTT ausgegeben werden, dann spare ich mir das Mapping im Grafana Dashboard (wo ich es für einige Codes inzwischen aber hinterlegt habe).

**Comment by lumapu** [comment]
man kann ja beides Senden, eine ID und in ausgeschriebener Form

**Comment by SandnerSoft** [comment]
https://github.com/lumapu/ahoy/pull/289
ist da enthalten, bitte prüfen und übernehmen
