### ISSUE TITLE
Powerlimit lässt sich nur via MQTT Befehl ändern

### ISSUE THREAD

**Issue by ambivalent11** [lumapu/ahoy#280]
_Man sagte mir, ich solle ein Issue zu meinem nun gelösten Problem anlegen._

In Version 0.5.17 war es nicht möglich via Setup das Powerlimit zu setzen. 
Dies war erst mit dem MQTT Befehl möglich.

Board: ESP8266
WR: 2x HM-1500

**Comment by DanielR92** [comment]
Kann ich teils bestätigen. 

Ich nutze Branch AsyncWebserver 0.5.18, dabei ist mir aufgefallen das die Werte erst übernommen werden, wenn man es mehrmals "überschreibt" oder statt persistent auf temp. setzt.

Hier müsste man nochmals verfolgen, ob die Befehle korrekt abgesendet werden.

**Comment by stefan123t** [comment]
Eventuell durch #278 bereits in AsyncWeb03 gelöst ?

**Comment by lumapu** [comment]
@DanielR92 sollte sich auch erledigt haben denke ich. Close?
