### ISSUE TITLE
Feature Request: Loginscreen

### ISSUE THREAD

**Issue by ambivalent11** [lumapu/ahoy#281]
Da ich ab und an via DNS auf den AHOY zugreife, wäre es möglich eine Loginmaske zu integrieren?

Ist sicherlich für andere ebenfalls interessant?

**Comment by hubsi5** [comment]
Warum nicht per VPN? Ist ja sicherer

**Comment by stefan123t** [comment]
Eventuell sinnvoll hierfür dasselbe Password wie beim AP zu verwenden. Dann muss man ggf nur noch ein Input Feld im Setup hinzufügen.

**Comment by lumapu** [comment]
ich rate dringend ab so einen Dienst ohne VPN öffentlich ins Netz zu stellen. Auch ein mögliches Passwort schützt hier aus meiner Sicht nicht ausreichend.
Ich finde die Idee generell gut, um im internen Netz die Konfiguration vor dritten zu schützen, wie zB bei einer Fritzbox

**Comment by DanielR92** [comment]
Hallo zusammen,

ich bin dabei den Login Screen zu implementieren. Es funktioniert schonmal, nur das Abmelden geht noch nicht. 
https://github.com/DanielR92/ahoy/commit/c1ea32472c9e3a9367833438254d50dcb7acd025 -> dont use it anymore!

Neuer Branch wurde erzeugt, damit es besser getraced werden kann.

Ich schaue später mal drüber... könnt gern was dazu schreiben. :)

**Comment by lumapu** [comment]
@DanielR92 wie ist dein Fortschritt? Kann man unterstützen?

**Comment by stupsi099** [comment]
ein Passwort wäre eine super Idee. Idealerweise für alles außer LIVE. Ein eigenes wäre sinnvoll da viele ein X-stellige Zahlenkombination beim Wlan haben.

**Comment by lumapu** [comment]
natürlich ein eigenes, die Live Übersicht auszunehmen fine ich eine gute Idee, evtl optional

**Comment by lumapu** [comment]
@ambivalent11 es gibt eine development Version, die eine Loginmaske hat
