### ISSUE TITLE
System Config Display für ESP32

### ISSUE THREAD

**Issue by andreash-esp** [lumapu/ahoy#286]
System Config zeigt auch beim ESP32 die Bezeichnungen des WEMOS an:

![ahoy](https://user-images.githubusercontent.com/65556586/190855871-4910b51c-b232-4dd6-ac68-d3d2622894ae.PNG)

Die "no IRQ" Meldung dürfte für den ESP32 nicht relevant sein, da alle GPIO IRQ-fähig sind.

**Comment by lumapu** [comment]
sehr gut es hier festzuhalten, wir werden es implementieren

**Comment by DanielR92** [comment]
Ganz kurz, was soll hier bitte geändert werden, dann könnte ich es in die Hand nehmen. :)

**Comment by lumapu** [comment]
die Namen und Anzahl der GPIOs sowie der Hinweis no IRQ stimmen nur für ESP8266.
Danke schonmal.

**Comment by Schorsch980** [comment]
mein Issue passt hier denke ich thematisch hin: Ist es bei der Gelegenheit möglich, die Liste der auswählbaren IRQs für ESP32 >16 zu erweitern? Problem ist, ich nutze hierfür ein Mini D1 ESP32, dass den gleichen Formfaktor wie D1 Mini (8266) hat - denn ich möchte das gelötete Shield einfach umsetzen. Bei dem Board entspricht D3 = IO17 und da komme ich in der Auswahl nicht dran, weil sie bei IO16 endet. Alle anderen (relevanten) Pins stimmen...
![D1 Mini ESP32 ESP8266](https://user-images.githubusercontent.com/67590334/192138892-1f0b4c3a-e4f9-41b7-aa20-7c52e9aea751.jpg)

**Comment by stefan123t** [comment]
Für den ESP32 build gibt es bis zu GPIO39 wobei GPIO34..39 nur als Input dienen.
Auch einige andere fallen vermutlich aus wegen pullups, etc

Siehe eine Liste hier:

https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

**Comment by Albert2222222** [comment]
> mein Issue passt hier denke ich thematisch hin: Ist es bei der Gelegenheit möglich, die Liste der auswählbaren IRQs für ESP32 >16 zu erweitern? Problem ist, ich nutze hierfür ein Mini D1 ESP32, dass den gleichen Formfaktor wie D1 Mini (8266) hat - denn ich möchte das gelötete Shield einfach umsetzen. Bei dem Board entspricht D3 = IO17 und da komme ich in der Auswahl nicht dran, weil sie bei IO16 endet. Alle anderen (relevanten) Pins stimmen... ![D1 Mini ESP32 ESP8266]

Habe exakt das gleiche Problem, IO17 benötigt für den ESP32 mini!

**Comment by Albert2222222** [comment]
Danke daß Du Dich dem angenommen hast @lumapu !

Im akt. Devbuild ist mir nur aufgefallen daß die IOs alle mit "Dxx" bezeichnet sind - müssten die beim ESP32 nicht eigentlich alle "GPIOxx" heißen?

**Comment by lumapu** [comment]
das weiß ich auch nicht, aber auf der 'Standard' ESP32 Platine sind die wohl aufgedruckt.
Wobei ich weiß nicht welche die Standard Platine ist.

**Comment by Albert2222222** [comment]
![esp32-devkitC-v4-pinout](https://user-images.githubusercontent.com/104326198/197011078-0db3cf1b-c2fe-45b7-9eaf-24c79ba67a0a.png)

Hier das offizielle Pinout Bild von Espressif, Quelle: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/get-started-devkitc.html

GPIOxx sind die offiziellen Bezeichnungen.

**Comment by lumapu** [comment]
@andreash-esp bitte mit aktuellem Dev Branch nochmal testen

**Comment by Albert2222222** [comment]
Eben mit der 0.5.23 getestet, Zuordnung funktioniert jetzt einwandfrei auf einem ESP32 mini! Danke !!

**Comment by mattmeye** [comment]
@Schorsch980 Darf ich fragen, wie du die restlichen Pins sind?

   NRF 	ESP32
   CS	        05
  MOSI	23
  MISO	19
   SCK	18
    CE	16
   IRQ	17
   
   ? Habe ein ähnliche Board und leider keine Connection zum NRF

**Comment by Schorsch980** [comment]
@mattmeye nach Anleitung müsste es funktionieren, ich bin damals allerdings zu OpenDTU gewechselt, daher hier keine praktische Erfahrung.
