### ISSUE TITLE
Feature Request: Inverter ein-/ausschalten via MQTT

### ISSUE THREAD

**Issue by ntfrnd** [lumapu/ahoy#302]
Hallo,

im Manual gibt es ein Beispiel um mittels MQTT den Inverter ein- bzw. auszuschalten.

"So as example sending any payload on inverter/devcontrol/0/1 will switch off the inverter."

Aufgrund der Liste:
![image](https://user-images.githubusercontent.com/99898355/191947504-0e241b20-352c-4f33-8cb0-ce4360396d6f.png)

und des Beispiels gehe ich davon aus, dass mittels MQTT-Message an 
inverter/devcontrol/0/1 der Inverter AUS
inverter/devcontrol/0/0 der Inverter EIN
geschaltet werden kann.

Ich habe -analog zum ActivePowerControl- die beiden Variablen händisch angelegt. 
Sende ich nun z.B. 
    `setState("mqtt.0.inverter.devcontrol.0.1", '1')`
sehe ich dies zwar in der MQTT-Objektansicht und auch im MQTT-Explorer (zur Kontrolle), aber den Inverter interessiert das irgendwie nicht.

Hab ich einen Denkfehler oder irgendwas vergessen?

![image](https://user-images.githubusercontent.com/99898355/191947357-a4f78670-b320-43d0-9760-6b8765984f73.png)

**Comment by stefan123t** [comment]
Steht das evtl noch nicht im User Manual ?

https://github.com/lumapu/ahoy/blob/main/tools/esp8266/User_Manual.md

**Comment by ntfrnd** [comment]
Dort habe ich es gelesen, aber entweder habe ich es nicht verstanden oder es funktioniert so nicht. Deshalb die Nachfrage...

**Comment by lumapu** [comment]
welche Version ist im Einsatz? Es kann sein, das es in der development Version nicht funktioniert

**Comment by ntfrnd** [comment]
0.5.17 (main) am 09.09. kompiliert und seitdem im Einsatz.

**Comment by lumapu** [comment]
@DanielR92 habt ihr buttons mal getestet unter der Webserial?
Sollte ja prinzipiell funktionieren.

Edit: sorry hab gesehen, dass es um MQTT und nicht JSON geht

**Comment by stefan123t** [comment]
@ntfrnd ist das Feature über MQTT noch notwendig oder reicht die Option über die JSON API `/api` ?

**Comment by ntfrnd** [comment]
Ich arbeite nur mit den MQTT-Objekten, von daher würde ich es mir wünschen 😀

**Comment by DanielR92** [comment]
Hallo zusammen,

folgendes habe ich getestet (ESP32, v0.5.39):
@lumapu: Serial Console: Turn On + Turn Off => Check, funktioniert.

**Comment by stefan123t** [comment]
@DanielR92 das war jetzt der Test dass die JSON API funktioniert. Danke!
Jetzt müsste man sich ansehen ob/wie der MQTT Callback funktioniert. Irgendwie muss er ja auch das Topic vom MQTT Broker lesen, dann das entsprechende Kommando ansetzen und vermutlich das MQTT Topic zurück setzen ?
Das hatte mW seinerzeit noch @aschiffler implementiert. Vielleicht kann er ja nochmal in den Code schauen ?

**Comment by lumapu** [comment]
am besten testen und gleich gut dokumentieren.

**Comment by lumapu** [comment]
mit der aktuellen Dev Version sollte das jetzt funktionieren
https://github.com/lumapu/ahoy/blob/development03/User_Manual.md

**Comment by stefan123t** [comment]
@ntfrnd kannst Du das neue Feature mit der Version 0.5.44 testen ?
