### ISSUE TITLE
MQTT Message fehlerhaft, bei mehr als 1 WR

### ISSUE THREAD

**Issue by SandnerSoft** [lumapu/ahoy#306]
Ich habe 3 WR laufen. 
Bei den MQTT Messages YieldDay / YieldTotal wechseln die Werte alle WR immer durch, sieht man hier gut im Bild.
![unknown](https://user-images.githubusercontent.com/10620782/192094632-af1720fe-f0d5-4f69-828c-0271eac53a82.png)

Außerdem stimmen dadurch die Werte im Topic "total" auch nicht:
![image](https://user-images.githubusercontent.com/10620782/192094730-fbc4a476-6ebe-461a-9e2c-e643ebef0747.png)

Nutze den development03 Branch und der Fehler ist am ESP32 genauso wie am ESP8266

**Comment by stefan123t** [comment]
@SandnerSoft machst Du selbst einen PR für die Korrektur ?
Ich vermute es liegt daran, dass er aktuell einige Daten unter das globale Topic schreibt die eigentlich pro Inverter sind.

**Comment by SandnerSoft** [comment]
> @SandnerSoft machst Du selbst einen PR für die Korrektur ? Ich vermute es liegt daran, dass er aktuell einige Daten unter das globale Topic schreibt die eigentlich pro Inverter sind.

ich schau mir das nochmal an, aber bisher konnte ich den Fehler nicht lokalisieren.
Ich probiere mal alle globalen Topics auszublenden.

**Comment by SandnerSoft** [comment]
So die Fehler im ersten Bild konnte ich auflösen.
Hier war ein verschachtelter for Loop drin, der 2x über alle WR geht. Deshalb wurden bei jedem richtigen Payload von einem WR, die Daten der anderen WR überschrieben.

Das zweite Bild mit den Total Werten ist etwas komplizierter.
Diese Werte dürfen nur gesendet werden, wenn die Payloads aller WR korrekt sind.
Das bekomme ich gerade noch nicht gelöst.

**Comment by stefan123t** [comment]
Man bräuchte also für die Total Werte ein Valid Flag pro WR. 
Diese Valid Flags werden dann beim Berechnen des Total Wertes vorher geprüft und anschließend zurückgesetzt ?

**Comment by SandnerSoft** [comment]
Ja genau! 
Irgendwie sowas muss an dieser Stelle eingebaut werden, ansonsten hat man nie alle WR zusammen in den Total Werten.

**Comment by Chrischi-** [comment]
Gibt es hierzu schon einen PR?

**Comment by lumapu** [comment]
@stefan123t: warum zurücksetzen? Ich glaube sobald man weiß, dass die Payload korrekt ist kann man doch immer wieder die Summe schicken. Sobald mal ein WR keinen Empfang hat muss man das valid-Flag wieder zurücksetzen.

**Comment by lumapu** [comment]
@SandnerSoft bitte nochmal mit dem aktuellen Release 0.5.28 testen, MQTT würde in diesem Bereich umgebaut / gefixt

**Comment by SandnerSoft** [comment]
ja passt jetzt, vielen Dank
