### ISSUE TITLE
PowerLimit in setup UI does work in 0.5.14 only

### ISSUE THREAD

**Issue by stefan123t** [lumapu/ahoy#307]
According to out #support channel users have to downgrade via OTA to version 0.5.14 in order to set the powerlimit back to 100% permanent.
The 0.5.14 bin file can be found here: 
https://filehorst.de/d/euEepgdC

**Comment by stefan123t** [comment]
To reset flash the bin file to your ESP via OTA and select the following:

ActivePowerLimit: 100
ActivePowerLimit ControlType: relative in percent persistent
[x] reboot after save
Save

**Comment by lumapu** [comment]
@stefan123t das geht doch mit den aktuellen development vertreiben wieder, ist jetzt unter Serial Console

**Comment by stefan123t** [comment]
Ja aber in unserem Main release ist es mW noch broken oder hast Du schon wieder mal ein Release gebaut bei dem das behoben ist ?
Die Development Version zu verwenden ist allerdings eine Option anstelle des Downgrades.
