### ISSUE TITLE
Status LEDs

### ISSUE THREAD

**Issue by Pony1966** [lumapu/ahoy#318]
Wäre es möglich bei Mqtt verbunden und bei Wechselrichter Produziert einen GPIO am ESP 8266 zu schalten.
Möchte am GPIO jeweils eine Status LED anschließen.
Das Gehäuse ist soweit Entwickelt und befindet sich im Druck.

**Comment by DanielR92** [comment]
Ja das wäre möglich. 
Jedoch ist die Prio dazu nicht so hoch. 

Ich werde es mir mal später anschauen und das ganze evtl. implementieren.

**Comment by knickohr** [comment]
Ist der Ausgang High oder Low wenn die LED an ist ?  Funktioniert das auch mit dem ESP32 ?

**Comment by lumapu** [comment]
low aktiv, auf dem ESP32 habe ich es nicht getestet
