### ISSUE TITLE
GetLossRate 0x15 and/or 1-Bit RSSI (RPD) aka “poor man's RSSI” for NRF24L01+

### ISSUE THREAD

**Issue by Chrischi-** [lumapu/ahoy#320]
As you know, the NRF24L01+ does not have an RSSI module like the nRF5 series. 
However, the NRF24L01+ has a type of 1-bit RSSI.

Received Power Detector (see screenshot)
![rpd](https://user-images.githubusercontent.com/6323217/193446418-e42b8ae9-2c78-4546-8441-1c57db27befb.png)

Wouldn't it make sense to display at least this information in the web interface so that you know that you have 
an RSSI of above or below -64dBm? 

Maybe we could use a simple green (better than -64dBm) or orange (worse than -64dBm) icon or colored character.

This could certainly be helpful when choosing a location for ahoy.

**Comment by stefan123t** [comment]
M.E. würde es mehr Sinn machen das [GetLossRate](https://github.com/lumapu/ahoy/wiki/Protocol#getlossrate--0x15) `0x15` Kommando zu implementieren.

**Comment by stefan123t** [comment]
Siehe #304
