### ISSUE TITLE
Connection over WLAN to AHOY-DTU as access point don´t accept the password (default) - on MAC systems or IPhone

### ISSUE THREAD

**Issue by Hertiwolfi** [lumapu/ahoy#331]
Hi,

i would like to support your project...after flashing with newest fw i can´t access to access point over wlan to the DTU..seems the password is not accepted - have you got any hints ?

Best regards

Michael

**Comment by DanielR92** [comment]
Do you try to connect with your Smartphone with the following data:

WiFiName    AHOY-DTU
Password     esp_8266

**Comment by Hertiwolfi** [comment]
> Do you try to connect with your Smartphone with the following data:
> 
> WiFiName AHOY-DTU Password esp_8266

Hi Daniel,

yes i tried on my MAC and IPhone - same issue...

**Comment by Hertiwolfi** [comment]
Just a little update - on my windows PC i can connect correctly - but why not over my MAC oder Iphone ?

**Comment by Hertiwolfi** [comment]
HI all - seems it´s not a problem with Ahoy project itself - i think this issue can be closed
