### ISSUE TITLE
Feature Request : "Receive fail" verbessern

### ISSUE THREAD

**Issue by ntfrnd** [lumapu/ahoy#332]
Aktuell ist es wohl so, dass der "receive fail"-Zähler bei der Statistics-Anzeige hoch zählt, wenn die Antwort nicht in Ordnung ist. Dabei spielt es offenbar keine Rolle, ob die Antwort fehlerhaft ist oder gar keine Antwort kommt (z.B. nach Sonnenuntergang). Da steigt die "receive fail"-Anzeige enorm schnell an.
Daher ist diese Info m.E. wenig hilfreich.

Besser wäre es doch, den "receive fail"-Zähler tatsächlich nur für fehlerhafte Antworten zu verwenden und zusätzlich einen Zähler für "receive no answer" einzuführen. Der würde dann über Nacht oder wenn sich der Inverter außerhalb der Reichweite befindet, hochzählen.

Im Gegensatz dazu könnte man  den "receive fail" nach einigen Tagen prüfen, ob die Kommunikation sauber verläuft.

Ich würde mich freuen, wenn mein Wunsch umgesetzt werden würde.

**Comment by homeautomation2022** [comment]
In der Nacht kein Funkverkehr ist bereits in Arbeit. Die Funktion dazu habe ich schon fertig und im Discord als Patch geteilt, fehlt nur noch jemand der Lust auf das Programmieren des Webinterfaces und EEPROM hat, für die Koordinaten und zum deaktivieren der Funktion für Akkubetrieb.

**Comment by lumapu** [comment]
trotzdem wird es Überschneidungen geben und der receive fail hochzählen.
Daher finde ich die Idee von @ntfrnd zwei separate Zähler zu haben sehr gut.

**Comment by homeautomation2022** [comment]
Das stimmt, ganz perfekt wird man Sonnenauf- und untergang nicht treffen, dennoch muss er Nachts nicht permanent versuchen den HM zu erreichen.
Du meinst also nur die fehlerhaften(unvollständig oder falsche CRC) RX Pakete zählen und nicht die Retransmitts, auf denen keine Antwort kommt, weil HM vermutlich aus oder gar nicht erreichbar, macht Sinn.

**Comment by ntfrnd** [comment]
Nur zwischen Sonnenauf- und -untergang zu senden ist auch ne gute Idee.
Darüber hinaus die Antworten aufteilen in 1) keine Antwort und 2) Antwort mit CRC-Error wäre doch perfekt, oder?

**Comment by deep470** [comment]
Ahoy zeigt ja schon den Zeitpunkt der letzten erfolgreichen Verbindung an. Den keine Antwort-Zähler könnte man automatisch leeren wenn wieder eine erfolgreiche Verbindung stattgefunden hat. Oder nach 5 Minuten stabiler Verbindung.

**Comment by homeautomation2022** [comment]
Ich versuche gerade herauszufinden, was nachts überhaupt passiert und habe einfach mal eine falsche SN konfiguriert:
Tx kommt, Rx nichts aber es zählt auch wie gewollt kein Rx failed hoch. Vielleicht muss aber auch einmal die Verbindung da gewesen sein???
EDIT: Ja, einmal muss Verbindung da gewesen sein, erst dann zählt er hoch und Retransmittet.
Prinzipiell ist es ja nicht falsch bei keiner Antwort hochzuzählen, aber leider ist das halt auch nachts der Fall, tagsüber muss er immer Antworten, ansonsten liegt es an der Verbindung, was wir ja sehen möchten.

**Comment by ntfrnd** [comment]
Aktuell sieht es so aus:
![image](https://user-images.githubusercontent.com/99898355/194526551-94c299a2-90f3-4bba-95a3-aa71a462b14d.png)

Also bei mir zählt der receive-fail-Zähler munter hoch, wenn die Sonne weg ist.
Bis morgen früh sinds tausende fails....

Ich gebe dir Recht, prinzipiell kann er das zählen. Aber für mich macht es einen Unterschied ob er nicht oder fehlerhaft geantwortet hat. Deshalb der Wunsch nach zwei Zählern.

**Comment by homeautomation2022** [comment]
Ja, sehe ich ähnlich, man sollte die ohne Antwort nicht ganz untergehen lassen, aber extra Zählen bei wie vielen denn eine Antwort kam, aber diese Feher enthielt woraufhin nochmal die Daten abgerufen werden mussten.
Die Frage wäre dann nur noch zählt man je CMD(kann bis zu 5 Retransmitversuche enthalten, dies ist auch auf mehr oder weniger konfigurierbar im Setup) oder je einzelnen Retransmit, denn zu denen dürfte es gar nicht kommen, wenn die Verbindung perfekt ist.
