### ISSUE TITLE
Feature Request: Manuelle Zeit einstellen

### ISSUE THREAD

**Issue by fila612** [lumapu/ahoy#336]
Hallo,

ich hatte letztens einen längeren Internetausfall (über 24h). Leider habe ich so erst gemerkt, dass ohne aktuelle Zeit ahoy keine Daten abrufen kann.
Da ich keine Möglichkeit gesehen habe die Zeit auch manuell zu setzen, wäre meine Frage ob dies noch in zukünftigen Releases eine Variante sein kann.
Sollte aus meiner Sicht im Setup neben dem NTP nur die Möglichkeit sein die Zeit manuell zu setzen.

**Comment by DanielR92** [comment]
Ja könnte man mal einkippen. Die Zeit könnte man aber zur Not via Fritbox bekommen, oder einmalig beim Setup über den PC wenn man darauf zugreift. 

var today = new Date();
var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();

Wäre eine möglichkeit... dies müsste jedoch einmalig passieren.

**Comment by fila612** [comment]
Bzgl Zeit vom Router: dachte ich auch, aber ohne Netz ist der auch ohne Zeit :(

**Comment by stefan123t** [comment]
Man könnte auch den Zeitstempel vom Client-Browser übernehmen, der wird ja in der Regel im Request-Header übergeben.
Ich glaube Thomas macht das in OpenDTU auch so mit dem SYNC Button oder wird da immer der NTP request getriggert ?
Sonst könnte man das ja als Fallback machen:
1. NTP versuchen.
2. Zeit aus dem HTTP Request-Header vom Client übernehmen.

3. Alternativ ein paar Input Felder für Datum, Uhrzeit und ggf. Zeitzone damit man es ggf. wirklich manuell eintragen kann.
@DanielR92 ich habe keine Ahnung wie man das macht, daß es auf dem Mobiltelefon sinnvoll auswählbar ist ?

**Comment by lumapu** [comment]
@fila612 bitte mit dem neuesten Dev-Build nochmal probieren, ich habe zwei Buttons eingebaut.
**Achtung** das EEprom Layout hat sich geändert, daher gehen bis auf WiFi alle Settings verloren.
Wenn alles passt den Issue bitte closen.

_Hinweis: Die Zeitzone wird vom Browser nicht beachtet - das wäre eine Änderung in JavaScript, da habe ich mich nicht weiter damit befasst. Daher stimmt dann die Zeit um 2 Stunden nicht._

**Comment by fila612** [comment]
Danke dir @lumapu ! :)
Habs grad aktualisiert und sieht gut aus, ich mach hier zu, sollte es zu Fehlern kommen, mach ich ein neues Issue auf.

**Comment by DanielR92** [comment]
Die Zeitzone mittels JS kann man mit folgenden Befehl grabben: 

```
var offset = new Date().getTimezoneOffset();
console.log(offset);
// if offset equals -60 then the time zone offset is UTC+01
```
https://stackoverflow.com/questions/1091372/getting-the-clients-time-zone-and-offset-in-javascript

**Comment by stefan123t** [comment]
Es gab Abfragen wie man AhoyDTU Off-Grid bzw Off-Network betreibt ? Hier wäre es sinnvoll dass der WR den Zeitstempel zumindest bei jedem speichern des Setups mit in die JSON Config schreibt. Noch besser wäre natürlich die Anbindung von nem RTC Modul ?

**Comment by DB1BMN** [comment]
Hi, sorry fürs Kapern... möchte es nur verstehen.

Für was genau benötigt es denn überhaupt die exakte Zeit/Datum?
OK, Sonnenauf- und Untergang, aber sonst?

Da es ja aktuell schon eine gute Unterstützung für die Displays gibt, kommt auch immer mehr ein Stand-Allone-Betrieb in Betracht, d.h. ohne externes WLAN/Internet.

Ergo: Modul per USB-Versorgen, per eigenem Access-Point die Seriennummer des Wechselrichters konfigurieren, Display einrichten, evtl. Default-Passwort ändern und so stehen lassen und sich an den Display-Daten erfreuen.

OK, falls der WR Datum/Uhrzeit braucht, damit er weiß, wann "today" ist, dann müsste man das evtl. manuell einstellen können. Den Button "Sync from Browser" gibts ja schon.
Bei Stromausfall müsste  man dann doch wieder noch eine (batteriegepufferte) RTC haben...

Edit:

P.S. Grad mal was ausprobiert (V. 0.6.12). Solange die Zeit nicht eingestellt wurde, bleibt der Splash-Screen stehen nach dem Booten. evtl. einen Hinweis "Waitng for Time/Data" nachpflegen oder?

Beste Grüße, Mar(e)k

**Comment by lumapu** [comment]
Man braucht es, für die Alarmmessages des Wechselrichters. Diese kommen mit der Zeit zurück, zu der sie aufgetreten sind. Bisher ist es nicht bekannt was mit dem YieldDay / YieldTotal passiert, wenn eine falsche Zeit verwendet wird.

**Comment by DB1BMN** [comment]
Danke für die Info!
Jetzt habe ich es verstanden.
Habe auch in der seriellen Konsole gesehen, dass beim Senden ganz viele Nullen gesendet werden, solange die Uhrzeit nicht gesetzt und erst dann durch irgendwelche Hex-Werte ersetzt werden.
Damit komme ich erst mal klar ;-)
