### ISSUE TITLE
Bugs in Setup Seite (development Branch)

### ISSUE THREAD

**Issue by homeautomation2022** [lumapu/ahoy#337]
1. Module Name auf 4 Zeichen begrenzt
2. Max Module Power (Wp) und Modulname Eingabefeld nach erstmaligen Speichern bzw. anlegen des Inv verschwunden(zumindest wenn man die Felder leer lässt, erst nach Reboot wieder Eingabefelder sichtbar, zum umkonfigurieren
3. nach Erase All sind auch die Standardkonfigs wie NTP und MQTT leer und Pinout (Wemos) und Radio (NRF24L01+) sind ohne Einagbefeld -> nach reboot behoben

**Comment by lumapu** [comment]
@homeautomation2022 bei `erase all` müsste doch automatisch ein reboot durchgeführt werden, daher sehe ich hier kein Handlungsbedarf.

**Comment by homeautomation2022** [comment]
Wäre es so, dann hätte ich wohl den Bug nicht beobachten können? Bei Factory Reset wird ein Reboot gemacht, Erase All anscheinend nicht oder ist das bei dir so?, ich musste manuell rebooten, um dem Problem aus dem Weg zu gehen.

**Comment by lumapu** [comment]
ok, ich habe es nur in Code heute verfolgt und nicht getestet, danke für den Hinweis dass nicht automatisch rebootet wird (das hatte ich erwartet).

**Comment by DanielR92** [comment]
Habe es gerade mit diesem PR https://github.com/lumapu/ahoy/pull/341 getestet. 
Bei mir sieht alles normal aus, Felder sind vor ausgefüllt.

Factory Reset: Ok
Erease Settings: Ok 

Beides sieht nachdem ich jedesmal neu Konfiguriert habe, identisch aus.

**Comment by homeautomation2022** [comment]
OK, ich muss mich korrigieren, keine Ahnung warum es bei meinem Test nicht ging, aber habe nun nochmal mit einer anderen FW gestestet und er macht tatsächlich bei "ERASE SETTINGS (not WiFi)" ein reboot, somit alles i.O.

**Comment by DanielR92** [comment]
Kurze Frage, geht es hier "Module Name auf 4 Zeichen begrenzt" darum das die PV-Module mit dem Namen gekürzt werden sollen? Wenn ja, wieso 4 Zeichen? Mit 8 wäre ich noch Einverstanden.

**Comment by lumapu** [comment]
@DanielR92 ist doch schon gelöst. Es ging darum, dass die Input Felder nur 4 statt der 16 erlaubten Zeichen zugelassen haben
