### ISSUE TITLE
NRF24L01+ mit oder ohne Antenne?

### ISSUE THREAD

**Issue by VIEWSION** [lumapu/ahoy#339]
Ich hab aktuell die Version ohne Antenne dran - vorsichtshalber aber noch eine Version mit Antenne bestellt. Ich bin direkt unter dem Dach unter der Anlage und die Verbindung scheint eigentlich recht stabil zu sein... "Receive fail" ist niedrig oder 0. Kann man sowas wie eine "Signalstärke" auslesen um das mal zu vergleichen? Wie ist Euere Erfahrung mit/ohne Antenne was die Reichweite angeht?

**Comment by DanielR92** [comment]
Wenn du direkt am WR dran bist, reicht der kleine. :) 
Im Setup Bereich ist es hierbei Sinnvoll die Leistung so gering wie möglich zu halten (Low). 

Wenn du bis hierhin super Daten erhälst, wieso etwas daran ändern?

**Comment by VIEWSION** [comment]
... ja - stimmt schon ;) Danke!

**Comment by stefan123t** [comment]
Nein RSSI der nRF24 Module gibt es nicht. Lediglich die Information ob die Empfangsstärke besser/schlechter als 60/64dB ist.
Es gäbe auch noch ein GetLossRate DevInfo Kommando aber das haben wir mW noch nicht inplementiert. Damit könnte man die Paket-Fehlerrate des Wechselrichters auslesen. Du kannst das gerne implementieren wenn Du Zeit und Lust hast ?

**Comment by VIEWSION** [comment]
gerne... dafür muss ich mir das aber erst mal genauer ansehen ;) Hatte bisher noch gar nix mit Arduino & Co am Hut und hier auch nur das fertige Image gezogen. Aber es interessiert mich.... mal sehen...

**Comment by stefan123t** [comment]
@VIEWSION herzlich willkommen, das Kommando ist hier beispielhaft beschrieben:
https://github.com/stefan123t/ahoy/wiki/FAQ-Frequently-Asked-Questions#getlossrate--0x15

Ach ja der Unterschied zwischen dem Modul ohne Antenne und dem mit externer Antenne ist bei mir bei gleichem Aufbau daß ich das PA+LNA Modul im MIN / LOW Modus betreiben kann, während ich das einfache Modul mit Leiterbahnschleife auf HIGH stellen muß. Es ist also i.d.R. zu empfehlen einen ~100uF Elektrolyt Kondensator zwischen +3.3V und GND an Pin 1 & 2 des NRF Moduls anzulöten um die Versorgungsspannung beim Senden zu stabilisieren.
