### ISSUE TITLE
HM-300 Active Power Limit does not work?

### ISSUE THREAD

**Issue by Mimi1968** [lumapu/ahoy#348]
I have a question about the Active Power Limit.
Does this work with the current Ahoy version?

I have a HM-300 and have at
Active Power Limit 150 entered
and at Active Power Limit Control Type
absolute in watts persistent.
But it still shows 100% in the visualization.

Or am I doing something wrong?
Unfortunately I am only a user of the system not a programmer

Thank you for your help

**Comment by homeautomation2022** [comment]
The main branch is buggy, try the dev03 branch or set 50% persistent (not Watt) in your buggy version. Why ever you want to set your only 300W to 150W permanently???

**Comment by Mimi1968** [comment]
It is an attempt to cover the base load at night
powered by a lifepo4 battery

**Comment by Mimi1968** [comment]
The basic consumption can probably also be actively controlled with MQQT.
But I have no idea about IOBroker and such :-(
I also have Shelly 3EM that can then probably actively regulate the Hoymiles via the interface.
