### ISSUE TITLE
ESP8266: Feature Request Transmit/Received Logging Format

### ISSUE THREAD

**Issue by stefan123t** [lumapu/ahoy#35]
Hallo Lukas,

kannst Du den Feature Request noch aufnehmen, d.h. die Daten mit  Transmit und Received per Serial (ggf. auch WebSerial oder MQTT o.a.) im "Unified Format" mitzuloggen, damit man die Daten auch mit dem Python Code nachverarbeiten könnte ?
Es gibt zwar ein paar Zeilen, die bereits die `sent packet: #` und `RAW` / `CMD` im entsprechenden Format ausgeben.
Diese sind jedoch meist inaktiv und man muss die immer von Hand einschalten vor dem Kompilieren, damit man die Rohdaten sieht.

Transmit
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/hmRadio.h#L239-L240
Received
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/app.cpp#L142-L151

**Comment by lumapu** [comment]
wurde in 0.4.0 eingebaut

**Comment by stefan123t** [comment]
Another job well done! Thanks a lot for anticipating this in 0.4.0 already!
