### ISSUE TITLE
Config Inverter 0: Address* Name*

### ISSUE THREAD

**Issue by janwilke** [lumapu/ahoy#366]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

## Software
* [X] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0.5.17

### Build & Flash Method:
* [ ] Arduino
* [X] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [ ] Windows
* [X] Mac OS

I've an easy question where I couldn't find a documentation yet.
What values exactly do I need to insert in config : Inverter 0 : Address & Name? The fields are mandatory.
Is it the serial number?

BR,
Lammermann

**Comment by lumapu** [comment]
correct, address is the 12 digit serial number.
The name is something human readable like 'house roof south'

**Comment by janwilke** [comment]
Thx, works fine for me. Maybe this info can be added to readme.
