### ISSUE TITLE
Feature Request / Improvement: Add and display (Multi-) Sensor for Monitoring the ESP8266 (e.g. BME280)

### ISSUE THREAD

**Issue by andi-bar157** [lumapu/ahoy#368]
## Hardware
x - ESP8266
 
Modelname: Wemos D1 mini 
Retailer URL: 

### nRF24L01+ Module
x -  nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
x circuit board

### Power Stabilization:
x  - 100uF Electrolytic Capacitor 

### Connection diagram:
n.A.

### Connection diagram I used:
n.a.

## Software
x - AhoyDTU

### Version / Git SHA: 
n.A.

### Build & Flash Method:
n.A.

### Desktop OS:
n.A.

### Debugging:
n.A. 

### Comment:

For monitoring the ESP82600 it would make sense to have the possibility to connect a multisensor like the BME280 to have the environmental parameters of the 8266. Furthermore it would be great if these parameters as well as the WIFI RSSI could be output, on the one hand via GUI and on the other hand via MQTT (see my first issue: https://github.com/lumapu/ahoy/issues/260).

**Comment by lumapu** [comment]
Verstehe den Feature Request nicht, bitte nochmal detailierter beschreiben. Ist die Funktion für die Allgemeinheit nützlich?

**Comment by stefan123t** [comment]
@lumapu BME280 ist ein Bosch Environment Sensor und mißt neben Luftdruck, Temperatur und Luftfeuchtigkeit. Wird m.W. per I2C Bus angeschloßen. Ich weiß jedoch nicht ob das für die DTU so interessant ist, wenn die im Gebäude aufgestellt ist und der WR bzw. die PV-Panele vor der Tür stehen. Wenn man die DTU aber auch draußen aufstellt und noch genügend Pins zur Verfügung hat, könnte man die gewünschten Werte ermitteln. ~~Eventuell reicht aber auch ein AM2302 oder ein DS18B20 für die Umgebungs-Temperatur. Obwohl die gibt der WR ja selbst aus ... Vielleicht kann man ja auch die Temperatur des ESP8266 aus einem Register abfragen~~ ?
