### ISSUE TITLE
Leistungsbegrenzung in Prozent

### ISSUE THREAD

**Issue by Matze7779** [lumapu/ahoy#380]
Bei der 0.5.28 funktioniert die Leistungsbegrenzung in Prozent nicht mehr.

Ahoy 0.5.28
HM 1200
Unter "Serial Console"

Angaben in Watt werden korrekt angenommen. In Prozent nicht.

**Comment by reserve85** [comment]
kann ich bestätigen, mit einem HM-1500 das gleiche. Es funktioniert nur die Einstellung in "Watt".

**Comment by DD0CW** [comment]
stimmt, und im Text "Every xx seconds the values are updated" wird der eingegebene Wert ( z.B. 20 Sekunden ) zwar entspr. ausgeführt aber immer nur xx = 30 angezeigt.

**Comment by DanielR92** [comment]
PullRequest ist raus. Bug für das setzen eines Wertes in % wurde behoben. Danke.

**Comment by lumapu** [comment]
@Matze7779 @reserve85 bitte um Feedback vom test mit aktueller Development Version

**Comment by reserve85** [comment]
funktioniert bei mir (Watt + %), vielen Dank!
edit: getestet mit [64fb587](https://github.com/lumapu/ahoy/commits/64fb587)
