### ISSUE TITLE
Feature Request - Serial, add inverter id (0-n) to each printed line

### ISSUE THREAD

**Issue by Waldo56** [lumapu/ahoy#388]
Please add the related Inverter id to the beginning of each line. E.g. 
13:50:44 I: (0) Devcontrol request 11 power limit 800
Are there any other message types than "I"? May be "E", like error?

**Comment by lumapu** [comment]
nice feature - will be implemented. 
Today there will be an Update to our debug level system.
Up for now we have the following levels:

- Error
- Warning
- Info
- Debug
- Verbose
