### ISSUE TITLE
Add HM1500 compatibility to ESP8266 version

### ISSUE THREAD

**Issue by wittj** [lumapu/ahoy#40]
I successfully initiated communication with two HM1500 inverters using the ESP8266 software out of the box. So this inverter could be added to the compatibility list. (I would suspect that this inverter is identical to the HM1200 except a slightly higher output power config).

**Comment by lumapu** [comment]
Correct, thank you for contribution! There are three groups of HM-Inverters. They are grouped by their number of DC-Inputs. 
HM1200, HM1500: 4 inputs
HM600, HM700, HM800: 2 inputs
...

Do you already use the lastest verison 0.4.1? I could not test it with two inverters, because I only have one.

**Comment by wittj** [comment]
I didn't find versioning information in the repo. But as I had cloned the repository one hour ago and the last commit before that (Multi inverter support) was done two hours ago the latest version should be running here with the two inverters.

**Comment by lumapu** [comment]
great! The version is declared in `defines.h` and you can check it using the web interface in the bottom right corner.
