### ISSUE TITLE
[ESP32] Reboot schleife mit default Settings (klick auf SAVE)

### ISSUE THREAD

**Issue by reserve85** [lumapu/ahoy#404]
### Platform

ESP32

### Model name

NodeMCU V1.1

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266/32 GPIO |
| ------------- | --------------- |
| Pin 1 GND []  |  GND            |
| Pin 2 +3.3V   |  +3.3V          |
| Pin 3 CE      | GPIO_2/_4 CE    |
| Pin 4 CSN     | GPIO15/_5 CS    |
| Pin 5 SCK     | GPIO14/18 SCLK  |
| Pin 6 MOSI    | GPIO13/23 MOSI  |
| Pin 7 MISO    | GPIO12/19 MISO  |
| Pin 8 IRQ     | GPIO_0/0 IRQ    |

Note: [] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.32

### Github Hash

2826726

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Debug Serial Log output

```shell
---------
AP MODE
SSID: AHOY-DTU
PWD: esp_8266
Active for: 60 seconds
---------

I: RF24 Amp Pwr: RF24_PA_I: LOW
I: Radio Config:
SPI Frequency		= 1 Mhz
Packets lost on
Retry attempts made for
W: WARNING! your NRF24 module can't be reached, check the wiring
I: Settings valid: false
I: EEprom storage size: 0x2f2
I: 1 client connected (no timeout)
I: 1 client connected (no timeout)
I: 1 client connected (no timeout)
I: 
I: Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[     3][E][EEPROM.cpp:70] begin(): Unable to open NVS namespace: 4353
I: loadEEpconfig
I: resetPayload: id: 0
I: resetPayload: id: 0
I: resetPayload: id: 0
I: resetPayload: id: 0
I: 

----------------------------------------
I: Welcome to AHOY!
I: 
point your browser to http://192.168.1.1
I: to configure your device
I: ----------------------------------------

I: RF24 Amp Pwr: RF24_PA_I: LOW
I: Radio Config:
SPI Frequency		= 1 Mhz
Packets lost on
Retry attempts made for
W: WARNING! your NRF24 module can't be reached, check the wiring

assert failed: tcpip_api_call IDF/components/lwip/lwip/src/api/tcpip.c:497 (Invalid mbox)


Backtrace:0x40083759:0x3ffb25400x4008b72d:0x3ffb2560 0x40090b35:0x3ffb2580 0x40105cf1:0x3ffb26b0 0x401551eb:0x3ffb26e0 0x400eaf3e:0x3ffb2730 0x400dcdb9:0x3ffb2750 0x400d6b7e:0x3ffb27a0 0x400da42a:0x3ffb2800 0x400f0b8e:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[     4][E][EEPROM.cpp:70] begin(): Unable to open NVS namespace: 4353
I: loadEEpconfig
I: resetPayload: id: 0
I: resetPayload: id: 0
I: resetPayload: id: 0
I: resetPayload: id: 0
I: 

----------------------------------------
I: Welcome to AHOY!
I: 
point your browser to http://192.168.1.1
I: to configure your device
I: ----------------------------------------

I: RF24 Amp Pwr: RF24_PA_I: LOW
I: Radio Config:
SPI Frequency		= 1 Mhz
Packets lost on
Retry attempts made for
W: WARNING! your NRF24 module can't be reached, check the wiring

assert failed: tcpip_api_call IDF/components/lwip/lwip/src/api/tcpip.c:497 (Invalid mbox)


Backtrace:0x40083759:0x3ffb25400x4008b72d:0x3ffb2560 0x40090b35:0x3ffb2580 0x40105cf1:0x3ffb26b0 0x401551eb:0x3ffb26e0 0x400eaf3e:0x3ffb2730 0x400dcdb9:0x3ffb2750 0x400d6b7e:0x3ffb27a0 0x400da42a:0x3ffb2800 0x400f0b8e:0x3ffb2820 

etc...
```

### Error description

Ein Problem tritt wenn man:

1. ESP32 mit Webinterface flasht
2. Connect auf AP "AHOY-DTU"
3. Onlineupdate auf #2826726 V0.5.32
4. Restart + Connect auf AP "AHOY-DTU"
5. Settings öffnen, nichts ändern, Haken setzen bei "reboot device after successful save" und "Save" klicken

Danach bootet der ESP nicht mehr mit o.g. Fehlermeldung aus dem Log (assert failed: tcpip_api_call IDF/components/lwip/lwip/src/api/tcpip.c:497 (Invalid mbox)). 
Ich vermute einen Zusammenhang mit den WiFi Einstellungen. Wenn ich das Szenario nochmal durchspiele und in den Settings sofort beim ersten Connect mein WiFi eintrage, dann funktioniert es auch nach dem Save und Reboot weiterhin.

**Comment by reserve85** [comment]
update: mit der Main-Version 0.5.28 funktioniert es.

**Comment by stefan123t** [comment]
@reserve85 ich hatte das heute auch bei 0.5.28 mit den ESP Web Tools geflasht.
Erst nach mehrmaligem Reset per Web Serial Console hat er sich dann irgendwie gefangen.

**Comment by lumapu** [comment]
danke für die detaillierten Reproduction steps.
Ich stelle es bei mir bei Gelegenheit nach.

**Comment by DanielR92** [comment]
Ich glaube dieses Issue kann dann geclosed werden. Oder?

**Comment by lumapu** [comment]
ich habe es noch nicht nachvollziehen können (aus zeitlichen Gründen)

**Comment by stefan123t** [comment]
Hallo @lumapu ich glaube das ist der Versuch des AhoyDTU sich mit YOUR_WIFI_SSID zu verbinden was ja nicht klappen kann.

Nebenbei bemerkt scheint da auch die Konfiguration für das NRF24 Modul überhaupt noch nicht zu stimmen:
> W: WARNING! your NRF24 module can't be reached, check the wiring
> I: Settings valid: false

Wie gut ist eigentlich unsere ESP32 Wiring / Pinout Dokumentation?
Sollen wir hierfür auf die mE gute und funktionierende Doku von OpenDTU verweisen bzw. das selbe Pinout als Default für den ESP32 hinterlegen ?

**Comment by stefan123t** [comment]
Der Reboot loop sollte in den aktuellen Versionen gefixt sein.
