### ISSUE TITLE
Suche Hilfe zum "inkludePath" Problem

### ISSUE THREAD

**Issue by daja64** [lumapu/ahoy#411]
![Fehler](https://user-images.githubusercontent.com/112585237/201484562-cfa7f252-2a53-4510-8994-0592e6b265bf.jpg)
Hallo, jetzt wollte ich mal mit meiner Anzeigegeschichte weitermachen und  nun dieses Problem. Mußt auf einen neues NB umziehen, beide haben Win10 64bit. VScode gestartet, Clone Git Projekt, bis hier ok. Wenn ich jetzt die z.B. die main.cpp anklicke, kommt dieser Fehler. Auf dem alten NB war das nicht der Fall, weil ich da schon mal damit hantiert habe ohne diese Meldung. Leider find ich außer "die Pfade händisch eintragen" keine gescheite Hilfe. Warum nun händisch obwohl es beim alten NB automatisch ging ?

**Comment by lumapu** [comment]
evtl. liegt es an einer der Dateien im `.vscode` Ordner.
Ansonsten mal clean Projekt (Mülltonne unten in der Statuszeile) ausprobieren.

**Comment by daja64** [comment]
Meintest du die hier c_cpp_properties.json
`{`
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x64"
        }
    ],
    "version": 4
`}`
Bitte mal genau beschreiben wie das mit Vscode geht, also den Ablauf vom Start des Programm, bis dahin wo ich kann dann z.B. die app.cpp bearbeiten kann.

**Comment by daja64** [comment]
Mann bin ich manchmal doof. Es war nur der falsche Projektordner. Also ist noch einiges an Einarbeitung nötig. Kann dann geschlossen werden. Sorry für die Aufregung.

**Comment by lumapu** [comment]
alles gut, hat immer seine Berechtigung ;-)
