### ISSUE TITLE
YieldDay Reset

### ISSUE THREAD

**Issue by usekevin1988** [lumapu/ahoy#414]
Bin mir nicht sicher, ob es so gewollt ist oder ein BUG, daher sicherheitshalber mal festhalten.

Wenn ich mein Ahoy neustarte, wird "YieldDay" resettet. "YieldTotal" bleibt erhalten.

Nutze Version 0.5.35

Kann man den Wert eigentlich Manuell anpassen irgendwie?

**Comment by homeautomation2022** [comment]
Beide Werte kommen direkt vom Wechselrichter, dieser resettet YieldDay nur beim Ausgehen zum Sonnenuntergang. Wenn du tagsüber Ahoy neustartest, kommt der YieldDay wieder, sowie auch der Yield Total. In der Nacht kommt da nichts, da der Wechselrichter da nicht erreichbar ist.

Manuell kann man da nichts anpassen. Einzig YieldDay wird zurückgesetzt, wenn du das Restart Command sendest.
Wenn du nur ESP Reboot anklickst holt er sich die Werte vom WR danach wieder.

**Comment by usekevin1988** [comment]
ok, dann lags am neustarten des WR.. dann hat sich das erledigt :)
