### ISSUE TITLE
Minimaler Formalfehler

### ISSUE THREAD

**Issue by Waldo56** [lumapu/ahoy#415]
### Platform

ESP8266

### Antenna

circuit board

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266/32 GPIO |
| ------------- | --------------- |
| Pin 1 GND []  |  GND            |
| Pin 2 +3.3V   |  +3.3V          |
| Pin 3 CE      | GPIO_2/_4 CE    |
| Pin 4 CSN     | GPIO15/_5 CS    |
| Pin 5 SCK     | GPIO14/18 SCLK  |
| Pin 6 MOSI    | GPIO13/23 MOSI  |
| Pin 7 MISO    | GPIO12/19 MISO  |
| Pin 8 IRQ     | GPIO_0/0 IRQ    |

Note: [] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.35

### Github Hash

56cfffb

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Manual Scoll -> Manual Scroll

![Screenshot_20221113-123452_Chrome](https://user-images.githubusercontent.com/116426880/201530467-0ac4816b-2c30-4c86-af12-702d1371ee38.jpg)

**Comment by lumapu** [comment]
müsste jetzt passt Sekunden drauf schauen, im den Fehler zu sehen. Wird behoben ;-)

**Comment by DanielR92** [comment]
please close this issue, is already fixed in dev03.

![grafik](https://user-images.githubusercontent.com/25644396/202522812-7a9662dc-a86a-4779-9839-25cc09b09db4.png)
