### ISSUE TITLE
Feature Request | "Sunrise" "Sunset" via MQTT übertragen

### ISSUE THREAD

**Issue by ambivalent11** [lumapu/ahoy#417]
Ist es möglich die beiden Datenpunkte ebenfalls via MQTT zu übertragen?

**Comment by stefan123t** [comment]
Möglich ja, die Frage ist, wieso brauchst Du die explizit und vor allem wie oft ?
Sollte ja dann einmal am Tag genügen ggf. mit einem retain Flag von 12 / 24h ?

@lumapu wie oft, bzw. wann werden die nochmal berechnet ?
Nur ein / zweimal am Tag um 0:00 und 12:00 Uhr ?

**Comment by lumapu** [comment]
@stefan123t ich glaube 1x, muss ich prüfen. 

im Grunde spricht nichts dagegen, diese beiden Infos auch zu übertragen.

**Comment by knickohr** [comment]
Wenn wir schon dabei sind, dann bitte auch WiFi RSSI mit übertragen 😉

**Comment by lumapu** [comment]
wird die noch nicht übertragen?

**Comment by knickohr** [comment]
Ich habe keine. MQTT-Topic gefunden 😉

**Comment by haselchen** [comment]
@knickohr 

Über die API kannste den Sunrise und Sunset abrufen und dann umwandeln in die Uhrzeit. Hab das per Iobrokers Blockly gemacht. Über MQTT gleich den Wert zu bekommen ist natürlich komfortabler :)

**Comment by DanielR92** [comment]
Ok, beduetet dann:

- Sunrise + Sunset
- WiFi RSSi

Wenn ich Zuhause bin, kann ich mir das mal anschauen. Dann ist es vom Tisch.

**Comment by lumapu** [comment]
@DanielR92 ist implementiert oder?

**Comment by knickohr** [comment]
Ich flashe 39 😉
