### ISSUE TITLE
HM600, HM700, HM800 with YieldTotal and YieldDay

### ISSUE THREAD

**Issue by meschnigm** [lumapu/ahoy#42]
hmDefines.h

`//-------------------------------------
// HM600, HM700, HM800
//-------------------------------------
const byteAssign_t hm2chAssignment[] = {
    { FLD_UDC, UNIT_V,   CH1,  2, 2, 10   },
    { FLD_IDC, UNIT_A,   CH1,  4, 2, 100  },
    { FLD_PDC, UNIT_W,   CH1,  6, 2, 10   },
    { FLD_YD,  UNIT_WH,  CH1, 22, 2, 1    },
    { FLD_YT,  UNIT_KWH, CH1, 14, 4, 1000 },

    { FLD_UDC, UNIT_V,   CH2,  8, 2, 10   },
    { FLD_IDC, UNIT_A,   CH2, 10, 2, 100  },
    { FLD_PDC, UNIT_W,   CH2, 12, 2, 10   },
    { FLD_YD,  UNIT_WH,  CH2, 18, 2, 1    },
    { FLD_YT,  UNIT_KWH, CH2, 24, 4, 1000 },

    { FLD_UAC, UNIT_V,   CH0, 26, 2, 10   },
    { FLD_IAC, UNIT_A,   CH0, 34, 2, 10   },
    { FLD_PAC, UNIT_W,   CH0, 30, 2, 10   },
    { FLD_F,   UNIT_HZ,  CH0, 28, 2, 100  },
    { FLD_T,   UNIT_C,   CH0, 38, 2, 10   },
    **{ FLD_YD,  UNIT_WH,  CH0, CALC_YD_CH0,   0, CMD_CALC },
    { FLD_YT,  UNIT_KWH, CH0, CALC_YT_CH0,   0, CMD_CALC }`**
    
    Is there a reason why YieldTotal and YieldDay is only available in HM1200, HM1500.
    If not please add this for HM600/700/800
    
    Thank you

**Comment by lumapu** [comment]
No, the only reason is that nobody defined it. I included it for my inverter (HM1200). I will include this definition.

**Comment by meschnigm** [comment]
is implemented
