### ISSUE TITLE
bugs 0.4.2

### ISSUE THREAD

**Issue by t0nym0n0** [lumapu/ahoy#43]
Hallo Lukas,
besten dank für den schnellen Fix, leider passen die Werte für den HM600 noch nicht.
Für den HM350 wird noch der CH2 angezeigt.

Bitte um kurze Anleitung wie per Remote auf die Konsole zugegriffen werden kann, über Putty bekomme ich keine Verbindung.

Vielen Dank!

anbei Bilder des Webinterfaces...

![grafik](https://user-images.githubusercontent.com/85127060/168888265-4e76ad54-962f-4a50-bc15-bc1e339cd120.png)
![grafik](https://user-images.githubusercontent.com/85127060/168888371-ceb4000a-939e-4386-a7bc-bcde64ed5281.png)

**Comment by lumapu** [comment]
Putty auf serial, den richtigen COM Port wählen und die Baudrate auf 115200 stellen. Dann in Web Interface des ESP noch unter serial den RF24 debug einschalten.
Jetzt sollten Werte kommen

**Comment by lumapu** [comment]
duplicate #41

**Comment by t0nym0n0** [comment]
Ok, remote über netzwerk können die Daten nicht über putty ausgegeben werden?

**Comment by lumapu** [comment]
noch nicht, am besten einen neuen Issue mit feature request oä öffnen

**Comment by t0nym0n0** [comment]
in Tasmota kann die Konsole im Webinterface aufgerufen werden, vielleicht kann das übernehmen.

Hier mal ein Bild aus der Tasmotaconsole meines APSystems YC Wechselrichters.
Hier wurde Tasmota so angepasst das die Komunikation mit dem YC600 Wechselrichter möglich ist allerding arbeitet der Wechselrichter mit einem speziellen Zigbee Protokoll. 

![grafik](https://user-images.githubusercontent.com/85127060/168899427-91200139-f8c0-4e6c-b9c2-7e2201bcfaea.png)
![grafik](https://user-images.githubusercontent.com/85127060/168898696-52b3cdeb-3452-42a6-89b2-03825c768caf.png)
