### ISSUE TITLE
logout_timeout not correct?

### ISSUE THREAD

**Issue by DanielR92** [lumapu/ahoy#439]
Hello, 

I saw the new version today and in the config.h it says:
`// timeout for automatic logoff (20 minutes)`
`#define LOGOUT_TIMEOUT      (20 * 60 * 60)`

But 20 minutes aren't just 20*60, are they? (count * 60 sec).

Please let me know. :)

**Comment by lumapu** [comment]
😅

**Comment by DanielR92** [comment]
I saw it is fixed now: https://github.com/lumapu/ahoy/commit/43af07716e03f20778d961166e89aff75154a8a8
Thanks! :)
