### ISSUE TITLE
NRF24 module can't be reached

### ISSUE THREAD

**Issue by MartinL96** [lumapu/ahoy#444]
## Hardware
  * [x] ESP8266 D1 Mini

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

## Software
* [x] AhoyDTU

### Version / Git SHA: 
[ahoy_v0.5.41]

### Build & Flash Method:
* [x] Platform IO

### Desktop OS:
* [x] Windows

![image](https://user-images.githubusercontent.com/118744962/203074886-d16ed717-2f78-4cdc-9c81-eb3d0e2df947.png)
____________________________________
Hi! 

Erstmal vielen Dank für dieses tolle Projekt :)

Leider bin ich noch ein Anfänger in Sachen Mikrocontroller und kann den Fehler nicht finden, weshalb AHOY die NRF24 Antenne nicht erkennt. 

Versucht habe ich es mit und ohne Kondensator und die Verdrahtung mehrmals auf Richtigkeit geprüft. Auch das NRF Modul selbst habe ich gegen ein anderes Ausgetauscht, aber auch hier das selbe Ergebnis. Kann mir hier jemand weiterhelfen die Ursache des Problems zu finden?

**Comment by stefan123t** [comment]
Hallo @MartinL96
welches ESP8266 Modul hast Du denn Händler Link und/oder Photo sind hier notwendig und hilfreich.

Es gibt Wemos D1 mini v1/v3 Boards bei denen funktioniert der genannte IRQ Anschluss nicht ordentlich. 

Versuche mal Pin 8 IRQ statt mit GPIO0/D3 mit GPUO2/D4 zu tauschen und im http://192.168.4.1/setup die Konfiguration entsprechend anpassen.

**Comment by lumapu** [comment]
sind die Kabel verlötet? Das muss mit der Hardware zusammenhängen. Für diesen Test wird die SPI Verbindung benötigt.
Wurde von der richtigen Seite auf die Module geschaut?
Ein Bild des Aufbaus könnte evtl auch weiterhelfen.

**Comment by MartinL96** [comment]
Hallo @stefan123t und @lumapu vielen Dank für euere raschen Antworten!

@stefan123t die Pins zu tauschen und in der Konfiguration zu ändern war scheinbar die Lösung. Die Fehlermeldung ist weg. 
Heute ist die Sonne leider auch schon weg, aber dann bin ich gespannt ob´s morgen dann klappt mit dem Daten auslesen.

**Comment by stefan123t** [comment]
@MartinL96 Wir brauchen dennoch ein Foto von Deinem ESP8266 Board für unsere Beweissammlung :) wie gesagt am Besten mit Händler Link.

**Comment by MartinL96** [comment]
Der Mikrocontroller ist von hier: https://www.makershop.de/plattformen/d1-mini/esp8266-mini-board/

Das sind die Fotos des Boards:

![IMG_20221122_170220544](https://user-images.githubusercontent.com/118744962/203363044-24112eb0-6ae6-4147-a741-fb4b2eab3594.jpg)
![IMG_20221122_170201358](https://user-images.githubusercontent.com/118744962/203363073-2f5fc5b8-448b-4c44-9c4d-4c00ae31ec79.jpg)

**Comment by MartinL96** [comment]
Um das Projekt zu unterstützen möchte ich gerne auch die 3D-Druck Daten meines Gehäuses mit euch teilen :)
https://www.printables.com/de/model/323500-ahoy-dtu-housing

**Comment by lumapu** [comment]
@MartinL96 du kannst den Link auch gerne per pull request in unsere Dokumentation einfließen lassen

**Comment by frankh-gituser** [comment]
> sind die Kabel verlötet? Das muss mit der Hardware zusammenhängen. Für diesen Test wird die SPI Verbindung benötigt. Wurde von der richtigen Seite auf die Module geschaut? Ein Bild des Aufbaus könnte evtl auch weiterhelfen.

kann das nicht-verlöten eine mögliche Fehlerquelle sein ? Habe hier 3 D1 Minis mit 3 verschiedenen RF Modulen zusammengesteckt. Kein einziges RF Modul wird erkannt. Die CE/IRQ Tausch/Konfig Variante habe ich auch bereits versucht - geht auch nicht. Die D1 Minis funktionieren alle tadellos mit anderen Arduino Sketches aber auch auch die Ahoy Software funktioniert bzgl MQTT etc - nur das RF Modul wird nicht erkannt. Total seltsam.

**Comment by lumapu** [comment]
Verlöten würde auf jeden Fall eine große Fehlerquelle ausschließen.
Komisch finde ich allerdings, das 3 Versuche nicht klappen. Vom NRF müssen alle 8 Pins angeschlossen sein.
Wie lang sind die Drähte und gibt es eine Möglichkeit die verbundenen durchzuklingeln?

**Comment by stefan123t** [comment]
@frankhoerper bitte mal einen Elko 10-100uF an Pin 1&2 des NRF24 Moduls (GND bzw. +3.3V) anlöten, das hat meist Abhilfe geschafft. Ansonsten Spannungsversorgung / USB-Kabel durch ein hochwertiges / neues austauschen. Bei Wemos D1 Mini v1/3 hat es auch häufig geholfen D3 & D4 sowohl in der Verkabelung als auch in den Settings IRQ / CE zu tauschen. Bitte ggf. ein eigenes Issue aufmachen, falls das Problem noch existiert.

**Comment by frankh-gituser** [comment]
Danke für die Hinweise. Die Bauteile sind alle neu, aber ich werde bei Gelegenheit nochmal eine Version verlöten. Habe jetzt einen alten nodemcu8266 an den verkabelten rf24 gehängt und damit lief alles direkt wie gewünscht. Somit weiss ich auf jeden Fall, dass das rf24 Modul nicht defekt ist.

**Comment by stefan123t** [comment]
@frankhoerper dann liegt es also nicht am NRF24 Modul das ist schon mal gut und erwartet. Wenn Du noch Zeit und Lust hast kannst Du gerne mal mit verschiedenen Belegungen con D1..D4 und IRQ bzw CE probieren. M.W. haben die Wemos D1 Module da irgendeine spezielle Reset/Flash/Boot Schaltung die das Problem verursacht.
Wäre schön wenn wir mal so einen Wemos D1 hätten der das Problem zeigt um es ggf. mit dem Oszi / Logikanalyzer auszumessen.

**Comment by frankh-gituser** [comment]
@stefan123t , werde das in den nächsten Tagen nochmal mit einem Breadboard durchtesten. Die D1-D4 Variante hatte ich aber auch bereits getestet , ebenso  den IRQ/CE Tausch. Zwischenzeitlich habe ich den gleichen Effekt auch mit openDTU und zwei verschiedenen ESP32 Modellen. Die nodecmu Variante , die in der Doku angegeben ist funktioniert, eine Dev Kit Variante mit ESP32 Chipset/38 Pins nicht. Auf irgendeinem PIN funkt scheinbar irgendein Signal je nach Modell nicht wie erforderlich. Auf jeden Fall habe ich gelernt , dass bei den Modellen bzgl Kompatibiltät eine ganz schöne Varianz besteht. 
Die ESP8266nodecmu / ahoyDTU Konfig läuft seit einigen Tagen problemlos. Vielleicht sollte das als Empfehlung mit in die Doku, falls es mit den D1 Modellen nicht auf Anhieb funktioniert und man nicht x Modelle durchtesten möchte.
