### ISSUE TITLE
Live View - Inverter Limit mehr als 100%

### ISSUE THREAD

**Issue by Waldo56** [lumapu/ahoy#447]
### Platform

ESP8266

### Antenna

circuit board

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.41

### Github Hash

dec333f

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

![Screenshot_20221121-163917_Chrome](https://user-images.githubusercontent.com/116426880/203311916-cf869dd4-daa0-4814-ac2c-6c5059ce4d76.jpg)

Manchmal wird beim eingestellten Inverter Limit mehr wie 100% angezeigt. Ich vermute es passiert durch Übertragungsfehler bei der Kommunikation. Sind die empfangenen Daten nicht auch mit CRC geschützt? Vielleicht wäre ein Wertebereichscheck hilfreich. Sollte der Wert größer als 100% sein dann vielleicht n/a anzeigen.

**Comment by stefan123t** [comment]
Du hast einen HM-600 oder einen HM-800, Deine Angaben im Template widersprechen den Screenshots ?
Hast Du das PowerLimit mit 100% permanent mal auf den Default gesetzt ?

Ich kann mich erinnern dass es ggf. bei auf 70% gedrosselten HM-300 sehr seltsame Zahlen herauskommen, da diese über das GridProfile entsprechend bereits auf 70% gedrosselt sind, d.h. bei 100% kommen irgendwelche Kommazahlen raus.

Aber das bei Dir sieht anders aus, kannst Du das Verhalten reproduzieren und ggf die Ausgabe der USB Serial Console beisteuern ? 
Dazu bitte ggf. die Option [x] Serial Debug unter System Config im Setup ankreuzen, speichern und neu booten.

Es interessieren vor allem das [ActivePowerLimit](https://github.com/lumapu/ahoy/wiki/Protocol#wie-funktioniert-das-active-power-limit-0x0b-sub-kommando) `0x0B` und das [SystemConfigPara](https://github.com/lumapu/ahoy/wiki/Protocol#systemconfigpara--0x05) `0x05` Kommando

**Comment by Waldo56** [comment]
Werde versuchen es zu reproduzieren. Wir haben 2xHM800. Der 2. HM800 (der diesen Wert zeigt) ist aber ca. 50m weit weg.

**Comment by Argafal** [comment]
I have the same issue with my HM-1500s. And interesting enough: I get the same wrong value 202.1%, so something seems to be special about it. I get the wrong value only sometimes, with no clear pattern when. I did not set a production limit.

**Comment by AsFaBw** [comment]
Gleiches Verhalten bei mir (die 202.1% bei einem HM-800).
SW Version 0.5.28

![DisplayHM800_200WattAbsolutLimitInWattPersistent_0_5_28](https://user-images.githubusercontent.com/35894484/203803023-e465df15-14e6-4a8a-985c-72a9a29a8e16.jpg)

**Comment by stefan123t** [comment]
It is probably a wrong attribution of responses from the inverter on some of our commands.
We ask for A and later for B and only then receive the response for A (or the other way round), which is eventually yielding the wrong value.
We need some more evidence based on log files where the above commands are logged in.
Make sure you enable [x] Serial Debug under Setup > System Config. Thanks!

**Comment by Waldo56** [comment]
Will do.

**Comment by stefan123t** [comment]
@Waldo56, these are the three common [`0x15 DeviceInfo` Sub Commands](https://github.com/lumapu/ahoy/wiki/Protocol#welche-device-info-req_arw_dat_all-0x15-sub-kommandos-gibt-es) that we execute in row after each other:
```
I: (#1) enqueuedCmd: 11 <-- SubCommand 0x0b RealTimeRunData_Debug
I: (#1) enqueuedCmd: 1 <-- SubCommand 0x01 InverterDevInform_All
I: (#1) enqueuedCmd: 5 <-- SubCommand 0x05 SystemConfigPara
```
@lumapu could we add the above SubCommand comments / explanation to the `enqueuedCmd` Informational message in order to make it more readable ?

They all use the sendTimePacket Method to send the command to the inverter together with the current timestamp.
```
I: TX 27B Ch40 |>15<75 21 23 45 87 65 43 21 80>0B<00 63 7F 71 26 00 00 00 00 00 00 00 00 14 5E EF 
...
I: TX 27B Ch61 |>15<75 21 23 45 87 65 43 21 80>01<00 63 7F 71 4A 00 00 00 00 00 00 00 00 1C A9 76 
...
I: TX 27B Ch75 |>15<75 21 23 45 87 65 43 21 80>05<00 63 7F 71 68 00 00 00 00 00 00 00 00 79 2C B0 
```

We cannot see from an individual response for which of the SubCommands the response by the inverter was actually meant for.
We only see that it is a response to one of the `0x15` DeviceInfo Commands (`REQ_ARW_DAT_ALL`) we sent,
as they all contain the answer code `0x95` which is the complement of the original query DeviceInfo command (`REQ_ARW_DAT_ALL | 0x80`). E.g.:
```
I: TX 27B Ch23 |>15<75 21 23 45 87 65 43 21 80>05<00 63 7F 71 68 00 00 00 00 00 00 00 00 79 2C B0 
I: RX 27B Ch61 |>95<75 21 23 45 75 21 23 45 81 00 01 03 E8 00 00 03 E8 FF FF FF FF 01 68 7D F8 F9 
I: procPyld: cmd:  5
I: procPyld: txid: 0x95
I: Payload (14): 00 01 03 E8 00 00 03 E8 FF FF FF FF 01 68 
```

**Comment by mroenne2022** [comment]
Hallo, ich hab bei mir ebenfalls den Effekt das nach dem Updates eines meiner Ahoy's  von 0.5.17 auf 0.5.41 das InverterLimit mit 202,1 % angzeigt wird. Ich hab da selbst noch nie irgendeinen Wert selbst eingegeben. Der andere Ahoy noch mit der FW Version 0.5.17 zeigt 100%  richtig an. Ich hab einen HM600 in Betrieb, die beiden Ahoy sind ESP8266 / D1 Wemos Mini. Ich les hier mal mit um zu sehen wie das ggf gelöst wird. VG Michael 
![Limit_Inverter](https://user-images.githubusercontent.com/114778920/204541042-a7a3844f-f749-48ba-ba70-e60a74c371be.jpg)

**Comment by stefan123t** [comment]
@mroenne2022 habt ihr da zwei DTUs parallel laufen, das verstärkt ggf. die Problematik dass die DTU nicht weiß auf welches Kommando der WR gerade antwortet.

**Comment by mroenne2022** [comment]
Hallo stefan123t, nein nein .... immer nur **EINE** DTU zur Zeit in Betrieb, NIE zur gleichen Zeit. Ich hab mir lediglich mehrere gebaut , z.T. mit verschiedener HW (ESP32 WROOM und ESP8266 D1 Mini). Einmal weil ich Lust hatte dazu, um mal zu testen oder auch um Ersatz zu haben falls mal etwas nach Update nicht mehr läuft ! Heute hab ich die mit der 0.5.41er FW am laufen und hab das Limit über Serial Console einfach mal auf 100% gesetzt, nun ist die Anzeige im Ahoy auch in Ordnung und zeigt die 100% richtig an. Ich hatte den Pkt gestern erst vermisst, dann aber gelesen das er ab 0.5.28 zur Serial Console gewandert ist :-) Im übrigen ist das eine tolle Sache die ihr hier bei diesem Projekt leistet, Vielen Dank dafür ! Gruß Michael R.

**Comment by Waldo56** [comment]
Ich habe nur eine DTU.

**Comment by AsFaBw** [comment]
Ich habe auch nur eine DTU.
Was ich aber nicht ausschliessen kann, ist, dass ich eine Web Session via Rechner und eine Web Session via Phone Richtung Ahoy offen hatte.
Kann es sein, dass die Refreshs der Beiden (Phone & Rechner) irgendwie eine Race condition innerhalb Ahoy erzeugen?

**Comment by stefan123t** [comment]
@Waldo56 und @mroenne2022 
Das aktuelle Power Limit wird m.W. über das Kommando [0x05 SystemConfigPara](https://github.com/lumapu/ahoy/wiki/Protocol#systemconfigpara--0x05) abgefragt (siehe > Traces).
Das wird aber nur beim Starten des ESP einmal oder nach dem Setzen des Power Limits enqueued und abgefragt.

Um Eure Problem näher zu einzugrenzen bräuchten wir die Antworten auf das SystemConfigPara Kommando:
```
11:25:37.358 > TX Channel: 61 --> >15< <71 60 35 46> <78 56 34 12> 80 >05< 00 63 30 1E 8B 00 00 00 00 00 00 00 00 16 A7 8D 
11:25:37.416 > RX >95< <71 60 35 46> <71 60 35 46> >81< 00 01 03 D4 00 00 <03 E8> FF FF FF FF 01 68 2D 38 55 
```
Hier wird das MainCmd `0x15` mit SubCmd `0x05` an den WR `<71 60 35 46>` von der DTU `<78 56 34 12>` per TX gesendet.
Dann kommt die Antwort vom WR an die DTU per RX als `0x95` MainCmd mit einem Single Frame bzw. dem letzten Antwort Paket Nummer `0x81`.
Hier steht das aktuelle Power Limit in Prozent `0x03 E8` = 1000 das bedeutet als Zahl mit einer fixen Nachkommastelle: `100.0` %

**Comment by mroenne2022** [comment]
Hallo Stefan, ich muss mal sehen ob der Effekt morgen überhaupt noch existiert. Ich hatte es ja nur nach dem Update auf 0.5.41 (von 0.5.17) bei der einen DTU zufällig gesehen, heute hab ich den Wert dann einfach im Menue Serial Console auf 100% gesetzt, seit dem wird er auch richtig angezeigt. Morgen am Tage werd ich sehen wie es aussieht, tritt das wieder auf werde ich versuchen die Outputs der Kommandos zu bekommen.

**Comment by mroenne2022** [comment]
Moin @stefan123t , der Effekt mit der Limit Anzeige über 200% tritt nun nicht mehr auf. Kam nur direkt nach dem FW Update, seit ich den Wert dann in der **Serial Console** 1mal auf 100 gesetzt hab ist alles OK , auch heute morgen nachdem der WR wieder erwacht ist alles OK. Für mich ist das in Ordnung , läuft alles prima !! VG Michael
![Limit](https://user-images.githubusercontent.com/114778920/205003084-4358ae70-07ee-49e8-96b6-138eeac4d7e1.jpg)

**Comment by Waldo56** [comment]
Hatte es heute wieder bei dem HM800, der zirka 40m weit von der DTU entfernt ist. Diesmal auch mit last alarm = unknown. Der HW Watchdog der DTU spricht etwa einmal pro Tag an. Werde jetzt mal den HM800 auf 100% konfigurieren und versuchen vom log einen Screenshot zu machen.
Da es immer der gleiche Wert ist habe ich schon an ein Muster gedacht -> 2021 -> 07E5h. 

![Screenshot_20221201-140833_Chrome](https://user-images.githubusercontent.com/116426880/205061094-d6e4eb54-90bd-4bb6-93f5-4648fa566749.jpg)
![Screenshot_20221201-140634_Chrome](https://user-images.githubusercontent.com/116426880/205061143-da194cf0-07f9-4343-895f-f5cc9bdb67a7.jpg)

**Comment by mroenne2022** [comment]
Oh shit 🤔 40m ist tatsächlich ne Menge. Bei mir ist der WR gerade mal 4-5m von der DTU entfernt, eine Ü-Ton Steinmauer dazwischen, aber die Verbindung klappt sehr gut. Läuft auch jetzt seit gestern problemlos mit der richtigen Limit-Anzeige.

**Comment by Waldo56** [comment]
Bei mir war zwischen den falschen Anzeigen zirka eine Woche mit richtigen Werten. Nicht zu früh freuen.😀

**Comment by mroenne2022** [comment]
Ok 😃 Ich werde es sowieso weiterhin beobachten,  ggf melde ich mich hier wieder wenn es tatsächlich nochmal auftritt. Wie schon gesagt - nach dem Update auf 0.5.41 trat es dauerhaft auf,  seit dem ich den Wert dann unter Serial Console einmal auf 100% gesetzt hab ist es in Ordnung. Das ganze ist aber erst wenige Tage her alles.

**Comment by steve-zero** [comment]
Bei mir kommt auch immer wieder nach einiger Zeit die 202.1%.
Firmwareversion ist egal. Bin derzeit auf der 0.5.41 und habe es gerade wieder.
Neusetzen hilft, aber wer weiß für wie lange...

**Comment by mroenne2022** [comment]
Ich hab das mit der 0.5.17 nie gehabt, nur einmal nach Update auf 0.5.41 . Danach einmal neu gesetzt und bisher nicht wieder aufgetreten, ich beobachte es weiter ob es wieder auftritt.

**Comment by stefan123t** [comment]
We need some more evidence based on log files where the above 0x05 SystemConfigPara commands are logged in.

Make sure you enable [x] Serial Debug under Setup > System Config. Thanks!

**Comment by mroenne2022** [comment]
@stefan123t : Sobald der Fall mit den 201% bei mir tasächlich nochmal auftritt werd ich versuchen die Outputs zu bekommen, oder ist das auch jetzt noch aussagekräftig wenn die Anzeige richtig 100% anzeigt. Falls JA , werd ich morgen mal Debug einschalten und gucken was kommt.

**Comment by lumapu** [comment]
ich sehe das auch an und zu, konnte aber noch keine Payload/ Debug print dazu einfangen. Bei mir sind es dann 202%

Ich kann mir vorstellen, dass es daran liegt, dass wir zwei Kommandos mit gleich langer Payload bekommen (FW Version und das Power-Limit). Als Abhilfe können wir die Reihenfolge der enqueue commands ändern, sodass zwischendrin eine längere Payload erwartet wird.
