### ISSUE TITLE
HW/FW Version der Wechselrichter

### ISSUE THREAD

**Issue by Waldo56** [lumapu/ahoy#448]
![Screenshot_20221122-151841_Chrome](https://user-images.githubusercontent.com/116426880/203337551-12adba5c-2bb8-4474-af8a-58942c433799.jpg)

Was bedeutet die Info V10010 in Klammern nach dem Namen des WR? Ist das eine Versionsnummer? HW/FW? Beide Versionen wären natürlich interessant.

**Comment by stefan123t** [comment]
@Waldo56 schau mal hier https://github.com/lumapu/ahoy/wiki/Protocol#inverterdevinform_simple--0x00 und hier https://github.com/lumapu/ahoy/wiki/Protocol#inverterdevinform_all--0x01 
Danke!

**Comment by DukeWolle** [comment]
@Waldo56 
Ja das ist deine FWVersion. Kannst auch anschauen indem du folgende Seite bei dir aufrufst. 

http://deine_ip/api/record/info

Gruß Wolfi

**Comment by Waldo56** [comment]
Ok. Danke Euch.
