### ISSUE TITLE
Live Ansicht ohne Funktion 5.28

### ISSUE THREAD

**Issue by DennisXK** [lumapu/ahoy#450]
Die live Ansicht in der Version 5.28 funktioniert auf meinem IPhone Safari und Firefox leider nicht. Am Pc (win10 firefox und MacOs Safari) funktioniert die Live Ansicht.

https://bilderupload.org/bild/848546235-a1e55fa8-570b-446e-b3b3-0

**Comment by roku133** [comment]
Was passiert, wenn du auf das Symbol mit den drei Balken links oben klickst bzw. tippst?

**Comment by DennisXK** [comment]
Dann geht das Menü auf. Drücke ich wieder auf die 3 Striche, verschwindet das Menü und ich sehe wieder die weise Oberfläche mit der Info "Every seconds the values are updated"

**Comment by roku133** [comment]
Was hat dein IPhone für eine Display-Auflösung?
Was wird bei deinem IPhone im Querformat angezeigt?

**Comment by DennisXK** [comment]
Im Querformat ist das Problem weiter vorhanden. Mein Iphone hat ein 4,7Zoll Display mit einer Auflösung von 1334x750 Pixel

**Comment by knickohr** [comment]
Laß mich raten :  iOS 14 oder älter 😉 Ich kenne das Problem, hier liegt ein altes iPad mini 2 rum 😞

**Comment by DennisXK** [comment]
ja und woran liegt es jetzt? kann ja nicht sein nur weil mein nicht das neuste ios installiert hat, dass es dann nicht angezeigt bekommt!

**Comment by knickohr** [comment]
Doch, ist so. Leider 😞
