### ISSUE TITLE
Feature Request: Aktuelles Active PowerLimit unter Live in Prozent und Watt ausgeben

### ISSUE THREAD

**Issue by Leviathan09** [lumapu/ahoy#451]
Hi,
wäre es möglich unter dem Reiter "Live" nicht nur den prozentualen Limit-Wert sondern auch das Limit in Watt anzuzeigen?

**Comment by stefan123t** [comment]
Der Wechselrichter liefert das aktuelle PowerLimit **nur** in Prozent an die AhoyDTU zurück. D.h. man könnte es aus dem Prozentwert und der Leistung des Wechselrichters berechnen.

@Leviathan09 das ist prinzipiell möglich wenn man die maximale Leistung des WR kennt. @tbnobody hat das in der OpenDTU basierend auf der HW ID des Wechselrichters eine Lookup Tabelle mit den einzelnen Modellen und deren max Leistung umgesetzt.

https://github.com/tbnobody/OpenDTU/issues/363

**Comment by stefan123t** [comment]
Siehe auch tbnobody/OpenDTU#35 für dessen Implementierung, speziell hier:
https://github.com/tbnobody/OpenDTU/issues/35#issuecomment-1264626167

**Comment by lumapu** [comment]
duplicates #201
