### ISSUE TITLE
NTP - Änderungsvorschlag

### ISSUE THREAD

**Issue by HFarryranz** [lumapu/ahoy#46]
Ein Änderungsvorschlag in main.cpp für die Abfrage der NTP-Zeit:

    if(!startAp) {
        delay(5000);
        mTimestamp  = getNtpTime();
        int x = 0;
        while( mTimestamp == 0 && x < 3)
        {
          delay(5000);
          mTimestamp  = getNtpTime();
          x++;
        }
        //DPRINTLN("[NTP]: " + getDateTimeStr(getNtpTime()));
        DPRINTLN("[NTP]: " + getDateTimeStr(mTimestamp));
    }

**Comment by lumapu** [comment]
Wie wäre es wenn wir den timestamp einfach in der Senderoutine (app.cpp) gegen 0 prüfen, dann hängt der ESP nicht ewig in einer Boot-Schleife.
Dafür ist natürlich nötig, das der timestamp nur inkrementiert wird, wenn er ungleich 0 ist.
