### ISSUE TITLE
Total W via MQTT

### ISSUE THREAD

**Issue by Ximon84** [lumapu/ahoy#460]
Moin,

kann man auch die Values untern total via MQTT abfragen?
An die Werte der Inverter komme ich heran, das läuft sehr gut.

DANKE

**Comment by DukeWolle** [comment]
@Ximon84 mit was willst du denn abrufen ?

**Comment by Ximon84** [comment]
@DukeWolle die Gesamt-Leistung W aktuell aller Wechselrichter oder auch die gesamt kWh..

**Comment by knickohr** [comment]
Schau dir mal die total-Werte im Broker an.

![D3B9CF85-283B-40C3-8C9B-6FBC634A9DB1](https://user-images.githubusercontent.com/63048210/204302345-2bd46b07-acd6-4dac-ae9d-f6ff36183395.jpeg)

Das AhoyDTU mußt Du mit Deinem Tpoic-Namen ersetzen (default ist „inverter“).

**Comment by DukeWolle** [comment]
@Ximon84 ich stell meine Frage gerne nochmal. "Mit was willst du abfragen?". Was du willst ist mir klar. Hast du homeassistant laufen ... oder ioBroker, Mosquitto etc. ???

**Comment by Ximon84** [comment]
@DukeWolle Sorry es ist Montag... ich habe nen eclipse mosquitto und nen openhab als docker laufen

@knickohr DANKE probiere ich morgen mal aus!

**Comment by Ximon84** [comment]
Rennt, DANKE!

![grafik](https://user-images.githubusercontent.com/118722998/204484812-502a343a-4d03-46a8-81b7-e0935cbbf30a.png)

**Comment by stefan123t** [comment]
Prima dann mache ich das Issue mal als gelöst zu.
