### ISSUE TITLE
Web Console gibt UTC Zeit aus

### ISSUE THREAD

**Issue by kawi73** [lumapu/ahoy#463]
### Platform

ESP8266

### Model name

D1 Mini

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.44

### Github Hash

0a5833e

### Build & Flash Method

Platform IO (build & flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 114173307265
    - Name: TSOL-M800
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 400, 400
    - Module Name: N/A
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123

### Error description

Die Version 0.5.44 reportet in der Web Serial Console die UTC Zeit. Datum und Uhrzeit in der Übsersichtseite werden richtig angezeigt, d.h. die Zeitsynchronisierung funktioniert.

**Comment by stefan123t** [comment]
Ja das ist works as designed. Wir können in der Serial Console den Timestamp nicht in die lokale Zeitzone durch den Browser umrechnen lassen. Dazu müssten wir den Timestamp getrennt von der Logzeile ausgeben und die Umrechnung im Browser machen.

@lumapu ist das geplant oder überhaupt möglich statt der Web Serial Console immer Tupel mit timestamp, message zu übertragen und die im Browser nebeneinander darzustellen ?

**Comment by kawi73** [comment]
Also in der Version 0.5.41 wird die Zeit richtig angezeigt in der Webconsole. In der Version 0.5.4 wir die UTC Zeit angezeigt. Deshalb habe ich es erwähnt.

**Comment by stefan123t** [comment]
@kawi73 kannst Du das mal anhand eines Screenshots verdeutlichen ?
Ich weiß nicht ob wir vom selben sprechen wenn wir von Web Serial Console reden: AhoyDTU > Serial / Control > Serial Console ?

**Comment by kawi73** [comment]
Einen Screenshot habe ich auf dem Discordserver hich geladen

**Comment by kawi73** [comment]
![Screenshot_2022-11-30-14-39-41-979-edit_com discord](https://user-images.githubusercontent.com/119332725/204811210-5d884e24-0e88-4134-80c6-3391f7624a0b.jpg)

**Comment by kawi73** [comment]
Die Uhrzeit links in dem Screenshot. Das war mit der Development Version 3. Die Zeit war gesynced und es war 11:30uhr.

**Comment by kawi73** [comment]
![Screenshot_2022-11-30-14-46-27-705-edit_com android chrome](https://user-images.githubusercontent.com/119332725/204812799-8c93d2ad-6987-42d2-8b20-e3099f59e36e.jpg)

**Comment by kawi73** [comment]
Das ist ein Screenshot mit der Version 0.5.41 gerade eben erstellt.

**Comment by stefan123t** [comment]
@kawi73 welche Browser sind denn auf den beiden Bildern zu sehen ?

### v0.5.44 funktioniert nicht -> erwartet
`0x63 85 E0 7B` = 1669718139:
GMT | Tue Nov 29 2022 10:35:39 GMT+0000
-- | --
Your Time Zone | Tue Nov 29 2022 11:35:39 GMT+0100 (Central European Standard Time)

### v0.5.41 funktionierte ??? -> vielleicht macht das der Browser ?
`0x63 87 5E 99` = 1669815961:
GMT | Wed Nov 30 2022 13:46:01 GMT+0000
-- | --
Your Time Zone | Wed Nov 30 2022 14:46:01 GMT+0100 (Central European Standard Time)

@lumapu hast Du da schon irgendwas geändert ?

**Comment by kawi73** [comment]
Beides der Chrome. Einmal unter Windows und einmal auf Android.

**Comment by kawi73** [comment]
Aber wenn 0.5.44 wie erwartet reagiert, ist das ok. Dann kann man den Thread schließen.

**Comment by Gerri1** [comment]
Im Firefox und Edge wird bei mir auch die UTC Zeit angezeigt (44), bei der 41 war das i.O.

**Comment by stefan123t** [comment]
Ja das unterwartete in 0.5.41 mit Chrome unter Android kann ich mir aktuell nicht erklären, außer dass der Browser eine lokale Übersetzung der Zeiten macht. Manchmal werden ja auf dem Smartphone auch Telefon Links u.a. anders markiert damit man sie direkt anklicken / anrufen kann. Vielleicht gibt es das auch für die Uhrzeit / Lokalisierung ?

@kawi73 kannst Du das auch unter v0.5.44 mit Chrome auf Android reproduzieren ? 
@Gerri1 wir müssen hier m.E. auch noch die Plattform Android / Desktop unterscheiden ?

**Comment by lumapu** [comment]
der Fehler war im Zusammenhang der Web API. Die habe ich umgestellt und die Web Console vergessen nachzuziehen

**Comment by Gerri1** [comment]
TOP ... läuft wieder!!! 😊👍
