### ISSUE TITLE
Display & Security

### ISSUE THREAD

**Issue by ghost** [lumapu/ahoy#465]
Hi,
( I am Dutch &My English is a bit rusty)
- An 2.7inch E-Paper Display Module 264x176 Resolution would be nice.
- Password protection is super but, the live page could do without an pw (if possible)

Kind regards
Peertje

**Comment by stefan123t** [comment]
Hoi @Peertje62 mijn nederlands is ook prettig rusty 😁 
You may look at #276 there gh-2fx has provided code to hook a nokia 5110 or an OLED display into AhoyDTU. Though it is a PR for an older version you should be able to follow the general idea. Note that the code base in AhoyDTU has been restrictured lately.
Dui, Stefan

**Comment by ghost** [comment]
Thx,
That's ''Adakadabra'' for me,
I'll leave it as it is, working perfect!
Regards Peertje

**Comment by ghost** [comment]
Hi, it me again
correct me if I'am wrong (pls)
Buy a nokia5110-display, connect VCC , GND, D1 - CE & D2 -DC and it will work?
Kind regards
Peertje

**Comment by ghost** [comment]
Hi, Stefan,
I'am still learning every day!
Could you/Would you  include this in the next update ?
(Ahoy, esp8266, nokia5110)
Kind regards
Herman

**Comment by lumapu** [comment]
I have the pull request and its code, but it has to be converted to a class. Was not included until now

**Comment by ghost** [comment]
Hi,
that would be nice if you did, 
kind regards,
Peertje
