### ISSUE TITLE
HM 400 not available

### ISSUE THREAD

**Issue by helibub** [lumapu/ahoy#473]
## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: _Wemos Mini D1 Pro v3_____
Retailer URL: ___aliexpress___

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [x ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V VCC   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

## Software
* [ x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0_.5_._41_
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [x![AhoyWemos_Steckplatine](https://user-images.githubusercontent.com/119676839/205303413-3e44f59d-e746-41ed-827d-211936effc5d.jpg)
 ] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [ x] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hello,

Maybe anyone had an idea ? I flashed with esp8266flasher/221119_ahoy_0.5.41_esp8266_dec333f.bin today to
![AhoyWemos_Steckplatine](https://user-images.githubusercontent.com/119676839/205305982-394af15d-b3ea-48e9-9606-2d5906dfeb56.jpg)
 esp 8266 successfully and the controller is online but it seems that the HM 400 isnt responding.12 digits serial number is checked.
***
14:29:22 I: devcontrol [0], cmd: 0x0
14:29:27 I: resetPayload: id: 0
14:29:27 I: sendControlPacket cmd: 0
14:29:27 I: TX 15B Ch23 | 51 82 83 99 47 82 48 93 16 81 00 00 b0 01 f1 
14:29:27 I: (#0) enqueuedCmd: 5
14:29:28 W: while retrieving data: last frame missing: Request Retransmit
14:29:28 I: (#0) sendTimePacket
14:29:28 I: TX 27B Ch40 | 15 82 83 99 47 82 48 93 16 80 05 00 63 89 fd b7 00 00 00 00 00 00 00 00 10 2a 9a 
***
    version: 0.5.41
    wifi_rssi: -79
    mac: 84:F3:EB:25:FB:E4
    sdk: 2.2.2-dev(38a443e)
    cpu_freq: 80
    heap_free: 12136
    sketch_used: 468
    core_version: 3.0.2
    flash_size: 4096
    heap_frag: 1
    max_free_blk: 12016
    reboot_reason: Hardware Watchdog
    esp_type: ESP8266

**Comment by Gerri1** [comment]
Bei meinem WeMos musste ich für den IRQ und CE andere PIN's nehmen (D1 und D2) !
Hast du genügend Leistung für den NRF24L01+ eingestellt?
![Pin](https://user-images.githubusercontent.com/119110321/205310385-f2d442f9-7694-4075-a222-7ed6d8452f4a.PNG)
![Power](https://user-images.githubusercontent.com/119110321/205310397-889d2016-0fb9-4489-b39d-0cf05aa8424f.PNG)

**Comment by stefan123t** [comment]
Du kannst auch D3 und D4 tauschen. Der Wemos D1 mini hat manchmal Probleme mit IRQ an D3.

**Comment by helibub** [comment]
Hey,

 

Denke auch dass es an den Pins liegen muss … Test ich mal und Danke vorerst.

 

LG

Helmut

 

Von: Gerri1 ***@***.***> 
Gesendet: Freitag, 2. Dezember 2022 15:05
An: lumapu/ahoy ***@***.***>
Cc: helibub ***@***.***>; Author ***@***.***>
Betreff: Re: [lumapu/ahoy] HM 400 not available (Issue #473)

 

Bei meinem WeMos musste ich für den IRQ und CE andere PIN's nehmen (D1 und D2) !
Hast du genügend Leistung für den NRF24L01+ eingestellt?
 <https://user-images.githubusercontent.com/119110321/205310385-f2d442f9-7694-4075-a222-7ed6d8452f4a.PNG> 
 <https://user-images.githubusercontent.com/119110321/205310397-889d2016-0fb9-4489-b39d-0cf05aa8424f.PNG>

**Comment by mroenne2022** [comment]
@helibub ,  Ich hab meinen Wemos D1 Mini 
![Pinout_Wemos](https://user-images.githubusercontent.com/114778920/205369555-03b0fd81-ee65-4d82-b2cd-3f4a9849c08b.jpg)
wie folgt in Betrieb :

**Comment by helibub** [comment]
Danke mal für die Pinouts aber hat bei mir nicht gefruchtet.

 

Receive success: 0

Receive fail: 0

Frames received: 0

Send Cnt: 5

 

Inverter #0: HM-400 (v0) is not available and is not producing

Inverter #1: n/a

Inverter #2: n/a

MQTT: not connected

 

LG

Helmut


Edit (lumapu), E-Mail Header entfernt für bessere Lesbarkeit

**Comment by helibub** [comment]
Besten Danke Gerri1,

 

 

D1 1 und D2 warens und nun alles wie es sein soll 😊

HM-400 Limit 100% (not controlled) | last Alarm: Inverter start

231.90VU_AC

0.06AI_AC

13.60WP_AC

50.01HzFreq

6.30Â°CTemp

3.60kWhYieldTotal

27.00WhYieldDay

14.30WP_DC

95.10%Efficiency

0.00VArP_ACr

 

Liebe Grüße

heli

 

Edit (lumapu), E-Mail Header entfernt für bessere Lesbarkeit
