### ISSUE TITLE
[ESP8266 Ihr NRF24-Modul kann nicht erreicht werden

### ISSUE THREAD

**Issue by AtzeMatze** [lumapu/ahoy#474]
### Platform

ESP8266

### Model name

ESP8266 ESP-12 ESP-12F CH340G CH340 V2 USB WeMos D1 Mini PRO V 3.0.0 WIFI Entwicklung Bord NodeMCU Lua IOT Bord 3,3 V Mit Pins

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |
Pin Bezeichnung

### Connection picture

- [x] I will attach/upload an Image of my wiring

### Version

05.05.41

### Github Hash

wWo finde ich den

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Setup

Betriebszeit: 0 Tage, 00:34:01

ESP-Zeit: 3.12.2022, 09:57:41

Sonnenaufgang: 3.12.2022, 07:36:35
Sonnenuntergang: 3.12.2022, 16:10:10
WLAN-RSSI: -54 dBm

Statistiken:

RX-Erfolg: 0
RX-Fehler: 0
RX keine Antwort: 71
Empfangene Frames: 0
TX-Zähler: 424
Wechselrichter Nr. 0: HM-1500 (v0) ist noch nicht verfügbar
WARNUNG: Ihr NRF24-Modul kann nicht erreicht werden, überprüfen Sie die Verdrahtung und Pinbelegung
WARNUNG: MQTT ist nicht verbunden
Alle 30 Sekunden werden die Werte aktualisiert

### Debug Serial Log output

```shell
Betriebszeit: 0 Tage, 00:34:01

ESP-Zeit: 3.12.2022, 09:57:41

Sonnenaufgang: 3.12.2022, 07:36:35
Sonnenuntergang: 3.12.2022, 16:10:10
WLAN-RSSI: -54 dBm

Statistiken:

RX-Erfolg: 0
RX-Fehler: 0
RX keine Antwort: 71
Empfangene Frames: 0
TX-Zähler: 424
Wechselrichter Nr. 0: HM-1500 (v0) ist noch nicht verfügbar
WARNUNG: Ihr NRF24-Modul kann nicht erreicht werden, überprüfen Sie die Verdrahtung und Pinbelegung
WARNUNG: MQTT ist nicht verbunden
Alle 30 Sekunden werden die Werte aktualisiert
```

### Error description

1) Go to http://ahoy-dtu/setup
2) configure above settings
3) Reboot
4) I did this
5) I expected that
6) and something completely differen happened

**Comment by lumapu** [comment]
@stefan123t ich denke das liegt hier schon wieder an Pinout, wir müssen hier ein neuen default machen. Durch littlefs geht bei bestehenden Systemen nichts verloren.

@AtzeMatze bitte den IRQ Pin und CE tauschen. Sowohl die Lötverbindung als auch in den Einstellungen. Siehe auch issue #473
