### ISSUE TITLE
Wemos D1 with different schematic

### ISSUE THREAD

**Issue by Stratis63b** [lumapu/ahoy#475]
I recently bought a wemos D1 that has different schematic ie
SCK/D5
Misc/D6
Mosi/D7
Ss/d8
D7
D6
D5. The question is do I wire on D5 or on SCK/D5 etc?

**Comment by Stratis63b** [comment]
![16700664321148242744665543731774](https://user-images.githubusercontent.com/119734974/205438159-988a3aef-9e1c-4bfa-a394-7833ff3b5daf.jpg)

**Comment by Solarteur** [comment]
Comparing the connectors from your Wemos D1R2 (?) board to those from the Wemos D1 mini, you can see that
1. the D"x" pins of both boards are connected to the same pins of the ESP8266,
2. the connections D5 and SCK/D5 of the Wemos D1R2 are connected to GPIO14 of the ESP8266 - so they are equivalent.
[sch_d1_mini_v3.0.0.pdf](https://github.com/lumapu/ahoy/files/10153540/sch_d1_mini_v3.0.0.pdf)
[wemos-d1-r2-schematic.pdf](https://github.com/lumapu/ahoy/files/10153544/wemos-d1-r2-schematic.pdf)

**Comment by Sinned42** [comment]
![1670925510658896558238667767675](https://user-images.githubusercontent.com/82511091/207287607-be96835d-1baa-4b13-9184-20f8bcecffa1.jpg)
![16709257209913783828505002675223](https://user-images.githubusercontent.com/82511091/207288047-001adb77-76d7-40d8-9001-121171659c99.jpg)
![16709258319851175463229817135620](https://user-images.githubusercontent.com/82511091/207288136-c073b4f0-28de-4327-93c1-52f0cc6670ba.jpg)
![Screenshot_20221109_105620_com android chrome](https://user-images.githubusercontent.com/82511091/207288219-25b598d0-5d6e-40e5-af8e-7b4584989ae6.jpg)
So funktioniert es bei mir. Sorry für die diletantische Darstellung.
