### ISSUE TITLE
[ESP32]  'Invalid Header' nach Flashing

### ISSUE THREAD

**Issue by FabianCzaja** [lumapu/ahoy#476]
### Platform

ESP32

### Model name

AZ-Delivery ESP-WROOM-32

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection diagram

-

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.41

### Github Hash

4c8a6da

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Setup

Ich komme nicht zum setup

### Error description

1 - ESP32 mit externer Antenne verkabelt
2 - ESP32 an den Rechner angeschlossen
3 - Wie beschrieben den NodeMCU PyFlasher benutzt und mit der ESP32 bin geflashed
4 - Flash war erfolgreich
5 - ESP32 blinkt nach Neustart rapide rot
6 - ESP32 eröffnet keinen Access Point

NodeMCU PyFlasher Output:
![image_2022-12-03_130008155](https://user-images.githubusercontent.com/70538349/205439890-64ead694-1948-486b-90a1-7cc86ea3a6f3.png)

PuTTY Output:
![image_2022-12-03_125632919](https://user-images.githubusercontent.com/70538349/205439754-a077f93c-ea7c-4f91-881b-6f57100f07c3.png)

**Comment by lumapu** [comment]
bitte auch mal https://ahoydtu.de/web_install/ ausprobieren. Evtl klappt es dann

**Comment by FabianCzaja** [comment]
@lumapu hat geklappt, danke.
