### ISSUE TITLE
Inverter Type cannot be detected 

### ISSUE THREAD

**Issue by uwejanssen19** [lumapu/ahoy#479]
Hello,

I am using a 8266 WEMOS MINI and NRF24 with external antenna.
Ahoy software is 0.5.41
Inverter is Hoymiles HM-600 purchased 2021

The inverter can't be detected .
I checked various wirings, and it did not work.
But I found something strange (to me ;-) ) :

My Inverter Serial number is **1141** 720 16837 (see attached)
In the ID coding rules the correct number then would be **1041** 72016837 .

Does it matter ?

(I also tried DEV Version 0.5.47.)

Best Regards,
Uwe Janssen

See log files:

[esp-web-tools-logs.txt](https://github.com/lumapu/ahoy/files/10166285/esp-web-tools-logs.txt)
[WEBLOG.txt](https://github.com/lumapu/ahoy/files/10166286/WEBLOG.txt)
![SERIAL_HM_600_114172016837](https://user-images.githubusercontent.com/50821183/205913068-6f1c529a-2c5f-4c28-acb2-fc2482502b96.jpg)

**Comment by Solarteur** [comment]
1141... for the first 4 digits for a HM-600 is ok - my HM-600 has it too.
Does your HM-600 produce electricity? Only then can a connection to the inverter be established.

**Comment by uwejanssen19** [comment]
Yes, I am aware of that. 
Although I do not know if it is enough. Do you know how much power is required ?

![image](https://user-images.githubusercontent.com/50821183/205958743-bf88a8ab-5cc1-444c-80d9-630e5e2fe6d7.png)

**Comment by Solarteur** [comment]
I don't know the exact minimum, but with an output of approx. 4W, my HR-600 can be reliably reached.

**Comment by uwejanssen19** [comment]
Then it should have worked with a minimum of daylight. 
I usually wait until it produces at least 15 Watts before starting tests.
I also applied a capacitor of 100 uF at the NRF24.
Distance from NRF24 to my HM-600 is maximum 15m (through a window) 
No idea why it does not work.
Do you know the range/power setting relation, just roughly?

Thank you for your help anyway

**Comment by stefan123t** [comment]
Hi @uwejanssen19,

I looked at your logs and apparently the NRF24 can be found via SPI. We can not test via software whether the IRQ is connected too. There are several reports that the out-of-box pinout may not work for a Wemos D1 mini. Though we do not know the exact reason as it seems to be depending on the model / make of the Wemos D1 mini. Maybe you can supply a picture of yours.
Common workaround is to either switch GPIO0 D3 & GPIO2 D4 connected to IRQ and CE. Some have also reported that instead using GPIO5 D1 and GPIO4 D2 for these two connections gives good results too.
As you can see the green SPI lines are fixed to D5..D8 as well as the GND and +3.3V.
![image](https://user-images.githubusercontent.com/11159753/205973735-fcf25337-48fe-48d8-9d90-2412f342ef7c.png)

The PA Level ist set to `RF Power Amplifier	= PA_HIGH` for your NRF24.
The reason we recommend a good Power Supply, new cables and an Elko close to the NRF module is that the regulator for 3.3.V supply on the Wemos D1 mini boards is a little bit low spec for the current consumption of the NRF during sending.
Did you try to use a different USB Power Supply, shorter / different cable or keep it plugged into the PC ?

**Comment by uwejanssen19** [comment]
Hello Stefan,
thank you very much for your info.
Power supply:
I have a wall Plug with 5V/2A and for working with the PC connection I am using a good USB 3.0 Hub with external power.
 
Connections:
 As you and others already recommended I swapped IRQ and CE. 
 In my last setup I used D2 for IRQ and D1 for CE .
Of course I changed the assignment in ahoy.
You might connect to my device if it is of any use:

[http://xdbu92gos1irkzbd.myfritz.net:8070/](url)

I'll leave that connection available .

19:53 Comment update: Now I think I understand the power supply problem better. Having a good USB power source is just one condition. If the NRF24 needs more than the WEMOS' 3.3 V regulator can provide the voltage might become unstable when transmitting.
I will try with an separate  stable external 3.3V  power supply for the RF24 tomorrow.

Thank you a lot,
Uwe Janssen
![assembly](https://user-images.githubusercontent.com/50821183/205984406-06a77af8-656f-4e24-bab9-4b3edf8531c2.jpg)
![wemos_cpu_side](https://user-images.githubusercontent.com/50821183/205983038-d494519d-0713-4173-a70a-27e8953b3a86.jpg)
![wemos_parts_side](https://user-images.githubusercontent.com/50821183/205983043-917c961e-91db-49c6-9625-5f266a895e79.jpg)

**Comment by stefan123t** [comment]
Hi Uwe,
thanks for the URL to your AhoyDTU, I have flipped some switches, i.e. 
* I added some arbitrary Max Module Power of 300 Wp given you have an HM-600.
![image](https://user-images.githubusercontent.com/11159753/206051983-bba3d5cc-b5d9-4476-a860-e9e93e2281d6.png)

* I also added the [x] Serial Debug option.

Unfortunately I cannot see the Boot messages where it should tell us, whether it could initialize the NRF module.
Can you upload the **USB Serial boot logs** tomorrow again ?

Could you also post a picture of your NRF model and fill in / double check & correct your Pinout diagram?

nRF24L01+ Pin | ESP8266 GPIO
-- | --
Pin 1 GND [*] | GND
Pin 2 +3.3V | +3.3V
Pin 3 CE | GPIO5 CE D1
Pin 4 CSN | GPIO15 CS D8
Pin 5 SCK | GPIO14 SCLK D5
Pin 6 MOSI | GPIO13 MOSI D7
Pin 7 MISO | GPIO12 MISO D6
Pin 8 IRQ | GPIO4 IRQ D2

The Wemos D1 mini you have shown should be capable of running the show, especially given that you want to substitute the Voltage regulator by an external one.
Oh but please make sure to solder the electrolytic cap directly to the NRF24 modules GND and +3.3V pins 1&2 as this is what actually draws the current while sending.
There have been suggestions that using thicker cables instead of jumper wires may improve the situation too.
Though I have mine running with an ESP8266 NodeMCU v3 board with normal 10cm Jumpers and no problems whatsoever.
But then this might have a different voltage regulator on board.

**Comment by uwejanssen19** [comment]
Good Morning,

First: It still does not work 👎 
  
(Although) made changes as proposed:

- shorter cables
- cap 100uF to VCC and GND close to RF24 (applied yesterday already)
- extra power supply for RF24 (3.4 V, max. 0.3 A which never has been exceeded)


Wiring is the same you sent. I double checked it during exchanging jumper cables.

Boot log from serial:
![image](https://user-images.githubusercontent.com/50821183/206131886-135c13e3-93cf-4f87-b3fd-236fa75c8458.png)
NRF24 Picture:
![NRF24](https://user-images.githubusercontent.com/50821183/206133286-af52ced0-c455-45d2-a715-582d1f906316.jpg)
Inverter Power:
![image](https://user-images.githubusercontent.com/50821183/206136644-a9f74336-4d62-46c2-8e36-74c388e554e6.png)
Log File
[esp-web-tools-logs (1).txt](https://github.com/lumapu/ahoy/files/10174496/esp-web-tools-logs.1.txt)

**Comment by uwejanssen19** [comment]
Hi Stefan,
I read [something](https://wolles-elektronikkiste.de/nrf24l01-2-4-ghz-funkmodule) about NRF24 and got at least some data from inverter:
![image](https://user-images.githubusercontent.com/50821183/206194400-b9afb406-5bb7-45a3-bc54-1381cde2d3ca.png)
I wrapped the board in plastic then in aluminium tape in order to shield it.
It is not yet stable at all but at least the wiring and config appear correct.

Thank you a lot for your effort,
Uwe

**Comment by stefan123t** [comment]
@uwejanssen19 I can see two things:
* your NRF24 module has an Power Amplifier PA+LNA Low Noise Attribution. It is usually sufficient to run it at PA Level LOW / MIN.
* your MQTT seems to be configured but not reachable. Please consider to reset to Factory Defaults to correct this and have it set up without MQTT broker.


```
I: MQTT disconnected, reason: TCP disconnect
I: enqueued cmd failed/timeout
```

**Comment by stefan123t** [comment]
From your link:

Falls ihr ein „nRF24L01 + PA + LNA“ Modul verwendet, dann wird es auf der Transmitterseite mit der **Stromversorgung** über den 3.3 Volt Pin **eng**. Der Arduino UNO und der Nano liefern nur 50 Milliampere. Für den Testbetrieb über kurze Distanz könnt ihr die **Sendeleistung herunterregeln**, ansonsten solltet ihr eine potentere Stromquelle wählen.

**Comment by stefan123t** [comment]
From your link:

> Falls ihr ein „nRF24L01 + PA + LNA“ Modul verwendet, dann wird es auf der Transmitterseite mit der **Stromversorgung** über den 3.3 Volt Pin **eng**. Der Arduino UNO und der Nano liefern nur 50 Milliampere. Für den Testbetrieb über kurze Distanz könnt ihr die **Sendeleistung herunterregeln**, ansonsten solltet ihr eine potentere Stromquelle wählen.
