### ISSUE TITLE
Keine Verbindung nach Flash auf 0.5.47

### ISSUE THREAD

**Issue by Gerri1** [lumapu/ahoy#480]
### Platform

ESP8266

### Model name

NodeMCU LoLin v3

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D1 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D2 |

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.47

### Github Hash

?

### Build & Flash Method

Platform IO (build & flash)

### Desktop

Windows

### Setup

N/V

### Error description

1) Download der .bin von https://ahoydtu.de/web_install/  und -/ oder  Download des Projekts von Github
2) Flash mit ESP-Tools und -/ oder PlatformIO
3) Reboot
4) ESP8266 LED blinkt sehr schnell für cs. 30s
5) Keine Verbindung zum AP

**Comment by Gerri1** [comment]
Das update von 0.5.41 auf 0.5.47 hat wunderbar funktioniert.
Ein Flash auf einen leeren ESP8266 schlug fehl! Bei allen Varianten die ich zum Flashen verwendet habe, kam das gleiche Endresultat heraus, die blaue LED blinkt für ca. 30s wie verrückt und danach Funkstille.
Es erscheint kein AP und der ESP lässt sich in keinster Weise ansprechen.

**Comment by knickohr** [comment]
Kann ich bestätigen. Ein Flash auf einen noch nicht beschmutzten 😅 8266 oder auch 32er schlägt fehl. Erst wenn man vorher eine ältere (z.B. 41) aufspielt und per OTA auf die 47 Updates funktioniert es.

**Comment by lumapu** [comment]
kann man einen ESP wieder jungfräulich machen?

**Comment by knickohr** [comment]
Eigentlich nicht. Ist das Häutchen mal durch 😅

müßte man wirklich mal probieren ob ein Bespielen mit Nullen über den ganzen Flash funktioniert.

**Comment by lumapu** [comment]
oder die erase Funktion des online Installer genügt... muss ich Mal probieren.
Sonst könnte man einfach den littlefs Bereich Nullen, zB per factory reset

**Comment by Rik74** [comment]
Kann ich ein Stück weit auch bestätigen, nur das bei mir die LED normal zu sein scheint...

**Comment by lumapu** [comment]
habe den Fehler gefunden und gefixt, hatte noch einen jungfräulichen ESP

**Comment by Gerri1** [comment]
... TOP, fuktioniert wieder!!! 😁👍

**Comment by Rik74** [comment]
Kurze Frage von einem Anwender - nicht Programmierer oder Entwickler :)

Wie bekomme ich diesen Code nun geflashed? Oder Warten bis es ein neues Release gibt?

**Comment by Gerri1** [comment]
Das dev bekommst du von der Ahoy Seite https://ahoydtu.de/web_install/  unter https://nightly.link/lumapu/ahoy/workflows/compile_development/development03/ahoydtu_dev.zip

**Comment by Rik74** [comment]
> Das dev bekommst du von der Ahoy Seite https://ahoydtu.de/web_install/ unter https://nightly.link/lumapu/ahoy/workflows/compile_development/development03/ahoydtu_dev.zip

okay, das habe ich gefunden - aber welche BIN-Datei zum manuellen flashen verwende ich von denen? Ich habe einen ESP 8266, würde daher die 221208_ahoy_0.5.50_esp8266_a9e4429.bin nehmen, oder liege ich da falsch?

sorry für die Anfänger-Fragen :)

**Comment by Gerri1** [comment]
Die 221208_ahoy_0.5.50_esp8266_a9e4429.bin nehmen! 😁

**Comment by Rik74** [comment]
> Die 221208_ahoy_0.5.50_esp8266_a9e4429.bin nehmen! 😁

Danke! gestern eingespielt, heute die ersten Daten wieder übermittelt bekommen 👍
