### ISSUE TITLE
Documentation bug, REST API set power limit

### ISSUE THREAD

**Issue by marseib** [lumapu/ahoy#482]
Hi, 

there is an error in the documentation for the REST API  in https://github.com/lumapu/ahoy/blob/main/User_Manual.md

The correct endpoint for setting the power limit is **/api/ctrl** and not **/api**
https://github.com/lumapu/ahoy/blob/4c8a6dab2f1bd599fb2653a775d61ad480633c38/User_Manual.md?plain=1#L138

The correct json payload is
```
{
  "inverter": 0,
  "cmd": 11,
  "tx_request": 81,
  "payload": [10,1]
}
```
and not 
https://github.com/lumapu/ahoy/blob/4c8a6dab2f1bd599fb2653a775d61ad480633c38/User_Manual.md?plain=1#L162-L168

The other examples are wrong, too.

I found the correct endpoint and format by analyzing the UI, Serial Console. 
But anyway, thanks for the great work 👍

**Comment by lumapu** [comment]
thank you for pointing this out. The next version will be different on this point. MQTT and REST will have the same functionality. Sadly it will not be compatible with the current release.

In the meantime you can test the latest development build, downloadable from https://ahoydtu.de/web_install
It already includes the mentioned chances.

development User_Manual:
https://github.com/lumapu/ahoy/blob/development03/User_Manual.md

Edit: Link to development User_Manual
