### ISSUE TITLE
HMS -series support ??

### ISSUE THREAD

**Issue by Mart-Muc** [lumapu/ahoy#484]
Hab mich grad gewundert, warum der HM600 plötzlich so im Preis verfallen ist..

siehe da- es gibt ne neue **HMS**-Serie

Wie schaut da das Protokoll aus? 
   Ist das kompatibel?
       Hat jemand schon einen HMS und arbeitet an der Integration?

Danke

**Comment by stefan123t** [comment]
Siehe #233 und #hms-hmt-serie im Discord
