### ISSUE TITLE
keine Verbindung zum Inverter

### ISSUE THREAD

**Issue by Basti77** [lumapu/ahoy#485]
Hallo Zusammen.

Der Zusammenauen und das Flashen der DTU war nicht schwer.
Der Adapter wird scheinbar auch erkannt vom ESP aber irgendwas scheint das nicht zu passen. Ich bekomme immer nur die Meldung:
Inverter #0: Garage (v0) is not available and is not producing

Ich habe diverse Build Versionen ausprobiert 
Darunter die aktuelle 0.5.14. und die dev

Inverter HM-1200 für die SN bin ich eben extra noch mal aufs Dach geklettert.

Zwischen der DTU und dem Inverter sind 4m und eine Wand.
Ich weiß nicht wie sich eine nicht + Version verhält. Kann es sein das mir eine falsche Version geliefert wurde, oder wie kann ich das erkennen? 

## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: (https://de.aliexpress.com/item/32280738812.html?spm=a2g0o.order_list.order_list_main.35.39fe5c5fdi2ftH&gatewayAdapt=glo2deu)

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode ? sollte es sein
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ x] circuit board
* [ ] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO04 IRQ  D2 |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [ x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0.5_.17__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [ x] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [ x] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Gerri1** [comment]
Siehe mal https://github.com/lumapu/ahoy/issues/473
Hat das nRF24L01 eine aufschraubbare -oder die Leiterbahnantenne?
Bei der 2. Variante müsstest du auf alle Fälle eine gute Stromversorgung (auch Kondensator) zum Modul haben und die Sendeleistung eher höher stellen! Bei meinem nRF24L01+ Modul mit ext. Antenne reicht die MIN Einstellung völlig aus!
Auch wirst du um diese Uhrzeit keine Verbindung mehr zu den WR bekommen!

**Comment by Basti77** [comment]
danke für die Antwort. 
Offensichtlich ist das ganze doch nicht Plug n play.
ich lesen mich dann man tiefer ein...

**Comment by stefan123t** [comment]
@Basti77 laut dem Link auf die Händler Seite handelt es sich um ein kleines Modul mit Leiterbahnantenne.
Es gibt eine Rückmeldung von einem Schweizer Käufer, dass das Modul auch mit AhoyDTU geht :grinning: 
Auf dem Chip (Foto) kann man die Bezeichnung NRF24L01+ lesen, obwohl die Beschreibung also die 250kBps nicht explizit erwähnt würde ich also mal davon ausgehen, daß das Modul in Ordnung ist.
Die kleinen Module brauchen i.d.R. ein stärkere Sendeleistung. Versuche mal ob Du mit PA HIGH Empfang bekommst. MAX ist nicht zu empfehlen, da das meist die Spannungsversorgung nicht verkraftet. Es ist auch zu empfehlen einen Elektrolyt Kondensator mit 47/100uF an die Pins 1 & 2 (GND & +3.3V) des NRF Moduls zu löten damit die Spannung nicht einbrechen kann.
Du hast das o.g. Connection Diagram nicht ausgefüllt. Bitte oben anpassen und mit der von Dir verwendeten Schaltung neu speichern. Danke! Ein Bild vom Aufbau Deiner Schaltung sagt meistens auch mehr aus.

**Comment by Basti77** [comment]
Der Elko wurde QnD angelötet.
Die verdrahtungsliste wurde oben aktualisiert. 
Ich hatte initial mit der Grundkonfiguration begonnen und probiert IRQ auf benachbarte Pins zu mappen.
Das einzige was ich dabei bemerke, das die wenn die Verdrahtung nicht zur Config passt, dass das Modul dann nicht gefunden wird. 
Die Einstellungen standen immer auf High.
ansonsten passiert leider nichts. :(
Der  HM-1200 Inerter arbeitet auch. 
![DSC_1490](https://user-images.githubusercontent.com/8112783/206852575-e5bfd8c7-1c20-4ec0-8ece-d3102ec91a69.JPG)
![DSC_1491](https://user-images.githubusercontent.com/8112783/206852576-b213b5d3-35f7-4ef8-a7ab-a24d1df29f1e.JPG)

**Comment by Gerri1** [comment]
Wie hast du das verbunden?
Auf dem Bild unten ist meine Anschlussbelegung, die Standardbelegung CE --> D4 und IRQ --> D3 hatte auf keinen meiner ESP's funktioniert!

![Pinout](https://user-images.githubusercontent.com/119110321/206858104-4e6e2207-1596-4932-8cbc-1b8be7d9f5ae.PNG)

**Comment by Basti77** [comment]
CE habe ich durch Deinen Hinweis auf D2 geändert.
Nun warte ich auf morgen.

Edit:
leider brachte das ändern der PINs nach Deiner Config keine Änderung der Situation.

Receive success: 0
Receive fail: 0
Frames received: 0
Send Cnt: 18

Inverter #0: Garage (v0) is not available and is not producing

Senden scheint das Ding ja zu tun...
kann es auch ganz einfach nur am Inverter liegen? 
(ja der ist auch an. aktuell kommen die daten über einen Sonoff POW)

**Comment by stefan123t** [comment]
Hallo @Basti77 das heisst Du hast jetzt eine Konfiguration gefunden bei der Du immerhin ab und zu Daten vom WR bekommst oder das NRF Modul gefunden wird ?
Vielleicht kannst Du noch mit unterschieldichen Netzteilen für das Wemos D1 mini Board experimentieren ? Hier gab es schon Berichte dass evtl selbst Markenprodukte evtl schlechte Glättung der Spannung o.a. haben und selbst damit kein ordentlicher Betrieb möglich war. Auch die Ausrichtung horizontal und vertikal der Antenne kann grosse Auswirkung auf den Empfang haben. Aus was ist denn die Wand die zwischen Dir und dem WR ist ? Hier sind es Ziegel und Dach da geht es mit so einem kleinen Modul auf 8m mit HIGH und am PC/Laptop.

**Comment by Basti77** [comment]
hi Stefan. 
Nein laut log sendet das Modul fleißig aber es kommt nie etwas zurück, egal bei welcher PIN Konfig. 
Aktuell sind nur noch 2m zwischen Modul und WR und eine Wand.
leider werde ich vor Freitag keine weiteren Erkenntnisse gewinnen (wegen Arbeit und danach keine Sonne) 
dann werde ich andere Netzteile / Powerbanks testen. 
danach fehlt eigentlich nur ein Test mit einem andern WR für ein vollständige Aussage.

**Comment by stefan123t** [comment]
Andere Nutzer berichten dass es bei Ihnen nur mit D1 IRQ geht. Vielleicht nach D2 auch noch einen Versuch wert ?
Kannst Du mal ein USB Serial Log vom Booten des ESP8266 anhängen, damit sollte geklärt werden ob überhaupt eine Kommunikation mit dem NRF24 modul möglich ist und wenn ja mit welcher RF Data Rate ?
Oder habe ich das USB Serial Log das im Issue Default Template angefragt wird übersehen ?

**Comment by bombastic99** [comment]
Hallo,

habe genau selbiges Problem :Inverter #0: Hoymiles 1000 (v0) is available and is not producing

Modul ist direkt neben Wehselrichter.

**Comment by Basti77** [comment]
@bombastic99 
nicht ganz. du bist ein stück weiter. 
meins " is **not** available"

**Comment by Joe1002C** [comment]
Hallo,
auch ich habe den selben Fehler:
Inverter #0: PV Garage (v0) is not available and is not producing
Ich habe auch schon divere Pin Konfig durchprobiert und bei nicht passenden Varianten gab es eine Fehlermeldung im seriel Log. Bin im Moment ein wenig ratlos...

**Comment by lumapu** [comment]
@Joe1002C was heißt diverse Pin Konfigurationen genau? Hardware und Software (Setup mit reboot) oder nur eines von beiden?

**Comment by Joe1002C** [comment]
@lumapu habe zu jeder Hardwareänderung auch die entsprechende Änderung in setup vorgenommen und danach neu gestartet. So sieht der log aus:
I: enqueuedCmd: 1
I: enqueuedCmd: 5
I: add inverter: PV Garage, SN: 1xxxxxx2264, Power Limit: 100 in %
I: connect to network 'WLAN-Z2xxx ...
...........
.
I: 

----------------------------------------
I: Welcome to AHOY!
I: 
point your browser to http://192.168.2.201
I: to configure your device
I: ----------------------------------------

I: RF24 Amp Pwr: RF24_PA_I: HIGH
I: Radio Config:
SPI Frequency		= 1 Mhz
Channel			= 3 (~ 2403 MHz)
Model			= nRF24L01+
RF Data Rate		= 250 KBPS
RF Power Amplifier	= PA_HIGH
RF Low Noise Amplifier	= Enabled
CRC Length		= 16 bits
Address Length		= 5 bytes
Static Payload Length	= 32 bytes
Auto Retry Delay	= 250 microseconds
Auto Retry Attempts	= 0 maximum
Packets lost on
    current channel	= 0
Retry attempts made for
    last transmission	= 15
Multicast		= Disabled
Custom ACK Payload	= Disabled
Dynamic Payloads	= Enabled
Auto Acknowledgment	= Disabled
Primary Mode		= RX
TX address		= 0xdeadbeef01
pipe 0 (closed) bound	= 0xdeadbeef01
pipe 1 ( open ) bound	= 0x1234567801
pipe 2 (closed) bound	= 0xc3
pipe 3 (closed) bound	= 0xc4
pipe 4 (closed) bound	= 0xc5
pipe 5 (closed) bound	= 0xc6
I: [NTP]: 2022-12-14 22:09:59
I: Requesting Inverter SN 1161xxxxxx

**Comment by lumapu** [comment]
könntest du im Setup noch den Haken bei System Config -> Serial Debug setzen und dann nochmal das Log posten?
Bitte beachte, das der Wechselrichter nur bei Tageslicht antwortet, wenn die PV Module Strom liefern (ca. 1W)

**Comment by Joe1002C** [comment]
Ich habe einfach zu wenig Ahnung von der Materie. Das obige log ist mit den ESP Home Webtools erstellt.
Den Haken im Setup habe ich gesetzt aber ich weiss nicht, wie ich an das log komme.
Vielen Dank für deine Mühe!

**Comment by lumapu** [comment]
Im Menü der Weboberfläche gibt es einen Punkt `Serial / Control`. Dort steht dann der Inhalt in den großen Fenster, das aktualisiert sich alle paar (~30s) Sekunden.

**Comment by Joe1002C** [comment]
Hm, ich finde diesen Punkt nicht. Kann es sein, dass es den in meiner Version 0.5.17 nicht gibt? Oder ist die Weboberfläche immer dieselbe?

**Comment by reserve85** [comment]
das gibt es da nicht, du bist mit der Version 0.5.17 ca. drei Monate zurück.

**Comment by bombastic99** [comment]
Hallo,
hab nun anderes Funkmodul (longrange)  ran...selbes Problem.

Uptime: 0 Days, 00:25:53

ESP-Time: 15.12.2022, 14:37:50

WiFi RSSI: -72 dBm

Statistics:

RX success: 0
RX fail: 0
RX no answer: 7
Frames received: 0
TX cnt: 37
Inverter #0: Hoym1000 (v0) is not yet available
WARN: MQTT is not connected
Every 30 seconds the values are updated


###############


version: 0.5.41
wifi_rssi: -71
mac: xxxanaonym
sdk: 2.2.2-dev(38a443e)
cpu_freq: 80
heap_free: 12064
sketch_used: 468
core_version: 3.0.2
flash_size: 4096
heap_frag: 1
max_free_blk: 11968
reboot_reason: External System
esp_type: ESP8266

**Comment by bombastic99** [comment]
...nicht das bei uns die falsche Seriennummer draufgeklebt wurde ;-)

**Comment by Basti77** [comment]
n/a15:30:20 I: [NTP]: 2022-12-15 14:30:20 UTC
15:30:33 I: enqueued cmd failed/timeout
15:30:33 I: (#0) I: no Payload received! (retransmits: 0)
15:30:33 I: resetPayload: id: 0
15:30:33 I: (#0) Requesting Inv SN 106160900697
15:30:33 I: (#0) enqueuedCmd: 11
15:30:33 I: (#0) enqueuedCmd: 1
15:30:33 I: (#0) enqueuedCmd: 5
15:30:33 I: (#0) sendTimePacket
15:30:33 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f 89 00 00 00 00 00 00 00 00 a4 c7 3a 
15:30:34 W: while retrieving data: last frame missing: Request Retransmit
15:30:34 I: (#0) sendTimePacket
15:30:34 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f 89 00 00 00 00 00 00 00 00 a4 c7 3a 
15:30:36 W: while retrieving data: last frame missing: Request Retransmit
15:30:36 I: (#0) sendTimePacket
15:30:36 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f 89 00 00 00 00 00 00 00 00 a4 c7 3a 
15:30:38 W: while retrieving data: last frame missing: Request Retransmit
15:30:38 I: (#0) sendTimePacket
15:30:38 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f 89 00 00 00 00 00 00 00 00 a4 c7 3a 
15:30:40 W: while retrieving data: last frame missing: Request Retransmit
15:30:40 I: (#0) sendTimePacket
15:30:40 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f 89 00 00 00 00 00 00 00 00 a4 c7 3a 
15:30:43 W: while retrieving data: last frame missing: Request Retransmit
15:30:43 I: (#0) sendTimePacket
15:30:43 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f 89 00 00 00 00 00 00 00 00 a4 c7 3a 
15:31:03 I: enqueued cmd failed/timeout
15:31:03 I: (#0) I: no Payload received! (retransmits: 5)
15:31:03 I: resetPayload: id: 0
15:31:03 I: (#0) Requesting Inv SN 106160900697
15:31:03 I: (#0) sendTimePacket
15:31:03 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 2f a7 00 00 00 00 00 00 00 00 0f 18 6a 
15:31:04 W: while retrieving data: last frame missing: Request Retransmit
15:31:04 I: (#0) sendTimePacket
15:31:04 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 2f a7 00 00 00 00 00 00 00 00 0f 18 6a 
15:31:06 W: while retrieving data: last frame missing: Request Retransmit
15:31:06 I: (#0) sendTimePacket
15:31:06 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 2f a7 00 00 00 00 00 00 00 00 0f 18 6a 
15:31:08 W: while retrieving data: last frame missing: Request Retransmit
15:31:08 I: (#0) sendTimePacket
15:31:08 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 2f a7 00 00 00 00 00 00 00 00 0f 18 6a 
15:31:11 W: while retrieving data: last frame missing: Request Retransmit
15:31:11 I: (#0) sendTimePacket
15:31:11 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 2f a7 00 00 00 00 00 00 00 00 0f 18 6a 
15:31:13 W: while retrieving data: last frame missing: Request Retransmit
15:31:13 I: (#0) sendTimePacket
15:31:13 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 2f a7 00 00 00 00 00 00 00 00 0f 18 6a 
15:31:33 I: enqueued cmd failed/timeout
15:31:33 I: (#0) I: no Payload received! (retransmits: 5)
15:31:33 I: resetPayload: id: 0
15:31:33 I: (#0) Requesting Inv SN 106160900697
15:31:33 I: (#0) sendTimePacket
15:31:33 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 05 00 63 9b 2f c5 00 00 00 00 00 00 00 00 a9 ac 1e 
15:31:34 W: while retrieving data: last frame missing: Request Retransmit
15:31:34 I: (#0) sendTimePacket
15:31:34 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 05 00 63 9b 2f c5 00 00 00 00 00 00 00 00 a9 ac 1e 
15:31:37 W: while retrieving data: last frame missing: Request Retransmit
15:31:37 I: (#0) sendTimePacket
15:31:37 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 05 00 63 9b 2f c5 00 00 00 00 00 00 00 00 a9 ac 1e 
15:31:39 W: while retrieving data: last frame missing: Request Retransmit
15:31:39 I: (#0) sendTimePacket
15:31:39 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 05 00 63 9b 2f c5 00 00 00 00 00 00 00 00 a9 ac 1e 
15:31:41 W: while retrieving data: last frame missing: Request Retransmit
15:31:41 I: (#0) sendTimePacket
15:31:41 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 05 00 63 9b 2f c5 00 00 00 00 00 00 00 00 a9 ac 1e 
15:31:43 W: while retrieving data: last frame missing: Request Retransmit
15:31:43 I: (#0) sendTimePacket
15:31:43 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 05 00 63 9b 2f c5 00 00 00 00 00 00 00 00 a9 ac 1e 
15:32:03 I: enqueued cmd failed/timeout
15:32:03 I: (#0) I: no Payload received! (retransmits: 5)
15:32:03 I: resetPayload: id: 0
15:32:03 I: (#0) Requesting Inv SN 106160900697
15:32:03 I: (#0) enqueuedCmd: 11
15:32:03 I: (#0) enqueuedCmd: 1
15:32:03 I: (#0) enqueuedCmd: 5
15:32:03 I: (#0) sendTimePacket
15:32:03 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f e3 00 00 00 00 00 00 00 00 06 11 24 
15:32:05 W: while retrieving data: last frame missing: Request Retransmit
15:32:05 I: (#0) sendTimePacket
15:32:05 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f e3 00 00 00 00 00 00 00 00 06 11 24 
15:32:07 W: while retrieving data: last frame missing: Request Retransmit
15:32:07 I: (#0) sendTimePacket
15:32:07 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f e3 00 00 00 00 00 00 00 00 06 11 24 
15:32:09 W: while retrieving data: last frame missing: Request Retransmit
15:32:09 I: (#0) sendTimePacket
15:32:09 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f e3 00 00 00 00 00 00 00 00 06 11 24 
15:32:11 W: while retrieving data: last frame missing: Request Retransmit
15:32:11 I: (#0) sendTimePacket
15:32:11 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f e3 00 00 00 00 00 00 00 00 06 11 24 
15:32:13 W: while retrieving data: last frame missing: Request Retransmit
15:32:13 I: (#0) sendTimePacket
15:32:13 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 2f e3 00 00 00 00 00 00 00 00 06 11 24 
15:32:33 I: enqueued cmd failed/timeout
15:32:33 I: (#0) I: no Payload received! (retransmits: 5)
15:32:33 I: resetPayload: id: 0
15:32:33 I: (#0) Requesting Inv SN 106160900697
15:32:33 I: (#0) sendTimePacket
15:32:33 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 01 00 00 00 00 00 00 00 00 0d fa 33 
15:32:35 W: while retrieving data: last frame missing: Request Retransmit
15:32:35 I: (#0) sendTimePacket
15:32:35 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 01 00 00 00 00 00 00 00 00 0d fa 33 
15:32:36 I: save settings
14:33:38 I: [NTP]: 2022-12-15 14:33:38 UTC
14:33:51 I: enqueued cmd failed/timeout
14:33:51 I: (#0) I: no Payload received! (retransmits: 0)
14:33:51 I: resetPayload: id: 0
14:33:51 I: (#0) Requesting Inv SN 106160900697
14:33:51 I: (#0) enqueuedCmd: 11
14:33:51 I: (#0) enqueuedCmd: 1
14:33:51 I: (#0) enqueuedCmd: 5
14:33:51 I: (#0) sendTimePacket
14:33:51 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 30 4f 00 00 00 00 00 00 00 00 a4 8d a9 
14:33:52 W: while retrieving data: last frame missing: Request Retransmit
14:33:52 I: (#0) sendTimePacket
14:33:52 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 30 4f 00 00 00 00 00 00 00 00 a4 8d a9 
14:33:54 W: while retrieving data: last frame missing: Request Retransmit
14:33:54 I: (#0) sendTimePacket
14:33:54 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 30 4f 00 00 00 00 00 00 00 00 a4 8d a9 
14:33:56 W: while retrieving data: last frame missing: Request Retransmit
14:33:56 I: (#0) sendTimePacket
14:33:56 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 30 4f 00 00 00 00 00 00 00 00 a4 8d a9 
14:33:59 W: while retrieving data: last frame missing: Request Retransmit
14:33:59 I: (#0) sendTimePacket
14:33:59 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 30 4f 00 00 00 00 00 00 00 00 a4 8d a9 
14:34:01 W: while retrieving data: last frame missing: Request Retransmit
14:34:01 I: (#0) sendTimePacket
14:34:01 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 0b 00 63 9b 30 4f 00 00 00 00 00 00 00 00 a4 8d a9 
14:34:21 I: enqueued cmd failed/timeout
14:34:21 I: (#0) I: no Payload received! (retransmits: 5)
14:34:21 I: resetPayload: id: 0
14:34:21 I: (#0) Requesting Inv SN 106160900697
14:34:21 I: (#0) sendTimePacket
14:34:21 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 6d 00 00 00 00 00 00 00 00 0f 07 a0 
14:34:22 W: while retrieving data: last frame missing: Request Retransmit
14:34:22 I: (#0) sendTimePacket
14:34:22 I: TX 27B Ch75 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 6d 00 00 00 00 00 00 00 00 0f 07 a0 
14:34:24 W: while retrieving data: last frame missing: Request Retransmit
14:34:24 I: (#0) sendTimePacket
14:34:24 I: TX 27B Ch3 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 6d 00 00 00 00 00 00 00 00 0f 07 a0 
14:34:27 W: while retrieving data: last frame missing: Request Retransmit
14:34:27 I: (#0) sendTimePacket
14:34:27 I: TX 27B Ch23 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 6d 00 00 00 00 00 00 00 00 0f 07 a0 
14:34:29 W: while retrieving data: last frame missing: Request Retransmit
14:34:29 I: (#0) sendTimePacket
14:34:29 I: TX 27B Ch40 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 6d 00 00 00 00 00 00 00 00 0f 07 a0 
14:34:31 W: while retrieving data: last frame missing: Request Retransmit
14:34:31 I: (#0) sendTimePacket
14:34:31 I: TX 27B Ch61 | 15 60 90 06 97 81 48 09 38 80 01 00 63 9b 30 6d 00 00 00 00 00 00 00 00 0f 07 a0 


ich habe es heute etwas früher nach Hause geschafft. 

wenn man Commands auf Restart drückt kommt es zu einem Speicher Überlauf  im log den text konnte ich nicht kopieren weil es nur noch am scrollen war. 
![image](https://user-images.githubusercontent.com/8112783/207888558-65169b1f-421c-4206-9cab-53db07a8e1bf.png)

**Comment by Joe1002C** [comment]
Bei mir hat es jetzt geklappt. Ich habe heute ein anderes NRF24L01+ bekommen und angeschlossen. Hat dann auf anhieb funktioniert. Dann noch ein Update auf die aktuelle Version gemacht und siehe da, hat auch geklappt. Das NRF24L01+ was ich zuerst dran hatte war eines mit externer Antenne, das aktuelle ist ohne externe Antenne. Habe  ca. 10m Abstand zum WR und 2 Wände dazwischen. Scheint aber stabil zu laufen.
Vielen Dank für eure Mühe!

**Comment by Basti77** [comment]
@Joe1002C 
Hast Du eine Link zu dem Modul welches bei Dir funktioniert?

**Comment by Joe1002C** [comment]
@Basti77 
Das Modul ist vom Makershop über Ebay.

**Comment by stefan123t** [comment]
@Basti77 Du hast m.E. einen von AhoyDTU aktuell (noch) nicht unterstützten Wechselrichter der Gen2: MI-XXX
Da wirst Du vermutlich eher mit dem Fork von Ziyat T. zu einem Ergebnis kommen.
> 15:30:33 I: (#0) Requesting Inv SN 106160900697

@lumapu ich glaube wir können an dieser Stelle das Issue zu machen, da wir aktuell keine MI- Wechselrichter in Ahoy unterstützen. 
Eventuell sollten wir in unserem Issue Template die Frage nach den ersten fünf Stellen der Serial Number stellen, damit wir solche Schwierigkeiten in Zukunft frühzeitig erkennen können ?

**Comment by stefan123t** [comment]
Siehe Link zu https://github.com/Ziyatoe/DTUsimMI-Hoymiles in #496.
