### ISSUE TITLE
[ESP8266] Wrong negative temperature values

### ISSUE THREAD

**Issue by ps915** [lumapu/ahoy#486]
### Platform

ESP8266

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

![IMG-20220820-WA0021](https://user-images.githubusercontent.com/3420935/206851722-12fd601d-1d09-4420-bba6-8387f41f6b7d.jpg)

### Version

0.5.17

### Github Hash

g5402e9b

### Build & Flash Method

Platform IO (build & flash)

### Desktop

Windows

### Setup

<img width="545" alt="Bildschirmfoto 2022-12-09 um 19 04 30" src="https://user-images.githubusercontent.com/3420935/206765164-d17f2064-3a22-4756-9e49-c9a22f6bf521.png">

### Error description

After it got cold in germany, my AHOY seems to send some strange temperature values. It happens from time to time, and works normally again randomly (no reboot required)

See attached screenshot:

<img width="968" alt="Bildschirmfoto 2022-12-09 um 09 36 58" src="https://user-images.githubusercontent.com/3420935/206765425-26cee389-8256-4995-ad1b-716a80cac2ed.png">

<img width="968" alt="Bildschirmfoto 2022-12-09 um 09 37 06" src="https://user-images.githubusercontent.com/3420935/206765355-3bf97085-58c5-4cac-8c2a-4f54e25f0f97.png">

Its seems, that the value of the **Active Power Limit** will overwrite the temperature reading of the inverter. When i delete the **Active Power Limit** and hit save, the same value will appear again.

**Comment by Gerri1** [comment]
Nimm mal die 0.5.28 zum Testen!

**Comment by knickohr** [comment]
Ich würde wohl eher sagen, irgendwas kann keine Minustemperaturen handeln. Ob’s jetzt die Anzeige auf der Seite oder generell ein Variablenproblem ist, muß noch geklärt werden.

Bei mir ist es noch nicht so kalt. Aber warten wir mal bis Montag.

Nutzt Du MQTT ?  Was kommen da für Werte ?

**Comment by Gerri1** [comment]
Bis jetzt läuft meine Temperaturerfassung ohne Probleme (0.5.28)! 

![Temp](https://user-images.githubusercontent.com/119110321/206860961-5b529842-d4c3-4315-88ee-dfedf05845ef.PNG)

**Comment by ps915** [comment]
Ich logge auch alles per MQTT -> FHEM -> MySQL -> Grafana. Die falschen Werte werden von MQTT bis Grafana so durchgereicht. Ich habe es nur bemerkt, da mein Verlaufsdiagramm so komisch aussah, da 45 Datensätze mit einer Temperatur von 6553°C gespeichert wurden. 

Ich tippe auch auch Minusgrade. Als es kälter wurde, fing es auch an mit den falschen Werten. Vorher lief es viele Monate fehlerfrei. 

Mein AHOY PCB ist allerdings keinen kalten Außentemperaturen ausgesetzt, nur die beiden Wechselrichter.

**Comment by Gerri1** [comment]
Flash einfach mal die 0.5.28, bei waren schon minus Grade!

**Comment by knickohr** [comment]
Warum nicht gleich die 41 ?

**Comment by ps915** [comment]
habe die 41 geflasht und werde berichten, ob der Fehler nochmal auftritt

**Comment by knickohr** [comment]
Ja, bin auch gespannt. Spätestens ab Montag werde ich auch solche Minusgrade unter Tags haben.

**Comment by mroenne2022** [comment]
Hier sind heute morgen Minus Grade , meine DTU (D1 Wemos Mini) mit 0.5.17 zeigt ebenfalls 6553 Grad an. Eine andere DTU zum Test angeschlossen (ESP32 WROOM mit 30PIN) mit der FW 0.5.41 zeigt heute garnicht mehr die Temp. an !? Anscheinend gibt es tatsächlich Probleme mit den Minus Temp.
![Temp](https://user-images.githubusercontent.com/114778920/206894721-105de0fb-eab9-4dee-a82a-607cecf461f1.jpg)

**Comment by mroenne2022** [comment]
Inzwischen knapp die Plus Grade erreicht im WR , schon ist die Temp. Anzeige wieder mit dabei !
![Screenshot_20221211_102532_Chrome](https://user-images.githubusercontent.com/114778920/206896107-ae7bcbed-0148-4090-8037-f84a21629362.jpg)

**Comment by stefan123t** [comment]
@lumapu Temperatur Temp scheint als unsigned int mit fix Komma interpretiert zu werden ist aber offensichtlich ein signed int mit fix Komma. Bitte ggf korrigieren. Danke !

**Comment by knickohr** [comment]
Ich kann leider heute nicht mitreden, meine DTU ist heute Nacht ausgestiegen und ich habe es erst jetzt bemerkt 😲

**Comment by mroenne2022** [comment]
@knickohr : Ich denke es ist jetzt ja bekannt und es liegt wohl (glaube ich) tatsächlich an den Minusgraden. Wird bestimmt in der nächsten FW gefixt sein. Die Temp. ist ja auch eher im Sommer wichtig wegen einer mgl. Überhitzung des WR.

**Comment by knickohr** [comment]
Trotzdem isses ein Bug 🐞

**Comment by Gerri1** [comment]
Bis heute hat die Temperaturerfassung ohne Probleme funktioniert. Es waren zwar nur -1,8C, aber es wurde richtig ausgelesen!
Nicht dass das an der FW des WR liegt! Ich habe einen HM-400 aus 2020 mit der FW 10010.

![Temp](https://user-images.githubusercontent.com/119110321/206910781-7d5c7334-f7a4-496f-9a93-5f7afe2eb93d.PNG)

**Comment by homeautomation2022** [comment]
Wie viel hier geschrieben wird zu einem Bug, der schon seit geraumer Zeit behoben ist, nur das hier anscheinend einige nicht regelmäßig die neueste FW updaten...
https://github.com/lumapu/ahoy/blob/59b8baab418bcd1dbe04efd2f8292732f1ac3711/src/hm/hmInverter.h#L242-L245

Werte die exakt 0 sind zeigt die Ahoy Live Webseite nicht an, nur so nebenbei zur Info.

**Comment by stefan123t** [comment]
Fixed & working in v0.5.41
