### ISSUE TITLE
keine Daten mehr über mqtt

### ISSUE THREAD

**Issue by DennisXK** [lumapu/ahoy#489]
Zeit ich auf die 5.28 gewechselt bin bekomme ich keine daten mehr in meinen IObroker. Habe auch schon die 5.40 versucht, aber mit der Version bekomme ich erst gar keine Verbindung über den Browser hin....(das ist aber ein anderes Thema)

Für was ist der Button "Discovery Config (homeassistant)" da? Muss man den drücken, dass er die Daten sendet? homeassistant möchte ich eig. nicht wieder in meinem IObroker aufgeführt bekommen...

<a href="https://ibb.co/nLDkkkd"><img src="https://i.ibb.co/nLDkkkd/mqqt.png" alt="mqqt" border="0"></a>

## Hardware
  * [x ] ESP8266

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [ x] circuit board

### Power Stabilization:
* [x ]  100uF Electrolytic Capacitor 

## Software
* [x ] AhoyDTU

### Version / Git SHA: 
Version: 0.5.28

### Build & Flash Method:
* [x] ESP Tools

### Desktop OS:
* [ x] Windows

**Comment by Gerri1** [comment]
Ich gehe davon aus, dass die Einstellungen in der Ahoy-DTU und ioBroker richtig sind und auch der MQTT- Adapter einmal neu gestartet wurde!
Wenn das alles dennoch passen sollte, würde ich die FW über USB neu Flashen, mit Erase !

**Comment by stefan123t** [comment]
@DennisXK  der Button "Discovery Config (homeassistant)" ist genau dafür da: Auto-Discovery der Topics in Home Assistant. Da Du das nicht hast und nicht möchtest solltest Du da auch nicht draufdrücken, sonst gibt es die Struktur eben wieder :smile:

**Comment by DennisXK** [comment]
Ja, die Einstellungen passen und der Adapter wurde auch neu gestartet. In der dtu Übersicht steht auch das er mit mqtt verbunden ist.

**Comment by lumapu** [comment]
bei mir klappt es seit Anfang an mit ioBroker, hier meine mqtt Instanz. Evtl. mal versuchen die Instanz neu zu starten.

![grafik](https://user-images.githubusercontent.com/22733082/208241376-4ddf2412-9ce6-493b-a6c4-a7bb068fbb16.png)

man kann ganz gut mit MQTTX die Daten prüfen: https://mqttx.app/

mein ioBroker läuft auf `10.20.1.1`, hier meine MQTTX Einstellungen
![grafik](https://user-images.githubusercontent.com/22733082/208241701-1cf98122-305f-440e-b645-9df761b04f6d.png)

dann connecten und noch das Topic des Inverters subscriben:
![grafik](https://user-images.githubusercontent.com/22733082/208241715-4523b54f-4acb-4041-b8d8-3780c3839395.png)

**Comment by DennisXK** [comment]
Bei mir hat mqqt auch tiptop von Anfang an funktioniert, bis ich auf 5.28 upgedatet habe🤷‍♂️.

**Comment by lumapu** [comment]
kannst gerne auch die aktuelle Development Version testen:
https://ahoydtu.de/web_install/

gerade sind wir bei 0.5.55

**Comment by DennisXK** [comment]
@lumapu habe mqqtx mal ausprobiert. Kommen leider keine Daten rein. ich werde jetzt mal den D1 mini erasen und neu flashen. evtl gehts dann wieder.

**Comment by DennisXK** [comment]
So habe jetzt die  D1 neu geflasht mit der 5.41. jetzt kommen die Dten im iobroker wieder an. Aber warum legt er eine neune ordner mit mqqt/0/PV-Anlage an? Nur um die Uptime abzulgen? Unter dem eig. mqqt Pfad wird doch schon ein uptime angelegt! leider aber mit dem Wert 0.

<a href="https://ibb.co/M91wds3"><img src="https://i.ibb.co/g6WqY3B/111.png" alt="111" border="0"></a>

**Comment by lumapu** [comment]
bitte die letzte Änderung der MQTT Daten in ioBroker einblenden, nicht dass man hier alte Daten von vorherigen Versuchen sieht.

**Comment by DennisXK** [comment]
Wenn ich den Ordner mqqt unter dem Pfad mqqt/0/ lösche wird er wieder erstellen beim erhalten von neuen Daten🤷‍♂️

**Comment by DennisXK** [comment]
Der IoBroker bringt ebenfalls Meldungen das etwas nicht stimmt!

<a href="https://ibb.co/18VqgJ1"><img src="https://i.ibb.co/Wg9yhpZ/111.png" alt="111" border="0"></a>

**Comment by lumapu** [comment]
wenn ich es richtig sehe ist ein Leerzeichen vor `PV-Anlage`, das wird durch ein `_` ersetzt LP

**Comment by DennisXK** [comment]
Ok, leider ist keine Leerzeichen in den Topic Einstellungen vor dem "PV-Anlage" eingetragen. Finde es extrem merkwürdig, dass er den Ordner HM-600_1 und den mqqt Ordner anlegt.

**Comment by lumapu** [comment]
der Ordner `mqtt.0` ist normal. Danach sollte dein in der Einstellungen gesetztes Topic kommen. In der nächsten Ebene kommen die Namen deiner Wechselrichter. 
Hinweis: Jeder Punkt im Topic oder Namen führt zu einer weiteren Ebene

**Comment by Gerri1** [comment]
> Aber warum legt er eine neune ordner mit mqqt/0/PV-Anlage an? Nur um die Uptime abzulgen? Unter dem eig. mqqt Pfad wird doch schon ein uptime angelegt! leider aber mit dem Wert 0.

Diesen Fehler hatte ich auch schön des öfteren!

Ich hatte den ESP Stromlos gemacht und im ioBroker den kompletten neu erstellten Baum ab MQTT gelöscht. Danach den richtigen Baum komplett zu machen und den Fokus nicht auf MQTT setzen und den Adapter neu starten.
Danach den ESP wieder einschalten und es sollte der Baum wieder richtig angelegt werden!

Falls das der einzige MQTT Client ist, mit dem Namen "PV-Anlage" auch diesen ab PV-Anlage löschen!
Wichtig ist es den MQTT Baum nicht nach dem Neustart des Adapters öffnen, erst nach dem der ESP wieder online ist!

**Comment by DennisXK** [comment]
@Gerri1 Habe ich gemacht. hat auch zum Erfolg geführt. Aber Irgendwie legt er mir immer noch einen Ordner an. 

Mit der ältern Version hatte ich keine Topic "PV-Anlage" aber diesen Ordner HM-600_1 wird mir immer nach dem ich ihn gelöscht habe am nächsten Tag wieder erzeugt.
<a href="https://ibb.co/3r04Kp1"><img src="https://i.ibb.co/dWQjZPB/ahoy.png" alt="ahoy" border="0"></a>

**Comment by Gerri1** [comment]
@DennisXK 
Hast du nach dem Ausschalten der Ahoy-DTU und dem Löschen des Ordners HM... den MQTT Adapter im ioBroker auch mal neu gestartet? Evtl. dein ioBroker auch mal neu Durchstarten!

**Comment by DennisXK** [comment]
@Gerri1 Ja klar erst den Adapter pausiert, Verzeichnisse gelöscht, Ahoy stromlos gemacht, Adapter neu gestartet, Ahoy mit Strom versorgt!

**Comment by Gerri1** [comment]
Ist der HM... Ordner auch unter dem Ordner PV-Anlage vorhanden?
Am besten den auch nochmal "so" löschen!

**Comment by DennisXK** [comment]
Ja unter dem Ordner PV-Anlage ist alles richtig jetzt mit deinem tipp! 
Den Ordner HM-600_1 unter dem Ordner mqtt/0 hatte ich zur mit gelöscht gehabt. kommt aber wie gesagt immer wieder.

**Comment by Gerri1** [comment]
Hast du wirklich beide Ordner mal gelöscht?!

![68747470733a2f2f692e6962622e636f2f6457516a5a50422f61686f792e706e67](https://user-images.githubusercontent.com/119110321/210263192-314694f3-fbd1-4a67-a0ca-18e25413b184.png)
