### ISSUE TITLE
Dev 0.5.51 keine Daten mehr über MQTT an Ahoy

### ISSUE THREAD

**Issue by jimknopf63** [lumapu/ahoy#491]
### Platform

ESP8266

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0,5,51

### Github Hash

221212_ahoy_0.5.51_esp8266_1bba068.bin

### Build & Flash Method

ESP Tools (flash)

### Desktop

Linux

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Ich habe eben von der stabilen 0.5.41 auf die Developer 0.5.51 Update über Ahoy gemacht. Nach erfolgreichen Reboot und Verbindung zum HM friert der Ahoy innerhalb weniger Minuten ein und muss kurz vom Strom getrennt werden für den erneuten Neustart. Ebenfalls kann ich keine PowerLimits per MQTT an den Ahoy senden. Werden nicht angezeigt/umgesetzt. MQTT Verbindung steht aber. Daten werden im IOBroker aktualisiert. Über die Serielle Konsole funktioniert das limitieren. Bin wieder zurück auf die StableVersion.

**Comment by lumapu** [comment]
für `0.5.51` haben sich die MQTT Topics geändert, daher bitte folgendes Manual heranziehen:
https://github.com/lumapu/ahoy/blob/development03/User_Manual.md

Wäre interessant ein Serielles Log (über USB) von dem einfrieren zu bekommen. Evtl. mal versuchen den Haken bei `print inverter data` unter `System Config` in den `Settings` zu deaktivieren.
