### ISSUE TITLE
Feature Request: Test Hoymiles HMS-2000 inverter once Software & Hardware is available

### ISSUE THREAD

**Issue by km1975** [lumapu/ahoy#501]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: HMS-2000-4T
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [x] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [x] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: v0.5.41
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [x] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [x] Windows
* [ ] Mac OS

### Debugging:
* [x] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)
![AhoyDTU](https://user-images.githubusercontent.com/120584681/208106671-d4a2c1b9-8184-4d13-b0ec-5192a2959f6d.PNG)
![Capture2](https://user-images.githubusercontent.com/120584681/208112992-3bb9f04b-518b-4168-b26e-bafb8a51fcb1.PNG)
![Capture3](https://user-images.githubusercontent.com/120584681/208113546-6b46e53e-4981-4aa6-8171-daa3f54a4222.PNG)

Hi Team, 
pls. help to connect a HMS-2000 2m in distance to  the AhoyDTU. 
I tested capture3 as well as CS-D8, CE-D2 and IRQ-D1 without success.
Thx for your great support. PLs. help.
Best Regards,
km

**Comment by stefan123t** [comment]
HMS-2000 is not yet supported. This will not work with NRF24L01+ by the way as Radio Chip used for HMS- and HMT- Series has to be replaced with a CMT2300A or similar. See #233 for current feature request where research and development is taking place.
Closing this as not valid.

**Comment by km1975** [comment]
Thx stefan123t for your fast answer, is there a roadmap or approx planning existing?

**Comment by lumapu** [comment]
@km1975 Yes I'm currently developing a new version of Ahoy which should support next gen Inverters. I will last at least another month to have a binary here.

**Comment by km1975** [comment]
Hi Lukas,

sounds great, if you want me to test something with my HMS-2000 pls. let me
know. I'm really interested to do so.

Mit freundlichem Gruß,

K. Martin


Edit: lumapu Rest von E-Mail geschlöscht für bessere Lesbarkeit

**Comment by bombastic99** [comment]
Hallo, 

habe den HMS 1000, habe ebenfalls Interesse. Falls ich was helfen testen kann bitte melden thx

**Comment by Taube47** [comment]
Hallo, 

gibt es einen neuen Stand? Kann man sich Hoffnungen machen? Die elektrischen Daten des HMS-2000-4T würden bei mir sehr gut passen.

**Comment by biasowicka** [comment]
Czy już działa na HMT-2250 ?

**Comment by lumapu** [comment]
@Taube47 ja wir haben bereits erste Daten auslesen können, allerdings noch keine fertige Firmware. Dauert nicht mehr lange 😊

**Comment by Taube47** [comment]
Hallo,

ich habe totale Hochachtung vor eurer Leistung.

Dann steht meine Entscheidung fest und ich bestelle drei HMS-2000 für drei Standorte. Zusätzlich komme ich günstig an eine "DTU Pro S" und einen Zähler "Chint DTUS666". Ich möchte damit an einem Standort eine Nulleinspeisung realisieren. Kann man später ja wieder verkaufen.

Wie kann ich helfen?  Geht die Entwicklung so weit, daß auch der Chint DTSU666 Zähler eingebunden wird?

**Comment by lumapu** [comment]
das Thema Zähler haben wir noch garnicht betrachtet, daher nein.

**Comment by lumapu** [comment]
bzgl. HMS:
bitte in #904 schauen, da ist auch schon eine Firmware, ansonsten im Branch `hms`.
