### ISSUE TITLE
inverter type can't be detected! Hoymiles HMS 1000

### ISSUE THREAD

**Issue by bombastic99** [lumapu/ahoy#510]
Hallo,

habe einen Hoymiles 1000. Leider klappt das auslesen nicht mit folgender Fehlermeldung:

inverter type can't be detected!
E: unknown inverter type: 11E: 44

**Comment by reserve85** [comment]
MI1000 oder HM1000?

**Comment by DanielR92** [comment]
Die ganze Seriennummer muss hinterlegt sein.
In der Log steht es ja, er kann nichts mit "44" Anfangen.

**Comment by bombastic99** [comment]
Hallo, die Seriennummer ist vollständig hinterlegt (habe die aus Sicherheitsgründen nicht gepostet) 
die 44 steht für  Wechelrichtertyp  den er nicht kennt


HMS 1000 der hat Antenne dran

**Comment by bombastic99** [comment]
![image](https://user-images.githubusercontent.com/43094087/208425454-2cef9903-d32a-401c-8431-31c4c19fe0aa.png)

**Comment by reserve85** [comment]
srry, but HMS type is not supported yet.

**Comment by bombastic99** [comment]
Hallo, hab's mir fast gedacht. 
Danke für Deine Antwort...hast Du Informationen ob das noch kommt oder kann ich das Thema begraben?

**Comment by reserve85** [comment]
hab das hier gefunden: https://github.com/lumapu/ahoy/issues/501
denke das trifft dann auch auf den 1000er zu.

**Comment by DanielR92** [comment]
HMS wird daran gearbeitet... solange kann man dieses issue closen meine ich. :)

**Comment by bombastic99** [comment]
wird derzeit noch nicht unterstützt HMS

**Comment by stefan123t** [comment]
see #233 for implementation progress.
