### ISSUE TITLE
ESP32 Flash Speicheradressen

### ISSUE THREAD

**Issue by Gerri1** [lumapu/ahoy#511]
Hallo zusammen,

wo findet man denn die Speicheradressen für den ESP32, ich habe da in der Doku nirgends was gefunden.
Zum Test habe ich mal die von dem OpenDTU - Projekt genommen, für den Flash mit dem Espressif Flash Download Tool.

bootloader.bin						                        0x1000
partitions.bin						                        0x8000
ota.bin							                        0xe000
221218_ahoy_0.5.56_esp32_ssd1306_c8ec1c1.bin	        0x10000

Ich habe mir ein paar ESP32 mit externer Antenne organisiert, da das WLAN bei denen wesentlich besser ist!
Nun wollte ich mit dem Web Installer der dev Versionen die 0.5.56 mit dem Display SSD1306 Braten, das leider nicht funktionierte, weder beim Chrome noch beim Edge!

Das Flashen mit dem Espressif Flash Download Tool und den o.g. Speicheradressen hatte zwar funktioniert und es war auch der AP vorhanden, aber das war dann schon alles.
Das Ganze versuchte ich dann auch noch mit VS zu Flashen, was auch ohne Probleme vonstatten ging, aber weiter wie auf die Index Seite kam ich dann nicht.

Um auszuschließen, das der ESP keinen Treffer hatte, habe ich dem ESP dann die Standard Version (ESP32) 0.5.41 mit Web Installer verpasst, lief ohne Probleme. Ein nachfolgendes Update auf die 0.5.56 bescherte mich wieder mit den gleichen Problemen, das nichts mehr ging! 😭

Dann habe ich noch eine Frage bzüglich dem ESP32 mit Display SSD1306.
Wie ist hier die PIN Belegung der I2C-Schnittstelle für das Display?

**Comment by knickohr** [comment]
Guckst Du da !  Man beachte auch die Optionen und Häkchrn unten im Flash-Tool.

Empfehlung :  vorher einen Erase machen

wenn gar nichts mehr geht, auf eine stable-Version zurück gehen (momentan die 41) und von dort dann per OTA auf eine neuere.

Sollte es dann immer noch nicht funktionieren, flashe mal eine Fremdsoftware (Tasmota z.B.), danach geht es erfahrungsgemäß wieder.

Der ESP32 ist etwas zickig, es kommt immer wieder zu Hängern und Reboots. Leider, aber wir sind dran.

Pin-Belegung findest Du hier
https://github.com/lumapu/ahoy/pull/401
![6BD18FE4-8369-4EA6-A3FB-806DB7FF173A](https://user-images.githubusercontent.com/63048210/208444594-dc03aa65-cec9-4294-8749-c990a50037fd.jpeg)

**Comment by Gerri1** [comment]
@knickohr ... SUPER, vielen Dank!

Die Einstellungen waren dann so richtig, wie ich sie hatte. 👍😁
Ein Update von der 0.5.41 nach höher muss dann wohl noch warten!
