### ISSUE TITLE
Feature Request: Verbesserungswünsche

### ISSUE THREAD

**Issue by Karlo49** [lumapu/ahoy#512]
## Hardware
  * [x ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: __8266 Pro____
Retailer URL: ______

### nRF24L01+ Module
* [ x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ x] external antenna

### Power Stabilization:
* [ x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [ x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0_.5_._56_
Github Hash: c8ec1c1_______

### Build & Flash Method:
* [ ] Arduino
* [ x] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ x] Linux
* [ ] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ x] Setup settings (use our templates ... to be added)

**Comment by Karlo49** [comment]
Ich benutze nur die Ahoy-DTU in der Webapp auf meinem Linux Desktop.
MQTT habe ich ein bischen getestet, aber bin noch  nicht sicher, ob ich das haben will.
Hier ein paar Dinge, die ich vermisse und gut gebrauchen könnte:
1. Anzeige des Device-Name im Kopf
2. Menue-Leiste ausblendbar
3. Grafic und Schrift auf ca. 75% verkleinerbar
4. Im Setup unter Inverter für jedes Modul ein Feld indem man die erzeugten YieldTotal eintragen kann und diese von den   bisherigen YieldTotal abgezogen werden. Sodas man z.B. zum 1.januar YieldTotal = 0 hat.
Vielen Dank für die bisher geleistete Arbeit.

**Comment by knickohr** [comment]
Ähhh ?   Wo willst Du das haben ?  Auf dem Liveview vom Ahoy, also der Ahoy-Webseite oder im MQTT über Deinen Visualisierer (Node-Red) o. Ä. ?

**Comment by Karlo49** [comment]
Wie geschrieben auf der Ahoy-Webseite

**Comment by knickohr** [comment]
OK,

also bei mir ist das so (siehe Foto), und die Schriftgräße kann man über den Browser für jede Seite im Browser einstellen 🤔

Nummer 4 ist natürlich eine Herausforderung 😉

![04224DC9-5CF6-4B0C-9840-5473132D778F](https://user-images.githubusercontent.com/63048210/208446484-098abf5f-ad03-485d-b95c-f33268610df3.jpeg)

**Comment by Karlo49** [comment]
Schriftgröße ist in der Webapp nicht einstellbar. Dafür ist aber alles drumrum weg.
![Bildschirmfoto vom 2022-12-19 15-27-43](https://user-images.githubusercontent.com/108924478/208448739-ebeb3b0e-982f-41ea-9dcb-ef74e4e8f6e4.png)

**Comment by 1-am-r00t** [comment]
@Karlo49 versuch doch mal entweder [STRG] + "-" / "+" oder alternativ [STRG] + Mausrad rauf/runter. Damlt kannst du im Browser die Schriftgröße an deine Vorlieben anpassen. Das ist glaube ich was @knickohr meinte.

**Comment by stefan123t** [comment]
Gerade Nummer 4. sollte eigentlich ganz interessant sein und m.E. durchaus möglich:
Die Differenz `deltaYieldTotal` zum vorherigen Wert (Prefix `_`) ist ja einfach `YieldTotal - _YieldTotal`
Eventuell könnte man daraus auch gleich den aktuellen Yield pro Zeiteinheit berechnen also `( YieldTotal - _YieldTotal ) / (Timestamp - _Timestamp)`.

Die Werte bzw. das Delta zu einem bestimmten Zeitpunkt nullen, könnte man noch einfacher durch eine virtuelle "Null"-Stelltaste in AhoyDTU verwirklichen. Dazu muss man sich nur den aktuellen YieldTotal zum Zeitpunkt X (z.B. den 1.1.2023) merken und zieht diesen künftig immer von allen YieldTotal Werten ab: Zack, fertig :D Man muss nur den Stand zum 1.1.2023 auch irgendwo notiert haben um ihn dann zurückzusetzen / -rechnen. Wohl dem der das per MQTT irgendwo gespeichert hat. Im Nachhinein ohne diese Daten / Information geht das natürlich nur noch schwierig.

**Comment by jimknopf63** [comment]
> Gerade Nummer 4. sollte eigentlich ganz interessant sein und m.E. durchaus möglich sein: Der Unterschied `deltaYieldTotal` zum vorherigen Wert (Präfix `_`) ist ja einfach `YieldTotal - _YieldTotal`Eventuell könnte man auch gleich den aktuellen Yield pro Zeiteinheit berechnen `( YieldTotal - _YieldTotal ) / (Timestamp - _Timestamp)` > > Die Werte oder das Delta zu einem bestimmten Zeitpunkt null, könnte noch einfacher durch einen virtuellen "Null"-Stelltaste in AhoyDTU zu verwirklichen. Dazu muss man sich nur den aktuellen YieldTotal zum Zeitpunkt X (z.B. den 1.1.2023) merken und zieht diesen künftig immer von allen YieldTotal Werten ab: Zack, fertig :D Man muss nur den Stand zum 1.1.2023 auch irgendwo notiert haben, um ihn dann zurückzusetzen / -rechnen. Wohl dem, was das pro MQTT irgendwo gespeichert hat. Im Nachhinein ohne diese Daten / Information geht das natürlich nur noch schwierig. 

Ich logge die MQTT YieldTotal Daten im IOBroker mit dem SourceAnalytics Adapter. Da kannst Du den Wert für heute, gestern, Woche, Vorwoche,  Monat, Vormonat. Quartal, vorheriges Quartal,halbjahr, vorheriges Halbjahr, jahr, vorheriges Jahr nach Bedarf auswählen für die Statistik

**Comment by lumapu** [comment]
Ich finde den Vorschlag von @jimknopf63 sehr gut. Denn wenn wir anfangen `Yield_Total` zurückzusetzen bzw. zu merken, dann kommen noch weitere Anfragen, ob man da nicht noch dies und das machen kann. 
Ich fände weiterhin sehr gut Ahoy als Bridge zwischen dem 2.4MHz Hoymiles Protokoll und MQTT / JSON zu sehen. 
@Karlo verwendest du eine Smart-Home System?

**Comment by Karlo49** [comment]
@1-am-r00t Danke, mit dem Befehl bekomme ich auch meine Webapp kleiner. Habe lange danach gesucht. Habe auf 80% gestellt. Nun ist aber die Beschriftung unter den Zahlenwerten kaum noch lesbar.
@lumapu Habe ein Raspberrymatic als Heizungssteuerung. Da kommt aber nichts anderes drauf.
Ich halte einen Wert  "YieldYear" für sinnvoll, aber das liegt natürlich am Entwickler, ob er sowas umsetzen will. Werde mich mit "MQTT Mosquitto Telegraf influxDB Grafena" testweise auf einen alten Laptop beschäftigen. Dafür benötige ich dann  das Endprodukt einen Raspberry Pi mit SSD (momentan nicht zu bekommen oder sehr teuer).
Wünsche allen einen guten Rutsch ins neue Jahr.

**Comment by stefan123t** [comment]
@lumapu ja ich finde den Vorschlag / Anfrage von @Karlo49 auch ganz sinnvoll.
Schließlich ist der YieldTotal der einzige Wert der sich ansonsten nicht zurücksetzen läßt.
Alle anderen Werte sind ja i.d.R. am nächsten Tag bereits Geschichte, wenn man nicht gerade die Stromversorgung von der Batterie trennen muß, da wäre aber m.W. auch ein Restart Command ausreichend.

**Comment by stefan123t** [comment]
Feature Request: YieldTotal Correction siehe #570
