### ISSUE TITLE
HomeAssistant integration?

### ISSUE THREAD

**Issue by 21-Jailbraik-21** [lumapu/ahoy#519]
Hallo, habe alles auf ESP32 installiert und funktioniert auch.
Leider wird in Homeassistant (MQTT) nichts angezeigt.

Ist eventuell eine Integration geplant?

Oder kann mir jemand schreiben, wie ich an die Daten komm?

Tolles Projekt.

**Comment by lumapu** [comment]
in den Settings gibt es in der Rubrik MQTT einen `send` Button, dann wird die entsprechende Struktur gesendet
