### ISSUE TITLE
regex - Eingabe eines Bindestrichs beim Inverternamen wird zurückgewiesen

### ISSUE THREAD

**Issue by roku133** [lumapu/ahoy#525]
Aktuell kann mit v0.5.61 beim Inverternamen kein Bindestrich eingegeben werden.
Der Bindestrich im regex-Ausdruck wird als Bereichsangabe zwischen "." und "_" interpretiert.

**Comment by Gerri1** [comment]
Auch bei den Eingaben >Modulname, >MQTT - Topic. Es erscheint auch ein Meldetext "Invalid input". 
Das war aber auch schon bei der  v0.5.60 vorhanden!

**Comment by beegee3** [comment]
Leerzeichen sind im regex auch nicht vorgesehen (genauso wenig wie Umlaute und sonstige internationale Zeichen).
Wenn es darum geht, bestimmte Zeichen nicht zu erlauben wäre eine regex Negativliste vielleicht besser, ansonsten öffnet sich die Büchse der Pandora.

**Comment by lumapu** [comment]
ich würde so wenig wie möglich erlauben, dann haben wir die geringesten Probleme. Mit der aktuellen Dev Version `0.5.62` sind folgende Zeichen erlaubt:

* `A-Z`
* `a-z`
* `0-9`
* `.`
* `-`
* `+`
* `_`

**Comment by roku133** [comment]
super, schneller Fix 👍

**Comment by beegee3** [comment]
zumindest noch das Leerzeichen wäre schön, wenn nichts dagegen spricht

**Comment by lumapu** [comment]
@beegee3 ich dachte genau das ist eines der Zeichen, die bei MQTT nicht erlaubt sind

**Comment by beegee3** [comment]
als 'topic' klar. Sorry, hatte es nicht gesagt, mir ging es um die Modul Namen, aber das ist ja in der neusten Version ok.
