### ISSUE TITLE
Feature Request: Webseite nach Update bis Reboot sperren

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#527]
Ist es möglich die Webseite nach Drücken des Update-Buttons so lange zu sperren bis der Reboot im Gange ist ?

Hintergrund :
Wenn man während des Updates noch einmal auf den Button „kommt“ dann zerschießt man sich das Programm, bzw. bringt den Update in einen komischen Status was als Folge hat das die DTU nicht mehr korrekt bootet.

Mir ist das jetzt schon mehrmals vorgekommen mit meinen Wurstfingern auf dem Tablett. Komme versehentlich beim Updatevorgang noch einmal auf den Update-Button und dann ist aus die Maus, die DTU startet nicht mehr korrekt und man muß sie mit einem Flashtool jungfreudig flashen. Kann man nach Drücken des Updates die Eingabe, bzw. die komplette Webseite so lange sperren bis die DTU rebootet, bzw. die Reboot-Seite anzeigt ?

Das Phänomen läßt sich jederzeit reproduzieren, egal ob mit ESP8266 oder ESP32.

**Comment by reserve85** [comment]
Das wäre in der Tat gut, ist mir auch schon passiert.
