### ISSUE TITLE
Feature Request :  MQTT neuer Topic „comm_disabled“

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#529]
Jajaa, ich weiß, wieder MQTT und kein Ende 🤪

Beim Node-Red puzzeln ist mir aufgefallen das ich nichts über den Status der Kommunikation zum NRF-Mudul bzw. den Invertern in Erfahrung bringen kann.

Ich vermisse einen Topic <topicname>/comm_disabled true/false

Damit meine ich jetzt nicht das Setzen des Häkchens bei „disable night communication“, das hat ja einen eigenen Topic, sondern den wirklichen Status ob die DTU gerade kommuniziert oder nicht. Der Status sollte gesetzt sein (true) wenn einerseits der obige Fall eintritt (Nachts) oder andererseits wenn man bei den Invertern die Kommunikation manuell deaktiviert. Also quasi immer wenn keine Kommunikation statt findet, oder unterbricht. Oder salopp gesagt, wenn nicht gepollt wird.

**Comment by DukeWolle** [comment]
Glaub mir du merkst wenn nichts mehr kommt. Also mir reichen aktuell Status und available..

**Comment by knickohr** [comment]
Darum geht’s nicht 😅

Ich würde gerne eine Rückmeldung haben was die DTU treibt oder eben nicht 🤓

**Comment by DukeWolle** [comment]
Stable Release ist mE erst mal wichtiger wie schnick schnack. 😀

**Comment by beegee3** [comment]
>Ich vermisse einen Topic /comm_disabled true/false

Evtl. noch ein /comm_dis_ts', für den Zeitpunkt der letzten Anpassung. Dazu braucht man nur
in pubMqtt.h
```
        void tickerComm(bool disabled) {
            publish("comm_disabled", ((disabled) ? "true" : "false"), true);
            publish("comm_dis_ts", String(*mUtcTimestamp).c_str(), true);
        }
```
und eine Anpassung in app.cpp
```
void app::tickIVCommunication(void) {
    mIVCommunicationOn = !mConfig->sun.disNightCom; // if sun.disNightCom is false, communication is always on
    if (!mIVCommunicationOn) {  // inverter communication only during the day
        ...
            if (mTimestamp > (mSunset + mConfig->sun.offsetSec)) { // current time is past communication stop, nothing to do. Next update will be done by tickCalcSunrise
                nxtTrig = 0;
        ...
        if (nxtTrig > 0)
            onceAt(std::bind(&app::tickIVCommunication, this), nxtTrig);
    }
    if (mConfig->mqtt.broker[0] > 0) {
        mMqtt.tickerComm(mIVCommunicationOn);
    }
}
```

**Comment by knickohr** [comment]
@beegee3 
Ich verstehe C(++) nur zum Teil, da ist klingonisch für mich einfacher. Ist auch der Grund warum ich mich da so schlecht einbringen kann. Ansonsten wäre da schon längst ein ePaper Display an der DTU 😉

Flag müßte eigentlich doch schon vorhanden sein, ansonsten wüßte die DTU doch gar nicht ob sie senden soll oder nicht. Muß doch salopp gesagt nur noch ein publish zum Broker gemacht werden.

Qapla‘

**Comment by beegee3** [comment]
@knickohr nuqneH
Der Code ist mehr als Anregung für @lumapu gedacht. Der wird zur Zeit nicht nur von mir mit jeder Menge anderer Anfragen genervt 😒 und muss ja nicht alles allein machen 😏.
>Flag müßte eigentlich doch schon vorhanden sein

ngem Sarghmey tlha'laH, to'waQ vIyIvtaH (tlhIngan Soj 'oH -- not bIyaj 😁):

`mIVCommunicationOn` ist die Flag, in `tickIVCommunication` wird sie gesetzt. Im Code oben ist die neue Funktion `tickerComm`, die den publish macht und (auch neu) am Ende von `tickIVCommunication` aufgerufen wird. Dazu noch eine kleine Korrektur, damit der Aufruf auch immer gemacht wird (vorher wurde die Funktion im Fall von 'current time is past communication stop' sofort beendet).

In diesem Sinne
Qapla‘

**Comment by knickohr** [comment]
Die Stable ist da 😎 Wie geht’s weiter ?  *drängel* *quängel* 😅

**Comment by knickohr** [comment]
Das comm_disabled ist verkehrt herum 😲

Also entweder umbenennen in comm_enabled oder true/false tauschen 😅

**Comment by lumapu** [comment]
ok, ich drehe es um, der Wahnsinn geht weiter 😊
Danke fürs testen!

**Comment by knickohr** [comment]
Danke 😎😘

Jetzt funktionieren alle 5 Stati out of the box 👍

- online (alle Inverter online und produzieren)
- partial (min. ein Inverter produziert nicht)
- missing (min. ein Inverter fehlt unter Tags)
- offline (alle Inverter sind offline)
- communication disabled (es ist Nacht 🤪)

🥳
