### ISSUE TITLE
Feature Request: current release version Nummer in Code hinterlegen

### ISSUE THREAD

**Issue by beegee3** [lumapu/ahoy#531]
Ich finde den Web Hinweis 'You are using a development version, current released version: ...' super (schön wäre der auch in MQTT). 

Im AP Modus, oder wenn Ahoy nur Zugriff auf das lokale Netz hat (mit 'fritz.box' als NTP Server; ist immer erreichbar 😄), gibt es diese Info natürlich nicht. Daher wäre es schön, die Release Versionsnummer nicht bei jedem Web Index Aufruf von github abzufragen, sondern im Code zu hinterlegen (so oft gibt es ja keine neue Release🤞).
Das ist evtl. mit etwas Pflegeaufwand verbunden, oder es lässt sich mit einem python script automatisieren.
Ist nur ein 'nice to have' :grimacing:

**Comment by lumapu** [comment]
finde den Mehrwert nicht entscheidend. Vor allem mit dem Gedanken, dass man auch zu einem späteren Zeitpunkt die Firmware nochmal installieren könnte. Ich mach hier mal zu.
