### ISSUE TITLE
HM 600 - Leistungswerte bei 100% werden zu niedrig angezeigt.

### ISSUE THREAD

**Issue by hajulied** [lumapu/ahoy#532]
## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ? Wemos Mini____
Retailer URL: __??____

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x] circuit board
* [ ] external antenna

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0.5_.41__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [ ] ESP Tools
* [x] Platform IO

### Desktop OS:
* [ ] Linux
* [x] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by hajulied** [comment]
Moin,
der AHOYDTU zeigt bei 100% Leistung zu geringe Wert an. Shelly und der Batteriemonitor zeigen die korrekten Werte. Bei einer schrittweisen Reduzierung um je 10% stimmt AHOY mit Shelly und  BattMon überein. 
Der Log zeigt manchmal "Missing frame..."
![SerialLog](https://user-images.githubusercontent.com/116681754/210089756-136815af-cb71-4e0d-9e78-76371dfb1215.jpg)
![BatterieMon100](https://user-images.githubusercontent.com/116681754/210089761-6dc40a81-7307-45f9-be5d-a558353fd813.jpg)
![Shelly100](https://user-images.githubusercontent.com/116681754/210089763-f7c9cb58-e52f-44af-b396-8bda209e400a.jpg)
![AHOY70](https://user-images.githubusercontent.com/116681754/210089764-d54c8e78-56f7-4c56-95c8-33b95111f174.jpg)
![AHOY100](https://user-images.githubusercontent.com/116681754/210089765-1a5db96d-de72-4a8f-a85d-0c271d65f5a4.jpg)

**Comment by lumapu** [comment]
Ja das wurde vor längerer Zeit schon mal besprochen. Der Wechselrichter gibt 2% mehr aus, da wohl davon ausgegangen wird, dass bis zur Messstelle Leitungsverluste auftreten.
Evtl. nochmal in Disord nach dem Thema suchen.

**Comment by Gerri1** [comment]
@hajulied 
Der Shelly Leistungswert ist doch Wechselstromseitig und der Batteriemonitor und Ahoy-DTU (untere Anzeige) Gleichstrom, oder liege ich da falsch! Der MPPT bei der DC Spannung ist, denke ich, nicht optimal!

**Comment by hajulied** [comment]
Moin,
Die Daten des Batterie Monitors sind korrekt (12,7 A, 26,3 Volt),nachgemessen mit Zangenamperemeter, d. H. der WR zieht etwa 336 Watt. Der Wert von Shelly 329 passt dazu. Ahoy zeigt aber nur 242 Watt an. Das bleibt so bei 100,90,80% so. Erst ungefähr ab 70%passen die Werte des Monitors, von shelly und ahoy zusammen.

**Comment by Gerri1** [comment]
Den Shelly als Leistungsmesser würde ich nicht machen (sehr ungenau)! Auch ein Vergleich der Leistung von Gleich-und Wechselstrom ist stark vom momentanen Wirkungsgrad abhängig. Wie schon oben geschrieben, der MPPT Regler hat nur einen bestimmten Bereich bei dem er richtig arbeitet, schau mal ins HM- Datenblatt.
Auch gibt dir Ahoy nur die Messwerte wieder, was dein WR ausgibt!

**Comment by Gerri1** [comment]
![MPPT](https://user-images.githubusercontent.com/119110321/210176624-813e08fb-b14a-4340-9cb5-96acb6d90d09.PNG)

**Comment by hajulied** [comment]
Moin,
Es kommt mir nicht auf die totale Genauigkeit an. Ich möchte nur wissen, warum der HM bzw. Ahoy etwa ab 70 % aufwärts immer die gleichen Werte zeigt, obwohl tatsächlich mehr eingespeist wird und ob ich etwas dagegen machen kann.

**Comment by Gerri1** [comment]
Erstmal würde ich mir für die AC-Messung einen Sonoff POW mit Tasmota zulegen und den dann richtig Kalibrieren! 😁
Dann wäre es evtl. besser einen anderen WR zu nehmen, der für die Batteriespannung passt!

**Comment by Gerri1** [comment]
Hat dein Batteriemonitor eine seperate Spannungsversorgung (Netzstecker) oder wird der aus der Batterie versorgt?
Wenn das zweite zutreffend ist, dann hast du ja noch einen Verbraucher in der Schleife!
Wie schon geschrieben, vergleichst du Äpfel mit Birnen und ein Sprichwort sagt:
"Wer viel misst, misst Mist!"

**Comment by hajulied** [comment]
Immer noch moin,
vielen Dank für die Antworten, aber sie haben nichts mit der eigentlichen Frage zu tun. (Akku und HM passen sehr gut zusammen, er startet nach wenigen Sekunden und läuft fehlerfrei, Genauigkeit und Kalibrierung brauche ich nicht, der Eigenverbrauch des Monitors liegt im mA -Bereich. )
![shelly65](https://user-images.githubusercontent.com/116681754/210181278-6093e21d-8ca4-416d-af7a-6ad9a36d76a4.jpg)
![ahoy65](https://user-images.githubusercontent.com/116681754/210181288-5d521c8d-1356-4ea0-aaae-229881f09381.jpg)
![mon65](https://user-images.githubusercontent.com/116681754/210181289-cb403f29-990b-4d7c-b18d-ab9a2bf1305e.jpg)
![zange65](https://user-images.githubusercontent.com/116681754/210181290-30c1902d-9963-4640-a13f-632f6f5ea3c9.jpg)
Habe den HM jetzt auf 65% gestellt. Bei jeder Einstellung unter 70% passen die Werte zusammen und sind plausibel, siehe Screenshots.

**Comment by Gerri1** [comment]
![HM600](https://user-images.githubusercontent.com/119110321/210181788-bfe66cd6-315e-4f88-8a3c-ca41a8f13117.PNG)

**Comment by hajulied** [comment]
... Danke für Eure Antworten . 
Ich gebe es auf :-((

**Comment by Gerri1** [comment]
Bei meinem Aufbau passen die Leistungen eigentlich sehr gut zusammen!
Sonoff POW und Ahoy-DTU

![Leistung](https://user-images.githubusercontent.com/119110321/210808162-aee560e7-06fe-49cf-a7f9-a6f5534402d5.png)

**Comment by stefan123t** [comment]
> Immer noch moin, vielen Dank für die Antworten, aber sie haben nichts mit der eigentlichen Frage zu tun. (Akku und HM passen sehr gut zusammen, er startet nach wenigen Sekunden und läuft fehlerfrei, Genauigkeit und Kalibrierung brauche ich nicht, der Eigenverbrauch des Monitors liegt im mA -Bereich. ) 
![ahoy65](https://user-images.githubusercontent.com/116681754/210181288-5d521c8d-1356-4ea0-aaae-229881f09381.jpg) Habe den HM jetzt auf 65% gestellt. Bei jeder Einstellung unter 70% passen die Werte zusammen und sind plausibel, siehe Screenshots.

Man sieht die Ursache des Problems doch bereits in Deinen AhoyDTU Screenshots:
* Du hast zwei MPPT in Deinem HM-600 die beide zur Stromerzeugung herangezogen werden sollen.
* Du stellst das Limit auf 100% bzw. darunter auf 90%, 80% und 70% ein.

Die Batt1 liefert ca. 68,9% der zu erwartenden Leistung des Kanals / MPPTs

* bei 100% sollte er den ersten MPPT an dem Batt1 hängt mit 50% seiner Nennleistung ausreizen.
* bei 90% bzw. 80%  verteilt er diese mit je 45%/40% auf beide Batt1 und Batt2, da aber Batt2 leer ist (U_DC = 0,7V) liefert der zweite MPPT keine Leistung.
* bei 70% oder irgendwann darunter kommst Du in den Bereich den Dein erster MPPT mit der Leistung der Batt1 auch abdecken kann und liefert damit auch die von Dir erwartete Leistung.

Für eine Batterieeinspeisung sind die Modelle mit nur einem MPPT m.E. besser geeignet, da hier auch wirklich x% der am Ausgang erwarteten Leistung entsprechen. Bei allen Modellen mit zwei / vier Eingängen und immer zwei MPPT teilt sich diese Leistung auf beide MPPTs auf. Die Einstellung ist dabei nicht mehr intuitiv richtig sondern maximal 50%!

**Comment by dermeb** [comment]
Hallo zusammen, 
ich habe genau das gleiche Phänomen wie @hajulied .
Ich nutze einen HM-350 zur Einspeisung über einen Akku (also einkanalig).
Der Wechselrichter  macht genau das was man erwartet bei verschiedenen gesetzten Limits (also z.B. bei 80% drosselt er auf ca. 280W). Nachgemessen mit einem Shelly, einer kalibrierten Messsteckdose und einem Energiezählerzwischenstecker). 
Allerdings bleiben die Werte, die AhoyDTU anzeigt und per MQTT weitergibt auf etwa 240W  und ca. 10A stehen (egal ob das Limit auf 70%, 80%, oder 100% steht.)
Wie gesagt, es wird tatsächlich das eingespeist, was man per Limit setzt - aber die Anzeige der der Werte stimmt nicht mehr ab ca. 70% - entsprechend ca. 240 W, sondern bleiben konstant. 
Hat das sonst noch jemand beobachten können? 

Beste Grüße
Michael

**Comment by dermeb** [comment]
Hallo zusammen, hat das Phänomen sonst niemand beobachten können?

Beste Grüße
Michael

**Comment by lumapu** [comment]
ich kann hier leider nichts beitragen. Ahoy gibt nur die von Wechselrichter gemeldeten Werte weiter.

**Comment by lumapu** [comment]
ist und bleibt wohl ein Bug des Wechselrichters, hier kann man in Ahoy höchstens versuchen zu rechnen, das wage ich aber lieber nicht.
