### ISSUE TITLE
v0.5.64

### ISSUE THREAD

**Issue by Gerri1** [lumapu/ahoy#533]
Die FW v0.5.64 läuft bei meinem System bis jetzt absolut stabil und zufriedenstellend! 👍👍👍😁

**Comment by DukeWolle** [comment]
@Gerri1 
Super! Kleine Fehler drin, aber fast Release reif 👍

**Comment by knickohr** [comment]
Ja stimmt, seit 1,5 Tagen keine Reboots und seltsamen Sachen, da ist bestimmt ein ganz schlimmer Bug drin 🪲

Jupp, könnte eine Stable werden 👍

**Comment by lumapu** [comment]
danke für's Feedback habe inzwischen eine Uptime von 1 Tag und 22h

**Comment by lumapu** [comment]
Release ist draußen, ich mach hier zu
