### ISSUE TITLE
v0.5.65 tickIVCommunication trigger

### ISSUE THREAD

**Issue by Gerri1** [lumapu/ahoy#534]
NTP timeserver unreachable und nrf24l01+ funkt fleißig weiter obwohl disable night communication! 😮

**Comment by lumapu** [comment]
Ihr seit ja schneller als das Licht - das korrigierte Release baut seit 6 Minuten

**Comment by knickohr** [comment]
Guckst Du 66 😅

**Comment by Gerri1** [comment]
😪

**Comment by knickohr** [comment]
Es ist ein Junge, ähhh Stable 🥳

**Comment by Gerri1** [comment]
Hurraaaa, ... da ist es ja!! 👍😊

**Comment by beegee3** [comment]
@knickohr @Gerri1 ihr seid ja hammer: live dabei 🙇‍♂️ 

> nrf24l01+ funkt fleißig weiter obwohl disable night communication!

@lumapu: in `tickIVCommunication` passt der Trigger nicht
Abhilfe schafft `nxtTrig = mSunset + mConfig->sun.offsetSec + 1;`
(alternativ: `if (mTimestamp >= (mSunset + mConfig->sun.offsetSec)) {` )

**Comment by knickohr** [comment]
@beegee3 

Wer was will muß auch was dafür tun. Da ich zwar des klingonisch mächtig bin aber nicht dieser kryptischen Programmiersprache kann ich wenigsten so meinen Beitrag dazu leisten und jede Menge Issues auf machen 😂

Wir müssen mal Gagh essen gehen 😉

Qapla‘
