### ISSUE TITLE
Testweise 2 Ahoy Dtu's an einem WR

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#535]
Guten Morgen zusammen,
ich habe seit letztem Monat eine Ahoy DTU im Einsatz. Läuft perfekt. 
Jetzt habe ich mir die Hardware für eine zweite DTU geholt und mit der neuesten Beta konfiguriert.
Leider bekomme ich keine Rückmeldung vom WR.
WR ist ein HM-600
Board ist ein AZ Delivery Mini D1 mit einer NRF24L01+ Antenne
Verdrahtet wie auf der get started Seite.
Gesendet wird, aber leider bekomme ich keine Rückmeldung.

Die erste DTU ruft mit der 0.5.41 alle 30 Sekunden die Daten ab. Die neue habe ich probehalber auf 5 Sekunden gestellt. Aber in der Übersicht steht, dass der WR nicht erreichbar sei.

Hat jemand einen Tipp, woran das liegen kann?

Gruß
dtuuser

**Comment by dtuuser** [comment]
Wurde grade entflagged. 
Eventuell wird  das Problem  #549 meine Lösung.
Ich habe D1 und D2 konfiguriert. Leider bekomme ich keine Rückantwort. Probiere jetzt ein anderes Netzteil und suche einen Kondensator.
Meine andere Hardware läuft seit einem Monat parallel (nur Stromanschlüsse vom USB Stecker) zu einer Webcam an einem USB Anschluss eines Routers

**Comment by dtuuser** [comment]
Läuft. 100er Kondensator und D1 für CE  und D2 für IRQ.
Mit 10er Kondensator  keine Rückmeldung. Mit 220er klappt auch diese Hardware
Power Level immer mit LOW

**Comment by stefan123t** [comment]
Danke für die Rückmeldung mit dem großen Kondensator! Wir hatten bisher meist 47-100uF verwendet aber angenommen es geht auch mit einem 10uF noch hinreichend gut.

@lumapu wir sollten hier also generell einen 100uF Kondensator empfehlen ich habe aus meiner Schublade mit den "sortierten" Kabeln wohl aus Versehen den richtigen erwischt und daher noch nie Probleme gehabt. Sollte ich mal mit einem 10uF nochmal probieren wenn der Lötkolben heiß ist ?

**Comment by lumapu** [comment]
@stefan123t meine Erfahrung zeigt, das sich leider die Wemos Boards sehr unterschiedlich verhalten. Einer von 5 benötigt zwingend einen Elko, sonst stürzt er ständig ab.
Eine große Kapazität ist doch nur beim Booten etwas mehr Belastung für den DCDC, ab dann wirkt die sich positiv auf das Gesamtsystem aus, daher würde ich keine kleinere Kapazität testen.

**Comment by stefan123t** [comment]
Ich würde den Nutzern einfach den 100uF ab sofort vorschreiben, wer ihn nicht dran hat bekommt auch keinen Support mehr 
Das mit dem 10uF wäre auch nur um den Fehler nachzustellen und mal mit dem Oszi draufzuschauen was passiert :grin:

**Comment by sstidl** [comment]
> Ich würde den Nutzern einfach den 100uF ab sofort vorschreiben, wer ihn nicht dran hat bekommt auch keinen Support mehr Das mit dem 10uF wäre auch nur um den Fehler nachzustellen und mal mit dem Oszi draufzuschauen was passiert 😁

Plus anlöten direkt am NRF ebenso. Bei mir war das die Lösung. Am ESP anlöten hat nichts gebracht, es mußte nahe am NRF sein. Und die Elko Beine auch so kurz wie möglich. :-)

**Comment by flummy1978** [comment]
Hai zusammen

hab seit ein paar Tagen das Teilen in Aktion und muss sagen MEGA..... 

> Ich würde den Nutzern einfach den 100uF ab sofort vorschreiben, wer ihn nicht dran hat bekommt auch keinen Support mehr 

hab das jetzt sicherlich schon 1000000x gelesen, dass er damit besser ist / sein soll. Aber äußert sich eine Problematik irgendwie IMMER? Ich habe meinen Aufbau an einem kurzen micro USB direkt angeschlossen und keine Probleme. Neustarts und "Ausfälle" sind selbst produziert ;)
