### ISSUE TITLE
Nach Flash auf 0.5.67/68 kein Zugriff mehr

### ISSUE THREAD

**Issue by Ollipop030** [lumapu/ahoy#543]
Hi, habe heute versucht die 0.5.67 zu flashen, danach war die DTU nicht mehr erreichbar. Neustarts helfen nicht, es gibt auch keinen AP. Bin dann wieder auf die 0.5.66 stable, und zufälligerweise gab es dann direkt die 0.5.68. Also nochmal damit probiert, gleiches Problem.

Geflasht habe ich über die Weboberfläche, so wie immer. Mir wurde auch Update success angezeigt, danach gab es aber nur einen Timeout im Browser.

**Comment by lumapu** [comment]
ich kann es nicht erklären, da in diesem Bezug keine Änderung gemacht wurde.

Bei einem meiner ESPs war es auch so, dass success dran stand und danach ein timeout. Allerdings war der Versuch direkt davor nicht erfolgreich. Wenn wohl ein Versuch fehlschlägt sollte man vor dem nächsten Versuch einen soft reboot machen.

Ich habe die Version 0.5.68 dann per Serial wieder reinladen können, seit dem rennt er wieder

**Comment by Ollipop030** [comment]
Ok. Hab grad nochmal probiert: Softreboot, direkt danach das Update auf 0.5.68 übers Webinterface. Diesmal hat es geklappt. Das Verhalten ist aber neu. Habe von der 0.5.41 bis zur 66 fast alle Dev Builds auf diese Weise installiert, gab nie Probleme.

**Comment by Gerri1** [comment]
Bei mir verlief das Update von 0.5.66 auf 67 und 68 ohne Auffälligkeiten! 
(Wemos D1 mini)

**Comment by knickohr** [comment]
68 hat jetzt funktioniert 👍

Hat zwar gefühlt Minuten gedauert bis die Inverter wieder da waren, ich bilde mir ein bei den vorherigen Versionen (66 und darunter) ging es schneller, aber egal, es geht.

Warum gibt es eigentlich 2 Changelog auf der Index ?  Ich vermute mal die obere ist für die Stable und die darunter für die DEVs ?   Sollte man deutlicher machen, bspw. Release-Changelog und Developer-Changelog.
![21BF90D0-32DC-49D5-A514-6F6E06BBD65B](https://user-images.githubusercontent.com/63048210/210241807-25614670-dbc3-4b66-8bfc-991538771475.jpeg)

**Comment by dtuuser** [comment]
Update hat funktioniert. Leider bekomme ich mit meiner Hardware keinen Kontakt zum WR. Da ich noch flagged bin, kann meine Nachfrage....funktionieren 2 DTU's parallel... noch keiner sehen.

**Comment by lumapu** [comment]
ok, ja das sind doch Peanuts 🥜

**Comment by knickohr** [comment]
Ich mag keine Erdnüsse 😂
