### ISSUE TITLE
Feature Request: WT32-ETH01

### ISSUE THREAD

**Issue by Gerri1** [lumapu/ahoy#545]
Hallo zusammen,
was haltet Ihr eigentlich von dem WT32-ETH01 Board mit Ahoy?

**Comment by TB-79** [comment]
Ich glaube ahoy unterstützt kein Ethernet oder POE.
Das kannst Du aber im Discord Support besprechen,das ist ja hier kein issue .

**Comment by Gerri1** [comment]
Vielen Dank für die Info, dann hat sich das erledigt!
