### ISSUE TITLE
Feature Request: Exclude internal Flash Pins, Power Limit über Serial / Control

### ISSUE THREAD

**Issue by Gerri1** [lumapu/ahoy#546]
### Platform

ESP8266

### Model name

NodeMCU LoLin v3

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

Display SSH1306   D1 = SCL, D2 = SDA
Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.66

### Github Hash

f8fe044

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-400
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 385
    - Module Name: Unten_O
#### Inverter 1
    - Address: 1141752123456
    - Name: HM-400
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 385
    - Module Name: Unten_W
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: MIN
#### Serial Console
    - print inverter data: [ ]
    - Serial Debug: [ ]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Nach Eingabe eines Powerlimits in % über >Serial / Control< bei beiden Invertern, hatte sich die Seite fast komplett verabschiedet!
Eine Auswahl der Inverter war nicht mehr möglich, da leer und auch der Schaltflächenframe. Auch eine Aktualisierung der Website blieb erfolglos. 
... reboot! 😩
![Fehler](https://user-images.githubusercontent.com/119110321/210361696-d5a30658-bdff-4a14-9b02-68ae19040e4a.PNG)

**Comment by lumapu** [comment]
hast du einen Kondensator an den 3.3V? Der ist bei mir bei einem Modul sogar ohne NRF24 nötig.

**Comment by Gerri1** [comment]
Ich habe ein Anker USB Netzteil am ESP und am nRF- Modul sogar einen 1000µF Kondensator!
Bei einem 2. Versuch das nochmal auszulösen hatte ich in der Konsole das gesehen! 
3x die gleiche Antwort.

![Fehler1](https://user-images.githubusercontent.com/119110321/210444152-97e2b203-554a-48eb-9b60-d4cd3562ad55.PNG)

Danach war die Verbindung zu den Invertern weg!

![Fehler2](https://user-images.githubusercontent.com/119110321/210444355-5a964b1f-f4f9-4ab7-8770-8d47adebad43.PNG)

**Comment by Gerri1** [comment]
Nach vielen Test- und Flashversuchen habe ich festgestellt, das meine alte Konfiguration CE -> GPIO10 und IRQ -> GPIO09 (wegen Display und keine Funkverbindung bei D3 und D4) anscheinend den ESP lahm legen! 
Jetzt habe ich CE -> GPIO00 und IRQ -> GPIO02 wieder hergestellt!
Es sind zwar die beiden Ports GPIO09 und GPIO10 in der Auswahlliste vorhanden, aber irgendwas ist da nicht mehr in Ordnung! 😮
Das setzen eines Powerlimits bei beiden Invertern über Serial / Control war auch i.O.

**Comment by lumapu** [comment]
danke für die Lösung. Evtl. kann das er anders bestätigen oder wir können nochmal die Doku der Pins für den ESP durchschauen und evtl. einen Hinweis finden.

**Comment by Gerri1** [comment]
Sobald ich die Ports GPIO09 und GPIO10 in der Auswahlliste eingestellt hatte und auf Speichern/Reboot klickte, hatte sich der ganze ESP aufgehängt. Sogar das Disply blieb dunkel und es sah so aus, des er ständig einen Reboot durchführte!
Die Leistungsreduzierung hatte ich Wetterbedingt und wegen der neuen 0.5.66  (Hauptsystem) erstmal im ioBroker abgeschalten um böse Überraschungen zu vermeiden. Da doch mal ein paar Sonnenstrahlen auf die Module trafen und meinen Verbrauch ins Minus drückten, habe ich mal schnell über Ahoy das machen wollen.
Ich werde mir ein gleiches Testsystem Aufbauen und das Ganze nochmal bei dem ausprobieren.

**Comment by Gerri1** [comment]
Ich habe mich dem Testsystem nochmal angenommen.
FW 0.5.66
Anscheinend haben die Ports SD3 - GPIO10 und SD2 - GPIO09 keine Lust da was zu machen, im Gegenteil.
Mit dem Anschluss von CE an GPIO10 und IRQ an GPIO09 kommt keine Verbindung zum WR zustande.
Mit dem Anschluss von CE an GPIO09 und IRQ an GPIO10 startet Ahoy nicht mehr.
Ausduck von Putty:
[Fehler Ahoy.txt](https://github.com/lumapu/ahoy/files/10392497/Fehler.Ahoy.txt)

**Comment by lumapu** [comment]
ich hab nochmal aufgemacht, da ich das gerne dokumentieren will

**Comment by Adminius** [comment]
GPOIO9 und 10 sind doch an den internen Flash von ESP8266 verbunden und dürfen somit gar nicht genutzt werden
(es gibt zwar Tricks, wo man Flash umlötet, kurzschließt und somit 9 und 10 befreit, aber im Standardfall bitte nicht nutzen)

**Comment by stefan123t** [comment]
@lumapu können wir die intern vom Flash belegten GPIOs nicht einfach auf eine Blacklist packen bzw in der ESP8266 / ESP32 Variante diese einfach entsprechend ausklammern.
Oder gibt es hier auch je nach Board und ESP32 wroom/wrover/s/c3 unterschiedliche Belegungen ?

**Comment by Adminius** [comment]
ESP32 hat andere verbotene Pins die leider meistens ausgeführt sind.
https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

meistens sind das die Pins an der kurzen Seite des Module ;)

**Comment by stefan123t** [comment]
@Adminius laut der o.g. Doku auf randomnerdtutorials sind sowohl beim ESP8266 als auch beim ESP32 die GPIOs 6..11 mit dem internen Flash Chip belegt.

ESP8266:
**[GPIOs connected to the Flash Chip](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)**
GPIO6 to GPIO11 are usually connected to the flash chip in ESP8266 boards. So, these pins are not recommended to use. 

ESP32:
**[SPI flash integrated on the ESP-WROOM-32](https://randomnerdtutorials.com/esp32-pinout-reference-gpios/)**
GPIO 6 to GPIO 11 are exposed in some ESP32 development boards. However, these pins are connected to the integrated SPI flash on the ESP-WROOM-32 chip and are not recommended for other uses. So, don’t use these pins in your projects:

    GPIO 6 (SCK/CLK)
    GPIO 7 (SDO/SD0)
    GPIO 8 (SDI/SD1)
    GPIO 9 (SHD/SD2)
    GPIO 10 (SWP/SD3)
    GPIO 11 (CSC/CMD)

**Comment by Adminius** [comment]
ja, da hast du Recht. Die 6-11 sind wirklich gleich. Die müssen raus aus der Pin-Liste.
ESP32 hat noch Eigenheit, dass Pins 34,35,36,39 nur Input können, d.h. für IRQ OK, für CS no go.
Diese sind ganz für ADC geeignet (für z.B. #605)

**Comment by lumapu** [comment]
ich denke das haben wir schon ewig umgesetzt, auf jeden Fall habe ich auf diesem Gebiet schon seit langem keine Kritik mehr gehört.
