### ISSUE TITLE
Wird in der FRITZ!Box nicht gefunden

### ISSUE THREAD

**Issue by herrvonbalou** [lumapu/ahoy#549]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [ ] ESP Tools
* [x] Platform IO

### Desktop OS:
* [ ] Linux
* [x] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Gerri1** [comment]
@herrvonbalou 

- Welche FW- Version?
- z.B. mit Handy WLAN einschalten und im Browser die 192.168.4.1 eingeben!

**Comment by herrvonbalou** [comment]
Hallo,

schön, dass du mir helfen möchtest

ich habe die aktuelle aufgespielt und komme auch mit dem iPad in die Einstellung
Heute Morgen wurde es auch im Netzwerk angezeigt ich konnte es mit der Adresse aber nicht anpingen
Das Teil macht mich noch kirre

Viele Grüße

Bernd

**Comment by Gerri1** [comment]
Das nRF24L01+ Modul ist richtig angeschlossen?
Evtl. plus und minus zum nRF24L01 mal trennen und einen Reset machen, dann nochmal über den AP Modus probieren.

**Comment by herrvonbalou** [comment]
Darf ich dir morgen ein Foto vom Anschluss zur Kontrolle schicken?

**Comment by Gerri1** [comment]
> ich habe die aktuelle aufgespielt und komme auch mit dem iPad in die Einstellung

unter >Settings/Network die SSID und Passwort vom WLAN richtig eingegeben?
Static IP Einstellungen erstmal leer lassen, falls da was eingetragen war!
Speichern und Reboot, danach solltest du den ESP im Router wiederfinden.

**Comment by herrvonbalou** [comment]
Guten Morgen,
es geht weiter
Ganz blöder Fehler wlan Schlüssel und Fritzbox Kennwort ist halt ein Unterschied
Komme jetzt auf den logger und habe den Schlüssel vom hm1500 eingetragen
Bekomme aber noch keine Daten
Beim serial/control geht etwas habe ein Foto angefügt
Vielleicht hast du eine Idee

Gruß Bernd

**Comment by lumapu** [comment]
@herrvonbalou leider ist das Bild nicht angekommen

**Comment by Gerri1** [comment]
@herrvonbalou Bilder bitte direkt in GitHub hochladen (ins Nachrichtenfenster ziehen)! 😁

**Comment by herrvonbalou** [comment]
![105BB195-D664-4824-8D8A-D3F53A4CC306](https://user-images.githubusercontent.com/121964073/210772340-02e6c470-5875-47f0-b7c6-f8d5ae0edad6.png)

**Comment by herrvonbalou** [comment]
Hallo, sagt euch der Screenshot etwas?

**Comment by Gerri1** [comment]
Welche Pins für CE und IRQ hast du genommen, evtl. musst du da andere nehmen!

**Comment by herrvonbalou** [comment]
D4 und D3

**Comment by herrvonbalou** [comment]
Muss ich dann aber auch in der konfig so konfigurieren oder?

**Comment by Gerri1** [comment]
... nimm mal D1 und D2 (HW und Software)

**Comment by Gerri1** [comment]
![pin](https://user-images.githubusercontent.com/119110321/210782472-49c21a05-e147-4c80-bedc-a01e413f9a11.PNG)

**Comment by Gerri1** [comment]
... evtl. auch mal die Leistung des nRF mal auf MIN stellen, wenn dass das mit der externen Antenne ist!

**Comment by herrvonbalou** [comment]
Kann machen was ich will immer der gleiche Fehler! 
Am Wechselrichter selbst kann es nicht liegen?

**Comment by Gerri1** [comment]
Stimmt die Seriennummer unter Settings/Inverter und ist der Haken drin bei >Communication Enable< ?

**Comment by herrvonbalou** [comment]
Ja, 2x kontrolliert

**Comment by Gerri1** [comment]
Da musst du das morgen noch mal probieren, jetzt geht eh nix mehr!

**Comment by Gerri1** [comment]
Mache Bitte morgen mal einen Screenshot von der Systemseite!

**Comment by stefan123t** [comment]
Und bitte auch mal ein Foto von Deinem Aufbau hier hochladen, damit man die Module und deren Verkabelung mal gesehen hat.
Meist reicht bei einem Wemos D1 mini v3 auch einfach der Tausch von D3 & D4 für IRQ und CE.
Du hast keinen 10-100uF Elko direkt am NRF24 Modul (Pin 1&2 GND / +3.3V) angebracht / angegeben, 
das gibt so leider kein Fleißbienchen :bee: für Dein Projekt! 
Auch solltest Du evtl. mal die Stromversorgung bzw. das USB Kabel des ESP Moduls durch ein anderes, qualitativ hochwertiges tauschen.

**Comment by herrvonbalou** [comment]
Na das mit dem Fleißbienchen könnte ich ja verschmerzen 
Ich werd mit dem GitHub noch nicht so richtig warm !

**Comment by herrvonbalou** [comment]
![8F2E28BC-C69C-4005-B125-5379F9D7EB8B](https://user-images.githubusercontent.com/121964073/210965994-88a58a8b-7db3-4860-bd44-dd3987355abd.png)
![A0D11F67-8D59-46D9-94CF-CD5C5D70EE96](https://user-images.githubusercontent.com/121964073/210966201-e284aa32-b672-47ab-ba27-c1651146cdfe.jpeg)
![3D154390-8C28-47DD-A79A-806EAD868D3E](https://user-images.githubusercontent.com/121964073/210966206-54d1b280-31ea-48c3-acd0-5e358d8ff436.jpeg)
![918CED4D-BC20-4152-8682-3196901FF790](https://user-images.githubusercontent.com/121964073/210966209-65220e41-7602-41cc-9947-d06d817d4f79.jpeg)

**Comment by herrvonbalou** [comment]
Kondensatoren hab ich bestellt 
Spannung habe ich 3.3 Volt gemessen

**Comment by Gerri1** [comment]
@herrvonbalou 
Wie ist denn die Distanz zum Wechselrichter?
Evtl. wenn möglich, mal die zwei Teile nacheinander Tauschen!
Ich habe schon des öfreren gelesen, das die nRF's nicht funktioniert haben!

**Comment by herrvonbalou** [comment]
Hatte ihn schon nah (5meter) und weiter weg 
nRF hab ich schon getauscht 
Morgen kommt noch ein Kondensator und dann gehen mir langsam die Ideen aus

**Comment by Gerri1** [comment]
... und einen anderen ESP?

**Comment by herrvonbalou** [comment]
noch nicht, da sind andere pins dran. versuche ich nachher noch umzulöten

**Comment by Gerri1** [comment]
... sehr, sehr komisch! 😯
Mit den D1 minis hatte ich ja auch Probleme mit CE und IRQ, aber seitdem die an D1 und D2 dran sind, funktionieren die schon super!

**Comment by dtuuser** [comment]
Bei mir #535 jetzt alles perfekt.

Mit D1 und D2, Kondensatoren 100er oder 220er und mit Power Level LOW. Sogar ein Parallelbetrieb von zwei "Sticks" mit Version 66 und Beta 68 möglich.

Mit einem 10er Kondensator klappte es nicht

Perfekte Alternative für die HM DTU Hardware.
Vielen Dank für das Projekt

**Comment by herrvonbalou** [comment]
Wie merke ich welcher KONDENSATOR MORGEN RAN MUSS?

**Comment by Gerri1** [comment]
Ich würde es jedenfalls mal mit einem 100µF Kondensator probieren!
Aber auch mal mit einem anderen ESP probieren, nicht das der einen Treffer hat!

**Comment by herrvonbalou** [comment]
Hat so ein Kondensator eine Einbaurichtung?
Hatte jetzt 2 Miniwemos bestellt Einer geht gar nicht! Der andere mit dem gezeigten Problem
Na ja, hab dafür im Lotto kein Glück

Viele Grüße aus Albstadt sendet

Bernd Güttinger

**Comment by herrvonbalou** [comment]
Sollte Glück heißen

Viele Grüße aus Albstadt sendet

Bernd Güttinger

Sent with Spark
Am 6. Jan. 2023, 16:08 +0100 schrieb Gerri1 ***@***.***>:

**Comment by Gerri1** [comment]
... und die Verkabelung CE -> D2 (GPIO04) und IRQ -> D1(GPIO05) sind auf alle Fälle richtig, auch in den Einstellungen?

**Comment by Gerri1** [comment]
> Hat so ein Kondensator eine Einbaurichtung?

![polung_von_elektrolytkondensatoren_erkennen_by_adlerweb_dagcrsm-350t](https://user-images.githubusercontent.com/119110321/211046508-d8ab0c1b-2087-4b80-ac06-097eb87aa297.png)

**Comment by herrvonbalou** [comment]
Erstmal ein herzliches Dankeschön für eure Hilfe! Ist es wichtig dass beim Flashen der NRF schon angesteckt ist?
Ich warte jetzt auf die Kondensatoren und dann meld ich mich wieder

**Comment by lumapu** [comment]
nein muss nicht da sein, kann zu einer beliebigen Zeit verdrahtet werden.
Du kannst auch schon alle Einstellungen machen, wenn du dann das NRF richtig verbindest geht es direkt los.

**Comment by herrvonbalou** [comment]
So ist der momentane Stand:
Es funktioniert! 

Noch einmal ein Original Lolin Wemos bestellt alles gleich angeschlossen und programmiert und nun läuft es absolut problemlos 

Also waren 2 neu bestellte Wemos Clone defekt so ein Mist 

Soweit so gut
Da ich nun sehe was vom Dach kommt ist mir etwas komisches aufgefallen 

Ich habe 4 Module an einem HM1500 und es wird auch an allen 4 Spannung angezeigt aber nur an 3 Strom und das schon seit ich es vor 5 Monaten montiert habe

An was kann es liegen wenn ein Modul zwar Spannung aber keinen Strom anzeigt?

Das ganze wäre mir ohne das AHOY DTU vermutlich nie aufgefallen

**Comment by herrvonbalou** [comment]
Weiß jemand welcher Anschluss am HM zu welchem Ausgabefeld an der DTU gehört?

**Comment by lumapu** [comment]
@herrvonbalou ja, von links nach rechts in Ahoy ist 1 -4, auf dem Wechselrichter stehen diese Nummern hinten drauf.

Bin gespannt was der Fehler ist. Kann nur ein riesiger Widerstand sein, oder ein Kanal nicht angeschlossen, da die Spannung beim HM1500 immer für zwei Eingänge zusammen erfasst wird. Also Kanal 1 und 2 haben eine Spannung und 3 und 4.

**Comment by herrvonbalou** [comment]
Hallo, komme gerade nicht weiter 
Der Fehler wandert mit.
Wenn ich umstecke ist ein anderer Kanal ohne Leistung 
Also ist es das Modul!
Wenn ich an dessen Leitungen messe liegen ungefähr 40 Volt Gleichstrom an
Hat noch jemand eine Idee?

**Comment by lumapu** [comment]
@herrvonbalou ja den Kurzschlussstrom messen, der sollte je nach Modul ca. 8 bis 14A sein. Steht auch hinten drauf.

Finde toll, das Ahoy dazu beigetragen hat einen Fehler der Anlage zu offenbaren. Hoffentlich kannst du den Fehler beheben und hast dann 25% mehr Ertrag.
