### ISSUE TITLE
Feature Request: "Login" link in sidebar, because ...

### ISSUE THREAD

**Issue by modem-man-gmx** [lumapu/ahoy#554]
## Hardware
  * [X] ESP8266
  * [X] ESP32
  * [ ] Raspberry Pi

Modelname: any
Retailer URL: any

## Software
* [X] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0.5.65
Github Hash: ded5e70d790ba42dc2a1f7a69a321e8b606ce773

### Build & Flash Method:
* [ ] Arduino
* [ ] ESP Tools
* [X] Platform IO

### Desktop OS:
* [ ] Linux
* [X] Windows
* [ ] Mac OS

Menue setup in sub-menue "Protection":

Select pages which should be protected by password
Index [ ]
Live [ ]
Serial / Console [ ]
Settings  [v]
Update  [v]
System  [v]

With the above given settings, a later refresh/login requires to know the login url (http://192.168.xxx.yyy/login), otherwise one could never ever see the password protected menues.
Would be very nice to have this .../login url as a separate menue topic in the sidebar.

![Missing_login_again_request](https://user-images.githubusercontent.com/96957387/210886177-1270d93f-f94e-4f8d-ad1d-3e8dd2fb998d.png)

**Comment by modem-man-gmx** [comment]
I can visit any of the 5 remaining menues, no one asks me for the password to unveil the hidden menues.

**Comment by lumapu** [comment]
good point 👍, never thought about that. Will be included
