### ISSUE TITLE
Feature Request: Die aktuelle IP-Adresse bitte mit über MQTT publishen

### ISSUE THREAD

**Issue by matthias882** [lumapu/ahoy#556]
## Hardware
  * [x ] ESP8266
  * [x ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna

### Power Stabilization:
* [x ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [x ] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: 0.5.66
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [x ] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [x ] Windows
* [ ] Mac OS

### Debugging:
* [x ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hallo,

ich würde darum bitten die aktuell vergebene IP-Adresse der AHOY-DTU mit über MQTT bereitzustellen. Dies erleichtert den Weg um bei DHCP-Systemen auf die DTU zu gelangen. Auch wären somit dynamische Links aus Visualisierungsoberflächen möglich. Der Umweg über die DHCP-Tabelle des DHCP-Servers würde somit entfallen.

MfG
Matthias

**Comment by knickohr** [comment]
Hast Du schon mal den Send-Befehl im MQTT Settings ausprobiert ?  Meines Wissens wird da die IP übermittelt :

![07CB847F-FB6D-432A-8167-088B02C608D8](https://user-images.githubusercontent.com/63048210/211041962-87b2a4f2-d1aa-4a04-a7bf-058fc5496d69.jpeg)

**Comment by Gerri1** [comment]
@knickohr  Die IP-Adresse ist nicht mit dabei!
Bei OpenDTU schon!

**Comment by knickohr** [comment]
Das oben IST Ahoy 😉

**Comment by Gerri1** [comment]
In den ioBroker wird nix mit übertragen! ☹

**Comment by Gerri1** [comment]
free_heap ist mit drin, da wäre die IP-Adresse informativer.

**Comment by knickohr** [comment]
Da gebe ich Dir Recht, auch die Version könnte nur einmal übertragen werden.

Je öfter ich darüber nachdenke, halte ich den Vorschlag das Ganze als JSON zu verschicken für immer mehr sinnvoller 😲

Statische Werte brauchen meiner Meinung nach nur einmal bei Änderung übertragen werden, da darf dann auch die IP und sowas dabei sein. Das sollte dann aber retained geflaggt sein !

Dynamische Werte brauchen Nachts auch nur alle paar Minuten kommen. Tagsüber mindestens bei Änderung und auch in regelmäßigen Abständen (Beispiel Yield-Werte). Einige sollten allerdings auch zusätzlich noch retained sein.

Sich schnell ändernde Werte könnten meiner Meinung schneller übertragen werden als nur in 30s Intervallen. Klar, kann man einstellen, aber ich weiß nicht wie schnell es noch stabil geht.

Prinzipiell gesagt, es sollte eigentlich alles immer bei Änderung sofort übertragen werden, außer es kommt zu oft und macht die DTU zu.

**Comment by Gerri1** [comment]
Ich finde das so schon gut, im JSON muss ich wieder einen ganz schönen Aufwand betreiben, die Daten da raus zubekommen! 😒

**Comment by knickohr** [comment]
Ja, das ist es was mich auch abschreckt. Prinzipiell machen wir das aber sowieso irgendwie, und sei es nur wenn wir den Topic zerpflücken. Aber da gehen die Meinungen auseinander. Ich möchte jetzt ungern meine Flows neu machen nur weil es jetzt JSON ist.

Außerdem würde der ursprüngliche Sinn und Zweck von MQTT untergraben werden, so viel Information wie möglich in so wenig Daten wie nötig zu übermitteln, vor allem beim Subscribe.

**Comment by Gerri1** [comment]
Eigentlich bin ich mit der MQTT - Daten - Übermittlung, bis auf ein paar kleinigkeiten, sehr zufrieden!
Man erkennt auch sofort wenn's irgendwo hängt.

**Comment by knickohr** [comment]
Natürlich !  Ist Meckern auf sehr hohem Niveau, aber alles kann man besser machen 😉

**Comment by lumapu** [comment]
sehr konstruktive Diskussion! IP Adresse macht Sinn, natürlich retained.
JSON finde ich hier auch nicht so praktisch,  höchstens als zusätzliches Feld. Das frisst aber unnötig Ressourcen, mit denen wir sinnvoll haushalten sollten.

**Comment by knickohr** [comment]
… und bitte nur einmal ausgeben nach Boot oder Änderung 😉 @lumapu 

Vielleicht sollten wir das Thema MQTT mal komplett neu aufrollen und überdenken. Ich sehe aber leider schon wieder den Shitstorm 😪

JSON kann man sich doch per REST-api abholen wenn ich das richtig verstanden habe im Discord.

**Comment by matthias882** [comment]
Wow, was für eine riesige Diskussion habe ich da denn losgetreten? ;)
Bitte als einzelne Subscriptions lassen, das ist äußerst praktisch um direkt auf die 2 oder 3 Werte zugreifen zu können die man dauerhaft wirklich braucht und auch loggen will. Nur die IP-Adresse eben noch dazu.

Und übrigens ein ganz großes Dankeschön für diese tolle Arbeit. Ich lese das ganze Projekt schon seit den ersten Tagen auf Microcontroller.net mit und dachte mir die Tage ich könnte es ja endlich mal ausprobieren. Und was soll ich sagen, ich bin begeistert wie schnell und reibungslos es beim ersten Versuch in Betrieb ging und wie klasse die Bedienung und Parametrierung gemacht ist. Da können sich meine eigen WLAN-Sensoren ne Scheibe abschneiden ;)

**Comment by Gerri1** [comment]
> JSON kann man sich doch per REST-api abholen wenn ich das richtig verstanden habe im Discord.

... sollte so sein!

**Comment by knickohr** [comment]
@matthias882 

MQTT ist **immer** ein Reizthema, habe mir da auch schon blutige Nasen geholt 😅

**Comment by lumapu** [comment]
@knickohr ich glaube, wenn ich mir die letzten Diskussionen so anschaue, dass wir das nicht 'einfach so' definieren können. Es ergeben sich einfach über die Zeit neue Anforderungen und wir bessern Stück für Stück nach und testen dann wieder. Wenn du konkrete Ideen hast und die Diskussion nicht scheust, dann raus damit :stuck_out_tongue_winking_eye:

**Comment by knickohr** [comment]
@lumapu 

Das nennt sich Feigheit vor dem Feind. Ich laufe nicht weg und verkrieche mich 😂

**Comment by stefan123t** [comment]
@lumapu das sollten wir mE schon einmal grundlegend auf die Beine stellen. Vielleicht mit einem kleinen Konzept (Spreadsheet?) in dem wir u.a. auch die MQTT Topics von AhoyDTU und OpenDTU abgleichen. 

@knickohr Du könntest doch mal einen Vergleich der beiden Topic Bäume erstellen und in einem neuen Issue als Anhang posten. Vielleicht kann dan @DukeWolle auch mit drüber schauen ob es aus seiner Sicht auch passt und evtl. kommt dann sogar @Ichirou dazu und schaut sich das im Vergleich mit den ModBus485 Werten an ?
