### ISSUE TITLE
Fehler Serial

### ISSUE THREAD

**Issue by MarcXX82** [lumapu/ahoy#560]
Habe einen ESP8266 mit Ver: 0.5.66 u .68 und nrf24I01+ ohne ext. Antenne (Einst. HIGH) und 100uF Kondensator zusammen geschlossen, die Platineen sind von der DTU ca. 2m durch eine Stahlbetonwand getrennt...

Soweit läuft alles, werte werden ausgegeben und AhoyDTU funktioniert.

Jedoch wird mir in der Konsole immer wieder der Fehler "while retieving data: Frame 1 missing: Request Retransmit" und das Ganze auch mit "Frame 2" ausgeben...

Was will mir die DTU damit sagen???
Und eine Abhilfe dagegen wäre auch super... :)

Danke Markus

**Comment by lumapu** [comment]
das ist kein Fehler, sondern eine Warnung. Eine Nachricht vom Wechselrichter besteht je nach Typ aus mehreren 'Frames' (Paketen). Fehlt eines auf der Empfangseite, dann wird dieses neu angefordert. 
Das Pakete verloren gehen ist ganz normal. Je mehr Anschlüsse der Wechelrichter hat, desto mehr Pakete müssen übertragen werden und natürlich steigt auch die Fehleranfälligkeit.

Was du machen kannst: Für optimale Funkverbindung sorgen - wird aber nicht gelingen, da sowohl Mobilfunk als auch WLAN auf den 2.4MHz funken. Zum Problem für dich wird es erst, wenn über längere zeiträume keine komplette Nachricht vom Wechselrichter übertragen werden kann.
