### ISSUE TITLE
Wemo D1 -> SSD1306  Display 

### ISSUE THREAD

**Issue by Wolle40764** [lumapu/ahoy#568]
Need some help to get SSD1306  Display running. D1 D2 VCC and Ground connected.

**Comment by knickohr** [comment]
Please describe your problem.

**Comment by Gerri1** [comment]
Die richtige Firmware genommen?
221230_ahoy_0.5.66_esp8266_ssd1306_f8fe044.bin für den ESP8266 
oder 
221230_ahoy_0.5.66_esp32_ssd1306_f8fe044.bin für den ESP32

**Comment by Wolle40764** [comment]
Now it. Works ! Thanks a lot!!!
