### ISSUE TITLE
[ESP8266] AhoyDTU main page says "not producing", but the inverter does

### ISSUE THREAD

**Issue by SpaceTeddy** [lumapu/ahoy#576]
### Platform

ESP8266

### Model name

Wmos d1 mini

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

~100uF Elko

### Connection diagram

wire

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.70

### Github Hash

d8e255d

### Build & Flash Method

ESP Tools (flash)

### Desktop

Mac OS

### Setup

...

### Error description

-> Ahoy main page shows "inverter is available but not producing"
![image](https://user-images.githubusercontent.com/9148964/211769650-11f03c6f-c57b-4c2d-8a8c-7b97b397ebe2.png)

-> Live page shows P_AC: 2.7W P_DC:2.9W
![image](https://user-images.githubusercontent.com/9148964/211769761-5a16bbf2-ce74-4fe2-a28f-423e10f6ee92.png)

After a while that P_AC is > 3W, the main page changed to "producing!"
 
Is there a P_AC Power threshold for the main page information`?

thx

**Comment by knickohr** [comment]
Yes, if the power is below 3W, the Inverter returned „available and **not** producing“. This will stop if the inverter is not responding in 5 minutes or the Power is more than 3W.

**Comment by SpaceTeddy** [comment]
alright, thanks a lot for your confirmation!
