### ISSUE TITLE
Gibt es die Möglichkeit eine "Scan" Funktion zu implementieren?

### ISSUE THREAD

**Issue by Meckiilino** [lumapu/ahoy#588]
Hallo zusammen,
ich meine so eine Funktion, die man aus dem WLAN-Bereich kennt.
Einmal auf Scan drücken und alle kompatiblen Inverter in Reichweite werden aufgelistet.

**Comment by Juergen2453** [comment]
Wozu, willst du dann andere Inverter manipulieren? (So in der Art, der Nachbar hat mich geärgert dann manipuliere ich sein Inverter)

**Comment by Meckiilino** [comment]
Autsch - an Missbrauch habe ich gar nicht gedacht. (Ich glaube an das Gute im Menschen :-))
Es war eigentlich als Erleichterung gedacht - wenn man die Seriennummer nicht zur Hand hat und aufs Dach müsste.
Da hast du aber Recht - das Risiko besteht natürlich.

Issue kann somit geschlossen werden.

**Comment by stefan123t** [comment]
Dazu brauchst Du das BROADCAST 0x02 Command laut der Hoymiles DTU Software.
Wir haben bisher unzureichende Informationen zum Ablauf und brauchen ordentliche Traces von einer echten DTU und bevorzugt mehreren WR die discovered / gescannt werden.
Siehe https://github.com/lumapu/ahoy/wiki/Protocol#broadcast-0x02 und der Originale #386 und #301 
Dieses Issue wird daher wieder geschlossen.

**Comment by Thomas-PV-Tryer** [comment]
Schade - ich hatte das gleiche "Urproblem nicht lesbare Seriennummer"! Habe mich dann an die Hoymiles Hotline gewendet - dort gibt es ja die Scanfunktion und die Hotline verweist auch drauf.
Wäre toll, wenn sie doch jemand tragen und dann implementieren könnte ...
Mir sind die Hoymiles DTU's zu teuer ....
