### ISSUE TITLE
0.5.70 Yield Total Berechnung vertauscht.

### ISSUE THREAD

**Issue by Loetnase** [lumapu/ahoy#589]
### Platform

ESP8266

### Model name

Wemos D1 mini

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.70

### Github Hash

d8e255d

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Setup

hallo zusammen

230108_ahoy_0.5.70_d8e255d_esp8266_sh1106.bin

In der neuen 0.5.70 Yield Total Correktion sind die Werte beim Berechnen vertauscht.
30,61kWh Total minus 20 kWh sollten nicht -9,4 sondern 10,6 kWh rauskommen.
![grafik](https://user-images.githubusercontent.com/120967249/212549508-5d46c285-6889-4b33-9c70-5b9aab0c2916.png)

Ich wünsche noch ein schönes Wochenende

### Error description

![grafik](https://user-images.githubusercontent.com/120967249/212549640-f92be4e8-fad4-4bfc-9e99-b924c9f1fc37.png)

**Comment by lumapu** [comment]
ich denke es war eine fehldene Klammer 😄

**Comment by Loetnase** [comment]
@lumapu 
ich denke an der Klammer lag es nicht, ich sehe immer noch negative Werte. 
in der 5.73 und der 5.75 ist das noch gleich :-(

Ich denke es wird das Doppelte (40) vom Yield Total Correction (bei mir 20 eingetragen) der  Yield Total (aktuell 36,65 kWh) abgezogen ergibt die angezeigten -3,35 kWh. 
Der Faktor 2 könnte mit der Modulanzahl (2 bei mir) zusmmenhängen

Yield Total Correction (bei mir 20 eingetragen)
![grafik](https://user-images.githubusercontent.com/120967249/213867572-19d24b51-ccbb-404c-8bd6-8ead8bde947b.png)
![grafik](https://user-images.githubusercontent.com/120967249/213867611-8136dd4c-f712-45ce-a09e-72854609ba53.png)
![grafik](https://user-images.githubusercontent.com/120967249/213867637-608765c8-54cf-4410-8f3b-a8420b9858e5.png)

Yield Total Correction (bei mir 0 eingetragen)
![grafik](https://user-images.githubusercontent.com/120967249/213868948-79db6498-dced-4e81-aab4-44e2e68c934d.png)


Eventuell noch ein paar Gedanken zum Offseteintrag.
Ich denke der Eintrag wird durch die Anzahl der Module geteilt und dann auch bei den einzelnen Modulen abgezogen. Aber sobald die Module unterschiedlich produzieren (Verschattung usw.) oder gar bei einem 4-fach Inverter nur 3 Module angeschlossen sind, passt das Verhältnis so nicht mehr.
Ist es ein großer Aufwand für jedes Modul einen eigenen Offseteintrag machen zu können?
Die Summe daraus würde ja dann die Yield Total Correction ergeben.
Ich denke nur so lassen sich die einzelnen Module bewerten.

Heute bei leichtem Schneefall wurden bis jetzt 112 Wh produziert.
Ich wünsche allen ein schönes Wochenende. :-)

**Comment by dtuuser** [comment]
Gerade auf 0.5.76 geupdatet.
Habe jetzt mal den halben Korrekturwert bei der Correction eingegeben. Jetzt passt es. 
Kann es sein, dass der Correction Wert jeweils vom Panel abgezogen wird?

**Comment by Loetnase** [comment]
@dtuuser Ja, du hats recht, mit dem halben Korrekturwert passt das bei mir auch in der 0.5.76 an meinem HM600.

Da ist noch was zu tun.

Kann das noch jemand an einem 4 fach Wechselrichter HM1200 oder HM1500 ausprobieren, vielleich muss da nur ein Viertel eingetragen werden, oder bei einem HM300 der ganze Wert. 

In der  Version 0.5.76 sind jetzt auch schön die Displays mit eingebaut worden.
Ich habe das SH1106 ausgewählt aber die parallel geschalteten SSD1306 interresiert das nicht, die funzen auch in meinem Testaufbau.
![grafik](https://user-images.githubusercontent.com/120967249/213927752-856ee8bb-d017-4654-a0e9-5e24cc524e76.png)

Das gefällt mir. Vielen Dank an den oder die "Macher".

**Comment by Loetnase** [comment]
@lumapu, @stefan123t, @dtuuser   

in der neuen 0.5.78 ist der Bug immer noch drin.
Es funktioniert aber wenn man den halben Offsetwert einträgt.

Eventuell noch ein paar Gedanken zum Offseteintrag. Siehe auch Post oben.
Ich denke der Eintrag wird durch die Anzahl der Module geteilt und dann auch bei den einzelnen Modulen abgezogen. Aber sobald die Module unterschiedlich produzieren (Verschattung usw.) oder gar bei einem 4-fach Inverter nur 3 Module angeschlossen sind, passt das Verhältnis so nicht mehr.
Ist es ein großer Aufwand für jedes Modul einen eigenen Offseteintrag machen zu können?
Die Summe daraus würde ja dann die Yield Total Correction ergeben.
Ich denke nur so lassen sich die einzelnen Module bewerten.

**Comment by lumapu** [comment]
klingt sinnvoll und wäre konsistent. Denke auch wir müssen für jeden Eingang einen Wert vorsehen.

**Comment by MiniOh** [comment]
Hallo, 

wurde hier schon etwas angepasst?
In der 0.5.78 ist es ja noch so, dass die eingetragene "Yield Total Correction (will be subtracted) [kWh]" im einem Inverter, pro Modul abgezogen wird.

Also wenn ich meine Yield Total um 1000kWh anpassen möchte, mütte ich bei einem HM-1500 "250" eintragen, richtig?
Zudem ist es nur möglich, die Werte zu verringern, da die Werte ja subtrahiert werden.
Ich möchte eigentlich +1000kWh in die Yield Total dazurechnen. Geht das auch?

Danke schon mal.

**Comment by lumapu** [comment]
ja das ist noch offen, Plan ist es Modulweise also pro Eingang anzubieten

**Comment by MiniOh** [comment]
Ist es evtl möglich kurzfristig positive Korrekturen einzubauen mit einer Auswahl ob + oder -?
Pro Modul kann man sich ja helfen indem man ganze, halbe oder viertel Werte einträgt?
Evtl hast du ja schnell eine 0.5.86 gebaut?
Würde mich freuen, da ich einen Inverter tauschen musste.

**Comment by lumapu** [comment]
eher gegen Abend heute 😃

**Comment by MiniOh** [comment]
Klingt fast genauso gut ;)

**Comment by MiniOh** [comment]
Morgen, 

vielen Dank fürs umbauen.
Beim ersten Versuch scheint aber noch nicht alles zu passen.
Ich habe bei einem HM-1500 bei Modul 1 und 2 jeweils 333 kWh addiert.

Hier werden aber bei Modul 4 merkwürdige Werte ausgegeben.

![ahoy_inverter_corr_1](https://user-images.githubusercontent.com/27901554/218297773-01ebdfbc-5f3d-44fc-b0b8-88813039aab9.PNG)

![ahoy_inverter_corr_2](https://user-images.githubusercontent.com/27901554/218297778-9bda6fd8-a568-4f2e-bf9f-0d3928916b9a.PNG)
