### ISSUE TITLE
setup as container - sb already tried?

### ISSUE THREAD

**Issue by isarrider** [lumapu/ahoy#592]
Hi,

as a Pi (pr sth else) is needed anyway for running InfluxDB,
did already try to pack everything in a container?

BR,
Alex

## Hardware
  * [ ] ESP8266
  * [ ] ESP32
  * [ X ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ X ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ X ] circuit board
* [ ] external antenna

### Power Stabilization:
* [ X ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

**Comment by stefan123t** [comment]
See your other feature request #598
There are not so many RPi implementation users active on the github, hence there is limited response. You may want to join the Discord channel #dev-ahoy-raspberry to meet other users too.
