### ISSUE TITLE
Some Failurs comes up after starting 

### ISSUE THREAD

**Issue by nobe2023** [lumapu/ahoy#593]
## Hardware
  * [ ] ESP8266
  * [ ] ESP32
  * [x ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ x] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ x] circuit board
* [ ] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ x] Voltage stabilizing motherboard

### Connection diagram:
* [ x] Image of the your wiring attached

| nRF24L01+ Pin | Rasp GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | Pin 6 GND            |
| Pin 2 +3.3V   | Pin 1 +3.3V          |
| Pin 3 CE      | GPIO22  CE   Pin 15 |
| Pin 4 CSN     | GPIO8  CS   Pin 24 |
| Pin 5 SCK     | SCLK Pin 23 |
| Pin 6 MOSI    | MOSI Pin 19 |
| Pin 7 MISO    | MISO Pin 21 |
| Pin 8 IRQ     | not used |

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [ x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [ ] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [ x] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Sorry, but I´m realy not a programmer and only a very stupid user.
I have done all the step are written for the Raspberry. The RF-Installtion look "good?" I can start the scrpit and get a selection of possibilities. Here I have chosen "R". Nothing happens, after a certain time the selection comes back. At least there is no error.

I also downloaded the Git inventory from AHOY and executed the call "sudo python3 -um hoymiles --log-transactions --verbose --config /home/pi/ahoy/tools/rpi/ahoy.yml | tee -a log2.log" under "~/ahoy/tools/rpi".

I edit the Serialnumber from my HM-1500 in "ahoy.yml".

It takes some time again and then various messages come up that I can't interrupt:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/ahoy/tools/rpi/hoymiles/__main__.py", line 345, in <module>
    mqtt_client = MqttOutputPlugin(mqtt_config)
  File "/home/pi/ahoy/tools/rpi/hoymiles/outputs.py", line 168, in __init__
    mqtt_client.connect(config.get('host', '127.0.0.1'), config.get('port', 1883))
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Can Someone help me pleas to undestand what's worng?

Thanks a lot for your support, and thanks for you work.

**Comment by stefan123t** [comment]
@nobe2023 this looks like you have no MQTT broker running on 127.0.0.1 Port 1883 as the code tries to connect to it in order to push the results into the MQTT broker for consumption by any of your Home Automation clients.
