### ISSUE TITLE
Feature request: Display-Helligkeit einstellen per Weboberfläche.

### ISSUE THREAD

**Issue by TB-79** [lumapu/ahoy#594]
Die Displays mit weißer Schrift sollen schnell altern/einbrennen.
Von daher wäre die ein/aus und auch die Sunrise-Kopplung anzuraten (Feature request bereits eingereicht) und zusätzlich auch die Möglichkeit die Helligkeit einzustellen in den Web settings.

**Comment by knickohr** [comment]
Sehr gut, wenn wir dann schon dran sind, auch gleich eine Option zum drehen des Displays um 180 Grad. Wird bei den blau/gelben OLED interessant, da diese eine hardwaretechnisch bedingte abgedeckte Zeile haben. Prinzipiell könnte man das OLED auch dauerhaft um 180 Grad drehen.

**Comment by kloppy1984** [comment]
Ich denke am ESP8266 wird kein Pin frei sein, für die Steuerung der Helligkeit

**Comment by knickohr** [comment]
Das wird über die Software eingestellt 😉

**Comment by kloppy1984** [comment]
@knickohr 
Dann hätte ich gern mal ein Anschlussplan wo der Light angeschlossen wird... :-) 
Bei sind alle alle Pins belegt...

**Comment by knickohr** [comment]
Es geht hier um OLED, wie @TB-79 im ersten Beitrag geschrieben hat. Klar, das Nokia kann man beleuchten, kannst ja über einen Schalter machen. Wenn Du einen PWM möchtest, dann wird’s in der Tat knapp mit dem 8266.
