### ISSUE TITLE
Sonderzeichen im Modul Namen

### ISSUE THREAD

**Issue by Ollipop030** [lumapu/ahoy#597]
Nur eine Kleinigkeit:

Sonderzeichen im Modulnamen werden zwar übernommen, aber falsch dargestellt. Aus "Süd" wird "S�d". Bekommt man das irgendwie hin?

**Comment by knickohr** [comment]
Ich würde ehrlich gesagt von Sonderzeichen, Umlauten und all dem Zeuchs Abstand nehmen. Bringt immer wieder Probleme, auch wenn es augenscheinlich funktionieren mag.

**Comment by QuickStopGroceries** [comment]
Du kannst "Süd" als `S&uuml;d` eintragen, dann funktioniert es.

**Comment by stefan123t** [comment]
Kannst Du mal schauen ob die Seite als UTF-8 encoded ausgeliefert wird ?

**Comment by Ollipop030** [comment]
> Du kannst "Süd" als `S&uuml;d` eintragen, dann funktioniert es.

Das ist ein guter Tipp, danke.

**Comment by stefan123t** [comment]
@lumapu der Workaround mit `&uuml;` (6 Bytes) statt dem Umlaut `ü` 1 Byte will mir nicht recht gefallen.
Haben wir den Content-Type Header auch überall richtig gesetzt ?

Hier wird er nur im Request-(?) Header gesetzt:
https://github.com/lumapu/ahoy/blob/main/src/web/html/api.js#L99
```c
            xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
```

Und hier zum Download:
https://github.com/lumapu/ahoy/blob/main/src/web/RestApi.h#L144
```c
            response->addHeader("Content-Type", "application/octet-stream");
```

Müssten wir den Content-Type Header mit `charset=UTF-8` nicht auch generell im Response Header der API setzen oder macht das der ESPAsyncWebServer im Default ?

**Comment by lumapu** [comment]
ich brauche den issue noch als Gedankenstütze 😊

**Comment by Ollipop030** [comment]
Sorry dafür. Habe gestern mal ein paar erledigte Issues geschlossen. War hier wohl ein bisschen zu schnell. ;-)

**Comment by lumapu** [comment]
sollte mit aktuellen Dev Versionen gehen, ich denke ab `0.5.93`
