### ISSUE TITLE
Feature Request: RPi Docker Container

### ISSUE THREAD

**Issue by isarrider** [lumapu/ahoy#598]
Hi,

as far as I can see with a quick view,
it should be doable to build a docker container...

When I am back from holiday,
Ill give it a try - that way we can also Host on the Pi InfluxDB & Grafana...

BR,
Alex

**Comment by stefan123t** [comment]
Thanks for the suggesstion / enhancement. We are expecting your PR of the Dockerfile you want to contribute.

**Comment by isarrider** [comment]
@PaeserBastelstube 
quick question - why is the NRF24 Python Wrapper used here - that makes it harder to write the Dockerfile...
https://github.com/Knedox/hoymiles_control uses circuitpython-nrf24l01...
would this be an option?

**Comment by lumapu** [comment]
Dockerfile was merged in March
