### ISSUE TITLE
RaspberryPi MQTT Topic fixed in Line 192 of tools/rpi/hoymiles/outputs.py

### ISSUE THREAD

**Issue by kct-networx** [lumapu/ahoy#601]
### Platform

RaspberryPi

### Model name

3B+

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

~100uF Elko

## Connection diagram I used:
https://github.com/lumapu/ahoy/blob/main/doc/RasPi_nRF24L01%2B_schem.png

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

main

### Github Hash

32366ba

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Setup
ahoy.yaml

### Error description

Line 192 in tools/rpi/hoymiles/outputs.py sets the MQTT Topic to a fixed value of 'Inverter-Name/Inverter_Serial-No'.
It does not care about the Inverter-MQTT-Topic Setting in ahoy.yaml
In previous Versions, the outputs.py took care about that.

>   inverters:
>     - name: 'balkon'
>       serial: 111234567891
>       txpower: 'low'                      # txpower per inverter (min,low,high,max)
>       mqtt:
>         send_raw_enabled: false           # allow inject debug data via mqtt
>         topic: 'hoymiles/balkon'    # defaults to '{inverter-name}/{serial}'
> 

(sorry - code aove is not indented as in original ahoy.yaml, but the content is correct.)

BTW: Changing the topics in emeter-dc from daily to YieldDay and from total to YieldTotal is a breaking change. Is there any reason for that, or just a copy&paste typo from the volkszaehler part?!?

**Comment by stefan123t** [comment]
Hi @kct-networx
yes, this sounds logically to me, though only we do not modify / update the code under the RPi implementation ourselfs.
We are mostly working on the ESP implementations only.

The original developer of the python module [Sprinterfreak/ahoy](https://github.com/Sprinterfreak/ahoy) is happy with his version and as far as I know hasn't changed / maintained that implementation here for a while on github.

If you want to change / remedy this issue please go ahead and create a pull request which we will happily merge into our current master. 
You may want to join the other RPi users on our Discord #dev-ahoy-raspberry channel or check the issues here on github which we have tagged with RPi so far:
https://github.com/lumapu/ahoy/issues?q=is%3Aopen+is%3Aissue+label%3ARPI

Kind regards,
Stefan
