### ISSUE TITLE
Feature Request: Anzeige last Alarm:

### ISSUE THREAD

**Issue by Juergen2453** [lumapu/ahoy#608]
Auf der Webseite von AhoyDTU gibt es dir Info **"last Alarm: Inverter start"**
Allerdings ändert sich die Anzeige nicht auch wenn es andere Alarme gibt.
Besser wäre es wenn es einen Punkt geben würde z.B. letzte Alarme oder Fehlerbericht...
Dann öffnet sich ein Fenster und die Meldungen werden angezeigt.
Der jetzige Anzeige "last Alarm: Inverter start" macht so kein sinn.

**Comment by jimknopf63** [comment]
> Auf der Webseite von AhoyDTU gibt es dir Info **"last Alarm: Inverter start"**
> Allerdings ändert sich die Anzeige nicht auch wenn es andere Alarme gibt.
> Besser wäre es wenn es einen Punkt geben würde z.B. letzte Alarme oder Fehlerbericht...
> Dann öffnet sich ein Fenster und die Meldungen werden angezeigt.
> Der jetzige Anzeige "last Alarm: Inverter start" macht so kein sinn.

Also im Prinzip wie das bei OpenDTU gehandelt wird. Da werden 15 Alarme im Verlauf gezeigt

**Comment by Juergen2453** [comment]
Genau so in der Art, oder überhaupt keine Anzeige.

**Comment by stefan123t** [comment]
Siehe auch #600 und #177

**Comment by lumapu** [comment]
@stefan123t kannst du erklären warum es auch ein "AlarmUpdate" Command gibt und wann ich es nutzen sollte?

**Comment by stefan123t** [comment]
@lumapu ich weiß es nicht, aber soweit ich es vermute kann man mit dem AlarmUpdate Command die alten bereits abgerufenen AlarmData Zeilen aus dem WR RAM löschen. Wir haben das Kommando m.W. bisher noch nicht bei einer Original DTU mit getraced daher ist die Anwendung hier nicht zweifelsfrei klar.
Alles was ich bisher dazu in Erfahrung bringen konnte findet sich hier https://github.com/lumapu/ahoy/wiki/Protocol#wie-sieht-das-device-info-kommando-alarm-data-0x11--alarm-update-0x12-aus-

**Comment by lumapu** [comment]
@stefan123t danke für deine Antwort. Ins Wiki hatte ich schon geschaut, aber nichts brauchbares finden können

**Comment by stefan123t** [comment]
@lumapu eventuell hilft hier nochmal der Blick in die Hoymiles DTU Pro sources oder ein neues Trace mit einem vollen Event/AlarmLog. Dann sollte die Hoymiles DTU ja das AlarmData Log aufräumen und dazu braucht sie mE auch das AlarmUpdate.
Laut Thomas kann man mit schneller Abfrage des SystemConfig Commands nach einem PowerLimit Fehler im WR Log erzeugen.

**Comment by knickohr** [comment]
Endlich !  😎

![IMG_1083](https://github.com/lumapu/ahoy/assets/63048210/3780c269-76ed-4d9e-936f-a061549c35d3)

(Auch wenn noch nix drin steht 🤪)

**Comment by lumapu** [comment]
Inverter start sollte schon drin stehen, allerdings fehlt noch das Zeitzonen Offset, das kommt heute noch dazu 😇

**Comment by knickohr** [comment]
Ein kleiner Schritt für einen Programmierer, aber ein großer Schritt für die Benutzer 😅

Damit wird Ahoy nochmals um einen großen Schritt aufgewertet 😎
