### ISSUE TITLE
Keine Anzeige unter Live

### ISSUE THREAD

**Issue by Hoykaldi** [lumapu/ahoy#610]

**Comment by stefan123t** [comment]
Keine Beschreibung im Issue ?

**Comment by dtuuser** [comment]
Unter altem Firefox ist das bei mir auch so

**Comment by lumapu** [comment]
@Hoykaldi 
* Screenshot ? 
* Version ?

**Comment by Hoykaldi** [comment]
Hallo, funktioniert wieder. Danke
