### ISSUE TITLE
ESP-32  serial output:  W: while retrieving data: last frame missing: Request Retransmit  --> es werden keine Daten angezeigt

### ISSUE THREAD

**Issue by franzgyoeroeg** [lumapu/ahoy#613]
### Platform

ESP32

### Model name

ESP 32 D0WDQ5

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

## Connection diagram I used:
 
| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

 

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

release 0.5.66

### Github Hash

f8fe044

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: [114181815193]
    - Name: HM-800
    - Active Power Limit: 450
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 450,450
    - Module Name: m1, m2
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: 2.at.pool.ntp.org
    - NTP Port: 123
### no MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Debug Serial Log output

```shell
[SERIAL/DIRECT] CONNECTED TO PORT COM3 (115200-8N1)

ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13104
load:0x40080400,len:3036
entry 0x400805e4
I: Initializing FS ..
I:  .. done
I: Settings valid: true
I: RF24 Amp Pwr: RF24_PA_I: LOW
I: Radio Config:
SPI Frequency           = 1 Mhz
Channel                 = 3 (~ 2403 MHz)
Model                   = nRF24L01+
RF Data Rate            = 250 KBPS
RF Power Amplifier      = PA_LOW
RF Low Noise Amplifier  = Enabled
CRC Length              = 16 bits
Address Length          = 5 bytes
Static Payload Length   = 32 bytes
Auto Retry Delay        = 250 microseconds
Auto Retry Attempts     = 0 maximum
Packets lost on
    current channel     = 0
Retry attempts made for
    last transmission   = 15
Multicast               = Disabled
Custom ACK Payload      = Disabled
Dynamic Payloads        = Enabled
Auto Acknowledgment     = Disabled
Primary Mode            = RX
TX address              = 0xdeadbeef01
pipe 0 (closed) bound   = 0xdeadbeef01
pipe 1 ( open ) bound   = 0x4477388501
pipe 2 (closed) bound   = 0xc3
pipe 3 (closed) bound   = 0xc4
pipe 4 (closed) bound   = 0xc5
pipe 5 (closed) bound   = 0xc6

---------
         AhoyDTU Info:
Version: 0.5.66
Github Hash: f8fe044

---------
         AP MODE
                SSID: AHOY-DTU
PWD: esp_8266
IP Address: http://192.168.4.1
---------

Wifi event: 0
Wifi event: 2
Wifi event: 10
connect to network 'wurschtl24' ...
I: added inverter 114181815193
I: added inverter 114181815389
reconnect in 9 seconds
Wifi event: 4

[WiFi] Connected
[WiFi] AP disabled
Wifi event: 7


--------------------------------
Welcome to AHOY!

point your browser to http://192.168.1.111 (Station)
to configure your device
--------------------------------

Wifi event: 11
[  1405][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for
I: MQTT disconnected, reason: TCP disconnect
[  2032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
[  7032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
[ 12032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
[ 17032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
[ 22032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
[ 27032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
I: resetPayload: id: 1
I: (#1) enqueuedCmd: 1
I: (#1) enqueuedCmd: 11
I: (#1) enqueuedCmd: 5
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch40 | 15 81 81 53 89 85 38 77 44 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 AB AB
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch61 | 15 81 81 53 89 85 38 77 44 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 AB AB
[ 32032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch75 | 15 81 81 53 89 85 38 77 44 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 AB AB
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch3 | 15 81 81 53 89 85 38 77 44 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 AB AB
[ 37032][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for 2.at.pool.ntp.org
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch23 | 15 81 81 53 89 85 38 77 44 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 AB AB
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch40 | 15 81 81 53 89 85 38 77 44 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 AB AB
I: Rebooting...
Wifi event: 5
[ 41039][E][WiFiSTA.cpp:253] begin(): disconnect failed!
[ 41040][E][WiFiGeneric.cpp:1166] mode(): Could not set mode! 12308
connect to network 'wurschtl24' ...
I: [WiFi] Connection Lost
Wifi event: 3
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13104
load:0x40080400,len:3036
entry 0x400805e4
I: Initializing FS ..
I:  .. done
I: Settings valid: true
I: RF24 Amp Pwr: RF24_PA_I: LOW
I: Radio Config:
SPI Frequency           = 1 Mhz
Channel                 = 3 (~ 2403 MHz)
Model                   = nRF24L01+
RF Data Rate            = 250 KBPS
RF Power Amplifier      = PA_LOW
RF Low Noise Amplifier  = Enabled
CRC Length              = 16 bits
Address Length          = 5 bytes
Static Payload Length   = 32 bytes
Auto Retry Delay        = 250 microseconds
Auto Retry Attempts     = 0 maximum
Packets lost on
    current channel     = 0
Retry attempts made for
    last transmission   = 15
Multicast               = Disabled
Custom ACK Payload      = Disabled
Dynamic Payloads        = Enabled
Auto Acknowledgment     = Disabled
Primary Mode            = RX
TX address              = 0xdeadbeef01
pipe 0 (closed) bound   = 0xdeadbeef01
pipe 1 ( open ) bound   = 0x4477388501
pipe 2 (closed) bound   = 0xc3
pipe 3 (closed) bound   = 0xc4
pipe 4 (closed) bound   = 0xc5
pipe 5 (closed) bound   = 0xc6

---------
         AhoyDTU Info:
Version: 0.5.66
Github Hash: f8fe044

---------
         AP MODE
                SSID: AHOY-DTU
PWD: esp_8266
IP Address: http://192.168.4.1
---------

Wifi event: 0
Wifi event: 2
Wifi event: 10
connect to network 'wurschtl24' ...
I: added inverter 114181815193
I: added inverter 114181815389
reconnect in 9 seconds
Wifi event: 4

[WiFi] Connected
[WiFi] AP disabled
Wifi event: 11
Wifi event: 7


--------------------------------
Welcome to AHOY!

point your browser to http://192.168.1.111 (Station)
to configure your device
--------------------------------

[  1416][E][WiFiGeneric.cpp:1476] hostByName(): DNS Failed for
I: MQTT disconnected, reason: TCP disconnect
I: [NTP]: 2023-01-21 14:22:32 UTC
I: resetPayload: id: 1
I: (#1) enqueuedCmd: 1
I: (#1) enqueuedCmd: 11
I: (#1) enqueuedCmd: 5
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch40 | 15 81 81 53 89 85 38 77 44 80 01 00 63 CB F5 44 00 00 00 00 00 00 00 00 B3 E0 8A
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch61 | 15 81 81 53 89 85 38 77 44 80 01 00 63 CB F5 44 00 00 00 00 00 00 00 00 B3 E0 8A
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch75 | 15 81 81 53 89 85 38 77 44 80 01 00 63 CB F5 44 00 00 00 00 00 00 00 00 B3 E0 8A
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch3 | 15 81 81 53 89 85 38 77 44 80 01 00 63 CB F5 44 00 00 00 00 00 00 00 00 B3 E0 8A
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch23 | 15 81 81 53 89 85 38 77 44 80 01 00 63 CB F5 44 00 00 00 00 00 00 00 00 B3 E0 8A
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch40 | 15 81 81 53 89 85 38 77 44 80 01 00 63 CB F5 44 00 00 00 00 00 00 00 00 B3 E0 8A
I: resetPayload: id: 0
I: (#0) enqueuedCmd: 1
I: (#0) enqueuedCmd: 11
I: (#0) enqueuedCmd: 5
I: (#0) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch61 | 15 81 81 51 93 85 38 77 44 80 01 00 63 CB F5 62 00 00 00 00 00 00 00 00 D2 52 67
W: while retrieving data: last frame missing: Request Retransmit
I: (#0) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch75 | 15 81 81 51 93 85 38 77 44 80 01 00 63 CB F5 62 00 00 00 00 00 00 00 00 D2 52 67
W: while retrieving data: last frame missing: Request Retransmit
I: (#0) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch3 | 15 81 81 51 93 85 38 77 44 80 01 00 63 CB F5 62 00 00 00 00 00 00 00 00 D2 52 67
W: while retrieving data: last frame missing: Request Retransmit
I: (#0) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch23 | 15 81 81 51 93 85 38 77 44 80 01 00 63 CB F5 62 00 00 00 00 00 00 00 00 D2 52 67
W: while retrieving data: last frame missing: Request Retransmit
I: (#0) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch40 | 15 81 81 51 93 85 38 77 44 80 01 00 63 CB F5 62 00 00 00 00 00 00 00 00 D2 52 67
W: while retrieving data: last frame missing: Request Retransmit
I: (#0) sendTimePacket
I: sendTimePacket 1
I: TX 27B Ch61 | 15 81 81 51 93 85 38 77 44 80 01 00 63 CB F5 62 00 00 00 00 00 00 00 00 D2 52 67
I: resetPayload: id: 1
I: (#1) sendTimePacket
I: sendTimePacket b
I: TX 27B Ch75 | 15 81 81 53 89 85 38 77 44 80 0B 00 63 CB F5 80 00 00 00 00 00 00 00 00 7C 88 E3
W: while retrieving data: last frame missing: Request Retransmit
I: (#1) sendTimePacket
I: sendTimePacket b
I: TX 27B Ch3 | 15 81 81 53 89 85 38 77 44 80 0B 00 63 CB F5 80 00 00 00 00 00 00 00 00 7C 88 E3
W: while retrieving data: last frame missing: Request Retransmit
```

### Error description

1) mit Version 0.5.72 kein geändertes Verhalten

**Comment by lumapu** [comment]
die üblichen Fragen:

- Kondensator verbaut (hier nicht so relevant, aber evtl. zu späterem Zeitpunkt)
- Pinout schon mal verdreht getestet (IRQ und CE vertauschen). Gilt für Hardware als auch in den Einstellungen
- Abstand zum Wechselrichter, NRF24 mit oder ohne Antenne

**Comment by franzgyoeroeg** [comment]
zu 1) kein Kondensator verbaut
zu 2) CE und IRQ getauscht --> keine Änderung
zu 3) NRF24 mit Antenne, Abstand zum Wechselrichter etwa 5 m, die Standard DTU light von Hoymiles funktionert im selben Abstand tadellos

**Comment by lumapu** [comment]
ok, das sind schon gute Voraussetzungen.
Hat du zufällig noch einen zweiten ESP um auch diesen ausschließen zu können. Es gab auch schon Defekte nrf24 Module.

Sind die Verbindungen gelötet? Wir hatten leider auch schon mit Steckverbindungen Probleme.

**Comment by franzgyoeroeg** [comment]
Verbindungen sind gesteckt, nicht gelötet
Habe dann nacheinander 
1) 2. esp32 neu  --> keine Änderung
2) 2. nrf24l01+ neu --> keine Änderung
3) alle Steckverbindungen neu (neue Drähte)  -> keine Änderung

Folgende Software habe ich eingesetzt (geflasht mit flash_download_tool_3.9.3)
Directory ahoy_0.5.66
Bootloader.bin		                        0x1000
partition.bin 		                                0x8000
221230_ahoy_0.5.66_esp32_f8fe044.bin	0x10000
von  download flash_download_tool_3.9.3
boot_app0.bin		                               0xe000

wird ota.bin benötig ?

welche Bedeutung haben die wemos pinouts ?
- CS: D8 (GPIO15)
- CE: D4 (GPIO2)
- IRQ: D3 (GPIO0)

recht herzlichen Dank für die Unterstützung

**Comment by lumapu** [comment]
am einfachsten über das Online-Flash-Tool von Ahoydtu.de flashen. Dann muss man sich keine Gedanken über die richtigen Dateien machen.
Das gepostete Pinout gehört zum ESP8266 und nicht zu dem hier verwendeten ESP32. Evtl. liegt hier das Problem.

**Comment by stefan123t** [comment]
@franzgyoeroeg bitte sowohl Elko an das NRF24 Modul anlöten als auch die Steckerleisten. Wir hatten auch schon Nutzer die die Steckerleisten einfach so zusammengesteckt hatten ohne ordentliche Kontakt/Lötstellen.
Am Besten mal ein Foto vom Aufbau posten.

**Comment by franzgyoeroeg** [comment]
zuersteinmal die Fotos
![20230125_153222-k](https://user-images.githubusercontent.com/122021733/214593527-183ad0f3-3af0-436e-8648-835e56d131c1.jpg)
![20230125_153344-k](https://user-images.githubusercontent.com/122021733/214593553-37cd0f18-41ea-47f9-b709-4f5216466a39.jpg)
![20230125_153417-k](https://user-images.githubusercontent.com/122021733/214593560-fca18ffc-f696-4ebb-b64d-0e6706f68508.jpg)
Muß noch einen Elko organisieren und löten

**Comment by stefan123t** [comment]
Manche haben auch berichtet dass die Dupont Jumper Wire's zu dünn / lang sind um genügend Spannung am NRF ab zu liefern, daher ja der Elko. Also Elko schadet nicht und die Lötstellen sehen ganz gut aus. 
Bis auf rot (3.3V) und schwarz (GND) habe ich bei mir andere Farben, daher kann / will ich das jetzt nicht kontrollieren :stuck_out_tongue_winking_eye:

**Comment by franzgyoeroeg** [comment]
Mit Elko, 100uF gelötet,  plaudern nun die Komponenten (5 Inverter HM800). Zeitweise kommt noch immer zu Fehlermeldungen. frame1, frame2 oder last frame missing, auf unterschiedlichen Kanälen. Daten sind aber vorhanden und fürs erste plausibel! Steckverbindungen noch nicht gelötet! Test über längere Zeit nun aktiv mit Version 0.5.66.  Nächster Schritt Drähte verstärken und danach löten.

**Comment by beegee3** [comment]
missing frames sind nicht wirklich Fehlermeldungen. Die WR übermitteln ihre Daten auf immer wechselnden Kanälen. Ein Schema für diese Wechsel ist nicht erkennbar, daher wird zyklisch auf allen in Frage kommenden Kanälen kurze Zeit gelauscht. Da kann es passieren, das man eine Nachricht nicht (vollständig) mitbekommt. Solche 'missing frames' werden aber sofort nochmal abgefragt. Man verpasst also nichts!
