### ISSUE TITLE
Vorteile ESP32?

### ISSUE THREAD

**Issue by New-three** [lumapu/ahoy#616]
Welche Vorteile habe ich wenn ich einen ESP32 benutze anstatt einem ESP8266?
Diese Information konnte ich nicht wirklich finden.

**Comment by knickohr** [comment]
Momentan gibt es noch keine Vor- und Nachteile. Bis jetzt ist alles gleich. Der 32er hat halt mehr Pins und einen schnelleren Prozessor. Das wirkt sich aber bis jetzt noch nicht wirklich aus.

**Comment by stefan123t** [comment]
Für AhoyDTU gibt es bisher keine zwingenden Gründe für einen ESP32 anstelle des ESP8266.
Du kannst aber ggf. auch die OpenDTU Firmware aufspielen, die gibt es nämlich nur für ESP32.
