### ISSUE TITLE
Sonderzeichen WLAN-Passphrase nicht erlaubt?

### ISSUE THREAD

**Issue by IngoEF** [lumapu/ahoy#617]
Sie scheinen die Verbindung zu Verhindern.
Steht da z.B. "$" in drin, kann die DTU sich nicht verbinden.
Lässt an es weg, funktioniert's.

**Comment by lumapu** [comment]
kann ich nicht erklären warum das so sein soll. Nach meiner Auffassung müssen sie Zeichen funktionieren.

**Comment by IngoEF** [comment]
Seltsam, nachdem ich das jetzt nochmal getestet habe, geht's. Allerdngs habe ich zwischendurch das Update von 0.5.66 auf 0.5.76 gemacht.
Wie auch immer. Mein Einwand kann ingoriert weden
