### ISSUE TITLE
Feature Request :  Displayorientation um 180 Grad drehbar machen

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#619]
Was für ein OLED belanglos ist, da man es in jedem Winkel gleich gut ablesen kann, fällt bei dem LCD von Nokia schon ins Gewicht. Das Display läßt sich in der jetzigen Orientation schlechter ablesen als wenn man es um 180 Grad dreht. Der Grund ist Hardwaretechnisch bedingt, LCDs haben eine Vorzugsblickrichtung.

Deshalb bitte die Orientation des Nokia um 180 Grad drehen oder es über ein Setting auf der Webseite einstellbar machen.

**Comment by tqma1** [comment]
Würde auch bei den OLED´s nicht schlecht sein aufgrund der Position der Anschlüsse und Einbausituation im Gehäuse ....

**Comment by lumapu** [comment]
hoffentlich kann das die Lib, dann ist es schnell eingebaut 😊

**Comment by knickohr** [comment]
Ich bin mir sicher das die Lib das hat :
https://github.com/olikraus/u8g2/wiki/u8g2reference#setdisplayrotation

Oder vielleicht besser das hier ?
https://github.com/olikraus/u8g2/wiki/u8g2reference#setflipmode

Oh, die Orientation wird offenbar schon bei der Initialisierung mitgegeben :

U8G2_SSD1306_128X64_NONAME_1_4W_SW_SPI u8g2(**U8G2_R0**, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);

Bei der Gelegenheit bitte auch einen „clean Screen“ machen nach dem Bootlogo und Reboots. Hin und wieder bleiben einzelne Pixel im Speicher der Displays hängen.

https://github.com/olikraus/u8g2/wiki/u8g2reference#cleardisplay

**Comment by knickohr** [comment]
Ich glaube das kann man zu machen, ist ja umgesetzt.
