### ISSUE TITLE
teils off topic: Nulleinspeisung mit HM-1500

### ISSUE THREAD

**Issue by trombose009** [lumapu/ahoy#622]
Hallo, 

ich würde gern mit ahoy (schon rein lesend im Einsatz), meinem Hoymiles HM-1500 und einem pylontech akku eine nulleinspeisung umsetzen. 
Ich habe gesehen, dass man die absolute power in watt via mqtt steuern kann. 
Der hm-1500 hat ja aber 4 Eingänge. Bezieht sich dieses Steuern dann schon auf die reine Abgabe von Energie ins Netz, unabhängig davon, zu welchem der vier Eingänge der Strom reinkommt? 
Mein Plan ist bisher, den Akku einfach an nur einen (oder zwei) der Eingänge zu hängen. Das würde mir genügen. Die anderen zwei Eingänge belasse ich wie sie sind mit einem Balkonkraftwerk dran. Je zwei Eingänge besitzen meines Wissens nach einen gemeinsamen MPPT. 
Geladen wird der Pylontech nicht über das Balkonkraftwerk. Ich habe zwischenzeitlich eine sehr große PV Anlage und würde den Akku mit einem einfachen DC Netzteil laden. 

Weiß hier zufällig jemand, ob ich zwei Eingänge des Wechselrichters einfach parallel mit dem einen, dann gesplitteten Ausgang des Akkus anfahren könnte? würde das Sinn machen, technisch funktionieren und die zur Verfügung stehende Leistung verdoppeln?

Grüße

**Comment by Ollipop030** [comment]
Ich habe auch einen HM1500, in Ost/West Ausrichtung. Wenn ich testweise die Leistung auf 10 Watt drossle, wird bereits auf der DC Seite gedrosselt. Jedes Modul lässt nur knapp 2,5 Watt durch.

Und Eingänge am WR würde ich nie brücken. Du wirst auch noch ein bisschen mehr Technik brauchen, zB einen Laderegler, Absicherungen usw.

**Comment by trombose009** [comment]
Ah OK, danke für die Info!

**Comment by dedegt** [comment]
Hallo trombose009,
ich hatte auch mit einem HM600 getestet. Gleiches Thema. Das eingestellte Limit wirkt global und wird verteilt auf die Kanäle. Genau wie Ollipop30 schreibt mit den 2,5W je 4 Eingänge ergeben die eingestellten 10W.
Ich habe mich auch dagegen entschieden die Eingänge parallel zu schalten an meine 24V LiFePo4. Konnte im Netz nichts finden dazu. Habe den HM600 daher gegen einen günstigeren HM400 getauscht.
Man kann ja auch den freien Eingang nicht unlimitiert mit Platte nutzen, bzw. wenn limitiert einen Eingang priorisieren oder auswählen. Schalten DC-seitig möchte ich wegen der Kondensatoren im WR nicht.

**Comment by trombose009** [comment]
"den freien Eingang nicht unlimitiert mit Platte nutzen"
das hab ich nicht verstanden. 
aber grundsätzlich würde es mir auch reichen, wenn ich nur einen der 4 Eingänge nutzen kann, da ich nachts lediglich so 300-400 Watt maximal benötige. Diese sollen ja lediglich abgedeckt werden. 

Irgendwo an anderer Stelle im Netz habe ich jedoch gelesen, dass es technisch für den Wechselrichter egal und nicht erkennbar sei, ob ich zwei Eingänge parallel nutze. Vielleicht finde ich ja noch mehr dazu raus.

**Comment by dedegt** [comment]
Ich meinte damit den Akku permanent dran und tagsüber runterregeln und den anderen Eingang mit PV ohne Limit zu nutzen. So nach dem Motto Verbrauch 400W, PV schluckt 300W und den Rest 100W aus Akku. Dachte vor dem Kauf man könnte die Eingänge einzeln limitieren.
Ich werde den HM400 jetzt aktiv regeln über fhem/mqtt um aktuellen Verbrauch zu reduzieren. Dafür nehme ich jetzt aber nur den HM400. Läuft super. PV lädt direkt in Akku. Weitere PV-Platten dann bei Bedarf an weiteren WR anschließen. 
Aber ich hätte auch vermutet, dass es gehen sollte die parallel zu nutzen, aber wollte den Test nicht riskieren. Wenn du dich da rantraust oder neue Erkenntnisse im Netz findest wäre das sehr interessant. Wobei ich aktuell eher zu 2. WR tendieren würde, sehe aber keinen großen Mehrwert, da ich nicht wirklich über 300W geregelt aus Akku ziehen muss, habe einfach nicht lange genug konstant so hohe Verbräuche im Haus.

**Comment by stefan123t** [comment]
Schaut mal in #ess-speichersystem im Discord dort hat homeautomation ein paar Bilder vom Innenleben gepinnt und erklärt auch das mit den zwei / vier Kanälen recht anschaulich.
