### ISSUE TITLE
Feature Request: Google Chart z.B. für 24h Power wie es in Tasmota Scripten möglich ist

### ISSUE THREAD

**Issue by Sinned42** [lumapu/ahoy#627]
Ich habe einen Vorschlag, wie der Live-View sehr aufgewertet werden und ohne zusätzliche Hardware detaillierte Angaben ausspucken kann. Auf die Idee hat mich die Seite

https://ottelo.jimdofree.com/stromzähler-auslesen/

gebracht. 

Der Code für Google Chart ist recht kompakt...

https://developers.google.com/chart?hl=de

![chart](https://user-images.githubusercontent.com/82511091/214568459-6f363424-cb2d-4291-9a0b-d276c9a22e86.jpg)

Wäre das was?

Viele Grüße,
Sinned

**Comment by stefan123t** [comment]
Siehe auch #185 sowie Auswertungen in Nextcloud mittels SensorLogger https://github.com/alexstocker/sensorlogger/ oder dem aktuell m.W. besser maintainten Code unter https://rello.github.io/analytics/

**Comment by ghost** [comment]
Dafür gibt es doch den Prometheus-Endpunkt um diese Daten auszulesen und zu speichern :) 
Kannst einfach den prometheus-release compilieren und bekommst dann einen `/metrics` Endpunkt den du mit besagtem tool auslesen und die Daten speichern kannst. 
(https://prometheus.io/docs/prometheus/latest/installation/) 
Oben drauf könntest du dir dann zur schönen Visualisierung noch Grafana gönnen ;)

**Comment by lumapu** [comment]
wir haben inzwischen seit einigen Versionen ein Diagramm, daher kann ich hier getrost zumachen.
