### ISSUE TITLE
Feature Request: IPS ST7789V möglich ??

### ISSUE THREAD

**Issue by Leonhard67105** [lumapu/ahoy#628]
Ist es möglich ein IPS ST7789V 1.14inch einzufügen in die Bibliothek ??
Dann könnten wir mit einem LILYGO ESP32 T-Display Modul für Arduino Development Board TTGO LCD Wi-Fi BLE CH9102F Chip
platzsparend arbeiten.

Mfg
Jörg

 ## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Modelname: _TTGO ESP32 with ST7789V Display_____
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [ ] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [x] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [x] Windows
* [x] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by stefan123t** [comment]
@Leonhard67105 prinzipiell sollte das Display von der u8g2 Bibliothek die wir aktuell verwenden um die unterschiedlichen Displays anzusteuern unterstützt werden. 
Es sind laut dem folgenden Issue (u8g2) einige Anpassungen an der Bibliohtek notwendig, die der Autor aber nicht commiten konnte. Vielleicht willst Du es ja probieren ?
https://github.com/olikraus/u8g2/issues/763#issuecomment-446771278
NB: Der Code kann nur zwei Farben auf dem Display darstellen (FG/BG) da u8g2 eine monochrome Bibliothek ist.
