### ISSUE TITLE
[ESP8266] Powerlimituebernahme mit MQTT Topic mit Stammbaum ohne Funktion

### ISSUE THREAD

**Issue by Screambear** [lumapu/ahoy#634]
### Platform

ESP8266

### Model name

Wemos D1 mini

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.77

### Github Hash

38a443e

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: Balkonkraftwerk
    - Active Power Limit: 600
    - Active Power Limit Control Type: 600
    - Max Module Power (Wp): 310, 310
    - Module Name: links, rechts
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: IP-Adresse
    - Port: 1883
    - Username (optional): user
    - Password (optional): password
    - Topic: Smarthome/Draussen/PV/hoymiles
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: MAX
#### Serial Console
    - print inverter data: [ ]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Moin,

wenn ich mit dem folgenden Topic: _"Smarthome/Draussen/PV/hoymiles"_ ein Powerlimit per: _"Smarthome/Draussen/PV/hoymiles/ctrl/limit_nonpersistent_absolute/0"_ 
senden möchte wird mir in der Console lediglich 
_"I: MQTT got topic: Smarthome/Draussen/PV/hoymiles/ctrl/limit_nonpersistent_absolute/0"_ 
wiedergegeben und nichts weiter passiert.

Das gleiche auch bei dem Topic: _"PV/hoymiles"_ und dem Befehl _"PV/hoymiles/ctrl/limit_nonpersistent_absolute/0"_
Consolenausgabe ist dann: _"I: MQTT got topic: PV/hoymiles/ctrl/limit_nonpersistent_absolute/0"_

ändere ich aber den Topic auf _"hoymiles"_ also das ganze ohne ein Stammbaum funktioniert das ganze ohne Probleme.

Könnte es an dem "/" liegen? Wird das beim empfangen ggf. nicht richtig verarbeitet!?

Daten von der DTU zu meinen Broker funktioniert in allen fällen korrekt.

**Comment by lumapu** [comment]
mir ist aufgefallen, dass der Ahoy eher zu viel abonniert, auch topics die nicht nur dem konfigurierten beginnen, habe noch nicht verstanden woher das kommt

**Comment by Screambear** [comment]
Das kann ich so jetzt nicht bestätigen. Hatte die letzten zwei Tage viel rumprobiert und ahoy hat mir in der serielconsole immer nur etwas ausgegeben wenn ich auch in dem, wie in dem Manual beschriebenen, Ctrl verzeichnis etwas published habe.

**Comment by Screambear** [comment]
Habe es eben auch mit "%2F" statt dem "/" probiert. ohne Erfolg. 
Dann macht er ein gesamten Topic auf ohne denn Stammbaum dahinter.

**Comment by Screambear** [comment]
@lumapu Moin, gibt es hierzu schon Neuigkeiten? Wird daran gearbeitet? Habe es gestern in der Version 0.5.85 getestet, ohne Erfolg.

Danke für deine/eure Mühen!

**Comment by lumapu** [comment]
schon seit Ewigkeiten gefixt - ich mach hier zu
