### ISSUE TITLE
Setting Problem

### ISSUE THREAD

**Issue by uhighwood** [lumapu/ahoy#647]
Wenn ich auf der Ahoy Maske mein Daten eintrage werden die nicht abgespeichert. meine Version der Ahoy DTU: [AhoyDTU © 2022]
[Git SHA: f8fe044 :: 0.5.66]Board: ESP8266 [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/de) Hast du einen TIP
wo mein Problem liegt?

**Comment by lumapu** [comment]
bitte mal alles aufklappen, vor allem im Bereich `Inverter` und `MQTT`. Dort sind Felder vorhanden, die nicht alle Zeichen erlauben. Wenn man auf speichern klickt, sollte man auf eine andere Seite geleitet werden und kann lesen `successfully saved`
