### ISSUE TITLE
Feature Request: Zuordnung der "Reset" XXX Einstellungen (z.b. mqtt.rstYieldMidNight)

### ISSUE THREAD

**Issue by fsck-block** [lumapu/ahoy#649]
Hallo 
Beim spielen mit den "Reset" Einstellungen ist mir aufgefallen, daß diese MQTT zugeordnet sind.
Aber eigentlich wird der allgemeine Datenbestand dadurch beeinflusst, unabhängig von eine MQTT Konfiguration / Nutzung.

Könnte man vllt die Einstellungen von `mConfig->mqtt.rstXXX` nach `mConfig->rstXXX` verschieben. 
Und im WebGui vielleicht nach "System Config"?
Wäre für mich eine klarere Darstellung

**Comment by lumapu** [comment]
ja das ist ein guter Vorschlag, werde ich umsetzen

**Comment by fsck-block** [comment]
Danke.
