### ISSUE TITLE
choose inverter in setup

### ISSUE THREAD

**Issue by ningyichensha** [lumapu/ahoy#66]
Hello,
I try to use the code for my HM-600 inverter.
I used the SN which is printed on the HM-600
But it does not get any payload data.

My questions:
- I do not use MQTT. Is it mandatory?
- There is no field to choose the type of converter in setup. Is it missing ?
- Do I have to deal with the DTU Radio ID or is the given ID just fine?
- I uncommended #define CHANNEL_HOP in hm_radio. is that enough or are there other places to take care about?

It would be great to get the software working 

regards
Peter

**Comment by lumapu** [comment]
- MQTT isn't mandatory
- the inverter type is identified by its serial number
- the given DTU serial is fine
- I would prefer to turn off channel hop, it does not work to get better results

Most helpful will be the information printed on your serial console. Before that you have to enable NRF24 debug messages via the web GUI.
Check your wiring (is the selected IRQ pin interrupt capable), have you enough power, maybe add a capacitor to your 3.3V

**Comment by ningyichensha** [comment]
Wow, thanks for your help.
Now it's working.

I did reset my modifications and changed the irq to D2

Peter
