### ISSUE TITLE
Feature Request: Rephrase "not producing" message

### ISSUE THREAD

**Issue by Argafal** [lumapu/ahoy#661]
Running 0.5.80. Upon start the inverter status changes to

`Inverter #1: Central (v10016) is available and is not producing`

This is not correct, the inverter is producing. 

How about "... is available, recent production data has not been received"?

**Comment by lumapu** [comment]
this is the sight from Ahoy. If it has not received any data it does not know if the inverter is producing. Normaly Ahoy runs all the time and starts receiving data before the inverter boots.

**Comment by Argafal** [comment]
Right, I agree. However, it does not say that it "does not know if the inverter is producing". It says it knows what the inverter is doing and that it isn't producing. ;) Hence my suggestion to rephrase it.

**Comment by lumapu** [comment]
I found a quick solution how to solve this feature-request. Will be included in next commit

**Comment by Argafal** [comment]
![Screenshot 2023-02-08 at 17-47-34 Index](https://user-images.githubusercontent.com/715254/217596417-78843f44-76b8-4eee-8f2a-666cdb7e8cf1.png)

Sweet, now there is actually a distinction between "no data (yet)" and "inverter actively answered that it is not producing"? That is fabulous, well done <3
