### ISSUE TITLE
Webseite: Hinweis für NRF24L01+ PA LNA SMA mit Antenne

### ISSUE THREAD

**Issue by gzi01** [lumapu/ahoy#669]
Es ist offenbar unbedingt notwendig, dass ein Kondensator zwischen die Pins 3,3V (Plus-Seite des Kondensators) und GND angelötet wird, wenn man AHOY mit dem NRF24L01+ PA LNA SMA mit Antenne betreiben will. 

Auch mit 100uF Kondensator funktioniert die Einstellung auf hohe Sendeleistung bei mir nicht. Bei niedriger Sendeleistung funktioniert AHOY aber perfekt!

Darauf sollte auf der Webseite und in der Doku hingewiesen werden.

**Comment by ghost** [comment]
Hi, I am not an expert,
- What I do know is NRF24L01 + is working in the same freq band as your Wifi (!)
- tried differend  NRF24L01 +
- tried differend power supplies
- Now : USB power supplie 2000 mah, 10  uF Elco, and an NRF better module  (max power no problem but low = sufficient)
![nRF24L01 + PA +LNA RF](https://user-images.githubusercontent.com/119303596/218746595-e7baada0-dbf3-4587-9b3c-443a1971911c.JPG)
Hope this was helpfull
kind regards 
Herman

**Comment by lumapu** [comment]
Option für PA LNA SMA mit Antenne ist auf https://ahoydtu.de
