### ISSUE TITLE
Version 0.4.17 MQTT topic

### ISSUE THREAD

**Issue by sude22** [lumapu/ahoy#67]
@lumapu  Danke für die neue Version!
In Bezug auf [hier](https://github.com/grindylow/ahoy/issues/53#issuecomment-1151623400) erst mal ein dickes Lob. 
Mein Setup mit jetzt 4 HM-1500 empfängt die Daten sehr sauber. Fast bei jedem Durchlauf wird eine Payload erkannt. Top.
Damit ist diese Version definitiv für den Multi-Inverter Einsatz geeignet ;)

Eine Kleinigkeit ist mir aufgefallen:
app.cpp Zeile 134 snprintf(mqttTopic, MQTT_TOPIC_LEN, "inverter");
Das setzt das MQTT Topic fest auf "inverter", ohne die Zeile funktioniert es wie gehabt.

[EDIT] Ich habe mal versucht dafür einen PullRequest zu erstellen. Eigentlich um mal zu testen ob ich das hinbekomme...

**Comment by lumapu** [comment]
Sehr schön, das freut mich. Ich habe bei mir einfach einen zweiten Inverter 'erfunden' und eingetragen. Das Ergebnis deckt sich mit deinem Test: 614 fail stehen 613 success gegenüber.
Also trotz falschem / nicht vorhandenem Inverter wird der andere fehlerfrei abgefragt.

**Comment by DanielR92** [comment]
Moin zusammen,
der [pull](https://github.com/grindylow/ahoy/pull/69) request wie ich sehe hat geklappt.
Könnte einer von euch das issue hier bitte dann closen? :)
