### ISSUE TITLE
No downloadable release available for 0.5.66

### ISSUE THREAD

**Issue by jcmp22** [lumapu/ahoy#670]
Hi, I would like to upgrade to the leatest stable release 0.5.66. But I can only download binary artefacts for the development releases. Seems as there is an issue on the github page? 

[https://github.com/lumapu/ahoy/actions/runs/3809334742](url)

(My goal is to update ahoy dtu via the upload option in the web interface. I'm on release 0.5.28. It is from time to time not available. So I was wondering if an update will help)
![grafik](https://user-images.githubusercontent.com/124533286/217638962-bfe3bec9-a76a-4d06-8167-0c510860a9aa.png)

**Comment by MrLee99** [comment]
This?
https://github.com/lumapu/ahoy/releases

**Comment by jcmp22** [comment]
Thanks a lot. I got almost crazy searching for this. I only found the zip file with the development structure and without binaries
