### ISSUE TITLE
Feature Request: Live - Limitanzeige in Watt?

### ISSUE THREAD

**Issue by Screambear** [lumapu/ahoy#673]
Hallo,

ist es möglich die Limitanzeige in der Live Übersicht auch in Watt anzeigen zu lassen?

**Comment by Ollipop030** [comment]
Das würde ich mir auch wünschen.

**Comment by Webranger2** [comment]
wäre nice

**Comment by ntfrnd** [comment]
Schön dass außer mir auch noch andere dies begrüßen würden.
Ich hatte dazu vor einem halben Jahr schon einmal ein issue aufgemacht: https://github.com/lumapu/ahoy/issues/201

Und ja, bei OpenDTU funktioniert das klasse. Sowohl auf der Webansicht als auch über MQTT gibt es das Limit in % und W.
