### ISSUE TITLE
ESP32 (30 Pin) ab 0.5.85 hängt in Rebootschleife

### ISSUE THREAD

**Issue by Ollipop030** [lumapu/ahoy#674]
Mein ESP32 hängt nach Flash auf 0.5.85 in ein Rebootschleife, das Webinterface ist sehr träge in der Zeit wie er erreichbar ist. Ich komme von der 0.5.83, diese lief jetzt knapp 72 Stunden durchgehend ohne Probleme.

Hat das noch jmd?

**Comment by knickohr** [comment]
Kann ich nicht bestätigen, habe heute auch die 85 drauf gehabt, lief flüssig. Bin aber wegen eines anderen Problems eben wieder zurück auf die 78.

**Comment by Ollipop030** [comment]
Keine Chance: Clean ESP32. 0.5.66 stable installiert, dann auf 0.5.85 aktualisiert. Ein paar Netzwerkeinstellungen gemacht und der ESP startet neu, Webinterface ist sehr langsam, Uptime kommt nur über ein paar Sekunden und staret wieder bei 0. Über das Webinterface dann die 0.5.83 installiert (ein bisschen tricky weil der ESP immer wieder neu startet). Läuft auf Anhieb ohne Neustarts und das Webinterface ist auch viel schneller.

**Comment by lumapu** [comment]
ok, ich hatte dieses Verhalten durch meine Neuerung die Werte der Wechselrichter sofort nach erfolgreichem NTP sync anzufragen.
Für die veröffentlichte Version habe ich dann eine Verzögerung von 3 Sekunden eingebaut was bei mir das Problem gelöst hat.
Danke fürs Feedback, dann deaktiviere ich es, bis ich verstehe warum er in meinen Fall sofort neu startet wenn ich die 3 Sekunden weglasse

**Comment by lumapu** [comment]
0.5.86 sollte das nicht mehr machen, biite um Feedback

**Comment by Ollipop030** [comment]
Danke für die schnelle Hilfe, jedoch verhält sich die 86 genau so.

Nachtrag:
Scheint nur den ESP32 (übrigens 30 PIN) zu betreffen. Hier läuft ab der 0.5.85 wie beschrieben das Ding nicht mehr rund. Auf einem 8266 habe ich gerade die 0.5.86 installiert, die läuft super.
Die 0.5.84 habe ich gar nicht getestet, man kommt hier bei dem Releasetempo kaum hinterher. 😄

**Comment by knickohr** [comment]
Ahhh jetzt. Ich wundere mich schon warum mein ESP32 das nicht macht (das Booten). Der läuft stabil und hat auch kein Watchdog-Problem. Es ist ein ESP32 DevKit C (keine V4 !) von AZ mit 38 Pins.

**Comment by Ollipop030** [comment]
Ja hätte ich vielleicht direkt dazuschreiben sollen, sorry. Die 38 Pin Varinate war damals leider nicht lieferbar, deshalb habe ich mir die "kleinere" Variante geholt. Bisher gab es auch absolut keine Probleme, die Boards laufen tagelang ohne einen Neustart.

**Comment by teletapi** [comment]
> Ahhh jetzt. Ich wundere mich schon warum mein ESP32 das nicht macht (das Booten). Der läuft stabil und hat auch kein Watchdog-Problem. Es ist ein ESP32 DevKit C (keine V4 !) von AZ mit 38 Pins.

Ich nutze den Vemos ESP32 D1 Mini der hat bisher auch keinerlei Probleme diesbzüglich angezeigt

**Comment by Ollipop030** [comment]
@lumapu 
Was meinst du, ist das zu fixen oder soll ich lieber auf ein 38 Pin Board umsteigen? So teuer sind die ja nicht. Evtl. kommen sonst ja noch andere Probleme in Zukunft auf mich zu.

**Comment by lumapu** [comment]
ich weiß bisher nicht was der Unterschied ist. Wenn es wirklich nur die Pins sind dann tippe ich eher auf ein Power-Supply Problem. Das kann auch der auf dem Board verbaute Spannungsregler sein.
Könntest du das ausschließen indem du den ESP noch einen Kondensator spendierst

**Comment by Ollipop030** [comment]
Ich habe jetzt noch ein wenig hin und her getestet. Scheinbar macht die DTU nur Neustarts, wenn sie "was zu tun" hat. Sprich wenn sie mit den WR kommunizieren soll. Wenn keine Antenne dran ist, läuft sie stabil. Wenn ein dran ist, aber keine WR eingetragen sind, läuft sie auch. Sobald ich die WR aber eintrage, kommen die Neustarts.
Bei diesem Verhalten würde man auf Hardware tippen, folgendes spricht aber dagegen: Die DTU läuft fehlerfrei mit Version 0.5.83 und darunter. Ich habe mehrere Antennen probiert, mit externer und ohne externer Antenne, aber alle mit Kondensator. Die Antennen selbst habe ich noch an einem 8266 getestet, da laufen sie.
Verschiedene ESP32 30PIN, unterschiedliche Netzteile (eines von meinem PiHole mit 3000mA, der läuft aktuell damit). Sobald eine Version größer 0.5.85 installiert wird laufen die Dinger nicht mehr. 

Es scheint also, dass die Boards ab Version 85 nicht mehr funktionieren. Sind übrigens diese hier: https://www.makershop.de/plattformen/nodemcu/esp32-board-stiftleisten/

**Comment by soelli22** [comment]
Das mit den Reboot unter „Last“ kann ich bestätigen. Sobald auf den WR‘s Aktivität herrscht, läuft nix mehr.

**Comment by lumapu** [comment]
> Es scheint also, dass die Boards ab Version 85 nicht mehr funktionieren. 

Das klingt stark danach, dass die frisch eingebauten MI inverter den Speicher sprengen. Komisch dabei ist aber, dass es sich um einen ESP32 handelt.

**Comment by Ollipop030** [comment]
Heute morgen spaßeshalber mal die 0.5.89 installiert, damit läuft alles wieder. DTU hat mittlerweile 7 Stunden Uptime.

**Comment by lumapu** [comment]
und hoffentlich jetzt schon 12

**Comment by Ollipop030** [comment]
Kann zu, keine Probleme mehr gehabt seit einer Woche.
