### ISSUE TITLE
Fehler in Modul 4 Ahoy 0.5.86

### ISSUE THREAD

**Issue by Karlo49** [lumapu/ahoy#676]
## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ x] external antenna

### Power Stabilization:
* [ x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [ x] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [ x ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ x] Linux
* [ ] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Karlo49** [comment]
Update von 0.5.83 auf 0.5.86 bringt erstaunliche Werte in Modul 4 und in Gesamtleistung.
/home/brkp/Bilder/Ahoy 5.86.png

**Comment by Karlo49** [comment]
![Ahoy 5 86](https://user-images.githubusercontent.com/108924478/218306246-772ca6c7-bc43-4a66-918d-1045deb10f09.png)

**Comment by dtuuser** [comment]
siehe #570

**Comment by lumapu** [comment]
gefixt in `0.5.87`

vorher:
![grafik](https://user-images.githubusercontent.com/22733082/218309206-c1ae27c1-1b91-4296-9a4d-c6ce99af6452.png)

nachher:
![grafik](https://user-images.githubusercontent.com/22733082/218309217-154afaf4-e779-428f-9a69-bb074d4c07c5.png)

Settings:
![grafik](https://user-images.githubusercontent.com/22733082/218309232-c3ec8dc2-0166-4267-9eb6-d0a87b47b58b.png)

**Comment by Karlo49** [comment]
@lumapu  schneller als der Schall
Ist behoben
