### ISSUE TITLE
Limit Verständnis Frage

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#678]
Mal eine Frage zum Limitsetzen über CURL Aufruf.
Ich habe das so verstanden, dass ein über CURL gesetztes Limit erst beim nächsten normal geplanten Datenabruf gesetzt wird. Ist das richtig? 
Oder wird das unabhängig vom geplanten Abrufintervall sofort nach Erhalt an den WR übermittelt? 
Was passiert,  wenn ich innerhalb von wenigen Sekunden zwei Limitwünsche an die AhoyDTU sende?
Danke

**Comment by Ollipop030** [comment]
Das Limit wird sofort gesetzt, sieht man auch in der Console. Bei mir wird über ein Script alle paar Sekunden das Limit Richtung Nulleinspeisung gesetzt, funktioniert wunderbar.

**Comment by dtuuser** [comment]
Danke für super schnelle Antwort.

Mist...dann muss ich mein Tool anpassen. Dachte, dass das über das Intervall läuft.

**Comment by Ollipop030** [comment]
Kannst dir das ja mal ansehen, funktioniert ganz gut:

https://github.com/reserve85/HoymilesZeroExport
