### ISSUE TITLE
0.5.88 Max. Anzahl Inverter? DTU nicht mehr erreichbar.

### ISSUE THREAD

**Issue by MiniOh** [lumapu/ahoy#681]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Hallo, 

gibt es Infos über die max. Anzahl der nutzbaren Inverter?
nachdem ich für mich beschlosssen hatte, dass die Version 0.5.88 für mein Empfinden wieder eine recht gute und einsetzbare Version ist, hatte ich heute versucht die Inverter einzurichten.
8 Stück an der Zahl. Nach dem Save Button war die DTU nicht mehr ereichbar im WLAN.
Auch das neu Flashen per USB war alles andere als einfach, da auch hier erst nach dem ca. 10. Versuch der Verbindungsversuch erfolgreich war.

Hab ihr eine Idee was das sein kann? Kann evtl. nicht genug Speicher allokiert werden, um die Anzahl der Inverter bzw. Module zu speichern?

Danke schon mal und sorry schon mal vorab, dass ich euch täglich heue Arbeit mache. ;-)

**Comment by lumapu** [comment]
ich glaube das habe mit diesen issues zusammen. Der `heap` des ESP ist zu fragmentiert. Ich werde bald eine neue Version veröffentlichen, die in diesem Punkt starke Verbesserungen liefert.

#644
#645
#682

**Comment by Ollipop030** [comment]
@lumapu Könnte das geplante Update auch #674 beheben?

**Comment by lumapu** [comment]
sollte mit aktueller Dev nicht mehr auftreten. Bitte nochmal testen `0.5.96`

**Comment by MiniOh** [comment]
Hallo @lumapu 

Ja, funktioniert jetzt problemlos.
8 Inverter mit allen Panels und deren Leistung und Bezeichnung lassen sich jetzt ohne Fehler anlegen.
