### ISSUE TITLE
0.5.88 "Live" Ansicht bei vielen Invertern "leer"

### ISSUE THREAD

**Issue by MiniOh** [lumapu/ahoy#682]
## Hardware
  * [ ] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Hallo, 

bei 9 Invertern, aber testweise nur einem mit aktiver Kommunikation, ist bei mir die "Live" Ansicht leer.

![AHOY_ Inverter](https://user-images.githubusercontent.com/27901554/219000924-cb2a95cc-e392-47cf-93b2-293c503104aa.JPG)

![AHOY_ Live](https://user-images.githubusercontent.com/27901554/219000964-f518277f-1266-4132-91ec-7c5986db0d47.JPG)

**Comment by MiniOh** [comment]
Hallo, 

es hat sich offenbar wirklich etwas verändert, auch was die Live Anzeige angeht.
Mit der 0.5.89 wird die Live Anzeige nun angezeigt.

Allerdings gibts es noch Unterschiede, "an welcher Stelle" der aktive Inverter in der Liste steht.
In dem Fall, wie oben dargestellt, dass nur der 8. Inverter aktiv ist, werden keine Channel Daten außer der U_DC ausgegeben.
Lässt man aber die gleichen Inverter drin, und setzt den auf Position 3 aktiv, werden dort Daten ausgegeben.

![Channel](https://user-images.githubusercontent.com/27901554/219367829-95727bad-6c64-49e3-9b1e-b7243a21ab4a.PNG)

**Comment by MiniOh** [comment]
@lumapu 
In der 0.5.90 hat sich an der Live Ansicht noch nichts geändert, oder?
Zumindest bei mir wird weiterhin nur die U_DC mit Werten ausgegeben.

**Comment by lumapu** [comment]
ja genau, bin schon dabei das zu verbessern, ist aber nicht nicht veröffentlicht

**Comment by MiniOh** [comment]
Ok. Super. Das klingt gut.
In 5 Wochen soll unsere Anlage in Betrieb gehen, dann ist Ahoy bestimmt auch in nem sehr guten Zustand. 👍

**Comment by MiniOh** [comment]
> ja genau, bin schon dabei das zu verbessern, ist aber nicht nicht veröffentlicht

Hallo, 

die 0.5.92 hat es bei mir aber eher "verschlechtert".
Bei der 0.5.89 war die Live Ansicht grundsätzlich OK, allerdings wurden, wie oben dargestellt, bei den Channels nicht alle Daten angezeigt.

In der 0.5.92 sieht "Live" wie folgt aus:

<img width="557" alt="inverter" src="https://user-images.githubusercontent.com/27901554/221357376-7c025b82-11c7-44c9-9481-1dfbfc9dc921.png">

<img width="872" alt="Total" src="https://user-images.githubusercontent.com/27901554/221357383-27969ff8-f8ac-4134-9a3d-76303f5014ab.png">

**Comment by MiniOh** [comment]
Hattest du in der 0.5.95 etwas angepasst bzgl. der leeren Live Ansicht?

Ich habe nach wie vor 8 Inverter konfiguriert.
Sofern nur die "unteren" mit aktiver Kommunikation definiert sind, ist die Live Ansicht immer noch leer.
Wenn ich Inverter 0 mit dazu "aktiv" nehme, auch wenn dieser noch nicht in Betrieb ist, zeigt die Live Ansicht etwas an.

**Comment by beegee3** [comment]
kann es sein, dass in `visualisation.html` `function parse(obj)` ein Fehler ist?
Da steht
```
                    for(var i = 0; i < obj.iv.length; i++) {
                        if(obj.iv[i])
                            getAjax("/api/inverter/id/" + i, parseIv);
                            break;
                    }
```
Ist `obj.iv` das gleiche wie `ivEn`? Oder sollte es so lauten:
```
                    for(var i = 0; i < ivEn.length; i++) {
                        if(ivEn[i])
                            getAjax("/api/inverter/id/" + i, parseIv);
                            break;
                    }
```

**Comment by lumapu** [comment]
ich denke in der `RestApi.h` wird bereits das `enable` ausgewertet.
Der Hinweis von @MiniOh ist sehr gut, es heißt, dass beim Start der Iteration der Fehler passiert.

**Comment by beegee3** [comment]
> ich denke in der RestApi.h wird bereits das enable ausgewertet.

ähh, nein. Genau dafür ist doch `ivEn`, oder bin ich im falschen Film?
Du rufst mit `getAjax("/api/live", parse)` genau die von mir zitierte `parse` Funktion auf. Die soll doch nach dem ersten enabled Inverter suchen. Das ist die zitierte `for` Schleife. Meine Frage ist, ob `obj.iv` das gleiche ist wie `ivEn`? Ansonsten wäre da wohl der Fehler. Denn dann wird `parseIv` ggfs. nicht aufgerufen (wo eine analoge `for` Schleife mit `ivEn` steht.
Warum beschreibe ich dir, was du programmiert hast? Ich bin echt im falschen Film 🎞️ 😭

**Comment by beegee3** [comment]
hab mir gerade die Frage selbst beantwortet: `obj.iv` ist das gleiche wie `ivEn`.
Ist trotzdem die richtige Fehlerquelle, da fehlen die Klammern für die `if` Anweisung, richtig ist
```
                    for(var i = 0; i < obj.iv.length; i++) {
                        if(obj.iv[i]) {
                            getAjax("/api/inverter/id/" + i, parseIv);
                            break;
                        }
                    }
```
Hab's gerade mit einem virtuellen 2. Inverter erfolgreich getestet!

**Comment by lumapu** [comment]
@beegee3 ich glaube wir waren gleich schnell - der commit ist bereits draußen und ich wollte gerade schreiben, dass die Klammern die Ursache waren 😂. Ich habe ewig diesen issue hier gesucht ...

**Comment by MiniOh** [comment]
Danke ;)
Sieht gut aus.
