### ISSUE TITLE
different Pinlayout esp-wroom-32

### ISSUE THREAD

**Issue by uwe98** [lumapu/ahoy#683]
Hello, i am irritated with the pinlayout (different to grafics)
![image](https://user-images.githubusercontent.com/125487561/219090459-9a85287f-c57e-4508-8a5b-6e66b9ecf699.png)
backside: NodeMCU-ESP32   ESP32 DEVKITV1

Please, can someone help me.

Sorry wrong picture, Pins are here:

vin gnd D13 D12 D14 D27 D26 D25 D33 D32 D35 D34 VN VP EN

3v3  gnd  D15  D2  D4  ax2  tx2  D5  D18  D19  D21 ax0 tx0 D22 D23

**Comment by mroenne2022** [comment]
Hallo Uwe:

Ich habe 2 Ahoys mit jeweils ESP-WROOM-32  mit jeweils 30PIN (gibt Unterschiede zu 38PIN !!!)
wie folgt zum laufen bekommen!
Den Tip hab ich hier vor einiger Zeit bekommen.
Es geht immer um die GPIO's , ich musste nur den IRQ ändern,
im Setup und Verkabelung auf GPIO 01 , damit läuft es.
Einstellung im Ahoy-Setup

CS - D1 (GPIO5)
CE - D2 (GPIO4)
IRQ - TX (GPIO1)

Auf dem ESP und dem NRF sieht es wie folgt aus:

Farbe 	ESP32 	nRF24L01+
Schwarz  GND 	Pin 1
Rot 	     +3.3V 	Pin 2
Blau 	D4 	        Pin 3
Lila 	        D5 	        Pin 4
Braun 	D18 	Pin 5
Gelb 	D23 	Pin 6
Orange 	D19 	Pin 7
Grün 	TX0 	Pin 8

Anbei eine Übersicht : 
![esp32_30Pin](https://user-images.githubusercontent.com/114778920/219122931-6ebb8c83-3433-4937-b6c8-45fd7161555f.png)

**Comment by marco050969** [comment]
Hi,

hättest du ein komplettes Foto oder Pinoutbeschreibung vom esp32 mit 30 Pin und von der Antenne oder einen Anschlussplan bitte.
Ich verzweifele gerade und werde nicht schlau draus.

Grüße

Marco

**Comment by mroenne2022** [comment]
Moin Marco,  ich kann dir was aus meiner eigenen Doku anbieten, musst mal gucken ob du das damit hinbekommst, sollte aber möglich sein.
![20230418_222534](https://user-images.githubusercontent.com/114778920/235446250-1098d1ff-251c-4405-a7bf-e9a8899bb22e.jpg)
![20230218_124207](https://user-images.githubusercontent.com/114778920/235446262-187b8068-231c-4df6-b0c4-beff3693df4a.jpg)
