### ISSUE TITLE
0.5.89 Upload Settings Button ohne Funktion

### ISSUE THREAD

**Issue by MiniOh** [lumapu/ahoy#686]
## Hardware
  * [x] ESP8266
  * [x] ESP32
  * [ ] Raspberry Pi

Hallo, 

seit einiger Zeit funktioniert der Restore über den Upload des JSON Files nicht mehr.
Man kann die Datei auswählen, aber der "UPLOAD" Button scheint keine Funktion zu haben.

![Ahoy Settings](https://user-images.githubusercontent.com/27901554/219565956-6ca0bf55-669e-4548-a8ce-1d78de28bed0.PNG)

**Comment by knickohr** [comment]
Kann ich bestätigen, ist seit mindestens der 87 so.
