### ISSUE TITLE
Version 0.5.66 MQTT logout

### ISSUE THREAD

**Issue by KLM30330** [lumapu/ahoy#702]
## Hardware
  * [x] ESP32

Modelname: ESP-WROOM-32

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [x] external antenna

### Power Stabilization:
None

### Connection diagram I used:
| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  **D16**  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [x] AhoyDTU

### Version / Git SHA: 
Version: 0.5.66

### Build & Flash Method:
* [x] ESP Tools

### Desktop OS:
* [x] Windows

### Debugging:
* [x] Setup settings (use our templates ... to be added)

## Problem
Hi,
I use AhoyDTU with home assistant and since about one month I lost MQTT connection.
I have this message in serial control :

`06:30:24 I: MQTT disconnected, reason: TCP disconnect`

Is there a solution ?

Thanks in advance

**Comment by Argafal** [comment]
I have seen this with 0.5.66, too. I have not seen it occur in the latest development version yet. So it might no longer be an issue once the next release comes out.

**Comment by KLM30330** [comment]
Hi, witch development version do you used and how did you installed it?

**Comment by beegee3** [comment]
you find a zip file with the latest Development Build on https://ahoydtu.de/web_install/
Please download and unzip it then use the AHOY update web surface (if you didn't change the setting it's http://ahoy-dtu/update), select the right bin file (depending on your ESP it ends with _esp8266.bin or _esp32.bin) klick on UPDATE and see what happens (message should be: update started -> Update: success  rebooting ... auto reload after 20s) -> dev. version -> 😃

**Comment by Argafal** [comment]
I used 0.5.89 and I really liked it. If you try it you'll probably encounter known bug #660. But that one is easily fixed with an occasional reboot.

 @beegee3 answered how to install development versions, thanks to them! :)

**Comment by lumapu** [comment]
@KLM30330 do you have an update for us?

**Comment by KLM30330** [comment]
Hello, I have installed 0.5.89 Today (thanks to @beegee3) and this version seems working better than 0.5.66.
