### ISSUE TITLE
Which .bin file I have to use.

### ISSUE THREAD

**Issue by OsteraT** [lumapu/ahoy#703]
Hello,

I have a question regarding the bin files.
I have a D1 ESP8266 Mini and a NRF24L01+.

I would like to use the standard firmware.

But inside the download folder there are multiple files for ESP8266
221230_ahoy_0.5.66_esp8266_ssd1306_f8fe044.bin
221230_ahoy_0.5.66_esp8266_nokia5110_f8fe044.bin
221230_ahoy_0.5.66_esp8266_f8fe044.bin

Wich one I have to use? I could not find any answer.

Sorry for the "stupid" question/issue.

**Comment by Ollipop030** [comment]
The last one, 221230_ahoy_0.5.66_esp8266_f8fe044.bin. ssd1306 and nokia5110 are binaries for DTU´s with display.

**Comment by OsteraT** [comment]
Ok, Thank you for the quick response. But where can I find these Informations?
And what about the other binaries like ota.bin?

**Comment by beegee3** [comment]
the easiest way to install Ahoy is to use the web installer:
connect your ESP to one of your PC USB ports, then open https://ahoydtu.de/web_install/ and click on CONNECT.
A window will open wher you have to select the right COM port, click on connect and follow the instructions.

**Comment by OsteraT** [comment]
I tried this already. But the webiste is telling me that the com port is already in use. 
I flashed the ESP with vscode+platformio and with esptool.py
The flash process was successful but the ESP(s) does not work. 
I will try another serial/usb driver.

**Comment by OsteraT** [comment]
After using another driver I was able to upload the firmware to the ESP8266.
But the device does not open the wlan access point.
Thats the output of the console window:
(What about the message "W: failed to load json, using default config"?)
```
wdt reset
load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v0007a480
~ld
I: Initializing FS ..
I:  .. done
W: failed to load json, using default config
I: Settings valid: false
I: RF24 Amp Pwr: RF24_PA_I: LOW
I: Radio Config:
SPI Frequency		= 1 Mhz
Channel			= 3 (~ 2403 MHz)
Model			= nRF24L01+
RF Data Rate		= 250 KBPS
RF Power Amplifier	= PA_LOW
RF Low Noise Amplifier	= Enabled
CRC Length		= 16 bits
Address Length		= 5 bytes
Static Payload Length	= 32 bytes
Auto Retry Delay	= 250 microseconds
Auto Retry Attempts	= 0 maximum
Packets lost on
    current channel	= 0
Retry attempts made for
    last transmission	= 0
Multicast		= Disabled
Custom ACK Payload	= Disabled
Dynamic Payloads	= Enabled
Auto Acknowledgment	= Disabled
Primary Mode		= RX
TX address		= 0xe7e7e7e7e7
pipe 0 (closed) bound	= 0xe7e7e7e7e7
pipe 1 ( open ) bound	= 0x3624258701
pipe 2 (closed) bound	= 0xc3
pipe 3 (closed) bound	= 0xc4
pipe 4 (closed) bound	= 0xc5
pipe 5 (closed) bound	= 0xc6

---------
AhoyDTU Info:
Version: 0.5.66
Github Hash: 0000000

---------
AP MODE
SSID: AHOY-DTU
PWD: esp_8266
IP Address: http://192.168.4.1
---------
```

**Comment by beegee3** [comment]
> W: failed to load json, using default config

on the very first start of Ahoy there is no (json) setting file. First you have enter all your the settings. Then press the SAVE button so that the settings are saved and the ESP restarts.
If there is no error in your settings ESP will connect to your wlan access point (name and password in Settings - Network) and try to get data from your inverter(s).
If the warning W:... reappears something is wrong in your settings.

**Comment by OsteraT** [comment]
OK, thank you for the information.
Why does it takes so long that the esp establish the wlan/access point?
I connect the esp to the power supply and after that I have to wait several minuts to see the new wlan (sometime it will never appear).

**Comment by lumapu** [comment]
Ahoy tries to connect to your strongest AP. For me it lasts only 30s to connect with a very weak connection (-82dBm).

**Comment by OsteraT** [comment]
First the ahoy should open the „ahoy dtu“ access point. This does not happend.
Could ist be that the wemos is doing a reboot all the time(every 3 seconds).

**Comment by OsteraT** [comment]
Now its working. I added a capacitor to the board. After that, the access point was stable.
In the beginning, the HM1500 was not connected. I changed the pin-setup (CE to RX and IRQ to TX).

Thank you for the help.
