### ISSUE TITLE
SD1306 OLED mit ESP32 - Schaltbild

### ISSUE THREAD

**Issue by Parodontitis** [lumapu/ahoy#707]
## Hardware
  * [X] ESP32

Wo finde ich den Schaltplan um ein SSD1306 OLED an ESP32 anzuschließen? Mir ist klar, dass ich mir die Freien GPIOs auswählen kann, allerdings würde ich gerne die nutzen, die in den standard-Images bereits eincompiliert sind. Danke.

**Comment by knickohr** [comment]
Gibt es noch keinen da es alles noch DEV ist. Wenn Du auf Nummer Sicher gehen willst, nutze die Standardmäßigen Hardware-I2C Pins, also SDA (GPIO21) und SCL (GPIO22) vom ESP32.

**Comment by Parodontitis** [comment]
Danke
