### ISSUE TITLE
feature request: changing AP password or name 

### ISSUE THREAD

**Issue by TobiScience** [lumapu/ahoy#708]
## Hardware
  *  ESP8266

Hello,
when AhoyDTU loose the connection to the wifi, it goes into AP mode, but I see no settings to change the AP name or the AP password. So if the DTU goes into AP mode it's easy for others to log in.

I think it would be great to disable AP mode or make it possible to change the default password.

thanks for the great work :)

regards

**Comment by gwse** [comment]
Hi, I would vote for this issue (but did not find the vote button :)
It is very security relevant if everybody is able to connect to Ahoy wifi AP with default password which cannot be changed. API is not secured so it is easy to manipulate converter for everybody.
Best regards an I love this great work
Florian

**Comment by lumapu** [comment]
ok noted.

**Comment by lumapu** [comment]
is included in the latest development builds
