### ISSUE TITLE
5.91 kein Inverter bei Serial/Control Auswahl

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#709]
Guten Morgen zusammen,
habe gerade die  5.91 installiert. WR läuft und produziert, wird aber unter Serial/Control (Select Inverter) zum Limit setzen nicht angezeigt

**Comment by Ollipop030** [comment]
Live, Settings, System ist auch ausgeblendet.

**Comment by lumapu** [comment]
ja das Menü kommt mobil nicht, mache heute einen hotfix

**Comment by dtuuser** [comment]
Ist wieder da. 
Vielen Dank für die super schnelle Rückmeldung

**Comment by Ollipop030** [comment]
Am Rechner mit 0.5.92 kommt das Menü aber nicht. Firefox und Edge getestet.

**Comment by dtuuser** [comment]
Bei mir auch nur in Chrome. Das ist bei mir aber schon lange so

**Comment by knickohr** [comment]
Das hatten wir doch schon mal 😲 Wurde bei mir als „zu alten“ Webbrowser abgetan 😉

**Comment by Ollipop030** [comment]
Naja, Firefox ist 110, aktueller geht es nicht. Aber runter auf die 0.5.90, und Menü ist wieder da.

**Comment by dtuuser** [comment]
Bei mir blockte die Firewall bzw. der Javafilter

**Comment by knickohr** [comment]
Dann mach zu das Ding 😉

**Comment by Ollipop030** [comment]
> Dann mach zu das Ding

Warum? Fehler ist noch vorhanden. Firefox ohne Addons, Edge und Firefox auf dem Handy, überall das gleiche Bild:

![grafik](https://user-images.githubusercontent.com/121013633/221369967-98f298b9-4b0b-493a-b1e3-3099b90f23e9.png)

Ich glaube, es liegt daran:

![grafik](https://user-images.githubusercontent.com/121013633/221371309-eb414756-dadd-4174-94b4-e5b6a362d5b7.png)


Die Haken kann ich deaktivieren, sind aber nach dem Neustart wieder vorhanden. Evtl. funktionieren die Switches einfach nicht?


Edit: Die Haken sind selbst nach dem Löschen der Settings noch aktiv.

Edit 2: Nach dem Löschen des Passwortes sind alle Menüeinträge wieder da, aber die Haken sind weiterhin nach dem Neustart immer wieder aktiviert.

**Comment by knickohr** [comment]
Ah OK, dachte das wäre mit der Firewall behoben. War wohl nur bei @dtuuser  so 😉

**Comment by lumapu** [comment]
ok, die Haken haben einen Haken 😂, man müsste halt alles testen bevor man committed, bin da leider immer etwas schnell ...

**Comment by MiniOh** [comment]
Ich musste auch auf die, für mich sehr stabile 0.5.89 zurück.
Wann gibts die 93?

**Comment by lumapu** [comment]
noch nicht, dauert aber bestimmt nicht mehr lange 😉

**Comment by 0xevolix** [comment]
keine eile funktioniert auch mit schönheitsfehler im menü =) 
man kann die gewünschten seiten ja auch direkt per url aufrufen.

was allerdings cool wäre, wenn passwortabfrage genutzt wird und eine selektion für geschützte seiten wie im bild oben festgelegt wurde, er automatisch im ausgeloggten zustand auf die jeweils offene seite defaulted. also im bild oben is ja /live offen. Quasi beim zugriff auf http://ip direkt auf /live defaulten anstelle der gesperrten /index seite.

**Comment by lumapu** [comment]
Der Issue #699 hat das selbe Fehlerbild. Der Fehler wurde bereits behoben, dieser Kommentar dient nur der Dokumentation
