### ISSUE TITLE
AhoyDtu enable prometheus endpoint without manual compile

### ISSUE THREAD

**Issue by moritz31** [lumapu/ahoy#719]
Hey, 

bin mir nicht sicher ob ich es vielleicht aktuell einfach nicht gefunden habe. Es gibt ja den Flag ENABLE_PROMETHEUS_EP
um einen Prometheus Endpunkt zu erstellen. Aktuell funktioniert das ganze nur über ein selbstkompiliertes Abbild und nicht über den Webinstaller oder eventuell sogar über die oberfläche ? 

Gruß

**Comment by lumapu** [comment]
richtig, die Nachfrage ist hier nicht sonderlich groß. Ich kann gerne ein automatischen build hinzufügen.

**Comment by fsck-block** [comment]
Super, es gibt doch noch jemand der auch Prometheus benutzt :thumbsup:
Dachte schon in bin der einzige.
