### ISSUE TITLE
[AHOY DEV 0.5.92] MQTT - Reset values midnight and inverter polling stops at sunset unsightly effect

### ISSUE THREAD

**Issue by Huschtegutsel** [lumapu/ahoy#722]
Eines gleich vorweg - super Arbeit vom gesamten Team. Absolut grandios, was ihr hier auf die Beine gestellt habt und die schnelle Weiterentwicklung, wie auch Fehlerbehebung... Hut ab

Ich habe inzwischen die 0.5.92 (ESP32+NRF+Display) stabil mit HM-800 & 2 Pannels am laufen - es gibt bisher nur zwei Dinge, die mir aufgefallen sind.

Die WeIf-Menüprobleme habe ich nicht, von denen einige berichten - vielleicht durch die fortlaufenden Updates von 0.5.66 auf 0.5.89 bis 0.5.92 - weder im Firefox, Chrome und Edge. iOS ist auch alles da... #720

Unter INVERTER habe ich "Reset values and YieldDay at midnight" aktiviert und die Option "Reset values when inverter polling stops at sunset". Im Menüpunkt "MQTT" den Interval auf "0" - damit nur erhaltene Daten vom Inverter gesendet werden und nicht zyklisch z.B. alle 20 Sekunden geschickt wird. Scheinbar beißt sich das mit der INVERTER-Einstellung. Zur Analyse sind MQTT-Broker und MQTT-Explorer dauerhaft verbunden geblieben.

1. Bei Sunset (18:17:01 Uhr):
In der WeIf-Live-Ansicht werden alle Werte auf 0 gesetzt - bis auf "YieldDay" - der bleibt bestehen, was absolut okay ist - der soll ja erst um Mitternacht genullt werden. Ebenso wurden auch die zuletzt empfangen Werte vom WR per MQTT übertragen. Am Broker, auf den ich den MQTT-Explorer mitlaufen habe lassen, sind immer noch die letzten Werte vom WR vor der Abschaltung vorhanden und werden nicht auf "0" gesetzt (klar, die meisten Werte sind retained). Auf der angeschalteten Visualisierung "EisBär" per MQTT-Client stehen somit immer noch die letzten Werte an, obwohl nichts mehr per MQTT ankommt - etwas unschön ;-) 

Perfekt wäre, wenn der Sunset-Reset aktiviert wurde und MQTT aktiv ist, dass auch hier die Nullwerte, wenn die Live-Ansicht aktualisiert wird, geschickt werden - vielleicht am Besten als Option, wenn andere das nicht so haben wollen. Da viele Werte retained sind, wäre das, wie ich finde, eine gute und saubere Lösung.

2. Bei Midnight:
Gilt eigentlich das Gleiche in Verbindung mit aktiviertem MQTT-Client wie bei Sunset. Evtl. auch hier eine Option einfügen?

**Comment by lumapu** [comment]
schon lange repariert aus meiner Sicht.
