### ISSUE TITLE
[AHOY DEV 0.5.92] Unexpected MQTT values (drops & spikes)

### ISSUE THREAD

**Issue by nexulm** [lumapu/ahoy#725]
Hello,

does anyone already observed some irregular values received via MQTT. I'm currently confused about some drops or spikes I see in my graphs over the day and more strange during the night as well. Please have a look on two screenshots of the same graph time duration from today. "Yield Day" is for me one of the most important values I'm monitoring of my HM1500 inverter. 
The configuration is: Reset values and YieldDay at midnight. Everything else is NOT set.
If I'll not find the source I've more effort in improving my filters to eliminate this behavior.

Would be nice if there is a solution or switch already available I'm not aware of. :-)

<img width="977" alt="image" src="https://user-images.githubusercontent.com/5346351/221944225-3044b365-c5f6-418f-8d36-6f510e2e585b.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/5346351/221945113-787a0ca1-f471-436b-82cb-a63de788e393.png">

**Comment by Argafal** [comment]
Mir fällt auf dass alle deine drops im ersten Bild immer zum gleichen Wert (ca 800) gehen. Ich hatte kürzlich ähnliches drops (selten und unregelmässig, genau wie du) mit einem Wasserzähler. Da war die Ursache eine alte Nachricht mit einem vorherigen Wert, die auf "retained" stand. Diese wurde zwischendurch immer wieder gelesen. Ich habe dann alte retained Nachrichten gelöscht. Das hatte für mich das Problem gelöst. Vielleicht ist die Ursache ja hier ähnlich?

**Comment by beegee3** [comment]
it seems that the drops and spikes occur where for some reason the connection to MQTT got lost. My guess: between 3:30 and 7:30 your WLAN is disabled. But I have no explanation why the Yield Day value is set to 750Wh. Looks like this is the Yield Day value from before midnight. Ahoy does not use any history. There is only one Yield Day value in memory. In your case this value is set to 0 at midnight. No possibility for Ahoy to get back the value from before midnight. And, if I'm right and the MQTT connection got lost, Ahoy can't send anything to MQTT.

@Argafal you're too fast 😄 I was thinking about a similar explanation too!

@lumapu Hinweis am Rande: in dem Zusammenhang ist mir aufgefallen, dass in `app::tickZeroValues` und `app::tickMidnight` die Zeile `if (!iv->config->enabled) continue; // skip to next inverter` fehlt. Füge sie doch bitte bei Gelegenheit ein.

**Comment by knickohr** [comment]
Diese „Drops“ beobachte ich seit ein paar Versionen auch bei mir. Ist immer nur ein Inverter, so das man wohl Abschattungen ausschließen kann. Es ist aber nicht immer der gleiche Inverter. Da es ja vorher nicht auftrat tippe ich darauf das per MQTT irgendetwas falsches oder unvollkommenes ausgegeben wird.

![0D9A0448-7F3B-47AA-BBA1-4987AE2D97E4](https://user-images.githubusercontent.com/63048210/222145097-80a71e76-da75-4b1c-ba80-2a4c2309c458.jpeg)

Ich beobachte das aber nicht bei den Yield, sondern bei der Momentanleistung P_AC.

**Comment by Argafal** [comment]
Ich hab keine Drops mit 0.5.92. Ich hab das HA Auto-discovery auch nie benutzt (das sind retained messages, oder)? Könnt ihr alle retained messages clearen und dann sehen, ob das Problem noch auftritt? Ich mache das so:

```
sudo systemctl stop mosquitto.service
sudo rm /var/lib/mosquitto/mosquitto.db
sudo systemctl start mosquitto.service
```

**Comment by knickohr** [comment]
Ich habe auch kein HA und Autodiscovery brauche ich nicht. Da ich vor wenigen Tagen meine Mosquitto-Installation neu aufgesetzt habe werden da wohl keine alten verwaisten Werte mehr drin sein. Aber ich kann die Datenbank trotzdem mal leeren.

**Comment by Argafal** [comment]
@nexulm Can you clarify your exact settings please? Which resets did you enable in the inverter settings, what happens with communication at night (sunset settings), what's your mqtt interval setting?  Do the two graphs show different quantities? What do they show exactly? What do you expect to happen? For example, what happens in your top graph between 2:30 and 7:30 and why doesn't it happen to the bottom graph?

**Comment by knickohr** [comment]
Ich ziehe meine Aussagen zurück. Es sind tatsächlich korrekte Werte. Die Leistung bricht aufgrund sehr kleiner Wolken ein. Es ist eben wieder passiert und ich konnte es sehen. Hätte nicht gedacht, das es so viel ausmacht. Bitte mein Gewäsch ignorieren, funktioniert alles bei mir wie es soll 😲 Sorry.

**Comment by nexulm** [comment]
@Argafal: My inverter settings are:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/5346351/222246861-c5ed301b-a04d-4cb9-9aee-7bfed81f2778.png">
---
I'm not an expert for MQTT but:
1) WLAN isn't disabled at night
2) As I'm using HA since a few days I did always a "Dicovery Config" in case of minor modifications and restart of HA to get actual values from Ahoy, especially if the inverter is offline after sunset. Maybe 750 was the value for "Yield Day" last time I did "Dicovery config"-send?
3) The two graphs are showing on one hand the original HA values and on the other hand the same entity values logged to Influx DB which is visualized by Grafana for nearly the same timeslot.
4) The graphs should switch to zero (0) at midnight, stay there until the inverter starts producing. The graph should show the rising PV production as it does w/o those drops or spikes.
5) Both graphs are showing the same behaviour, especially between 02:30 - 07:30. The only different is that Grafana is/was configured to show dots for the datapoints and doesn't connect the 4 datapoints (22:00 - 07:30) as the default HA visualization does.
---

**Comment by knickohr** [comment]
Hier mal die Aufzeichnung von der Nacht. Nichts was die DTU nicht machen soll, keine Spikes, keine Drops.

![A8CC57D8-CCE6-477A-AE8B-2576E2457715](https://user-images.githubusercontent.com/63048210/222360743-12074441-fcf8-458a-b228-404152acb228.jpeg)

**Comment by knickohr** [comment]
Keine Spikes und Drops in den letzten 24 Stunden. Das einzige was auffällt, der aufsummierte YieldDay wird vorher (beim ersten Zucker der Inverter) genullt, die Yields der einzelnen Inverter erst wenn sie produktiv gehen. Aber das kann man mit den Einstellungen verhindern.

![940D0079-7FB6-40CB-9B5A-95C8AA22E537](https://user-images.githubusercontent.com/63048210/222487073-d5fa9716-8c00-4cd0-b0ef-88c39f2208f6.jpeg)

**Comment by nexulm** [comment]
I‘ll give a try with another MQTT broker. Good to know that na setup has the fault and not Ahoy. 😀👍🏻
Graph from the last 24h added:
![E78EC0EA-11C1-4679-B945-715450E2F490](https://user-images.githubusercontent.com/5346351/222492259-0c467bf2-2d7c-4036-87f5-84677dddedfe.jpeg)

**Comment by knickohr** [comment]
Is this a Broker in the cloud ?  I‘m using a local MQTT Broker.

Maybe the QoS is a problem. Ahoy only use QoS = 0 (fire and forget, no error redundancy).

**Comment by nexulm** [comment]
No, it’s the MQTT2-Server from FHEM which I‘m using since years for my home automation. As I‘m currently in the process of switching from one system (FHEM) to another one (HA).

**Comment by Argafal** [comment]
> I‘ll give a try with another MQTT broker. Good to know that na setup has the fault and not Ahoy. grinning👍🏻

@nexulm Could you please try the following: turn off ahoy. Restart your MQTT broker. And then would you please post the mqtt messages you have for your ahoy mqtt topic?

**Comment by beegee3** [comment]
> @knickohr Das einzige was auffällt, der aufsummierte YieldDay wird vorher (beim ersten Zucker der Inverter) genullt, die Yields der einzelnen Inverter erst wenn sie produktiv gehen.

🤔 komisch, eigentlich sollte beim einzelnen Inverter mit der Statusänderung 'not available' zu 'available' auch ein publish erfolgen und nicht erst bei 'producing'.
@lumapu dafür steht doch in `sendIvData`
```
                        // send RTR Data only if status is available
                        if ((curInfoCmd != RealTimeRunData_Debug) || (MQTT_STATUS_NOT_AVAIL_NOT_PROD != mLastIvState[id]))
                            sendData(iv, curInfoCmd);
```
Was funktioniert da nicht?

Pragmatisch könnte das publish natürlich erzwungen werden (wie abends nach letztmaligem 'producing').
Braucht man das? Wenn ja, wären das in `processIvStatus` die Zeilen (die letzte `if (...)` ist neu)
```
                ...
                if(mLastIvState[id] != status) {
                    // if status changed from producing to not producing send last data immediately
                    if (MQTT_STATUS_AVAIL_PROD == mLastIvState[id])
                        sendData(iv, RealTimeRunData_Debug);
                    // if status changed from not available to availabe send new data immediately
                    if (MQTT_STATUS_NOT_AVAIL_NOT_PROD == mLastIvState[id])
                        sendData(iv, RealTimeRunData_Debug);
                ...
```
Könnte man natürlich in eine `if (...)` zusammenfassen. ist aber so leserlicher.

**Comment by knickohr** [comment]
Ja, hat mich auch gewundert. Es ist sogar noch grasser, er gibt nochmal einen alten Wert aus bevor er nullt 😵

![7CAD9DE0-B119-4845-9634-941E9C5493C6](https://user-images.githubusercontent.com/63048210/222545051-81003530-9a0b-45ee-a0dd-c7b8f13cafc6.jpeg)

(Glück gehabt, wat gerade noch drin im Grahen 😅)

**Comment by beegee3** [comment]
ah, dann wird ja doch bei Statusänderung 'not available' zu 'available' gepublished.
**Also [pragmatischen Vorschlag](https://github.com/lumapu/ahoy/issues/725#issuecomment-1452336872) bitte sofort wieder vergessen.**
Ahoy nullt nur, wenn in den Settings bei mind. einem der 'Reset values' ein Haken gesetzt ist, was bei dir nicht der Fall ist.
Daher sind bei dir die alten Werte bis zur Statusänderung noch im Speicher.

@lumapu `isAvailable` reagiert ja nicht nur darauf, dass aktuelle Werte vom Inverter geliefert werden, sondern auch auf den `timestamp` von `recordInfo`, `recordConfig` und `recordAlarm`. Kann es sein, dass einer von denen ein 'available' auslöst, **bevor** neue Daten vorliegen? Z.B. in `getQueuedCmd` wird bei Bedarf `InverterDevInform_All` **vor** `RealTimeRunData_Debug` in die Queue gestellt. Das würde erklären, warum @knickohr noch einmal die alten Werte erhalten hat, denn der Inverter selbst wird wohl morgens keine alten Daten mehr liefern.

Sollte `isAvailable` vielleicht nur den `timestamp` von `recordMeas` prüfen, oder gibt es dann an anderer Stelle Probleme? Ansonsten würde eine Funktion helfen, die nur genau das abfragt und dementsprechend den 'available' Status in MQTT setzt, d.h.:
in `hmInverter`
```
        bool hasCurrentData(uint32_t timestamp) {
           return ((timestamp - recordMeas.ts) < INACT_THRES_SEC);
        }
```
in `pubMqtt`
```
         bool processIvStatus() {
         ...
                // inverter status
                uint8_t status = MQTT_STATUS_NOT_AVAIL_NOT_PROD;
                if (iv->hasCurrentData(*mUtcTimestamp)) {
         ...

```

**Comment by nexulm** [comment]
After switching to another MQTT broker and using the newer Ahoy DEV 0.5.93 no drops & spikes observed.
![4E0BCA72-79B3-4E04-92EC-E17FBB34A0D3](https://user-images.githubusercontent.com/5346351/222976703-9ace560b-3fee-4a75-bf47-ca99df3d16dd.jpeg)
