### ISSUE TITLE
MQTT - Retained-Flag von 2 Werten entfernen

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#726]
Bitte bei den beiden P_AC und P_DC Werten vom Topic total das Retained-Flag wieder entfernen.

Die beiden Werte sind flüchtig und werden auch nicht aufsummiert. Ein Vorhalten als Retained im Broker ist somit sinnbefreit.

<img width="298" alt="D1E8CFAF-54D5-469C-944A-54ACA9DD370C" src="https://user-images.githubusercontent.com/63048210/222190376-25d0f8b2-0fd8-489e-a385-2b2eaa7907b0.png">

**Comment by Pixel-Chris** [comment]
siehe dazu auch
#721

**Comment by knickohr** [comment]
Hier alle Werte die retained geflaggt sind, also auch P_AC und P_DC (DEV 93) :

![7F1E2B84-A2EA-4A30-A019-9824271D299B](https://user-images.githubusercontent.com/63048210/222787241-6bbb6fef-21f1-495f-a713-a3bcc579c776.jpeg)

Topic mqtt ist der „Last Will“ !

**Comment by knickohr** [comment]
OK

**Comment by knickohr** [comment]
Das war zu viel des Guten 😲

Bitte nur die beiden Werte P_AC und P_DC aus den retained Values entfernen, nicht alle 4 unter inverter/total 😉

Es fehlen jetzt auch die beiden grün markierten Werte YieldDay und YieldTotal 👍 

![3145EE46-DA0C-46B0-BAA1-0A80EF9F5CAF](https://user-images.githubusercontent.com/63048210/224561679-77c25132-cc0d-4fc6-a518-e6b110540855.jpeg)

**Comment by knickohr** [comment]
Jetzt paßts 🤔
