### ISSUE TITLE
YieldTotal Correction nach Update auf DEV

### ISSUE THREAD

**Issue by Pixel-Chris** [lumapu/ahoy#730]
bin nun auf der DEV 0.5.92

gibt es irgendwie die Möglichkeit den YieldTotal wieder auf den Wert von vor dem Update zu setzen? Der hat sich leider genullt.

Mit dem Offset klappt es leider nicht, obwohl man dort minus und plus Werte eintragen kann (leider anscheinend aber auch keine Kommastellen)
Oder zieht das Offset nur, wenn der WR/Inverter auch wieder online ist?

ich müsste auf diese Werte kommen:
CH1: 5.974
CH2: 0.106
CH3: 4.482
CH4: 0.149
CH0: 10.711
Total: 10.711

Ist dies irgendwie möglich?

Wenn nicht, dann sollte dies möglich gemacht werden.
Habe gehofft, dass diese Werte (wie auch Wifi-Settings) erhalten bleiben.

---- ODER ABER
ich überlege hier total falsch.... die Werte kommen nicht von der AhoyDTU sondern direkt vom WR

so wird es wahrscheinlich sein

**Comment by mroenne2022** [comment]
@Pixel-Chris  : Die Werte kommen aus dem WR , wenn also am Abend ein Update der DTU erfolgt dann sind die Werte alle auf "0" , am nächsten morgen wenn der WR wieder erreicht wird kommen die Werte wieder ! Ich denke so ist es , bin ziemlich sicher. Hab gerade z.B. bei meiner OpenDTU den Update gemacht - dort ist es genauso !
