### ISSUE TITLE
Keine Anzeige der Live-Ansicht auf dem Samsung Fernseher

### ISSUE THREAD

**Issue by Mart-Muc** [lumapu/ahoy#739]
Hallo Zusammen,
Für einen schnellen Überblick (für meine Familie) habe ich die „Internet“-App unseres Samsung Fernsehers (BJ2023) nutzen wollen.

alle Menüpunkte wie Einstellungen, etc werden korrekt dargestellt, nur die Live-Übersicht bleibt unausgefüllt.

Javascript habe ich kontrolliert, ist aktiviert.

Gibt es eine Lösung? Was könnte ich übersehn haben?

Danke, Mart

**Comment by Mart-Muc** [comment]
V. 5.66

**Comment by dtuuser** [comment]
5.93 bei Philips auch nicht

**Comment by tqma1** [comment]
Kann für Samsung bestätigen 0.5.93 - keine Live Anzeige

**Comment by lumapu** [comment]
gibt es da eine Art debug Konsole oder eine Info worauf der Browser basiert?

**Comment by dtuuser** [comment]
Konsole habe ich beim Philips nicht gefunden. Auf dem TV läuft Android mit dem Standard Browser

**Comment by lumapu** [comment]
könnt ihr versuchen genaueres über den Browser über zB. http://wieistmeinuseragent.de/ herauszufinden?

**Comment by tqma1** [comment]
![image](https://user-images.githubusercontent.com/1890699/223936521-96379c17-a873-4037-a751-675cebb8368e.png)

Mozilla/5.0 (SMART-TV; Linux; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/76.0.3809.146 TV Safari/537.36

Samsung TV

**Comment by dtuuser** [comment]
Beim Philips wie oben beim Samsung. 
Unterschied
Linux Android 9.KHTML like Gecjo, Chrome 77.0.3865.120 Safari 536.36 OPR 46 0.2207.0 OMI 4.20.3.56 Typhoon 59 Philips MT 5599

**Comment by DanielR92** [comment]
Wenn ich mein Agent auf die von obrigen Daten ändere. Ändert sich bei mir nichts.
Sieht alles i.O aus. ... hmm vielleicht ist es nicht der Agent unbedingt, sondern eher der Browser vom TV was es ja falsch darstellt.

Irgendwo gab es eine Tabelle zum Thema Stylesheet... welche Browser was genau Unterstützen.

**Comment by lumapu** [comment]
es ging hier vielmehr darum den eingesetzten Browser zu erfahren und dessen Fähigkeiten

**Comment by stefan123t** [comment]
@lumapu hier ist die Liste der von Samsung's Tizen 6.0 unterstützten CSS und JavaScript (ES6) Features:

Web Engine Specifications
https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html
