### ISSUE TITLE
Addition of support for poe ESP32

### ISSUE THREAD

**Issue by ude6** [lumapu/ahoy#745]
Hi,
I am using the current ahoy version to collect data from my Hoymiles Hm-600 and
set parameters via MQTT. Both of these things wor actually very good. Thank you for developing such a 
fantastic product. 
I have one problem: I am using the HM-600 inside a closed steel cabinet so the WLAN in/out is
very restricted.

I was wondering if it would be an idea to also support mybe boards like the following:
https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware
to mitigate the problems of flaky WLAN coverage?

Thanks again!
Andreas

**Comment by lumapu** [comment]
it is planed to support W5500 boards in near future

**Comment by lumapu** [comment]
we continue discussing in issue #886
