### ISSUE TITLE
development version 0.5.95 Nokia-Display fehlt plötzlich in den Settings

### ISSUE THREAD

**Issue by nuiler** [lumapu/ahoy#746]
### Platform

ESP8266

### Antenna

circuit board

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

development version 0.5.95

### Github Hash

f5ef19c

### Build & Flash Method

ESP Tools (flash)

### Desktop

Linux

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Seit dem Update auf development version 0.5.95 fehlt das Nokia-Display. Ist dies gewollt?

**Comment by knickohr** [comment]
Wurde wegen Stabilitätsproblemen und Verwendung anderer Ports vom ESP8266 entfernt. Wird nur noch am ESP32 (HSPI, andere Pins) supportet.

**Comment by nuiler** [comment]
Schade - gab es einen Hinweis darauf?

**Comment by Loetnase** [comment]
@knickohr 
Das find ich auch schade.
Ich habe da so schöne Platinchen (PCB) für den ESP8266 fertigen lasse und auch schon was mit dem Nokia aufgebaut aber die Oleds funktionieren auch, ich bin fast soweit um die hier für alle online zu stellen. Siehe  #733
Ist es denkbar einen ESP32 D1mini mit gleicher Pinbelegung wie ESP8266 zu verwenden.
Wären da alle PIOs entsprechend ummappbar.
Könnte am ESP32 D1mini auch das ePaper verwendet werden?

**Comment by knickohr** [comment]
Dazu habe es mehrere Diskussionen im Discord, auch gab es im Github Issues. Daraufhin wurde beschlossen das Nokia vorerst beim ESP8266 mal nicht über den SPI gleichzeitig mit dem NRF-Modul kommunizieren zu lassen. Der ESP32 hat 2 getrennte SPI, deshalb haben wir eine strikte Trennung eingeführt.

Die zweite Frage kann ich so auf die Schnelle auch nicht beantworten. Vergleiche doch einfach die GPOIs der beiden Module.

**Comment by lumapu** [comment]
@Loetnase 
Habe gestern noch mit @dAjaY85 diskutiert, es kann gut sein, dass das Nokia in kürze beim ESP8266 wieder reinkommt.

**Comment by lumapu** [comment]
sollte wieder gehen mit Version `0.5.96`

**Comment by Loetnase** [comment]
Danke euch allen. 
Ihr seid toll.

**Comment by dAjaY85** [comment]
Geht das Nokia wieder, hat es jemand getestet?

**Comment by Loetnase** [comment]
Bei mir hat es leider nicht funktioniert.
Das Update von 0.5.93 auf 0.5.96 ergab einen blanken Bildschirm und bootenden ESP 8266.
Nachtrag: die Settings vom Display waren weg, nach Wiedereintrag hat es aber auch nichts angezeigt. 
So sollte es eigentlich klappen aber ich habe leider keine Anzeige. 
![grafik](https://user-images.githubusercontent.com/120967249/224141949-10de09fd-0c24-4ce5-b169-d0a557f5b7c5.png)

**Comment by knickohr** [comment]
Ich habe es auch nicht hin bekommen. Sieht auch so aus als ob Settings nicht übernommen werden. Beispiel OLED und Drehung, Kontrast (Helligkeit) ohne Funktion.

**Comment by lumapu** [comment]
OLED und Drehung konnte ich erfolgreich anwenden, aber wie ihr mich kennt ist die `0.5.97` schon bald unterwegs und behebt hoffentlich alle Probleme mit Displays

**Comment by Loetnase** [comment]
@lumapu 
bei mir funktionier es in der 0.5.97 (rechts schwarzer Hintergrund) leider nicht wie gedacht.
Das Nokia Display zeigt wieder etwas an aber nur Offline weil die  **nrf24l01+ is not connected**
Bei der 0.5.93 (links weisser Hintergrund) funktionier es, da geht die Hardware online.
Ich hoffe meine Einstellungen dazu sind alle richtig?
![grafik](https://user-images.githubusercontent.com/120967249/224271206-8a7521bd-619d-48c5-b4fa-2100f03b1610.png)
![grafik](https://user-images.githubusercontent.com/120967249/224272936-87e1bff3-624a-42dd-8409-375af69ed512.png)
Rotation funktioniert nicht, pixel shifting funktioniert
![grafik](https://user-images.githubusercontent.com/120967249/224273666-af2701fe-f7f5-446d-820e-82168844ab54.png)
Hast du ein Nokia zum Testen, wenn nein könnte ich dir eines komplett aufgebaut am Wemos zukommen lassen, 
als kleines Dankeschön für deine Anstrengungen für uns alle. 
![grafik](https://user-images.githubusercontent.com/120967249/224276507-93497328-81e7-4626-be9d-f9ad52ec55bf.png)

**Comment by dAjaY85** [comment]
Moin, ich habe ein Nokia.

Mit dieser Hardwareverdrahtung soll es auf der dev 97 funktionieren.

![Screenshot_2023-03-11-13-40-44-655_com.discord.jpg](https://user-images.githubusercontent.com/6034639/224485144-e007c6cb-f0ba-4f9a-affc-656f149992d8.jpg)
