### ISSUE TITLE
Temperatur Anzeige

### ISSUE THREAD

**Issue by theunknownstarman** [lumapu/ahoy#754]
Weis jemand ob die Temperaturanzeige den Wert des Wechselrichters entspricht oder ist das die Temperatur der Platine?

![Screenshot](https://user-images.githubusercontent.com/8588074/223979688-5a359c12-392d-4472-be6b-e83240913665.jpg)

**Comment by Argafal** [comment]
Das ist die Temperatur die der Wechselrichter an die DTU sendet.
