### ISSUE TITLE
Faulty irradiation calculation of CH4 - HM1500

### ISSUE THREAD

**Issue by nexulm** [lumapu/ahoy#755]
Great update on the UI. 😀
—-
I believe there is a calculation error [AHOY 0.5.96] of the irradiation. For me at least for CH4. All modules are very similar orientated close together. Multiplicator of 10 for Ch4 would solve the issue for me!?!

![6227E51E-A964-4259-982A-215FBF225E99](https://user-images.githubusercontent.com/5346351/224002267-12e8ab72-0da6-41cb-8ba5-558010ea92a4.jpeg)

**Comment by beegee3** [comment]
please look into your setting for CH4. Is the Max Module Power value correct?

**Comment by nexulm** [comment]
Good hint, there was a typo 4110 instead of 410 due to the fact that I've to re-add the inverter after updating from 0.5.92 to 0.5.93 this week. I will close the issue again although I can't reach the ESP8266 anymore after update, Save and PowerOn-Reset aswell. :-(
---
![image](https://user-images.githubusercontent.com/5346351/224039532-cae66b15-0087-45ec-8cb8-25a654dfc01a.png)
