### ISSUE TITLE
Nachtabschaltung Display funktioniert nicht

### ISSUE THREAD

**Issue by jimknopf63** [lumapu/ahoy#756]
### Platform

ESP32

### Antenna

circuit board

### Power Stabilization

~100uF Elko

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.96

### Github Hash

6ef7720

### Build & Flash Method

Platform IO (build & flash)

### Desktop

Mac OS

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Habe seit gestern die Version 0.5.96 installiert.
Gestern Abend habe ich bemerkt das obwohl eingestellt
das Display (1,3") nicht deaktiviert wird. Komme von
der 0.5.93 da funktionierte das noch.

<img width="902" alt="Bildschirm­foto 2023-03-10 um 11 34 19" src="https://user-images.githubusercontent.com/97401894/224293970-85e2e82a-92ca-4dc5-b50e-8b5baa08ffc2.png">

**Comment by Loetnase** [comment]
Du kannst ja mal die neue 0.5.97 ausprobieren, aber an der lässt sich bei mir am ESP8266 das Nokia Display nicht um 180° drehen und die Antenne wird auch nicht mehr verbunden.
Vieleicht funktioniert es mit demESP32 und SSH1106 trotzdem. Siehe #746

**Comment by jimknopf63** [comment]
> Du kannst ja mal die neue 0.5.97 ausprobieren, aber an der lässt sich bei mir am ESP8266 das Nokia Display nicht um 180° drehen und die Antenne wird auch nicht mehr verbunden.
> Vieleicht funktioniert es mit demESP32 und SSH1106 trotzdem. Siehe #746

Die 05.97 habe ich seit heute Mittag installiert. Mein Display funktioniert nach wie vor am ESP32 und die Antenne hat sich auch normal mit dem WR (HM1500) verbunden. Von daher also Entwarnung. Nachtabschaltung des Displays ist allerdings auch in der Version  nicht gegeben. Weiterhin habe ich gerade festgestellt das die Pinouts vom Display alle auf Off/default stehen. Wenn man eigene Einstellungen macht (was bei mir die default Werte sind) werden die nach speichern/reboot nicht übernommen.

**Comment by lumapu** [comment]
es liegt am ausgewählten Displaytyp welche Einstellungen übernommen werden.
Ich habe schon eine 0.5.98 vorbereitet, aber noch nicht veröffentlicht, die kann dann wieder Nachtabschaltung
