### ISSUE TITLE
[ESP8266] Display 0,96" SSD1306 geht nicht

### ISSUE THREAD

**Issue by ntfrnd** [lumapu/ahoy#759]
### Platform

ESP8266

### Model name

https://www.makershop.de/plattformen/d1-mini/esp8266-mini-board/

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.97 dev

### Github Hash

28bd99e

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

Ich habe ein 0,96" Display SSD1306 angeschlossen.
VCC an 3,3V
GND an GND
SCL an GPIO5 Pin D1
SDA an GPIO4 Pin D2

Im Setup habe ich den Displaytyp (SSD 1306 0,96") ausgewählt und Clock = D1 (GPIO5, SCL) und Data = D2 (GPIO4, SDA) gesetzt, gespeichert und rebootet.
ABER: Display bleibt dunkel. Nach Überprüfen der HW habe ich den Displaytyp geändert auf "SSH1106 1,3" ", Pinout unverändert, und siehe da: Das Display funktioniert.

![image](https://user-images.githubusercontent.com/99898355/224476694-b886772c-0b9c-423d-9c3c-04b8bd7238ee.png)

![20230311_103419](https://user-images.githubusercontent.com/99898355/224476847-df8ed48f-814f-4a07-b3f0-0242cd22550d.jpg)

**Comment by knickohr** [comment]
Das ist so nicht ganz korrekt. Ja, der SH1106 kann als Workaround für das SSD1306 genommen werden, es kann aber sein das das Display dann komische Punkte am linken Rand anzeigt. Sollte so keine Dauerlösung sein !

**Comment by gandalfred** [comment]
Display SSD1306 geht mit der 0.5.99 immer noch nicht. Mit dem Setting für SH1106 funktioniert das SSD1306 aber.

**Comment by MiniOh** [comment]
Bei mir geht das SSD1306er mit SSD1306 Settings auch nicht, also es bleibt vollkommen schwarz.
Mit SH1106  im Setting gehts, sieht aber eben nicht sauber aus.

ESP32 bei mir.

**Comment by dixy245** [comment]
Ich hatte mal etwas gelesen, dass es programmiertechnisch einen Shift um 2 Pixel nach links beim SSD1306 bedarf. Ansonsten sollen die beiden Displays identisch sein.

**Comment by HorstyS** [comment]
Same here....ich hab eben die 0.5.100 aufgespielt und mein SSD1306 funktioniert nur mit der Auswahl SH1106. Pixelshift funktioniert auch ohne Probleme und alles scheint lesbar zu sein (bis auf die zu kleinen Statusinfos am unteren Rand).

**Comment by knickohr** [comment]
Dann nimm gleich mal die 101 !

damit funktioniert es wieder 😉

![0CBA4D9B-09E6-4E6D-B236-7F44BC69FCC5](https://user-images.githubusercontent.com/63048210/225628382-618304c3-d67f-458f-a0b1-bcfa31e9e46d.jpeg)

**Comment by HorstyS** [comment]
Merci, versuche ich gleich mal.
Frage: Was ist das rechte denn für ein Display und wie wird es angesteuert/konfiguriert? Sieht aus wie ein eInk :) Haben will ;)

**Comment by HorstyS** [comment]
Jup, funktioniert nun auch mit der Einstellung SSD1316 und dem SSD1316 Display.
Well done

**Comment by lumapu** [comment]
ja das rechte ist ein ePaper 1.54" 200x200px Waveshare per SPI angeschlossen 
geht nur mit ESP32

**Comment by HorstyS** [comment]
Danke, werd ich mal versuchen

**Comment by lumapu** [comment]
wichtig ist die V2 zu kaufen, es gibt verschiedene Merkmale dafür

**Comment by knickohr** [comment]
V2 Rev 2.1 Am besten direkt bei waveshare.

Vorsicht, es gibt viele Anbieter die noch Restbestände „günstig“ vertickern. Es gibt mindestens 3 verschiedene Versionen mit teilweise unterschiedlichen Controllern. Es funktioniert nur das bisher neueste !

![09830ACE-6D3F-4AE4-99D4-015A4FA60A3E](https://user-images.githubusercontent.com/63048210/225718290-79093677-f2c8-4895-bdb7-99250079806b.jpeg)

**Comment by dtuuser** [comment]
> Dann nimm gleich mal die 101 !
> 
> damit funktioniert es wieder 😉
> 
> ![0CBA4D9B-09E6-4E6D-B236-7F44BC69FCC5](https://user-images.githubusercontent.com/63048210/225628382-618304c3-d67f-458f-a0b1-bcfa31e9e46d.jpeg)

gibt es ein changelog zur 101?

**Comment by knickohr** [comment]
Leider noch nicht gesehen. Da muß @lumapu noch Hausaufgaben machen 😇

**Comment by dtuuser** [comment]
Okay. Danke.
Meine 5.92 läuft jetzt seit 12 Tagen 1 Std.

**Comment by soebbing** [comment]
@knickohr Sorry für's de-railen, aber hast Du vielleicht einen Link zu dem Gehäuse? Das gefällt mir echt gut!

**Comment by lumapu** [comment]
es gibt in Discord einen eigenen Channel dafür
