### ISSUE TITLE
Panel max-Values can only be configured on the second attempt

### ISSUE THREAD

**Issue by Argafal** [lumapu/ahoy#766]
Running 0.5.99

When initially configuring, I can add inverters but there are no fields for the max values. Screenshot attached:
![image](https://user-images.githubusercontent.com/715254/224817268-ed4888cb-0932-484c-b2bc-c39830714536.png)

After rebooting the max-value fields appear. I expected that the max-value fields should be presented already on the initial configuration of the inverter.

**Comment by lumapu** [comment]
yes I locally fixed that issue yesterday but not provided a new version.
thanks for reporting
