### ISSUE TITLE
"Settings successfully saved"

### ISSUE THREAD

**Issue by Argafal** [lumapu/ahoy#770]
0.5.99.
When configuring a new AHOY setup and pressing save, there is webUI saying that the settings were successfully saved. However, I encountered a few times that after a reboot ahoy still was unconfigured. I assume that the settings couldn't applied correctly, for example because the JsonDocument might have been too small for all the settings (guess). Is the message "settings successfully saved" actually trigger by success? Or is it just a generic message that is said upon POST, no matter what?

**Comment by lumapu** [comment]
yes this message was only printed if the settings were stored successful. While checking this part of code if seen that an overflow of the JsonDocument will lead in a empty configuration.
With next dev version `0.5.102` this message only occurs if the settings were stored.
