### ISSUE TITLE
Nach Firmware und AP > Passwort eingabe & keine Verbindung

### ISSUE THREAD

**Issue by SteBe80** [lumapu/ahoy#777]
## Hardware
 
  * [X ] ESP32
   
Modelname: AZ_Delivery
Retailer URL: ______

### nRF24L01+ Module
* [ X] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
 
### Antenna:
* [ ] circuit board
* [ ] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

 Hallo zs,
nach Firmewareaufspielung habe ich jetzt den AP...mit dem PW openXXXX schreibt er jedesmal, Verb. kann nicht hergestellt werden.
auch andere Versionen der FM ohne Erfolg... ich musste auch zum flaschen den ESP32 Flash DL Tool 3.9.4 nutzen.

Ich bin ratlos und wer kann helfen....
Danke Euch

**Comment by mroenne2022** [comment]
Hier bist du doch bei Ahoy  , das Passwort ist hier esp_......... !
Das andere Passwort gilt beim Projekt OpenDTU
