### ISSUE TITLE
JSON Export: Seriennummern werden Dezimal statt Hexadezimal gespeichert

### ISSUE THREAD

**Issue by dixy245** [lumapu/ahoy#783]
### Platform

ESP8266

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

~100uF Elko

### Version

0.5.101.

### Github Hash

3e67f2a

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU

**Comment by lumapu** [comment]
gerade mit `0.5.105` getestet:
- export mit 2 invertern
- delete inverter -> save + reboot
- import 
- beide inverter sind wieder mit identischer Seriennummer da
