### ISSUE TITLE
ESP32 Kommunikation mit NRF24L01+ Modul

### ISSUE THREAD

**Issue by KoLSMS** [lumapu/ahoy#787]
Hallo,
habe heute ein ESP32 Board mit einem NRF24L01+ Modul verdrahtet, leider zeigt mir die Weboberfläche der AhoyDTU die Meldung an nrf24l01+ is not connected.
Habe ich bei der Verdrahtung einen Fehler gemacht?!
Ich hoffe man kann auf den Bildern alles gut erkennen 🙂
Gruß...

![PXL_20230318_160710403 MP](https://user-images.githubusercontent.com/29553174/226170037-8e327d8e-38a1-42bf-a696-ecf204ea4a88.jpg)
![PXL_20230318_160715581 MP](https://user-images.githubusercontent.com/29553174/226170041-64e69c14-0c42-4f4c-9b1b-5ecf7040bdc3.jpg)
![PXL_20230318_160756522](https://user-images.githubusercontent.com/29553174/226170042-34087237-0bfb-42b2-bc9e-5ff1c94e0a05.jpg)
![PXL_20230318_160809358](https://user-images.githubusercontent.com/29553174/226170044-0f353d55-0f94-47d8-9ca6-f4dea02255ae.jpg)
![PXL_20230318_160823588](https://user-images.githubusercontent.com/29553174/226170045-e3940b0a-73da-4dce-924e-453ee8b24f15.jpg)

**Comment by teletapi** [comment]
Die Bilder sind in teilen so groß und unscharf und noch gezoomt das man garnix mehr richtig erkennt

**Comment by KoLSMS** [comment]
> Die Bilder sind in teilen so groß und unscharf und noch gezoomt das man garnix mehr richtig erkennt

Hallo,

so sieht man es besser?!

Gruß...

![PXL_20230319_130347874 MP](https://user-images.githubusercontent.com/29553174/226177208-b3f35179-edd7-4ed2-9164-4ea215c3d498.jpg)
![PXL_20230319_130415381 MP](https://user-images.githubusercontent.com/29553174/226177211-9e8ba931-2fcd-4e06-b415-215db0efcd57.jpg)
![PXL_20230319_130425153](https://user-images.githubusercontent.com/29553174/226177214-b44c307a-d398-4b4b-ac62-54fde524fe44.jpg)
![PXL_20230319_130435421](https://user-images.githubusercontent.com/29553174/226177215-2f4894fa-c50c-4f36-8291-ffc6efd340c1.jpg)

**Comment by Argafal** [comment]
Hast du noch einen Screenshot von "Einstellungen" "System Config"? Da ist das Pinout definitert.

**Comment by KoLSMS** [comment]
> Hast du noch einen Screenshot von "Einstellungen" "System Config"? Da ist das Pinout definitert.

Hallo, ja, selbstverständlich:

![Screenshot_20230319-180639](https://user-images.githubusercontent.com/29553174/226192712-738edb5c-c3dc-4fb6-b6a3-45a0da787715.png)

**Comment by Argafal** [comment]
Sieht in meinen Augen gut aus. Vielleicht ist der NRF kaputt? oder eine nicht-plus Version? Der Kondensator falsch rum? Die Verdrahtung sieht so aus, wie ich sie erwartet hätte. 
Irgendwo gab es hier einen anderen Issue da hatte jemand Fotos von zwei NRF Modulen gepostet. Beide sahen gleich aus, eins ging, das andere nicht...

**Comment by Tofffii** [comment]
Die Verdrahtung sieht auch für mich gut aus. Die Lötpunkte am Kondensator wirken recht groß, sind auf den Fotos aber nicht richtig sichtbar, ist ein Kurzschluss sicher ausgeschlossen?

**Comment by KoLSMS** [comment]
Hallo,

vielen Dank für die Antworten, ich habe den Fehler nun endlich gefunden...

Es war alles richtig, der ESP32 Chip hat einen Schuss weg...

Neuer ESP32 und schon läuft alles...

Ärgerlich wenn man voraussetzt das der Chip in Ordnung ist...

Vielen Dank nochmals...

PS: Woran ich das gemerkt habe?

Ich habe die Verbindung zwischen ESP32 und NRF getestet mit einem Messgerät, dabei ist mir per Zufall aufgefallen das GND und GPIO23 eine Verbindung haben, was sowas von keinen Sinn machte das ich das am anderen Chip auch getestet habe, hier Bestand keinerlei Verbindung und schon ging alles...

Tja, der Fehler liegt im Detail :)
