### ISSUE TITLE
sanity check of the serial number

### ISSUE THREAD

**Issue by Argafal** [lumapu/ahoy#790]
I propose to check the first four digits of the serial numbers. That is, we should verify that they match our expected format. I propose this because a user in discord's #support-ahoy channel entered an inverter starting with 1411, rather than our expected 1141. It might be a typo, but if so it is well masked: since the last 8 digits match ahoy works, just the format expectation of the messages doesn't match.

Maybe it'd be prudent to tell the user if the first four digits of a serial number are not in our whitelist of format expectation, so that they can double check their input.

**Comment by lumapu** [comment]
I think this check is not needed - there are no reported issues about that. Will close here.
