### ISSUE TITLE
kein Display Setting Menü in 0.5.66?! ESP32 SSD1306 + SSD1306/1106 an 8266

### ISSUE THREAD

**Issue by grericht** [lumapu/ahoy#791]
Hallo. Bin erst neu bei Github angemeldet und hoffe nicht gleich einen Fehler durch eine zu Dumme Frage zu begehen.

Ich bastel gerade etwas an einer ahoyDTU herum. Bin bisher super zufrieden und wollte nun um ein Display erweitern. Da ich 2 Freunde mit versorge hab ich mir fast alle Kombinationen bei Ali.*.* bestellt.

Ich habe bisher mit dem Webinstaller die letzte stable installiert. 0.5.66 müsste das sein. Danach bleibt mein Display am ESP32 dunkel. Der rest geht. Wenn ich dann die Datei 221230_ahoy_0.5.66_esp32_ssd1306_f8fe044.bin per web-gui update installiere. geht das Display an. Aber ich habe kein Menü Display Settings. Gibt es das ncoh nicht in der Rev?

Wie bekomme ich eine Dev-Rev. installiert und welche Version ist da empfohlen? Die neueste? Hab nur die 230319_ahoy_0.5.103_296597a_esp32.bin  per web-gui update installiert aber dabei "fährt der esp32 fest". Muss dann wieder komplett auf die 0.5.66 zurück udn die display.bin updaten. Entschuldigt meine dummen fragen aber ich finde wirklich kaum etwas zum Thema Display anschließen.

die nächste Frage wäre: ich hab mir gleich noch das 1306 und das halb so große 1306 mitbestellt. Die würde ich gerne als nächstes anschließen. Dafür gibt es aber bei der 0.5.66 keine update Datei.

Last but not least: zum 8266 finde ich gar keien Darstellung zur Verkabelung mit den Displays. 5v udn gnd finde ich sicher. Aber woran kommn die beiden Signal-Leitungen?

Ich danke euch!

**Comment by mroenne2022** [comment]
![Screenshot_20230320_065102_Facebook](https://user-images.githubusercontent.com/114778920/226258147-db9712c5-6b2b-403b-876c-95959a7e8ba3.jpg)

Das wird so zumindest in der FB Gruppe kommuniziert, ich selbst hab aber kein Display.

**Comment by knickohr** [comment]
Das ist die offizielle Verdrahtung für eine Ahoy-DTU mit OLED

![06BC587D-4BED-4729-8275-51C0A62C59EF](https://user-images.githubusercontent.com/63048210/226268942-b4dced82-1b88-46a9-adc2-43ffc646dba0.jpeg)

unf für den ESP32

![1549DBF5-9AC7-4C4E-999F-5182236E23C4](https://user-images.githubusercontent.com/63048210/226269894-394da364-8dd1-42c3-b90a-5c289e82362e.jpeg)

Ein Display-Setting findest Du für die Version 0.5.66 noch nicht, einfach nur das richtige Binary auswählen und gut ist,

Das größere 1,3“ SH1106 wird mit der 66 auch noch nicht supportet. Nimm eine Developer-Version.

Developer-Versionen gibt es hier :
https://nightly.link/lumapu/ahoy/workflows/compile_development/development03/ahoydtu_dev.zip

**Comment by grericht** [comment]
vielen vielen Dank! Super Community hier!
Hab jetzt auch die aktuellste dev installiert bekommen. Hatte den Hinweis "Bekommt man nach der Auswahl des COM-Ports einen Fehler Failed to download manifest muss man Chrome mit einem Parameter starten: Windows start chrome --allow-file-access-from-files" übersehen. 
Am 8266 werde ich die displays zeitnah testen.

_Ich habe auf dem Display links oben aber ein paar fehlende Pixel. Ist das normal? Muss mal ein anderes Display anschließen und schauen. Ist genau dort wo die Aktuelle Leistung angezeigt wird. also ein no-Go_
EDIT: hat sich erledigt. Keine AHnung woran es lag aber nachdem ich es neu angeschlossen hab waren alle Pixel da

Frage 01: Ich hab vorher von der 0.5.66 eine jsan sicherung gemacht und hinterher eingespielt. Dabei hat es aber keien Daten übernommen? Liegt das daran, weil die Versionen (zu) unterschiedlich sind?

Frage 02: Perspektivisch würde ich gerne versuchen selber ein wenig zu schauen wie/wo ich etwas auf dem Display anzeige. Gibt es dafür eine gute Beschreibung wie ich mich damit gut auseinandersetzen kann?

**Comment by Argafal** [comment]
> Frage 01: Ich hab vorher von der 0.5.66 eine jsan sicherung gemacht und hinterher eingespielt. Dabei hat es aber keien Daten übernommen? Liegt das daran, weil die Versionen (zu) unterschiedlich sind?

Es hat sich viel seit 0.5.66 einiges geändert. Ich denke, neue Einstellungen setzen ist die beste Lösung. Macht man ja auch nur einmal.

**Comment by Loetnase** [comment]
Hallo @knickohr ,
liegen die fritzings mit Display (auch Nokia neuester Stand) irgendwo ab?
In Discord habe ich die gesehen, waren aber nicht runterladbar und etwas unscharf.

**Comment by lumapu** [comment]
@Loetnase ich packe sie auf https://AhoyDTU.de

**Comment by knickohr** [comment]
Ich kann sie hier in Originalauflösung oder wie ihr sie haben wollt (sagt mir die DPI) hier her laden.

Habe für alle Displaytypen jeweils ein Fritzing.

**Comment by Loetnase** [comment]
Die Auflösung sollte hoch sein damit beim ESP32 möglichst die GPIO Beschriftung und auch sonstige Beschriftungen noch lesbar sind. Wenn das möglich ist? 
Macht es Sinn die bei den Tools z.B. https://github.com/lumapu/ahoy/tree/main/tools abzulegen, dort eventuell einen neuen Ordner Schemen, Schaltpläne oder Verkabelung zu erstellen.
Danke

**Comment by knickohr** [comment]
![4D2C49A6-C457-49FC-80C2-7EF481B57862](https://user-images.githubusercontent.com/63048210/227565141-4dcd1187-40bd-4ef3-974e-a4e7dd20b027.png)
![C5C1820C-34E2-4FC7-8E6F-93DD4D2F0A06](https://user-images.githubusercontent.com/63048210/227565152-d8d8bb0a-fbbb-47a3-b381-eaa7395a52df.png)
![C8A9C792-A8E9-4054-9705-1BBA6606E773](https://user-images.githubusercontent.com/63048210/227565157-d381147d-aa6a-4b31-9c54-18b8584554d3.png)
![573F42A0-BCBB-44E5-996D-D623202D37A2](https://user-images.githubusercontent.com/63048210/227565163-c4a18485-7716-49a8-afd9-b4e82a5cd003.png)
![51AB2959-A8B7-48B5-BAA7-9BDB39BB95B5](https://user-images.githubusercontent.com/63048210/227565167-421bc13b-02ff-4766-bac8-94cd4b8803a0.png)
![07C0FD0C-4991-41C8-87FD-18AAA3AAE9BF](https://user-images.githubusercontent.com/63048210/227565175-c875946e-983a-4407-8dbb-9f9eb10914de.png)

**Comment by Loetnase** [comment]
Die sehen doch schön und lesbar aus, 
ich danke dir  👍

**Comment by filo4444** [comment]
Please add descriptions of capacitors capacity.

**Comment by Silece87** [comment]
Hi, wie hoch muss die Kapazität der Kondensatoren sein? Viele Grüße

**Comment by Loetnase** [comment]
@Silece87 
100uF 5V oder mehr. Der Kondensator am Antennenmodul nrf24 ist Pflicht, die zwei andern "nice to have".
Meist wird der Kondensator direkt am Antennenmodul an den +3,3V und GND Pins oben angelötet. Dabei auch die Polarität des Kondensators beachten, meist ist ein - an dem Anschlusspin am Gehäuse aufgedruckt, der kommt auf GND.

**Comment by Silece87** [comment]
Hi,
Vielen Dank für die Info, dass 5V steht für 5 Volt? Könnte ich auch einen 100uF mit 35 V verwenden? Oder meinst du mit mehr, mehr farad.
Viele Grüße
    Am Freitag, 11. August 2023 um 10:20:05 MESZ hat loetnase ***@***.***> Folgendes geschrieben:  
 
 


@Silece87
100uF 5V oder mehr. Der Kondensator am Antennenmodul nrf24 ist Pflicht, die zwei andern "nice to have".
Meist wird der Kondensator direkt am Antennenmodul an den +3,3V und GND Pins oben angelötet. Dabei auch die Polarität des Kondensators beachten, meist ist ein - an dem Anschlusspin am Gehäuse aufgedruckt, der kommt auf GND.

**Comment by Loetnase** [comment]
@Silece87 
das bezog sich auf die 5 Volt, wenn die eine größere Spannung z.B. 35 Volt können funktionieren die auch mit 5 Volt sind aber mechanisch größer. 
Mehr uF ist auch okay aber auch mechanisch größer.

**Comment by Silece87** [comment]
Ohne die Kondensatoren würde ich das Board grillen?
    Am Montag, 14. August 2023 um 12:50:04 MESZ hat loetnase ***@***.***> Folgendes geschrieben:  
 
 


@Silece87
das bezog sich auf die 5 Volt, wenn die eine größere Spannung z.B. 35 Volt können funktionieren die auch mit 5 Volt sind aber mechanisch größer.
Mehr uF ist auch okay aber auch mechanisch größer.

**Comment by Loetnase** [comment]
@Silece87 
Nein, ohne Kondensatoren passiert dem Board nichts, das sind in dem Fall nur Pufferspeicher, die das Ganze stabiler funktionieren lassen.  Das funktioniert oft auch ohne die Kondensatoren, aber bei vielen komischen Problemen sind die mit Kondensatoren plötzlich weg. Suche mal nach den 10 Geboten von Knickohr.

**Comment by Silece87** [comment]
Ich habe die Anschlüsse 10mal geprüft und auch diverse Leute drüber schauen lassen.Wenn ich es ohne Kondensatoren an 5volt anschließe wird es Sau heiß und kurz danach fängt es an zu qualmen. Kein Grund /plus Verwechslung,alles probeweise getauscht.
    Am Montag, 14. August 2023 um 21:59:31 MESZ hat loetnase ***@***.***> Folgendes geschrieben:  
 
 


@Silece87
Nein, ohne Kondensatoren passiert dem Board nichts, das sind in dem Fall nur Pufferspeicher, die das Ganze stabiler funktionieren lassen. Das funktioniert oft auch ohne die Kondensatoren, aber bei vielen komischen Problemen sind die mit Kondensatoren plötzlich weg. Suche mal nach den 10 Geboten von Knickohr.

**Comment by knickohr** [comment]
Also wenn’s heiß wird und qualmt, ist auf alle Fälle schon mal was kaputt.

Ab in den Müll !

**Comment by Loetnase** [comment]
Ja da hat Knickohr wieder mal zu 100% recht.
Aber was wird denn da heiss und qualmt?
Versuche das mal schrittweise zu testen.
1. Schritt: Mach mal alle Leitungen vom ESP weg und stecke das USB Kabel an einem USB Netzteil ein. Wird der ESP heiss bzw qualmt, dann ist der defekt.
2. Schritt: USB Kabel am PC einstecken, schauen ob sich der ESP am USB meldet und sich eventuell flashen lässt.
3. Schritt: Versuche den ESP ganz normal als AhoyDTU ins WLAN zu nehmen. Hat das funktioniert ist der ESP i.O.
Natürlich kann er dabei die Antenne nicht finden und ist nicht connectet.
4. Schritt: USB ist ausgesteckt. Verbinde nur die schwarze Leitung GND und rote Leitung 3,3V vom ESP zum Antennemodul, jetzt USB einstecken und beobachten ob und was was heiss wird. Vieleicht machst du das ohne Kondensator, der könnte falsch gepolt sein. Versuche den ESP als AhoyDTU im WLAN zu finden. Wenn das geht ist bis jetzt alles i.O. Wenn nein Antennenmodul defekt.
5. Schritt: Kondensator richtig rum anlöten. Was ist nun i.O. oder n.i.O. (lag der Fehler an dir oder am Kondensator)
6. Schritt: die restlichen 6 Leitungen verbinden und schauen ob jetzt  i.O. oder n.i.O.

Vieleicht auch hier mal ein Bild vom angelöteten Kondensator posten, das - (minus) am Kondensator sollte zu sehen sein.
Viel Erfolg

**Comment by knickohr** [comment]
Punkt 1 :  Wenn’s mal qualmt isses IMMER kaputt. Es qualmt meißt such nur einmal 💥

 Punkt 4 und 5 :  Wenn der Kondensaor mal falsch herum war ist er entweder schon explodiert 💥 oder aber zumindest so arg angeschlagen das ich ihn nicht mehr verwenden würde. Denn über kurz oder lang mach er sich von dannen und reißt womöglich noch was (neues) mit.

**Comment by Loetnase** [comment]
Fehler zu suchen, finden und verstehen ist immer lehrreich.
Denn "aus Fehlern wird man klug, drum ist einer nicht genug".
Aus dem Schrott kann auf jeden Fall noch etwas gelernt werden.
Ich denke, du hast da wie ich auch schon viel gelernt :joy:
Du hast aber recht, angerauchte und "madige" Teile ghören erneuert.
