### ISSUE TITLE
[ESP8266] MQTT Home Assistant Auto Discovery mit 2 Invertern klappt nicht

### ISSUE THREAD

**Issue by ottelo9** [lumapu/ahoy#794]
### Platform

ESP8266

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

board

## Connection diagram I used:
-

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.104

### Github Hash

25695fc

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: -
    - Name: HM800-Schuppen
#### Inverter 1
    - Address: -
    - Name: HM800-Carport
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: meine Home Assistant IP
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: HM800

### Error description

Ich verwende Home Assistant 2023.3.5 mit Mosquitto broker 6.1.3 und der Integration Mosquitto broker. Bisher habe ich mit Ahoy einen Inverter HM-800 ausgelesen und via MQTT an HA gesendet ohne Probleme! Nun habe ich einen zweiten HM-800 eingebunden. Beide werden von Ahoy gefunden und korrekt ausgelesen. Nur leider wird der zweite nie in dem Moquitto Broker dargestellt. Daraufhin habe ich Ahoy auf Werkseinstellung zurück gesetzt und alles neu eingegeben ... ohne Erfolg. Die Broker Integration in HA gelöscht, HA neugestartet und dann neu hinzugefügt -> findet Ahoy nun garnicht mehr automatisch. Erst wenn ich auf den Ahoy Button "Discovery Config (homeassistant)" klicke, wird der erste Inverter in HA gefunden. Mit dem inoffiziellen Addon MQTT Explorer in HA werden aber beide Inverter angezeigt. Scheint also ein Problem mit dem Auto Discover zu geben?

![image](https://user-images.githubusercontent.com/33122175/226574349-cd678b50-0d52-4dd2-90d1-aec5b8708a88.png)

**Comment by ottelo9** [comment]
Ein anderer Nutzer aus Discord hat auch bestätigt, dass die Auto Discovery Message nur den ersten Inverter beinhaltet.

**Comment by ottelo9** [comment]
Aktuell verwende ich den Workaround aus dem Discord Chat Kanal #home-assistant. Da muss man zum Anfang gehen und die dort veröffentlichte yaml config Datei in config\packages\ einfügen und anpassen. Dann hat man beide Inverter manuell hinzugefügt, LEIDER ABER lose ohne die passenden zwei Devices (Inverter) als "Gruppe" wo die Entities untergeordnet sind.

Hier meine angepasste yaml:
[ahoy.yaml.txt](https://github.com/lumapu/ahoy/files/11033247/ahoy.yaml.txt)

**Comment by lumapu** [comment]
finde eigenartig, dass es wieder 'kaputt' sein soll. Ein Inverter geht, ab dem zweiten hakts?

**Comment by ottelo9** [comment]
In welcher Version ging es denn mal? Die würde ich ja dann nehmen :). Ich habe auch mal testweise alle Inverter aus Ahoy rausgeschmissen und dann neu hinzugefügt. Der Fehler bleibt aber. Nur der erste Inverter wird in HA angezeigt.

**Comment by lumapu** [comment]
Habe gerade das changelog nochmal gelesen, daher an Version 0.5.79.
Sollte sich meiner Meinung nach aber auch nicht wieder verschlechtert haben.

https://github.com/lumapu/ahoy/blob/development03/src/CHANGES.md

Edit:
Evtl. ist es das gleiche Problem wie in #632 beschrieben

**Comment by ottelo9** [comment]
Kann gut sein. Ich kann ja mal "irgendwie" die Discovery Message abhorchen, wenn ich in Ahoy auf den Button klicken. Wie kann man das am besten machen? 

- Mosquitto broker ?
- MQTT Explorer?
- ?

**Comment by KG3RK3N** [comment]
@ottelo9 
Ich nutze dafür in der Regel [MQTT Explorer](http://mqtt-explorer.com/)
Das müsste dann in etwa so aussehen damit es von HA erkannt wird:
![image](https://user-images.githubusercontent.com/16717995/227598457-b9bf6312-7426-4c71-87d1-aef16ba1a0bd.png)
![image](https://user-images.githubusercontent.com/16717995/227598122-0b1b7483-a80d-495d-882e-5828f52951ad.png)

Wichtig ist, das unter dem Topic "homeassistant" die Configs gepublished werden wie in den beiden Bildern zu sehen, damit HA das dann auch erkennt. Dort sind dann die Konfigurationen der einzelnen Sensoren enthalten, damit HA dann weiß worauf er horchen muss um Werte zu bekommen. 
In deinem Bild aus dem initialen Kommentar sind nur die Werte von ahoy selbst zu sehen aber nicht die für HA

**Comment by ottelo9** [comment]
@lumapu Danke für den Fix! Habe V0.5.109 direkt mal raufgeschoben. Es tauchen nun beide WR + AHOY-DTU_TOTAL auf. Werde morgen berichten, wenn die Sonne wieder scheint und die Werte übertragen werden.

PS
Läuft alles einwandfrei! DANKE FÜR DEN FIX !!!!!!!!
