### ISSUE TITLE
Feature Request: Configure offset to YieldTotal MQTT value

### ISSUE THREAD

**Issue by fesc2000** [lumapu/ahoy#795]
I just replaced my old inverter with a new one. Now obviously my total yield starts from zero, so it would be nice to have a config option where i could use the previous YieldTotal as baseline for the new one (when sent via to MQTT).

Vice versa, considering that a used inverter starts with a non-zero value it would be good to be able to adjust it back to zero (assuming that it's not possible to (re)set the counter .. or is it?).

**Comment by Argafal** [comment]
I believe what you are suggesting already exists. Maybe it wasn't part of 0.5.66 yet, then it will be part of the next release. In the development snapshots you can find a setting called _Yield Total Correction [kWh]_ as part of the inverter settings. I think this is what you are looking for! :)

**Comment by fesc2000** [comment]
Ah, yes, thanks!
