### ISSUE TITLE
Geräte- / Device-Name in title der Seite ausgeben

### ISSUE THREAD

**Issue by nhet** [lumapu/ahoy#797]
In meinem Netzwerk arbeite ich statt DNS Namen lediglich mit IP-Adressen. Somit ist das "schnelle" Aufrufen von Systemen nur durch die Eingabe der IP-Adresse möglich. 
Ich möchte, dass der vergebene DeviceName im Title der Seiten mit ausgegeben wird, da Chrome sich den html-Title von Seiten merkt und zieht diese ggf. zur Schnellvorauswahl heran. Somit brauche ich nicht die IP eingeben, sondern kann wieder den DeviceNamen benutzen.

**Comment by dknubben** [comment]
Wenn Du in Deinem Netzwerk arbeitest, dann wäre ein eigener DNS-Server/Forwarder, z.B. auch Unbound die bessere Lösung. Jeder aktuelle Router bietet das an. AhoyDTU muss das nicht leisten.

**Comment by lumapu** [comment]
es ist in Ahoy auch nicht ohne weiteres möglich durch die aktuelle Struktur wie die Webseiten ausgeliefert werden
