### ISSUE TITLE
ESP32/ Problem nach dem Flaschen

### ISSUE THREAD

**Issue by mavrs77** [lumapu/ahoy#798]
### Platform

ESP32

### Antenna

circuit board

### Power Stabilization

~100uF Elko

### Connection diagram

Hallo, nach Flaschen wird falsche Seite angezeigt.
![ggggg](https://user-images.githubusercontent.com/122673169/227392242-ca871c2c-5a19-498d-8272-19b7e4f7fcf2.jpg)
was mache ich falsch?

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.5.66

### Github Hash

5402g43

### Build & Flash Method

ESP Tools (flash)

### Desktop

Windows

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 1141752123456
    - Name: HM-600
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 375, 375
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS: D8 (GPIO15)
    - CE: D4 (GPIO2)
    - IRQ: D3 (GPIO0)
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [x]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Debug Serial Log output

```shell
[D][wifi:386]: Starting scan...
[D][wifi:401]: Found networks:
[I][wifi:445]: - 'xxx' [redacted]▂▄▆█
[D][wifi:446]:     Channel: 1
[D][wifi:447]:     RSSI: -64 dB
[I][wifi:257]: WiFi Connecting to 'xxx'...
[W][wifi:549]: Error while connecting to network.
[I][wifi:257]: WiFi Connecting to 'xxx'...
[W][wifi_esp32:494]: Event: Disconnected ssid='xxx' bssid=[redacted] reason='Authentication Failed'
[W][wifi_esp32:494]: Event: Disconnected ssid='xxx' bssid=[redacted] reason='Auth Expired'
```

### Error description

1) Go to http://ahoy-dtu/setup
2) configure above settings
3) Reboot
4) I did this
5) I expected that
6) and something completely differen happened

**Comment by lumapu** [comment]
hast du über https://ahoydtu.de/web_install installiert?
