### ISSUE TITLE
Read/Display Firmware Version 

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#803]
Hi, i can´t find any information how to Display or to read the Firmware Version from the Inverter.

**Comment by teletapi** [comment]
Da gibt es ja auch noch nix

**Comment by rmayergfx** [comment]
Wäre schön wenn das implementiert wird. Habe es bei OpenDTU gesehen das es dort verfügbar ist.

**Comment by mtet2** [comment]
So zum Beispiel:
http://ahoy-dtu/api/record/info
Oder die IP von deiner "ahoy-dtu" einsetzen.

**Comment by Ollipop030** [comment]
![grafik](https://user-images.githubusercontent.com/121013633/227544886-420102fd-42b7-40e3-a7e4-3761c8de0014.png)

Der Wert in Klammern ist doch die Firmware?

**Comment by rmayergfx** [comment]
Danke, wusste nicht das der Wert in der Klammer die Firmware des Inverters ist. Die Api gibt aber noch viel mehr aus. 
Leider habe ich das in der Doku nicht gefunden sonst hätte ich hier kein Issue geöffnet. 
Wäre halt schon schön wenn man das auch per mqtt bzw im Webinterface in einer eigenen Rubrik direkt sehen könnte.

Würde sich doch Prima anbieten im Bereich System einen Punkt Inverter mit in die Oberfläche zu integrieren und dort die Daten aus der Api zu hinterlegen, Firmwareversion mit Datum z.B.

**Comment by lumapu** [comment]
per MQTT wird es bereits übertragen:

![grafik](https://user-images.githubusercontent.com/22733082/227667607-ab26ba53-9e33-42d7-8431-0d8ecfb461e6.png)

**Comment by rmayergfx** [comment]
Ich habe es in HA (Docker Synology mit Eclipse Mosquitto) eingebunden. Dort hat er keine der von dir gezeigten Entitäten gefunden oder eingebunden, auch der MQTT Explorer http://mqtt-explorer.com/ zeigt keine dieser Werte an. Ist allerdings auch ein TSUN TSOL-M800 FW 10010.00  mit der http://ipinverter/api/record/info zeigt er jedoch alle diese Werte an.

Habe schon verschiedene FW Versionen für ESP32 ausprobiert, auch wegen Display Anschluss, gestartet mit stable v0.5.66 über Webinstaller bis hoch zu 0.5.105, sehe die Werte in MQTT nicht.

Ein parallel dazu neu aufgesetzter ESP8266 Wemos D1 mini zeigt dies auch nicht an.

Es fehlen im MQTT alle Zeilen mit FW* und HWPartId

Kann es damit zusammenhängen das ich die Settings im MQTT abgeändert habe? Statt inverter steht hier bei mir nur M800?
Ok, die letzte Frage habe ich mir gerade selbst beantwortet, indem ich den ESP8266 (Testsystem) einfach mal auf die Defaultwerte zurückgesetzt habe und als MQTT wieder "inverter" drinsteht. Keine Änderund. Die Daten fehlen im MQTT nach wie vor, ich bekomme laut MQTT Explorer vom Inverter 50 Topics.

So, gerade die 0.5.106 eingespielt da dort ja laut Changelog: 
*fixed MQTT autodiscover #794, #632

und siehe da, nun sind die Werte im MQTT Explorer auch mit dem TSUN TSOL-M800 auch sichtbar.

THX

So, leider ist nach einem reboot des ESP32 mit FW v0.5.106 wieder das Problem vorhanden, das die Firmware im MQTT nicht mehr sichtbar ist ???? Zudem hat das System nun ein zusätzliches Gerät "AHOY_DTU_DF7C" angelegt das auf der gleichen IP liegt... Sehr seltsam.

**Comment by lumapu** [comment]
Es gibt zwei verschiedene MQTT Pfade, einmal das was du hier nennst und per `Autodiscover` angelegt wird und einmal die live Daten aus dem Wechselrichter. 
Unter den Live-Daten des Wechselrichters befindet sich auch die FW-Version
