### ISSUE TITLE
Fehler beim Kompilieren des ESP8266 Programms in der Arduino IDE

### ISSUE THREAD

**Issue by ocxjuergen** [lumapu/ahoy#81]
Hallo, 
Bekomme beim Kompilieren diesen Fehler in der Arduino IDE
Habe den Ordner ganz normal Runtergeladen, entpackt, alle Libraries installiert.

"conversion from 'const __FlashStringHelper*' to 'const StringSumHelper' is ambiguous"

ist in der app.cpp ganz unten

Liegt Hier das Problem bei mir oder ist hier etwas anderes?

Danke

**Comment by stefan123t** [comment]
Hallo @ocxjuergen,
ich vermute mal Du hast noch nicht das richtige Board "ESP8266" Wemos D1 o.a. im Tools Menü konfiguriert.
Die FlashStringHelper sind ein Macro, das m.W. Bestandteil von Arduino/ESP8266 ist und daher bei Auswahl des richtigen Boards vorhanden sein sollte.
Hast Du die URL für den ESP8266 unter dem Board Manager eingetragen und die Arduino IDE evtl. neu gestartet ?

Hier die Anleitung von https://github.com/esp8266/Arduino:

**Installing with Boards Manager**
Starting with 1.6.4, Arduino allows installation of third-party platform packages using Boards Manager. We have packages available for Windows, Mac OS, and Linux (32 and 64 bit).

* Install the current upstream Arduino IDE at the 1.8.9 level or later. The current version is on the [Arduino website](https://www.arduino.cc/en/software).
* Start Arduino and open the Preferences window.
* Enter `https://arduino.esp8266.com/stable/package_esp8266com_index.json` into the *File>Preferences>Additional Boards Manager URLs* field of the Arduino IDE. You can add multiple URLs, separating them with commas.
* Open Boards Manager from Tools > Board menu and install *esp8266* platform (**and don't forget to select your ESP8266 board from Tools > Board menu after installation**).

**Latest release Latest release**
Boards manager link: `https://arduino.esp8266.com/stable/package_esp8266com_index.json`
Documentation: https://arduino-esp8266.readthedocs.io/en/3.0.2/

**Comment by ocxjuergen** [comment]
Hallo Stefan,

Boards sind eigentlich alle Installiert, trotzdem Vielen Dank für die tolle Anleitung. Hab beim Kompilieren ja wie laut Anleitung das „Generic 8266 Module“ ausgewählt sowie auch die speichergröße vom Flash. Hmmm werde es einfach nochmal mit einen anderen Board(z.B Wemos D1) probieren und dann kompilieren und schauen was passiert.

**Comment by stefan123t** [comment]
Hallo Jürgen, ich verwende bei mir ein NodeMCU v1.0 Board mit ESP8266-12E/F chip.  
Den Wemos D1 habe ich immer noch nicht ausprobiert aber zumindest schon mal die Pin-Header drangelötet.
Kannst Du ggf ein Logfile anhängen mit etwas mehr Kontext Deiner Fehlermeldung ?

**Comment by ocxjuergen** [comment]
Hallo Stefan, Okay werde mal mit den NodeMCU Board probieren.

Anbei das Logfile: (für Pastebin zu groß)

https://zerobin.net/?7784faab35de51ad#/QIlaV9wD/mVrGFNzKBdIHbCVxexIpQd80m2eB/J5oc=

**Comment by ocxjuergen** [comment]
Hallo Stefan,
jetzt lässt sich es  kompilieren - habe zusätzlich noch die ESP32 Boards runtergeladen. Laut Arduino Forum (finde den Link leider nicht mehr) gibt es irgendwie Probleme mit den SSL Files zwischen der ESP8266 2.7.4 Version und der 3.0.2 - bei der neueren Fehlen eben die SSL Files - die jedoch wiederrum bei den ESP32 Boards dabei sind. =)

Trotzdem Danke für die Hilfe!
LG

**Comment by stefan123t** [comment]
Ich glaube ich habe den Artikel gefunden:
https://forum.arduino.cc/t/f-question-syntax/271595/3
Wir sollten also den Code optimieren und String() concatenation / casts vermeiden.

**Comment by billy0xff** [comment]
@ocxjuergen: wie hast du denn das genau gemacht, bei mir funktioniert das ebenfalls nicht.
Ausserdem meckert er bei #include "version.h"   in main.cpp
Hast Du ein Kompilat das du weitermailen magst (mit unveränderten Quelltexten) ?
Danke für die Hilfe! LG

**Comment by ocxjuergen** [comment]
@billy0xff habe die esp8266 v3.0.2 upgedatet, danach die esp32 boards runter geladen, danach ist es bei mir ganz normal zum kompilieren gegangen… was schreibt er dir den für einen Fehler beim Kompilieren? Ja klar, kann dir gerne die Files schicken!

**Comment by billy0xff** [comment]
@ocxjuergen: danke, jetzt hat es geklappt, ich hatte nicht die esp8266 boards auf 3.0.2 aktualisiert gehabt.

**Comment by DanielR92** [comment]
Super das alles geklappt hat, wen möglich dann diesen Thread schließen.
