### ISSUE TITLE
Vorschlag zur Suche in Issues: Issue Template reduzieren, bzw.nicht alle Buzzwords schon im Template erwähnen!

### ISSUE THREAD

**Issue by GallusMax** [lumapu/ahoy#822]
Die Suche nach relevanten Issues - dringend empfohlen, bevor ein eigenes angelegt wird - ist schwierig, wenn ALLE Keywords in ALLEN Issues erscheinen.

Mein Problem: mit der Suchzeile: "is:issue is:open mqtt" erscheinen ausnahmslos ALLE offenen Issues, insbesondere auch die, wo die Vorlage "MQTT: nicht vorhanden" ausgefüllt ist.

Ich weiß, es gibt sehr gute Gründe, ein ausfühliches Template vorzuhalten. Ich gebe aber hier zu bedenken, daß diese Methode die Suche schwierig bis unbrauchbar macht.

Lösung: vielleicht nur die jeweils relevanten Abschnitte des Templates ausfüllen, den Rest wegwerfen?
Ansprechpartner: alle Issueautoren (klingt nach Disziplin?) Seufz.

(Ich lasse das Template hier mal stehen, dieser Hinweis wird also auch unter allen denkbaren Suchen auftauchen..)
## Hardware
  * [ ] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ ] external antenna

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Connection diagram:
* [ ] Image of the your wiring attached

### Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

## Software
* [ ] AhoyDTU
* [ ] OpenDTU

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] Arduino
* [ ] ESP Tools
* [ ] Platform IO

### Desktop OS:
* [ ] Linux
* [ ] Windows
* [ ] Mac OS

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by lumapu** [comment]
guter Input, müssen wir tatsächlich drüber nachdenken, ich brauche die Suche täglich, hab jedoch noch nie ein template Parameter gefunden

**Comment by rmayergfx** [comment]
Schau dir doch mal die Beta mit Issue Forms an: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
Anleitung und Ansicht:
https://youtu.be/MvyGcLg6AvI?t=226

Damit kann man per Dropdown wunderbar rausfiltern.
