### ISSUE TITLE
Device information MQTT "von Hoymiles"

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#825]
Where does HA get the information "from Hoymiles" via MQTT? I have a TSUN inverter here and it is a bit irritating.
Is this fixed in the firmware?

**Comment by rejoe2** [comment]
Don't really understand the question, but if your TSUN is a 2nd gen. Device (serian nr. 10x1), recent AhoyDTU firmware (0.6.0) should be able to request the informations this type provides. Pls. note: 2nd gen. Devices provide less information than newer models.

Apart from that: Please provide more info.

**Comment by rmayergfx** [comment]
What kind of informationdo you need? Synology Docker with installed acutal HA and Eclipse Mosquito also as Docker. Nothing else.Enabled MQTT in HA and AhoyDTU, device was recognized and when you click on the MQTT Devices you will see all devices detected by the system. There is the MQTT name given in AhoyDT with underlined information "from Hoymiles". This can´t be changed, so this information was deployed by AhoyDTU i think. I never did write anywhere Hoymiles, because i have a TSUN.

**Comment by rejoe2** [comment]
OK, so you are just taking about the info displayed within HomeAssistant. 
Can't help further, I'm using FHEM as automation sofrware, but I'd recommend to rename your "issue" to make your point more clear. 

Additional remark: AhoyDTU (or OpenDTU) just treat all the inverters the same way and only distinguish between the protocol they use (or in the future: perhaps the RF transceiver type). Internally they are all "hoymiles".

**Comment by beegee3** [comment]
yes, the manufacturer ("mf") in the JSON sent to HA via MQTT is hardcoded as "Hoymiles".

**Comment by rmayergfx** [comment]
that is the information i needed. is there an option to change this? Will HA recognize or ist "mf" just a free variable we can change? Maybe this can be done on webgui to select betwenn TSUN and Hoymiles, according to the topic. Default topic is "inverter" this can be changed any time by the user, why not the manufacturer?

**Comment by beegee3** [comment]
as far as I know HA needs the "mf" information. Since most users have Hoymiles inverters it's hardcoded.
I don't know if there's much interest in changing that. But this is a question for @lumapu. It may be that the manufacturer can be deduced from the serial number.

**Comment by lumapu** [comment]
using the serial number will be the approach I would choose.
This feature has no priority for me, if you need it on a short term don't hesitate to publish a pull request
