### ISSUE TITLE
[ESP8266] 0.6.0 "Live" Ansicht mit MI-1200

### ISSUE THREAD

**Issue by AsZork** [lumapu/ahoy#829]
## Hardware
   [* ] ESP8266
## Software
 [* ] AhoyDTU
### Version / Git SHA: 
Version: 0.6.0

### Build & Flash Method:
 [*] Platform IO
mit OTA eingespielt

### Desktop OS:
 [*] Windows

Habe mal die aktuelle Software mit meinem alten MI-1200 getestet. Sehr schöne Arbeit.

Hardware Info Wechselrichter
MI-1200   FWVersion: 242 BuildYear: 2019 MonatTag: 328 HWPartID: 33

Mir sind folgende Punkte aufgefallen.
1. Auf der Live Seite werden die Summen nicht berechnet.
![grafik](https://user-images.githubusercontent.com/39065525/228489089-b47a1f9d-76de-4465-bf6c-e1ed837d2963.png)

2. Auf der Übersichtseite wird der Wechselrichter als nicht produzierend geführt.
![grafik](https://user-images.githubusercontent.com/39065525/228489544-b2789e6c-0566-422b-ae88-344da9a8536e.png)

**Comment by rejoe2** [comment]
Ahhh, ein 4ch-MI! Cool...

Das Problem bzw. dessen Lösung ist seit vorhin klar. Bist du auf discord? Da gäbe es aktualisierte .bin zum weiteren Testen.
