### ISSUE TITLE
Ahoy limitation with Home Assistant

### ISSUE THREAD

**Issue by Deny11Matrix** [lumapu/ahoy#831]
Right now I'm using this project with an ESP8266 where I read, through the home assistant, the inverter data .... and so far everything is great; now I would like to create an automation with home assistant that allows me to limit the output power... but I'm not understanding how to do it... can some of you kindly post me an example of code?

A thousand thanks :)

**Comment by rmayergfx** [comment]
Hello @Deny11Matrix,
so AhoyDTU is up and running fine. congrats. For support HA you need to change to 
https://community.home-assistant.io/
there you can search, find and add an issue if necessary.

You should start here: https://www.home-assistant.io/docs/automation/

_**This forum should be only related to bugs and issues with AhouyDTU and not any other 3D party software.**_
