### ISSUE TITLE
[ESP8266] No data from inverter due to corrupted LED pin settings

### ISSUE THREAD

**Issue by tastendruecker123** [lumapu/ahoy#832]
### Platform

ESP8266

### Model name

NodeMCU

### nRF24L01+ Module

nRF24L01+ plus

### Version

0.6.0

### Github Hash

9c7d7a0

(removed unnecessary template info)

### Error description

I haven't been able to reproduce it reliably yet, but I have run into this problem several times over the past days.

Ahoy works as expected if I input all the settings in one go and save them. When making small changes to the settings several times, at some point the values for the LED pins were changed from '255' to '0'. It's possible that part of the settings page hadn't loaded properly (see issue #828).

Because '0' refers to pin D0, and D0 is the default IRQ pin, Ahoy was using the IRQ pin as a LED output at the same time, which means it was unable to receive any inverter data.

I did not change the LED pins manually and I never touched any of the pin settings at all because my setup uses the default wiring scheme. I suspect that Ahoy defaults to '0' when there's no valid data submitted for the LED pins, which breaks the NRF pin configurations.

I would suggest making sure that the two LED pin settings always default to 255, and perhaps add a check to make sure that the LED pins do not conflict with the NRF pins.

I'm mainly submitting this bug in case someone else runs into it as well. It's no big deal if you know about it and you can simply change the LED pins, but it's quite tricky to find if you don't and the inverter just stops communicating all of a sudden.

**Comment by Joh49** [comment]
the workaround I performed at version 0.6.0 was to change in the setup - display config: 
the pin configuration clock and data to off (default) 
and it worked as before

**Comment by Joh49** [comment]
this may be only applicable at the 1.3" SH1106 display
