### ISSUE TITLE
[ESP32] Update 0.5.100 -> 0.6.0 nrf2401 wird nicht mehr gefunden

### ISSUE THREAD

**Issue by novegit** [lumapu/ahoy#838]
### Platform

ESP32

### Antenna

external antenna

### Power Stabilization

~100uF Elko

### Connection diagram

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.0

### Github Hash

bb5cb8b

### Build & Flash Method

ESP Tools (flash)

### Desktop

Mac OS

### Device Host Name
    - Device Name: AHOY-DTU
### WiFi
    - SSID: YOUR_WIFI_SSID *don't paste here*
    - Password: YOUR_WIFI_PWD *don't paste here*
#### Inverter 0
    - Address: 114175123456789
    - Name: HM-1500
    - Active Power Limit: 65535
    - Active Power Limit Control Type: no powerlimit
    - Max Module Power (Wp): 400, 400, 400, 400
    - Module Name: link, rech
### General
    - Interval [s]: 30
    - Max retries per Payload: 5
### NTP Server
    - NTP Server / IP: pool.ntp.org
    - NTP Port: 123
### MQTT
    - Broker / Server IP: 
    - Port: 1883
    - Username (optional): 
    - Password (optional): 
    - Topic: inverter
#### Pinout (Wemos)
    - CS:  GPIO5
    - CE:  GPIO4
    - IRQ: GPIO16
#### Radio (NRF24L01+)
    - Amplifier Power Level: LOW
#### Serial Console
    - print inverter data: [x]
    - Serial Debug: [ ]
    - Interval [s]: 5

- Reboot device after successful save: [x]
- SAVE

### Error description

habe von 0.5.100 (alles lief perfekt) auf 0.6.0 geupdated.
Auf der Startseite stand, daß nrf2401 nicht gefunden wurde.
zurück auf 0.5.100  geflasht - keine Fehlermeldung mehr

Meine Verkabelung folgt der ahoy esp32 Dokumentation, ohne Änderungen.

**Comment by beegee3** [comment]
das Pinout im Setup -> System Config wurde erweitert. Setze MISO=19, MOSI=23, SCLK=18 dann sollte wieder alles funktionieren, s. https://github.com/lumapu/ahoy/blob/main/Getting_Started.md

**Comment by markusdd** [comment]
genau. liegt einfach dran, dass die SPI Pins jetzt einstellbar sind um exotischere ESP32 Boards und die neuen ESP32S3/C3 zu unterstützen, wo das SPI nicht mehr fix ist.

@lumapu vllt. solltest du in den Release notes mal noch nen fetten Kommentar dazu machen, sonst kriegen wir hier noch viele solcher Tickets.

**Comment by novegit** [comment]
vielen Dank, mit setzen von MISO=19, MOSI=23, SCLK=18  funktionierts.

**Comment by rmayergfx** [comment]
Siehe auch https://github.com/lumapu/ahoy/issues/812
 Warning, do not update to dev release 0.5.108 or greater if you don´t have the pinout on your desk #812 
Habe ich nicht ohne Grund geschrieben.
Mein Vorschlag war die Default Werte anzuzeigen oder als Voreinstellung zu nehmen, zumindest für "Standard" ESP32 Boards.
