### ISSUE TITLE
REST API view broken on chrome based browsers -- Firefox 111.0.1 still working

### ISSUE THREAD

**Issue by rmayergfx** [lumapu/ahoy#840]
REST API view on chrome based browsers is broken. only textlines are viewed. This happens on actual versions of Chrome and Edge.

Firefox view still working.

![grafik](https://user-images.githubusercontent.com/105392164/229073353-ad94c5b4-cd18-4f04-8eaa-e520183ab51d.png)

**Comment by lumapu** [comment]
This must be a change from the browsers side. We didn't changed anything. The basic REST API URL `/api` reports a valid JSON.

**Comment by rmayergfx** [comment]
Just a short update. If anyone uses Chrome and need a good solution to view the REST API agin, install from the chrome webstore the addon JSON Formatter from callumlocke.com
https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?
