### ISSUE TITLE
Frage: Umgang mit Problemen in lib_deps

### ISSUE THREAD

**Issue by fsck-block** [lumapu/ahoy#841]
Hallo Lukas

Ahoy benutzt ESP Async Webserver aus dem Repository "yubox-node-org/ESPAsyncWebServer".
Aus meiner Sicht gibt's da Probleme (siehe #834) und die können nur im Aysync Webserver behoben werden. Allerdings sieht das o.g. Repository jetzt nicht wirklich aktiv gepflegt aus, das zugehörige Master Repository auch nicht.

Hast du eine Idee wie man mit solch' einer Thematik am besten umgeht?

**Comment by lumapu** [comment]
die einizige Idee, die ich aktuell habe wäre das Repository zu forken und die Änderung im Fork zu machen.
Ist die Änderung denn kompatibel mit allem bishierigen? Warum braucht der AsyncWebserver das Alignment auf 4 Bytes?

**Comment by ksjh** [comment]
Ich habe gerade mal versucht, für einen ESP32C3 zu bauen und bin auch auf Probleme mit dem besagten ESPAsyncWebServer gestoßen. Wie wäre es denn, wenn man auf einen anderen Fork, der aktiver gepflegt wird, umsteigen würde? Ich habe mal mit dem Repo "esphome/ESPAsyncWebServer" herumprobiert, aber ganz unproblematisch ist das auch nicht, ich bin noch am experimentieren damit. Das letzte Update dort war vor zwei Wochen, und esphome an sich ist ja ein aktives Projekt. Wie offen die dort für commits/pull requests von außen, die nicht direkt mit esphome zu tun haben, weiß ich aber auch nicht.

**Comment by ksjh** [comment]
Der offene Pull Request #11 beim "esphome/ESPAsyncWebServer" ist natürlich ein Show Stopper. Mir ist unverständlich, warum der offensichtliche einfache Typo beim letzten Update nicht gleich mit gefixt wurde. Aber mit dem Fix baut ahoy zumindest ohne Probleme ein Binary für den ESP32C3. Getestet habe ich das resultierende Binary aber noch nicht. Zum Testen kann man vorerst einfach https://github.com/CRSLEE/ESPAsyncWebServer#patch-1 verwenden, von da ist der besagte Pull Request.

**Comment by fsck-block** [comment]
Wenn ich es richtig gesehen habe, haben sich beide aus me-no-dev/ESPAsyncWebserver entwickelt. Aber leider mit unterschiedlichen Änderungen.

![esphome_ESPAsyncWebServer](https://user-images.githubusercontent.com/58307481/229339843-37fa929a-c437-4971-8a21-b22df86a8962.png)

![yubox-node-org_ESPAsyncWebServer](https://user-images.githubusercontent.com/58307481/229339844-94e26b8d-e3e9-4106-90fe-81b243bbd5b9.png)


Wenn wir den esphome/AsyncWebserver out of the box nehmen wissen wir nicht was wir alles von den 94 commit aus yubox-node-org/AsyncWebserver verlieren.

**Comment by ksjh** [comment]
Das ist natürlich völlig richtig, und leider kann ich dazu (noch) wenig sagen, da ich gestern ahoy zum ersten mal angesehen habe. Ich habe auch keine Ahnung, wie viele der 94 commits hier relevant oder zumindest sinnvoll sind. Andererseits habe ich vorher mit ESPHome, wo dieser Fork eingesetzt wird, ein paar Erfahrungen gesammelt und habe zumindest keine offensichtlichen Probleme entdeckt. Ich habe zumindest mit dem ESPHome-Fork für alle von ahoy unterstützen Plattformen (plus ESP32-C3) problemlos Binaries bauen können. Aber, klar, das müsste man auf jeden Fall im Detail genau ansehen und testen, bevor man sich evtl. für einen Wechsel entscheidet.

**Comment by lumapu** [comment]
vor wenigen Wochen habe ich das ganze Thema per patch gelöst. Wenn es wieder oder weiter Probleme gibt dann öffnet einfach einen neuen Issue.
In der letzten Release ist es bereits enthalten (`0.7.36`)
