### ISSUE TITLE
0.6.2 ACHTUNG!! Es kann nur noch die Seite /live angezeigt werden

### ISSUE THREAD

**Issue by HFarryranz** [lumapu/ahoy#852]
### Platform

ESP8266

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

board

## Connection diagram I used:
| nRF24L01+ Pin | ESP8266 GPIO   |
| ------------- | -------------- |
| Pin 1 GND [*] | GND            |
| Pin 2 +3.3V   | +3.3V          |
| Pin 3 CE      | GPIO2  CE   D4 |
| Pin 4 CSN     | GPIO15 CS   D8 |
| Pin 5 SCK     | GPIO14 SCLK D5 |
| Pin 6 MOSI    | GPIO13 MOSI D7 |
| Pin 7 MISO    | GPIO12 MISO D6 |
| Pin 8 IRQ     | GPIO0  IRQ  D3 |

| nRF24L01+ Pin | ESP32 GPIO      |
| ------------- | --------------- |
| Pin 1 GND [*] | GND             |
| Pin 2 +3.3V   | +3.3V           |
| Pin 3 CE      | GPIO4  CE   D4  |
| Pin 4 CSN     | GPIO5  CS   D5  |
| Pin 5 SCK     | GPIO18 SCLK D18 |
| Pin 6 MOSI    | GPIO23 MOSI D23 |
| Pin 7 MISO    | GPIO19 MISO D19 |
| Pin 8 IRQ     | GPIO0  IRQ  D0  |

Note: [*] GND Pin 1 has a square mark on the nRF24L01+ module

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.2

### Github Hash

6533143

### Build & Flash Method

ESP Tools (flash)

### Desktop

Linux

### Setup

-

### Debug Serial Log output

```shell
-
```

### Error description

nach dem Update funktionieren nur doch die Seiten /live  /api /about

**Comment by tastendruecker123** [comment]
Workaround: manuell /login aufrufen und mit leerem Passwort einloggen.

**Comment by beegee3** [comment]
@tastendruecker123 👍 
@lumapu : das war wohl zu viel des guten. die Login Seite poppt nicht automatisch auf. Und standardmäßig ist in den Protection Settings bis auf Live alles angehakt. Egal, welche Haken man entfernt, wenn kein Admin Passwort vergeben ist, kann man das nicht abspeichern, beim Reboot sind die Haken wieder gesetzt. War bisher ohne Wirkung. Mit 0.6.2 kommt es zu dem von @HFarryranz beschriebenem Problem.

**Comment by lumapu** [comment]
oh je, da fehlt eine Prüfung, ob das Passwort überhaupt gesetzt wurde. Ich werde es in laufe des Tages fixen

**Comment by beegee3** [comment]
@lumapu hab nachgeschaut: in `settings.h` `jsonWifi` steht
```
                if(mCfg.sys.protectionMask == 0)
                    mCfg.sys.protectionMask = DEF_PROT_INDEX | DEF_PROT_LIVE | DEF_PROT_SERIAL | DEF_PROT_SETUP
                                            | DEF_PROT_UPDATE | DEF_PROT_SYSTEM | DEF_PROT_API | DEF_PROT_MQTT;
```
Danach wird, wenn alle Haken entfernt werden, der Default wie bei `loadDefaults` gesetzt. Das sollte nur geschehen, wenn auch ein Admin Passwort vergeben ist. Ohne Passwort hat man keinen LOGIN Button und muss http://ahoy-dtu/login bemühen. Die Passwort Prüfung braucht man also hier und in der neuen `web.h` Funktion `isProtected`.

**Comment by lumapu** [comment]
@beegee3 ich finde es keinen Schaden, wenn die Haken per Default gesetzt sind - wenn kein Passwort gesetzt wurde, dann sind auch die Haken egal. Daher baue ich in `0.6.3` nur die Prüfung in `isProtected(..)` ein

**Comment by beegee3** [comment]
@lumapu ist schon richtig, aber wenn man kein Passwort gesetzt hat und die Haken entfernt wurden, wird das auch so abgespeichert (in ahoy_setup.json steht "prot_mask": 0). Sollte das nicht auch nach einem Reboot wieder hergestellt werden? Warum das Default Setting?

**Comment by lumapu** [comment]
die Idee war, dass beim setzten eines Passworts gewisse Seiten schon gesperrt sind. Ich denke alles bis auf `live` zu sperren ist auch der normale Use-case. Wir können aber gerne noch bisschen über eure Vorlieben disktieren und diese dann in eine der nächsten Versionen integrieren.
Ich denke, das wurde auch eingeführt während die Settings teilweise bei den Leuten schon im JSON standen. Daher war es in den dev Verisonen uU. nötig hier den Default nochmal zu erzwingen.

**Comment by beegee3** [comment]
Letztlich ist es egal. Es könnte nur den ein oder anderen User verwirren, der kein Passwort setzt, die Häkchen entfernt und sie nachher doch wieder sieht.
