### ISSUE TITLE
Ahoy DTU seems to crash (reboot) if i connect to webif from mobile device

### ISSUE THREAD

**Issue by x23piracy** [lumapu/ahoy#863]
## Hardware
  * [X] ESP8266

Modelname: Wemos D1 Mini

### nRF24L01+ Module
* [X] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [X] external antenna (SMA)

### Power Stabilization:
* [X]  220uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module

### Version / Git SHA: 
Version: 0.6.0

### Build & Flash Method:
* [X] AhoyDTU Webinstaller

Hi,

i just build my own Ahoy DTU and everything went smoothly, i build it before i own my own Hoymiles inverter :P
While playing around with the webif i could see that i can bring it easily to a reboot with just connecting to its webif with a mobile browser (iphone with safari or firefox).

When doing this on firefox on my computer this does not happen.
There is no inverter configured currently.

I've read about better stability with esp32 but i would expect that ahoy with wemos d1 mini should at least alive a night without doing nothing :) any idea? 

Best Regards X23

**Comment by tastendruecker123** [comment]
This should be fixed in the newer dev versions starting with 0.6.3.

**Comment by x23piracy** [comment]
Ok but what is it? I have not switched over to the dev version yet which i will do.
Hier scheinen ja doch recht viele deutsch natives zu sein ;-)

**Comment by x23piracy** [comment]
0.6.4 seems to fix it: https://github.com/lumapu/ahoy/issues/828
