### ISSUE TITLE
WLAN nach Unterbrechung bis zum Neustart weg

### ISSUE THREAD

**Issue by z7ths** [lumapu/ahoy#868]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [x] I will attach/upload an Image of my wiring

### Version

0.6.0

### Github Hash

9c7d7a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

- 1 Hoymiles Inverter set
- WLAN with IP and Subnet set (no DNS or Gateway)
- MQTT Broker set
- NTP set
- LAT and LONG set

### Error description

Ich verwende ein TP-LINK WLAN AP der nun mal nicht mehr als eine Woche stabil läuft. 
Daher habe ich ein täglichen Neustart vom WLAN AP konfiguriert. 

Leider ist ab dem Zeitpunk der Ahoy DTU weg bzw. nicht mehr erreichbar. 
Die Erwartung ist dass der WLAN AP mehrere Minuten braucht und der Ahoy DTU daher wieder ein Fallback auf seinen eigenen AP Mode macht? Allerdings erscheint nicht als eigener AP soweit ich gesehen habe.
Erst nachdem die Stromversorgung entfernt und wieder verbunden wird, verbindet sich der Ahoy DTU wieder mit dem WLAN.

Könnte die WLAN Verbindung nach einer Trennung (i.e. AP Neustart) in automatisch wieder aufgebaut werden? 
Der AP Braucht ca. 2 bis 3 Minuten bis er wieder erreichbar ist und es sollte daher mehrere Verbindungsversuche geben.
Ggf. eine Einstellung z.B. Wenn 30 Minuten lang der WLAN AP nicht erreichbar ist dann fallback auf eigenen AP?

**Comment by z7ths** [comment]
![20230405_202423i](https://user-images.githubusercontent.com/85059062/230717510-610e8c4f-5a78-4cfc-8c71-25474b30aba0.jpg)

**Comment by z7ths** [comment]
Habe jetzt mit Discord Hilfe die GIT SHA: d114fd6 :: 0.6.4 installiert und werde es mal damit versuchen.

**Comment by rmayergfx** [comment]
Tipp:
Im Router für AhoyDTU den Haken setzen damit immer die gleiche IP Adresse genutzt wird. TP-Link nach Möglichkeit so konfigurieren, das er nur im 2,4 Ghz Bereich arbeitet.

**Comment by lumapu** [comment]
die aktuelle dev `0.6.4`, wie es @z7ths geschrieben hat löst das Problem nach meiner Ansicht.

**Comment by lumapu** [comment]
duplicate #851

**Comment by z7ths** [comment]
Vielen Dank! Mit 0.6.4 funktioniert es perfekt!
