### ISSUE TITLE
Documentation: Fehlerhaftes Fritzing in der Doku

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#870]
Das Fritzing für den NodeMCU ist fehlerhaft, es fehlt eine Verbindung und ist falsch verdrahtet. Bitte entfernen oder austauschen.

des Weiteren bitte auch nur noch Verdrahtungen mit Elko publizieren.

Außerdem wäre es sinnvoll auch Fritzings und Schaltpläne mit Display anzubieten.

![BFD446B3-F5A8-42B0-91A4-893176CC4689](https://user-images.githubusercontent.com/63048210/230775462-e5e9f8be-e1fc-4e13-a17a-9fd6b5c31ec1.jpeg)
![60DBDB41-FC91-4C9F-8189-C0B6307CD4DE](https://user-images.githubusercontent.com/63048210/230733131-b9e28acf-c3c3-4799-aaa7-33dd1667166a.jpeg)
![EE0519E9-6A92-4E05-81BA-1BB9636E6C2C](https://user-images.githubusercontent.com/63048210/230733135-1ac13a98-a226-4638-8510-1c7f6a91833e.jpeg)
![ED2FE253-9E79-4467-BBD6-D7997B447FE0](https://user-images.githubusercontent.com/63048210/230733138-2b459387-606b-4cab-b98c-89201549ae6c.jpeg)
![81E6B8A1-CED3-4F24-BD04-9719E92A0D77](https://user-images.githubusercontent.com/63048210/230733140-c9a52f69-d228-4631-bffa-df825d0e57bf.jpeg)
![7C8F8E4D-B841-44C7-9BF9-BDF3695DFADB](https://user-images.githubusercontent.com/63048210/230733137-acbd5cd0-ebe2-4e26-a0bd-fe1bf9ab831a.jpeg)

Fritzings mit ohne Display kann ich nachliefern wenn gewünscht.

**Comment by mager33** [comment]
Nett. Kann man irgendwas machen, dass man bei den ESP32 auch die Pinbeschriftung lesen kann?

**Comment by Joh49** [comment]
die gewünschte Schaltung in Word oder eine eigene Datei kopieren dann kann man zoomen

**Comment by rmayergfx** [comment]
Ähm wo genau war da jetzt der Fehler im Fritzing? Bitte doch genau dazuschreiben was und wo es gefehlt hat. Hier sind mehrere Dokus und auch im Wiki liegen Informationen.

Wo ist der Fehler im Fritzing und bei welcher Version ? 30Pin oder 38Pin Variante? Welcher Anschluss fehlt?

Meiner Meinung nach sind da zu viele Elkos in der Schaltung. Statt hier 3x 100 uF zu verbauen genügen hier max. 2 etwas größerere, da es sich um eine parallel Schaltung der Kondensatoren im 3V Bereich handelt. Jeweils einen für die 5V und 3V Schiene und GND, somit ergibt sich für die 3V Schiene Cges=C1+C2

Zudem ist das mit den Kondensatoren so eine Glaubensfrage, Kondensator kann zwar nicht Schaden, es gibt jedoch Berichte das bei einigen Usern die Verdrahtung auch ohne sehr gut funktioniert und sie mit Kondensator keine Änderung feststellen konnten.

Generell sollte man zum Fritzing bei den Displays noch die Größe/Typ in der Grafik mit einfügen und einen großen Warnhinweis denn bei einigen Displays sind vom Hersteller VCC und GND vertauscht !

**Comment by mager33** [comment]
Kein Fehler, nur Pin-Beschriftung des ESP32 eben kaum lesbar. Sehe keinen Sinn in mehr als 100 uF

Am 9. April 2023 15:03:37 MESZ schrieb rmayergfx ***@***.***>:

**Comment by knickohr** [comment]
Na, wenn das kein Fehler ist, bzw. Sogar 2 Fehler. Es fehlt ein Anschluß am NRF-Modul und die Verbindung zum D2 ist falsch, zumindest paßt sie nicht zum Schaltplan.

![66C5C2B7-E767-405D-B6E6-5BE8AEFF4B1C](https://user-images.githubusercontent.com/63048210/230775294-24d96a46-8ca9-4395-8b5d-766c21b43ba1.jpeg)

Und bitte auch mal genau schauen wo „meine“ Kondensatoren angeschlossen sind. Über den 3. am Display läßt sich noch streiten, aber die andern beiden sind NICHT parallel geschaltet !

**Comment by rmayergfx** [comment]
Genau lesen was ich geschrieben habe bzgl. der Kondensatoren!  
Wo hast du diese Grafik gefunden, bitte mal die Quelle angeben!

**Comment by knickohr** [comment]
In der offiziellen Doku hier auf Git :

https://github.com/lumapu/ahoy/blob/main/Getting_Started.md#symbolic-view-1

**Comment by rmayergfx** [comment]
Ah, du meinst Pin8(IRQ) am NRF24L01+

**Comment by Loetnase** [comment]
Vielleicht auch die Farben in Schematic und Symbolic View für die Verbindungen gleich halten.
Z.B. gelbe Verbindung usw. die passen nicht zusammen.
Vieleicht am  NRF24L01+ die angeschlossenen Farben gleich halten wie bei @knickohr seinen fritzings
![grafik](https://user-images.githubusercontent.com/120967249/230781174-d036d164-0a63-4740-891e-ef97a050a4a5.png)

**Comment by knickohr** [comment]
Das olle fehlerhafte Fritzing ist ja immer noch drin 😲
