### ISSUE TITLE
Aktuelle Leistung in Watt per API auslesen

### ISSUE THREAD

**Issue by SteveBaeumer** [lumapu/ahoy#871]
Hallo,

da ich neu hier bin Hofe ich die richtige Seite erwischt zu haben für meine Frage.

ich würde gern die aktuelle Leistung AC die der WR erzeugt aus der DTU auslesen um sie in meinem Smart home zu visualisieren.
Über REST API sehe ich unter http://192.168.178.38/api/record/live die Daten die ich benötige. 
Aktuell: `"fld":"P_AC","unit":"W","val":"31.90"`
Wie kann ich genau diese Daten auslesen.
Über get-Input kann ich die Adresse eintragen, aber welcher Befehl liefert mir die in diesem Beispiel angezeigten 31.9 Watt?
Habe leider nicht wirklich viel Erfahrung in dem ganzen Thema und hoffe daher auf Hilfe.
Hoffe ich konnte mich einigermaßen verständlich ausdrücken.

lieben Dank,
Steve

## Hardware
  * [ x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [ x] external antenna (SMA)

### Power Stabilization:
* [ x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by mager33** [comment]
Das hängt ganz von Deinem Smarthome-System ab, da bist Du hier falsch. Bei HomeAssistant geht es über MQTT inkl. Autodiscovery. MQTT und REST sollte überall gehen.

**Comment by SteveBaeumer** [comment]
Danke,
genau da habe ich ja mein Problem. 
Wie lautet denn die entsprechende Abfrage über REST API.
Gibt es nicht einen Befehl der mit genau die Daten aus diesem Feld ausgibt? `"fld":"P_AC","unit":"W","val":"31.90"`

Also sowas wie `{"fld":"P_AC","unit":"W","val":"31.90"}` ? Kenne mich halt mit diesen JSON Befehlen nicht aus.

**Comment by dknubben** [comment]
Also ich gebe auch per REST die aktuellen Daten an einen 2. ESP32 mit LCD-Display weiter und mache das über ein Skript (auf dem MQTT-"Server"), das mir die Werte filtert. Die API kann das nicht direkt leisten. DIe URL lautet aber (seit 0.5.90 meine ich) `http://[IP]/api/inverter/id/0` (erster Inverter). Die Ausgabe kann dann in ein Array konvertiert und nach dem `Schlüssel/Array [ch][0]` gefiltert werden. Das sind die Daten, die Du willst.

**Comment by SteveBaeumer** [comment]
Vielen lieben Dank.Mein Problem ist dann wohl der Array nach dem gefiltert wird. Sagt mir Laien nämlich einfach gar nix. 😉

**Comment by siriuskht** [comment]
Da ich auch gerade dabei bin, einige Daten aus dem REST API auszulesen, hier mein Lösungsansatz (Python). Vielleicht hilft das etwas weiter. 
Vorab noch die Anmerkung, dass meiner Meinung nach die JSON Datenstruktur "etwas gewöhnungsbedürftig" ist. 
Hauptproblem für mich war, dass die Inverter und Channel Daten von "`/api/record/live`" sequenziell angeordnet sind. Besser man hätte die getrennt und gruppiert, z.B.: `['inverter'][0][inverter data][channel 0 data]...[channel n data];` oder die Inverter Daten zuerst aufgelistet.
Um an die Inverter Daten zu kommen, muss man zuerst die Anzahl der Channels (Solarmodule) des jeweiligen Inverters lesen und mit 6 (Anzahl Daten pro Channel) multiplizieren. Dieser Wert ist dann der Offset/Index für die eigentlichen Inverter Daten.

Codebeispiel (dabei ist "`RspAhoyApi{Command}[1]`" der JSON Datensatz (Antwort) der entsprechenden Anfrage):
```python
  # -> get number of channels/modules of inverter 1
  Inverter1_NrOfChannels = RspAhoyApiInverterList[1]['inverter'][0]['channels']
       
  # -> get some live data
  # -> order is: per channel 6 values | inverter = 12 values
  OffsetInverter = Inverter1_NrOfChannels * 6

  U_AC       = RspAhoyApiRecordLive[1]['inverter'][0][OffsetInverter + 0]['val']
  P_AC       = RspAhoyApiRecordLive[1]['inverter'][0][OffsetInverter + 2]['val']
  YieldDay   = RspAhoyApiRecordLive[1]['inverter'][0][OffsetInverter + 8]['val']
  YieldTotal = RspAhoyApiRecordLive[1]['inverter'][0][OffsetInverter + 9]['val']
  print ("U_AC=%s | P_AC=%s | YieldDay=%s | YieldTotal=%s" % (U_AC, P_AC, YieldDay, YieldTotal))
```
Vielleicht hilft das etwas weiter.

**Comment by KSNWH** [comment]
Hallo,
ich hänge mich mal hier rein:
Bisher habe ich keine Erfahrung mit der Ahoi DTU, werde aber demnächst eine für mein BKW einsetzen,
um die Werte in eine bestehende DB und Grafana-Umgebung einzulesen.
Dies möchte ich schon vorbereiten, bevor das BKW läuft.
Meine FRAGE:
a) gibt es ein curl-Kommando, mit dem ich alle relevanten Daten (in Summe) auslesen kann,
z,B. [diese Liste?](https://github.com/lumapu/ahoy/blob/main/User_Manual.md#topicinverter_name_from_setupch0)

b) kann mir jemand das Kommando UND das (ASCII-) Egebnis zur Verfügung stellen.
    PS ich bin Purist und will daraus die relevanten Parameter (per String-Verarbeitung) extrahieren und direkt in die DB schreiben. (one über MQTT, Broker,... zu gehen)

Herzlichen Dank im Vorraus!
Klaus

**Comment by mager33** [comment]
Moin, der Link war der Richtige... weiter unten ist die REST API erklärt. 


Am 10. Januar 2024 20:31:06 MEZ schrieb KSNWH ***@***.***>:

**Comment by KSNWH** [comment]
Danke für die Info.
Dann wäre ich dankbar, wenn mir jemand das Ergebnis dieses Kommandos senden könnte:
http://<Ahoi-IP>/api/inverter/id/0
Klaus

**Comment by mager33** [comment]
{"id":0,"enabled":true,"name":"HM300","serial":"GEHEIM","version":"10014","power_limit_read":0,"power_limit_ack":false,"ts_last_success":1705163547,"generation":0,"status":1,"alarm_cnt":0,"ch":[[0,0,0,0,0,23.5,30.639,29583,1.3,0,0,0],[26.4,0.05,1.3,29583,30.639,0.433,1.3]],"ch_name":["AC","Battery"],"ch_max_pwr":[null,300]}
