### ISSUE TITLE
Wechsel AhoyDTU 0.6.0 zu ältere Version? 

### ISSUE THREAD

**Issue by schulle61** [lumapu/ahoy#875]
## Hardware
  * [ ] ESP8266
  * [ x] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [ ] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

Hallo,

Wie kann ich von der Aktuellen Ahoy DTU  zu einer älteren wechseln? Wenn ich es einfach über Software aktualisieren machen, dann schreibt er zwar erfolgreich,  aber danach kann ich nicht mehr auf die Ahoy DTU zugreifen.
Seit ich auf die Version 0.5.66 und 0.6.0 aktualisiert habe, geht bei der gebauten DTU das Display nicht mehr. Es zeigt garnix mehr an

Wie kann ich auf OpenDTU wechseln?

**Comment by tastendruecker123** [comment]
Zurück geht's am besten mit dem [Flash Tool](https://www.espressif.com/en/support/download/other-tools) von Espressif mit folgenden Einstellungen (für einen ESP8266):

![image](https://user-images.githubusercontent.com/111116980/230879413-9f2cb5fd-2789-46aa-8960-429dbb1fb707.png)

Erst Erase, dann Start, Wichtig ist, dass man das Häkchen setzt vor der zu flashenden Datei. COM Port muss man natürlich individuell anpassen.

Dein Problem wird vermutlich an der Pin-Belegung liegen. Schau mal in den Einstellungen, ob da alles korrekt ist.

**Comment by schulle61** [comment]
So habe es so auf ner älteren Version geflasht. Ist auch alles grün und finish. Aber trotzdem finde ich die AhoyDTU im Netzwerk nicht. Mache ich was falsch?

Das Display hatte vor den neuen Updates funktionert. Die Pinbelegung die man bei der neuen Version ändern muss, die sind so eingestellt wie die sein sollen
![Screenshot 2023-04-10 173205](https://user-images.githubusercontent.com/130185478/230938035-68450c4c-ee33-4826-8bf3-048b00ab99ac.png)
![Screenshot 2023-04-10 173456](https://user-images.githubusercontent.com/130185478/230938087-fc83773c-6b7f-4544-a895-0bf559c60782.png)
![Screenshot 2023-04-10 173510](https://user-images.githubusercontent.com/130185478/230938127-766e22f3-ce99-46e8-a61a-49f824af3257.png)
![Screenshot 2023-04-10 173514](https://user-images.githubusercontent.com/130185478/230938144-df27d677-181a-452a-9c9b-4573b2526f1f.png)

/

**Comment by schulle61** [comment]
.

**Comment by tastendruecker123** [comment]
Vorher Erase gemacht? Macht er einen Access Point auf?

**Comment by schulle61** [comment]
Ja hatte ich vorher gemacht.  Auf ging nix. War nur grün das er fertig ist und dann hatte ich auf Start gemacht. 
Aber hat sich jetzt auch erstmal erledigt. Hab die Einstellung für das Display,  das es wieder anzeigt gefunden was ich noch ändern musste.
Jetzt läuft alles wunderbar.

**Comment by JoeGhost-22** [comment]
Selbes Problem hier, mit NodeMCU PyFlasher konnte ich erfolgreich downgraden. Hatte auch vorher ESP32 FlashTool versucht. vielleicht hilfts
