### ISSUE TITLE
0.6.5 - LED active high/low

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#879]
NOTE: incompatible change: renamed led_high_active to act_high, maybe setting must be changed after update

Funktioniert leider immer noch nicht.

Manuelles editieren der JSON mit anschließendem Import funktioniert jetzt leider auch nicht mehr 😢

Bei der Gelegenheit auch gleich mal verhindern das man den Import-Button auch drücken kann wenn keine Datei ausgewählt wurde. Latsche da mit meinen Wurstfingern immer auf den Button drauf. Oder den Button nicht so nahe am Auswählen-Button platzieren 😉

**Comment by knickohr** [comment]
Danke für die Mühe 😉 Brachte aber fast gar nichts 😲
Zwar kann man jetzt wieder den Trick über das Editieren der JSON machen, aber in der GUI speichert er das LED active high immer noch nicht ab. Steht jedesmal nach dem Reboot wieder low drin.

Bezüglich des Import Buttons hat sich bei mir rein gar nichts verändert 🤔

![A0F85A1A-A496-48F5-BA01-FE082E5339F7](https://user-images.githubusercontent.com/63048210/231672286-82a7dcb4-8767-4dd0-9ce2-1d65978a8695.jpeg)

**Comment by tastendruecker123** [comment]
Ich denke, dass ich das Problem gefunden habe. Ich habe einen PR erstellt, der dieses und andere Problem beim Speichern behebt.

**Comment by knickohr** [comment]
Yeahhh ! 👍
