### ISSUE TITLE
MQTT Server  erreichbar per  IP Adr. und / oder DNS, ON / OFF  Feature Request

### ISSUE THREAD

**Issue by NDS234** [lumapu/ahoy#88]
Kopie von https://www.mikrocontroller.net/topic/525778?goto=7116390#7116209

Ist nur ein Vorschlag:

Es spielt doch gar keine Rolle wor ein MQTT Server steht !
Das kann intern oder extern sein.

Mein Vorschlag für die Programmierer wäre:

MQTT ein/aus  wählbar

Wenn MQTT ein, dann

A) IP Addr und Timeout in ms  angebbar
B) DNS Adr. und Timeout in ms  angebbar

Reihenfolge zur Erreichbarkeit Auswahl:
(folgende Optionen nur wählbar, wenn A) bzw. B) auch ausgefüllt)

Nur A)
Nur B)
Erst A) und wenn nicht erreichbar bis Timeout dann B)
Erst B) und wenn nicht erreichbar bis Timeout dann A)

So was in der Art würde vielleicht Sinn machen.

**Comment by thinklerde** [comment]
Es wäre ja schon schön, wenn man anstatt einer IP Adresse eine Webadresse eingeben könnte.  Z:B: "xyz.ddns.net"

**Comment by lumapu** [comment]
ja das stimmt, guter Feature-Request. Wie lange URLs sollen wir zulassen - ist immer eine Speicherfrage und die Geschäcker sind bekanntlich verschieden. Die Vorgabe kann natürlich dann wieder in der `config.h` geändert werden - aber der Default sollte schon für den Mainstream passen finde ich.
Genügen 32 Zeichen oder lieber gleich 64? Es geht natürlich jede beliebige Zahl - ich denke nur gerne in 2er-Potenzen.

**Comment by NDS234** [comment]
wenn man z.B. mal nimmt:  mqtt.meinhaus.meinestadt.net wären das 28 Zeichen. Ich denke, 32 Zeichen reichen da für den DNS Namen. Ein vielfaches von 2 oder vielleicht besser 4 würde ich vielleicht nehmen wegen dem Alignment im Speicher.
Bevor nun die Frage nach Defaults für die TimeOuts kommen:
MQTT Server Erreichbarkeit TimeOut für DNS viellecht auf 500 ms als Default setzen ? (u16)
MQTT Server Erreichbarkeit TimeOut für IP vielleicht auf 150 ms als Default setzen ?    (u16)
Jemand, der damit was anzufangen weiss, kann es ja dann ändern. Ich denke, die beiden Werte sollten auf der Sicheren Seite sein, für die, die damit nicht so richtig was anfangen können.

**Comment by stefan123t** [comment]
@lumapu & @NDS234 ja 32 sollten grade so reichen z.B. auch für die verbreiteten "123456789ABCDEF.myfreez.net" Adressen, meine hat  zumindest nur 28 chars. Eintragen in der config.h wäre m.E. ausreichend.

**Comment by stefan123t** [comment]
Haha den DNS Eintrag in PR #98 wollte @thinklerde als Feature, vielleicht kann er es ja mal testen ?
Müssen wir jetzt eigentlich auch einen DNS Server (1.1.1.1 oder 8.8.8.8, etc.) konfigurierbar machen oder reicht der, den der ESP über DHCP bekommen hat ?

**Comment by NDS234** [comment]
Da es kein Zwang ist, per DHCP einen DNS Server bekannt zu machen, wäre es optional irgendwann evt. mal sinnvoll, einen von Hand eintragen zu können. Für die, die eine Fritzbox ihr Eigen nennen ist ja normalerweise die Fritzbox der DNS Server. Bei anderen Routern wird es sicher ähnlich sein. Erst mal würde ich da nix machen. Gibt noch Wichtigeres zu tun.

**Comment by stefan123t** [comment]
Ja, wenn man einen anderen (externen) DNS im ESP angibt dann findet er evtl. lokale Namen / Adressen nicht mehr. Es wird also ggf. beliebig kompliziert. Ich denke wir verlassen uns erstmal auf DHCP und schliessen diesen Feature Request wenn @thinklerde es getestet hat.

**Comment by thinklerde** [comment]
das scheint soweit zu funktionieren. Allerdings aktualisiert er nur noch alle 90sek. lässt sich auch nicht anders einstellen. General Intervall auch nicht kleiner 30sek?

**Comment by thinklerde** [comment]
> das scheint soweit zu funktionieren. Allerdings aktualisiert er nur noch alle 90sek. lässt sich auch nicht anders einstellen. General Intervall auch nicht kleiner 30sek?

ich habe es jetzt erstmal in der config.h bei mir geändert. MIN_SEND_INTERVAL auf 5
die Eingabe bei MIN_MQTT_INTERVALL wird mit der MIN_SEND_INTERVAL anscheinend addiert. 
Die habe ich bei mir auf 1 gesetzt und habe nun somit einen MQTT Intervall von 6

Habe den Wert bei MIN_MQTT_INTERVAL auf 0 gesetzt, so scheint das dann erst mal bei mir zu passen. Läuft bisher ganz gut. 

Vielen Dank!

**Comment by stefan123t** [comment]
@thinklerde ja ich habe die [Default Minimum Werte](https://github.com/grindylow/ahoy/pull/98/commits/d4ba302307b2b6995c2df0a83e4d02ff45bbd08d) mal etwas höher angesetzt um Probleme vor allem bei neuen Nutzern auszuschließen. Wer seinen Inverter im *Denial-of-Service Modus* :smiling_face_with_tear: betreiben / abfragen will, kann das ja wie Du in der config.h jederzeit anpassen.
