### ISSUE TITLE
0.4.14 works, 0.4.20 "inverter is available and is not producing" 

### ISSUE THREAD

**Issue by oxylog** [lumapu/ahoy#89]
In Version 0.4.14 funktioniert alles problemlos. Pins CS = 15, CE = 2 und IRQ = 0. 
Werte werden korrekt dargestellt;
In 0.4.20: Gleiche Einstellungen, Pins manuell gesetzt oder auch in Arduino vorhergehend geändert: Egal ob OTA-Update oder frisch auf das Board aufgespielt - "inverter is available and is not producing". Kein Anzeigen der Werte oder ähnliches

Selbiges passiert auch wenn eine lauffähige 0.4.14 mit einer neu kompilierten 0.4.20 geupdated wird und eigentlich alle Settings übernommen werden sollten.

**Comment by lumapu** [comment]
für die Zukunft wäre noch schön zu erfahren warum der Issue geclosed wurde. Im Forum glaube ich gelesen zu haben, dass ein Update der Libraries und erneutes kompilieren den Fehler verschwinden haben lassen.

**Comment by oxylog** [comment]
Ich hatte die zugemacht da ich auf dem falschen Dampfer war. 
Ich dachte zuerst, dass ich es durch ein Update der Libraries hinbekommen habe - das war aber nicht der Fall, wie sich nach einem Wifi-Disconnect zeigte. Der ware Grund ist in #90 zusammengefasst. 
Danke dir für die Erinnerung, bin noch sehr neu in der Materie und bei Github
