### ISSUE TITLE
[Bug] Nullung der Werte bei mehreren Invertern

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#892]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.7

### Github Hash

12a3d50

### Build & Flash Method

ESP Tools (flash)

### Setup

Kann ich so nicht beschreiben, es handelt sich um das PCB von Markus, also der ESP32S3. Tut aber nichts zur Sache, tritt bei allen ESPs auf.

### Error description

Betrifft nur DTUs mit mehreren Invertern !

Beim Start der WRs werden die YieldDay Werte der einzelnen inverter , nicht der totale Yield Day, offenbar erst dann genullt. Anschließend werden die Werte aller WRs zusammen gerechnet als einen einzigen Wert YieldDay total über MQTT übertragen.

Soweit ja alles OK. Wenn jetzt aber ein oder mehr Inverter noch nicht aufgewacht ist, dann werden offenbar alte Werte die sich noch in irgendeiner Variable befinden ebenfalls fälschlicherweise mit aufsummiert und übertragen.

Die Werte der einzelnen Inverter müssen vor der Übertragung alle genullt werden, egal ob die Inverter bereits aufgewacht sind oder noch schlafen.

![71B32F2A-8F16-4300-AF16-D71218B5EA92](https://user-images.githubusercontent.com/63048210/232984878-68ab7805-7691-48ca-bc0b-abf084d66304.jpeg)

**Comment by beegee3** [comment]
das ist merkwürdig. Bei der Nullung um Mitternacht werden die Variablen mit den YieldDay Werten bei **allen** Invertern auf 0 gesetzt (Schleife in `app::tickMidnight`). Und genau diese Variablen werden für den YieldDay Total aufsummiert (`sendIvData` in `pupMqtt.h`). YieldDay Werte von **vor** Mitternacht sollten nirgendwo mehr gespeichert sein, also auch nicht aufaddiert werden können. Kannst du anhand der YieldDay Werte der einzelnen Inverter **vor** Mitternacht nachvollziehen, das deren Summe (bis auf den ersten aufgewachten) das ergibt, was du morgens beim YieldDay Total beobachtet hast?
Oder spielt dir der erste aufgewachte Inverter einen Streich und meldet (fälschlicherweise) diesen Wert? Denn beim Aufwachen wird von Ahoy aktiv nichts genullt, sondern nur das rausgegeben, was der Inverter meldet.

**Comment by beegee3** [comment]
@lumapu oder könnte `doCalculations` in `hmInverter.h` der Übeltäter sein? Das rechnet doch den Inverter YieldDay Wert aus den Panel YieldDay Werten zusammen. Und die wurden nicht genullt. Es ist schwierig nachzuvollziehen, wann diese Funktion aufgerufen wird. Bin mir nicht sicher, ob das immer erst passiert, wenn ein Inverter Daten liefert und damit auch aktuelle Panel Werte vorliegen. Evtl. wäre es das einfachste (und sicherste), in der `zeroYieldDay` Funktion die YieldDay Werte **aller** Channels zu nullen. Wenn ich mir die Funktion ansehe, scheint das auch so geplant zu sein (Schleife über die Channel). Allerdings läuft die Schleife zu kurz (< statt <=) und in der Schleife steht `CH0` statt `ch`.
Modifiziert wäre es dann:
```
        void zeroYieldDay(Inverter<> *iv) {
            DPRINTLN(DBG_DEBUG, F("zeroYieldDay"));
            record_t<> *rec = iv->getRecordStruct(RealTimeRunData_Debug);
            uint8_t pos;
            for(uint8_t ch = 0; ch <= iv->channels; ch++) {
                pos = iv->getPosByChFld(ch, FLD_YD, rec);
                iv->setValue(pos, rec, 0.0f);
            }
        }
```

**Comment by knickohr** [comment]
Ich teste heute Nacht mal genauer. Hab eben den Flow angepaßt um zu sehen wo die Werte herkommen, welcher Inverter der Übeltäter ist.

Was ich bis jetzt sehe, das die Wert genau minus dem Yield des ersten aufgewachten Inverters ist. Danach habe ich manuell den Graphen genullt.

Erinnert mich daran heute Abend den Graphen zu nullen, sonst ist es zu unübersichtlich 😅

**Comment by lumapu** [comment]
@knickohr: Erinnerung

**Comment by lumapu** [comment]
@beegee3 ich glaube du hast mal wieder ins schwarze getroffen. Sieht für mich auch stark nach dem Fehler aus. @knickohr: ich veröffentliche gleich mal eine neue Version mit dem Fix.
`doCalculations` wird immer beim setzen neuer (empfangener) Werte aufgerufen:

https://github.com/lumapu/ahoy/blob/bf1e77e33ecdebc9ba2273c7ca65aab7ef026444/src/hm/hmPayload.h#L313-L337

**Comment by knickohr** [comment]
Wieso finde ich nur immer so eine Sch… ? 😅🤪

**Comment by knickohr** [comment]
Rückmeldung :  Hat heute Morgen alles prima funktioniert 👍
