### ISSUE TITLE
[Bug] Reset values and YieldDay at midnight

### ISSUE THREAD

**Issue by TobiScience** [lumapu/ahoy#895]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

nothing

### Error description

The daily data (total and both inverters get a reset at 0:00 in the interface) but only the total data get an mqtt update at 0:00

https://i.imgur.com/tAeuITn.png (the red circle)

settings:
Reset values and YieldDay at midnight [x]
Reset values when inverter polling pauses at sunset [ ]
Reset values when inverter status is 'not available' [ ]

thanks for the great project

**Comment by lumapu** [comment]
Does it mean that both of the inverters are publishing a value different from zero at midnight? When is their last update?

**Comment by TobiScience** [comment]
No there is no mqtt update for the inverters between nighttime. 

For example yesterday the last mqtt update was around 20:45 from the inverter and the first update comes when the wake up 6:35. Only the total gets a reset and mqtt publish at midnight. 

I think the inverters should get an update at midnight since ahoy resets both inverters and total at midnight.

I have intervall[s] = 0

**Comment by ottelo9** [comment]
Exactly the same problem here. I discussed this problem in Discord already.

**Comment by lumapu** [comment]
I'm sorry, I didn't get the problem. From the implementation side the inverter data should become zero from the inverter itself because of slowly reduced light in the evening. The yield is one of the fields which doesn't decrease while turning off and need a manual reset it you need this value day by day.
What would be the expected behavior compared to the implementation?

I'm also fine if you answer in German.

**Comment by TobiScience** [comment]
Hey,
um 24 Uhr werden in der Oberfläche die Tageswerte auf 0 kWh gesetzt.
Gleichzeitig wird dies auch per Mqtt verschickt, dort allerdings nur Total, die Mqtt Daten für die Inverter kommen erst morgens. 

Besser wäre wenn um 24 Uhr für Total und alle Inverter ein Mqtt mit 0 kWh verschickt wird. Sonst sieht das so komisch aus wie auf dem Screenshot aus Grafana.

**Comment by lumapu** [comment]
bitte nochmal mit der aktuellen Release `0.7.25` testen, da dieser Issue etwas aus dem Fokus gerückt ist. Danke.

**Comment by TobiScience** [comment]
Soweit ich das sehe funktioniert das mit dem Night reset, :)

allerdings ist jetzt Total, also das Summieren von mehrern Invertern nicht mehr korrekt :/

![grafik](https://github.com/lumapu/ahoy/assets/68364344/40eaec40-5b28-4ab1-91e8-e38d311bd740)

Sobald ein Inverter Daten liefert, rechnet ahoy System den total aus und senden diesen
Inverter(x kwH) + Inverter2(0kwH) = total x kwH per mqtt, statt zu warten bis der 2te Inverter überhaupt Daten geliefert hat, dadurch macht jedes Restarten direkt einen Knick ins Diagramm

**Comment by lumapu** [comment]
man müsste quasi eine Art 'timeout' festlegen, ab wann YieldDay Werte verschickt werden dürfen, damit würde man auch auf den x-ten inverter warten.

**Comment by TobiScience** [comment]
Müsste man nicht nur verhindern, dass total per mqtt verschickt wird wenn ein Inverter noch Yield Total auf 0 steht. Weil eigentlich kann ein Inverter ja nicht auf 0 stehen wenn er läuft. Der Zähler geht ja nur rauf,

**Comment by lumapu** [comment]
guter Hinweis!

**Comment by lumapu** [comment]
maybe resolved in the meantime, check the new Release 0.8.140 😉
