### ISSUE TITLE
MQTT is not connected

### ISSUE THREAD

**Issue by Duesendaniel** [lumapu/ahoy#898]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT Broker hinzugefügt

### Error description

'MQTT is not connected' tritt immer weider auf, diesmal nach 1 Tag uptime nach update auf 0.6.9. Keine Fehlermeldung in der Console. Im  ioBroker nur ' Client connection closed: timeout'. Nach reboot läuft es wieder. Vorher hatte ich die 0.6.0 und 0.6.4 auf ESP32  D1 mini laufen und nach 4 - 5 Tagen dann das Problem.

**Comment by teletapi** [comment]
Hab ein ähnliches Problem FW 6.8 und 6.9 ESP32 nach dem abendlichen abschalten der DTU und am nächsten tag wieder einschalten "kein mqtt connect" nach mehrfachem Neustart geht es dann wieder aber wieder nur bis zum nächsten ein/ausschalten dann wieder das gleiche Spiel

**Comment by Duesendaniel** [comment]
Das Problem hatte ich schon bei der 0.5.8X mit ESP 32 und ESP 8266. Mal ist es nach 1 Tag uptime oder 3-5 Tages uptime passiert. Nach Reboot oder MPR war dann sofort für die nächsten Tage alles ok.

**Comment by teletapi** [comment]
Das passiert nicht solange es online ist, das passiert nur wenn ich der DTU den Stecker ziehe und morgens wieder einschalte dann kommt einfach kein mqtt. ich muss dann jenachdem 2-4 mal neu strom drauf geben irgend wann ist mqtt wieder connected und bleibt es auch den ganzen tag über

**Comment by Duesendaniel** [comment]
Wenige Stunden nach dem gestrigen Update auf 0.6.9 war die Verbindung wieder weg.

**Comment by StefanTR96** [comment]
Ebenfalls das selbe Problem seit dem Update auf 0.6.9

**Comment by Jumperm** [comment]
Vielleicht bringt es etwas Licht ins dunkle: ich hab die Fritzbox als lokalen NTP.
8266er mit 100uF. Sauber geflashed mit esphome flasher 
https://github.com/esphome/esphome-flasher
Bei mir läuft die Version 0.6.7 mit den selben Parametern ohne Probleme

**Comment by derTillus** [comment]
Ich habe das oben genannte Problem seit 0.5.66 und es ist leider mit dem Update auf 0.6.9 unverändert.

**Comment by Jumperm** [comment]
Besteht mit 0.6.12 leider immer noch.

**Comment by lumapu** [comment]
wie steht bei euch das Abfrageintervall? Gibt es hier Analogien zu #901?

**Comment by exo1987** [comment]
Seitdem ich "Pause polling inverters during night" deaktiviert habe, bleibt MQTT verbunden.

**Comment by lumapu** [comment]
sehr interessant, kann aber leider nicht erklären warum das scheinbar zusammenhängt

**Comment by Jumperm** [comment]
Ich habe auf 7.6. gewechselt und nur den mqtt herausgenommen. Läuft seit einem Tag mit RestAPI ohne Einschränkung.

**Comment by lumapu** [comment]
bitte das neue Release `0.725` testen und Feedback geben, danke.
