### ISSUE TITLE
FeatureRequest: HMS Support + Parallele Nutzung von NRF24L01+ und CMT2300A

### ISSUE THREAD

**Issue by MiniOh** [lumapu/ahoy#904]
Hallo, 

ich weiß, es gibt bereits einige Themen dazu.
Dennoch hier die Frage ob es auch mit Ahoy, ähnlich wie beim OpenDTU Projekt möglich sein wird, auf einem ESP32 die beiden Antennen NRF24L01+ und CMT2300A parallel zu betreiben?

Bei mir ist noch die Beschaffung eines Inverters offen, und ich würde gerne einen HMS 1800 nutzen, sollte in Zukunft die Nutzung einer DTU mit beiden Antennen möglich sein.

Danke schon mal vorab, für die hoffentlich positive Rückmeldung.

Beste Grüße

**Comment by lumapu** [comment]
ja genau, das ist schön integriert, schaue einfach später nach einem Branch `HMS`

**Comment by MiniOh** [comment]
Oh, super.
Wusste gar nicht dass das schon soweit ist.

Da ich eh nur ESP32 nutze, sollte das ja für mich passen.

Gibts eine PIN Belegung für die zweite Antenne?

**Comment by lumapu** [comment]
ja ist eine Testversion: https://github.com/lumapu/ahoy/tree/hms

Pinbelegung ist relativ frei wählbar, ich habe hier leider keine Erfahrung und auch noch nicht getestet, ob beides gleichzeitig geht.

**Comment by MiniOh** [comment]
Sorry für dei wahrscheinlich blöde Frage.
Wie komme ich in der HMS Branch zu einer dem .bin File?
Unter Actions gibts die Branch nicht, um das fertge File herunterzuladen, oder?

**Comment by MiniOh** [comment]
> ja ist eine Testversion: https://github.com/lumapu/ahoy/tree/hms
> 
> Pinbelegung ist relativ frei wählbar, ich habe hier leider keine Erfahrung und auch noch nicht getestet, ob beides gleichzeitig geht.

Das Testen kann ich gerne übernehmen, sobald die Antenne ankommt.
Der Inverter sollte diese Woche noch kommen.

**Comment by lumapu** [comment]
hier ist die bin gebaut aus dem aktuellen Stand:
Getestet habe ich es jetzt über Wochen hinweg mit einem HMS 2000 4T, ein weiterer Test mit 3x HMS 2000 4T wurde auch schon gemacht.

[230425_ahoy_0.6.10_HMS_esp32.bin.zip](https://github.com/lumapu/ahoy/files/11326812/230425_ahoy_0.6.10_HMS_esp32.bin.zip)

**Comment by MiniOh** [comment]
Super.
Besten Dank.
Dann werde ich auch mal etwas damit spielen.

Gibts die Antennen auch irgendwo in Deutschland zu kaufen, oder kommen die aktuell alle noch aus China?

**Comment by lumapu** [comment]
meinst du Funkmodule oder Antennen?

**Comment by MiniOh** [comment]
Funkmodule, sorry.

**Comment by lumapu** [comment]
melde dich beim Kontakt auf Ahoydtu.de, ich hab was da

**Comment by MiniOh** [comment]
> hier ist die bin gebaut aus dem aktuellen Stand: Getestet habe ich es jetzt über Wochen hinweg mit einem HMS 2000 4T, ein weiterer Test mit 3x HMS 2000 4T wurde auch schon gemacht.
> 
> [230425_ahoy_0.6.10_HMS_esp32.bin.zip](https://github.com/lumapu/ahoy/files/11326812/230425_ahoy_0.6.10_HMS_esp32.bin.zip)

Hallo, 

ich hatte heute mal die 0.6.10 HMS getestet.
Grundconfig war ok. Ich habe dann den NRF24L01+ aktivert.
Danach habe ich in der Config CMT2300A aktivert (ohne dass ein Funkmodul verkabelt ist)
Anschließend war die DTU nicht mehr per IP erreichbar.

Auch seriell erhalte ich folgende Meldug:
"Serial port is not ready. Close any other application using it and try again."

Ne Idee?

**Comment by MiniOh** [comment]
OK, ich kann es noch etwas detailierter eingrenzen.

Ich habe nochmal mit einem ESP32 DEVKIT1 geteset.

Grundkonfig OK. 

NRF24 verkabelt, CMT2300A noch nicht vorhanden.

Test 1:
Nur NRF24 aktiviert und Pins konfiguriert.
> Reboot, alles OK, **Meldung NRF24 is connected.**

Test 2:
NRF24 aktiviert und Pins konfiguriert und zusätzlich das Häkchen bei "CMT2300A Enable"
Pins des CMT2300A auf **OFF / default**
> Reboot, DTU nicht mehr erreichbar, auch nicht seriell. Nur über Halten des Boot Buttons wieder flashbar.

Test 3:
NRF24 aktiviert und Pins konfiguriert und zusätzlich das Häkchen bei "CMT2300A Enable"
Pins des CMT2300A auf **12, 13, 14 (beliebig)**
> Reboot OK, DTU noch erreichbar, allerdings ist mit zusätzlich aktivem CMT2300A, die NRF24 nicht mehr ereichbar.
Meldung "your NRF24 module can't be reached, check the wiring and pinout"

Hilft das evtl. bei der weiteren Entwicklung der HMS Branch?
Oder ist generall kein Parallelbetrieb von HM und HMS Invertern geplant?

Danke schon mal vorab.

**Comment by MiniOh** [comment]
Gibts bereits eine Version nach der 0.6.10 für HMS?
Kannst du nochmal die .bin bereitstellen?

**Comment by mc-0815** [comment]
Hi, 

vermutlich für euch eine dumme Frage, aber wo finde ich eine Wiring Schaubild für eine ESP32 oder ESP8266 und dem Funkmodul CMT2300A? Habe heute einen HMS-1600 und möchte gern loslegen.

Vielen Dank,

**Comment by lumapu** [comment]
Bei mir hängt das Modul am VSPI (SCK und MOSI)

Daraus ergibt sich als feste Pins, ESP zu CMT:
D23 - SDIO
D18 - SCK

und frei wählbar:
D17 - CSB 
D26 - FCSB
D34 - GPIO3

**Comment by lumapu** [comment]
> Gibts bereits eine Version nach der 0.6.10 für HMS?
> Kannst du nochmal die .bin bereitstellen?

Ja kann ich, allerdings hat sich da bisher nicht wirklich was verändert.

**Comment by lumapu** [comment]
> Oder ist generall kein Parallelbetrieb von HM und HMS Invertern geplant?


Doch ist schon geplant, genau dieses Setup habe ich hier auch an Wechselrichtern. Plan ist Mi, HM und HMS zu unterstützen.

**Comment by mc-0815** [comment]
> Bei mir hängt das Modul am VSPI (SCK und MOSI)
> 
> Daraus ergibt sich als feste Pins, ESP zu CMT: D23 - SDIO D18 - SCK
> 
> und frei wählbar: D17 - CSB D26 - FCSB D34 - GPIO3

Vielen Dank.

**Comment by MiniOh** [comment]
> > Oder ist generall kein Parallelbetrieb von HM und HMS Invertern geplant?
> 
> Doch ist schon geplant, genau dieses Setup habe ich hier auch an Wechselrichtern. Plan ist Mi, HM und HMS zu unterstützen.

Guten Morgen, 

vielen Dank für die Info und die tolle Hilfe.
Wie auch schon per Mail kommuniziert, funktioniert bereits mit der 0.6.10 HMS, der Parallelbetrieb von HM und HMS.

![grafik](https://github.com/lumapu/ahoy/assets/27901554/b6a1d085-de63-4ece-b301-f1ee98c81c5e)

**Comment by lumapu** [comment]
> Wie auch schon per Mail kommuniziert, funktioniert bereits mit der 0.6.10 HMS, der Parallelbetrieb von HM und HMS.

würdest du dafür mit uns noch dein Pinout teilen?

**Comment by MiniOh** [comment]
> > Wie auch schon per Mail kommuniziert, funktioniert bereits mit der 0.6.10 HMS, der Parallelbetrieb von HM und HMS.
> 
> würdest du dafür mit uns noch dein Pinout teilen?

Hallo, ja, natürlich.

Der CMT ist auf dein Board gelötet, der NRF manuell auf die Pins des ESP32 gelötet.

![grafik](https://github.com/lumapu/ahoy/assets/27901554/e0f657d7-ea59-4d8e-9194-0bdc327a816c)

**Comment by MiniOh** [comment]
![image](https://github.com/lumapu/ahoy/assets/27901554/e902ceec-f9de-4d3d-b3ca-ad9d0b4ec0db)

**Comment by MiniOh** [comment]
So, ich habe testweise auch mal meine produktiven Inverter eingebunden. 
Scheint auch alles sauber zu funktionieren.

![grafik](https://github.com/lumapu/ahoy/assets/27901554/1c9d3e47-7c78-492a-b5a0-ce82010a5b9a)

**Comment by Argafal** [comment]
Hier noch ein pull request, der die gleichzeitige Nutzung von NRF und CMT auch auf dem Fusion v2 Board (und anderen S3/C3/S2 basierten Boards) ermoeglicht: https://github.com/lumapu/ahoy/pull/935

Fusion v2 pinout Einstellungen:

![image](https://github.com/lumapu/ahoy/assets/715254/19fdc297-b184-4cd6-9ee3-4175d953fe3f)

**Comment by commandermatz** [comment]
> hier ist die bin gebaut aus dem aktuellen Stand: Getestet habe ich es jetzt über Wochen hinweg mit einem HMS 2000 4T, ein weiterer Test mit 3x HMS 2000 4T wurde auch schon gemacht.
> 
> [230425_ahoy_0.6.10_HMS_esp32.bin.zip](https://github.com/lumapu/ahoy/files/11326812/230425_ahoy_0.6.10_HMS_esp32.bin.zip)

Diese Version läuft nicht auf einem 8266?

**Comment by MiniOh** [comment]
Nein

**Comment by MiniOh** [comment]
Nur mal zur Info.
Bei mit läuft die HMS Version 0.6.10 seit 2 Wochen fehlerfrei mit 6 HM und 2 HMS Invertern.

@lumapu 
Gibts bereits eine neuere .bin?

**Comment by leowinterde** [comment]
Nur zum Verständnis, sind die HMS und HMT (#233) von der Kommunikation her gleich?

**Comment by lumapu** [comment]
@LeoWinterDE Ja beide verwenden ein 868MHz Protokoll und benötigen den Funkchip CMT2300A

@MiniOh sehr cool, freut mich dass es so gut läuft.

hier ist die Version, die auf den neuesten Sourcen basiert `0.6.15`:
[230527_ahoy_esp32_hms_hmt_0.6.15.bin.zip](https://github.com/lumapu/ahoy/files/11580498/230527_ahoy_esp32_hms_hmt_0.6.15.bin.zip)

**Comment by MiniOh** [comment]
@lumapu 

Es gibt doch noch etwas, was mit dem HMS Invertern nicht ganz passt.
Einer der beiden HMS, liefert abends beim "Offline gehen" Zero Yield Day Werte, wodurch dann auch die Total Yield Day nicht mehr passt.

Hast du eine Idee an was das liegen könnte?

![grafik](https://github.com/lumapu/ahoy/assets/27901554/2da2b3df-77d3-4456-bdb7-c1139c229c8f)

Es ist der "letzte" Inverter der Offline ging, welcher dann 0 bei Yield Day liefert, falls das hilft.

![grafik](https://github.com/lumapu/ahoy/assets/27901554/c54100f3-551d-456d-bbee-2e178e8f6ea4)


Olli

**Comment by lumapu** [comment]
ich denke es liegt an wechselnden Lichtverhältnissen in der Dämmerung. Der Wechselrichter ist schon mal aus und hat alles vergessen, dann bekommt er nochmal genug Saft um noch eine Nachricht zu schicken, leider durch den vorherigen reset mit falschen Informationen.
Wir könnten eine Unterdrückung von diesen Nachrichten einbauen, sie wären leicht erkennbar.

**Comment by MiniOh** [comment]
Ich weiß was du meinst.
Das ist bei mir bisher nur einmal passiert bei extrem dunkler Bewölkung vor der Dämmerung.
Aber keinesfalls unter "normalen" Verhältnissen.

In den letzten Monaten kam das nie vor.
Lediglich jetzt an 3 aufeinanderfolgenden Tagen, und auch nur mit den HMS.

**Comment by MiniOh** [comment]
@lumapu 

Hey, 

heute ist das nicht passiert. Ich bin testweise aber wieder zurück zur HMS 0.6.10
Die letzten beiden Tage, also das Verhalten auftrat, war die HMS 0.6.15 installiert.
Zufall, oder hat sich da etwas diesbezüglich verändert?

Beste Grüße

**Comment by lumapu** [comment]
@MiniOh mich wundert, dass dein NRF Pinout geht, da du HSPI und VSPI gemischt hast. Hier mein Vorschlag:
![grafik](https://github.com/lumapu/ahoy/assets/22733082/1911dad9-067b-4380-b6e0-6f18c3fb6f4d)

**Comment by MiniOh** [comment]
Danke für den Hinweis.
Bisher klappt das einwandfrei, zumindest mit der 0.6.10.

**Comment by jho59** [comment]
> Bei mir hängt das Modul am VSPI (SCK und MOSI)
> 
> Daraus ergibt sich als feste Pins, ESP zu CMT: D23 - SDIO D18 - SCK
> 
> und frei wählbar: D17 - CSB D26 - FCSB D34 - GPIO3

Ich bin etwas überrascht ...
Da der ESP32 sowohl Daten zum Funkmodul senden als auch von dort empfangen muss, müssten doch sowohl MOSI als auch MISO verbunden sein? Das ist bei Verwendung eines CMT2300A aber nicht der Fall. Wie bekommt der ESP32 in dem Fall Daten? Und was ist mit einem SPI-ChipSelect? Wenn der CMT2300A an VSPI angeschlossen ist, wäre das der GPIO5 ...
GPIO34 fungiert in dem Fall als IRQ? 

Grüße, Jürgen

**Comment by schluss123** [comment]
Hi Lumapu,
Wäre es möglich, alle PinOUT Konfigurationen frei definierbar zu machen? Auf meiner PCB sind die festen Pins, ESP zu CMT:
D23 - SDIO und D18 - SCK als direkte Leiterbahn zum NRF24L01+ ausgestaltet,  OpenDTU läuft damit, Ahoy leider nicht mehr. Ich kann die GPIOs 18 und 23 NICHT zum CMT2300A routen.
<img width="472" alt="image" src="https://github.com/lumapu/ahoy/assets/140070789/d486129b-eddf-4a54-a68a-1e6366845ce3">

Danke.

**Comment by lumapu** [comment]
@jho59 

> Wie bekommt der ESP32 in dem Fall Daten? 

Der Mosi Pin wird ganz besonders eingestellt in diesem Fall. Das CMT Modul verwendet den Pin bidirektional, war für uns auch neu und eine gewisse Zeit ein Blocker während der Entwicklung.

**Comment by lumapu** [comment]
@schluss123 werde ich mir anschauen. Hast du einen ESP32 mit 30 oder 38 Pins?

**Comment by schluss123** [comment]
> @schluss123 werde ich mir anschauen. Hast du einen ESP32 mit 30 oder 38 Pins?

@lumapu : Ich nutze meistens die 38poligen ESPs, gelegentlich auch die 30poligen im Evo-Board. 38 bevorzugt. Danke Dir.

**Comment by Jakobi88** [comment]
@lumapu Ähnliches Problem bei mir - SCK liegt auf dem HSPI GPIO 12 und SDIO liegt ebenfalls auf dem HSPI GPIO 14. Dito 38 Pin ESP32.

**Comment by lumapu** [comment]
@schluss123 @Jakobi88 macht bitte einen neuen Issue dafür auf - so geht die Info verloren, da dieser Issue beim nächsten Release zugemacht wird. (wegen `fixed dev`)

**Comment by schluss123** [comment]
added at #1046

**Comment by Agerter** [comment]
Hallo welche Antenne kann ich für den CMT2300A Funkchip verwenden geht da nur diese große Antenne oder reicht es auch ein kleine Antenne mit IPX Anschluss und einem Kabel zu verwenden

**Comment by jho59** [comment]
@Agerter:
Zunächst einmal sollte die Antenne für 800 - 900 MHz geeignet sein. Eine WLAN-Antenne für 2,4 GHz hätte vermutlich höhere Verluste. "Groß" und "klein" sind bei Antennen irrelevant, da geht es darum, welchen Antennengewinn in dBi der Anbieter angibt.  Antennengewinn bedeutet aber auch, dass die Antennen eine gewisse Richtwirkung hat. Man muss sie dann evtl. auf den Wechselrichter ausrichten.

Der IPX-Anschluss ist für max. 30 Steckvorgänge spezifiziert. Es spricht nichts dagegen eine 800 MHz-Antenne mit Kabel und IPX-Stecker zu verwenden. Nur sollte man die Antenne idealerweise 1mal anschließen und es dann so lassen. Eine Antenne mit SMA-Steckverbindung und eine Knickstelle zum Ausrichten ist da praktischer.

**Comment by schluss123** [comment]
"Geeignet" und "Verluste" sind zwar schöne Worte, aber vielleicht nicht ganz die Antwort, die der Ersteller hatte:
der CMT2300A wird bei einer Mittenfrequenz von 850 MHz betrieben, das ergibt eine Wellenlänge von ca. 35cm. Die verwendete Antenne sollte dann ein viertel, halbes oder ganzes der Wellenlänge sein, um "optimal" an die Frequenz angepasst zu sein. Also sollte die Drahtlänge der Antenne : 35 oder 17,5 oder 8,75 cm lang sein. Einen wirklichen Antennengewinn hat keine dieser Antennen, da sie sehr wenig Richtwirkung haben und bei dBi immer gegen einen isotropen Strahler definiert wird.
Eine WLAN-Antenne mit einer Mittenfrequenz von 2.450 MHz hat eine Wellenlänge von 12,2 cm. Nicht optimal für 860 MHz.
Also am besten einen IPX-Verbinder auf SMA-Einbaubuchse fest verbauen und dann einen Antennendrahtstummel mit SMA-Stecker bauen.

**Comment by lumapu** [comment]
@schluss123 bist du dir sicher mit den 8.75cm? Ich dachte immer das muss noch ein Korrekturfaktor oä. gerechnet werden. Ehrlich gesagt kenne ich mich hier garnicht aus, aber kenne von anderen Projekten eine Drahtlänge von 8.3cm
Auch online Rechner haben mir das ausgespuckt.

**Comment by schluss123** [comment]
@lumapu Du hast Recht, es gibt noch einen Verkürzungsfaktor, aber bei den Reichweiten, die wir für die WRs brauchen, müsste auch eine nasse Spaghetti als Antenne reichen.

**Comment by Agerter** [comment]
ok heisst das ich kann so ne 2.4ghz Antenne verwende und habe Reichweiten Einbußen.. für ein Balkonkraftwerk im Haus sollte das doch reichen oder?

**Comment by jho59** [comment]
Probiere es einfach aus und berichte dann, wie es funktioniert. 

Ich habe einen ESP32 nur mit CM2300A laufen und eine Antenne für die 860 MHz am Funkmodul. Entfernung zum Wechselrichter ca. 3,5 m durch eine 30 cm dicke Ytongwand bzw. durch das Fenster. 
 RX success 984, RX no answer 3, RX fragments 2946 - ich hätte da ein anderes Verhältnis erwartet. 
Entfernung zum Router ähnlich, aber zwei Innenwände. wifi_rssi zwischen -61 und -63.

**Comment by 58dahl** [comment]
Moin,
ich hab mal eine blöde Frage, im Setup des AHOY-DTU ist unten der IRQ Pin zu definieren. Wenn ich mein CMT2300 Breakboard ansehe ist da aber kein IRQ Pin vorhanden. Steh ich auf dem Schlauch oder welcher Pin am CMT ist gemeint?
Kann mir das jemand beantworten?
Vielen Dank
Pit

**Comment by jho59** [comment]
Ich habe IRQ an den Pin GPIO3 des CMT2300-Modules angeschlossen.

**Comment by lumapu** [comment]
ja das ist korrekt GPIO3 ist der IRQ (ich schreibe es zukünftig ins Setup)

**Comment by 58dahl** [comment]
> ja das ist korrekt GPIO3 ist der IRQ (ich schreibe es zukünftig ins Setup)

Hi Lukas, danke für die Aufklärung, das wird dann klarer für die Leute die nicht so tief in der Materie stecken.
Fürs Setup wäre das eine gute Idee evtl. GPIO3(IRQ) zu schreiben. Dann sollte es klar sein.
Lieben Dank und Gruß
Pit
P.S. Ich würde evtl. noch einen Schritt weiter gehen und im Setup CLK unsd SDIO auch aufnehmen, dann sind alle Anschlüsse erfasst.

**Comment by MWagnerOE5AOO** [comment]
Hi zusammen, 
Nur zur Ergänzung zum Thema Antenne. Die Koaxleitung vom Board weg abisolieren und auf den Schirm und den Innenleiter je ein Stück Draht mit 7,8cm anlöten. So entsteht ein Dipol mit einer Resonanzfrequenz von 850Mhz. An der Luft ist der Verkürzungsfaktor 0,98. Der geöffnete Dipol liegt mit der Impedanz etwas neben den 50Ohm der Module. Daher passen die längen auch nicht genau.   
![1694287052331](https://github.com/lumapu/ahoy/assets/132038848/ba93f420-e23a-4999-9917-35656d004522)
![1694287052348](https://github.com/lumapu/ahoy/assets/132038848/abdb5543-6f7e-48ad-8fac-174af254a332)
Soll die Frequenz bei 886 liegen die beiden Drähte auf 7,6cm kürzen.
viel Spaß und Erfolg beim Nachbauen
Michael
