### ISSUE TITLE
MQTT Steuerbefehl scheinbar fehlerhaft

### ISSUE THREAD

**Issue by Swigart1** [lumapu/ahoy#916]
Version 0.6.9

Bei Steuerung des Limits über MQTT mit limit_nonpersistent_absolute wird aus 600 als Eingabe 600% statt 600W.

Bitte prüfen.

VG

**Comment by dtuuser** [comment]
Moin, wie sieht denn Dein Befehl aus?
Befehl wurde etwas geändert.  siehe  https://github.com/lumapu/ahoy/blob/main/User_Manual.md#control-via-mqtt

inverter/ctrl/limit/0     600W

Ohne W nimmt er das als %

**Comment by Swigart1** [comment]
Danke für den hint. Habe ich nicht gelesen.
