### ISSUE TITLE
Wechselrichter HM1500 is not yet available !?

### ISSUE THREAD

**Issue by Piffekopp** [lumapu/ahoy#922]
## Hardware
  * [X] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: _VENDOR ESP8266MOD
Retailer URL: ______

### nRF24L01+ Module
* [X] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [X] external antenna (SMA)

### Power Stabilization:
* [X]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [X] AhoyDTU Webinstaller

Hallo Leute,
meine AhoyDTU empfängt nichts von meinen Hoymiles HM1500. 
Habe die Anschlüsse laut Plan nochmal überprüft und durchgemessen. Hier ist mir nichts aufgefallen bzw. das sollte alles richtig angeschlossen sein. Weis mir momentan keinen Rat mehr.

Habt ihr da vielleicht eine Idee an was es liegen könnte ?

An meinem Wechselrichter sind derzeit nur zwei Module auf Eingang 1 + 2 angeschlossen. Die grüne LED am Wechselrichter blinkt alle 2s grün was laut Beschreibung bedeutet, daß der WR Strom erzeugt jedoch gibt es ein Problem mit einem Anschluss. Ich vermute, daß das von den zwei fehlenden Modulen kommt die auf Eingang 3 + 4 nicht angeschlossen sind. Denke mal die fehlende Kommunikation mit der AhoyDTU dürfte damit nichts zu tun haben. Der WR müsste ja trotzdem Daten senden.

LG Sven

![20230501_182533](https://user-images.githubusercontent.com/132290316/235758686-bbdea3bf-06df-4de9-afb0-331a801c7a01.jpg)
![20230501_183147](https://user-images.githubusercontent.com/132290316/235758696-8e4440de-5a09-4137-b6c0-625917b97a59.jpg)
![20230501_183520](https://user-images.githubusercontent.com/132290316/235758701-92c2eeab-72d5-4fbb-ad50-1f57a0e29192.jpg)
![20230501_183558](https://user-images.githubusercontent.com/132290316/235758710-e74d49ce-bb34-426f-aef4-205057ab9c01.jpg)
![20230501_183909](https://user-images.githubusercontent.com/132290316/235758718-3234dfe7-06bd-48fc-aafe-5eaf31cb206d.jpg)
![20230502_192744](https://user-images.githubusercontent.com/132290316/235758719-a7a6bc02-5b17-4a0a-a043-4e689755893c.jpg)
![20230502_192934](https://user-images.githubusercontent.com/132290316/235758723-7f5eae63-1dbe-44dd-9220-d3491774e7c7.jpg)
![20230502_200516](https://user-images.githubusercontent.com/132290316/235758725-58f09c1c-7dd2-4008-93f5-ebed2ff9235a.jpg)
![20230502_200606](https://user-images.githubusercontent.com/132290316/235758727-04c40723-8fa6-4619-a0b6-f4250f445c49.jpg)
![20230502_201226](https://user-images.githubusercontent.com/132290316/235758730-e6e3cfc6-9c6f-4d44-ae19-cf356756584c.jpg)
![20230502_201254](https://user-images.githubusercontent.com/132290316/235758736-350eea08-37e8-4a0a-8e77-9e1ffe59e17b.jpg)

**Comment by mroenne2022** [comment]
![Screenshot_20230112_194830_Chrome](https://user-images.githubusercontent.com/114778920/235766047-46173b7e-3792-491a-bef8-3125fccf86fb.jpg)
In den Einstellungen müssen m.E. bei LED0 und LED1 auf off gestellt werden!? Sonst kollidiert das doch mit dem IRQ Port

**Comment by Piffekopp** [comment]
O.K.
Werde es morgen mal probieren. Danke schon mal für die rasche Antwort.

**Comment by mroenne2022** [comment]
Ja genau,  kannst das heute schon so einstellen und wirst morgen früh sehen das es dann sehr warscheinlich läuft sobald der WR erwacht ist 🌞👍

**Comment by cibis8** [comment]
Falls es doch morgen noch nicht gehen sollte, bitte mal die Lötstelle bei D4 nachlöten, sieht meiner Meinung etwas nach einer "kalten" Lötstelle aus.

**Comment by Piffekopp** [comment]
Hey.
Als ich das Bild gesehen habe dachte ich auch schon daran. Ist aber nur Flussmittel vom Lötzinn.

**Comment by mroenne2022** [comment]
@Piffekopp : Hast du die Einstellungen für LED0+1 auf OFF gesetzt ? Läuft es heute ?

**Comment by Piffekopp** [comment]
@mroenne2022 
Danke mein Freund. 👍  Hat tatsächlich daran gelegen. Funktioniert jetzt.
Hatte ja den Web Installer genutzt und bin davon ausgegangen, daß ich da nix mehr einstellen muss. :-/

Gruß Sven

**Comment by Piffekopp** [comment]
Davon abgesehen ist das alles noch Neuland für mich.

**Comment by mroenne2022** [comment]
@Piffekopp : Super,  ab jetzt wirst du dich nach und nach einarbeiten,  hier ständig mitlesen hilft sehr 👌
