### ISSUE TITLE
Ist das mit dieser Lizenz legal?? --> ahoy DTU Cloud

### ISSUE THREAD

**Issue by Mart-Muc** [lumapu/ahoy#924]
Hallo Lukas, hallo Team,

bin gerade über diese Seite "gestolpert", und frage mich nun, ob es moralisch vertretbar und legitim ist, Eure Arbeit kommerziell zu nutzen???
Also ich würde mich ausgenutzt fühlen - oder ist das einer von den Entwicklern hier?

Ich kenn mich aber mit der Gesetzgebung Null aus, deshalb auch nicht der direkte Link:
googelt mal nach: ahoy DTU Cloud

Danke für Eure Arbeit, lg Mart

**Comment by rmayergfx** [comment]
Ich weiss nicht warum du nicht den Link direkt hier rein kopiert hast, aber egal. 
Hast du mal genau gelesen was dort angeboten wird? Cloudspeicher:

> Diese Cloud übernimmt als günstige Alternative zur DTU pro das Monitoring, die Speicherung, und Visualisierung der ahoy DTU PV-Daten. Die open DTU wird ebenfalls unterstützt.

Wer also meint er müsste seine Daten in der Cloud ablegen kann dies doch gerne tun. Meine Daten gehen in keine Cloud, ich speichere alles lokal ab, da ist es mir auch egal ob der Anbieter dann die Hufe hochlegt und alle Daten weg sind, da man kein Backup hat.

Und von welcher Lizenz sprichst du hier? AhoyDTU und OpenDTU sind OpenSource und werden hier nicht tangiert.

**Comment by knickohr** [comment]
Ich glaube nicht das man dagegen was unternehmen kann oder auch soll. Schließlich bietet der Anbieter ja nur an die Daten aus Ahoy in eine Cloud abzulegen, so wie es viele auch mit HA oder sonstige MQTT Broker machen. Solange er nicht die Software Ahoy auf irgendwelchen DTU vertreibt ist es legal.

**Comment by Ollipop030** [comment]
Die vermieten nur eine Datenbank. Die DTU soll man sich ja auch selbst beschaffen, auf deren Homepage ist sogar eine Bauanleitung (inkl. Link zu diesem Repo). Unterstützt meiner Meinung nach sogar dieses Projekt.

**Comment by Harisjems** [comment]
Ich würde die Thema hier missbrauchen,ohne neue anzufangen.
Wie kann man die daten Lokal speichern.inkl. Monitoring usw.!?
Synology DS ist vorhanden und paar Rasperrys die sich langweilen.
Über Begriff Grafan,Home Asi usw.bin ich gestolpert,ist des einer von den richtige Ansatz!?

**Comment by knickohr** [comment]
MQTT, Grafana, HomeAssistant, Mosquitto, über REST-API auslesen …

Es gibt viele Möglichkeiten.

**Comment by Harisjems** [comment]
O.K. Danke

**Comment by mager33** [comment]
https://www.pv-argus.de/

**Comment by mager33** [comment]
PS: ich würde das NICHT so machen, da sie einen Portweiterleitung zur AhoyDTA/OpenDTU einrichten. Wehe, da ist in eigendeiner Libary eine noch nicht entdeckte Lücke, dann ist das ein prima Einfallstor. Deren Lösung ist ja für Leute ohne techn. Ahnung gedacht - die aktualisieren ihre IOT-devices auch nicht. Und die, die Ahnung haben brauchen sowas eh nicht.
