### ISSUE TITLE
[Bug] Reset funktioniert nicht

### ISSUE THREAD

**Issue by sri-elgora** [lumapu/ahoy#926]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

.

### Error description

Hallo,

Ein Reset des WR funktioniert bei mir nicht. Habe einen HM-1500 und einen HM-700 getestet. Weder über das Web-UI noch über die REST-API lässt sich ein Reset auslösen, die YieldDay-Werte bleiben stehen und die WR produzieren durchgängig weiter. Power Off und Power On funktioniert.

Grüße SRI

**Comment by rmayergfx** [comment]
Bitte in Zukunft auch einen passenden Titel für das Thema wählen, mit BUG alleine kann man nicht viel anfangen und dann wird es auch von einigen Leuten wegignoriert. Bitte etwas mehr Mühe geben!

**Comment by sri-elgora** [comment]
Sorry, übersehen, geändert.

Background: 
Ein HM-700 läuft bei mir direkt an einer 24V Batterie, per vzlogger und einer kleinen Regelung habe ich eine Nulleinspeisung gebastelt. Nach ca. 2-3 Tagen hört der WR aber einfach auf zu produzieren und ich muss ihn von der Batterie abklemmen, um den Mikrocontroller neuzustarten. Etwas mühlseelig. Dabei ist mir aufgefallen, dass Resetten nicht funktioniert. Ging auch in der 0.5.6 Version nicht.

**Comment by sri-elgora** [comment]
Fehler liegt hier, RestApi.h Zeile 556:

```
else if(F("restart") == jsonIn[F("restart")])  /* BUGFIX: jsonIn[F("cmd")] */
  accepted = iv->setDevControlRequest(Restart);
```

Hab's getestet indem ich den REQUEST-Parameter "restart=restart" per JSON an die REST-Api übergeben habe, dann hat er neu gestartet und die Werte waren resettet.
