### ISSUE TITLE
[Bug] MQTT sendet 0 bei YieldDay und YieldTotal

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#927]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.12

### Github Hash

f67a68e

### Build & Flash Method

ESP Tools (flash)

### Setup

Reset values when inverter status is 'not available - disabled

### Error description

MQTT sendet immer eine 0 bei YieldDay und YieldTotal wenn Inverter abends auf offline gehen, egal ob „ Reset values when inverter status is 'not available“ enabled oder disabled ist.

Fehler trat zum ersten Mal bei 0.6.10 auf.

**Comment by amzrhh** [comment]
Hi,Experts, my observations are the following:
 YieldDay and YieldTotal are sent by two topics: 1. inverter/total and 2. inverter/tsunny/ch0/ where tsunny is the given inverter name. Those sent by the 1. are 0 when the inverter goes offline. Topic 2. keeps the last values.
rgs amzrhh

**Comment by knickohr** [comment]
Thats correct. The second one is send for every inverter, thats OK. But the total Values should not redettet if not selected in the settings.

**Comment by lumapu** [comment]
@knickohr für mich klingt das eher nach der `neuen` Art des MqTT publish. Siehst du, ob alle Werte des Inverters nochmal geschrieben werden?
Ich habe gerade den Code geprüft und keinen Punkt gesehen, an dem 'versehentlich' der Reset ausgeführt wird.

**Comment by knickohr** [comment]
@lumapu 
Ja, das hat definitiv mit dem neuen zu tun. In 0.6.8 war das ja noch nicht drin. Hat auch sicher was mit dem zweiten Issue zu tun.

Und ja, es werden nochmal (alle) Werte gesendet nachdem die Inverter offline sind. Passiert so ca. bis zu einer Minute nachdem der Inverter offline geht. Ist mir aufgefallen weil einige Uhren im Node-Red wieder (falsche) Werte hatten.

Ist  halt doof da dann die Settings wertlos sind.

Stört mich persönlich recht wenig da ich es in Node-Red unterbinde, aber andere werden früher oder später drüber stolpern.

vielleicht hat das sogar auch was mit #949 zu tun ?

**Comment by lumapu** [comment]
ich kann es bei mir nicht nachvollziehen. Ich denke der Inverter geht kurz offline da zu wenig Spannung. Kurz später hat er nochmal genug Spannung, aber leider sind zu diesem Zeitpunkt alle Zähler schon 0. Kannst du dieses Szenario bei dir ausschließen?
Bei allen drei Invertern bei mir sind sowohl die YieldDay als auch die YieldTotal Werte noch vorhanden (jetzt um 23:23 Uhr). Interessant wäre zB. die Temperatur in deinem Fall, bei mir steht sie zB. noch auf 10,9°C und 11.1°C.

**Comment by knickohr** [comment]
Dieses blöde Total 😅

Ich meine nicht das Total der einzelnen Inverter sondern das Totale aufsummierte. Scheint auch nur ein Problem beim der Ausgabe von MQTT zu sein, das braune Feld im Webgui macht es nicht.

Ich umschiffe halt den Bug indem ich mir immer den höchsten Wert im Node-Red halte und ihn um Mitternacht selbst resette.

Und ja, ich kann das Szenario ausschließen da es jeden Tag mit jedem Inverter passiert. Wäre schon ein komischer Zufall. Ab und zu geht wirklich mal ein Inverter Off und dann wieder on. Dann ist er aber erst im Status Partial und das würde ich merken.

Wie gesagt, seit dem „Neuen“ sind einige so „Schmankerl“ reingekommen. Hab ja schon die Issues darauf untereinander verlinkt.

Mach Dir erst mal darüber nicht zuviel Kopf. Fällt wahrscheinlich auch nur denjenigen auf die pausenlos auf das Dashboard starren. Im Moment alles noch mit Node-Red vertuschbar 😉

Und es scheint auch nur ein Problem bei mehreren Invertern zu sein. Bei 9 fällt das halt schon gleich heftig auf 😅

Ach ja, die Temperatur bleibt komischerweise stehen. Hat sie aber schon immer gemacht.

**Comment by knickohr** [comment]
Ich hab’s gefunden 😲 Offensichtlich donnert MQTT nochmal alle Werte aller Inverter raus wenn der globale Status auf „offline“ geht. Und ich hab mich schon gewundert warum das mal früher oder später passiert.

**Comment by lumapu** [comment]
heute getestet und hat funktioniert - was sagt ihr?

**Comment by knickohr** [comment]
Geht nicht, der Build ging in die Hose 😲 Außerdem kann ich erst testen wenn es auch wieder mit dem S3 Fusion klappt 😇

**Comment by knickohr** [comment]
OK, ich werde es heute Abend sehen 👍

**Comment by knickohr** [comment]
👍

**Comment by knickohr** [comment]
Ich mach den mal wieder auf, weil das Problem wieder da ist ☹️

![IMG_0924](https://github.com/lumapu/ahoy/assets/63048210/7dc6cd88-0d8b-4408-b6f0-4ccb7fb70866)

**Comment by teletapi** [comment]
ja hab ich jetzt gerade auch mit meinem Issue gemacht habs auch gerade eben bemerkt

**Comment by MiniOh** [comment]
Ja, kann ich bestätigen.
Sowohl mit der 0.7.4, also auch 0.7.6 stimmen die Werte in der GUI aber nicht via MQTT.

**Comment by knickohr** [comment]
Er sendet jetzt schon wieder eine Null bei YieldDay 😢

![IMG_0934](https://github.com/lumapu/ahoy/assets/63048210/d2afa145-bd15-40a9-ba22-6a6c8408c58c)

Es ging, solange ein Inverter noch online war. Jetzt wo sie alle im Status 1 sind, geht der Wert wieder auf Null.

Nachtrag :
YieldTotal scheint zu funktionieren. Zumindest steht jetzt nachdem alles offline ist noch der Wert da.

**Comment by teletapi** [comment]
Ja so ähnlich sieht das bei mir auch aus, YieldTotal scheint aber zu senden aber YieldDay geht wenn die Produktion auf 0 geht ebenfalls auf null.
P/AC geht wieder auf 0 wie es sein soll

SW 0.7.6

![Screenshot_1](https://github.com/lumapu/ahoy/assets/94724873/07a5463b-aa9a-4930-9bc0-5bbacc4f43ef)

**Comment by knickohr** [comment]
Es geht noch weiter :  YieldDay wird teilweise auch noch falsch berechnet (bei mehreren Invertern), siehe Issue #929

**Comment by knickohr** [comment]
Yeahhh !  Das funktioniert jetzt (endlich) 😎 Am Ende werden auch nochmal schön alle Werte von allen Invertern raus gegeben 👍

Zu das Ding !

**Comment by MiniOh** [comment]
Aus meiner Sicht ist das noch nicht ganz gelöst.
Wenn alle Interver online sind und produzieren, dann aber einer nicht mehr produziert, werden erst mal 0 Werte bei YieldDay und Total AC per MQTT übermittelt und dann erst wieder die richtigen werte.

Zudem habe ich mit der 0.7.7 schon diverse DTU Reboots innerhalb eines Tages gehabt.
Ich bin wieder zurück zur aller ersten 0.6.10 HMS, die, zumindest bei mir, am besten läuft, abgesehn davon, dass abends hin und wieder falsche YieldDay liefert.

**Comment by knickohr** [comment]
Ist mir gestern Abend nicht aufgefallen. Wenn das aber nur einmal kurz kommt, dann kann gut sein das ich es übersehen habe.

**Comment by knickohr** [comment]
Hab’s eben nochmal beobachtet. Ich kann zu diesem Issue kein Problem mehr feststellen. Es kommt nur dann eine Null wenn die Inverter auch aus gehen. Nun ja,  es kommt eine Null bei /total/P_AC etwas zu früh, das ist aber Problem vom Issue #929 

Und eben den neuen Issue #1013

**Comment by lumapu** [comment]
> Zudem habe ich mit der 0.7.7 schon diverse DTU Reboots innerhalb eines Tages gehabt. Ich bin wieder zurück zur aller ersten 0.6.10 HMS, die, zumindest bei mir, am besten läuft, abgesehn davon, dass abends hin und wieder falsche YieldDay liefert.

Reboots beim ESP32? Das hatte ich noch nie

**Comment by lumapu** [comment]
@MiniOh bitte einen neuen Issue aufmachen, falls das Problem mit den Yields wie du beschrieben hast nochmal auftreten solte.

**Comment by MiniOh** [comment]
> > Zudem habe ich mit der 0.7.7 schon diverse DTU Reboots innerhalb eines Tages gehabt. Ich bin wieder zurück zur aller ersten 0.6.10 HMS, die, zumindest bei mir, am besten läuft, abgesehn davon, dass abends hin und wieder falsche YieldDay liefert.
> 
> Reboots beim ESP32? Das hatte ich noch nie

Ich auch nur mit der 0.7.7 gestern. Da kam ich nicht über 5min hinaus.
Kann es für die Software ein Problem sein, wenn ein Inverter einen Status lliefert, mit dem du nicht rechnest?
Gestern hatte ich einige Male bei dem der NA Schutz greift.
Also Spannung recht hoch, Inverter bleibt online, hört aber auf zu produzieren.
Ich weiß nicht ob dann ein anderer Status übermittelt wird.
In der GUI steht dann, Inverter online aber keine Erzeugung.

**Comment by lumapu** [comment]
nein der Inverter Status hat keinen Einfluss auf die Stabilität von Ahoy
