### ISSUE TITLE
[Bug] YieldTotal korrekt ausgeben auch wenn ein Inverter nicht online

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#929]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.12

### Github Hash

https://github.com/lumapu/ahoy/commit/f67a68e852306fb16b7287231256432c42843de4

### Build & Flash Method

ESP Tools (flash)

### Setup

MQTT enabled

### Error description

Mir fällt auf das über MQTT falsche, bzw. fehlende YieldTotal Werte ausgegeben werden. Es kommen nur die aufaddierten Werte der Inverter die online sind. Kurioserweise zeigt das Display an der DTU die korrekten aufsummierten Werte aller bekannten Inverter an, auch wenn einer oder mehrere nicht online sind.

![141AECD1-D2B1-452D-AF0C-EB3337C1BFFB](https://user-images.githubusercontent.com/63048210/236686506-ad3916bf-c728-44be-aced-3e3c36c38390.jpeg)

**Comment by knickohr** [comment]
Betrifft auch Abends das total/YieldDay 😞

![IMG_0933](https://github.com/lumapu/ahoy/assets/63048210/2c94aa4b-c3a7-4018-87e1-a6b6d1441fdc)
![IMG_0932](https://github.com/lumapu/ahoy/assets/63048210/69cbcdd6-0903-4e19-bcec-babd2ac414d8)

**Comment by lumapu** [comment]
ok, das liegt daran, dass vor dem Senden der Totalwerte geprüft wird, ob die Inverter 'avail' sind. Diese Prüfung muss raus, da Ahoy die Werte trotzdem noch hat und diese auch valide sind.

**Comment by knickohr** [comment]
Das scheint immer noch nicht ganz zu funktionieren. YieldDay und YieldTotal werden jetzt weitergezählt bis alle offline sind, aber das Power_AC geht auf Null sobald alle Inverter im Status 1 sind. A bisserl zu früh, das braune Feld im WebGUI zeigt noch ein paar Watt an 😉

![IMG_0962](https://github.com/lumapu/ahoy/assets/63048210/6eab58e9-2c7a-4d25-8b25-0dbad2b15b81)

![IMG_0961](https://github.com/lumapu/ahoy/assets/63048210/9898e591-5d10-4ee6-bdbf-94c80ed5c12a)

**Comment by knickohr** [comment]
Jetzt funktioniert’s mit der Nachbarin 😇
