### ISSUE TITLE
Feature Request: WLAN Passwort Länge

### ISSUE THREAD

**Issue by duenengeist** [lumapu/ahoy#93]
Hallo,

muss es hier in "defines.h" nicht 64 an Stelle von 63 heißen?

#define PWD_LEN             63

Ich muss es jedenfalls bei mir immer entsprechend anpassen, da mein WLAN einen Schlüssel mit voller Änge benutzt.

LG

Carsten

**Comment by stefan123t** [comment]
Carsten @duenengeist was ist eigentlich der Gewinn von 64 char Passwörtern, ich dachte immer WiFi wäre konsistent unsicher ?
Also ich habe auch 32 char, aber mehr halte ich persönlich für nicht sinnvoll, da das Protokoll bereits unsicherer ist als der Schlüssel, bei einem SSH Key mit RSA und 3072/4096 bit Länge o.a. kann ich Passwortlängen >=12 chars durchaus verstehen.
