### ISSUE TITLE
Hoymiles Crashes

### ISSUE THREAD

**Issue by IngoEF** [lumapu/ahoy#930]
Running hoymiles modul in RasPi suffering several crashes per day, alway getting two lines like following in logfile:
2023-05-07 19:43:22 CRITICAL: Exception catched: unpack requires a buffer of 2 bytes
2023-05-07 19:43:22 CRITICAL: None

What does it mean and how can I repair?

Am I right in this branch?

**Comment by rmayergfx** [comment]
What kind of Software is running on the Raspi ? Which Module do you mean?
Sorry, we can´t help without further information.

**Comment by IngoEF** [comment]
we are talking about ahoy/tools/rpi/hoymiles
the software starts with "python -um hoymiles" in the newest RasPi OS.
I have no idea, what more information I could provide.
The software feeds Volkszähler and was running stable since October last year but about two weeks ago reliabilty got lost without doing anything from my side.

**Comment by rmayergfx** [comment]
take a new SD Card and make a fresh setup and test again.

**Comment by lumapu** [comment]
is the issue still there?

**Comment by IngoEF** [comment]
I do not use it anymore
