### ISSUE TITLE
[Question] How to Turn On/Off an Inverter from Node-RED

### ISSUE THREAD

**Issue by Alpha4Linux** [lumapu/ahoy#933]
I would like to Turn On/Off a Hoymiles inverter via Ahoy.
Any recommendations / examples are very welcome.
I'm not very experienced with Node-RED and writing code yet; just started with that great community project.

**Comment by sstolk90** [comment]
This is the node-red code for limiting the hoymiles within Ahoy:
Paste this code into Node-Red by Ctrl+i and paste the code from below.

`[
    {
        "id": "a902690c81ae6589",
        "type": "inject",
        "z": "dfc5189934b7ea7c",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1200,
        "y": 620,
        "wires": [
            [
                "dce1a4db22a9f3de"
            ]
        ]
    },
    {
        "id": "dce1a4db22a9f3de",
        "type": "change",
        "z": "dfc5189934b7ea7c",
        "name": "0%",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "0",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1350,
        "y": 620,
        "wires": [
            [
                "17f91cdd3ce94b05"
            ]
        ]
    },
    {
        "id": "991382a826e0f854",
        "type": "change",
        "z": "dfc5189934b7ea7c",
        "name": "Baseline home",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "8",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1380,
        "y": 660,
        "wires": [
            [
                "17f91cdd3ce94b05"
            ]
        ]
    },
    {
        "id": "05b9a8a1b1fc97ab",
        "type": "change",
        "z": "dfc5189934b7ea7c",
        "name": "100%",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "100",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1350,
        "y": 700,
        "wires": [
            [
                "17f91cdd3ce94b05"
            ]
        ]
    },
    {
        "id": "17f91cdd3ce94b05",
        "type": "mqtt out",
        "z": "dfc5189934b7ea7c",
        "name": "Hoymiles Output Limit",
        "topic": "inverter/ctrl/limit/0",
        "qos": "",
        "retain": "",
        "respTopic": "",
        "contentType": "",
        "userProps": "",
        "correl": "",
        "expiry": "",
        "broker": "b058792e7980f060",
        "x": 1640,
        "y": 660,
        "wires": []
    },
    {
        "id": "6054e3ee702c7f8a",
        "type": "inject",
        "z": "dfc5189934b7ea7c",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1200,
        "y": 660,
        "wires": [
            [
                "991382a826e0f854"
            ]
        ]
    },
    {
        "id": "b9bd03c1848a8b4b",
        "type": "inject",
        "z": "dfc5189934b7ea7c",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1200,
        "y": 700,
        "wires": [
            [
                "05b9a8a1b1fc97ab"
            ]
        ]
    },
    {
        "id": "b058792e7980f060",
        "type": "mqtt-broker",
        "name": "Domoticz",
        "broker": "localhost",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "sessionExpiry": ""
    }
]`

**Comment by Alpha4Linux** [comment]
Did some JSON API tests; succeeded to power the Inverter On and Off via Ahoy DTU.
Next step will be to integrate that in Node-RED

![postman_JSON-Post_doc](https://github.com/lumapu/ahoy/assets/133150482/0f7d38b5-8eae-43b6-ae9b-d4eeb4075147)
