### ISSUE TITLE
Modulspannung steigt bei Drosselung

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#945]
Mahlzeit,
mal eine Frage. Bei WR Drosslung steigt die Modulspannung laut Ahoy auf über 40 Volt.
Ist das normal oder können die Module oder der WR davon beschädigt werden?

**Comment by knickohr** [comment]
Das ist ganz normal. Auch eine Abschattung treibt die Spannung nach oben. Die Leerlaufspannung der Module sollten aber niemals den Max. Spannungswert des Wechselrichters überschreiten. Bei Hoymiles sind das 60V.

**Comment by dtuuser** [comment]
Danke für die schnelle Rückmeldung. Dann kann ich die automatische Drosselung ja beruhigt weiter laufen lassen

**Comment by knickohr** [comment]
Dann mach zu das Ding.
