### ISSUE TITLE
Feature Request: Please use a Changelog

### ISSUE THREAD

**Issue by BernhardLinz** [lumapu/ahoy#95]
Please add and use a Changelog in the README.md of the the different tools like esp8266.
So "breaking changes" like renaming MQTT-Points or change PinOut can be seen before using them.

Thanks for the great projekt!

**Comment by lumapu** [comment]
Thanks for the hint. Normally I put my changelog direct to the commit message. I see the point to make it visible to all users using `README.md`

**Comment by BernhardLinz** [comment]
Thanks!

**Comment by lumapu** [comment]
Thanks to @stefan123t he had included all history of changes
