### ISSUE TITLE
Feature Request: Will the WeMos S2 mini be supported?

### ISSUE THREAD

**Issue by bltoby** [lumapu/ahoy#965]
A total newbie question 

WeMos S2 mini is also EPS32 based, although slashed to a single core, but comparing to D1 mini at about the same price, it provides a much 
better price performance ratio.

So my question is will WeMos S2 mini be supported by ahoy?

Thanks

**Comment by tastendruecker123** [comment]
Someone tried to add support a while ago, and though it was possible to compile Ahoy for the S2, it crashed when it tried to establish a wifi connection. I have ordered an S2 and I might get to play around with it in July, so it should be possible to make Ahoy run on the S2. The question is just whether supporting another ESP could make it harder to maintain the project.

**Comment by kscholty** [comment]
I tried it as well for the last few days.
It works fine in AP mode. As soon was it connects to to the WIFI in Station mode it seems to go into an endless loop. It's no crash, unfortunately but the chip gets extremely hot.
Tried the the latest  platform libs etc. to no avail.
Also deactivated all radio, mqtt, etc. but still it happens. The S2 mini does not expose the JTAG pins so that I can't debug it with my equipment.

It's probably something in the wifi setup. Which in theory should be quite straight forward.

**Comment by lumapu** [comment]
should be supported since version `0.7.42` from 2023-08-27

**Comment by DB1BMN-collection** [comment]
Hi, are there any progress supporting the S2 mini?
I've just received mine but can not install via Webinstaller (in Chrome of course).

I push the "0"-Butteon and then press Reset und releas it and release "0".
Some Devices (ESP32-S2, IcService_New and SMS/MMS) are listet in the Device Manager and a new Comport (COM6).
![grafik](https://github.com/lumapu/ahoy/assets/118214924/4b44219e-c7f1-48cc-b3a0-5b54543ee6f9)

But in the Webinstaller I cannot flash it. It says "Failed to initialize". The COM-Port will be recognized anyway.
Tried to press "0"-Button again bevor clicking "Install" but no success.
![grafik](https://github.com/lumapu/ahoy/assets/118214924/9bdc8a2c-508c-4d8b-bdb9-a95c1d0a3beb)

Any ideas?

**Comment by MetaChuh** [comment]
hi @DB1BMN-collection 

probier mal:

esp flash download tools hier herunterladen: [`Espressif Flash Download Tools V3.9.5`](https://www.espressif.com/sites/default/files/tools/flash_download_tool_3.9.5.zip)

v0.8.89 für esp32 s2 mini hier herunterladen: [`AhoyDTU-v0.8.89-ESP32-S2.zip`](https://github.com/lumapu/ahoy/files/14498785/AhoyDTU-v0.8.89-ESP32-S2.zip)

esp tools starten und uart auswählen.

screenshot:
<img width="245" alt="Bildschirmfoto 2024-03-05 um 17 51 01" src="https://github.com/lumapu/ahoy/assets/45773305/90d36d7d-85f7-4069-8186-8171a624090f">

alle 4 dateien genau wie auf folgendem screenshot hinzufügen,
anhaken zum aktivieren,
die richtige zieladresse angeben,
den com port der bei dir vorhanden ist und zutrifft auswählen.

screenshot:
<img width="531" alt="Bildschirmfoto 2024-03-05 um 18 06 07" src="https://github.com/lumapu/ahoy/assets/45773305/2a114cbe-385d-4e22-a33c-adbe541b7452">

dann zuerst <kbd>erase</kbd> klicken.
wenn das geklappt hat, dann auf <kbd>start</kbd> klicken und beten 😉

fehlersuche wenn es nicht funktioniert:
1) beim start von esp flash tools usb auswählen und erneut probieren.
2) diesen winchip ch34xser treiber für win10/11 arm64/x64 im gerätemanager installieren:
[`WinChip CH341SER (wch.cn) win11 x64-arm64 drivers.zip`](https://github.com/lumapu/ahoy/files/14499022/WinChip.CH341SER.wch.cn.win11.x64-arm64.drivers.zip)
danach im uart mode erneut probieren.
3) benzin holen, auf den s2 gießen, anzünden (im freien).
danach nicht mehr probieren, aber bitte fotos davon posten 😉

greetings,
metachuh

**Comment by DB1BMN-collection** [comment]
Wow, danke, das Programmieren hat soweit geklappt, glaube ich.
![grafik](https://github.com/lumapu/ahoy/assets/118214924/225b021a-9d51-4514-9257-0c376abc55be)

Konsolen-Ausgabe:
`Uploading stub...
Running stub...
Stub running...
Changing baud rate to 115200
Changed.
SPI_BOOT_CRYPT_CNT 0
SECURE_BOOT_EN False
Compressed 13648 bytes to 9600...
Compressed 3072 bytes to 146...
Compressed 8192 bytes to 47...
Compressed 1194736 bytes to 784578...

 is stub and send flash finish`

Aber nach dem Neustart sehe ich keinen WLAN-Access-Point mit der SSID "AHOY-DTU".
Habe es dann auch mit "USB" für "LoadMode" probiert
Weitere Ideen?

Das mit dem Anzünden ist keine gute Option. FR4 brennt nicht besonders gut: https://www.mikrocontroller.net/topic/565226

**Comment by MetaChuh** [comment]
erster schritt (flashen) ist mal ein teilerfolg 👍

> Aber nach dem Neustart sehe ich keinen WLAN-Access-Point mit der SSID "AHOY-DTU".

hänge den s2 mal am pc, linux, mac auf einen usb port,
starte chrome/chromium,
öffne die seite [`https://ahoydtu.de/web_install`](https://ahoydtu.de/web_install/)
klicke auf connect
wähle usb2.0-Ser aus
klicke auf `Logs & Console` wie am folgenden screenshot:

<img width="1093" alt="Bildschirmfoto 2024-03-05 um 23 21 42" src="https://github.com/lumapu/ahoy/assets/45773305/7932a5b4-f3a2-40c6-ad4a-db82ddeab175">

beobachte und poste das serial log in copy/paste textform, oder als screenshot hier.
beispiel screenshot:
<img width="967" alt="Bildschirmfoto 2024-03-05 um 23 34 39" src="https://github.com/lumapu/ahoy/assets/45773305/b7e2bd1d-bca2-4cc7-9dd1-83b61af9a4ce">

hoffe du siehst keine fehlermeldung, und keinen black screen mit nur einem `>` cursor.

> Das mit dem Anzünden ist keine gute Option. FR4 brennt nicht besonders gut: [https://www.mikrocontroller.net/topic/56](https://www.mikrocontroller.net/topic/565226)

in dem thread hat ja auch noch keiner benzin darauf gegossen ... wär lustig wenn du den microcontroller thread noch mit dem wort "benzin" ergänzt 😂

**Comment by DB1BMN-collection** [comment]
Leider doch nur ein schwarzes Terminal und ein leeres Prompt.
Scheint, als wäre der ESP verfused.
Also doch anzünden?

**Comment by MetaChuh** [comment]
... und dabei das lied "me gusta la gasolina" anhören ;-)

**Comment by peterhax** [comment]
Moin,

ich habe auch noch etwas rumprobiert und ich konnte mein S2 mini mit dem esptool.py erfolgreich bespielen und in Betrieb nehmen ...

1. Speicher löschen ...
`python esptool.py -p COM5 --chip esp32s2 erase_flash`

2. Firmware flashen mit folgenden Offsets ...
`python esptool.py -p COM5 -b 115200 --before default_reset --after hard_reset --chip auto  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 bootloader.bin 0x8000 partitions.bin 0xe000 ota.bin 0x10000 240302_ahoy_0.8.89_0d7c67d_esp32-s2-mini-de.bin --force`

![grafik](https://github.com/lumapu/ahoy/assets/127313371/757420b4-ed92-4a2a-8862-0d05d654b913)

**Comment by MetaChuh** [comment]
@peterhax 

danke dir für die info 👍

wenn du lust hast, oder einen zweiten s2, kannst du mal den neuen ahoydtu web flasher beta, mit freier versions- und sprachauswahl aus dev und release antesten.
(alle anderen environments wurden erfolgreich getestet, nur eben der s2 noch nicht.)

[`https://solar.metacontrol.eu/webinstall`](https://solar.metacontrol.eu/webinstall/)

<img width="1061" alt="Bildschirmfoto 2024-04-16 um 18 32 17" src="https://github.com/lumapu/ahoy/assets/45773305/f8ed0a74-f2ba-4d62-b326-17f0d3eda91c">

unser ziel: die erstinstallation und das re-flashen via usb soll für alle so einfach und selbsterklärend wie möglich werden, und wenn geht auch zu 99.9% funktionieren.


greetings,
metachuh

**Comment by peterhax** [comment]
Moin,

hat direkt funktioniert! Hab einen neuen S2 mini genommen und mit GPIO0 halten, Reset kurz drücken und GPIO0 loslassen in den Bootmodus versetzt, wurde direkt erkannt und der Flashvorgang wurde durchgeführt. 

![Screenshot 2024-04-16 210732](https://github.com/lumapu/ahoy/assets/127313371/5ac6e1b1-980e-4110-b334-ff15554b6b30)

![Screenshot 2024-04-16 210842](https://github.com/lumapu/ahoy/assets/127313371/b1831b63-73a5-468a-a704-8579be200d47)

BTW: Verbinden zum Netzwerk funktioniert ... allerdings nur wenn man per USB einmalig auf die serielle Schnittstelle zugreift ... klingt nach einem Bug ... S2 spezifisch? Wenn ich mich per Putty draufschalte beginnt er direkt sich in das Heimnetz einzuwählen, sonst nicht. Ist mir bei meiner Variante garnicht aufgefallen, da ich immer per serielle Konsole mit drauf war ...

Tolle Arbeit von Euch!

**Comment by MetaChuh** [comment]
@peterhax 

suuuuper, danke dir für die info, das testen, und vor allem an das lob 👍🤗🙏

wir werden uns das mit der seriellen schnittstelle bei s2 nochmals ansehen.
aus mangel an s2 wissen wir dies leider noch nicht.

die meisten tests die wir momentan in der community durchführen sind auf esp8266 (legacy support für schwächere, jedoch bestehende und darum nach wie vor wichtige hardware), esp32 wroom, und die esp32-s3 boards, sowohl die selbstgebastelten, als auch die community fusion boards.

greetings & thanks,
metachuh

**Comment by MetaChuh** [comment]
ps:
> GPIO0 halten, Reset kurz drücken und GPIO0 loslassen

ja, unsere anleitung im web installer sollte diesbezüglich von uns überarbeitet werden.
ähnliches gilt für das fusion board, und boot taste halten und wärenddessen kurz auf die reset taste drücken.

wir wissen jedoch noch nicht, wie wir alle plattform abhängigen anleitung automatisiert einblenden können, da die web seite nicht weiß welcher esp typ angeschlossen ist, bevor man auf installieren klickt.

(wenn wir alle hypothetischen anleitungen einblenden würden, ist das nicht nur für neue user zu viel, sondern auch für experts und power user)
