### ISSUE TITLE
Ahoy Release 069 

### ISSUE THREAD

**Issue by Esp82662023** [lumapu/ahoy#969]
## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [ ] circuit board
* [x] external antenna (SMA)

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by Esp82662023** [comment]
Hallo , 
bin neu hier und versuche nach diversen Lötarbeiten (Wmos d1 Mini v3 & NRF24L01+) die Ahoy DTU zum laufen zu bekommen.Verbindung intern steht  ,komme ins Ahoy Menü usw. nur bekomme ich keine Live Daten vom WR angezeigt( Inverter #0: 1500HR.EU.HM (v0) is not yet available) .Habe nun zwei verschiedene DTU’s versucht ,einmal mit Print Antenne das zweite Setup mit Stabantenne , jedoch wie in einem anderem Fall von Euch beschrieben ,nach Update keine Verbindung mehr zum WR ein Downgrade schafft Abhilfe.Wenn ich eine ältere Release über die Weboberfläche installiere funktioniert der Wemos danach nicht mehr .Gibt es eventuell für mich unwissenden eine andere Möglichkeit das Teil zum laufen zu bringen ?

**Comment by rejoe2** [comment]
Die LED-GPIO-Settings bitte...?

Die sollten im Zweifel auf "off" stehen.

**Comment by Esp82662023** [comment]
CS- D8 Gipo15
CE - D4 Gipo2
IRQ -D3 Gipo0
LED0- off/default
LED1- off/default
LED Polarität - los active

**Comment by rejoe2** [comment]
Die IRQ-Zuodnung paßt auch?

Ahoy zeigt "is connected" für den nRF?

Wie ist das Invervall? Versuch's mal mit 5 Sekunden und bitte die Sendeleistung nicht über "LOW".

Wie schaut die Kommunikation auf der seriellen Konsole aus? Gar keine Rückmeldung (vermutlich) oder immer nur unvollständig?

Ggf. mal versuchen, den nRF über einen eigenen DC-DC-Konverter zu versorgen.

**Comment by Esp82662023** [comment]
Ahoy zeigt : Radio nrf24l01+ is connected

Auf Deine Frage mit der IRQ Zuordnung weis ich keine Antwort weil ich keinen Plan davon habe 🙈,das betrifft ebenso die serielle Konsole…..

Sendeleistung habe ich jetzt wieder auf Low , ich werde mal noch ein stärkeres Netzteil versuchen dieses hat nur 1A .

**Comment by Esp82662023** [comment]
Unter dem Button Serial/aConsole steht :connectet (grüne LED)

**Comment by Esp82662023** [comment]
Hier mal ein kleiner Mitschnitt aus der Console:
20:25:05 I: (#0) resetPayload
20:25:05 I: (#0) prepareDevInformCmd 0x0b
20:25:05 15 pid: 80
20:25:05 I: TX 27B Ch23 | 15 84 89 38 21 84 16 47 44 80 0b 00 64 74 ee 01 00 00 00 00 00 00 00 00 47 07 a4 
20:25:10 I: (#0) resetPayload
20:25:10 I: (#0) enqueCommand: 0x01
20:25:10 I: (#0) enqueCommand: 0x0b
20:25:10 I: (#0) prepareDevInformCmd 0x01
20:25:10 15 pid: 80
20:25:10 I: TX 27B Ch40 | 15 84 89 38 21 84 16 47 44 80 01 00 64 74 ee 06 00 00 00 00 00 00 00 00 7d 2b bf 
20:25:15 I: (#0) resetPayload
20:25:15 I: (#0) prepareDevInformCmd 0x0b
20:25:15 15 pid: 80
20:25:15 I: TX 27B Ch61 | 15 84 89 38 21 84 16 47 44 80 0b 00 64 74 ee 0b 00 00 00 00 00 00 00 00 e7 79 70 
20:25:20 I: (#0) resetPayload
20:25:20 I: (#0) enqueCommand: 0x01
20:25:20 I: (#0) enqueCommand: 0x0b
20:25:20 I: (#0) prepareDevInformCmd 0x01
20:25:20 15 pid: 80

**Comment by Esp82662023** [comment]
Habe noch einen anderen Thread gefunden mit gleichem Problem dort wurde dann IRQ auf D4 und CE auf D3 getauscht (habe ich jetzt über die Software gemacht) probiere ich morgen ob es läuft,auf jeden Fall leuchtet nun die blaue LED nicht mehr………

so die Softwareänderung der IRQ und CE hat nichts gebracht …werde jetzt einen ESP32 ordern und neues Funkmodul

**Comment by mtet2** [comment]
Bei mir läuft die ahoy-dtu auf dem "Wmos d1 Mini Board" nur mit der folgenden Einstellung und nätürlich auch mit der dazu passenden Verdrahtung:
![AhoyDTU_setting](https://github.com/lumapu/ahoy/assets/120575424/ed96e757-c2e7-451b-bfc7-f79ee455e71c)

Einen Versuch wäre es wert.
Bei deinem Softwaretausch hast du auch die Verdrahtung angepasst?  Die richtige Seriennummer ist eingegeben? Viel Glück Manfred

**Comment by Esp82662023** [comment]
Grüße Manfred
Die Verdrahtung hatte ich nicht geändert sondern nur die Ports über soft , aber Deine Belegung werde ich gleich mal probieren

**Comment by heldmannm** [comment]
Habe keinen neuen WR und auch keine Update auf diesem durchgeführt und es geht trotzdem nicht. Der WR lief über Monate mit der Software v.0.5.66 kaum auf die neue 0.6.9 und nichts geht mehr. Alles was in diesen beiden threat's eingestellt wurde habe ich ausprobiert und NIX

**Comment by Esp82662023** [comment]
Ich denke auch das Hoymiles da was geändert hat damit man ihre kostenintensive Lösung kaufen muss, eventuell finden ja die Softwareprofis hier noch eine Lösung ……😎

**Comment by lumapu** [comment]
@heldmannm leider weiß ich es nicht mehr ganz genau, aber ca. zu Version 0.6.0 haben wir stark an der Kommunikation geschraubt.
Würdest du verschiedene Versionen testen, wenn ich sie hier poste? Dadurch könnten wir besser verstehen würdig der Fehler auftritt

**Comment by Esp82662023** [comment]
Klar kann ich tun ,habe nur das Problem das ich kein Linux habe ,aber kann ja das Update über die Ahoy direkt machen oder ? Probiere morgen noch eine ESP32 anstatt des Wmos

**Comment by Esp82662023** [comment]
Guten Morgen,habe soeben mit dem ESP32,Antennenmodulmit externer Stabantenne und Display versucht und ZACK es läuft .

**Comment by Esp82662023** [comment]
![image](https://github.com/lumapu/ahoy/assets/134935845/5395b023-4cbe-4139-b2d9-b55d0c0b3dd5)

**Comment by Esp82662023** [comment]
ich werde nochmals einen Wmos versuchen und dann berichten

**Comment by Officer-on-duty** [comment]
Ich habe ziemlich alles probiert.
 
Letztlich hat bei mir ein Wechsel des IRQ von D3 auf D1 zu Erfolg geführt.
Also gelb von D3 auf D1 **und** in der Weboberfläche unter „System Config“ ändern.

Viel Erfolg!

![grafik](https://github.com/lumapu/ahoy/assets/131025588/f1c6718c-282b-4832-83bb-7a789ad2a23d)

**Comment by Esp82662023** [comment]
Werde ich dann nochmals testen bei mir sind ja 3 Einheiten da zum Versuch plus ESP32
Wobeigenau dieser sehr instabil läuft die Verbindung bricht ständig ab vor allem wenn der WR heis ist

**Comment by Esp82662023** [comment]
Also wie du es beschreibst gelbes Kabel  von D3 auf D1 und das blaue vomDisplay von D1 auf D3 und alles läuft ☺️ach so und natürlich den IRQ in der Soft sowie das Display Clock auf D3

**Comment by lumapu** [comment]
cool 😅👍

**Comment by Roy12343** [comment]
[Esp82662023] Das erste habe ich verstanden (gelbes Kabel von D3 nach D1),
aber was heißt: blaues vom Display von D1 nach D3, welches display??? Und von wo nach wo?? Wird jetzt D3 mit blauen Kabel was vom Radio(NRF....)kommt, belegt???

**Comment by Officer-on-duty** [comment]
Ich war nach dem "erstens" auch fertig
Blaues vom Display versstehe ich auch nicht. 
Das blaue Kabel geht vom NRF24 Pin SCK (Serial Clock) auf den D5-Pin beim D1-Mini. Daran habe ich nix geändert.  Wie übrigens auch an allen aderen nicht.
Ich hab nur ein 2A Netzzeil, den Kondensator und das Ding sehr nah am Wechselricherter. Allerdings hat das alles alleine keinen Erfolg gehabt. Erst der Wechsel vom Interrupt (IRQ) Pin (gelbes Kabel) hat geholfen.
So long!

**Comment by Esp82662023** [comment]
mann kann ein kleines Display an die Ahoy stecken was sehr gut funktioniert hier mal meine Steckverbindungen:

<img width="773" alt="Bildschirmfoto 2023-06-05 um 09 16 43" src="https://github.com/lumapu/ahoy/assets/134935845/3bce4488-55aa-4122-be25-9f51c2311c9e">


<img width="225" alt="Bildschirmfoto 2023-06-05 um 09 18 47" src="https://github.com/lumapu/ahoy/assets/134935845/35520c98-a775-4808-ae08-be78be32927c">

Die Wlan Verbindung über den Wmos ist wesentlich stärker als die des ESP32 , der einzigste Vorteil des ESP32 ist das mehr Masse Ports frei sind für den Anschluss des Display ,hier muss man nämlich den GND vom Wmos doppelt belegen für NRF24 & Display & natürlich den Kondensator am Spannungseingang des NRF.

**Comment by Roy12343** [comment]
Bei mir hat's auch geklappt. IRQ von D3 nach D1 am wmos und settings IRQ auf D1,
dann Leistung setzen. Prima , Vielen Dank.

**Comment by JeaneLG** [comment]
Ich habe nur D3 und D4 vertschaut und es hat funktioniert.
