### ISSUE TITLE
setting "power limit" via MQTT, persistent / harmful for eeprom? 

### ISSUE THREAD

**Issue by stundenblume** [lumapu/ahoy#972]
Hi everyone,

1. Thank you for this great software!

If I set the "power limit" via MQTT, is it persistent?
More important: Is it harmful for the hardware to change the power setting often?

Thanks very much,
Sebastian

**Comment by knickohr** [comment]
There are several ways to set the power limit :
https://github.com/lumapu/ahoy/blob/main/User_Manual.md#active-power-limit-via-serial--control-page

**Comment by stundenblume** [comment]
Thank you!
That was the [information](https://github.com/lumapu/ahoy/blob/main/User_Manual.md#power-limit-persistent) I was looking for.
