### ISSUE TITLE
MQTT setting limit not working

### ISSUE THREAD

**Issue by hseibel12** [lumapu/ahoy#974]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

square dot

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.15

### Github Hash

6dcf5ee

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT: Broker added (mqtt.eclipseprojects.io)
TOPIC: (1) Long Topic using Chars, Numbers and Special Chars,  (2) Short Topic only using 7 Numbers

### Debug Serial Log output

```shell
16:31:52 I: 
16:31:52 I: (#0) resetPayload
16:31:52 I: (#0) Requesting Inv SN 114182945385
16:31:52 I: (#0) enqueCommand: 0x0b
16:31:52 I: (#0) prepareDevInformCmd 0x0b
16:31:52 15 pid: 80
16:31:52 I: TX 27B Ch23 | 15 82 94 53 85 81 39 56 00 80 0b 00 64 7d f1 d8 00 00 00 22 00 00 00 00 ec 17 59 
16:31:52 I: RX 27B Ch61 | 95 82 94 53 85 82 94 53 85 01 00 01 01 22 04 52 0c 7e 01 2a 02 51 06 e6 00 00 0a 
16:31:52 I: RX 27B Ch40 | 95 82 94 53 85 82 94 53 85 02 84 a2 00 00 93 cd 07 d9 09 54 09 5a 13 87 12 84 3d 
16:31:52 I: RX 23B Ch40 | 95 82 94 53 85 82 94 53 85 83 00 00 00 c6 03 e8 01 c9 00 22 c8 d9 c0 
16:31:52 I: procPyld: cmd:  0x0b
16:31:52 I: procPyld: txid: 0x95
16:31:52 I: Payload (42): 00 01 01 22 04 52 0c 7e 01 2a 02 51 06 e6 00 00 84 a2 00 00 93 cd 07 d9 09 54 09 5a 13 87 12 84 00 00 00 c6 03 e8 01 c9 00 22 
16:31:57 I: Iv: 0
16:31:57 I: MyPV/ch1/U_DC: 29.000 V
16:31:57 I: MyPV/ch1/I_DC: 11.060 A
16:31:57 I: MyPV/ch1/P_DC: 319.800 W
16:31:57 I: MyPV/ch1/YieldDay: 2009.000 Wh
16:31:57 I: MyPV/ch1/YieldTotal: 33.954 kWh
16:31:57 I: MyPV/ch1/Irradiation: 87.616 %
16:31:57 I: MyPV/ch2/U_DC: 29.800 V
16:31:57 I: MyPV/ch2/I_DC: 5.930 A
16:31:57 I: MyPV/ch2/P_DC: 176.600 W
16:31:57 I: MyPV/ch2/YieldDay: 2388.000 Wh
16:31:57 I: MyPV/ch2/YieldTotal: 37.837 kWh
16:31:57 I: MyPV/ch2/Irradiation: 48.384 %
16:31:57 I: MyPV/ch0/U_AC: 239.400 V
16:31:57 I: MyPV/ch0/I_AC: 1.980 A
16:31:57 I: MyPV/ch0/P_AC: 474.000 W
16:31:57 I: MyPV/ch0/F_AC: 49.990 Hz
16:31:57 I: MyPV/ch0/PF_AC: 1.000 
16:31:57 I: MyPV/ch0/Temp: 45.700 °C
16:31:57 I: MyPV/ch0/ALARM_MES_ID: 34.000 
16:31:57 I: MyPV/ch0/YieldDay: 4397.000 Wh
16:31:57 I: MyPV/ch0/YieldTotal: 71.791 kWh
16:31:57 I: MyPV/ch0/P_DC: 496.400 W
16:31:57 I: MyPV/ch0/Efficiency: 95.488 %
16:31:57 I:
```

### Error description

Setting limit not working either using long topic or short topic.
I've been using command <topic>/ctrl/limit/0 99 as explaind in documentation, sent by MQTT-Explorer in raw format (no json).
Setting power limt from web interface works well.

Any suggestion what to do?
Can anyone confirm a working system?

**Comment by beebee** [comment]
Are you sure you have the topic right?
At the MQTT settings in ahoy - default is "inverter", seems to be missing on your comments?


`Message 2 received on inverter/ctrl/limit/0 at 17:20:
75W
QoS: 0 - Retain: false
Message 1 received on inverter/ctrl/power/0 at 17:12:
1
QoS: 0 - Retain: false`

`
17:22:00 I: MQTT got topic: inverter/ctrl/power/0
17:22:00 I: (#0) resetPayload
17:22:00 I: sendControlPacket cmd: 0x01
17:22:00 51 pid: 81
17:22:00 I: TX 15B Ch40 | 51 74 95 31 03 84 96 00 48 81 01 00 20 00 78 
17:22:00 I: MQTT got topic: inverter/ctrl/limit/0
17:22:00 I: (#0) resetPayload
17:22:00 I: sendControlPacket cmd: 0x0b
17:22:00 51 pid: 81
17:22:00 I: TX 19B Ch61 | 51 74 95 31 03 84 96 00 48 81 0b 00 00 00 00 00 60 01 33 
`

Works here with Home Assistant and mosquitto

**Comment by hseibel12** [comment]
No, I do not use the word 'inverter' in my topic! For better understandig i post my settings for mqtt:

Broker/Server/IP:   mqtt.eclipseprojects.io
Username:
Password:
Topic:    my_personal_topic

when publishing the limit command in MQTT-Explorer I use the line:      my_personal_topic/ctrl/limit/0 75W

Is there anything missing? As I understood the docs I have to substitute the word 'inverter' by my own topic and this is 'my_personal_topic'. Am I wrong?

**Comment by beebee** [comment]
Maybe related to #889 ?
Seems I cannot help much here - I tested MQTT Explorer on my local Broker Instance and this works but I am only using the default Topic locally and not a longer one...

**Comment by hseibel12** [comment]
Thank's beebee!
I changed my setting using a local mqtt broker (mosquitto on RaspberryPi). Additionally I changed the topic back to 'inverter'  acc. your suggestion. Now it works!
