### ISSUE TITLE
setting sporadisch weg...

### ISSUE THREAD

**Issue by smarteshome2020** [lumapu/ahoy#977]
Hi, 
sporadisch ist die Startseite des Ahoy um einige Menüpunkte reduziert. 
Einige Minuten später oder nach einem Power down geht es wieder und alle Parameter sind wie gewohnt verfügbar.

Board: ESP8266
V0.6.9

![image](https://github.com/lumapu/ahoy/assets/97242825/506d89f3-fa2a-44a7-b6ab-ca75d0165a2d)

**Comment by smarteshome2020** [comment]
nochmal zum vergleich. Leider keine Ahnung was du für Daten zur Analyse benötigst.

![image](https://github.com/lumapu/ahoy/assets/97242825/67c80cc7-a569-47a4-8412-e28ee5399d74)

**Comment by HFarryranz** [comment]
Habe ich auch immer wieder einmal. Manchmal startet der ESP neu. 
Meist wenn ich auf LIVE schalte bzw evtl. bei schnellen Seitenwechseln.

V: 0.7.1
Geht aber schon durch alle Versionen so.

**Comment by knickohr** [comment]
Das ist der 8266, der ist am Limit, muß zu viel machen.

Nimm einen ESP32 und die Probleme sind weg 😉

**Comment by smarteshome2020** [comment]
Danke, aber was soll da jetzt "enabled" werden. Diesen Haken finde ich dort nicht. 
Habe mal auf "max" umgestellt, bin mir aber nicht sicher ob das gemeint war und was es bringt.

![image](https://github.com/lumapu/ahoy/assets/97242825/89e791c5-b1da-4d28-a189-f61acf3c40c2)

**Comment by Harald-U** [comment]
Setzt den Powerlevel wieder runter auf LOW, sonst hast Du nur noch mehr Probleme ... außer Dein WR ist sehr weit weg.

Du must gar nichts enablen, ich hatte da ein Problem mit der neuen Dev-Version 0.7.1, da fehlt nach dem Flashen ein Haken fürs Funkmodul (Issue #979). Ich habe am Ende dieses Issue gelinkt, weil mit der Version 0.7.1 jetzt Dein Problem bei mir auch gehäuft auftaucht. Und Github fügt dann diesen Querverweis in Deinem (diesem) Issue ein ...
