### ISSUE TITLE
[Bug] Version 0.7.1 "your NRF24 module can't be reached"

### ISSUE THREAD

**Issue by Harald-U** [lumapu/ahoy#979]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.1

### Github Hash

f0848ec

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT Broker gesetzt, Intervall 0

### Error description

Über funktionierende Version 0.6.15 die Version 0.7.1 geflashed (über "Update" im Webinterface).

Nach Start zeigt die AhoyDTU-Seite "your NRF24 module can't be reached, check the wiring and pinout"

![Ahoy_0 7 1](https://github.com/lumapu/ahoy/assets/8513585/847ea035-48dc-44b9-8499-e141b644aa4b)

Log von Update auf 0.7.1 bis Downgrade 0.6.15: 
[Ahoy_0.7.1.log](https://github.com/lumapu/ahoy/files/11679804/Ahoy_0.7.1.log)

**Comment by Tanakkara** [comment]
in System Config das NRF Modul ausgewählt?
Nach Installation von 0.7.1 war bei mir weder NRF noch CMT ausgewählt.

**Comment by knickohr** [comment]
Schau Dir auch mal #978 an.

**Comment by kiu77** [comment]
Der "bug" besteht lediglich darin, dass in 0.7.1 der Haken bei _Settings_ -> _System Config_ bei _NRF24 Enable_ nicht gesetzt ist. Setzen, saven und alles ist gut.

![Bildschirmfoto 2023-06-08 um 11 47 20](https://github.com/lumapu/ahoy/assets/43971413/ef55312f-86ed-451f-b00f-054878d99f48)

**Comment by lumapu** [comment]
richtig, ich werde das für den ESP8266 entfernen, das es dort keinen Sinn ergibt.
Die Änderung kam durch den HMS/HMT Support rein.

**Comment by Harald-U** [comment]
Super, danke, genau das war es. Ich hatte wohl Tomaten auf den Augen, die Checkbox war mir gar nicht aufgefallen.

Inzwischen hab ich vermehrt das Problem von [#977](https://github.com/lumapu/ahoy/issues/977) ... ich werde das wohl auf einen ESP32 umbauen müssen.

**Comment by Harald-U** [comment]
Das kann dann wohl zugemacht werden, danke für Eure Hilfe!!!
