### ISSUE TITLE
Prevent sending not updated data over MQTT - Die Zweite !

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#982]
Ich dachte wir haben das „Rauskotzen“ aller Werte mit Issue #826 schon mal gelöst ?  Nun scheint es aber das es wieder da ist 😵

Ist mir heute aufgefallen als ich mal zufällig den Datenstroms angeschaut habe. Bin fast vom Hocker gefallen als ich diesen Datenwulst gesehen habe.

![IMG_0901](https://github.com/lumapu/ahoy/assets/63048210/f5633376-7c4f-40a5-aa78-270fd0b06a10)

Bitte wieder reparieren und auch nur Daten senden die upgedated wurden, keine alten Daten wiederholen. Das obige Bildchen ist nur ein Auszug, das sind mehrere Dutzend Meldungen innerhalb einer Sekunde. Bei 10 Invertern ist das schon heftig 😲 Ich habe eigentlich erwartet das immer nur max. die Datenpakete eines Inverters innerhalb eines Intervals kommen und nicht deren aller 10 Inverter.

**Comment by lumapu** [comment]
der Einfachheit halber ist dieses Phänomen wohl geschuldet. Aktuell wird nur das angefragte Kommando an MqTT übergeben - dieses 'loopt' über alle Inverter und gibt deren Werte aus. Ich schaue mal was sich hier optimieren lässt.

**Comment by lumapu** [comment]
biite erneut testen, ich glaube es 'erwischt' zu haben

**Comment by knickohr** [comment]
Geht nicht, der Build ging in die Hose 😲 Außerdem kann ich erst testen wenn es auch wieder mit dem S3 Fusion klappt 😇

**Comment by knickohr** [comment]
Hab extra wieder das gute alte „DukeWolle“ Board raus gekramt 😉

Ja, jetzt klappt’s wieder mit der Nachbarin 😎

![IMG_0905](https://github.com/lumapu/ahoy/assets/63048210/6262611b-1921-448e-b8dc-c49c6167c5fd)

Interessanter Nebeneffekt :  Mein Node-Red Dashboard ist jetzt auch wieder flüssiger. Klar, wenn es nicht immer von Daten überschüttet wird 👍

**Comment by lumapu** [comment]
welcher issue beschreibt das Problem mit s3 fusion?

**Comment by knickohr** [comment]
Es gibt kein Issue, aber offenbar gehört PR #961 dazu.

Es funktioniert nicht, wenn ein ePaper dran hängt. Deaktiviert man es, dann scheint der NRF wieder zu funktionieren.

**Comment by knickohr** [comment]
Kann man eigentlich zu machen, das Ding ist durch 👍
