### ISSUE TITLE
[Bug] Fehlende Einheit % in Live-Anzeige Irradiation ab 0.7.2

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#986]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.3

### Github Hash

4e54bcf

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

standard
with 2 inverters

### Error description

Fehlende Einheit % in Live-Anzeige Irradiation ab 0.7.2
Vorher war diese %-Einheit noch da.
Nicht wichtig, aber es wäre schön, wenn sie wieder da wäre.
![Bildschirmfoto 2023-06-11 um 16 30 27](https://github.com/lumapu/ahoy/assets/43971413/0a757f00-2320-46e3-b20b-5e232ec0a028)

**Comment by lumapu** [comment]
it came with the merge of HMS / HMT contents, will be fixed this evening

**Comment by kiu77** [comment]
Thank you!
