### ISSUE TITLE
[Bug] MQTT sendet kein P_AC wenn Inverter im Status 1

### ISSUE THREAD

**Issue by knickohr** [lumapu/ahoy#987]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.3

### Github Hash

bdf43fd

### Build & Flash Method

ESP Tools (flash)

### Setup

MQTT, Nighttime, Display enabled.

### Error description

Wir haben uns mit dem Fixen von Issue #980 bzw. #927 offenbar ein neues Problem eingefangen :

MQTT sendet über total/P_AC keine Werte mehr wenn ein Inverter in den Status <INVERTER_NAME_FROM_SETUP>/available = 1 wechselt.

Auf der WebGuI und im Display werden weiterhin die Werte ausgegeben, aber über MQTT bleibt der letzte Wert hängen als noch alle Inverter available = 2 waren.

(Siehe Fotos)

![IMG_0913](https://github.com/lumapu/ahoy/assets/63048210/5d37d4fd-4c7b-4c7f-ab88-7a60af2dba59)

![IMG_0912](https://github.com/lumapu/ahoy/assets/63048210/f95560c3-7793-4f7f-9e62-d03a6a3e36b0)

![IMG_0911](https://github.com/lumapu/ahoy/assets/63048210/b4a76037-a538-4622-8e63-63e87cd92397)

**Comment by teletapi** [comment]
Das ist mir tatsächlich heute Abend ebenfalls aufgefallen.  Ich war aber am überlegen das bis morgen abend noch zu beobachten

**Comment by knickohr** [comment]
Passiert Morgens auch. Nur fällts da weniger auf 😉

![IMG_0914](https://github.com/lumapu/ahoy/assets/63048210/4db4e9f2-c303-43a9-bf88-90b887920006)

**Comment by knickohr** [comment]
Nachtrag :
total/YieldTotal und total/YieldDay werden ebenfalls nicht mehr gesendet 😵

Ich schätze mal, es wird überhaupt kein Wert aus dem Topic total mehr gesendet wenn ein Inverter in den Status available = 1 geht, egal wieviele noch online sind.

Obwohl sich die Werte hier noch fleißig ändern, wird nichts mehr davon über MQTT gesendet 😪

![IMG_0915](https://github.com/lumapu/ahoy/assets/63048210/92c61e7a-fcf8-4265-95a8-6a517df4ea40)

**Comment by knickohr** [comment]
Siehe dazu auch Issue #929 , ähnliches Phänomen 😲

**Comment by MiniOh** [comment]
Ja, kann ich ebenfalls bestätigen.

@lumapu 
Was hat sich denn von der 0.6.10 HMS zur 0.7.3 bzgl. der Total AC und Yield Day Werte, welche per MQTT übermittelt werden, verändert?
Vorher war es so, dass auch noch Werte übermittelt werden, wenn alle Inverter erreichbar waren, aber z.B. einer bereits nicht mehr produziert.

Mit der 0.7.3 werden, wenn nicht alle Inverter produzieren, auch keine Daten mehr übermittelt.
Ist das gewollt, bzw. kannst du das nachvollzielen?

![grafik](https://github.com/lumapu/ahoy/assets/27901554/b5d5a50c-fa8f-4bd6-9fdd-aa2d0f382c68)

**Comment by knickohr** [comment]
Bis 0.6.15 war es noch OK. Ich würde sagen sogar bis 0.7.0.

Development Changes

0.7.3 - 2023-06-09

fix hidden SSID scan #983
improved NRF24 missing message on home screen #981
fix MqTT publishing only updated values #982
0.7.2 - 2023-06-08

fix HMS-800 and HMS-1000 assignments #981
make nrf enabled all the time for ESP8266
fix menu item active highlight for 'API' and 'Doku'
fix MqTT totals issue #927, #980
reduce maximum number of inverters to 4 for ESP8266, increase to 16 for ESP32
0.7.1 - 2023-06-05

enabled power limit control for HMS / HMT devices
changed NRF24 lib version back to 1.4.5 because of compile problems for EPS8266
0.7.0 - 2023-06-04

HMS / HMT support for ESP32 devices

**Comment by lumapu** [comment]
ich glaube der Fehler liegt einfach an der Abfrage, neu ist der Teil mit `mSendTotals = false`. Die Abfrage dafür müsste lauten `isAvail()`

https://github.com/lumapu/ahoy/blob/development03/src/publisher/pubMqttIvData.h#L122-L126

**Comment by knickohr** [comment]
Ahhh, verstehe 😲 Dann ist das erst durch Issue #982 aufgekommen. Klar, bis dahin wurden ja alle Daten raus gedonnert bis auch der letzte WR offline war.

Schnell fixen 😉

**Comment by lumapu** [comment]
oh da stand 'schnell fixen' - bin jetzt dran

**Comment by knickohr** [comment]
Noch nicht fertig ? 🤪

15 Minuten früher und ich hätte es noch gleich testen können 🙉🙈🙊

**Comment by knickohr** [comment]
Teilweise gefixed 😉
 YieldDay bleibt immer noch hängen und ich schätze YieldTotal auch. Wahrscheinlich das gleiche Problem. 
 
Ahhh, Stop, langsam 😲

Die Werte gehen sogar auf Null, ich denke wir haben das gefixed ? 🤔

![IMG_0924](https://github.com/lumapu/ahoy/assets/63048210/f7bd4d56-71e3-4a9a-9da8-f262663fe2d7)

Die Inverter sind noch im Status 1 und auf dem Display erscheinen noch die Werte. Nein, ich habe keinen der 3 Optionen ausgewählt.

![IMG_0925](https://github.com/lumapu/ahoy/assets/63048210/ba28c6cf-21aa-46b6-9269-e53a6af3c890)

**Comment by knickohr** [comment]
Jepp, jetzt kommt auch das YieldDay und YieldTotal wieder rüber 👍

Nur leider rechnet er die Summe noch falsch zusammen ☹️ Siehe Issue #929 .  Er summiert nur die der noch online Inverter. Komischerweise macht es das WebGUI aber richtig 🫣

edit :  Nein, Stop, alles zurück. Er sendet jetzt schon wieder eine Null bei YieldDay 😢

![IMG_0934](https://github.com/lumapu/ahoy/assets/63048210/d2afa145-bd15-40a9-ba22-6a6c8408c58c)

Es ging, solange ein Inverter noch online war. Jetzt wo sie alle im Status 1 sind, geht der Wert wieder auf Null.

**Comment by knickohr** [comment]
Ich glaube wir machen hier zu, der P_AC funktioniert ja, alles weitere in den anderen Issues 😉
