### ISSUE TITLE
HM-800 has 4 connectable panels that can be plugged in but only two are configurable

### ISSUE THREAD

**Issue by mmattel** [lumapu/ahoy#988]
The HM-800 has 4 connections available for solar panels but the config section only shows 2, see screenshot below.

![HM800](https://github.com/lumapu/ahoy/assets/3321281/b861fac9-5e1a-4e6a-8e58-91c92dda9646)

As possible solution, you may want to make the number of connectable panels selectable.

**Comment by kiu77** [comment]
This is wrong. The HM-800 has 2 and only and exactly 2 panel connections.
There is no need for a configurable # of panels.

**Comment by mmattel** [comment]
Sorry you are right, mixed it up with another one 🤦‍♂️
