### ISSUE TITLE
ota wechsel von 0.4.23 auf 0.4.24 Einstellungen/Ordner mqtt

### ISSUE THREAD

**Issue by crunchip77** [lumapu/ahoy#99]
habe soeben per https://github.com/grindylow/ahoy/actions die .24 aufgespielt, nachdem der wemos rebootet hatte sind die Einstellungen teils verschwunden bzw verstellt, sowie auch im Gerätenamen der erste Buchstabe fehlt. 
so sieht es aktuell aus
![grafik](https://user-images.githubusercontent.com/41550245/178234650-26c04355-fa9d-4cd5-9966-4a24fa550af0.png)
EDIT
Wenn ich es richtig gelesen habe ist das so korrekt, das man die Daten erneut eingeben muss
zuzücklich die Frage, woher der Ordner homeassistant kommt/dient?

![grafik](https://user-images.githubusercontent.com/41550245/178238109-18d01213-f4f5-41af-8edb-c260c024e141.png)

**Comment by KG3RK3N** [comment]
@crunchip77
Zu deiner Frage woher und wofür der Home Assistant Ordner ist #85

**Comment by crunchip77** [comment]
@KG3RK3N ah ok danke, das hatte ich nicht gelesen

**Comment by stefan123t** [comment]
Ja die Änderung mit der [WiFi Passwort Länge](https://github.com/grindylow/ahoy/pull/98/commits/6c22ff6fb6277baa136e6e5d398eaf9611d954cc) und das Feature für den [MQTT DNS Namen](https://github.com/grindylow/ahoy/pull/98/commits/35e1ff1e17ae8a6c9e9a051698eec7ad0d32e77d) siehe #88 erzwingen eine Anpassung der EEPROM Settings Struktur (siehe defines.h). Daher muss man leider auch alle Settings erneut eintragen.
Das habe ich auch wie in #95 gewünscht im [Changelog](https://github.com/grindylow/ahoy/blob/main/tools/esp8266/README.md) mit (*) EEPROM Change vermerkt.
In #94 diskutieren wir ob das eventuell mit dem SPIFFS Filesystem anstelle der EEPROM Bibliothek evtl. zu vermeiden ist.
Aber dann müssen wir viele weitere Plausibilitätschecks einbauen und einiges an Code umstellen.

**Comment by crunchip77** [comment]
@stefan123t auch dir danke für die ausführliche Erklärung, somit kann eigentlich das issue geschlossen werden.
Da ich mit der Materie nicht so bewandert bin, weiss ich nicht in wie fern bekannt/bug mit mqtt. 
Folgende Situation,
hatte den iobroker neu aufgesetzt, daher war die Instanz für ne gewisse Zeit nicht verfügbar, entsprechend bestand keine Verbindung zwischen iobroker und ahoy. Diesen musst ich manuell rebooten, damit er sich wieder verbindet. Heute war die mqtt Verbindung auch einmal unterbrochen (Grund nicht bekannt bzw wlan Problem schließe ich aus) und musste den wemos rebooten.

**Comment by stefan123t** [comment]
Also der erste Buchstabe Deines Wechselrichters ist definitiv ans Ende Deines Passworts gekommen, siehe PR #98 :grin: !

Das Problem dass sich der MQTT PubSubClient manchmal nicht mehr mit dem MQTT Broker verbindet bzw. keine Daten mehr ankommen ist bekannt und wurde in #68 behandelt. Sollte es immer noch ein Problem geben bitte ein neues Issue mit entsprechenden Debug Logs aufmachen.

**Comment by stefan123t** [comment]
@crunchip77 das Problem mit den verschobenen Konfigdaten ist hinreichend klar. Kannst Du das Issue schließen ?

**Comment by crunchip77** [comment]
Mach ich, bei erneutem mqtt Problem werd ich ein neues erstellen.
