### ISSUE TITLE
[Bug] MQTT uptime value overflow

### ISSUE THREAD

**Issue by gone-for-coding** [lumapu/ahoy#990]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT: IP, Port, ansonsten default.

### Debug Serial Log output

```shell
22:29:52 W: Time not set or it is night time, therefore no communication to the inverter!
22:30:22 W: Time not set or it is night time, therefore no communication to the inverter!
22:30:52 W: Time not set or it is night time, therefore no communication to the inverter!
22:31:22 W: Time not set or it is night time, therefore no communication to the inverter!
```

### Error description

Der Uptime-Wert in den MQTT Nachrichten scheint einen overflow zu haben.
Der letzte Wert nach ~49,7 Tagen ist 4294909, eine Minute später geht es mit exakt 1 wieder los.

Im Webinterface steht die richtige Zeit:
 Uptime: 51 Days, 10:44:08
ESP-Time: 13.6.2023, 22:31:50 

Scheinbar liegt der Fehler nur im MQTT, da im Webinterface alles korrekt angezeigt wird.

**Comment by gone-for-coding** [comment]
Das Problem scheint hier zu sein: https://github.com/lumapu/ahoy/blob/dbb352801e9076f50679efd0a7f432b9fa34dbd4/src/publisher/pubMqtt.h#LL122C14-L122C14

millis läuft über. Siehe auch hier: https://forum.arduino.cc/t/how-to-test-millis-rollover-on-esp32/927524

**Comment by rmayergfx** [comment]
@lumapu 
Bitte eine Funktion einbauen das man wenn nur Solar benutzt z.b. um Mitternacht oder besser frei definierte Uhrzeit ein Reboot stattfindet oder der Wert der Variable genullt wird. Alternativ wie im Link beschrieben die Function umbauen.

**Comment by lumapu** [comment]
wir haben schon einen `mUptime`-Counter. Den habe ich jetzt verknüpft - jetzt läuft der Zähler erst nach 47900 Tagen (~130 Jahre) über.
