### ISSUE TITLE
[Bug] kein Datenaustausch mehr möglich seit neueren Versionen: Datenrate schaltet auf 2 MBps, nachdem mit 250 kBps gestartet wurde

### ISSUE THREAD

**Issue by ralfsfb** [lumapu/ahoy#991]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

Webinstaller

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

 siehe beigefügte Sceenshots

### Debug Serial Log output

```shell
.
```

### Error description

In früheren  Versionen konnten ganz normal Daten mit den Wechselrichtern ausgetauscht werden, seit den neueren Versionen wird kurz nach dem Neustart eine Datenrate von 250 kBps angezeigt und wechselt dann nach 2 MBps, wodurch kein Datenaustausch mehr möglich ist. Um Fehler in der Konfiguration auszuschließen, habe ich den Webinstaller verwendet.
Was kann ich noch versuchen, um auch aktuelle Versionen nutzen zu können?
Besten Dank für eure Ideen im Voraus sendet
ralf
![Screenshot 2023-06-14 134152](https://github.com/lumapu/ahoy/assets/127597967/f345ed44-c398-4076-b252-d1e102f38c15)
![Screenshot 2023-06-14 135942](https://github.com/lumapu/ahoy/assets/127597967/901b01c5-35d4-4120-929d-1a4f7c607150)
![Screenshot 2023-06-14 135958](https://github.com/lumapu/ahoy/assets/127597967/28e18668-d375-4fb0-9893-ea49ce7603d7)

![Screenshot 2023-06-14 134231](https://github.com/lumapu/ahoy/assets/127597967/fa3a6547-3cf4-4fec-b508-c2bcf7a1b6f8)

**Comment by fsck-block** [comment]
Ich habe bei mir auch diesen Effekt.
Nach dem ersten Senden von Daten wechselt die Datenrate von 250 kbps auf 2M bps.
Um genauer zu sein in `HmRadio::sendPacket` nach aufruf von ` mNrf24.stopListening();` wechselt die Datenrate auf 2M bps.
Habe schon unterschiedliche esp8266 Module probiert. Allerdings am gleichen nrf24l01+ Modul.
Bisher habe ich das auf die HW geschoben, aber wenn andere das Problem auch haben ...

**Comment by rmayergfx** [comment]
Kann auch am NRF24l01+ Modul liegen.

**Comment by ralfsfb** [comment]
> Kann auch am NRF24l01+ Modul liegen.

Ist natürlich möglich, doch bei früheren Versionen hat die selbe Hardware gut funktioniert und schaltet inzwischen immer wieder auf 2 Mbps

**Comment by rmayergfx** [comment]
Es soll durchaus auch vorkommen das ein Modul defekt geht und zufälligerweise genau mit dem Update. Das hat nichts mit dem Update an sich zu tun, das ist Murphy. Daher würde ich erst einmal ein anderes Modul ausprobieren und genau prüfen das die Verkabelung passt und keinen Wackler hat. Elko ist ja schon verbaut, vielleicht auch noch mal ein anderes USB Kabel und Netzteil ausprobieren, nicht das es noch Probleme mit der Stromversorgung generell gibt.

**Comment by fsck-block** [comment]
Ich habe mal mein NRF24l01+ Modul getauscht und der Fehler war weg.
Lag' wohl doch an am Modul

**Comment by lumapu** [comment]
jetzt haben wir noch einen Issue mit gleichem Problem #1149
