### ISSUE TITLE
Wemos D1 Mini ESP32 und NRF verbinden

### ISSUE THREAD

**Issue by dtuuser** [lumapu/ahoy#992]
Hallo zusammen,

habe mir zum Testen einen Wemos D1 Mini ESP32 geholt. Leider ein Mini ESP32. Finde keine Verdrahtung dazu. 
Kann hier vielleicht jemand helfen?

Gruß

**Comment by dknubben** [comment]
Wo liegt Dein Problem?
Die Verdrahtung ist doch weitgehend frei wählbar. Ich habe einen Wemos D1 Mini ESP32 wie im Bild angeschlossen.
Das 2. Bild zeigt das Pinout des Moduls.
![GPIO_Setup_W32_mini](https://github.com/lumapu/ahoy/assets/485594/d117f38f-0d43-411a-aa91-bf6557d3ccc6)
![D1_mini_ESP32_pinout](https://github.com/lumapu/ahoy/assets/485594/7fdf3199-96cc-409d-b65f-a0378978fb02)

**Comment by rmayergfx** [comment]
> Hallo zusammen,
> 
> habe mir zum Testen einen Wemos D1 Mini ESP32 geholt. Leider ein Mini ESP32. Finde keine Verdrahtung dazu. Kann hier vielleicht jemand helfen?
> 
> Gruß

Was heist hier leider? Ein ESP32 ist doch besser als ein ESP8266 was die Leistung betrifft.
https://smarthome-blogger.de/blog/esp32-projekte/esp32-vs-esp8266

Preislich ist der Unterschied jetzt auch nicht so groß.

Was ich aber leider immer noch nicht verstehen kann ist warum man in Gottes Namen sich nicht einfach an die Empfehlungen des Entwicklers hält und bereits getestete und funktionierende Boards kauft. Spart Zeit und Geld und erleichtert den Support!
Da teilt einem der Entwickler schon mit was man kaufen kann https://ahoydtu.de/getting_started/ und dann kommen immer wieder Leute um die Ecke die Unterstützung für ein anderes Board haben möchten.  Warum kauft man sich so etwas wenn man nicht weiß wie das ganze funktioniert?

**Comment by dtuuser** [comment]
@dknubben 
Danke für die Konfig. Hat nach der Verdrahtung auf Anhieb geklappt. Topp

@rmayergfx
Ich nutze den USB Ausgang eines Accesspoints mit einem Y Kabel für eine USB Kamera und einen Wemos. Bei der USB Buchse vom Wemos habe ich nur Masse und die 5 Volt angeschlossen.
Diesen Wemos tausche ich gegen den ESP32 aus. Ich habe mich für den ESP32 Mini entschieden, da er angeblich weniger Strom als ein normaler ESP32 verbraucht.
Und ich jedes mA für die Kamera benötige.
