### ISSUE TITLE
Documentation: Looking for a PCB for Wemos D1 mini, nRF24L01+, Nokia display

### ISSUE THREAD

**Issue by TomTom101** [lumapu/ahoy#997]
## Hardware
  * [x] ESP8266

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [x] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode

### Antenna:
* [x] circuit board

### Power Stabilization:
* [x]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module

Ordering a single PCB board to be etched is either costly or when ordered in China takes forever and is hardly economical.

Does anyone have a tip where to get one for max €10 incl. shipping? 

Alternatively, would we find enough users to make a bulk order?

**Comment by ghost** [comment]
Easy,
https://shop.blinkyparts.com/en/OpenDTU-Your-evaluation-for-your-balcony-solar-system/blink237542

Regards

**Comment by CBFOUR** [comment]
Jepp, > German Area
https://www.makershop.de/?s=esp&post_type=product
Cheers

**Comment by TomTom101** [comment]
Thanks, but I am looking for a PCB only, no components or anything else! Just this: https://github.com/lumapu/ahoy/blob/main/tools/pcb-nokia5110/PCB-V1.jpg

**Comment by lumapu** [comment]
maybe you should ask in our Discord channel. Otherwise it's not that hard to use a breadboard for that.

**Comment by stefan123t** [comment]
@TomTom101 is this still relevant or can we close this issue ?
