### ISSUE TITLE
Hoymiles HM 1500 keine Verbindung

### ISSUE THREAD

**Issue by graueresel** [lumapu/ahoy#999]
Hallo,
soweit ist alles Super erklärt und habe es genauso gemacht. Bei mir sind keine Live Daten zu sehen und das Limit kann ich auch nicht einstellen. Die Ahoy DTU ist in der Fritzbox zu sehen und ich kann von dort auch den Wechselrichter erreichen. Was mache ich Falsch? Vielleicht kann mir jemand helfen.

 
![grafik](https://github.com/lumapu/ahoy/assets/137093510/45198c3e-f1ff-4df8-b011-7f7ca36ebcd6)

![grafik](https://github.com/lumapu/ahoy/assets/137093510/36267372-7b13-4664-895c-4c0c55d34f58)

## Hardware
  * [x] ESP8266
  * [ ] ESP32
  * [ ] Raspberry Pi

Modelname: ______
Retailer URL: ______

### nRF24L01+ Module
* [ ] nRF24L01+ you verified this is a **Plus model** capable of the required 256kBit/s mode
* [ ] **square dot** indicates original Nordic Semicon chip 
* [ ] **round dot** indicates copy-cat / counterfeit SI labs chip

### Antenna:
* [x ] circuit board
* [ ] external antenna (SMA)

### Power Stabilization:
* [ ]  100uF Electrolytic Capacitor 
connected between +3.3V and GND (Pin 1 & 2) of the NRF Module
* [ ] Voltage stabilizing motherboard

### Version / Git SHA: 
Version: _._.__
Github Hash: _______

### Build & Flash Method:
* [x] AhoyDTU Webinstaller
* [ ] VSCode - Platform IO
* [ ] Arduino
* [ ] ESP Tools

### Debugging:
* [ ] USB Serial Log (attached)
* [ ] Setup settings (use our templates ... to be added)

**Comment by rmayergfx** [comment]
Solange AhoyDTU keine Verbindung zum Wechselrichter hat kann man natürlich auch nichts einstellen. Wurde die Seriennummer richtig in der Konfiguration eingetragen? Sind die IRQ richtig definiert und angeschlossen? Stehen alle LED auf off? Welche Ahoy Version ist installiert ? Bitte mal Screenshots der Settings posten und die Seriennummer nach der 3ten stelle schwärzen!
Welches ESP8266 wurde gekauft, dito nRF24L01+

**Comment by graueresel** [comment]
Die Seriennummer passt, dass habe ich geprüft.

![grafik](https://github.com/lumapu/ahoy/assets/137093510/64e7fa44-530a-4097-9a35-70fb0e8f24b0)
![grafik](https://github.com/lumapu/ahoy/assets/137093510/b03cc0e1-3de2-44b9-94fd-d381a0b5a539)
![grafik](https://github.com/lumapu/ahoy/assets/137093510/e2fad746-0962-4a4e-bdef-941e6c4438fa)
![grafik](https://github.com/lumapu/ahoy/assets/137093510/c9f1cb7b-b821-4ae1-9a4f-2294757593ab)
![grafik](https://github.com/lumapu/ahoy/assets/137093510/3ab78676-098f-483a-b5a5-f98f1837bce6)

**Comment by graueresel** [comment]
Ich hoffe das passt soweit von dern Info,

**Comment by mroenne2022** [comment]
Meines Erachtens müssen die beiden Schalter für LED0 und LED1 auf off gestellt werden, überschneiden sich ja mit dem IRQ (GPIO0). Dann läuft es sehr warscheinlich. 

Weiterhin musst du mal direkt ggf mit Lupe auf den Chip vom NRF Modul gucken ob es wirklich ein "+" Modul ist,  das kann man so auf der Abbildung nicht 100pro sehen.

**Comment by graueresel** [comment]
ICh habe mal die LEDs wie beschrieben auf Off gestellt.
Die blaue LED ist nun nicht mehr dauerhaft an und blinkt immer wieder mal.

![grafik](https://github.com/lumapu/ahoy/assets/137093510/136367d2-7131-406e-9b87-2640c9364dc3)

**Comment by graueresel** [comment]
![IMG_0176](https://github.com/lumapu/ahoy/assets/137093510/a4569477-7def-4a8a-a850-802e5be04222)
![IMG_0177](https://github.com/lumapu/ahoy/assets/137093510/c58c9448-a8c2-46d0-bd71-816b64ae0426)
![IMG_0177](https://github.com/lumapu/ahoy/assets/137093510/e7ab8c4f-9811-4a6b-b8f5-d705988ec07d)
![IMG_0176](https://github.com/lumapu/ahoy/assets/137093510/30002a38-4475-42a6-a98e-eed0582c8d1d)

**Comment by mroenne2022** [comment]
Die LED wird alle 30sec blinken weil er dann versucht den WR zu erreichen. 
In Kürze ist Dunkelheit und Sense für heute, dann erreicht man den WR nicht. 
Tip: NRF Modul angucken ob ein + 
Entfernung zum WR?
ggf Sendeleistung etwas erhöhen zum Test. 
Netzteil stark genug für Versorgung?

**Comment by graueresel** [comment]
WWenn das blinken richtig ist, dann warte ich mal ab und melde mich Morgen wieder. Aktuell kommen noch ca. 80 W vom Dach.
Habe gerade nochmal ein stärkeres Netzteil angehängt. Entfernung zum Wechselrichter max. 5m durch eine Außenwand.

**Comment by mroenne2022** [comment]
Woher weißt du das 80W kommen?
Siehst du nun bei LiveDaten etwas ?
Das blinken ist richtig, aber das macht der esp sowieso, auch wenn kein WR in der Nähe ist. Das ist ja so eingestellt und sagt nichts aus. 
Entfernung sollte null Problem sein.

**Comment by graueresel** [comment]
![grafik](https://github.com/lumapu/ahoy/assets/137093510/cff3d2a8-8cc0-4cf0-9929-c038f46a1ece)
 
NRF +

**Comment by mroenne2022** [comment]
Das kann niemand erkennen, du musst mit Lupe auf den schwarzen Cip kontrollieren ob ein + dahinter steht. Ich befürchte das es keines mit + ist

**Comment by graueresel** [comment]
Steht auch auf der Platine so

**Comment by mroenne2022** [comment]
Ah okay, dann ist das richtig!!!

**Comment by graueresel** [comment]
Langsam kommt nichts mehr vom Dach. Dann müssen wir morgen weitermachen

**Comment by graueresel** [comment]
Die Leistung vom Dach wird mit Shelly gemessen

**Comment by mroenne2022** [comment]
Ah Okay - mit Shelly. Grundsätzlich muss der WR erreicht werden , muss in der Übersicht bei Systeminfo auch so sichtbar sein . Wenn das (morgen)  nicht der Fall ist , dann kommen keine Daten. Das ist die Grundvorrausetzung, wenn nichts kommt alles halt nochmals prüfen , PinOut,Kabelverbindungen ...usw

**Comment by graueresel** [comment]
Okay, das machen wir so

**Comment by mroenne2022** [comment]
Ich kann da nichts machen, hab eigentlich entsprechend die Tips angesprochen, akribisch kontrollieren musst du das morgen. Ich drücke die Daumen. Ich hab mal schnell eine Ahoy angeschlossen, hab sonst OpenDTU am laufen. Wemos D1 Mini und NRF+ , 0.6.9 ! So muss es aussehen !
![NRF](https://github.com/lumapu/ahoy/assets/114778920/7d19a82e-8406-44b4-9cac-306394468f14)
![Ahoy](https://github.com/lumapu/ahoy/assets/114778920/6863edc4-acb7-402b-b237-e52065931342)

**Comment by graueresel** [comment]
Vielen Dank für die Hilfe und melde mich wieder

 

Von: mroenne2022 ***@***.***> 
Gesendet: Montag, 19. Juni 2023 21:13
An: lumapu/ahoy ***@***.***>
Cc: graueresel ***@***.***>; Author ***@***.***>
Betreff: Re: [lumapu/ahoy] Hoymiles HM 1500 keine Verbindung (Issue #999)

 

Ich kann da nichts machen, hab eigentlich entsprechend die Tips angesprochen, akribisch kontrollieren musst du das morgen. Ich drücke die Daumen. Ich glaube der Punkt LED prirority muss auch auf off, bin da nicht so sicher, ggf kann das jemand anders bestätigen. Ich hab zur Zeit OpenDTU bei mir in Betrieb, daher hab ich keinen Screenshot parat von Ahoy

**Comment by graueresel** [comment]
Ich habe gerade noch die vorbeschriebenen Einstellungen geprüft und eingestellt. Nach kurzer Zeit mit etwas höherer Sendeleistung kommen nun die LIVE Daten an. Vielen Dank für die schnelle und kompetente Hilfe.

**Comment by mroenne2022** [comment]
@graueresel : Glückwunsch 👍😃

**Comment by graueresel** [comment]
Hallo, ich habe heute mal die Leistungsbegrenzung ausprobiert. Leider kann ich kein Limit einstellen und bekomme folgende Meldung. Vielleicht kann mir jemand helfen?

![grafik](https://github.com/lumapu/ahoy/assets/137093510/b4e7cc79-7c15-46c1-af91-65f25c799398)

**Comment by lumapu** [comment]
@graueresel die Fehlermeldung sagt aus, dass der Wechselrichter das Powerlimit nicht akzeptiert hat. Deine Uptime ist sehr kurz, funktioniert die Funkverbindung überhaupt zum Wechselrichter? Sehr interessant wäre natürlich auch er Output der Konsole weiter oben. Dafür wäre es noch hilfreich die Einstellung `Serial Debug` unter `System Settings` zu aktivieren.

**Comment by graueresel** [comment]
Hallo, danke für die Hilfe. Jetzt funktioniert auch die Einstellung des Limit.
